const fs = require('fs');
const path = require('path');
const { withDangerousMod } = require('expo/config-plugins');

// @react-native-kakao pins the native Kakao SDK to an old release (2.22.0 as of
// wrapper 2.4.6). Kakao's auth servers inspect the calling SDK and reject stale
// ones with KOE033 ("지원하지 않는 SDK를 사용해 인가 코드를 요청한 경우"), so the pin
// is raised to the newest release available.
//
// Ceiling: CocoaPods only carries up to 2.22.7 — Kakao's 2.24+ releases (2.28.0
// is current on GitHub) ship via Swift Package Manager only. If KOE033 comes back
// at 2.22.7, moving the iOS dependency to SPM is the next lever.
//
// The library supports this: its podspecs read the $KakaoCoreSDKVersion /
// $KakaoUserSDKVersion Podfile globals when defined. We inject them here rather
// than editing ios/Podfile by hand because ios/ is gitignored and regenerated by
// every `expo prebuild`.
//
// Android note: the Gradle side reads `project.ext.RNCKakaoSdkVersions` (set by
// the library's package-json.gradle from its own package.json), so raising the
// Android pin needs a separate hook — do that when Android builds start.
const withKakaoSdkVersion = (config, { version }) =>
  withDangerousMod(config, [
    'ios',
    (cfg) => {
      const podfile = path.join(cfg.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfile, 'utf8');
      // prebuild reuses an existing ios/, so REWRITE a previous injection rather
      // than skipping — otherwise a version bump here never reaches the Podfile.
      const stripped = contents.replace(/^\$Kakao(Core|User)SDKVersion = '[^']*'\n/gm, '').replace(/^\n+/, '');
      fs.writeFileSync(
        podfile,
        `$KakaoCoreSDKVersion = '${version}'\n$KakaoUserSDKVersion = '${version}'\n\n${stripped}`,
      );
      return cfg;
    },
  ]);

module.exports = withKakaoSdkVersion;
