from _ctx_common_b import run
run("er-shock", {
 "circulation": {"scenes": {0: {"en": "Circulation: extremities cool; cap refill 4 sec."},
   1: {"en": "Her circulation looks poor — hands are cool and cap refill is delayed."},
   2: {"en": "Your peripheral circulation is compromised, with delayed capillary refill."}}},
 "volume-depleted": {"scenes": {0: {"en": "Pt volume-depleted d/t vomiting x 2 days."}}},
 "ready": {"scenes": {1: {"en": "I've got fluids running and blood ready on standby."},
   2: {"en": "Two units of PRBCs are crossmatched and ready."}}},
 "infection": {"scenes": {0: {"en": "Febrile, tachycardic, hypotensive; suspected infection, source unknown."},
   1: {"en": "She's febrile and tachycardic with low pressure — I'm concerned for infection, maybe sepsis."},
   2: {"en": "You're febrile, tachycardic, and hypotensive, with a suspected infection.",
       "fix": "You have a fever, your heart is racing, and your pressure is low. It may be an infection."}}},
 "output": {"scenes": {0: {"en": "Urine output 20 mL/hr over the last 2 hrs."},
   2: {"en": "Your urine output is 20 mL an hour."}}},
 "hold": {"scenes": {0: {"en": "Norepi 8 mcg/min via R IJ; MAP holding at 66."},
   2: {"en": "Norepi is at 8 mcg/min, titrating to hold your MAP above 65."}}},
 "cause": {"scenes": {0: {"en": "Cause of hypotension unclear; work-up in progress."},
   1: {"en": "Still no clear cause — labs and ECG are pending."},
   2: {"en": "The cause of your hypotension is undetermined."}}},
 "norepinephrine": {"word": "norepi",
   "scenes": {2: {"en": "She's fluid-refractory, so we're starting norepi, a vasopressor."}}},
 "notify": {"word": "notified", "ko": "알렸다",
   "scenes": {2: {"en": "I've notified the PERT per the massive PE pathway."}}},
 "drain": {"scenes": {0: {"en": "Tamponade physiology on echo; pericardial drainage planned."},
   1: {"en": "Echo shows tamponade — setting up to drain it by pericardiocentesis."},
   2: {"en": "She has tamponade physiology, so we need emergent pericardial drainage."}}},
 "activate": {"scenes": {1: {"en": "MTP is activated, and the first cooler is on its way."}}},
 "precaution": {"scenes": {1: {"en": "Spinal precautions on: C-spine immobilized, log-rolling only."},
   2: {"en": "Your C-spine is immobilized under spinal precautions, so no range of motion."}}},
})
