from _ctx_common_b import run
run("er-procedures", {
 "date of birth": {"scenes": {1: {"en": "Can you confirm the name and date of birth on this wristband with me?"},
   2: {"en": "You're John Smith, date of birth March 4th, 1960, right?", "fix": "Please tell me your name and your birthday, so I can match your wristband."}}},
 "start": {"scenes": {2: {"en": "I'm going to start cannulation of your forearm now."}}},
 "specimen": {"scenes": {1: {"en": "Clean-catch UA specimen collected and sent."}}},
 "labs": {"scenes": {0: {"en": "I drew labs for his abdominal pain: CBC, BMP, and lipase."}}},
 "vein": {"scenes": {1: {"en": "Poor veins; warm compress applied to L arm prior to PIV attempt."}}},
 "brave": {"scenes": {0: {"en": "All done! You were so brave!"},
   1: {"en": "Pt brave throughout; tolerated venipuncture well."},
   2: {"en": "You were brave and tolerated the venipuncture well.", "fix": "All done, and you held so still. That took real courage!"}}},
 "metformin": {"scenes": {2: {"en": "Any history of CKD or biguanide use, such as metformin?", "fix": "Do you have any kidney trouble? Do you take a pill for diabetes?"}}},
 "contamination": {"scenes": {0: {"en": "That culture looks like contamination, not true bacteremia."},
   2: {"en": "Your blood culture shows contamination with skin flora."}}},
 "allergy": {"scenes": {1: {"en": "Allergy: PCN (rash)."}}},
 "verify": {"word": "double-check", "ko": "이중 확인하다",
   "why": "숫자·기호(ABO/Rh, unit number)로 말하는 확인은 의료진끼리의 말이에요. 환자에게는 두 사람이 확인했고 정확히 맞다는 결론을 말해요.",
   "scenes": {0: {"en": "Let's double-check together — unit number, ABO/Rh, and expiration all match."},
     1: {"en": "Double-check done at bedside by two RNs; product matches pt ID."},
     2: {"en": "Your ABO/Rh and unit number have been double-checked.", "fix": "Two of us checked, and this blood matches you exactly."}}},
 "NGT": {"scenes": {0: {"en": "The NGT is in — can we get an X-ray to confirm placement?"}}},
 "bedside": {"scenes": {2: {"en": "Per policy, specimens are labeled at the bedside in the patient's presence."}}},
 "monitor": {"scenes": {2: {"en": "I'm watching for ectopy from the guidewire on the monitor."}}},
 "epinephrine": {"scenes": {0: {"en": "Epinephrine 0.5 IM going in, lateral thigh, at 14:02."}}},
 "IO": {"scenes": {2: {"en": "We're placing an IO line in your proximal tibia."}}},
 "match": {"scenes": {2: {"fix": "Stop — the label says 5 mg, but the order says 0.5. Don't give it."}}},
 "lung": {"scenes": {2: {"en": "Your pneumothorax has resolved, and your lung is re-expanded on the post-procedure film."}}},
 "vitals": {"scenes": {0: {"en": "Vitals just now: BP 90 over 56, heart rate 120, after unit two."},
   1: {"en": "Vitals q5min during MTP; see flowsheet."},
   2: {"en": "Um, I think the vitals might be kind of low-ish?", "fix": "BP is 82 over 50 and heart rate 128 — worse than five minutes ago."}}},
})
