from _ctx_common_b import run
run("er-stroke", {
 "slurred": {"scenes": {2: {"en": "You are presenting with slurred speech and facial palsy."}}},
 "normal": {"scenes": {1: {"en": "Per his wife, he was completely normal at 08:15."},
   2: {"en": "At what hour did his premorbid baseline cease to be normal?",
       "fix": "Think back — what time did you last see him acting like himself?"}}},
 "drink": {"scenes": {0: {"en": "Your mouth feels dry, I know. Nothing to drink until we test your swallow."},
   1: {"en": "NPO — no food or drink until swallow screen passed."},
   2: {"en": "You are not permitted to drink any fluids.",
       "fix": "Please wait on drinks for now. I need to check your swallowing first, then I'll get you water."}}},
 "score": {"scenes": {0: {"en": "NIHSS score is 12: right arm drift, aphasia, left gaze preference."},
   1: {"en": "Baseline NIHSS score 12 at 09:10."}, 2: {"en": "Your NIHSS score is 12, with a motor arm score of 3 and an aphasia score of 2."}}},
 "stroke": {"scenes": {1: {"en": "Pt c/o dizziness, diplopia x 1 hr, unable to ambulate without assist; r/o stroke."},
   2: {"en": "I'm afraid you're having a cerebellar stroke and may deteriorate rapidly."}}},
 "wake": {"scenes": {0: {"en": "When did you wake up this morning, and when did you go to bed?"},
   1: {"en": "Wake-up stroke: last known well 22:30 at bedtime; found with weakness on waking at 06:00."},
   2: {"en": "State the timestamp of your last intact moment prior to wake-up."}}},
 "safe": {"scenes": {1: {"en": "I'm screening him for bleeding risks to see if tPA is safe."},
   2: {"en": "Please confirm the absence of contraindications so tPA is safe."}}},
 "interpreter": {"scenes": {2: {"en": "Please remain until an interpreter becomes available for linguistic support."}}},
 "headache": {"scenes": {2: {"en": "Report any exacerbation of your headache."}}},
 "stay": {"scenes": {0: {"en": "Please stay with us a little longer while we run tests."},
   1: {"en": "TIA, symptoms resolved. She wants to leave, but I'd like her to stay for workup."},
   2: {"en": "Staying is recommended per protocol, and discharge is not advised at this time."}}},
 "consent": {"scenes": {0: {"en": "The doctor will explain everything, then we'll need your consent."}}},
 "stop": {"scenes": {2: {"en": "The infusion has been stopped pending reassessment.",
       "fix": "I've stopped the medicine to be safe, and we're getting a scan right away."}}},
 "deterioration": {"scenes": {0: {"en": "NIHSS is up from 12 to 15 — neurological deterioration."},
   1: {"en": "Neurological deterioration: NIHSS went from 12 to 15. Watch him closely."}}},
 "pupil": {"scenes": {2: {"en": "His pupils show anisocoria with impending herniation.",
       "fix": "His pupils are different sizes, which tells us the brain is under pressure. Doctors are coming now."}}},
})
