from _ctx_common import run
run("core-family-er", {
 "visitor": {"scenes": {2: {"en": "Visitors are limited to one per patient in treatment areas."}}},
 "relationship": {"scenes": {1: {"en": "Before I share anything, can I ask what your relationship is to the patient?"}}},
 "explain": {"scenes": {2: {"en": "To explain: labs are pending, turnaround about an hour."}},
   "why": "같은 설명이어도 'labs are pending, turnaround' 같은 인계식 말은 가족에게 벽처럼 들려요. 다시 묻는 가족에게는 질문을 반기고 쉬운 말로 다시 설명하세요."},
 "danger": {"scenes": {0: {"en": "He's not in immediate danger — BP is holding."},
                        1: {"en": "No immediate danger right now — he's stable on the monitor."},
                        2: {"en": "Your dad is not in imminent danger of decompensation.",
                            "fix": "Your dad is not in danger right now — his blood pressure is holding steady."}},
   "why": "decompensation(대상부전) 같은 임상어는 의료진끼리는 정확하지만, 아들에게 '위험'을 말할 때는 알아듣기 어렵고 오히려 불안하게 해요. 지금 안전하다는 것과 그 근거를 쉬운 말로 알려 주세요."},
 "practice": {"scenes": {0: {"en": "Cultural practices: family requests prayer at bedside."},
                          2: {"en": "What religion do you practice?"}}},
 "private": {"scenes": {0: {"en": "Can we use a private room? We need to talk with the Lee family."},
                         2: {"en": "This hallway is private enough — the doctor has bad news.", "fix": "Let's step into a private room where we can talk."}},
   "why": "나쁜 소식 전달의 첫 단계(SPIKES의 Setting)는 조용하고 사적인 곳으로 옮기는 거예요. 복도를 '이 정도면 충분히 private'이라고 넘기고 바로 나쁜 소식을 말하면 가족은 준비 없이 그 자리에서 충격을 받아요."},
 "condition": {"scenes": {0: {"en": "I'm going to call the daughter with an update on her mother's condition."},
                           2: {"en": "Calling to update you on the pt's condition — she is hemodynamically stable."}}},
 "pass away": {"word": "passed away", "ko": "돌아가시다",
   "scenes": {0: {"en": "Pt passed away at 14:32. Family at bedside."}, 2: {"en": "Pt passed away at 2:30. Sign here for his belongings.", "fix": "I'm so sorry — your husband died at 2:30. I'll stay with you."}},
   "why": "아내를 'Pt'라고 부르며 곧바로 서류부터 내미는 말은 차갑게 들려요. 가족에게는 먼저 애도를 전하고, 돌아가셨다는 사실을 분명한 말로 알린 뒤 곁에 있겠다고 하세요."},
 "CPR": {"scenes": {0: {"en": "Continue CPR — pulse check in two minutes."}}},
 "comfort": {"scenes": {2: {"en": "Do you want us to withdraw care and go comfort only?"}}},
 "keepsake": {"scenes": {0: {"en": "Can you bring the keepsake box? The parents want handprints."},
                          2: {"en": "We need to make a keepsake of handprints before transport.",
                              "fix": "When you're ready, we can make handprints as a keepsake — only if you'd like."}}},
})
