package main

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// Chapters are generated, not hand-written, for the same reason the scenarios
// are: there are twenty of them, they must reference ids that actually exist,
// and a new department should extend the learning path without anyone
// remembering to edit a catalog.
//
// Step order inside a chapter follows the topic's curated difficulty, so a
// chapter opens with something a newcomer can carry and closes with the hardest
// thing on that floor.
const stepsPerChapter = 6

// generateCurriculum writes internal/curriculum/catalog_gen.go.
func generateCurriculum(path string) error {
	var b strings.Builder
	b.WriteString(`// Code generated by cmd/gencontent — DO NOT EDIT.
//
// One chapter per elevator floor, ordered by learning difficulty (see
// cmd/gencontent/floors.go). Hand-authored chapters 1–5 live in curriculum.go
// and come first; these continue the path across the rest of the hospital.

package curriculum

var generated = []Chapter{
`)

	floors := append([]Floor(nil), Floors...)
	sort.SliceStable(floors, func(i, j int) bool { return floors[i].Tier < floors[j].Tier })

	for _, fl := range floors {
		steps := chapterSteps(fl)
		if len(steps) == 0 {
			continue // a floor whose banks are missing produces no chapter, not a broken one
		}
		fmt.Fprintf(&b, "\t{Name: %q, Dept: %q, Steps: []Step{\n", fl.Chapter, fl.Where)
		for _, s := range steps {
			fmt.Fprintf(&b, "\t\t{Kind: %q, Name: %q, ScenarioID: %q},\n", s.Kind, s.Name, s.ScenarioID)
		}
		b.WriteString("\t}},\n")
	}
	b.WriteString("}\n")
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

type genStep struct{ Kind, Name, ScenarioID string }

// chapterSteps picks this floor's steps: easiest first, the hardest as the
// chapter test, and one quiz in the middle so the run isn't six dialogues deep.
func chapterSteps(fl Floor) []genStep {
	type cand struct {
		topic Topic
		id    string
		code  string
	}
	var cands []cand
	for _, code := range fl.Depts {
		d, ok := deptByCode(code)
		if !ok {
			continue
		}
		// Variant 0 of each topic — ids run idStart, idStart+1, … in bank order.
		for i, t := range d.Topics {
			cands = append(cands, cand{topic: t, id: fmt.Sprintf("SCN-%s-%05d", d.Code, idStart+i), code: d.Code})
		}
	}
	if len(cands) == 0 {
		return nil
	}
	// Difficulty first; bank order breaks ties so the result is deterministic.
	sort.SliceStable(cands, func(i, j int) bool { return cands[i].topic.Diff < cands[j].topic.Diff })

	n := stepsPerChapter
	if len(cands) < n {
		n = len(cands)
	}
	// Take the easiest n-1 plus the single hardest, so the chapter actually ends
	// on its peak rather than trailing off mid-bank.
	picked := append([]cand(nil), cands[:n-1]...)
	picked = append(picked, cands[len(cands)-1])

	steps := make([]genStep, 0, n+1)
	for i, c := range picked {
		kind := "dlg"
		if !NormalizeAcuityLocal(c.topic.acuityOf()) {
			kind = "event" // a situation that is happening, not a conversation to hold
		}
		if i == len(picked)-1 {
			kind = "boss"
		}
		steps = append(steps, genStep{Kind: kind, Name: c.topic.Title, ScenarioID: c.id})
	}
	// One quiz from the floor's first department, dropped in the middle.
	if d, ok := deptByCode(fl.Depts[0]); ok {
		q := genStep{Kind: "quiz", Name: d.Name + " 용어 점검", ScenarioID: fmt.Sprintf("QZ-%s-%05d", d.Code, idStart)}
		mid := len(steps) / 2
		steps = append(steps[:mid], append([]genStep{q}, steps[mid:]...)...)
	}
	return steps
}

func deptByCode(code string) (Dept, bool) {
	for _, d := range Depts {
		if d.Code == code {
			return d, true
		}
	}
	return Dept{}, false
}

// NormalizeAcuityLocal reports whether an acuity string is the routine case.
// (The domain has the real parser; the generator only needs the yes/no.)
func NormalizeAcuityLocal(a string) bool { return a != "urgent" && a != "critical" }
