package main

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/bingoring/forin/server/internal/curriculum"
)

// The learning path is hand-authored, one file per building, in
// internal/curriculum/authored_*.go. This generator no longer writes it.
//
// It used to: one chapter per floor, six topics picked by difficulty, named after
// the floor. That was cheap and it was wrong in a way nobody could see. Running
// the same mechanical pass over all 29 department banks produces an empty
// curriculum for 14 of them — SIM/LOUNGE/SPD have no patients, so "who are you
// talking to" carries no signal, and ER has seven urgent topics because that is
// what an emergency room is. Curriculum names have to come from a floor's actual
// topics, and once you are reading all ten to name them, assigning them is free.
//
// What survives here is the safety net: a department nobody has authored still
// gets a path, split by difficulty, with an honest name and a warning on stderr.
// The steady state is an empty fallback (R7).
const fallbackBands = 3

// generateCurriculum writes internal/curriculum/catalog_gen.go.
func generateCurriculum(path string) (int, error) {
	covered := curriculum.CoveredDeptCodes()

	// Only departments the lift can actually reach need a curriculum. GEN is a
	// generic ward bank that sits on no floor — its scenarios are reachable from
	// the department sheet and always have been — so an unauthored GEN is not a
	// gap, and warning about it would train people to ignore the warning.
	onAFloor := map[string]bool{}
	for _, fl := range Floors {
		for _, code := range fl.Depts {
			onAFloor[code] = true
		}
	}

	var missing []Dept
	for _, d := range Depts {
		if onAFloor[d.Code] && !covered[d.Code] {
			missing = append(missing, d)
		}
	}
	sort.SliceStable(missing, func(i, j int) bool { return missing[i].Code < missing[j].Code })

	var b strings.Builder
	b.WriteString(`// Code generated by cmd/gencontent — DO NOT EDIT.
//
// The difficulty fallback for departments nobody has authored curricula for yet
// (business-rules R7). Empty means every department bank is covered by
// internal/curriculum/authored_*.go, which is the desired steady state.

package curriculum

var fallback = []Curriculum{
`)
	for _, d := range missing {
		fmt.Fprintf(os.Stderr,
			"WARN curriculum: %s has no authored curricula — using the difficulty fallback. "+
				"Add it to internal/curriculum/authored_*.go.\n", d.Code)
		for i, band := range fallbackSplit(d) {
			fmt.Fprintf(&b, "\t{Key: %q, Name: %q, Building: %q, Floor: %q, Where: %q, Steps: []Step{\n",
				fmt.Sprintf("미배치|%s|band%d", d.Code, i+1),
				fmt.Sprintf("%s %s", d.Name, fallbackBandName(i)),
				"미배치", d.Code, d.Name)
			for j, t := range band {
				kind := "dlg"
				if !NormalizeAcuityLocal(t.acuityOf()) {
					kind = "event"
				}
				if j == len(band)-1 {
					kind = "boss"
				}
				fmt.Fprintf(&b, "\t\t{Kind: %q, Name: %q, ScenarioID: %q},\n",
					kind, t.Title, t.ScenarioID)
			}
			b.WriteString("\t}},\n")
		}
	}
	b.WriteString("}\n")
	return len(missing), os.WriteFile(path, []byte(b.String()), 0o644)
}

func fallbackBandName(i int) string {
	return [fallbackBands]string{"기본", "응용", "고난도"}[i]
}

type fallbackTopic struct {
	Topic
	ScenarioID string
}

// fallbackSplit orders a bank by difficulty and cuts it into three near-equal
// runs. Difficulty only: Acuity and Role are exactly the fields whose distribution
// broke the mechanical rule, so the net does not lean on them.
func fallbackSplit(d Dept) [][]fallbackTopic {
	ts := make([]fallbackTopic, 0, len(d.Topics))
	for i, t := range d.Topics {
		ts = append(ts, fallbackTopic{Topic: t, ScenarioID: fmt.Sprintf("SCN-%s-%05d", d.Code, idStart+i)})
	}
	sort.SliceStable(ts, func(i, j int) bool { return ts[i].Diff < ts[j].Diff })

	out := make([][]fallbackTopic, 0, fallbackBands)
	per := (len(ts) + fallbackBands - 1) / fallbackBands
	for i := 0; i < len(ts); i += per {
		end := i + per
		if end > len(ts) {
			end = len(ts)
		}
		out = append(out, ts[i:end])
	}
	return out
}

// NormalizeAcuityLocal reports whether an acuity string is the routine case.
// (The domain has the real parser; the generator only needs the yes/no.)
func NormalizeAcuityLocal(a string) bool { return a != "urgent" && a != "critical" }
