package main

// Curated clinical topic banks (part 1). Each topic is a real nursing situation;
// the generator multiplies it across patient personas and a difficulty spread.
// To extend: add a topic here (more variety) or a whole Dept entry.
func init() {
	Depts = append(Depts, []Dept{
		{Code: "ER", Name: "응급의료센터", Label: "ER", Color: "#DC2626", Tone: "#FEE2E2", Accent: "#B91C1C", Topics: []Topic{
			{Title: "흉통 트리아지", Tagline: "It feels like an elephant on my chest…", Room: "TRIAGE", Role: "patient", Diff: 2, Brief: "운동 후 흉통 환자를 PQRST로 사정하고 ESI 등급을 정하세요.", Skills: []string{"흉통 PQRST", "심혈관 어휘", "ESI 트리아지"}, Phrases: []string{"Can you describe the chest pain?", "Does it spread to your arm or jaw?", "On a scale of 0 to 10?"}, Goals: []string{"흉통 양상·방사통·동반증상 사정", "STEMI 배제 위해 트리아지"}},
			{Title: "호흡곤란 초기 평가", Tagline: "I can't catch my breath…", Room: "RESUS", Role: "patient", Diff: 3, Brief: "급성 호흡곤란 환자의 기도·호흡·순환을 빠르게 평가하고 안심시키세요.", Skills: []string{"ABC 평가", "SpO2 어휘", "산소 적용 설명"}, Phrases: []string{"When did the breathing get worse?", "I'm putting oxygen on you now.", "Try to take slow breaths with me."}, Goals: []string{"호흡곤란 발생·악화 요인 청취", "산소 적용을 안심시키며 설명"}},
			{Title: "복통 문진", Tagline: "It hurts down here, and it's getting worse.", Room: "EXAM 2", Role: "patient", Diff: 1, Brief: "복통 환자의 위치·양상·동반증상을 OPQRST로 문진하세요.", Skills: []string{"복통 OPQRST", "소화기 어휘"}, Phrases: []string{"Where exactly does it hurt?", "Have you had any nausea or vomiting?", "When did you last eat?"}, Goals: []string{"복통 위치·양상·동반증상 청취", "적색 신호 증상 확인"}},
			{Title: "열성 환자 감염 선별", Tagline: "I've had a fever for three days.", Room: "FAST TRACK", Role: "patient", Diff: 1, Brief: "발열 환자의 감염원·여행력·접촉력을 선별하고 격리 필요성을 판단하세요.", Skills: []string{"감염 선별 어휘", "격리 안내"}, Phrases: []string{"How high has your fever been?", "Any recent travel or sick contacts?", "We may need to place you in isolation."}, Goals: []string{"발열 경과·감염 위험 요인 청취", "격리 필요성 판단·안내"}},
			{Title: "낙상 외상 사정", Tagline: "I slipped and I can't move my wrist.", Room: "TRAUMA BAY #3", Role: "patient", Diff: 2, Brief: "낙상 환자의 손상 부위·기전·신경혈관 상태를 사정하세요.", Skills: []string{"외상 기전 청취", "신경혈관 사정"}, Phrases: []string{"How did you fall?", "Can you wiggle your fingers?", "Does it hurt when I press here?"}, Goals: []string{"손상 기전·부위 청취", "신경혈관 상태 확인"}},
			{Title: "알레르기 반응 대응", Tagline: "My lips are swelling up!", Room: "RESUS BAY #1", Role: "patient", Diff: 3, Brief: "아나필락시스 의심 환자의 노출·증상을 빠르게 확인하고 처치를 설명하세요.", Skills: []string{"알레르기 어휘", "에피네프린 설명"}, Phrases: []string{"What did you eat or take?", "I'm giving you epinephrine now.", "Your throat may feel better soon."}, Goals: []string{"알레르겐 노출·증상 진행 확인", "응급 처치를 안심시키며 설명"}},
			{Title: "주취 환자 진정", Tagline: "I'm fine, leave me alone!", Room: "BAY #5", Role: "patient", Diff: 2, Brief: "흥분한 주취 환자를 안전하게 진정시키고 협조를 얻으세요.", Skills: []string{"디에스컬레이션", "안전 확보"}, Phrases: []string{"I'm here to help you.", "Let's keep everyone safe.", "Can I check your vital signs?"}, Goals: []string{"비폭력적으로 진정 유도", "안전하게 사정 협조 확보"}, Moods: []string{"angry", "anxious"}},
			{Title: "소아 열경련 부모 안내", Tagline: "My baby was shaking — is she okay?", Room: "PEDS CORNER", Role: "parent", Diff: 2, Brief: "열경련을 목격한 보호자를 안심시키고 경과·주의점을 교육하세요.", Skills: []string{"소아 발열 교육", "보호자 안심"}, Phrases: []string{"Febrile seizures are usually not harmful.", "Let's bring the fever down.", "Watch for these warning signs at home."}, Goals: []string{"보호자를 안심시키며 설명", "가정 관찰 포인트 교육"}},
			{Title: "경찰 동행 환자 인계", Tagline: "Officer, what happened here?", Room: "RECEPTION", Role: "colleague", Diff: 2, Brief: "경찰과 함께 온 환자의 상황을 인계받고 사정 우선순위를 정하세요.", Skills: []string{"기관 간 인계", "우선순위 결정"}, Phrases: []string{"Can you tell me what happened?", "Is the patient stable?", "We'll take it from here."}, Goals: []string{"동행자에게 상황 인계 청취", "사정 우선순위 결정"}},
			{Title: "언어 장벽 · 통역 호출", Tagline: "(환자가 영어를 거의 못 함)", Room: "EXAM 1", Role: "patient", Diff: 2, Brief: "영어가 서툰 환자에게 통역 서비스를 안내하고 핵심 증상을 확인하세요.", Skills: []string{"통역 서비스 안내", "쉬운 영어"}, Phrases: []string{"I'll get an interpreter for you.", "Point to where it hurts.", "Are you in pain now?"}, Goals: []string{"통역 연계 안내", "쉬운 표현으로 핵심 증상 확인"}, Moods: []string{"anxious", "worried"}},
		}},
		{Code: "ICU", Name: "중환자실", Label: "ICU", Color: "#7F1D1D", Tone: "#FEE2E2", Accent: "#7F1D1D", Topics: []Topic{
			{Title: "인공호흡기 환자 소통", Tagline: "(환자가 삽관되어 말을 못 함)", Room: "BED 3", Role: "patient", Diff: 2, Brief: "삽관된 환자와 필담·몸짓으로 소통하며 불편을 확인하세요.", Skills: []string{"대체 의사소통", "인공호흡기 어휘"}, Phrases: []string{"Blink once for yes.", "Are you in pain?", "I'll suction to help you breathe."}, Goals: []string{"비언어적 소통으로 요구 파악", "불편·통증 확인"}, Moods: []string{"worried", "anxious"}},
			{Title: "진정 관리 설명", Tagline: "Why is he so sleepy?", Room: "BED 5", Role: "family", Diff: 2, Brief: "보호자에게 진정 수준과 목적을 설명하고 안심시키세요.", Skills: []string{"진정 어휘", "가족 교육"}, Phrases: []string{"We're keeping him lightly sedated.", "It helps him tolerate the ventilator.", "He can still hear you."}, Goals: []string{"진정 목적·수준 설명", "가족을 안심"}},
			{Title: "모니터 알람 해석", Tagline: "The monitor keeps beeping — is that bad?", Room: "BED 2", Role: "family", Diff: 1, Brief: "보호자에게 알람의 의미를 쉽게 설명하고 불안을 낮추세요.", Skills: []string{"모니터 어휘", "불안 완화"}, Phrases: []string{"That alarm just means the sensor moved.", "His numbers are stable.", "I'm watching closely."}, Goals: []string{"알람 의미 쉽게 설명", "불안 완화"}},
			{Title: "Code Blue 콜 응대", Tagline: "Code Blue, bed 4 — go!", Room: "BED 4", Role: "colleague", Diff: 3, Brief: "심정지 상황에서 역할을 분담하고 명확히 폐쇄루프 소통하세요.", Skills: []string{"CPR 팀 소통", "폐쇄루프"}, Phrases: []string{"I'll start compressions.", "Epinephrine given, noted.", "Pulse check in two minutes."}, Goals: []string{"역할 분담·폐쇄루프 확인", "타임키핑 소통"}},
			{Title: "패혈증 상태 설명", Tagline: "What does sepsis mean for her?", Room: "BED 1", Role: "family", Diff: 3, Brief: "패혈증의 의미와 치료 계획을 가족에게 설명하세요.", Skills: []string{"패혈증 어휘", "예후 소통"}, Phrases: []string{"Her body is fighting a serious infection.", "We're giving fluids and antibiotics.", "The next hours are important."}, Goals: []string{"패혈증·치료 계획 설명", "현실적이되 지지적으로"}},
			{Title: "ICU 섬망 대응", Tagline: "I need to go home — untie me!", Room: "BED 6", Role: "patient", Diff: 2, Brief: "섬망 환자를 현실 지남력으로 재정향하고 안전을 확보하세요.", Skills: []string{"재지남", "섬망 대응"}, Phrases: []string{"You're safe in the hospital.", "I'm your nurse, Sofia.", "It's morning now, look outside."}, Goals: []string{"지남력 재정향", "안전하게 안심"}, Moods: []string{"panic", "anxious"}},
			{Title: "인공호흡기 이탈 격려", Tagline: "I'm scared to breathe on my own.", Room: "BED 3", Role: "patient", Diff: 2, Brief: "이탈 시도 환자를 격려하며 호흡 코칭을 하세요.", Skills: []string{"위닝 어휘", "호흡 코칭"}, Phrases: []string{"You're doing great, keep breathing.", "We'll go slowly.", "I'm right here with you."}, Goals: []string{"이탈 과정 설명·격려", "호흡 코칭"}},
			{Title: "가족 면회 안내", Tagline: "Can I stay with my husband tonight?", Room: "WAITING", Role: "family", Diff: 1, Brief: "면회 규정과 환자 상태를 설명하고 정서적 지지를 제공하세요.", Skills: []string{"면회 안내", "정서 지지"}, Phrases: []string{"You can stay until 8 tonight.", "He's resting comfortably.", "Let me get you a chair."}, Goals: []string{"면회 규정 안내", "정서적 지지"}},
			{Title: "SBAR 당직의 보고", Tagline: "Doctor, calling about bed 2.", Room: "STATION", Role: "colleague", Diff: 3, Brief: "악화된 환자를 SBAR로 당직의에게 명확히 보고하세요.", Skills: []string{"SBAR", "전화 보고"}, Phrases: []string{"Situation: new desaturation in bed 2.", "Background: post-op day 2.", "I recommend a stat ABG."}, Goals: []string{"SBAR 순서로 보고", "요청 명확화"}},
			{Title: "임종 가족 면담", Tagline: "Is this the end?", Room: "QUIET ROOM", Role: "family", Diff: 3, Brief: "임종이 임박한 환자의 가족에게 공감적으로 상황을 전달하세요.", Skills: []string{"임종 소통", "공감"}, Phrases: []string{"I'm so sorry.", "We're keeping her comfortable.", "Take all the time you need."}, Goals: []string{"공감적으로 상황 전달", "존엄·편안함 보장"}, Moods: []string{"sad"}},
		}},
		{Code: "OR", Name: "수술실", Label: "OR", Color: "#9333EA", Tone: "#F3E8FF", Accent: "#7E22CE", Topics: []Topic{
			{Title: "수술 동의 확인", Tagline: "I'm not sure what they're doing to me.", Room: "PRE-OP", Role: "patient", Diff: 2, Brief: "수술 전 동의 내용을 확인하고 환자의 이해와 불안을 점검하세요.", Skills: []string{"동의 확인", "수술 어휘"}, Phrases: []string{"Can you tell me which procedure you're having?", "Do you have any questions?", "We'll take good care of you."}, Goals: []string{"동의·시술 이해 확인", "불안 완화"}},
			{Title: "마취 전 문진", Tagline: "I had a bad reaction to anesthesia once.", Room: "PRE-OP", Role: "patient", Diff: 2, Brief: "마취 전 금식·알레르기·과거력을 확인하세요.", Skills: []string{"마취 전 문진", "알레르기 확인"}, Phrases: []string{"When did you last eat or drink?", "Any allergies to medications?", "Tell me about that reaction."}, Goals: []string{"금식·알레르기·과거력 확인", "위험 요인 보고"}},
			{Title: "수술 전 Time-out", Tagline: "Everyone, let's confirm.", Room: "OR 2", Role: "colleague", Diff: 2, Brief: "팀과 함께 환자·부위·시술을 Time-out으로 확인하세요.", Skills: []string{"Time-out", "팀 확인"}, Phrases: []string{"Confirming: correct patient, correct site.", "Any concerns before we start?", "Antibiotics given?"}, Goals: []string{"환자·부위·시술 확인", "안전 체크"}},
			{Title: "수술 부위 표시 확인", Tagline: "Is the left or the right knee?", Room: "PRE-OP", Role: "patient", Diff: 1, Brief: "환자와 함께 수술 부위를 확인하고 표시하세요.", Skills: []string{"부위 확인", "환자 참여"}, Phrases: []string{"Can you point to the correct side?", "I'll mark it with you.", "We double-check for your safety."}, Goals: []string{"부위 재확인", "환자 참여 유도"}},
			{Title: "무균술 유지 소통", Tagline: "Watch the sterile field!", Room: "OR 1", Role: "colleague", Diff: 2, Brief: "무균 영역을 유지하며 팀에 명확히 알리세요.", Skills: []string{"무균술 어휘", "팀 소통"}, Phrases: []string{"That's contaminated, please re-glove.", "Keep the field sterile.", "Passing the scalpel, sharp."}, Goals: []string{"무균 위반 지적·정정", "기구 전달 소통"}},
			{Title: "수술 중 가족 업데이트", Tagline: "How's the surgery going?", Room: "WAITING", Role: "family", Diff: 1, Brief: "수술 중 가족에게 진행 상황을 업데이트하고 안심시키세요.", Skills: []string{"가족 소통", "진행 설명"}, Phrases: []string{"The surgery is going well so far.", "It should take about two hours.", "I'll update you again soon."}, Goals: []string{"진행 상황 업데이트", "불안 완화"}},
			{Title: "PACU 인계", Tagline: "Receiving from OR — status?", Room: "PACU", Role: "colleague", Diff: 3, Brief: "회복실로 환자를 SBAR로 인계하세요.", Skills: []string{"PACU 인계", "SBAR"}, Phrases: []string{"Post-op knee replacement, stable.", "Estimated blood loss minimal.", "Pain managed with fentanyl."}, Goals: []string{"수술·마취·활력 인계", "주의사항 전달"}},
			{Title: "회복 후 통증 사정", Tagline: "It really hurts when I wake up.", Room: "PACU", Role: "patient", Diff: 2, Brief: "마취에서 깬 환자의 통증을 사정하고 조절을 설명하세요.", Skills: []string{"통증 사정", "진통 설명"}, Phrases: []string{"On a scale of 0 to 10?", "I can give you something for the pain.", "Take slow breaths."}, Goals: []string{"통증 사정", "진통 조절 설명"}},
			{Title: "수술 지연 설명", Tagline: "Why is it taking so long to start?", Room: "PRE-OP", Role: "patient", Diff: 1, Brief: "수술 지연 사유를 설명하고 환자의 불안을 낮추세요.", Skills: []string{"지연 설명", "안심"}, Phrases: []string{"The previous case ran long.", "You're still first priority.", "I'll keep you updated."}, Goals: []string{"지연 사유 설명", "불안 완화"}},
			{Title: "수술 후 조기 이상 격려", Tagline: "I don't think I can stand yet.", Room: "PACU", Role: "patient", Diff: 2, Brief: "수술 후 조기 보행의 중요성을 설명하고 안전하게 격려하세요.", Skills: []string{"조기 이상 교육", "낙상 예방"}, Phrases: []string{"Moving early helps you heal.", "I'll support you, take it slow.", "Tell me if you feel dizzy."}, Goals: []string{"조기 이상 필요성 설명", "안전하게 보행 지원"}},
		}},
		{Code: "PEDS", Name: "소아과", Label: "PEDS", Color: "#3B82F6", Tone: "#DBEAFE", Accent: "#2563EB", Topics: []Topic{
			{Title: "아동 발열 부모 상담", Tagline: "His fever won't come down.", Room: "EXAM 1", Role: "parent", Diff: 1, Brief: "발열 아동 보호자에게 해열·수분·관찰을 교육하세요.", Skills: []string{"소아 발열", "보호자 교육"}, Phrases: []string{"Give the correct dose for his weight.", "Keep him hydrated.", "Come back if he seems lethargic."}, Goals: []string{"체중 기반 해열 안내", "경고 신호 교육"}},
			{Title: "예방접종 이상반응 안내", Tagline: "He got a fever after his shots.", Room: "WELL CHILD", Role: "parent", Diff: 1, Brief: "접종 후 흔한 반응과 대처를 보호자에게 안내하세요.", Skills: []string{"접종 반응", "안심"}, Phrases: []string{"A mild fever is common after shots.", "You can give infant acetaminophen.", "Call us if it lasts over two days."}, Goals: []string{"흔한 반응 설명", "대처·경고 신호 교육"}},
			{Title: "천식 발작 아동 진정", Tagline: "I can't... breathe...", Room: "TREATMENT", Role: "child", Diff: 3, Brief: "천식 발작 아동을 진정시키며 흡입 치료를 설명하세요.", Skills: []string{"소아 호흡", "아동 눈높이 설명"}, Phrases: []string{"Let's breathe with the mask together.", "You're doing so well.", "In through the nose, out slow."}, Goals: []string{"아동을 진정시키며 흡입 치료", "부모 동참 유도"}},
			{Title: "탈수 아동 수분 교육", Tagline: "She won't drink anything.", Room: "EXAM 2", Role: "parent", Diff: 2, Brief: "탈수 아동의 경구수액 요령을 보호자에게 교육하세요.", Skills: []string{"탈수 사정", "ORS 교육"}, Phrases: []string{"Try small sips every few minutes.", "Watch for fewer wet diapers.", "This oral solution helps."}, Goals: []string{"탈수 징후 확인", "경구수액 요령 교육"}},
			{Title: "채혈 전 아동 안심", Tagline: "Is it going to hurt?", Room: "LAB DRAW", Role: "child", Diff: 2, Brief: "채혈을 앞둔 아동을 놀이·설명으로 안심시키세요.", Skills: []string{"아동 대처 지원", "통증 완화"}, Phrases: []string{"It's a quick little pinch.", "You can squeeze this toy.", "You were so brave!"}, Goals: []string{"절차를 눈높이로 설명", "대처 전략 제공"}},
			{Title: "중이염 항생제 교육", Tagline: "Does she really need antibiotics?", Room: "EXAM 1", Role: "parent", Diff: 1, Brief: "중이염 항생제 복용의 필요성과 완수를 교육하세요.", Skills: []string{"항생제 복약", "보호자 상담"}, Phrases: []string{"Finish the full course.", "Give it at the same times daily.", "Come back if the ear pain worsens."}, Goals: []string{"복약 순응 교육", "경과 관찰 안내"}},
			{Title: "낙상·머리 손상 관찰", Tagline: "He fell off the couch — should I worry?", Room: "EXAM 3", Role: "parent", Diff: 2, Brief: "머리를 부딪친 아동의 경고 신호와 가정 관찰을 교육하세요.", Skills: []string{"두부 손상 관찰", "경고 신호"}, Phrases: []string{"Watch for vomiting or drowsiness.", "Wake him gently tonight to check.", "Come back right away if he seems off."}, Goals: []string{"경고 신호 교육", "가정 관찰 지도"}},
			{Title: "소아 통증 사정", Tagline: "(아동이 얼굴 척도를 가리킴)", Room: "TREATMENT", Role: "child", Diff: 1, Brief: "얼굴 통증 척도로 아동의 통증을 사정하세요.", Skills: []string{"FACES 척도", "아동 사정"}, Phrases: []string{"Point to the face that matches.", "Where does it hurt?", "I'll help make it better."}, Goals: []string{"얼굴 척도로 통증 사정", "안심 제공"}},
			{Title: "보호자 불안 공감", Tagline: "I feel like a bad parent.", Room: "EXAM 1", Role: "parent", Diff: 2, Brief: "죄책감을 느끼는 보호자를 공감적으로 지지하세요.", Skills: []string{"공감", "보호자 지지"}, Phrases: []string{"You did the right thing bringing her in.", "This can happen to anyone.", "Let's take it one step at a time."}, Goals: []string{"보호자 감정 공감", "지지·정보 제공"}},
			{Title: "퇴원 가정간호 교육", Tagline: "How do I care for him at home?", Room: "DISCHARGE", Role: "parent", Diff: 2, Brief: "퇴원 아동의 가정간호·투약·재방문 기준을 교육하세요.", Skills: []string{"퇴원 교육", "복약"}, Phrases: []string{"Give this medicine twice a day.", "These are the warning signs.", "Your follow-up is next Tuesday."}, Goals: []string{"가정간호·투약 교육", "재방문 기준 안내"}},
		}},
		{Code: "PHARMA", Name: "중앙약국", Label: "PHARMA", Color: "#16A34A", Tone: "#DCFCE7", Accent: "#15803D", Topics: []Topic{
			{Title: "헤파린 더블 체크", Tagline: "Can you verify this heparin dose?", Room: "COUNTER", Role: "colleague", Diff: 3, Brief: "고위험 약물 헤파린 용량을 동료와 이중 확인하세요.", Skills: []string{"고위험 약물", "이중 확인"}, Phrases: []string{"Confirming units and rate.", "Weight-based dose checks out.", "Both of us verified."}, Goals: []string{"용량·속도 이중 확인", "안전 문서화"}},
			{Title: "구두 처방 받아쓰기", Tagline: "Give me a read-back on that order.", Room: "STATION", Role: "doctor", Diff: 2, Brief: "구두 처방을 받아 적고 복창 확인하세요.", Skills: []string{"read-back", "처방 어휘"}, Phrases: []string{"Read-back: 4 milligrams IV, once.", "Spelling the drug name to confirm.", "Order confirmed."}, Goals: []string{"처방 받아쓰기·복창", "오류 방지"}},
			{Title: "인슐린 자가주사 교육", Tagline: "I'm scared of needles.", Room: "CONSULT", Role: "patient", Diff: 2, Brief: "당뇨 환자에게 인슐린 자가주사법을 단계별로 교육하세요.", Skills: []string{"인슐린 교육", "환자 시연"}, Phrases: []string{"Rotate your injection sites.", "Pinch the skin gently.", "Let's practice together."}, Goals: []string{"자가주사 단계 교육", "저혈당 대처 안내"}},
			{Title: "와파린 복약 상담", Tagline: "Can I still eat my vegetables?", Room: "CONSULT", Role: "patient", Diff: 2, Brief: "와파린 복용 환자의 식이·상호작용·모니터링을 상담하세요.", Skills: []string{"항응고 상담", "상호작용"}, Phrases: []string{"Keep your vitamin K intake steady.", "Watch for unusual bruising.", "Don't skip your INR checks."}, Goals: []string{"식이·상호작용 교육", "출혈 경고 신호"}},
			{Title: "마약류 픽업 2인 인증", Tagline: "Two-witness sign-out for Schedule II.", Room: "NARC SAFE", Role: "colleague", Diff: 2, Brief: "마약류 불출을 2인 인증 절차로 처리하세요.", Skills: []string{"마약류 관리", "2인 검증"}, Phrases: []string{"Count matches the record.", "Both witnesses signing.", "Waste documented together."}, Goals: []string{"2인 인증 수행", "재고·폐기 문서화"}},
			{Title: "다약제 복용 검토", Tagline: "I take a lot of pills — is that okay?", Room: "CONSULT", Role: "patient", Diff: 2, Brief: "다약제 복용 환자의 상호작용·중복을 검토하고 정리하세요.", Skills: []string{"약물 검토", "복약 단순화"}, Phrases: []string{"Let's review everything you take.", "These two may interact.", "Here's a simplified schedule."}, Goals: []string{"상호작용·중복 확인", "복약 정리·교육"}},
			{Title: "소아 용량 환산", Tagline: "How much for a 14-kilo child?", Room: "COUNTER", Role: "colleague", Diff: 3, Brief: "체중 기반 소아 용량을 계산하고 검증하세요.", Skills: []string{"용량 계산", "체중 기반"}, Phrases: []string{"Dose is per kilogram.", "Double-checking the math.", "That's within the safe range."}, Goals: []string{"체중 기반 용량 계산", "안전 범위 확인"}},
			{Title: "항생제 복약 순응 상담", Tagline: "I feel better, can I stop?", Room: "CONSULT", Role: "patient", Diff: 1, Brief: "증상 호전에도 항생제를 완수해야 함을 교육하세요.", Skills: []string{"항생제 순응", "환자 교육"}, Phrases: []string{"Finish the whole course.", "Stopping early can cause resistance.", "Set a daily reminder."}, Goals: []string{"완수 필요성 설명", "순응 전략 제공"}},
			{Title: "부작용 상담", Tagline: "This pill makes me nauseous.", Room: "CONSULT", Role: "patient", Diff: 1, Brief: "약물 부작용을 청취하고 대처·보고를 안내하세요.", Skills: []string{"부작용 상담", "보고 안내"}, Phrases: []string{"Taking it with food may help.", "That side effect is common.", "Call us if it gets worse."}, Goals: []string{"부작용 청취·평가", "대처·보고 안내"}},
			{Title: "고위험 약물 이중확인", Tagline: "Independent double-check, please.", Room: "COUNTER", Role: "colleague", Diff: 3, Brief: "고위험 약물을 독립 이중확인 절차로 검증하세요.", Skills: []string{"이중 확인", "안전 문화"}, Phrases: []string{"I'll check independently.", "Patient, drug, dose, route, time.", "Confirmed, all five rights."}, Goals: []string{"독립 이중확인 수행", "5 rights 확인"}},
		}},
	}...)
}
