package main

// Curated clinical topic banks (part 3) — the four tower floors that had a built
// interior but no scenarios of their own: 내과 8F, 외과 7F, 정형외과 6F, 피부과 2F.
//
// They previously would have had to borrow the GEN (공통 병동) bank, which made
// three ward floors read identically and left dermatology with nothing at all —
// light therapy and laser aftercare are not ward work.
//
// Each bank keeps the house shape: a real situation, a line the other person
// actually says, the English a Korean nurse tends to reach for and miss, and a
// difficulty that drives the curriculum's step order.
func init() {
	Depts = append(Depts, []Dept{
		// ── 본관 8F · 내과 병동 ─────────────────────────────────────────────
		{Code: "WARD", Name: "내과 병동", Label: "WARD", Color: "#0E7490", Tone: "#E0F2FE", Accent: "#0369A1", Topics: []Topic{
			{Title: "만성질환 입원 사정", Tagline: "I've had diabetes for twenty years.", Room: "WARD", Role: "patient", Diff: 1, Brief: "만성질환 병력을 가진 신규 입원 환자를 사정하세요.", Skills: []string{"입원 사정", "병력 청취"}, Phrases: []string{"How long have you been on insulin?", "Any hospital stays this year?", "Who manages your medications at home?"}, Goals: []string{"병력 청취", "복약 현황 파악"}},
			{Title: "혈당 변동 설명", Tagline: "Why is my sugar high again?", Room: "WARD", Role: "patient", Diff: 2, Brief: "입원 중 혈당이 흔들리는 이유를 이해할 수 있게 설명하세요.", Skills: []string{"혈당 교육", "공감"}, Phrases: []string{"Illness itself raises your sugar.", "We'll adjust the dose, not blame you.", "Let's look at the pattern together."}, Goals: []string{"변동 원인 설명", "자책 완화"}},
			{Title: "심부전 체중·부종 교육", Tagline: "My legs are swollen again.", Room: "WARD", Role: "patient", Diff: 2, Brief: "매일 체중과 부종을 확인해야 하는 이유를 교육하세요.", Skills: []string{"심부전 교육", "자가 모니터링"}, Phrases: []string{"Weigh yourself at the same time each morning.", "Two kilos in three days — call us.", "Press here and see if it leaves a dent."}, Goals: []string{"자가 모니터링 교육", "경고 신호 설명"}},
			{Title: "산소 요구 증가 사정", Tagline: "I feel more short of breath than yesterday.", Room: "WARD", Role: "patient", Diff: 3, Brief: "호흡 악화를 사정하고 보고 여부를 판단하세요.", Skills: []string{"호흡 사정", "에스컬레이션"}, Phrases: []string{"Is it worse lying flat?", "Your oxygen has dropped since this morning.", "I'm going to call the doctor now."}, Goals: []string{"악화 사정", "적시 보고"}, Acuity: "urgent"},
			{Title: "이뇨제 복용 상담", Tagline: "I skip it when I go out.", Room: "WARD", Role: "patient", Diff: 2, Brief: "이뇨제를 거르는 이유를 듣고 현실적인 대안을 찾으세요.", Skills: []string{"복약 순응", "협상"}, Phrases: []string{"I understand — the bathroom trips are hard.", "Could we move it to the morning?", "Skipping it is what brings you back here."}, Goals: []string{"비순응 이유 청취", "대안 제시"}},
			{Title: "다학제 회진 참여", Tagline: "What's the plan for Mr. Kim today?", Room: "STATION", Role: "colleague", Diff: 3, Brief: "회진에서 간호사 관점의 관찰을 간결히 전달하세요.", Skills: []string{"회진 발표", "SBAR"}, Phrases: []string{"Overnight he needed two extra liters.", "His intake is down since Tuesday.", "My concern is his mobility at discharge."}, Goals: []string{"관찰 공유", "우선순위 제안"}},
			{Title: "혈액검사 결과 설명", Tagline: "The doctor said my kidney numbers changed.", Room: "WARD", Role: "patient", Diff: 2, Brief: "검사 수치 변화를 겁주지 않고 설명하세요.", Skills: []string{"결과 설명", "안심"}, Phrases: []string{"It's slightly up, not dangerous.", "We'll recheck in the morning.", "Drinking enough water helps."}, Goals: []string{"수치 설명", "다음 단계 안내"}},
			{Title: "감염 격리 안내", Tagline: "Why is everyone wearing a gown for me?", Room: "WARD", Role: "patient", Diff: 2, Brief: "격리 이유를 설명하고 낙인감을 덜어주세요.", Skills: []string{"감염관리", "존엄"}, Phrases: []string{"It protects other patients, not because you're dirty.", "It's temporary, until the culture clears.", "Your family can still visit with a gown."}, Goals: []string{"격리 이유 설명", "낙인 완화"}},
			{Title: "야간 불면 대응", Tagline: "I haven't slept properly in three nights.", Room: "WARD", Role: "patient", Diff: 1, Brief: "약에 앞서 환경 요인을 먼저 다루세요.", Skills: []string{"수면 위생", "비약물 중재"}, Phrases: []string{"Would dimming the light help?", "I can move your vitals check later.", "Let's try that before a sleeping pill."}, Goals: []string{"원인 탐색", "비약물 중재 제안"}},
			{Title: "내과 병동 인계", Tagline: "Handoff — eight patients, two unstable.", Room: "STATION", Role: "colleague", Diff: 3, Brief: "우선순위를 드러내는 인계를 하세요.", Skills: []string{"SBAR", "우선순위"}, Phrases: []string{"Start with room 4 — he's the one I'd watch.", "Room 2 is stable, discharge pending labs.", "Nothing outstanding on the rest."}, Goals: []string{"우선순위 인계", "미결 사항 전달"}},
		}},

		// ── 본관 7F · 외과 병동 ─────────────────────────────────────────────
		{Code: "SURGWARD", Name: "외과 병동", Label: "SURG", Color: "#B45309", Tone: "#FEF3C7", Accent: "#92400E", Topics: []Topic{
			{Title: "수술 후 첫 사정", Tagline: "I just woke up — where am I?", Room: "WARD", Role: "patient", Diff: 2, Brief: "PACU에서 올라온 환자의 의식·통증·출혈을 사정하세요.", Skills: []string{"술후 사정", "지남력"}, Phrases: []string{"You're on the surgical ward now.", "Can you tell me your name?", "I'm checking your dressing."}, Goals: []string{"의식·통증 사정", "환자 안심"}},
			{Title: "통증 자가조절 장치 교육", Tagline: "Am I allowed to press it that often?", Room: "WARD", Role: "patient", Diff: 2, Brief: "PCA 사용법과 안전장치를 설명하세요.", Skills: []string{"PCA 교육", "통증 관리"}, Phrases: []string{"Only you press this button — never family.", "It locks out so you can't overdose.", "Press before the pain gets bad."}, Goals: []string{"사용법 교육", "가족 대리 사용 금지"}},
			{Title: "조기 보행 격려", Tagline: "It hurts too much to stand up.", Room: "WARD", Role: "patient", Diff: 2, Brief: "통증을 인정하면서 조기 보행의 필요를 설득하세요.", Skills: []string{"조기 보행", "동기부여"}, Phrases: []string{"Let's medicate first, then try.", "Just to the door and back.", "Moving prevents clots and pneumonia."}, Goals: []string{"통증 선처치", "단계적 목표 제시"}},
			{Title: "수술 부위 드레싱 관찰", Tagline: "Is it supposed to look like that?", Room: "WARD", Role: "patient", Diff: 2, Brief: "상처 상태를 설명하고 이상 징후를 함께 알려주세요.", Skills: []string{"상처 관찰", "환자 교육"}, Phrases: []string{"A little pink is normal healing.", "Tell me if it starts to smell.", "Keep it dry until Friday."}, Goals: []string{"정상·이상 구분 설명", "보고 기준 제시"}},
			{Title: "배액관 관리 설명", Tagline: "How long will this tube stay in?", Room: "WARD", Role: "patient", Diff: 2, Brief: "배액관의 목적과 제거 기준을 설명하세요.", Skills: []string{"배액관", "환자 교육"}, Phrases: []string{"It comes out when the drainage drops.", "Keep the bulb below the wound.", "Don't pull on the tubing when you walk."}, Goals: []string{"목적 설명", "취급 주의 교육"}},
			{Title: "수술 후 출혈 의심", Tagline: "The dressing is soaked through.", Room: "WARD", Role: "patient", Diff: 3, Brief: "출혈 징후를 사정하고 즉시 보고하세요.", Skills: []string{"출혈 사정", "에스컬레이션"}, Phrases: []string{"I need to look at this right now.", "Stay flat for me.", "I'm calling the surgical team."}, Goals: []string{"출혈 사정", "즉시 보고"}, Acuity: "critical"},
			{Title: "장운동 회복 안내", Tagline: "When can I eat real food?", Room: "WARD", Role: "patient", Diff: 1, Brief: "식이 진행 단계를 설명하세요.", Skills: []string{"식이 진행", "회복 교육"}, Phrases: []string{"We start with sips of water.", "Once you pass gas, we move up.", "Rushing it usually means vomiting."}, Goals: []string{"단계 설명", "기대 조정"}},
			{Title: "수술 후 섬망 관찰", Tagline: "My father is talking to people who aren't there.", Room: "WARD", Role: "family", Diff: 3, Brief: "술후 섬망을 가족에게 설명하고 함께 대응하세요.", Skills: []string{"섬망", "가족 교육"}, Phrases: []string{"This is common after surgery and usually passes.", "Familiar faces and daylight help a lot.", "Please bring his glasses and hearing aid."}, Goals: []string{"섬망 설명", "가족 참여 유도"}, Acuity: "urgent"},
			{Title: "퇴원 상처 관리 교육", Tagline: "Can I shower with this?", Room: "WARD", Role: "patient", Diff: 2, Brief: "귀가 후 상처 관리와 재방문 기준을 교육하세요.", Skills: []string{"퇴원 교육", "상처 관리"}, Phrases: []string{"Shower after 48 hours, don't soak.", "Come back if it's red and hot.", "Your stitches come out next Tuesday."}, Goals: []string{"관리법 교육", "재방문 기준 제시"}},
			{Title: "외과 병동 인계", Tagline: "Three post-ops, one for theatre tomorrow.", Room: "STATION", Role: "colleague", Diff: 3, Brief: "수술 일정과 술후 상태를 함께 인계하세요.", Skills: []string{"SBAR", "술후 인계"}, Phrases: []string{"Bed 6 is day one, drain still heavy.", "Bed 2 is nil by mouth from midnight.", "Bed 4's pain isn't controlled yet."}, Goals: []string{"술후 상태 인계", "수술 준비 공유"}},
		}},

		// ── 본관 6F · 정형외과 병동 ─────────────────────────────────────────
		{Code: "ORTHOWARD", Name: "정형외과 병동", Label: "ORTHO", Color: "#7C3AED", Tone: "#EDE9FE", Accent: "#5B21B6", Topics: []Topic{
			{Title: "골절 환자 입원 사정", Tagline: "I slipped on the stairs at home.", Room: "WARD", Role: "patient", Diff: 1, Brief: "수상 경위와 신경·순환 상태를 사정하세요.", Skills: []string{"골절 사정", "신경순환"}, Phrases: []string{"Can you wiggle your toes for me?", "Does this feel the same on both sides?", "Tell me exactly how you landed."}, Goals: []string{"수상 경위 청취", "말초 순환 확인"}},
			{Title: "석고붕대 관리 교육", Tagline: "It itches so much I want to scratch inside.", Room: "WARD", Role: "patient", Diff: 2, Brief: "석고 관리와 금기를 설명하세요.", Skills: []string{"석고 관리", "합병증 예방"}, Phrases: []string{"Never push anything down inside the cast.", "Keep it dry — a bag for showers.", "Call us if your fingers go numb."}, Goals: []string{"관리 교육", "위험 신호 안내"}},
			{Title: "견인 장치 설명", Tagline: "How long do I have to lie like this?", Room: "WARD", Role: "patient", Diff: 2, Brief: "견인의 목적과 자세 유지 필요성을 설명하세요.", Skills: []string{"견인", "체위 유지"}, Phrases: []string{"The weights keep the bone aligned.", "We shouldn't lift them, even for a moment.", "I'll help you shift without losing the pull."}, Goals: []string{"목적 설명", "체위 협조"}},
			{Title: "고관절 수술 후 자세 제한", Tagline: "Can I just cross my legs for a second?", Room: "WARD", Role: "patient", Diff: 3, Brief: "탈구 예방 자세 제한을 이해시키세요.", Skills: []string{"탈구 예방", "체위 교육"}, Phrases: []string{"Don't cross your legs — not even briefly.", "Keep the pillow between your knees.", "Bend no more than ninety degrees."}, Goals: []string{"금기 자세 교육", "실생활 적용"}},
			{Title: "보행 보조기구 훈련", Tagline: "I feel like I'm going to fall with these.", Room: "WARD", Role: "patient", Diff: 2, Brief: "워커·목발 사용을 단계적으로 지도하세요.", Skills: []string{"보행 훈련", "낙상 예방"}, Phrases: []string{"Crutches first, then the weak leg.", "I'll walk right beside you.", "Small steps — we're not in a hurry."}, Goals: []string{"사용법 지도", "자신감 형성"}},
			{Title: "심부정맥혈전 예방 교육", Tagline: "Why do I need these tight stockings?", Room: "WARD", Role: "patient", Diff: 2, Brief: "부동 환자의 혈전 예방을 교육하세요.", Skills: []string{"DVT 예방", "환자 교육"}, Phrases: []string{"Lying still lets clots form.", "Pump your ankles like this, every hour.", "Tell me about any calf pain."}, Goals: []string{"예방 필요성 설명", "운동 지도"}},
			{Title: "구획증후군 의심 사정", Tagline: "The pain is much worse than before.", Room: "WARD", Role: "patient", Diff: 3, Brief: "석고 후 통증 악화를 사정하고 즉시 보고하세요.", Skills: []string{"구획증후군", "에스컬레이션"}, Phrases: []string{"Pain out of proportion worries me.", "Can you feel me touching here?", "I'm calling the doctor right now."}, Goals: []string{"위험 징후 사정", "즉시 보고"}, Acuity: "critical"},
			{Title: "재활 목표 상담", Tagline: "Will I get back to hiking?", Room: "WARD", Role: "patient", Diff: 2, Brief: "현실적인 회복 목표를 함께 세우세요.", Skills: []string{"목표 설정", "동기부여"}, Phrases: []string{"Let's aim for stairs first.", "Most people take three months.", "What matters most to you at home?"}, Goals: []string{"현실적 목표 설정", "동기 유지"}},
			{Title: "낙상 재발 예방 상담", Tagline: "I don't want to end up back here.", Room: "WARD", Role: "patient", Diff: 2, Brief: "가정 환경 위험을 함께 점검하세요.", Skills: []string{"낙상 예방", "환경 점검"}, Phrases: []string{"Are there rugs on your floors?", "A night light in the hallway helps.", "Grab bars in the bathroom are worth it."}, Goals: []string{"위험 요인 파악", "구체적 대안 제시"}},
			{Title: "정형 병동 인계", Tagline: "Two hip replacements, one traction.", Room: "STATION", Role: "colleague", Diff: 3, Brief: "체위 제한과 보행 진행도를 인계하세요.", Skills: []string{"SBAR", "체위 제한"}, Phrases: []string{"Bed 3 is hip precautions, day two.", "Bed 5 walked to the door today.", "Bed 8's traction weights are set at four."}, Goals: []string{"체위 제한 전달", "보행 진행 공유"}},
		}},

		// ── 본관 2F · 피부과 센터 ───────────────────────────────────────────
		{Code: "DERM", Name: "피부과 센터", Label: "DERM", Color: "#DB2777", Tone: "#FCE7F3", Accent: "#9D174D", Topics: []Topic{
			{Title: "피부 병변 문진", Tagline: "It started as one spot and spread.", Room: "CLINIC", Role: "patient", Diff: 1, Brief: "병변의 발생·경과·유발 요인을 문진하세요.", Skills: []string{"피부 문진", "경과 청취"}, Phrases: []string{"When did you first notice it?", "Does anything make it flare?", "Have you changed soaps or detergent?"}, Goals: []string{"경과 청취", "유발 요인 탐색"}},
			{Title: "가려움 조절 상담", Tagline: "I scratch it in my sleep without knowing.", Room: "CLINIC", Role: "patient", Diff: 2, Brief: "긁는 악순환을 끊는 실질적 방법을 상담하세요.", Skills: []string{"소양증", "생활 지도"}, Phrases: []string{"Scratching makes it itch more, not less.", "Cool compresses can break the cycle.", "Cotton gloves at night help a lot."}, Goals: []string{"악순환 설명", "대안 제시"}},
			{Title: "국소 스테로이드 교육", Tagline: "I've heard steroids are dangerous.", Room: "CLINIC", Role: "patient", Diff: 2, Brief: "스테로이드 연고의 오해를 풀고 올바른 사용법을 교육하세요.", Skills: []string{"국소 도포", "복약 순응"}, Phrases: []string{"A fingertip amount covers both palms.", "Thin layer, twice a day, then stop.", "Under-using it keeps the rash going."}, Goals: []string{"오해 해소", "도포량 교육"}},
			{Title: "광선치료 전 안내", Tagline: "Will this burn my skin?", Room: "PHOTO", Role: "patient", Diff: 2, Brief: "광선치료 절차와 보호 장비를 안내하세요.", Skills: []string{"광선치료", "안전 안내"}, Phrases: []string{"You'll wear goggles the whole time.", "We start with a very short exposure.", "Tell me immediately if it stings."}, Goals: []string{"절차 설명", "안전 수칙 안내"}},
			{Title: "광선치료 중 이상반응", Tagline: "My skin is burning right now.", Room: "PHOTO", Role: "patient", Diff: 3, Brief: "치료 중 화상 징후에 즉시 대응하세요.", Skills: []string{"이상반응", "즉시 중단"}, Phrases: []string{"I'm stopping the session now.", "Let's cool it and look together.", "I'll report this before your next visit."}, Goals: []string{"즉시 중단", "사정·보고"}, Acuity: "urgent"},
			{Title: "레이저 시술 전 설명", Tagline: "How much downtime will I need?", Room: "LASER", Role: "patient", Diff: 2, Brief: "시술 과정과 회복 기간을 설명하세요.", Skills: []string{"레이저", "기대 조정"}, Phrases: []string{"Redness for about three days is normal.", "No makeup until the crusting settles.", "Sun exposure now undoes the result."}, Goals: []string{"과정 설명", "회복 기간 안내"}},
			{Title: "시술 후 자외선 차단 교육", Tagline: "I only go out for a few minutes.", Room: "CLINIC", Role: "patient", Diff: 2, Brief: "일상 노출도 위험함을 납득시키세요.", Skills: []string{"자외선 차단", "생활 지도"}, Phrases: []string{"Even a short walk adds up.", "Reapply every two hours outdoors.", "A hat does more than you'd think."}, Goals: []string{"위험 설명", "구체적 습관 제안"}},
			{Title: "만성 습진 심리 지지", Tagline: "People stare at my hands at work.", Room: "CLINIC", Role: "patient", Diff: 3, Brief: "만성 피부질환의 사회적 부담을 다루세요.", Skills: []string{"심리 지지", "공감"}, Phrases: []string{"That sounds exhausting to carry every day.", "This isn't something you caused.", "Let's find something that fits your work."}, Goals: []string{"정서 인정", "현실적 지원"}},
			{Title: "알레르기 접촉 유발 물질 추적", Tagline: "It always comes back after the weekend.", Room: "CLINIC", Role: "patient", Diff: 2, Brief: "생활 패턴에서 접촉 원인을 함께 찾으세요.", Skills: []string{"접촉피부염", "원인 추적"}, Phrases: []string{"What do you do differently on weekends?", "Gloves at home might be the trigger.", "Let's keep a simple diary for two weeks."}, Goals: []string{"패턴 탐색", "기록 지도"}},
			{Title: "피부과 외래 인계", Tagline: "Handoff — two phototherapy, one biopsy.", Room: "STATION", Role: "colleague", Diff: 2, Brief: "시술 일정과 이상반응 이력을 인계하세요.", Skills: []string{"외래 인계", "이상반응 이력"}, Phrases: []string{"Bay 1 reacted to last week's dose.", "Bay 2's biopsy site needs a check.", "Bay 3 is a first-time laser patient."}, Goals: []string{"일정 인계", "주의 환자 공유"}},
		}},
	}...)
}
