// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package sqlc

import (
	"context"
)

const deleteDepartments = `-- name: DeleteDepartments :exec
DELETE FROM departments
`

func (q *Queries) DeleteDepartments(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteDepartments)
	return err
}

const deleteEvents = `-- name: DeleteEvents :exec
DELETE FROM events
`

func (q *Queries) DeleteEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteEvents)
	return err
}

const deleteInteriors = `-- name: DeleteInteriors :exec
DELETE FROM interiors
`

func (q *Queries) DeleteInteriors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteInteriors)
	return err
}

const deletePhrases = `-- name: DeletePhrases :exec
DELETE FROM phrases
`

func (q *Queries) DeletePhrases(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deletePhrases)
	return err
}

const deleteQuizzes = `-- name: DeleteQuizzes :exec
DELETE FROM quizzes
`

func (q *Queries) DeleteQuizzes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteQuizzes)
	return err
}

const deleteScenarios = `-- name: DeleteScenarios :exec
DELETE FROM scenarios
`

func (q *Queries) DeleteScenarios(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteScenarios)
	return err
}

const getContentMeta = `-- name: GetContentMeta :one
SELECT v FROM content_meta WHERE k = $1
`

func (q *Queries) GetContentMeta(ctx context.Context, k string) (string, error) {
	row := q.db.QueryRow(ctx, getContentMeta, k)
	var v string
	err := row.Scan(&v)
	return v, err
}

const getInterior = `-- name: GetInterior :one
SELECT id, profession, dept_id, cols, rows, player_start, floor_theme, regions, rooms, objects, hotspots, collision
FROM interiors WHERE id = $1
`

func (q *Queries) GetInterior(ctx context.Context, id string) (Interior, error) {
	row := q.db.QueryRow(ctx, getInterior, id)
	var i Interior
	err := row.Scan(
		&i.ID,
		&i.Profession,
		&i.DeptID,
		&i.Cols,
		&i.Rows,
		&i.PlayerStart,
		&i.FloorTheme,
		&i.Regions,
		&i.Rooms,
		&i.Objects,
		&i.Hotspots,
		&i.Collision,
	)
	return i, err
}

const getScenario = `-- name: GetScenario :one
SELECT id, profession, event_id, title, tagline, persona, goals, guardrails, key_phrases, steps, briefing
FROM scenarios WHERE id = $1
`

type GetScenarioRow struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	EventID    string `json:"event_id"`
	Title      string `json:"title"`
	Tagline    string `json:"tagline"`
	Persona    []byte `json:"persona"`
	Goals      []byte `json:"goals"`
	Guardrails []byte `json:"guardrails"`
	KeyPhrases []byte `json:"key_phrases"`
	Steps      []byte `json:"steps"`
	Briefing   []byte `json:"briefing"`
}

func (q *Queries) GetScenario(ctx context.Context, id string) (GetScenarioRow, error) {
	row := q.db.QueryRow(ctx, getScenario, id)
	var i GetScenarioRow
	err := row.Scan(
		&i.ID,
		&i.Profession,
		&i.EventID,
		&i.Title,
		&i.Tagline,
		&i.Persona,
		&i.Goals,
		&i.Guardrails,
		&i.KeyPhrases,
		&i.Steps,
		&i.Briefing,
	)
	return i, err
}

const insertDepartment = `-- name: InsertDepartment :exec
INSERT INTO departments (id, profession, ward, name_ko, name_en, color) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertDepartmentParams struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Ward       string `json:"ward"`
	NameKo     string `json:"name_ko"`
	NameEn     string `json:"name_en"`
	Color      string `json:"color"`
}

func (q *Queries) InsertDepartment(ctx context.Context, arg InsertDepartmentParams) error {
	_, err := q.db.Exec(ctx, insertDepartment,
		arg.ID,
		arg.Profession,
		arg.Ward,
		arg.NameKo,
		arg.NameEn,
		arg.Color,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (id, profession, title, ward, category, tier, tags, delivery, prerequisites, follow_ups, related, scenarios)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertEventParams struct {
	ID            string `json:"id"`
	Profession    string `json:"profession"`
	Title         string `json:"title"`
	Ward          string `json:"ward"`
	Category      string `json:"category"`
	Tier          int    `json:"tier"`
	Tags          []byte `json:"tags"`
	Delivery      string `json:"delivery"`
	Prerequisites []byte `json:"prerequisites"`
	FollowUps     []byte `json:"follow_ups"`
	Related       []byte `json:"related"`
	Scenarios     []byte `json:"scenarios"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.Profession,
		arg.Title,
		arg.Ward,
		arg.Category,
		arg.Tier,
		arg.Tags,
		arg.Delivery,
		arg.Prerequisites,
		arg.FollowUps,
		arg.Related,
		arg.Scenarios,
	)
	return err
}

const insertInterior = `-- name: InsertInterior :exec
INSERT INTO interiors (id, profession, dept_id, cols, rows, player_start, floor_theme, regions, rooms, objects, hotspots, collision)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type InsertInteriorParams struct {
	ID          string `json:"id"`
	Profession  string `json:"profession"`
	DeptID      string `json:"dept_id"`
	Cols        int    `json:"cols"`
	Rows        int    `json:"rows"`
	PlayerStart []byte `json:"player_start"`
	FloorTheme  string `json:"floor_theme"`
	Regions     []byte `json:"regions"`
	Rooms       []byte `json:"rooms"`
	Objects     []byte `json:"objects"`
	Hotspots    []byte `json:"hotspots"`
	Collision   []byte `json:"collision"`
}

func (q *Queries) InsertInterior(ctx context.Context, arg InsertInteriorParams) error {
	_, err := q.db.Exec(ctx, insertInterior,
		arg.ID,
		arg.Profession,
		arg.DeptID,
		arg.Cols,
		arg.Rows,
		arg.PlayerStart,
		arg.FloorTheme,
		arg.Regions,
		arg.Rooms,
		arg.Objects,
		arg.Hotspots,
		arg.Collision,
	)
	return err
}

const insertPhrase = `-- name: InsertPhrase :exec
INSERT INTO phrases (id, profession, ko, en, note, tag) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPhraseParams struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Ko         string `json:"ko"`
	En         string `json:"en"`
	Note       string `json:"note"`
	Tag        string `json:"tag"`
}

func (q *Queries) InsertPhrase(ctx context.Context, arg InsertPhraseParams) error {
	_, err := q.db.Exec(ctx, insertPhrase,
		arg.ID,
		arg.Profession,
		arg.Ko,
		arg.En,
		arg.Note,
		arg.Tag,
	)
	return err
}

const insertQuiz = `-- name: InsertQuiz :exec
INSERT INTO quizzes (id, profession, type, title) VALUES ($1, $2, $3, $4)
`

type InsertQuizParams struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Type       string `json:"type"`
	Title      string `json:"title"`
}

func (q *Queries) InsertQuiz(ctx context.Context, arg InsertQuizParams) error {
	_, err := q.db.Exec(ctx, insertQuiz,
		arg.ID,
		arg.Profession,
		arg.Type,
		arg.Title,
	)
	return err
}

const insertScenario = `-- name: InsertScenario :exec
INSERT INTO scenarios (id, profession, event_id, title, tagline, persona, goals, guardrails, key_phrases, steps, briefing)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type InsertScenarioParams struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	EventID    string `json:"event_id"`
	Title      string `json:"title"`
	Tagline    string `json:"tagline"`
	Persona    []byte `json:"persona"`
	Goals      []byte `json:"goals"`
	Guardrails []byte `json:"guardrails"`
	KeyPhrases []byte `json:"key_phrases"`
	Steps      []byte `json:"steps"`
	Briefing   []byte `json:"briefing"`
}

func (q *Queries) InsertScenario(ctx context.Context, arg InsertScenarioParams) error {
	_, err := q.db.Exec(ctx, insertScenario,
		arg.ID,
		arg.Profession,
		arg.EventID,
		arg.Title,
		arg.Tagline,
		arg.Persona,
		arg.Goals,
		arg.Guardrails,
		arg.KeyPhrases,
		arg.Steps,
		arg.Briefing,
	)
	return err
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, profession, ward, name_ko, name_en, color FROM departments
WHERE ($1 = '' OR profession = $1 OR profession = 'common') ORDER BY id
`

func (q *Queries) ListDepartments(ctx context.Context, dollar_1 interface{}) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.Profession,
			&i.Ward,
			&i.NameKo,
			&i.NameEn,
			&i.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, profession, title, ward, category, tier, tags, delivery, prerequisites, follow_ups, related, scenarios
FROM events WHERE ($1 = '' OR profession = $1 OR profession = 'common') ORDER BY tier, id
`

func (q *Queries) ListEvents(ctx context.Context, dollar_1 interface{}) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Profession,
			&i.Title,
			&i.Ward,
			&i.Category,
			&i.Tier,
			&i.Tags,
			&i.Delivery,
			&i.Prerequisites,
			&i.FollowUps,
			&i.Related,
			&i.Scenarios,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const todaysBoard = `-- name: TodaysBoard :many
SELECT id, profession, title, ward, category, tier, tags, delivery, prerequisites, follow_ups, related, scenarios
FROM events WHERE delivery IN ('daily_pool', 'both') AND ($1 = '' OR profession = $1 OR profession = 'common')
ORDER BY tier, id LIMIT $2
`

type TodaysBoardParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) TodaysBoard(ctx context.Context, arg TodaysBoardParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, todaysBoard, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Profession,
			&i.Title,
			&i.Ward,
			&i.Category,
			&i.Tier,
			&i.Tags,
			&i.Delivery,
			&i.Prerequisites,
			&i.FollowUps,
			&i.Related,
			&i.Scenarios,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertContentMeta = `-- name: UpsertContentMeta :exec
INSERT INTO content_meta (k, v) VALUES ($1, $2)
ON CONFLICT (k) DO UPDATE SET v = EXCLUDED.v
`

type UpsertContentMetaParams struct {
	K string `json:"k"`
	V string `json:"v"`
}

func (q *Queries) UpsertContentMeta(ctx context.Context, arg UpsertContentMetaParams) error {
	_, err := q.db.Exec(ctx, upsertContentMeta, arg.K, arg.V)
	return err
}
