// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package sqlc

import (
	"context"
)

const appendTurn = `-- name: AppendTurn :exec
INSERT INTO dialogue_turns (session_id, role, content, mood) VALUES ($1, $2, $3, $4)
`

type AppendTurnParams struct {
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	Mood      string `json:"mood"`
}

func (q *Queries) AppendTurn(ctx context.Context, arg AppendTurnParams) error {
	_, err := q.db.Exec(ctx, appendTurn,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.Mood,
	)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO conversation_sessions (user_id, scenario_id) VALUES ($1, $2) RETURNING id
`

type CreateSessionParams struct {
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.ScenarioID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const discardSession = `-- name: DiscardSession :execrows
UPDATE conversation_sessions
   SET discarded_at = now()
 WHERE id = $1 AND user_id = $2 AND discarded_at IS NULL
`

type DiscardSessionParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

// Marks a session as thrown away so it is never offered back. The user_id is part of the
// predicate, not checked beforehand: one statement that cannot touch someone else's
// session beats two that can disagree. execrows so the caller can tell "not yours / does
// not exist" from "done".
func (q *Queries) DiscardSession(ctx context.Context, arg DiscardSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, discardSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, scenario_id FROM conversation_sessions WHERE id = $1
`

type GetSessionRow struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ScenarioID)
	return i, err
}

const insertCardSchedule = `-- name: InsertCardSchedule :exec
INSERT INTO review_schedules (card_id, due_date) VALUES ($1, CURRENT_DATE)
`

func (q *Queries) InsertCardSchedule(ctx context.Context, cardID string) error {
	_, err := q.db.Exec(ctx, insertCardSchedule, cardID)
	return err
}

const insertCorrection = `-- name: InsertCorrection :exec
INSERT INTO correction_results (user_id, original, corrected, note, topic_tag)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCorrectionParams struct {
	UserID    string `json:"user_id"`
	Original  string `json:"original"`
	Corrected string `json:"corrected"`
	Note      string `json:"note"`
	TopicTag  string `json:"topic_tag"`
}

func (q *Queries) InsertCorrection(ctx context.Context, arg InsertCorrectionParams) error {
	_, err := q.db.Exec(ctx, insertCorrection,
		arg.UserID,
		arg.Original,
		arg.Corrected,
		arg.Note,
		arg.TopicTag,
	)
	return err
}

const insertReviewCard = `-- name: InsertReviewCard :one
INSERT INTO review_cards (user_id, source, front, back, note, topic_tag, scenario_id, context)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
`

type InsertReviewCardParams struct {
	UserID     string `json:"user_id"`
	Source     string `json:"source"`
	Front      string `json:"front"`
	Back       string `json:"back"`
	Note       string `json:"note"`
	TopicTag   string `json:"topic_tag"`
	ScenarioID string `json:"scenario_id"`
	Context    []byte `json:"context"`
}

func (q *Queries) InsertReviewCard(ctx context.Context, arg InsertReviewCardParams) (string, error) {
	row := q.db.QueryRow(ctx, insertReviewCard,
		arg.UserID,
		arg.Source,
		arg.Front,
		arg.Back,
		arg.Note,
		arg.TopicTag,
		arg.ScenarioID,
		arg.Context,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const latestAssistantMood = `-- name: LatestAssistantMood :one
SELECT COALESCE(mood, '') FROM dialogue_turns
 WHERE session_id = $1 AND role <> 'user'
 ORDER BY created_at DESC LIMIT 1
`

// The mood of the last thing the NPC said, for comparing the next turn against.
// Empty when the NPC has not spoken yet, or spoke before this column existed —
// either way there is nothing to have improved on, which MoodImproved treats as
// "no change" rather than as a win.
func (q *Queries) LatestAssistantMood(ctx context.Context, sessionID string) (string, error) {
	row := q.db.QueryRow(ctx, latestAssistantMood, sessionID)
	var mood string
	err := row.Scan(&mood)
	return mood, err
}

const latestSessionWithTurns = `-- name: LatestSessionWithTurns :one
SELECT s.id, count(t.id)::int AS turn_count
  FROM conversation_sessions s
  JOIN dialogue_turns t ON t.session_id = s.id
 WHERE s.user_id = $1 AND s.scenario_id = $2 AND s.discarded_at IS NULL
 GROUP BY s.id, s.started_at
 ORDER BY s.started_at DESC
 LIMIT 1
`

type LatestSessionWithTurnsParams struct {
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
}

type LatestSessionWithTurnsRow struct {
	ID        string `json:"id"`
	TurnCount int    `json:"turn_count"`
}

// The most recent session for this learner + scenario that actually has turns.
// Sessions carry no completion flag (only started_at), so "resumable" is defined
// by having said something — an empty session is nothing to come back to.
func (q *Queries) LatestSessionWithTurns(ctx context.Context, arg LatestSessionWithTurnsParams) (LatestSessionWithTurnsRow, error) {
	row := q.db.QueryRow(ctx, latestSessionWithTurns, arg.UserID, arg.ScenarioID)
	var i LatestSessionWithTurnsRow
	err := row.Scan(&i.ID, &i.TurnCount)
	return i, err
}

const sessionHistory = `-- name: SessionHistory :many
SELECT role, content, mood FROM dialogue_turns WHERE session_id = $1 ORDER BY created_at LIMIT $2
`

type SessionHistoryParams struct {
	SessionID string `json:"session_id"`
	Limit     int32  `json:"limit"`
}

type SessionHistoryRow struct {
	Role    string `json:"role"`
	Content string `json:"content"`
	Mood    string `json:"mood"`
}

func (q *Queries) SessionHistory(ctx context.Context, arg SessionHistoryParams) ([]SessionHistoryRow, error) {
	rows, err := q.db.Query(ctx, sessionHistory, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionHistoryRow
	for rows.Next() {
		var i SessionHistoryRow
		if err := rows.Scan(&i.Role, &i.Content, &i.Mood); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
