// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package sqlc

import (
	"context"
)

const appendTurn = `-- name: AppendTurn :exec
INSERT INTO dialogue_turns (session_id, role, content) VALUES ($1, $2, $3)
`

type AppendTurnParams struct {
	SessionID string `json:"session_id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
}

func (q *Queries) AppendTurn(ctx context.Context, arg AppendTurnParams) error {
	_, err := q.db.Exec(ctx, appendTurn, arg.SessionID, arg.Role, arg.Content)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO conversation_sessions (user_id, scenario_id) VALUES ($1, $2) RETURNING id
`

type CreateSessionParams struct {
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (string, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.ScenarioID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, scenario_id FROM conversation_sessions WHERE id = $1
`

type GetSessionRow struct {
	ID         string `json:"id"`
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(&i.ID, &i.UserID, &i.ScenarioID)
	return i, err
}

const insertCardSchedule = `-- name: InsertCardSchedule :exec
INSERT INTO review_schedules (card_id, due_date) VALUES ($1, CURRENT_DATE)
`

func (q *Queries) InsertCardSchedule(ctx context.Context, cardID string) error {
	_, err := q.db.Exec(ctx, insertCardSchedule, cardID)
	return err
}

const insertCorrection = `-- name: InsertCorrection :exec
INSERT INTO correction_results (user_id, original, corrected, note, topic_tag)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCorrectionParams struct {
	UserID    string `json:"user_id"`
	Original  string `json:"original"`
	Corrected string `json:"corrected"`
	Note      string `json:"note"`
	TopicTag  string `json:"topic_tag"`
}

func (q *Queries) InsertCorrection(ctx context.Context, arg InsertCorrectionParams) error {
	_, err := q.db.Exec(ctx, insertCorrection,
		arg.UserID,
		arg.Original,
		arg.Corrected,
		arg.Note,
		arg.TopicTag,
	)
	return err
}

const insertReviewCard = `-- name: InsertReviewCard :one
INSERT INTO review_cards (user_id, source, front, back, note, topic_tag, scenario_id, context)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id
`

type InsertReviewCardParams struct {
	UserID     string `json:"user_id"`
	Source     string `json:"source"`
	Front      string `json:"front"`
	Back       string `json:"back"`
	Note       string `json:"note"`
	TopicTag   string `json:"topic_tag"`
	ScenarioID string `json:"scenario_id"`
	Context    []byte `json:"context"`
}

func (q *Queries) InsertReviewCard(ctx context.Context, arg InsertReviewCardParams) (string, error) {
	row := q.db.QueryRow(ctx, insertReviewCard,
		arg.UserID,
		arg.Source,
		arg.Front,
		arg.Back,
		arg.Note,
		arg.TopicTag,
		arg.ScenarioID,
		arg.Context,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const sessionHistory = `-- name: SessionHistory :many
SELECT role, content FROM dialogue_turns WHERE session_id = $1 ORDER BY created_at LIMIT $2
`

type SessionHistoryParams struct {
	SessionID string `json:"session_id"`
	Limit     int32  `json:"limit"`
}

type SessionHistoryRow struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (q *Queries) SessionHistory(ctx context.Context, arg SessionHistoryParams) ([]SessionHistoryRow, error) {
	rows, err := q.db.Query(ctx, sessionHistory, arg.SessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionHistoryRow
	for rows.Next() {
		var i SessionHistoryRow
		if err := rows.Scan(&i.Role, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
