// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lesson.sql

package sqlc

import (
	"context"
)

const hasNuanceCard = `-- name: HasNuanceCard :one
SELECT EXISTS (
    SELECT 1 FROM review_cards WHERE user_id = $1 AND source = 'nuance' AND front = $2
)::bool
`

type HasNuanceCardParams struct {
	UserID string `json:"user_id"`
	Front  string `json:"front"`
}

// A reel's 감상 is noted once per word (spec 2-9 §11-8): the card's front is the word.
func (q *Queries) HasNuanceCard(ctx context.Context, arg HasNuanceCardParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasNuanceCard, arg.UserID, arg.Front)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasSentenceCard = `-- name: HasSentenceCard :one
SELECT EXISTS (
    SELECT 1 FROM review_cards WHERE user_id = $1 AND source = 'sentence' AND back = $2
)::bool
`

type HasSentenceCardParams struct {
	UserID string `json:"user_id"`
	Back   string `json:"back"`
}

// A STEP 2 sentence the learner found confusing is filed once (lesson-fidelity-v46 R5):
// the card's back is the sentence.
func (q *Queries) HasSentenceCard(ctx context.Context, arg HasSentenceCardParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasSentenceCard, arg.UserID, arg.Back)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const hasWordCard = `-- name: HasWordCard :one
SELECT EXISTS (
    SELECT 1 FROM review_cards WHERE user_id = $1 AND source = 'word' AND back = $2
)::bool
`

type HasWordCardParams struct {
	UserID string `json:"user_id"`
	Back   string `json:"back"`
}

// A word the learner found confusing is filed once, however many times they say so.
func (q *Queries) HasWordCard(ctx context.Context, arg HasWordCardParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasWordCard, arg.UserID, arg.Back)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listLessonStepClears = `-- name: ListLessonStepClears :many
SELECT step, detail FROM lesson_step_clears WHERE user_id = $1 AND scenario_id = $2
`

type ListLessonStepClearsParams struct {
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
}

type ListLessonStepClearsRow struct {
	Step   string `json:"step"`
	Detail []byte `json:"detail"`
}

func (q *Queries) ListLessonStepClears(ctx context.Context, arg ListLessonStepClearsParams) ([]ListLessonStepClearsRow, error) {
	rows, err := q.db.Query(ctx, listLessonStepClears, arg.UserID, arg.ScenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLessonStepClearsRow
	for rows.Next() {
		var i ListLessonStepClearsRow
		if err := rows.Scan(&i.Step, &i.Detail); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLessonStepClear = `-- name: UpsertLessonStepClear :exec
INSERT INTO lesson_step_clears (user_id, scenario_id, step, detail) VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, scenario_id, step) DO UPDATE SET detail = EXCLUDED.detail
`

type UpsertLessonStepClearParams struct {
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
	Step       string `json:"step"`
	Detail     []byte `json:"detail"`
}

// Finishing a step again keeps the first time it was finished, but takes the newest
// detail: the words missed on the latest run are the ones to bring back.
func (q *Queries) UpsertLessonStepClear(ctx context.Context, arg UpsertLessonStepClearParams) error {
	_, err := q.db.Exec(ctx, upsertLessonStepClear,
		arg.UserID,
		arg.ScenarioID,
		arg.Step,
		arg.Detail,
	)
	return err
}
