// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lesson.sql

package sqlc

import (
	"context"
)

const hasWordCard = `-- name: HasWordCard :one
SELECT EXISTS (
    SELECT 1 FROM review_cards WHERE user_id = $1 AND source = 'word' AND back = $2
)::bool
`

type HasWordCardParams struct {
	UserID string `json:"user_id"`
	Back   string `json:"back"`
}

// A word the learner found confusing is filed once, however many times they say so.
func (q *Queries) HasWordCard(ctx context.Context, arg HasWordCardParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasWordCard, arg.UserID, arg.Back)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listLessonStepClears = `-- name: ListLessonStepClears :many
SELECT step FROM lesson_step_clears WHERE user_id = $1 AND scenario_id = $2
`

type ListLessonStepClearsParams struct {
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
}

func (q *Queries) ListLessonStepClears(ctx context.Context, arg ListLessonStepClearsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listLessonStepClears, arg.UserID, arg.ScenarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var step string
		if err := rows.Scan(&step); err != nil {
			return nil, err
		}
		items = append(items, step)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLessonStepClear = `-- name: UpsertLessonStepClear :exec
INSERT INTO lesson_step_clears (user_id, scenario_id, step) VALUES ($1, $2, $3)
ON CONFLICT (user_id, scenario_id, step) DO NOTHING
`

type UpsertLessonStepClearParams struct {
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
	Step       string `json:"step"`
}

// Idempotent: finishing a step twice keeps the first time it was finished.
func (q *Queries) UpsertLessonStepClear(ctx context.Context, arg UpsertLessonStepClearParams) error {
	_, err := q.db.Exec(ctx, upsertLessonStepClear, arg.UserID, arg.ScenarioID, arg.Step)
	return err
}
