// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lounge.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpLoungeCheers = `-- name: BumpLoungeCheers :exec
UPDATE lounge_posts SET cheers = GREATEST(0, cheers + $1::int) WHERE id = $2
`

type BumpLoungeCheersParams struct {
	Delta int    `json:"delta"`
	ID    string `json:"id"`
}

// GREATEST(0, …) so a race that decrements twice cannot leave a negative count
// on screen; the cheer rows remain the truth either way.
func (q *Queries) BumpLoungeCheers(ctx context.Context, arg BumpLoungeCheersParams) error {
	_, err := q.db.Exec(ctx, bumpLoungeCheers, arg.Delta, arg.ID)
	return err
}

const cheerLoungePost = `-- name: CheerLoungePost :execrows
INSERT INTO lounge_post_cheers (post_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CheerLoungePostParams struct {
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
}

// ON CONFLICT DO NOTHING makes this idempotent: a double tap is one cheer, and
// the affected-rows count is what tells the caller whether to bump the counter.
func (q *Queries) CheerLoungePost(ctx context.Context, arg CheerLoungePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, cheerLoungePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createLoungePost = `-- name: CreateLoungePost :one
INSERT INTO lounge_posts (author_id, kind, body, tags, scenario_id, snippet)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at
`

type CreateLoungePostParams struct {
	AuthorID   string   `json:"author_id"`
	Kind       string   `json:"kind"`
	Body       string   `json:"body"`
	Tags       []string `json:"tags"`
	ScenarioID string   `json:"scenario_id"`
	Snippet    []byte   `json:"snippet"`
}

type CreateLoungePostRow struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateLoungePost(ctx context.Context, arg CreateLoungePostParams) (CreateLoungePostRow, error) {
	row := q.db.QueryRow(ctx, createLoungePost,
		arg.AuthorID,
		arg.Kind,
		arg.Body,
		arg.Tags,
		arg.ScenarioID,
		arg.Snippet,
	)
	var i CreateLoungePostRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const loungeFeed = `-- name: LoungeFeed :many
SELECT p.id, p.author_id, p.kind, p.body, p.tags, p.scenario_id, p.snippet,
       p.cheers, p.created_at,
       COALESCE(pr.display_name, '')                      AS author_name,
       COALESCE(pr.destination, '')                       AS author_destination,
       COALESCE(pr.job, '')                               AS author_job,
       COALESCE(g.level, 0)::int                          AS author_level,
       pr.avatar                                          AS author_avatar,
       (c.user_id IS NOT NULL)::bool                      AS cheered
  FROM lounge_posts p
  LEFT JOIN profiles pr     ON pr.user_id = p.author_id
  LEFT JOIN user_progress g ON g.user_id = p.author_id
  LEFT JOIN lounge_post_cheers c ON c.post_id = p.id AND c.user_id = $1
 WHERE p.deleted_at IS NULL
   AND ($3::timestamptz IS NULL OR p.created_at < $3::timestamptz)
 ORDER BY p.created_at DESC
 LIMIT $2
`

type LoungeFeedParams struct {
	UserID string             `json:"user_id"`
	Limit  int32              `json:"limit"`
	Before pgtype.Timestamptz `json:"before"`
}

type LoungeFeedRow struct {
	ID                string             `json:"id"`
	AuthorID          string             `json:"author_id"`
	Kind              string             `json:"kind"`
	Body              string             `json:"body"`
	Tags              []string           `json:"tags"`
	ScenarioID        string             `json:"scenario_id"`
	Snippet           []byte             `json:"snippet"`
	Cheers            int                `json:"cheers"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	AuthorName        string             `json:"author_name"`
	AuthorDestination string             `json:"author_destination"`
	AuthorJob         string             `json:"author_job"`
	AuthorLevel       int                `json:"author_level"`
	AuthorAvatar      []byte             `json:"author_avatar"`
	Cheered           bool               `json:"cheered"`
}

// One page of the feed, newest first, with the author's display name and the
// reader's own cheer state joined in.
//
// `cheered` is per-reader, so it cannot be cached on the row: two people looking
// at the same post see different buttons. The count CAN be cached (posts.cheers)
// and is, because a feed page would otherwise count rows per post.
func (q *Queries) LoungeFeed(ctx context.Context, arg LoungeFeedParams) ([]LoungeFeedRow, error) {
	rows, err := q.db.Query(ctx, loungeFeed, arg.UserID, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LoungeFeedRow
	for rows.Next() {
		var i LoungeFeedRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Kind,
			&i.Body,
			&i.Tags,
			&i.ScenarioID,
			&i.Snippet,
			&i.Cheers,
			&i.CreatedAt,
			&i.AuthorName,
			&i.AuthorDestination,
			&i.AuthorJob,
			&i.AuthorLevel,
			&i.AuthorAvatar,
			&i.Cheered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const loungePostAuthor = `-- name: LoungePostAuthor :one
SELECT author_id FROM lounge_posts WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) LoungePostAuthor(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, loungePostAuthor, id)
	var author_id string
	err := row.Scan(&author_id)
	return author_id, err
}

const loungePostsToday = `-- name: LoungePostsToday :one
SELECT count(*)::int FROM lounge_posts
 WHERE author_id = $1 AND created_at > now() - interval '24 hours'
`

// How many posts this author has made in the last 24h — the rate limit reads it.
func (q *Queries) LoungePostsToday(ctx context.Context, authorID string) (int, error) {
	row := q.db.QueryRow(ctx, loungePostsToday, authorID)
	var column_1 int
	err := row.Scan(&column_1)
	return column_1, err
}

const reportLoungePost = `-- name: ReportLoungePost :exec
INSERT INTO lounge_reports (post_id, user_id, reason) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ReportLoungePostParams struct {
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
	Reason string `json:"reason"`
}

func (q *Queries) ReportLoungePost(ctx context.Context, arg ReportLoungePostParams) error {
	_, err := q.db.Exec(ctx, reportLoungePost, arg.PostID, arg.UserID, arg.Reason)
	return err
}

const softDeleteLoungePost = `-- name: SoftDeleteLoungePost :exec
UPDATE lounge_posts SET deleted_at = now()
 WHERE id = $1 AND author_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLoungePostParams struct {
	ID       string `json:"id"`
	AuthorID string `json:"author_id"`
}

// Only the author's own post. The row stays: a deleted post is still evidence
// for a report filed against it.
func (q *Queries) SoftDeleteLoungePost(ctx context.Context, arg SoftDeleteLoungePostParams) error {
	_, err := q.db.Exec(ctx, softDeleteLoungePost, arg.ID, arg.AuthorID)
	return err
}

const uncheerLoungePost = `-- name: UncheerLoungePost :execrows
DELETE FROM lounge_post_cheers WHERE post_id = $1 AND user_id = $2
`

type UncheerLoungePostParams struct {
	PostID string `json:"post_id"`
	UserID string `json:"user_id"`
}

func (q *Queries) UncheerLoungePost(ctx context.Context, arg UncheerLoungePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, uncheerLoungePost, arg.PostID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
