// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	UserID    string             `json:"user_id"`
	Provider  string             `json:"provider"`
	SubjectID string             `json:"subject_id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ContentMetum struct {
	K string `json:"k"`
	V string `json:"v"`
}

type Department struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Ward       string `json:"ward"`
	NameKo     string `json:"name_ko"`
	NameEn     string `json:"name_en"`
	Color      string `json:"color"`
}

type Event struct {
	ID            string `json:"id"`
	Profession    string `json:"profession"`
	Title         string `json:"title"`
	Ward          string `json:"ward"`
	Category      string `json:"category"`
	Tier          int    `json:"tier"`
	Tags          []byte `json:"tags"`
	Delivery      string `json:"delivery"`
	Prerequisites []byte `json:"prerequisites"`
	FollowUps     []byte `json:"follow_ups"`
	Related       []byte `json:"related"`
	Scenarios     []byte `json:"scenarios"`
}

type Interior struct {
	ID          string `json:"id"`
	Profession  string `json:"profession"`
	DeptID      string `json:"dept_id"`
	Cols        int    `json:"cols"`
	Rows        int    `json:"rows"`
	PlayerStart []byte `json:"player_start"`
	FloorTheme  string `json:"floor_theme"`
	Regions     []byte `json:"regions"`
	Rooms       []byte `json:"rooms"`
	Objects     []byte `json:"objects"`
	Hotspots    []byte `json:"hotspots"`
}

type Phrase struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Ko         string `json:"ko"`
	En         string `json:"en"`
	Note       string `json:"note"`
	Tag        string `json:"tag"`
}

type Profile struct {
	UserID      string             `json:"user_id"`
	Job         string             `json:"job"`
	NativeLang  string             `json:"native_lang"`
	Destination string             `json:"destination"`
	EnLevel     string             `json:"en_level"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Quiz struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Type       string `json:"type"`
	Title      string `json:"title"`
}

type ReviewCard struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Source      string             `json:"source"`
	Front       string             `json:"front"`
	Back        string             `json:"back"`
	Note        string             `json:"note"`
	TopicTag    string             `json:"topic_tag"`
	MasteryPips int                `json:"mastery_pips"`
	Favorite    bool               `json:"favorite"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ReviewSchedule struct {
	CardID       string             `json:"card_id"`
	Ease         float64            `json:"ease"`
	IntervalDays int                `json:"interval_days"`
	Reps         int                `json:"reps"`
	DueDate      time.Time          `json:"due_date"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Scenario struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	EventID    string `json:"event_id"`
	Title      string `json:"title"`
	Tagline    string `json:"tagline"`
	Goals      []byte `json:"goals"`
	Guardrails []byte `json:"guardrails"`
	KeyPhrases []byte `json:"key_phrases"`
	Steps      []byte `json:"steps"`
}

type ScenarioAttempt struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	ScenarioID     string             `json:"scenario_id"`
	ContentVersion string             `json:"content_version"`
	State          string             `json:"state"`
	Score          int                `json:"score"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ClearedAt      pgtype.Timestamptz `json:"cleared_at"`
}

type User struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserProgress struct {
	UserID              string             `json:"user_id"`
	Xp                  int                `json:"xp"`
	Level               int                `json:"level"`
	Rank                string             `json:"rank"`
	PatientSatisfaction int                `json:"patient_satisfaction"`
	PeerTrust           int                `json:"peer_trust"`
	EmergencyResponse   int                `json:"emergency_response"`
	StreakCurrent       int                `json:"streak_current"`
	StreakLongest       int                `json:"streak_longest"`
	LastActiveDate      pgtype.Date        `json:"last_active_date"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}
