// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	UserID    string             `json:"user_id"`
	Provider  string             `json:"provider"`
	SubjectID string             `json:"subject_id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Cheer struct {
	ID         string             `json:"id"`
	FromUserID string             `json:"from_user_id"`
	ToUserID   string             `json:"to_user_id"`
	Preset     string             `json:"preset"`
	Message    string             `json:"message"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ReadAt     pgtype.Timestamptz `json:"read_at"`
}

type ColleagueLink struct {
	OwnerID   string             `json:"owner_id"`
	OtherID   string             `json:"other_id"`
	Relation  string             `json:"relation"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ColleaguePref struct {
	UserID      string             `json:"user_id"`
	ShareStatus bool               `json:"share_status"`
	ShareWeekly bool               `json:"share_weekly"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ColleagueRequest struct {
	ID          string             `json:"id"`
	FromUserID  string             `json:"from_user_id"`
	ToUserID    string             `json:"to_user_id"`
	Relation    string             `json:"relation"`
	Code        string             `json:"code"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
}

type ContentMetum struct {
	K string `json:"k"`
	V string `json:"v"`
}

type ConversationSession struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	ScenarioID  string             `json:"scenario_id"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	DiscardedAt pgtype.Timestamptz `json:"discarded_at"`
}

type CorrectionResult struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	Original  string             `json:"original"`
	Corrected string             `json:"corrected"`
	Note      string             `json:"note"`
	TopicTag  string             `json:"topic_tag"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DailyEventSet struct {
	UserID      string             `json:"user_id"`
	LocalDate   string             `json:"local_date"`
	ScenarioIds []byte             `json:"scenario_ids"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	AdGrants    int                `json:"ad_grants"`
}

type DailyPage struct {
	UserID     string             `json:"user_id"`
	LocalDate  string             `json:"local_date"`
	ScenarioID string             `json:"scenario_id"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
}

type Department struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Ward       string `json:"ward"`
	NameKo     string `json:"name_ko"`
	NameEn     string `json:"name_en"`
	Color      string `json:"color"`
}

type DialogueTurn struct {
	ID        string             `json:"id"`
	SessionID string             `json:"session_id"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Mood      string             `json:"mood"`
}

type Event struct {
	ID            string `json:"id"`
	Profession    string `json:"profession"`
	Title         string `json:"title"`
	Ward          string `json:"ward"`
	Category      string `json:"category"`
	Tier          int    `json:"tier"`
	Tags          []byte `json:"tags"`
	Delivery      string `json:"delivery"`
	Prerequisites []byte `json:"prerequisites"`
	FollowUps     []byte `json:"follow_ups"`
	Related       []byte `json:"related"`
	Scenarios     []byte `json:"scenarios"`
}

type HiddenMissionProgress struct {
	UserID    string             `json:"user_id"`
	MissionID string             `json:"mission_id"`
	FoundAt   pgtype.Timestamptz `json:"found_at"`
}

type Interior struct {
	ID          string `json:"id"`
	Profession  string `json:"profession"`
	DeptID      string `json:"dept_id"`
	Cols        int    `json:"cols"`
	Rows        int    `json:"rows"`
	PlayerStart []byte `json:"player_start"`
	FloorTheme  string `json:"floor_theme"`
	Regions     []byte `json:"regions"`
	Rooms       []byte `json:"rooms"`
	Objects     []byte `json:"objects"`
	Hotspots    []byte `json:"hotspots"`
	Collision   []byte `json:"collision"`
}

type InviteCode struct {
	Code      string             `json:"code"`
	UserID    string             `json:"user_id"`
	Relation  string             `json:"relation"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int                `json:"max_uses"`
	Uses      int                `json:"uses"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

type Phrase struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Ko         string `json:"ko"`
	En         string `json:"en"`
	Note       string `json:"note"`
	Tag        string `json:"tag"`
}

type Profile struct {
	UserID        string             `json:"user_id"`
	Job           string             `json:"job"`
	NativeLang    string             `json:"native_lang"`
	Destination   string             `json:"destination"`
	TargetLevel   string             `json:"target_level"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	TargetLang    string             `json:"target_lang"`
	Onboarded     bool               `json:"onboarded"`
	EquippedTitle string             `json:"equipped_title"`
	UiLang        string             `json:"ui_lang"`
	DisplayName   string             `json:"display_name"`
}

type Quiz struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	Type       string `json:"type"`
	Title      string `json:"title"`
	Content    []byte `json:"content"`
}

type ReviewCard struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	Source      string             `json:"source"`
	Front       string             `json:"front"`
	Back        string             `json:"back"`
	Note        string             `json:"note"`
	TopicTag    string             `json:"topic_tag"`
	MasteryPips int                `json:"mastery_pips"`
	Favorite    bool               `json:"favorite"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ScenarioID  string             `json:"scenario_id"`
	Context     []byte             `json:"context"`
}

type ReviewSchedule struct {
	CardID       string             `json:"card_id"`
	Ease         float64            `json:"ease"`
	IntervalDays int                `json:"interval_days"`
	Reps         int                `json:"reps"`
	DueDate      time.Time          `json:"due_date"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Scenario struct {
	ID         string `json:"id"`
	Profession string `json:"profession"`
	EventID    string `json:"event_id"`
	Title      string `json:"title"`
	Tagline    string `json:"tagline"`
	Goals      []byte `json:"goals"`
	Guardrails []byte `json:"guardrails"`
	KeyPhrases []byte `json:"key_phrases"`
	Steps      []byte `json:"steps"`
	Persona    []byte `json:"persona"`
	Briefing   []byte `json:"briefing"`
	Acuity     string `json:"acuity"`
}

type ScenarioAttempt struct {
	ID             string             `json:"id"`
	UserID         string             `json:"user_id"`
	ScenarioID     string             `json:"scenario_id"`
	ContentVersion string             `json:"content_version"`
	State          string             `json:"state"`
	Score          int                `json:"score"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	ClearedAt      pgtype.Timestamptz `json:"cleared_at"`
	Grade          pgtype.Int4        `json:"grade"`
	Guide          string             `json:"guide"`
}

type SpeechAttempt struct {
	ID            string             `json:"id"`
	UserID        string             `json:"user_id"`
	SentenceKey   string             `json:"sentence_key"`
	ReferenceText string             `json:"reference_text"`
	Locale        string             `json:"locale"`
	AttemptNo     int                `json:"attempt_no"`
	Recognized    string             `json:"recognized"`
	Overall       float64            `json:"overall"`
	Accuracy      float64            `json:"accuracy"`
	Fluency       float64            `json:"fluency"`
	Completeness  float64            `json:"completeness"`
	Prosody       pgtype.Float4      `json:"prosody"`
	DurationMs    int                `json:"duration_ms"`
	Words         []byte             `json:"words"`
	ScenarioID    string             `json:"scenario_id"`
	ReviewCardID  pgtype.UUID        `json:"review_card_id"`
	Origin        string             `json:"origin"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	SessionID     string             `json:"session_id"`
}

type SpeechPhonemeScore struct {
	AttemptID string             `json:"attempt_id"`
	UserID    string             `json:"user_id"`
	Phoneme   string             `json:"phoneme"`
	Accuracy  float64            `json:"accuracy"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SpeechReference struct {
	SentenceKey   string             `json:"sentence_key"`
	ReferenceText string             `json:"reference_text"`
	Locale        string             `json:"locale"`
	Ipa           string             `json:"ipa"`
	Words         []byte             `json:"words"`
	DurationMs    int                `json:"duration_ms"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AudioWav      []byte             `json:"audio_wav"`
}

type User struct {
	ID        string             `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type UserPresence struct {
	UserID     string             `json:"user_id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ScenarioID string             `json:"scenario_id"`
	Label      string             `json:"label"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UserProgress struct {
	UserID         string             `json:"user_id"`
	Xp             int                `json:"xp"`
	Level          int                `json:"level"`
	Rank           string             `json:"rank"`
	StreakCurrent  int                `json:"streak_current"`
	StreakLongest  int                `json:"streak_longest"`
	LastActiveDate pgtype.Date        `json:"last_active_date"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type UserReputation struct {
	UserID    string             `json:"user_id"`
	Dimension string             `json:"dimension"`
	Value     int                `json:"value"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
