// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const dueCards = `-- name: DueCards :many
SELECT c.id, c.source, c.front, c.back, c.note, c.topic_tag, c.mastery_pips, c.favorite,
       s.ease, s.interval_days, s.reps, s.due_date, c.scenario_id, c.context
FROM review_cards c JOIN review_schedules s ON s.card_id = c.id
WHERE c.user_id = $1 AND s.due_date <= $2 ORDER BY s.due_date LIMIT $3
`

type DueCardsParams struct {
	UserID  string    `json:"user_id"`
	DueDate time.Time `json:"due_date"`
	Limit   int32     `json:"limit"`
}

type DueCardsRow struct {
	ID           string    `json:"id"`
	Source       string    `json:"source"`
	Front        string    `json:"front"`
	Back         string    `json:"back"`
	Note         string    `json:"note"`
	TopicTag     string    `json:"topic_tag"`
	MasteryPips  int       `json:"mastery_pips"`
	Favorite     bool      `json:"favorite"`
	Ease         float64   `json:"ease"`
	IntervalDays int       `json:"interval_days"`
	Reps         int       `json:"reps"`
	DueDate      time.Time `json:"due_date"`
	ScenarioID   string    `json:"scenario_id"`
	Context      []byte    `json:"context"`
}

func (q *Queries) DueCards(ctx context.Context, arg DueCardsParams) ([]DueCardsRow, error) {
	rows, err := q.db.Query(ctx, dueCards, arg.UserID, arg.DueDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueCardsRow
	for rows.Next() {
		var i DueCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Front,
			&i.Back,
			&i.Note,
			&i.TopicTag,
			&i.MasteryPips,
			&i.Favorite,
			&i.Ease,
			&i.IntervalDays,
			&i.Reps,
			&i.DueDate,
			&i.ScenarioID,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardForUser = `-- name: GetCardForUser :one
SELECT c.id, c.source, c.front, c.back, c.note, c.topic_tag, c.mastery_pips, c.favorite,
       s.ease, s.interval_days, s.reps, s.due_date
FROM review_cards c JOIN review_schedules s ON s.card_id = c.id
WHERE c.user_id = $1 AND c.id = $2
`

type GetCardForUserParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetCardForUserRow struct {
	ID           string    `json:"id"`
	Source       string    `json:"source"`
	Front        string    `json:"front"`
	Back         string    `json:"back"`
	Note         string    `json:"note"`
	TopicTag     string    `json:"topic_tag"`
	MasteryPips  int       `json:"mastery_pips"`
	Favorite     bool      `json:"favorite"`
	Ease         float64   `json:"ease"`
	IntervalDays int       `json:"interval_days"`
	Reps         int       `json:"reps"`
	DueDate      time.Time `json:"due_date"`
}

func (q *Queries) GetCardForUser(ctx context.Context, arg GetCardForUserParams) (GetCardForUserRow, error) {
	row := q.db.QueryRow(ctx, getCardForUser, arg.UserID, arg.ID)
	var i GetCardForUserRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Front,
		&i.Back,
		&i.Note,
		&i.TopicTag,
		&i.MasteryPips,
		&i.Favorite,
		&i.Ease,
		&i.IntervalDays,
		&i.Reps,
		&i.DueDate,
	)
	return i, err
}

const getProgress = `-- name: GetProgress :one
SELECT xp, level, rank, patient_satisfaction, peer_trust, emergency_response, streak_current, streak_longest
FROM user_progress WHERE user_id = $1
`

type GetProgressRow struct {
	Xp                  int    `json:"xp"`
	Level               int    `json:"level"`
	Rank                string `json:"rank"`
	PatientSatisfaction int    `json:"patient_satisfaction"`
	PeerTrust           int    `json:"peer_trust"`
	EmergencyResponse   int    `json:"emergency_response"`
	StreakCurrent       int    `json:"streak_current"`
	StreakLongest       int    `json:"streak_longest"`
}

func (q *Queries) GetProgress(ctx context.Context, userID string) (GetProgressRow, error) {
	row := q.db.QueryRow(ctx, getProgress, userID)
	var i GetProgressRow
	err := row.Scan(
		&i.Xp,
		&i.Level,
		&i.Rank,
		&i.PatientSatisfaction,
		&i.PeerTrust,
		&i.EmergencyResponse,
		&i.StreakCurrent,
		&i.StreakLongest,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO scenario_attempts (user_id, scenario_id, state, score, cleared_at)
VALUES ($1, $2, 'cleared', $3, now())
`

type InsertAttemptParams struct {
	UserID     string `json:"user_id"`
	ScenarioID string `json:"scenario_id"`
	Score      int    `json:"score"`
}

func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt, arg.UserID, arg.ScenarioID, arg.Score)
	return err
}

const updateCardMastery = `-- name: UpdateCardMastery :exec
UPDATE review_cards SET mastery_pips = $2 WHERE id = $1
`

type UpdateCardMasteryParams struct {
	ID          string `json:"id"`
	MasteryPips int    `json:"mastery_pips"`
}

func (q *Queries) UpdateCardMastery(ctx context.Context, arg UpdateCardMasteryParams) error {
	_, err := q.db.Exec(ctx, updateCardMastery, arg.ID, arg.MasteryPips)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE review_schedules SET ease = $2, interval_days = $3, reps = $4, due_date = $5, updated_at = now()
WHERE card_id = $1
`

type UpdateScheduleParams struct {
	CardID       string    `json:"card_id"`
	Ease         float64   `json:"ease"`
	IntervalDays int       `json:"interval_days"`
	Reps         int       `json:"reps"`
	DueDate      time.Time `json:"due_date"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.Exec(ctx, updateSchedule,
		arg.CardID,
		arg.Ease,
		arg.IntervalDays,
		arg.Reps,
		arg.DueDate,
	)
	return err
}

const upsertProgressOnAttempt = `-- name: UpsertProgressOnAttempt :exec
INSERT INTO user_progress (user_id, xp, level, streak_current, streak_longest, last_active_date)
VALUES ($1, $2, 1 + ($2 / 100), 1, 1, $3)
ON CONFLICT (user_id) DO UPDATE SET
    xp    = user_progress.xp + $2,
    level = 1 + ((user_progress.xp + $2) / 100),
    streak_current = CASE
        WHEN user_progress.last_active_date = $3 THEN user_progress.streak_current
        WHEN user_progress.last_active_date = $3 - 1 THEN user_progress.streak_current + 1
        ELSE 1 END,
    streak_longest = GREATEST(user_progress.streak_longest, CASE
        WHEN user_progress.last_active_date = $3 THEN user_progress.streak_current
        WHEN user_progress.last_active_date = $3 - 1 THEN user_progress.streak_current + 1
        ELSE 1 END),
    last_active_date = $3,
    updated_at = now()
`

type UpsertProgressOnAttemptParams struct {
	UserID         string      `json:"user_id"`
	Xp             int         `json:"xp"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
}

func (q *Queries) UpsertProgressOnAttempt(ctx context.Context, arg UpsertProgressOnAttemptParams) error {
	_, err := q.db.Exec(ctx, upsertProgressOnAttempt, arg.UserID, arg.Xp, arg.LastActiveDate)
	return err
}
