// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: progress.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptDailyPage = `-- name: AcceptDailyPage :one
UPDATE daily_pages SET accepted_at = COALESCE(accepted_at, now())
 WHERE user_id = $1 AND local_date = $2
RETURNING scenario_id, accepted_at
`

type AcceptDailyPageParams struct {
	UserID    string `json:"user_id"`
	LocalDate string `json:"local_date"`
}

type AcceptDailyPageRow struct {
	ScenarioID string             `json:"scenario_id"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
}

// Taking the call. Idempotent: accepting twice keeps the first timestamp, because the
// "did they actually go?" check below is measured from it.
func (q *Queries) AcceptDailyPage(ctx context.Context, arg AcceptDailyPageParams) (AcceptDailyPageRow, error) {
	row := q.db.QueryRow(ctx, acceptDailyPage, arg.UserID, arg.LocalDate)
	var i AcceptDailyPageRow
	err := row.Scan(&i.ScenarioID, &i.AcceptedAt)
	return i, err
}

const addBonusXP = `-- name: AddBonusXP :one
UPDATE user_progress SET xp = xp + $2, updated_at = now()
 WHERE user_id = $1
RETURNING xp
`

type AddBonusXPParams struct {
	UserID string `json:"user_id"`
	Xp     int    `json:"xp"`
}

// A bare XP grant, for rewards that are not a scenario attempt. RecordAttempt is the
// only other XP path and it logs an attempt row, which would put a phantom run in the
// learner's history.
func (q *Queries) AddBonusXP(ctx context.Context, arg AddBonusXPParams) (int, error) {
	row := q.db.QueryRow(ctx, addBonusXP, arg.UserID, arg.Xp)
	var xp int
	err := row.Scan(&xp)
	return xp, err
}

const clearedPassGuides = `-- name: ClearedPassGuides :many
SELECT DISTINCT scenario_id, CASE WHEN guide = 'choices' THEN 'choices' ELSE 'free' END AS guide
  FROM scenario_attempts
 WHERE user_id = $1 AND state = 'cleared'
`

type ClearedPassGuidesRow struct {
	ScenarioID string `json:"scenario_id"`
	Guide      string `json:"guide"`
}

// Which scenarios the learner has finished, and with how much help.
//
// Both sets are needed, not just the guided one. A dialogue appears twice in a
// curriculum — guided, then alone — and reading both entries off one "is it cleared"
// flag would tick them together: the second would be born complete. A clear made with
// three replies on screen is not a clear made alone.
//
// The pre-feature default is ” and those runs had no help, so they read as unaided.
func (q *Queries) ClearedPassGuides(ctx context.Context, userID string) ([]ClearedPassGuidesRow, error) {
	rows, err := q.db.Query(ctx, clearedPassGuides, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClearedPassGuidesRow
	for rows.Next() {
		var i ClearedPassGuidesRow
		if err := rows.Scan(&i.ScenarioID, &i.Guide); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeDailyPageIfAttempted = `-- name: CompleteDailyPageIfAttempted :one
UPDATE daily_pages SET answered_at = now()
 WHERE daily_pages.user_id = $1 AND daily_pages.local_date = $2
   AND accepted_at IS NOT NULL
   AND answered_at IS NULL
   AND EXISTS (
     SELECT 1 FROM scenario_attempts a
      WHERE a.user_id = daily_pages.user_id
        AND a.scenario_id = daily_pages.scenario_id
        AND a.started_at >= daily_pages.accepted_at
   )
RETURNING scenario_id
`

type CompleteDailyPageIfAttemptedParams struct {
	UserID    string `json:"user_id"`
	LocalDate string `json:"local_date"`
}

// Pays the call off, but ONLY once the learner actually started the scenario it points
// at, after accepting it. Tapping 지금 응답 and walking straight back out is not
// answering a call.
//
// The WHERE answered_at IS NULL is what makes the bonus payable exactly once: a second
// run returns no row, and the caller then knows not to award XP again.
func (q *Queries) CompleteDailyPageIfAttempted(ctx context.Context, arg CompleteDailyPageIfAttemptedParams) (string, error) {
	row := q.db.QueryRow(ctx, completeDailyPageIfAttempted, arg.UserID, arg.LocalDate)
	var scenario_id string
	err := row.Scan(&scenario_id)
	return scenario_id, err
}

const dueCards = `-- name: DueCards :many
SELECT c.id, c.source, c.front, c.back, c.note, c.topic_tag, c.mastery_pips, c.favorite,
       s.ease, s.interval_days, s.reps, s.due_date, c.scenario_id, c.context
FROM review_cards c JOIN review_schedules s ON s.card_id = c.id
WHERE c.user_id = $1 AND s.due_date <= $2 ORDER BY s.due_date LIMIT $3
`

type DueCardsParams struct {
	UserID  string    `json:"user_id"`
	DueDate time.Time `json:"due_date"`
	Limit   int32     `json:"limit"`
}

type DueCardsRow struct {
	ID           string    `json:"id"`
	Source       string    `json:"source"`
	Front        string    `json:"front"`
	Back         string    `json:"back"`
	Note         string    `json:"note"`
	TopicTag     string    `json:"topic_tag"`
	MasteryPips  int       `json:"mastery_pips"`
	Favorite     bool      `json:"favorite"`
	Ease         float64   `json:"ease"`
	IntervalDays int       `json:"interval_days"`
	Reps         int       `json:"reps"`
	DueDate      time.Time `json:"due_date"`
	ScenarioID   string    `json:"scenario_id"`
	Context      []byte    `json:"context"`
}

func (q *Queries) DueCards(ctx context.Context, arg DueCardsParams) ([]DueCardsRow, error) {
	rows, err := q.db.Query(ctx, dueCards, arg.UserID, arg.DueDate, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueCardsRow
	for rows.Next() {
		var i DueCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.Front,
			&i.Back,
			&i.Note,
			&i.TopicTag,
			&i.MasteryPips,
			&i.Favorite,
			&i.Ease,
			&i.IntervalDays,
			&i.Reps,
			&i.DueDate,
			&i.ScenarioID,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const foundMissions = `-- name: FoundMissions :many
SELECT mission_id FROM hidden_mission_progress WHERE user_id = $1 ORDER BY found_at
`

func (q *Queries) FoundMissions(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, foundMissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var mission_id string
		if err := rows.Scan(&mission_id); err != nil {
			return nil, err
		}
		items = append(items, mission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCardForUser = `-- name: GetCardForUser :one
SELECT c.id, c.source, c.front, c.back, c.note, c.topic_tag, c.mastery_pips, c.favorite,
       s.ease, s.interval_days, s.reps, s.due_date
FROM review_cards c JOIN review_schedules s ON s.card_id = c.id
WHERE c.user_id = $1 AND c.id = $2
`

type GetCardForUserParams struct {
	UserID string `json:"user_id"`
	ID     string `json:"id"`
}

type GetCardForUserRow struct {
	ID           string    `json:"id"`
	Source       string    `json:"source"`
	Front        string    `json:"front"`
	Back         string    `json:"back"`
	Note         string    `json:"note"`
	TopicTag     string    `json:"topic_tag"`
	MasteryPips  int       `json:"mastery_pips"`
	Favorite     bool      `json:"favorite"`
	Ease         float64   `json:"ease"`
	IntervalDays int       `json:"interval_days"`
	Reps         int       `json:"reps"`
	DueDate      time.Time `json:"due_date"`
}

func (q *Queries) GetCardForUser(ctx context.Context, arg GetCardForUserParams) (GetCardForUserRow, error) {
	row := q.db.QueryRow(ctx, getCardForUser, arg.UserID, arg.ID)
	var i GetCardForUserRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.Front,
		&i.Back,
		&i.Note,
		&i.TopicTag,
		&i.MasteryPips,
		&i.Favorite,
		&i.Ease,
		&i.IntervalDays,
		&i.Reps,
		&i.DueDate,
	)
	return i, err
}

const getDailyPage = `-- name: GetDailyPage :one
SELECT user_id, local_date, scenario_id, issued_at, accepted_at, answered_at
  FROM daily_pages WHERE user_id = $1 AND local_date = $2
`

type GetDailyPageParams struct {
	UserID    string `json:"user_id"`
	LocalDate string `json:"local_date"`
}

type GetDailyPageRow struct {
	UserID     string             `json:"user_id"`
	LocalDate  string             `json:"local_date"`
	ScenarioID string             `json:"scenario_id"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

func (q *Queries) GetDailyPage(ctx context.Context, arg GetDailyPageParams) (GetDailyPageRow, error) {
	row := q.db.QueryRow(ctx, getDailyPage, arg.UserID, arg.LocalDate)
	var i GetDailyPageRow
	err := row.Scan(
		&i.UserID,
		&i.LocalDate,
		&i.ScenarioID,
		&i.IssuedAt,
		&i.AcceptedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const getProgress = `-- name: GetProgress :one
SELECT xp, level, rank, streak_current, streak_longest
FROM user_progress WHERE user_id = $1
`

type GetProgressRow struct {
	Xp            int    `json:"xp"`
	Level         int    `json:"level"`
	Rank          string `json:"rank"`
	StreakCurrent int    `json:"streak_current"`
	StreakLongest int    `json:"streak_longest"`
}

// Unused by any caller (ProgressRepo.GetProgress reads user_progress directly and
// joins user_reputation for standings) but kept generatable. patient_satisfaction/
// peer_trust/emergency_response were dropped in 000020_reputation_kv — this query
// had gone stale (sqlc generate failed) until this fix.
func (q *Queries) GetProgress(ctx context.Context, userID string) (GetProgressRow, error) {
	row := q.db.QueryRow(ctx, getProgress, userID)
	var i GetProgressRow
	err := row.Scan(
		&i.Xp,
		&i.Level,
		&i.Rank,
		&i.StreakCurrent,
		&i.StreakLongest,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :exec
INSERT INTO scenario_attempts (user_id, scenario_id, state, score, grade, guide, cleared_at)
VALUES ($1, $2, $3, $4, $5, $6, CASE WHEN $3 = 'cleared' THEN now() ELSE NULL END)
`

type InsertAttemptParams struct {
	UserID     string      `json:"user_id"`
	ScenarioID string      `json:"scenario_id"`
	State      string      `json:"state"`
	Score      int         `json:"score"`
	Grade      pgtype.Int4 `json:"grade"`
	Guide      string      `json:"guide"`
}

// state is 'cleared' (passed, counts as 완료) or 'attempted' (engaged but below the
// pass score). grade is the 0..100 AI score (NULL for direct/legacy attempts).
// cleared_at is set only on a real clear.
func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) error {
	_, err := q.db.Exec(ctx, insertAttempt,
		arg.UserID,
		arg.ScenarioID,
		arg.State,
		arg.Score,
		arg.Grade,
		arg.Guide,
	)
	return err
}

const insertDailyPage = `-- name: InsertDailyPage :one
INSERT INTO daily_pages (user_id, local_date, scenario_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, local_date) DO UPDATE SET local_date = daily_pages.local_date
RETURNING user_id, local_date, scenario_id, issued_at, accepted_at, answered_at
`

type InsertDailyPageParams struct {
	UserID     string `json:"user_id"`
	LocalDate  string `json:"local_date"`
	ScenarioID string `json:"scenario_id"`
}

type InsertDailyPageRow struct {
	UserID     string             `json:"user_id"`
	LocalDate  string             `json:"local_date"`
	ScenarioID string             `json:"scenario_id"`
	IssuedAt   pgtype.Timestamptz `json:"issued_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	AnsweredAt pgtype.Timestamptz `json:"answered_at"`
}

// DO NOTHING then RETURNING would give no row on a conflict, so the caller could not
// tell "already issued" from "insert failed". DO UPDATE on its own key returns the
// existing row untouched, which is exactly "give me today's call, issuing it if this is
// the first look".
func (q *Queries) InsertDailyPage(ctx context.Context, arg InsertDailyPageParams) (InsertDailyPageRow, error) {
	row := q.db.QueryRow(ctx, insertDailyPage, arg.UserID, arg.LocalDate, arg.ScenarioID)
	var i InsertDailyPageRow
	err := row.Scan(
		&i.UserID,
		&i.LocalDate,
		&i.ScenarioID,
		&i.IssuedAt,
		&i.AcceptedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const listModelAnswerCards = `-- name: ListModelAnswerCards :many
SELECT scenario_id, front, back, note, created_at
  FROM review_cards
 WHERE user_id = $1 AND scenario_id = ANY($2::text[]) AND source <> 'grade'
 ORDER BY scenario_id, created_at
`

type ListModelAnswerCardsParams struct {
	UserID      string   `json:"user_id"`
	ScenarioIds []string `json:"scenario_ids"`
}

type ListModelAnswerCardsRow struct {
	ScenarioID string             `json:"scenario_id"`
	Front      string             `json:"front"`
	Back       string             `json:"back"`
	Note       string             `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// The cards for a page of scenarios, fetched in ONE query rather than per group:
// a page of ten groups would otherwise be ten round trips, and the block's most
// recent group alone would be a second one.
func (q *Queries) ListModelAnswerCards(ctx context.Context, arg ListModelAnswerCardsParams) ([]ListModelAnswerCardsRow, error) {
	rows, err := q.db.Query(ctx, listModelAnswerCards, arg.UserID, arg.ScenarioIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelAnswerCardsRow
	for rows.Next() {
		var i ListModelAnswerCardsRow
		if err := rows.Scan(
			&i.ScenarioID,
			&i.Front,
			&i.Back,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelAnswerScenariosNeedsWork = `-- name: ListModelAnswerScenariosNeedsWork :many
WITH grouped AS (
    SELECT scenario_id,
           COUNT(*)::int  AS corrections,
           MAX(created_at)::timestamptz AS last_at
      FROM review_cards
     WHERE user_id = $1 AND scenario_id <> '' AND source <> 'grade'
     GROUP BY scenario_id
)
SELECT g.scenario_id, g.corrections, g.last_at,
       COALESCE(s.title, '') AS title,
       (SELECT COUNT(*)::int FROM grouped) AS total
  FROM grouped g
  LEFT JOIN scenarios s ON s.id = g.scenario_id
 ORDER BY g.corrections DESC, g.last_at DESC
 LIMIT $2 OFFSET $3
`

type ListModelAnswerScenariosNeedsWorkParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListModelAnswerScenariosNeedsWorkRow struct {
	ScenarioID  string             `json:"scenario_id"`
	Corrections int                `json:"corrections"`
	LastAt      pgtype.Timestamptz `json:"last_at"`
	Title       string             `json:"title"`
	Total       int                `json:"total"`
}

// 개선 필요: most corrections first. Ties break by recency so two scenarios with
// the same count are still in a stable, meaningful order. Same projection as the
// recent sort so one repo mapper serves both.
func (q *Queries) ListModelAnswerScenariosNeedsWork(ctx context.Context, arg ListModelAnswerScenariosNeedsWorkParams) ([]ListModelAnswerScenariosNeedsWorkRow, error) {
	rows, err := q.db.Query(ctx, listModelAnswerScenariosNeedsWork, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelAnswerScenariosNeedsWorkRow
	for rows.Next() {
		var i ListModelAnswerScenariosNeedsWorkRow
		if err := rows.Scan(
			&i.ScenarioID,
			&i.Corrections,
			&i.LastAt,
			&i.Title,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelAnswerScenariosRecent = `-- name: ListModelAnswerScenariosRecent :many
WITH grouped AS (
    SELECT scenario_id,
           COUNT(*)::int  AS corrections,
           MAX(created_at)::timestamptz AS last_at
      FROM review_cards
     WHERE user_id = $1 AND scenario_id <> '' AND source <> 'grade'
     GROUP BY scenario_id
)
SELECT g.scenario_id, g.corrections, g.last_at,
       COALESCE(s.title, '') AS title,
       (SELECT COUNT(*)::int FROM grouped) AS total
  FROM grouped g
  LEFT JOIN scenarios s ON s.id = g.scenario_id
 ORDER BY g.last_at DESC
 LIMIT $2 OFFSET $3
`

type ListModelAnswerScenariosRecentParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

type ListModelAnswerScenariosRecentRow struct {
	ScenarioID  string             `json:"scenario_id"`
	Corrections int                `json:"corrections"`
	LastAt      pgtype.Timestamptz `json:"last_at"`
	Title       string             `json:"title"`
	Total       int                `json:"total"`
}

// 시나리오 모범답안, grouped by the scenario the corrections came from
// (04_SCREENS ⑨). One row per scenario, newest activity first.
//
// source <> 'grade' is the whole point of the grouping: a 'grade' card is a
// "you could have said this" suggestion for a sentence the learner never spoke,
// so it has no 내 답변 to strike through and does not belong in a block built on
// 내 답변 vs 모범. Everything else is a real correction (the same rule the app's
// faceOf() applies when drawing a card).
//
// scenario_id <> ” drops cards made outside a scenario: they cannot be grouped
// under one, and a group keyed on ” would collect unrelated cards together.
//
// `total` rides along on every row so the list's count needs no second query.
func (q *Queries) ListModelAnswerScenariosRecent(ctx context.Context, arg ListModelAnswerScenariosRecentParams) ([]ListModelAnswerScenariosRecentRow, error) {
	rows, err := q.db.Query(ctx, listModelAnswerScenariosRecent, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelAnswerScenariosRecentRow
	for rows.Next() {
		var i ListModelAnswerScenariosRecentRow
		if err := rows.Scan(
			&i.ScenarioID,
			&i.Corrections,
			&i.LastAt,
			&i.Title,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordMission = `-- name: RecordMission :exec
INSERT INTO hidden_mission_progress (user_id, mission_id) VALUES ($1, $2)
ON CONFLICT (user_id, mission_id) DO NOTHING
`

type RecordMissionParams struct {
	UserID    string `json:"user_id"`
	MissionID string `json:"mission_id"`
}

func (q *Queries) RecordMission(ctx context.Context, arg RecordMissionParams) error {
	_, err := q.db.Exec(ctx, recordMission, arg.UserID, arg.MissionID)
	return err
}

const updateCardMastery = `-- name: UpdateCardMastery :exec
UPDATE review_cards SET mastery_pips = $2 WHERE id = $1
`

type UpdateCardMasteryParams struct {
	ID          string `json:"id"`
	MasteryPips int    `json:"mastery_pips"`
}

func (q *Queries) UpdateCardMastery(ctx context.Context, arg UpdateCardMasteryParams) error {
	_, err := q.db.Exec(ctx, updateCardMastery, arg.ID, arg.MasteryPips)
	return err
}

const updateSchedule = `-- name: UpdateSchedule :exec
UPDATE review_schedules SET ease = $2, interval_days = $3, reps = $4, due_date = $5, updated_at = now()
WHERE card_id = $1
`

type UpdateScheduleParams struct {
	CardID       string    `json:"card_id"`
	Ease         float64   `json:"ease"`
	IntervalDays int       `json:"interval_days"`
	Reps         int       `json:"reps"`
	DueDate      time.Time `json:"due_date"`
}

func (q *Queries) UpdateSchedule(ctx context.Context, arg UpdateScheduleParams) error {
	_, err := q.db.Exec(ctx, updateSchedule,
		arg.CardID,
		arg.Ease,
		arg.IntervalDays,
		arg.Reps,
		arg.DueDate,
	)
	return err
}

const upsertProgressOnAttempt = `-- name: UpsertProgressOnAttempt :exec
INSERT INTO user_progress (user_id, xp, level, streak_current, streak_longest, last_active_date)
VALUES ($1, $2, 1 + ($2 / 100), 1, 1, $3)
ON CONFLICT (user_id) DO UPDATE SET
    xp    = user_progress.xp + $2,
    level = 1 + ((user_progress.xp + $2) / 100),
    streak_current = CASE
        WHEN user_progress.last_active_date = $3 THEN user_progress.streak_current
        WHEN user_progress.last_active_date = $3 - 1 THEN user_progress.streak_current + 1
        ELSE 1 END,
    streak_longest = GREATEST(user_progress.streak_longest, CASE
        WHEN user_progress.last_active_date = $3 THEN user_progress.streak_current
        WHEN user_progress.last_active_date = $3 - 1 THEN user_progress.streak_current + 1
        ELSE 1 END),
    last_active_date = $3,
    updated_at = now()
`

type UpsertProgressOnAttemptParams struct {
	UserID         string      `json:"user_id"`
	Xp             int         `json:"xp"`
	LastActiveDate pgtype.Date `json:"last_active_date"`
}

func (q *Queries) UpsertProgressOnAttempt(ctx context.Context, arg UpsertProgressOnAttemptParams) error {
	_, err := q.db.Exec(ctx, upsertProgressOnAttempt, arg.UserID, arg.Xp, arg.LastActiveDate)
	return err
}
