// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: speech.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSpeechReference = `-- name: GetSpeechReference :one
SELECT sentence_key, reference_text, locale, ipa, words, duration_ms
  FROM speech_references WHERE sentence_key = $1
`

type GetSpeechReferenceRow struct {
	SentenceKey   string `json:"sentence_key"`
	ReferenceText string `json:"reference_text"`
	Locale        string `json:"locale"`
	Ipa           string `json:"ipa"`
	Words         []byte `json:"words"`
	DurationMs    int    `json:"duration_ms"`
}

func (q *Queries) GetSpeechReference(ctx context.Context, sentenceKey string) (GetSpeechReferenceRow, error) {
	row := q.db.QueryRow(ctx, getSpeechReference, sentenceKey)
	var i GetSpeechReferenceRow
	err := row.Scan(
		&i.SentenceKey,
		&i.ReferenceText,
		&i.Locale,
		&i.Ipa,
		&i.Words,
		&i.DurationMs,
	)
	return i, err
}

const insertPhonemeScore = `-- name: InsertPhonemeScore :exec
INSERT INTO speech_phoneme_scores (attempt_id, user_id, phoneme, accuracy)
VALUES ($1, $2, $3, $4)
`

type InsertPhonemeScoreParams struct {
	AttemptID string  `json:"attempt_id"`
	UserID    string  `json:"user_id"`
	Phoneme   string  `json:"phoneme"`
	Accuracy  float64 `json:"accuracy"`
}

func (q *Queries) InsertPhonemeScore(ctx context.Context, arg InsertPhonemeScoreParams) error {
	_, err := q.db.Exec(ctx, insertPhonemeScore,
		arg.AttemptID,
		arg.UserID,
		arg.Phoneme,
		arg.Accuracy,
	)
	return err
}

const insertSpeechAttempt = `-- name: InsertSpeechAttempt :one
INSERT INTO speech_attempts (
    user_id, sentence_key, reference_text, locale, attempt_no,
    recognized, overall, accuracy, fluency, completeness, prosody,
    duration_ms, words, scenario_id, review_card_id, origin
)
SELECT $1, $2, $3, $4,
       COALESCE(MAX(attempt_no), 0) + 1,
       $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
  FROM speech_attempts
 WHERE user_id = $1 AND sentence_key = $2
RETURNING id, attempt_no
`

type InsertSpeechAttemptParams struct {
	UserID        string        `json:"user_id"`
	SentenceKey   string        `json:"sentence_key"`
	ReferenceText string        `json:"reference_text"`
	Locale        string        `json:"locale"`
	Recognized    string        `json:"recognized"`
	Overall       float64       `json:"overall"`
	Accuracy      float64       `json:"accuracy"`
	Fluency       float64       `json:"fluency"`
	Completeness  float64       `json:"completeness"`
	Prosody       pgtype.Float4 `json:"prosody"`
	DurationMs    int           `json:"duration_ms"`
	Words         []byte        `json:"words"`
	ScenarioID    string        `json:"scenario_id"`
	ReviewCardID  pgtype.UUID   `json:"review_card_id"`
	Origin        string        `json:"origin"`
}

type InsertSpeechAttemptRow struct {
	ID        string `json:"id"`
	AttemptNo int    `json:"attempt_no"`
}

// attempt_no is numbered inside the same statement so two concurrent requests
// cannot claim the same number (an application-side counter would race). A
// unique-violation retry (23505) still lives in the repo for when two racing
// requests compute the same MAX and both try to insert it.
func (q *Queries) InsertSpeechAttempt(ctx context.Context, arg InsertSpeechAttemptParams) (InsertSpeechAttemptRow, error) {
	row := q.db.QueryRow(ctx, insertSpeechAttempt,
		arg.UserID,
		arg.SentenceKey,
		arg.ReferenceText,
		arg.Locale,
		arg.Recognized,
		arg.Overall,
		arg.Accuracy,
		arg.Fluency,
		arg.Completeness,
		arg.Prosody,
		arg.DurationMs,
		arg.Words,
		arg.ScenarioID,
		arg.ReviewCardID,
		arg.Origin,
	)
	var i InsertSpeechAttemptRow
	err := row.Scan(&i.ID, &i.AttemptNo)
	return i, err
}

const listSpeechAttempts = `-- name: ListSpeechAttempts :many
SELECT id, attempt_no, overall, accuracy, fluency, completeness, prosody,
       duration_ms, recognized, words, created_at
  FROM speech_attempts
 WHERE user_id = $1 AND sentence_key = $2
 ORDER BY attempt_no DESC
 LIMIT $3
`

type ListSpeechAttemptsParams struct {
	UserID      string `json:"user_id"`
	SentenceKey string `json:"sentence_key"`
	Limit       int32  `json:"limit"`
}

type ListSpeechAttemptsRow struct {
	ID           string             `json:"id"`
	AttemptNo    int                `json:"attempt_no"`
	Overall      float64            `json:"overall"`
	Accuracy     float64            `json:"accuracy"`
	Fluency      float64            `json:"fluency"`
	Completeness float64            `json:"completeness"`
	Prosody      pgtype.Float4      `json:"prosody"`
	DurationMs   int                `json:"duration_ms"`
	Recognized   string             `json:"recognized"`
	Words        []byte             `json:"words"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSpeechAttempts(ctx context.Context, arg ListSpeechAttemptsParams) ([]ListSpeechAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listSpeechAttempts, arg.UserID, arg.SentenceKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeechAttemptsRow
	for rows.Next() {
		var i ListSpeechAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.AttemptNo,
			&i.Overall,
			&i.Accuracy,
			&i.Fluency,
			&i.Completeness,
			&i.Prosody,
			&i.DurationMs,
			&i.Recognized,
			&i.Words,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSpeechReference = `-- name: PutSpeechReference :exec
INSERT INTO speech_references (sentence_key, reference_text, locale, ipa, words, duration_ms)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (sentence_key) DO NOTHING
`

type PutSpeechReferenceParams struct {
	SentenceKey   string `json:"sentence_key"`
	ReferenceText string `json:"reference_text"`
	Locale        string `json:"locale"`
	Ipa           string `json:"ipa"`
	Words         []byte `json:"words"`
	DurationMs    int    `json:"duration_ms"`
}

func (q *Queries) PutSpeechReference(ctx context.Context, arg PutSpeechReferenceParams) error {
	_, err := q.db.Exec(ctx, putSpeechReference,
		arg.SentenceKey,
		arg.ReferenceText,
		arg.Locale,
		arg.Ipa,
		arg.Words,
		arg.DurationMs,
	)
	return err
}
