// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: speech.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSpeechReference = `-- name: GetSpeechReference :one
SELECT sentence_key, reference_text, locale, ipa, words, duration_ms
  FROM speech_references WHERE sentence_key = $1
`

type GetSpeechReferenceRow struct {
	SentenceKey   string `json:"sentence_key"`
	ReferenceText string `json:"reference_text"`
	Locale        string `json:"locale"`
	Ipa           string `json:"ipa"`
	Words         []byte `json:"words"`
	DurationMs    int    `json:"duration_ms"`
}

// Deliberately does NOT select audio_wav: this is read on every practice-
// screen mount (GET /speech/reference) and the segmentation is all that path
// needs. Fetching a ~320KB blob on every such call would be pure waste — see
// GetSpeechReferenceAudio, used only by the audio route.
func (q *Queries) GetSpeechReference(ctx context.Context, sentenceKey string) (GetSpeechReferenceRow, error) {
	row := q.db.QueryRow(ctx, getSpeechReference, sentenceKey)
	var i GetSpeechReferenceRow
	err := row.Scan(
		&i.SentenceKey,
		&i.ReferenceText,
		&i.Locale,
		&i.Ipa,
		&i.Words,
		&i.DurationMs,
	)
	return i, err
}

const getSpeechReferenceAudio = `-- name: GetSpeechReferenceAudio :one
SELECT audio_wav FROM speech_references WHERE sentence_key = $1
`

func (q *Queries) GetSpeechReferenceAudio(ctx context.Context, sentenceKey string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSpeechReferenceAudio, sentenceKey)
	var audio_wav []byte
	err := row.Scan(&audio_wav)
	return audio_wav, err
}

const insertPhonemeScore = `-- name: InsertPhonemeScore :exec
INSERT INTO speech_phoneme_scores (attempt_id, user_id, phoneme, accuracy)
VALUES ($1, $2, $3, $4)
`

type InsertPhonemeScoreParams struct {
	AttemptID string  `json:"attempt_id"`
	UserID    string  `json:"user_id"`
	Phoneme   string  `json:"phoneme"`
	Accuracy  float64 `json:"accuracy"`
}

func (q *Queries) InsertPhonemeScore(ctx context.Context, arg InsertPhonemeScoreParams) error {
	_, err := q.db.Exec(ctx, insertPhonemeScore,
		arg.AttemptID,
		arg.UserID,
		arg.Phoneme,
		arg.Accuracy,
	)
	return err
}

const insertSpeechAttempt = `-- name: InsertSpeechAttempt :one
INSERT INTO speech_attempts (
    user_id, sentence_key, reference_text, locale, attempt_no,
    recognized, overall, accuracy, fluency, completeness, prosody,
    duration_ms, words, scenario_id, review_card_id, origin, session_id
)
SELECT $1, $2, $3, $4,
       COALESCE(MAX(attempt_no), 0) + 1,
       $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
  FROM speech_attempts
 WHERE user_id = $1 AND sentence_key = $2
RETURNING id, attempt_no
`

type InsertSpeechAttemptParams struct {
	UserID        string        `json:"user_id"`
	SentenceKey   string        `json:"sentence_key"`
	ReferenceText string        `json:"reference_text"`
	Locale        string        `json:"locale"`
	Recognized    string        `json:"recognized"`
	Overall       float64       `json:"overall"`
	Accuracy      float64       `json:"accuracy"`
	Fluency       float64       `json:"fluency"`
	Completeness  float64       `json:"completeness"`
	Prosody       pgtype.Float4 `json:"prosody"`
	DurationMs    int           `json:"duration_ms"`
	Words         []byte        `json:"words"`
	ScenarioID    string        `json:"scenario_id"`
	ReviewCardID  pgtype.UUID   `json:"review_card_id"`
	Origin        string        `json:"origin"`
	SessionID     string        `json:"session_id"`
}

type InsertSpeechAttemptRow struct {
	ID        string `json:"id"`
	AttemptNo int    `json:"attempt_no"`
}

// attempt_no is numbered inside the same statement so two concurrent requests
// cannot claim the same number (an application-side counter would race). A
// unique-violation retry (23505) still lives in the repo for when two racing
// requests compute the same MAX and both try to insert it.
func (q *Queries) InsertSpeechAttempt(ctx context.Context, arg InsertSpeechAttemptParams) (InsertSpeechAttemptRow, error) {
	row := q.db.QueryRow(ctx, insertSpeechAttempt,
		arg.UserID,
		arg.SentenceKey,
		arg.ReferenceText,
		arg.Locale,
		arg.Recognized,
		arg.Overall,
		arg.Accuracy,
		arg.Fluency,
		arg.Completeness,
		arg.Prosody,
		arg.DurationMs,
		arg.Words,
		arg.ScenarioID,
		arg.ReviewCardID,
		arg.Origin,
		arg.SessionID,
	)
	var i InsertSpeechAttemptRow
	err := row.Scan(&i.ID, &i.AttemptNo)
	return i, err
}

const listSessionSpeech = `-- name: ListSessionSpeech :many
SELECT sentence_key, reference_text, recognized, overall, accuracy, fluency,
       completeness, attempt_no, created_at
  FROM (
    SELECT DISTINCT ON (sentence_key)
           sentence_key, reference_text, recognized, overall, accuracy, fluency,
           completeness, attempt_no, created_at,
           MIN(created_at) OVER (PARTITION BY sentence_key) AS first_said
      FROM speech_attempts
     WHERE user_id = $1 AND session_id = $2
     ORDER BY sentence_key, attempt_no DESC
  ) newest
 ORDER BY first_said
`

type ListSessionSpeechParams struct {
	UserID    string `json:"user_id"`
	SessionID string `json:"session_id"`
}

type ListSessionSpeechRow struct {
	SentenceKey   string             `json:"sentence_key"`
	ReferenceText string             `json:"reference_text"`
	Recognized    string             `json:"recognized"`
	Overall       float64            `json:"overall"`
	Accuracy      float64            `json:"accuracy"`
	Fluency       float64            `json:"fluency"`
	Completeness  float64            `json:"completeness"`
	AttemptNo     int                `json:"attempt_no"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Every sentence the player spoke aloud during ONE dialogue run, oldest first,
// for the Scenario Clear review list.
//
// DISTINCT ON collapses re-tries: saying the same sentence three times in one
// session is one sentence with the score they finally reached, not three rows —
// the list is a review of what they said, not of how many attempts it took
// (attempt_no carries that). The outer ORDER BY restores conversation order,
// which DISTINCT ON had to break to pick the newest per key.
//
// That order is by when the sentence was FIRST said, not by the retained row's
// created_at. Ordering by the retained row put a re-tried sentence wherever its
// LAST attempt landed: say A, say B, fix A, and the review listed B before A —
// caught by the Postgres-backed test, and invisible to any fake repo. The window
// function is evaluated before DISTINCT ON, so MIN sees every attempt in the
// session, not just the surviving one.
func (q *Queries) ListSessionSpeech(ctx context.Context, arg ListSessionSpeechParams) ([]ListSessionSpeechRow, error) {
	rows, err := q.db.Query(ctx, listSessionSpeech, arg.UserID, arg.SessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionSpeechRow
	for rows.Next() {
		var i ListSessionSpeechRow
		if err := rows.Scan(
			&i.SentenceKey,
			&i.ReferenceText,
			&i.Recognized,
			&i.Overall,
			&i.Accuracy,
			&i.Fluency,
			&i.Completeness,
			&i.AttemptNo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeakSentencesHigh = `-- name: ListSpeakSentencesHigh :many
WITH latest AS (
    SELECT DISTINCT ON (sentence_key)
           sentence_key, reference_text, recognized, overall, accuracy, fluency,
           completeness, scenario_id, origin, attempt_no, created_at
      FROM speech_attempts
     WHERE user_id = $1
       -- '' means every department. Filtering HERE rather than on the client is what
       -- makes ` + "`" + `total` + "`" + ` and the paging honest: a client-side filter reported "3 of 128"
       -- for "3 matched among the pages loaded so far", and pulled more in as the
       -- learner scrolled.
       AND ($4::text = '' OR split_part(scenario_id, '-', 2) = $4::text)
       -- 문장 검색: the same reasoning as ` + "`" + `dept` + "`" + ` — filtering here is what keeps ` + "`" + `total` + "`" + `
       -- and the paging honest. ILIKE rather than a full-text index: the corpus is one
       -- learner's own sentences (hundreds, not millions), and a substring is what
       -- somebody typing "acetaminophen" actually means.
       AND ($5::text = '' OR reference_text ILIKE '%' || $5::text || '%')
     ORDER BY sentence_key, attempt_no DESC
)
SELECT sentence_key, reference_text, recognized, overall, accuracy, fluency,
       completeness, scenario_id, origin, attempt_no, created_at,
       (SELECT COUNT(*)::int FROM latest) AS total
  FROM latest
 ORDER BY overall DESC, created_at DESC
 LIMIT $3 OFFSET $2
`

type ListSpeakSentencesHighParams struct {
	UserID string `json:"user_id"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
	Dept   string `json:"dept"`
	Q      string `json:"q"`
}

type ListSpeakSentencesHighRow struct {
	SentenceKey   string             `json:"sentence_key"`
	ReferenceText string             `json:"reference_text"`
	Recognized    string             `json:"recognized"`
	Overall       float64            `json:"overall"`
	Accuracy      float64            `json:"accuracy"`
	Fluency       float64            `json:"fluency"`
	Completeness  float64            `json:"completeness"`
	ScenarioID    string             `json:"scenario_id"`
	Origin        string             `json:"origin"`
	AttemptNo     int                `json:"attempt_no"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Total         int                `json:"total"`
}

// 높은 순: best standing first — the mirror of ListSpeakSentencesWeak. Same projection
// so one repo mapper serves all three sorts; only the final ORDER BY differs.
//
// `total` rides along on every row so the list's "N문장 중 M개 표시" needs no
// second round trip per page.
func (q *Queries) ListSpeakSentencesHigh(ctx context.Context, arg ListSpeakSentencesHighParams) ([]ListSpeakSentencesHighRow, error) {
	rows, err := q.db.Query(ctx, listSpeakSentencesHigh,
		arg.UserID,
		arg.Off,
		arg.Lim,
		arg.Dept,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeakSentencesHighRow
	for rows.Next() {
		var i ListSpeakSentencesHighRow
		if err := rows.Scan(
			&i.SentenceKey,
			&i.ReferenceText,
			&i.Recognized,
			&i.Overall,
			&i.Accuracy,
			&i.Fluency,
			&i.Completeness,
			&i.ScenarioID,
			&i.Origin,
			&i.AttemptNo,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeakSentencesRecent = `-- name: ListSpeakSentencesRecent :many
WITH latest AS (
    SELECT DISTINCT ON (sentence_key)
           sentence_key, reference_text, recognized, overall, accuracy, fluency,
           completeness, scenario_id, origin, attempt_no, created_at
      FROM speech_attempts
     WHERE user_id = $1
       -- '' means every department. Filtering HERE rather than on the client is what
       -- makes ` + "`" + `total` + "`" + ` and the paging honest: a client-side filter reported "3 of 128"
       -- for "3 matched among the pages loaded so far", and pulled more in as the
       -- learner scrolled.
       AND ($4::text = '' OR split_part(scenario_id, '-', 2) = $4::text)
       -- 문장 검색: the same reasoning as ` + "`" + `dept` + "`" + ` — filtering here is what keeps ` + "`" + `total` + "`" + `
       -- and the paging honest. ILIKE rather than a full-text index: the corpus is one
       -- learner's own sentences (hundreds, not millions), and a substring is what
       -- somebody typing "acetaminophen" actually means.
       AND ($5::text = '' OR reference_text ILIKE '%' || $5::text || '%')
     ORDER BY sentence_key, attempt_no DESC
)
SELECT sentence_key, reference_text, recognized, overall, accuracy, fluency,
       completeness, scenario_id, origin, attempt_no, created_at,
       (SELECT COUNT(*)::int FROM latest) AS total
  FROM latest
 ORDER BY created_at DESC
 LIMIT $3 OFFSET $2
`

type ListSpeakSentencesRecentParams struct {
	UserID string `json:"user_id"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
	Dept   string `json:"dept"`
	Q      string `json:"q"`
}

type ListSpeakSentencesRecentRow struct {
	SentenceKey   string             `json:"sentence_key"`
	ReferenceText string             `json:"reference_text"`
	Recognized    string             `json:"recognized"`
	Overall       float64            `json:"overall"`
	Accuracy      float64            `json:"accuracy"`
	Fluency       float64            `json:"fluency"`
	Completeness  float64            `json:"completeness"`
	ScenarioID    string             `json:"scenario_id"`
	Origin        string             `json:"origin"`
	AttemptNo     int                `json:"attempt_no"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Total         int                `json:"total"`
}

// 최신: newest first. Same projection as ListSpeakSentencesWeak so one repo
// mapper serves both sorts.
func (q *Queries) ListSpeakSentencesRecent(ctx context.Context, arg ListSpeakSentencesRecentParams) ([]ListSpeakSentencesRecentRow, error) {
	rows, err := q.db.Query(ctx, listSpeakSentencesRecent,
		arg.UserID,
		arg.Off,
		arg.Lim,
		arg.Dept,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeakSentencesRecentRow
	for rows.Next() {
		var i ListSpeakSentencesRecentRow
		if err := rows.Scan(
			&i.SentenceKey,
			&i.ReferenceText,
			&i.Recognized,
			&i.Overall,
			&i.Accuracy,
			&i.Fluency,
			&i.Completeness,
			&i.ScenarioID,
			&i.Origin,
			&i.AttemptNo,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeakSentencesWeak = `-- name: ListSpeakSentencesWeak :many
WITH latest AS (
    SELECT DISTINCT ON (sentence_key)
           sentence_key, reference_text, recognized, overall, accuracy, fluency,
           completeness, scenario_id, origin, attempt_no, created_at
      FROM speech_attempts
     WHERE user_id = $1
       -- '' means every department. Filtering HERE rather than on the client is what
       -- makes ` + "`" + `total` + "`" + ` and the paging honest: a client-side filter reported "3 of 128"
       -- for "3 matched among the pages loaded so far", and pulled more in as the
       -- learner scrolled.
       AND ($4::text = '' OR split_part(scenario_id, '-', 2) = $4::text)
       -- 문장 검색: the same reasoning as ` + "`" + `dept` + "`" + ` — filtering here is what keeps ` + "`" + `total` + "`" + `
       -- and the paging honest. ILIKE rather than a full-text index: the corpus is one
       -- learner's own sentences (hundreds, not millions), and a substring is what
       -- somebody typing "acetaminophen" actually means.
       AND ($5::text = '' OR reference_text ILIKE '%' || $5::text || '%')
     ORDER BY sentence_key, attempt_no DESC
)
SELECT sentence_key, reference_text, recognized, overall, accuracy, fluency,
       completeness, scenario_id, origin, attempt_no, created_at,
       (SELECT COUNT(*)::int FROM latest) AS total
  FROM latest
 ORDER BY overall, created_at DESC
 LIMIT $3 OFFSET $2
`

type ListSpeakSentencesWeakParams struct {
	UserID string `json:"user_id"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
	Dept   string `json:"dept"`
	Q      string `json:"q"`
}

type ListSpeakSentencesWeakRow struct {
	SentenceKey   string             `json:"sentence_key"`
	ReferenceText string             `json:"reference_text"`
	Recognized    string             `json:"recognized"`
	Overall       float64            `json:"overall"`
	Accuracy      float64            `json:"accuracy"`
	Fluency       float64            `json:"fluency"`
	Completeness  float64            `json:"completeness"`
	ScenarioID    string             `json:"scenario_id"`
	Origin        string             `json:"origin"`
	AttemptNo     int                `json:"attempt_no"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Total         int                `json:"total"`
}

// 약한 순: worst standing first. Ties break by recency so the sentence they hit
// most recently is the one they are shown first.
//
// `total` rides along on every row so the list's "N문장 중 M개 표시" needs no
// second round trip per page.
func (q *Queries) ListSpeakSentencesWeak(ctx context.Context, arg ListSpeakSentencesWeakParams) ([]ListSpeakSentencesWeakRow, error) {
	rows, err := q.db.Query(ctx, listSpeakSentencesWeak,
		arg.UserID,
		arg.Off,
		arg.Lim,
		arg.Dept,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeakSentencesWeakRow
	for rows.Next() {
		var i ListSpeakSentencesWeakRow
		if err := rows.Scan(
			&i.SentenceKey,
			&i.ReferenceText,
			&i.Recognized,
			&i.Overall,
			&i.Accuracy,
			&i.Fluency,
			&i.Completeness,
			&i.ScenarioID,
			&i.Origin,
			&i.AttemptNo,
			&i.CreatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeechAttempts = `-- name: ListSpeechAttempts :many
SELECT id, attempt_no, overall, accuracy, fluency, completeness, prosody,
       duration_ms, recognized, words, created_at
  FROM speech_attempts
 WHERE user_id = $1 AND sentence_key = $2
 ORDER BY attempt_no DESC
 LIMIT $3
`

type ListSpeechAttemptsParams struct {
	UserID      string `json:"user_id"`
	SentenceKey string `json:"sentence_key"`
	Limit       int32  `json:"limit"`
}

type ListSpeechAttemptsRow struct {
	ID           string             `json:"id"`
	AttemptNo    int                `json:"attempt_no"`
	Overall      float64            `json:"overall"`
	Accuracy     float64            `json:"accuracy"`
	Fluency      float64            `json:"fluency"`
	Completeness float64            `json:"completeness"`
	Prosody      pgtype.Float4      `json:"prosody"`
	DurationMs   int                `json:"duration_ms"`
	Recognized   string             `json:"recognized"`
	Words        []byte             `json:"words"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSpeechAttempts(ctx context.Context, arg ListSpeechAttemptsParams) ([]ListSpeechAttemptsRow, error) {
	rows, err := q.db.Query(ctx, listSpeechAttempts, arg.UserID, arg.SentenceKey, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeechAttemptsRow
	for rows.Next() {
		var i ListSpeechAttemptsRow
		if err := rows.Scan(
			&i.ID,
			&i.AttemptNo,
			&i.Overall,
			&i.Accuracy,
			&i.Fluency,
			&i.Completeness,
			&i.Prosody,
			&i.DurationMs,
			&i.Recognized,
			&i.Words,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSpeechReference = `-- name: PutSpeechReference :exec
INSERT INTO speech_references (sentence_key, reference_text, locale, ipa, words, duration_ms, audio_wav)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (sentence_key) DO NOTHING
`

type PutSpeechReferenceParams struct {
	SentenceKey   string `json:"sentence_key"`
	ReferenceText string `json:"reference_text"`
	Locale        string `json:"locale"`
	Ipa           string `json:"ipa"`
	Words         []byte `json:"words"`
	DurationMs    int    `json:"duration_ms"`
	AudioWav      []byte `json:"audio_wav"`
}

func (q *Queries) PutSpeechReference(ctx context.Context, arg PutSpeechReferenceParams) error {
	_, err := q.db.Exec(ctx, putSpeechReference,
		arg.SentenceKey,
		arg.ReferenceText,
		arg.Locale,
		arg.Ipa,
		arg.Words,
		arg.DurationMs,
		arg.AudioWav,
	)
	return err
}

const speakBands = `-- name: SpeakBands :one
WITH latest AS (
    SELECT DISTINCT ON (sentence_key) sentence_key, overall, scenario_id
      FROM speech_attempts
     WHERE user_id = $1
     ORDER BY sentence_key, attempt_no DESC
)
SELECT COUNT(*)::int                                            AS total,
       COUNT(*) FILTER (WHERE overall < 60)::int                AS low,
       COUNT(*) FILTER (WHERE overall >= 60 AND overall < 80)::int AS mid,
       COUNT(*) FILTER (WHERE overall >= 80)::int               AS high
  FROM latest
 WHERE ($2::text = '' OR split_part(scenario_id, '-', 2) = $2::text)
`

type SpeakBandsParams struct {
	UserID  string `json:"user_id"`
	Column2 string `json:"column_2"`
}

type SpeakBandsRow struct {
	Total int `json:"total"`
	Low   int `json:"low"`
	Mid   int `json:"mid"`
	High  int `json:"high"`
}

// Score-band distribution over the player's CURRENT standing on each sentence:
// one row per sentence_key at its newest attempt, bucketed 60↓ / 60–79 / 80+.
//
// Counting attempts instead of sentences would let one heavily-drilled sentence
// dominate the distribution, and would keep punishing the player for the early
// bad tries they have since fixed.
//
// $2 is the department filter: ” means every department, otherwise the code that
// ListSpeakSentences filters on (split_part(scenario_id, '-', 2)). It is filtered
// HERE so the distribution the 말하기 탭 draws under its filter chips is the
// distribution OF that filter — pick ER and the bars re-read as ER's spread.
func (q *Queries) SpeakBands(ctx context.Context, arg SpeakBandsParams) (SpeakBandsRow, error) {
	row := q.db.QueryRow(ctx, speakBands, arg.UserID, arg.Column2)
	var i SpeakBandsRow
	err := row.Scan(
		&i.Total,
		&i.Low,
		&i.Mid,
		&i.High,
	)
	return i, err
}

const spokenDepartments = `-- name: SpokenDepartments :many
SELECT DISTINCT split_part(scenario_id, '-', 2) AS dept
  FROM speech_attempts
 WHERE user_id = $1 AND scenario_id LIKE 'SCN-%-%'
 ORDER BY dept
`

// Every department the learner has spoken in, derived from the scenario id prefix
// (SCN-ER-00002 -> ER).
//
// Sent with the list so the department chips are COMPLETE. Deriving them from the
// loaded pages instead made chips appear as the learner scrolled, and filtering to
// one showed only its rows among the pages fetched so far — the rest arrived later,
// which reads as the filter being broken.
func (q *Queries) SpokenDepartments(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, spokenDepartments, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var dept string
		if err := rows.Scan(&dept); err != nil {
			return nil, err
		}
		items = append(items, dept)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSpeechReferenceAudio = `-- name: UpdateSpeechReferenceAudio :exec
UPDATE speech_references SET audio_wav = $2
 WHERE sentence_key = $1 AND audio_wav = ''
`

type UpdateSpeechReferenceAudioParams struct {
	SentenceKey string `json:"sentence_key"`
	AudioWav    []byte `json:"audio_wav"`
}

// Backfills a row that already exists but has no audio yet (review round 2,
// Important 1) — the empty-audio guard makes this first-writer-wins, same as
// PutSpeechReference's ON CONFLICT DO NOTHING: a race between two backfills
// just means one Synthesize call goes unused, never corruption.
func (q *Queries) UpdateSpeechReferenceAudio(ctx context.Context, arg UpdateSpeechReferenceAudioParams) error {
	_, err := q.db.Exec(ctx, updateSpeechReferenceAudio, arg.SentenceKey, arg.AudioWav)
	return err
}
