// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const avatars = `-- name: Avatars :many
SELECT user_id, avatar FROM profiles
WHERE user_id = ANY ($1::uuid[]) AND avatar IS NOT NULL
`

type AvatarsRow struct {
	UserID string `json:"user_id"`
	Avatar []byte `json:"avatar"`
}

// Portraits for a set of users, in ONE query — the same reason DisplayNames exists:
// a lounge feed or a colleague list draws many people at once, and a per-row lookup
// turns a page of twenty into twenty round trips.
//
// The NULL filter is an optimisation, not the guard: rows nobody will use should not
// cross the wire. What actually makes "absent" mean "never chose one" is the repo,
// which drops any row whose json does not parse — a NULL included. Both are kept,
// and the mutation test that proved the filter alone is not load-bearing is why this
// comment no longer claims it is.
func (q *Queries) Avatars(ctx context.Context, userIds []string) ([]AvatarsRow, error) {
	rows, err := q.db.Query(ctx, avatars, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvatarsRow
	for rows.Next() {
		var i AvatarsRow
		if err := rows.Scan(&i.UserID, &i.Avatar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO auth_identities (user_id, provider, subject_id, email) VALUES ($1, $2, $3, $4)
`

type CreateIdentityParams struct {
	UserID    string `json:"user_id"`
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
	Email     string `json:"email"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.SubjectID,
		arg.Email,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (status) VALUES ($1) RETURNING id, status, created_at
`

func (q *Queries) CreateUser(ctx context.Context, status string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, status)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const displayNames = `-- name: DisplayNames :many
SELECT user_id, display_name FROM profiles
WHERE user_id = ANY ($1::uuid[]) AND display_name <> ''
`

type DisplayNamesRow struct {
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
}

// Names for a set of users, in ONE query. Colleague lists render many people at
// once, and a per-row lookup is how a list of ten becomes ten round trips. Rows
// with no name set are omitted rather than returned blank — the caller already
// has a fallback for "not set", and an empty string would make it choose twice.
func (q *Queries) DisplayNames(ctx context.Context, userIds []string) ([]DisplayNamesRow, error) {
	rows, err := q.db.Query(ctx, displayNames, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DisplayNamesRow
	for rows.Next() {
		var i DisplayNamesRow
		if err := rows.Scan(&i.UserID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProfile = `-- name: GetProfile :one
SELECT user_id, job, native_lang, target_lang, destination, target_level, onboarded, equipped_title, ui_lang, display_name, avatar FROM profiles WHERE user_id = $1
`

type GetProfileRow struct {
	UserID        string `json:"user_id"`
	Job           string `json:"job"`
	NativeLang    string `json:"native_lang"`
	TargetLang    string `json:"target_lang"`
	Destination   string `json:"destination"`
	TargetLevel   string `json:"target_level"`
	Onboarded     bool   `json:"onboarded"`
	EquippedTitle string `json:"equipped_title"`
	UiLang        string `json:"ui_lang"`
	DisplayName   string `json:"display_name"`
	Avatar        []byte `json:"avatar"`
}

func (q *Queries) GetProfile(ctx context.Context, userID string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Job,
		&i.NativeLang,
		&i.TargetLang,
		&i.Destination,
		&i.TargetLevel,
		&i.Onboarded,
		&i.EquippedTitle,
		&i.UiLang,
		&i.DisplayName,
		&i.Avatar,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, status, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.status, u.created_at
FROM auth_identities ai JOIN users u ON u.id = ai.user_id
WHERE ai.provider = $1 AND ai.subject_id = $2
`

type GetUserByIdentityParams struct {
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.SubjectID)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const recordProfileChange = `-- name: RecordProfileChange :exec
INSERT INTO profile_changes (user_id, from_job, to_job, from_lang, to_lang, from_dest, to_dest)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type RecordProfileChangeParams struct {
	UserID   string `json:"user_id"`
	FromJob  string `json:"from_job"`
	ToJob    string `json:"to_job"`
	FromLang string `json:"from_lang"`
	ToLang   string `json:"to_lang"`
	FromDest string `json:"from_dest"`
	ToDest   string `json:"to_dest"`
}

// One row per ACTUAL change (the handler compares before/after and skips a no-op save).
// The audit is what lets learning-tracks P2 partition existing history by time instead
// of guessing which subject three weeks of review cards belonged to.
func (q *Queries) RecordProfileChange(ctx context.Context, arg RecordProfileChangeParams) error {
	_, err := q.db.Exec(ctx, recordProfileChange,
		arg.UserID,
		arg.FromJob,
		arg.ToJob,
		arg.FromLang,
		arg.ToLang,
		arg.FromDest,
		arg.ToDest,
	)
	return err
}

const setAvatar = `-- name: SetAvatar :exec
INSERT INTO profiles (user_id, avatar, updated_at) VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE SET avatar = $2, updated_at = now()
`

type SetAvatarParams struct {
	UserID string `json:"user_id"`
	Avatar []byte `json:"avatar"`
}

// Single-field patch, like SetDisplayName. Never UpsertProfile: that one fills the
// columns it is not given with onboarding defaults, so saving a portrait through it
// would reset the learner's job and languages.
func (q *Queries) SetAvatar(ctx context.Context, arg SetAvatarParams) error {
	_, err := q.db.Exec(ctx, setAvatar, arg.UserID, arg.Avatar)
	return err
}

const setDisplayName = `-- name: SetDisplayName :exec
INSERT INTO profiles (user_id, display_name, updated_at) VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE SET display_name = $2, updated_at = now()
`

type SetDisplayNameParams struct {
	UserID      string `json:"user_id"`
	DisplayName string `json:"display_name"`
}

// Single-field patch, like SetEquippedTitle and SetUILang. Never UpsertProfile:
// that one fills omitted columns with onboarding defaults, so saving a name
// through it would reset job and languages.
func (q *Queries) SetDisplayName(ctx context.Context, arg SetDisplayNameParams) error {
	_, err := q.db.Exec(ctx, setDisplayName, arg.UserID, arg.DisplayName)
	return err
}

const setEquippedTitle = `-- name: SetEquippedTitle :exec
INSERT INTO profiles (user_id, equipped_title, updated_at) VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE SET equipped_title = $2, updated_at = now()
`

type SetEquippedTitleParams struct {
	UserID        string `json:"user_id"`
	EquippedTitle string `json:"equipped_title"`
}

func (q *Queries) SetEquippedTitle(ctx context.Context, arg SetEquippedTitleParams) error {
	_, err := q.db.Exec(ctx, setEquippedTitle, arg.UserID, arg.EquippedTitle)
	return err
}

const setUILang = `-- name: SetUILang :exec
INSERT INTO profiles (user_id, ui_lang, updated_at) VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE SET ui_lang = $2, updated_at = now()
`

type SetUILangParams struct {
	UserID string `json:"user_id"`
	UiLang string `json:"ui_lang"`
}

// Single-field patch, like SetEquippedTitle: the full UpsertProfile fills omitted
// columns with onboarding defaults, so reusing it to save one setting would reset
// job and languages.
func (q *Queries) SetUILang(ctx context.Context, arg SetUILangParams) error {
	_, err := q.db.Exec(ctx, setUILang, arg.UserID, arg.UiLang)
	return err
}

const updateIdentityEmail = `-- name: UpdateIdentityEmail :exec
UPDATE auth_identities SET email = $3 WHERE provider = $1 AND subject_id = $2
`

type UpdateIdentityEmailParams struct {
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
	Email     string `json:"email"`
}

func (q *Queries) UpdateIdentityEmail(ctx context.Context, arg UpdateIdentityEmailParams) error {
	_, err := q.db.Exec(ctx, updateIdentityEmail, arg.Provider, arg.SubjectID, arg.Email)
	return err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (user_id, job, native_lang, target_lang, destination, target_level, onboarded, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, true, now())
ON CONFLICT (user_id) DO UPDATE SET
    job = $2, native_lang = $3, target_lang = $4, destination = $5, target_level = $6,
    onboarded = true, updated_at = now()
`

type UpsertProfileParams struct {
	UserID      string `json:"user_id"`
	Job         string `json:"job"`
	NativeLang  string `json:"native_lang"`
	TargetLang  string `json:"target_lang"`
	Destination string `json:"destination"`
	TargetLevel string `json:"target_level"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Job,
		arg.NativeLang,
		arg.TargetLang,
		arg.Destination,
		arg.TargetLevel,
	)
	return err
}
