// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO auth_identities (user_id, provider, subject_id, email) VALUES ($1, $2, $3, $4)
`

type CreateIdentityParams struct {
	UserID    string `json:"user_id"`
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
	Email     string `json:"email"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.SubjectID,
		arg.Email,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (status) VALUES ($1) RETURNING id, status, created_at
`

func (q *Queries) CreateUser(ctx context.Context, status string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, status)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT user_id, job, native_lang, destination, en_level FROM profiles WHERE user_id = $1
`

type GetProfileRow struct {
	UserID      string `json:"user_id"`
	Job         string `json:"job"`
	NativeLang  string `json:"native_lang"`
	Destination string `json:"destination"`
	EnLevel     string `json:"en_level"`
}

func (q *Queries) GetProfile(ctx context.Context, userID string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Job,
		&i.NativeLang,
		&i.Destination,
		&i.EnLevel,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, status, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.status, u.created_at
FROM auth_identities ai JOIN users u ON u.id = ai.user_id
WHERE ai.provider = $1 AND ai.subject_id = $2
`

type GetUserByIdentityParams struct {
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.SubjectID)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const updateIdentityEmail = `-- name: UpdateIdentityEmail :exec
UPDATE auth_identities SET email = $3 WHERE provider = $1 AND subject_id = $2
`

type UpdateIdentityEmailParams struct {
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
	Email     string `json:"email"`
}

func (q *Queries) UpdateIdentityEmail(ctx context.Context, arg UpdateIdentityEmailParams) error {
	_, err := q.db.Exec(ctx, updateIdentityEmail, arg.Provider, arg.SubjectID, arg.Email)
	return err
}
