// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :exec
INSERT INTO auth_identities (user_id, provider, subject_id, email) VALUES ($1, $2, $3, $4)
`

type CreateIdentityParams struct {
	UserID    string `json:"user_id"`
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
	Email     string `json:"email"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) error {
	_, err := q.db.Exec(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.SubjectID,
		arg.Email,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (status) VALUES ($1) RETURNING id, status, created_at
`

func (q *Queries) CreateUser(ctx context.Context, status string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, status)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT user_id, job, native_lang, target_lang, destination, target_level, onboarded, equipped_title FROM profiles WHERE user_id = $1
`

type GetProfileRow struct {
	UserID        string `json:"user_id"`
	Job           string `json:"job"`
	NativeLang    string `json:"native_lang"`
	TargetLang    string `json:"target_lang"`
	Destination   string `json:"destination"`
	TargetLevel   string `json:"target_level"`
	Onboarded     bool   `json:"onboarded"`
	EquippedTitle string `json:"equipped_title"`
}

func (q *Queries) GetProfile(ctx context.Context, userID string) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.Job,
		&i.NativeLang,
		&i.TargetLang,
		&i.Destination,
		&i.TargetLevel,
		&i.Onboarded,
		&i.EquippedTitle,
	)
	return i, err
}

const setEquippedTitle = `-- name: SetEquippedTitle :exec
INSERT INTO profiles (user_id, equipped_title, updated_at) VALUES ($1, $2, now())
ON CONFLICT (user_id) DO UPDATE SET equipped_title = $2, updated_at = now()
`

type SetEquippedTitleParams struct {
	UserID        string `json:"user_id"`
	EquippedTitle string `json:"equipped_title"`
}

func (q *Queries) SetEquippedTitle(ctx context.Context, arg SetEquippedTitleParams) error {
	_, err := q.db.Exec(ctx, setEquippedTitle, arg.UserID, arg.EquippedTitle)
	return err
}

const upsertProfile = `-- name: UpsertProfile :exec
INSERT INTO profiles (user_id, job, native_lang, target_lang, destination, target_level, onboarded, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, true, now())
ON CONFLICT (user_id) DO UPDATE SET
    job = $2, native_lang = $3, target_lang = $4, destination = $5, target_level = $6,
    onboarded = true, updated_at = now()
`

type UpsertProfileParams struct {
	UserID      string `json:"user_id"`
	Job         string `json:"job"`
	NativeLang  string `json:"native_lang"`
	TargetLang  string `json:"target_lang"`
	Destination string `json:"destination"`
	TargetLevel string `json:"target_level"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) error {
	_, err := q.db.Exec(ctx, upsertProfile,
		arg.UserID,
		arg.Job,
		arg.NativeLang,
		arg.TargetLang,
		arg.Destination,
		arg.TargetLevel,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, status, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const getUserByIdentity = `-- name: GetUserByIdentity :one
SELECT u.id, u.status, u.created_at
FROM auth_identities ai JOIN users u ON u.id = ai.user_id
WHERE ai.provider = $1 AND ai.subject_id = $2
`

type GetUserByIdentityParams struct {
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
}

func (q *Queries) GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentity, arg.Provider, arg.SubjectID)
	var i User
	err := row.Scan(&i.ID, &i.Status, &i.CreatedAt)
	return i, err
}

const updateIdentityEmail = `-- name: UpdateIdentityEmail :exec
UPDATE auth_identities SET email = $3 WHERE provider = $1 AND subject_id = $2
`

type UpdateIdentityEmailParams struct {
	Provider  string `json:"provider"`
	SubjectID string `json:"subject_id"`
	Email     string `json:"email"`
}

func (q *Queries) UpdateIdentityEmail(ctx context.Context, arg UpdateIdentityEmailParams) error {
	_, err := q.db.Exec(ctx, updateIdentityEmail, arg.Provider, arg.SubjectID, arg.Email)
	return err
}
