-- 시도가 도움을 받았는지 기록한다.
--
-- 커리큘럼이 같은 상황을 두 번 가르친다: 한 번은 선택지와 함께, 한 번은 혼자. 그러면
-- "이 시나리오를 깼다"만으로는 부족하다 — 선택지를 받고 깬 것과 혼자 깬 것은 다른
-- 일이고, 전자를 후자로 세면 사다리의 두 번째 칸이 사라진다.
--
-- 값은 코드 쪽 집합이다(curriculum.GuideLevel): 'choices' | 'free'. DB CHECK를 두지
-- 않는 이유는 이 프로젝트의 다른 열거형과 같다 — 단계를 하나 더 만드는 데 마이그레이션이
-- 필요해선 안 된다. 빈 문자열은 이 컬럼이 생기기 전의 시도이고, 그때는 도움이 없었으므로
-- 'free'와 같게 읽는다.
ALTER TABLE scenario_attempts ADD COLUMN IF NOT EXISTS guide text NOT NULL DEFAULT '';
