-- 대화 세션이 어떤 칸에서 열렸는지 기록한다.
--
-- 커리큘럼은 같은 상황을 두 번 가르친다. 첫 칸은 선택지와 함께, 둘째 칸은 혼자.
-- 그런데 서버는 어느 쪽인지 몰랐다 — 화면이 클라이언트에서만 판단했다. 그래서
-- 사전 작성된 선택지 트리를 쓸 수 있는 순간에도 매 턴 LLM을 불렀고, 무엇보다
-- 트리를 쓰기로 정한 뒤에는 서버가 이걸 알아야 한다: 트리로 답할 턴에 모델을
-- 부르면 대화가 트리와 어긋난다.
--
-- 값은 코드 쪽 집합이다(curriculum.GuideLevel): 'choices' | 'free'. scenario_attempts.guide와
-- 같은 규칙이고 같은 이유다 — 칸을 하나 더 만드는 데 마이그레이션이 필요해선 안 된다.
-- 빈 문자열은 이 컬럼이 생기기 전의 세션이고, 그때는 트리가 없었으므로 'free'로 읽는다.
ALTER TABLE conversation_sessions ADD COLUMN IF NOT EXISTS guide text NOT NULL DEFAULT '';
