// Command speechrefgc removes cached pronunciation references nobody has opened lately.
//
// speech_references is a global cache that is never invalidated (business-rules R9), and
// any sentence — including free text a learner typed or said — can mint a row with its
// synthesized audio (~320KB). The daily generation cap bounds how fast rows appear, not
// how long they stay; this is the other half (cross-review I4c). A row is "unused" when
// its last_used_at (refreshed at most daily on a cache hit, migration 000044) is older
// than the cutoff.
//
// It cannot tell a free-text sentence from a curriculum one, and does not need to: a
// deleted row is simply regenerated by its next visitor (one TTS + one assessment), so
// the worst case of cleaning a curriculum sentence is one repeat of what that sentence
// cost the first time.
//
// Not scheduled anywhere — run it by hand or wire a job deliberately.
//
//	usage: DATABASE_URL=... go run ./cmd/speechrefgc [--days 90] [--apply]
//
// Without --apply it only reports how many rows would go.
package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/bingoring/forin/server/internal/adapters/postgres"
)

func main() {
	days := flag.Int("days", 90, "delete references not served for this many days")
	apply := flag.Bool("apply", false, "actually delete (default is a dry run)")
	flag.Parse()

	if *days < 7 {
		// last_used_at is only refreshed once a day, and a very short window would delete
		// rows that are in active use. A week is a floor that keeps the guard meaningful.
		fmt.Fprintln(os.Stderr, "speechrefgc: --days must be at least 7")
		os.Exit(2)
	}
	url := os.Getenv("DATABASE_URL")
	if url == "" {
		fmt.Fprintln(os.Stderr, "speechrefgc: DATABASE_URL is required")
		os.Exit(2)
	}

	ctx := context.Background()
	pool, err := pgxpool.New(ctx, url)
	if err != nil {
		fmt.Fprintln(os.Stderr, "speechrefgc: connect:", err)
		os.Exit(1)
	}
	defer pool.Close()

	repo := postgres.NewSpeechRepo(pool)
	cutoff := time.Now().Add(-time.Duration(*days) * 24 * time.Hour)

	if !*apply {
		n, err := repo.CountStaleReferences(ctx, cutoff)
		if err != nil {
			fmt.Fprintln(os.Stderr, "speechrefgc: count:", err)
			os.Exit(1)
		}
		fmt.Printf("speechrefgc: dry run — %d reference(s) unused since %s would be deleted (pass --apply)\n", n, cutoff.Format(time.RFC3339))
		return
	}
	n, err := repo.DeleteStaleReferences(ctx, cutoff)
	if err != nil {
		fmt.Fprintln(os.Stderr, "speechrefgc: delete:", err)
		os.Exit(1)
	}
	fmt.Printf("speechrefgc: deleted %d reference(s) unused since %s\n", n, cutoff.Format(time.RFC3339))
}
