// FIcon — the forin icon system from design-handoff_v23 (02_COMPONENTS).
//
// 87 icons, each a 16×16 pixel-stair silhouette drawn as a rect list. The
// geometry comes from src/theme/ficons.ts, generated by executing the handoff's
// own forin-pixel-icons.jsx rather than transcribing it (see that file's header).
//
// Two things this does NOT do, both deliberate:
//
//  1. It takes no `color`. These icons are artwork with fixed internal colours —
//     the thumb has a blue sleeve, the tower a red cross, the pill two halves.
//     A single tint would flatten all of that into a silhouette, which is what
//     the previous line-icon set was and what v23 replaced. Where a surface needs
//     a monochrome mark (a chevron on a dark bar), the line-icon PixelIcon is
//     still the right component.
//  2. It does not scale strokes. Pixel art at 16×16 has no strokes to scale — the
//     rects scale with the viewBox. The web source sets shape-rendering:
//     crispEdges; react-native-svg has no such prop, and it does not need one:
//     these are axis-aligned rects on integer coordinates, which the native
//     renderers fill exactly. (A handful of rects sit on half-pixels — board's
//     clip at 6.5 — and those get the same soft edge the web version gets from
//     the browser, so the two stay in agreement rather than diverging.)
import Svg, { Rect } from 'react-native-svg';
import { FICONS, type FIconName } from '@/theme/ficons';

export type { FIconName };

/** Whether a name is one the icon set actually draws. */
export function hasFIcon(name: string): name is FIconName {
  return Object.prototype.hasOwnProperty.call(FICONS, name);
}

export function FIcon({ name, size = 18 }: { name: FIconName | string; size?: number }) {
  // Falls back to `xp` exactly as the handoff's own svgFor() does, so a name that
  // slips through renders the reward gem rather than an invisible hole. A missing
  // icon should look like a mistake, not like nothing.
  const rects = FICONS[name] ?? FICONS.xp;
  return (
    <Svg width={size} height={size} viewBox="0 0 16 16">
      {rects.map(([x, y, w, h, fill], i) => (
        <Rect key={i} x={x} y={y} width={w} height={h} fill={fill} />
      ))}
    </Svg>
  );
}
