// Code generated by cmd/gencontent — DO NOT EDIT.
//
// The difficulty fallback for departments nobody has authored curricula for yet
// (business-rules R7). Empty means every department bank is covered by
// internal/curriculum/authored_*.go, which is the desired steady state.

package curriculum

var fallback = []Curriculum{}
