// Package handoff builds 환자 인수인계 노트: follow-up notes from the AI patients a learner
// has met. Clearing a patient scenario may bring a note — the better the encounter (higher
// AI grade), the likelier — and each note carries an action: reply, a follow-up scenario,
// or a review link.
//
// Note bodies are generated by the LLM (in the patient's voice, in the learner's language),
// with a template fallback so the feature works even with no LLM key. The whole thing is
// bounded: at most one note is generated per inbox open, and one LLM call per reply.
package handoff

import (
	"context"
	"crypto/sha256"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/bingoring/forin/server/internal/curriculum"
	"github.com/bingoring/forin/server/internal/domain/content"
	"github.com/bingoring/forin/server/internal/ports"
)

type Kind string

const (
	KindGratitude Kind = "gratitude"
	KindFollowup  Kind = "followup"
	KindReview    Kind = "review"
)

// Note is one 후일담 in the inbox.
type Note struct {
	ID            string
	ScenarioID    string
	Kind          Kind
	PatientName   string
	PatientSub    string // a short condition, e.g. "흉통 호소"
	Coord         string // where they met, e.g. "ER · TRAUMA BAY"
	Body          string
	RefScenarioID string // follow-up scenario (followup) or the encounter (review)
	ReplyText     string
	PatientReply  string
	MetAt         time.Time
	RepliedAt     *time.Time
	ReadAt        *time.Time
	CreatedAt     time.Time
}

// Store persists notes. It lives in the domain (not ports) so there is no import cycle; the
// postgres adapter implements it structurally.
type Store interface {
	List(ctx context.Context, userID string) ([]Note, error)
	Get(ctx context.Context, userID, id string) (*Note, error)
	Insert(ctx context.Context, userID string, n Note) (Note, error)
	MarkRead(ctx context.Context, userID, id string) error
	SetReply(ctx context.Context, userID, id, reply, patientReply string) error
}

// Service turns cleared encounters into notes.
type Service struct {
	store    Store
	progress ports.ProgressRepo
	content  ports.ContentReader
	review   ports.ReviewRepo
	llm      ports.LLMPort
	model    string
	now      func() time.Time
}

func NewService(store Store, prog ports.ProgressRepo, cont ports.ContentReader, rev ports.ReviewRepo, llm ports.LLMPort, model string) *Service {
	return &Service{store: store, progress: prog, content: cont, review: rev, llm: llm, model: model, now: time.Now}
}

// isPatient is true for personas the nurse CARED for (a note comes from a patient or their
// family), not colleagues like doctors or surgeons.
func isPatient(role string) bool {
	switch strings.ToLower(strings.TrimSpace(role)) {
	case "patient", "parent", "family", "mother", "father", "child", "caregiver", "guardian", "":
		return true
	}
	return false
}

// hashUnit is a stable 0..1 from a seed — the same encounter always resolves the same way,
// so a note that never came does not suddenly appear on a later open.
func hashUnit(seed string) float64 {
	sum := sha256.Sum256([]byte(seed))
	return float64(binary.BigEndian.Uint64(sum[:8])) / float64(1<<64)
}

// gateThreshold: better encounters are likelier to bring a note.
func gateThreshold(grade int) float64 {
	switch {
	case grade >= 80:
		return 0.85
	case grade >= 60:
		return 0.60
	default: // includes ungraded (-1)
		return 0.35
	}
}

func (s *Service) eligible(userID, scenarioID string, grade int) bool {
	return hashUnit(userID+"|"+scenarioID) < gateThreshold(grade)
}

// pickKind chooses the note's flavour and its action target from the encounter.
//
// review when this encounter left corrections to sharpen; otherwise mostly gratitude, and
// sometimes a follow-up nudge toward the next scenario (a stable per-encounter roll, so the
// same note keeps its kind). Gratitude is the default so a curriculum that always has a
// "next step" does not turn every note into a follow-up.
func (s *Service) pickKind(ctx context.Context, userID string, sc *content.Scenario) (Kind, string) {
	if corrs, err := s.review.ListModelAnswerCards(ctx, userID, []string{sc.ID}); err == nil && len(corrs[sc.ID]) > 0 {
		return KindReview, sc.ID // review opens this encounter's corrections
	}
	if hashUnit(userID+"|"+sc.ID+"|kind") < 0.4 {
		cleared, _ := s.progress.ClearedScenarioIDs(ctx, userID)
		attempted, _ := s.progress.AttemptedScenarioIDs(ctx, userID)
		if next := curriculum.NextScenarioAfter(cleared, attempted, sc.ID); next != "" && next != sc.ID {
			return KindFollowup, next
		}
	}
	return KindGratitude, ""
}

// Inbox returns the notes newest-first, generating at most one new note from an eligible,
// not-yet-noted cleared encounter. unread is the count still unread.
func (s *Service) Inbox(ctx context.Context, userID, locale string) ([]Note, int, error) {
	notes, err := s.store.List(ctx, userID)
	if err != nil {
		return nil, 0, err
	}
	noted := make(map[string]bool, len(notes))
	for _, n := range notes {
		noted[n.ScenarioID] = true
	}

	if cleared, err := s.progress.ClearedScenariosDetail(ctx, userID); err == nil {
		for _, cs := range cleared { // newest first
			if noted[cs.ScenarioID] || !s.eligible(userID, cs.ScenarioID, cs.Grade) {
				continue
			}
			sc, err := s.content.GetScenario(ctx, cs.ScenarioID)
			if err != nil || sc == nil || !isPatient(sc.Persona.Role) {
				continue
			}
			n := s.generate(ctx, userID, sc, cs.Grade, cs.ClearedAt, locale)
			if saved, err := s.store.Insert(ctx, userID, n); err == nil {
				notes = append([]Note{saved}, notes...)
			}
			break // at most one per open
		}
	}

	unread := 0
	for _, n := range notes {
		if n.ReadAt == nil {
			unread++
		}
	}
	return notes, unread, nil
}

func (s *Service) generate(ctx context.Context, userID string, sc *content.Scenario, grade int, metAt time.Time, locale string) Note {
	kind, ref := s.pickKind(ctx, userID, sc)
	coord := ""
	if sc.Briefing != nil {
		coord = sc.Briefing.Dept
	}
	n := Note{
		ScenarioID:    sc.ID,
		Kind:          kind,
		PatientName:   sc.Persona.Name,
		PatientSub:    firstNonEmpty(sc.Tagline, sc.Persona.Mood),
		Coord:         coord,
		RefScenarioID: ref,
		MetAt:         metAt,
	}
	n.Body = s.genBody(ctx, sc, kind, grade, locale)
	return n
}

// MarkRead marks one note read.
func (s *Service) MarkRead(ctx context.Context, userID, id string) error {
	return s.store.MarkRead(ctx, userID, id)
}

// Reply stores the learner's reply, generates the patient's reply back, and returns the
// updated note.
func (s *Service) Reply(ctx context.Context, userID, id, text, locale string) (*Note, error) {
	n, err := s.store.Get(ctx, userID, id)
	if err != nil {
		return nil, err
	}
	if n == nil {
		return nil, nil
	}
	patientReply := s.genReply(ctx, n, text, locale)
	if err := s.store.SetReply(ctx, userID, id, text, patientReply); err != nil {
		return nil, err
	}
	now := s.now()
	n.ReplyText, n.PatientReply, n.RepliedAt, n.ReadAt = text, patientReply, &now, &now
	return n, nil
}

// ── generation (LLM with template fallback) ─────────────────────────────────

func langName(locale string) string {
	switch locale {
	case "ko":
		return "Korean"
	case "ja":
		return "Japanese"
	case "de":
		return "German"
	default:
		return "English"
	}
}

func (s *Service) genBody(ctx context.Context, sc *content.Scenario, kind Kind, grade int, locale string) string {
	tmpl := templateBody(kind, locale)
	if s.llm == nil || s.model == "" {
		return tmpl
	}
	who := strings.TrimSpace(sc.Persona.Name + " (" + sc.Persona.Sub + ")")
	dept := ""
	if sc.Briefing != nil {
		dept = sc.Briefing.Dept
	}
	kindHint := map[Kind]string{
		KindGratitude: "You are recovering or were discharged; thank the nurse warmly and say you are doing better.",
		KindFollowup:  "You are doing okay, but a follow-up visit is coming up; gently say you hope to see them again.",
		KindReview:    "You remember the visit fondly; mention, softly, one moment where the English was hard, as encouragement to keep practicing.",
	}[kind]
	sys := fmt.Sprintf(
		"You are %[1]s, a patient a nurse cared for in %[2]s. It is a day or two later. Write a SHORT follow-up note to that nurse — 2 to 3 warm, natural sentences in %[3]s, in your own voice as the patient. %[4]s Do not use the nurse's name or invent clinical details beyond the encounter. Respond ONLY with JSON: {\"body\": string}.",
		orText(who, "the patient"), orText(dept, "the ward"), langName(locale), kindHint,
	)
	raw, err := s.llm.Complete(ctx, ports.LLMRequest{
		Model: s.model, System: sys,
		Messages: []ports.LLMMessage{{Role: "user", Content: "Write the note."}}, MaxTokens: 260,
	})
	if err != nil {
		return tmpl
	}
	if body := jsonField(raw, "body"); body != "" {
		return body
	}
	return tmpl
}

func (s *Service) genReply(ctx context.Context, n *Note, text, locale string) string {
	tmpl := replyTemplate(locale)
	if s.llm == nil || s.model == "" {
		return tmpl
	}
	sys := fmt.Sprintf(
		"You are %s, a former patient replying to a nurse who just wrote you back. Reply in ONE short, warm sentence in %s, in your own voice. Respond ONLY with JSON: {\"reply\": string}.",
		orText(n.PatientName, "a patient"), langName(locale),
	)
	raw, err := s.llm.Complete(ctx, ports.LLMRequest{
		Model: s.model, System: sys,
		Messages: []ports.LLMMessage{{Role: "user", Content: text}}, MaxTokens: 120,
	})
	if err != nil {
		return tmpl
	}
	if r := jsonField(raw, "reply"); r != "" {
		return r
	}
	return tmpl
}

// ── helpers ─────────────────────────────────────────────────────────────────

func firstNonEmpty(a, b string) string {
	if strings.TrimSpace(a) != "" {
		return a
	}
	return b
}

func orText(s, fallback string) string {
	if strings.TrimSpace(strings.Trim(s, "()")) == "" {
		return fallback
	}
	return s
}

func jsonField(raw, field string) string {
	i := strings.IndexByte(raw, '{')
	j := strings.LastIndexByte(raw, '}')
	if i < 0 || j <= i {
		return ""
	}
	var m map[string]any
	if json.Unmarshal([]byte(raw[i:j+1]), &m) != nil {
		return ""
	}
	if v, ok := m[field].(string); ok {
		return strings.TrimSpace(v)
	}
	return ""
}

var bodyTemplates = map[string]map[Kind]string{
	"ko": {
		KindGratitude: "그날 참 고마웠어요. 큰 이상 없이 잘 회복하고 있어요 — 그 친절, 오래 기억할게요.",
		KindFollowup:  "잘 지내고 있어요. 그런데 다음에 한 번 더 뵐 일이 생겼어요 — 그때도 잘 부탁드려요.",
		KindReview:    "그날 나눈 대화가 자꾸 생각나요. 한 표현만 더 다듬으면 완벽할 것 같아요.",
	},
	"en": {
		KindGratitude: "Thank you for that day. I'm recovering well — I won't forget your kindness.",
		KindFollowup:  "I'm doing okay. There's another visit coming up, though — I hope you'll be there.",
		KindReview:    "I keep thinking about our talk that day. One phrase more and it'll be perfect.",
	},
}

func templateBody(kind Kind, locale string) string {
	if m, ok := bodyTemplates[locale]; ok {
		if b := m[kind]; b != "" {
			return b
		}
	}
	return bodyTemplates["en"][kind]
}

func replyTemplate(locale string) string {
	switch locale {
	case "ko":
		return "고마워요 — 그 말 한마디에 힘이 나요."
	case "ja":
		return "ありがとう — その一言で元気が出ます。"
	case "de":
		return "Danke — dieser Satz tut gut."
	default:
		return "Thank you — that means a lot."
	}
}
