// Generates src/theme/ficons.ts from the v23 handoff's forin-pixel-icons.jsx.
//
// The geometry is EXECUTED, not transcribed. Each of the 87 icons is a chain of
// rect lists in the source (`P([[x,y,w,h],…], fill)`), and hand-copying 87 of
// those is exactly the kind of transcription that produces an icon that is
// almost right. So this loads the reference file with a DOM shim, reads the
// FICONS table it publishes, and parses the SVG rects back into numbers.
//
// Run: node scripts/gen-ficons.mjs   (then commit the generated file)
import { readFileSync, writeFileSync } from 'fs';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';
import vm from 'vm';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, '..', '..', 'docs', 'dlc', 'projects', 'forin', 'inputs',
  'design-handoff_v25', 'reference', 'forin-pixel-icons.jsx');
const OUT = join(here, '..', 'src', 'theme', 'ficons.ts');

const source = readFileSync(SRC, 'utf8');

// The file is a browser IIFE: it defines a React component, installs a
// MutationObserver, and assigns to window. None of that runs here — we only need
// the table it publishes — so the shim is the minimum that lets it reach the
// final Object.assign without throwing.
const win = {};
const noop = () => {};
const sandbox = {
  window: win,
  document: {
    createTreeWalker: () => ({ nextNode: () => null }),
    addEventListener: noop,
    readyState: 'complete',
    body: null,
  },
  MutationObserver: class { observe() {} disconnect() {} },
  setTimeout: noop,
  React: { createElement: () => null },
  console,
};
sandbox.globalThis = sandbox;
vm.createContext(sandbox);
// The file's tail contains JSX (the FIcon component and the catalog screen),
// which vm cannot parse. Cutting at the first JSX-bearing function keeps every
// icon definition and the emoji map — both are declared well before it — and the
// assign is re-added so the tables are reachable.
const cut = source.indexOf('function FIcon(');
if (cut < 0) throw new Error('reference layout changed: FIcon component not found');
const trimmed = source.slice(0, cut) + '\n Object.assign(window,{FICONS:ICONS,FEMOJI:EMOJI_MAP});\n})();\n';
vm.runInContext(trimmed, sandbox);

const icons = win.FICONS;
const emoji = win.FEMOJI;
if (!icons || Object.keys(icons).length === 0) throw new Error('no icons extracted');

// <rect x=".." y=".." width=".." height=".." fill=".."/> → [x, y, w, h, fill]
const RECT = /<rect x="([-\d.]+)" y="([-\d.]+)" width="([-\d.]+)" height="([-\d.]+)" fill="([^"]+)"\/>/g;
const parsed = {};
for (const [name, svg] of Object.entries(icons)) {
  const rects = [];
  for (const m of svg.matchAll(RECT)) {
    rects.push([Number(m[1]), Number(m[2]), Number(m[3]), Number(m[4]), m[5]]);
  }
  if (rects.length === 0) throw new Error(`icon ${name} parsed to no rects`);
  parsed[name] = rects;
}

const names = Object.keys(parsed).sort();
const body = names.map((n) =>
  `  ${/^[a-z][a-z0-9]*$/i.test(n) ? n : JSON.stringify(n)}: [` +
  parsed[n].map(([x, y, w, h, f]) => `[${x},${y},${w},${h},'${f}']`).join(',') +
  `],`
).join('\n');

const emojiEntries = Object.entries(emoji)
  .map(([e, n]) => `  ${JSON.stringify(e)}: '${n}',`)
  .join('\n');

writeFileSync(OUT, `// GENERATED by scripts/gen-ficons.mjs — do not edit by hand.
//
// The forin icon system (FIcon) from design-handoff_v25, ported 1:1: every icon
// is the same 16×16 rect list the handoff's forin-pixel-icons.jsx draws, read out
// of that file by executing it rather than by transcribing ${names.length} coordinate
// tables. Regenerate after a handoff bump:
//
//   node scripts/gen-ficons.mjs
//
// Palette note: these fills are the handoff's own literals, deliberately NOT
// swapped for theme tokens. The icons are artwork with fixed internal colours
// (a blue sleeve on the thumb, a red cross on the tower); routing them through
// the theme would recolour parts that were drawn to be that colour, and the ink
// and pastel values already match src/theme/tokens.ts anyway.

/** One rect: [x, y, width, height, fill] on a 16×16 grid. */
export type FRect = readonly [number, number, number, number, string];

export const FICONS: Record<string, readonly FRect[]> = {
${body}
};

/** The handoff's emoji → icon map (${Object.keys(emoji).length} entries). Expression emoji (😄 …) are
 *  deliberately unmapped there, and stay unmapped here: they are faces, not icons. */
export const FEMOJI: Record<string, string> = {
${emojiEntries}
};

export type FIconName = keyof typeof FICONS;
`);

console.log(`wrote ${OUT}: ${names.length} icons, ${Object.keys(emoji).length} emoji mappings`);
console.log(`rect count: ${names.reduce((a, n) => a + parsed[n].length, 0)}`);
