import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"Situation: room four with chest pain since noon.":("상황: 6호실, 정오부터 흉통이 있습니다.","상황: 4호실, 아침부터 흉통이 있습니다."),
"Background: history of high blood pressure, no cardiac history.":("배경: 당뇨 병력이 있고, 심장 병력은 없습니다.","배경: 고혈압 병력이 있고, 폐 병력은 없습니다."),
"Assessment: he's alert, and his vitals are stable right now.":("평가: 의식은 명료하고, 활력징후는 아까 안정적이었습니다.","평가: 의식은 명료하고, 활력징후는 지금 측정 중입니다."),
"My recommendation is to keep him on the monitor.":("제 권고는 계속 침상 옆에서 관찰하는 것입니다.","제 보고는 모니터로 계속 관찰한 내용입니다."),
"Sure, let me repeat that: his blood pressure was one forty over ninety.":("네, 다시 말씀드릴게요: 혈압은 140에 80이었습니다.","네, 다시 말씀드릴게요: 혈압은 130에 90이었습니다."),
"Call me right away if his pain score goes above five.":("통증 점수가 3점을 넘으면 바로 저를 불러 주세요.","통증 점수가 5점을 넘으면 바로 의사를 불러 주세요."),
"Her vitals are stable, last set thirty minutes ago.":("활력징후는 안정적이고, 마지막 측정은 한 시간 전입니다.","활력징후는 안정적이고, 마지막 보고는 30분 전입니다."),
"Chief complaint is abdominal pain since this morning.":("주호소는 어제 아침부터 시작된 복통입니다.","주호소는 오늘 아침부터 시작된 요통입니다."),
"We're still waiting on the CT results.":("엑스레이 결과는 아직 기다리는 중입니다.","CT 촬영은 아직 기다리는 중입니다."),
"Please recheck her blood pressure before you chart it.":("차트에 기록하기 전에 체온을 다시 확인해 주세요.","차트에 기록한 뒤에 혈압을 다시 확인해 주세요."),
"She hasn't needed any pain medicine this shift.":("이번 근무 동안 수액은 필요 없었습니다.","이번 주 동안 진통제는 필요 없었습니다."),
"His next antibiotic dose is due at four.":("다음 혈액 채취는 4시 예정입니다.","다음 항생제 투여는 약사가 준비합니다."),
"The urine sample still needs to go to the lab.":("혈액 검체는 아직 검사실로 보내야 합니다.","소변 검체는 아직 검사실에서 찾아와야 합니다."),
"Please recheck her blood pressure in an hour.":("삼십 분 뒤에 혈압을 다시 확인해 주세요.","한 시간 뒤에 체온을 다시 확인해 주세요."),
"His last dose of antibiotic was given on time.":("지난번 수액 교체는 제시간에 이루어졌습니다.","지난번 항생제 투여는 보호자에게 설명되었습니다."),
"Can you confirm the lab result once it's back?":("결과가 나오면 출력해 주실 수 있나요?","결과가 나오면 전화해 주실 수 있나요?"),
"This is Mr. Alvarez in bed two, correct?":("이분은 3번 병상의 알바레즈 씨, 맞나요?","이분은 2번 병상의 로페즈 씨, 맞나요?"),
"Working diagnosis is dehydration, ruling out infection.":("현재 진단은 빈혈이고, 감염은 배제하는 중입니다.","현재 진단은 탈수이고, 출혈은 배제하는 중입니다."),
"Can you read the ID band back to me?":("차트를 저에게 다시 읽어 주시겠어요?","ID 밴드를 환자에게 다시 읽어 주시겠어요?"),
"Let's confirm the date of birth on the chart together.":("차트에 있는 병상 번호도 함께 확인해요.","차트에 있는 생년월일도 따로 확인해요."),
"His name and date of birth both match the chart.":("이름과 생년월일 모두 밴드와 일치합니다.","이름과 생년월일 모두 차트에 적었습니다."),
"I'll wait while you double-check his wristband.":("손목밴드를 다시 확인하시는 동안 서 있을게요.","손목밴드를 다시 채우시는 동안 기다릴게요."),
"Watch bed three most closely this shift.":("이번 근무 동안 3번 병상을 가장 먼저 청소해 주세요.","오늘 아침 3번 병상을 가장 주의 깊게 봐 주세요."),
"Her pressure has been trending down all afternoon.":("그분 체온이 오후 내내 계속 떨어지고 있습니다.","그분 혈압이 오전 내내 계속 떨어지고 있습니다."),
"If anything changes, call the doctor early.":("뭔가 변화가 있으면 일찍 간호 팀장을 호출하세요.","뭔가 질문이 있으면 일찍 의사를 호출하세요."),
"The other three beds are stable and just waiting for discharge.":("나머지 네 병상은 안정적이고 퇴원만 기다리고 있습니다.","나머지 세 병상은 안정적이고 이송만 기다리고 있습니다."),
"Bed three needs the most attention tonight.":("오늘 밤은 3번 병상에 가장 많은 물품이 필요합니다.","오늘 아침은 3번 병상에 가장 주의가 필요합니다."),
"She's admitted for pneumonia, on IV antibiotics.":("폐렴으로 입원했고, 정맥 항생제를 처방받았습니다.","폐렴으로 전원했고, 정맥 항생제를 투여 중입니다."),
"Last vitals were stable, oxygen at two liters.":("첫 활력징후는 안정적이고, 산소는 2리터입니다.","마지막 활력징후는 안정적이고, 산소는 모니터로 확인합니다."),
"Pending labs are her morning cultures.":("대기 중인 검사는 저녁 배양검사입니다.","대기 중인 검사는 아침 소변검사입니다."),
"She's due for her next antibiotic dose at six.":("다음 활력징후 측정은 6시 예정입니다.","다음 항생제 투여는 차트에 적혀 있습니다."),
"Please recheck her oxygen level once she's settled on the floor.":("병동에 자리 잡으면 산소 탱크를 다시 확인해 주세요.","병동에 자리 잡기 전에 산소 수치를 다시 확인해 주세요."),
"His troponin is pending, due back within the hour.":("트로포닌 결과는 대기 중이며, 두 시간 내로 나올 예정입니다.","헤모글로빈 결과는 대기 중이며, 한 시간 내로 나올 예정입니다."),
"If it's elevated, the doctor wants to be called.":("수치가 나오면 의사에게 연락해 달라고 했습니다.","수치가 높으면 책임 간호사에게 연락해 달라고 했습니다."),
"The X-ray is done but not yet read.":("CT는 촬영했지만 아직 판독 전입니다.","엑스레이는 예약했지만 아직 촬영 전입니다."),
"His pain score has stayed the same since the last check.":("마지막 확인 이후 통증 부위는 그대로입니다.","마지막 확인 이전 통증 점수는 그대로였습니다."),
"Please confirm the troponin result as soon as it's back.":("엑스레이 결과가 나오는 대로 확인해 주세요.","트로포닌 결과가 나오는 대로 전화해 주세요."),
"Her pressure is borderline and trending down.":("맥박이 경계선이고 계속 떨어지고 있습니다.","혈압이 경계선이고 계속 재고 있습니다."),
"If systolic drops below ninety, start the fluid bolus.":("수축기 혈압이 90 아래로 떨어지면 수액 라인을 먼저 확인하세요.","수축기 혈압이 90 아래로 떨어지면 혈압을 한 번 더 재 보세요."),
"The doctor is aware and wants a call for any change.":("책임 간호사도 알고 있고, 변화가 있으면 연락을 원합니다.","의사도 알고 있고, 변화가 없어도 연락을 원합니다."),
"Watch her closely — she could turn quickly.":("그분을 주의 깊게 봐 주세요, 보호자가 불안해할 수 있습니다.","그분을 주의 깊게 봐 주세요, 빠르게 이송될 수 있습니다."),
"Her monitor alarm has gone off twice this hour.":("이번 한 시간 동안 모니터 경보가 세 번 울렸습니다.","이번 한 시간 동안 호출벨이 두 번 울렸습니다."),
"Let's start with the sickest and work down.":("가장 최근 입원한 환자부터 시작해서 내려가요.","가장 연세 많은 환자부터 시작해서 내려가요."),
"Bed one is stable and just waiting for discharge.":("1번 병상은 안정적이고 식사만 기다리고 있습니다.","1번 병상은 안정적이고 이송만 기다리고 있습니다."),
"Bed three is the one that needs the most attention.":("3번 병상이 가장 서류가 필요한 환자입니다.","3번 병상이 가장 주의가 필요한 보호자입니다."),
"Bed two just needs her antibiotic dose at noon.":("2번 병상은 정오에 항생제 서류만 확인하면 됩니다.","2번 병상은 정오에 항생제 설명만 하면 됩니다."),
"I'll give you the full report on each bed in order.":("각 병상에 대해 순서대로 간단한 보고를 드릴게요.","각 병상에 대해 순서대로 전체 서류를 드릴게요."),
"You didn't mention her allergies — any I should know?":("알레르기를 말씀하셨는데, 제가 알아야 할 게 더 있나요?","알레르기를 말씀 안 하셨는데, 의사가 알아야 할 게 있나요?"),
"Was the pain medicine actually given, or just ordered?":("수액은 실제로 투여됐나요, 아니면 처방만 됐나요?","진통제는 실제로 투여됐나요, 아니면 준비만 됐나요?"),
"Let me confirm the last vitals time before you go.":("가시기 전에 마지막 투약 시각을 확인할게요.","가시기 전에 마지막 활력징후 시각을 기록할게요."),
"Did the doctor already see her, or is that still pending?":("간호사가 이미 봤나요, 아니면 아직 대기 중인가요?","의사가 이미 봤나요, 아니면 아직 연락 전인가요?"),
"I'll go check the chart now so we don't miss anything.":("놓치는 게 없도록 지금 환자를 확인하러 갈게요.","놓치는 게 없도록 지금 약 목록을 확인하러 갈게요."),
"He speaks Vietnamese and needs a phone interpreter.":("베트남어를 쓰시고, 대면 통역이 필요합니다.","베트남어를 쓰시고, 전화 통역사가 대기 중입니다."),
"The family prefers a female nurse for personal care.":("가족은 개인 간호에 나이 든 간호사를 선호합니다.","가족은 식사 보조에 여성 간호사를 선호합니다."),
"Please always confirm understanding through the interpreter.":("항상 통역사를 통해 동의했는지 확인해 주세요.","항상 통역사를 통해 이름을 확인해 주세요."),
"Don't rely on the son to interpret for him.":("아드님에게 서류를 맡기지 마세요.","아드님에게 전화를 맡기지 마세요."),
"The interpreter line number is already on his chart.":("통역 전화번호는 이미 벽에 붙어 있습니다.","통역 전화번호는 이미 의사에게 전달했습니다."),
"He's under a seventy-two-hour hold, cannot leave.":("72시간 보류 상태라 면회할 수 없습니다.","72시간 보류 상태라 전화할 수 없습니다."),
"He requires one-to-one observation at all times.":("항상 2대1 관찰이 필요합니다.","항상 1대1 안내가 필요합니다."),
"All sharps and cords have been removed from the room.":("날카로운 물건과 줄은 모두 가방에서 치웠습니다.","날카로운 물건과 줄은 모두 병실에서 세었습니다."),
"Please recheck the room every time you leave and return.":("나갔다 돌아올 때마다 환자를 다시 확인해 주세요.","들어갈 때마다 병실을 다시 확인해 주세요."),
"Security is aware and will call if he tries to leave.":("간호 팀장도 알고 있고, 나가려 하면 연락할 것입니다.","보안팀도 알고 있고, 화내면 연락할 것입니다."),
"The daughter knows the diagnosis but not the prognosis.":("따님은 진단은 알지만 일정은 모릅니다.","따님은 진단은 알지만 보험은 모릅니다."),
"The doctor still needs to speak with the wife.":("간호사가 아직 아내분과 이야기해야 합니다.","의사가 아직 따님과 이야기해야 합니다."),
"The son had a lot of anger earlier — be gentle.":("아드님이 아까 많이 우셨어요, 부드럽게 대해 주세요.","따님이 아까 화가 많이 나셨었어요, 부드럽게 대해 주세요."),
"No one has mentioned the prognosis to the family yet.":("아직 가족에게 치료비를 언급한 사람은 없습니다.","아직 가족에게 퇴원을 언급한 사람은 없습니다."),
"Let the doctor know before you say anything about the prognosis.":("예후에 대해 말하기 전에 책임 간호사에게 먼저 알려 주세요.","퇴원에 대해 말하기 전에 의사에게 먼저 알려 주세요."),
"This is a transfer for a higher level of stroke care.":("심장 상급 치료를 위한 전원입니다.","뇌졸중 재활 치료를 위한 전원입니다."),
"Symptom onset was two hours ago, tPA not given.":("증상 발생은 2시간 전이고, 헬기는 호출하지 않았습니다.","증상 발생은 2시간 전이고, 보호자는 도착하지 않았습니다."),
"All records and imaging are traveling with the patient.":("모든 기록과 영상 자료는 보호자와 함께 이동합니다.","모든 기록과 처방 자료는 환자와 함께 이동합니다."),
"Please confirm the accepting doctor's name before transport.":("이송 전에 수용 병원 이름을 확인해 주세요.","이송 전에 수용 의사 연락처를 확인해 주세요."),
"Her last blood pressure was stable before the transfer.":("전원 전 처음 혈압은 안정적이었습니다.","입원 전 마지막 혈압은 안정적이었습니다."),
"Her pressure keeps dropping despite fluids.":("수액을 줘도 체온이 계속 떨어지고 있습니다.","수액을 줘도 산소가 계속 떨어지고 있습니다."),
"She's on a norepinephrine drip, titrating up.":("노르에피네프린을 투여 중이고, 용량을 확인하고 있습니다.","노르에피네프린을 투여 중이고, 기록을 확인하고 있습니다."),
"She needs an ICU bed and close monitoring right now.":("지금 바로 중환자실 병상과 보호자 면담이 필요합니다.","지금 바로 격리실 병상과 집중 관찰이 필요합니다."),
"Please call the ICU charge nurse and confirm a bed.":("병동 책임 간호사에게 연락해서 병상을 확인해 주세요.","중환자실 책임 간호사에게 연락해서 이송을 확인해 주세요."),
"I'll travel with her and give report at the door.":("제가 먼저 이동해서 문 앞에서 인계하겠습니다.","제가 함께 이동해서 침상 옆에서 인계하겠습니다."),
"Situation: this is a fifty-eight-year-old post-cardiac-arrest patient.":("상황: 68세 심정지 후 소생 환자입니다.","상황: 58세 수술 후 회복 환자입니다."),
"Background: down time was about eight minutes with two shocks.":("배경: 정지 시간은 약 12분이었고, 제세동은 두 번 있었습니다.","배경: 정지 시간은 약 8분이었고, 제세동은 세 번 있었습니다."),
"Right now he's on a norepinephrine drip and intubated.":("지금은 노르에피네프린을 투여 중이고 침대에 누운 상태입니다.","지금은 노르에피네프린을 준비 중이고 삽관된 상태입니다."),
"His pressure has been stable since the last shock.":("첫 제세동 이후 혈압은 안정적이었습니다.","마지막 삽관 이후 혈압은 안정적이었습니다."),
"Can you confirm his last recorded blood pressure for me?":("마지막으로 기록된 체온을 확인해 주시겠어요?","마지막으로 기록된 시각을 확인해 주시겠어요?"),
"Forget what I just said — his status has changed.":("방금 한 말은 적으세요, 상태가 바뀌었습니다.","방금 한 말은 잊으세요, 순서가 바뀌었습니다."),
"His oxygen just dropped to eighty-five percent.":("산소포화도가 80퍼센트로 방금 떨어졌습니다.","산소 탱크가 85퍼센트로 방금 떨어졌습니다."),
"Let's both go see him and reassess together.":("같이 가서 그분 가족을 다시 사정해요.","각자 가서 그분을 다시 사정해요."),
"Call the doctor now — this can't wait.":("지금 바로 책임 간호사를 호출하세요, 기다릴 수 없습니다.","지금 바로 의사를 호출하세요, 보호자가 기다립니다."),
"His monitor is showing the drop in oxygen right now.":("모니터에 지금 맥박 하락이 나타나고 있습니다.","모니터에 아까 산소 수치 하락이 나타났습니다."),
"We didn't get her medication list — do you have it?":("알레르기 목록을 받지 못했는데, 갖고 계신가요?","검사 목록을 받지 못했는데, 갖고 계신가요?"),
"Can you confirm when the last dose was given?":("마지막 측정 시각을 확인해 주시겠어요?","마지막 방문 시각을 확인해 주시겠어요?"),
"I'll reassess from scratch to be safe.":("안전을 위해 처음부터 다시 소개하겠습니다.","안전을 위해 처음부터 같이 사정하겠습니다."),
"The report we got didn't mention any allergies.":("받은 보고에는 병력 언급이 없었습니다.","받은 보고에는 보호자 언급이 없었습니다."),
"Please confirm her vitals time so I can chart it correctly.":("차트에 정확히 기록하도록 활력징후 값을 확인해 주세요.","차트에 정확히 기록하도록 투약 시각을 확인해 주세요."),
"From nursing, her pain is controlled but mobility is poor.":("간호 측면에서는 통증은 조절되지만 식사는 좋지 않습니다.","사회복지 측면에서는 통증은 조절되지만 거동은 좋지 않습니다."),
"Social work is arranging safe discharge to a shelter.":("사회복지팀이 친척 집으로의 안전한 퇴원을 주선하고 있습니다.","사회복지팀이 보호소로의 안전한 이송을 주선하고 있습니다."),
"Let's agree who follows up on each item.":("각 항목을 언제 후속 처리할지 합의해요.","각 환자를 누가 후속 처리할지 합의해요."),
"The doctor still needs to confirm the discharge plan.":("간호사는 아직 퇴원 계획을 확인해야 합니다.","의사는 아직 퇴원 서류를 확인해야 합니다."),
"Her family knows about the shelter plan already.":("환자는 이미 보호소 계획을 알고 있습니다.","가족은 이미 퇴원 계획을 알고 있습니다."),
"We have three reds, five yellows, and eight greens.":("적색 3명, 황색 5명, 녹색 6명입니다.","적색 3명, 황색 7명, 녹색 8명입니다."),
"The reds are in bays one through three, most critical first.":("적색 환자는 1번부터 3번 구역에 있고, 가장 먼저 도착한 순서입니다.","적색 환자는 1번부터 3번 구역에 있고, 가장 어린 순서입니다."),
"Reassess yellows every fifteen minutes for changes.":("황색 환자는 10분마다 변화를 재사정하세요.","녹색 환자는 15분마다 변화를 재사정하세요."),
"Greens can wait in the hallway until we call them.":("녹색 환자는 호출할 때까지 대기실에서 기다릴 수 있습니다.","환자 보호자는 호출할 때까지 복도에서 기다릴 수 있습니다."),
"Here are the triage tags for every bed in this bay.":("이 구역 모든 병상에 대한 투약 기록지입니다.","저 구역 모든 병상에 대한 중증도 분류 태그입니다."),
}
W={'w-noon':(None,['dawn','dusk']),'w-alert':(None,['drowsy','altered']),'w-lab':(None,['ward','unit']),'w-bed':(None,['chair','room']),
'w-hold':(None,['halt','fold']),'w-son':(None,['nephew','uncle']),'w-shock':(None,['spark','shot']),'w-sharp':(['침대 시트','일회용 장갑'],None),'w-norepinephrine':(['에피네프린','바소프레신'],None),'w-elevated':(['정상 범위의','(수치가) 감소한'],None)}
B={"Working diagnosis is dehydration, ruling out infection.":('dehydration',['hypertension','arrhythmia','hemorrhage']),
"Her pressure is borderline and trending down.":('borderline',['excellent','irregular','elevated']),
"Situation: this is a fifty-eight-year-old post-cardiac-arrest patient.":('post-cardiac-arrest',['post-cardiac-surgery','post-respiratory-failure','pre-cardiac-catheter']),
"From nursing, her pain is controlled but mobility is poor.":('controlled',['unbearable','radiating','worsening'])}
apply('core-handoff-er',S,W,B)
