import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"Can you state your full name for me?":("성함을 정확히 적어 주시겠어요?","성함의 철자를 정확히 말씀해 주시겠어요?"),
"And your date of birth, please?":("그리고 의무기록번호도 말씀해 주시겠어요?","그리고 출생지도 말씀해 주시겠어요?"),
"I'm checking this against your wristband.":("이걸 차트와 대조해서 확인할게요.","이걸 처방전과 대조해서 확인할게요."),
"I always confirm two identifiers for every patient.":("저는 모든 환자에게 항상 세 가지 신원 확인 항목을 확인해요.","저는 모든 환자에게 항상 두 가지 신원 확인 항목을 기록해요."),
"This helps prevent us from mixing up two patients.":("이렇게 하면 두 약을 혼동하는 걸 막을 수 있어요.","이렇게 하면 두 가족을 혼동하는 걸 막을 수 있어요."),
"If your name or date of birth doesn't match, I'll stop and ask again.":("이름이나 병상이 일치하지 않으면 멈추고 다시 확인할게요.","이름이나 생년월일이 일치하지 않으면 멈추고 의사에게 물어볼게요."),
"Have you had any falls in the past year?":("지난 1년 동안 입원하신 적이 있으세요?","지난 5년 동안 넘어지신 적이 있으세요?"),
"Do you take any medicines that make you dizzy?":("졸리게 만드는 약을 드시고 계세요?","배를 아프게 만드는 약을 드시고 계세요?"),
"Do you use a cane or walker at home?":("집에서 휠체어나 보행기를 사용하세요?","병원에서 지팡이나 보행기를 사용하세요?"),
"I'll also check if any medicine you take can raise your fall risk.":("복용 중인 약이 출혈 위험을 높이는지도 확인할게요.","복용 중인 약이 낙상 위험을 높이는지도 설명할게요."),
"Based on what I find, we'll work together to prevent a fall.":("확인한 내용을 바탕으로 욕창을 예방하도록 함께 노력할게요.","확인한 내용을 바탕으로 퇴원을 준비하도록 함께 노력할게요."),
"Let's talk about your risk before you get up on your own.":("혼자 앉으시기 전에 위험 요소에 대해 먼저 이야기해요.","혼자 일어나시기 전에 식사에 대해 먼저 이야기해요."),
"I'm lowering the bed and putting the rails up.":("침대를 낮추고 불을 켤게요.","침대를 낮추고 난간을 닦을게요."),
"This is your call button — press it if you need help.":("이건 호출벨이에요, 화장실이 필요하면 누르세요.","이건 호출벨이에요, 도움이 필요하면 두 번 누르세요."),
"Please don't get up on your own; call me first.":("혼자 걷지 마시고, 먼저 저를 불러주세요.","혼자 일어나지 마시고, 먼저 의사를 불러주세요."),
"I'll keep the bed low so it's safe for you to sit up.":("일어나기 안전하도록 바닥을 건조하게 유지할게요.","일어나기 안전하도록 침대를 낮게 유지해 주세요."),
"The top rails will stay up whenever I'm not right beside you.":("제가 바로 옆에 없을 때는 호출벨을 가까이 둘게요.","제가 바로 옆에 없을 때는 침대 불을 켜 둘게요."),
"Press the call button anytime you need help — don't try to get up alone.":("도움이 필요하면 언제든 호출벨을 누르시고, 혼자 걷지 마세요.","도움이 필요하면 언제든 호출벨을 누르시고, 혼자 식사하지 마세요."),
"Setting up your bed and call button correctly helps prevent falls.":("침대와 호출벨을 올바르게 설정하면 욕창을 예방하는 데 도움이 돼요.","침대와 조명을 올바르게 설정하면 낙상을 예방하는 데 도움이 돼요."),
"Let's check the bed height together before I go.":("제가 가기 전에 호출벨 위치를 같이 확인해요.","제가 가기 전에 침대 난간을 같이 확인해요."),
"Your band says you're allergic to penicillin, correct?":("차트에는 페니실린 알레르기가 있다고 되어 있는데, 맞나요?","밴드에는 페니실린 알레르기가 있다고 되어 있는데, 언제부터인가요?"),
"Any other allergies we should add?":("추가해야 할 다른 약이 있으세요?","추가해야 할 다른 병력이 있으세요?"),
"This red band alerts everyone on the team.":("이 노란 밴드가 팀 전체에게 알려줘요.","이 빨간 밴드가 의사에게만 알려줘요."),
"Let me check your chart to confirm this allergy record.":("처방을 확인해서 이 알레르기 기록을 대조할게요.","차트를 확인해서 이 알레르기 기록을 갱신할게요."),
"I don't see any penicillin allergy on your chart.":("밴드에는 페니실린 알레르기가 없다고 되어 있네요.","차트에는 페니실린 처방이 없다고 되어 있네요."),
"Let's add that to your allergy band and your chart together.":("그럼 알레르기 밴드와 처방에 같이 추가할게요.","그럼 알레르기 밴드와 차트를 같이 확인할게요."),
"I'm making sure your IV line is secure.":("소변줄이 잘 고정되어 있는지 확인할게요.","정맥 주사줄이 잘 고정되어 있는지 기록할게요."),
"Your oxygen tank is full for the trip.":("이송에 필요한 서류는 가득 차 있어요.","이송에 필요한 산소통은 제가 가져갈게요."),
"Please stay lying down while we move you.":("옮기는 동안 눈을 뜨고 계세요.","옮기는 동안 말씀하지 마세요."),
"Before we leave, let's check that all your lines and tubing are secure.":("나가기 전에 모든 짐이 잘 고정되어 있는지 확인할게요.","나가기 전에 모든 줄이 잘 정리되어 있는지 확인할게요."),
"I'll also make sure your fall risk precautions are in place for the move.":("이동을 위한 욕창 예방 조치도 확인할게요.","이동을 위한 감염 예방 조치도 확인할게요."),
"Once we arrive, stay lying down until the team says it's safe to sit up.":("도착하면 팀이 부를 때까지 누워 계세요.","도착하면 팀이 안전하다고 할 때까지 조용히 계세요."),
"You're a bit unsteady, so let me help you move.":("조금 피곤하시니 제가 옮기는 걸 도와드릴게요.","조금 불안정하시니 제가 옷 갈아입는 걸 도와드릴게요."),
"Press this button and I'll come right away.":("이 줄을 당기시면 바로 갈게요.","이 버튼을 누르시면 불이 바로 켜져요."),
"For now, stay in bed so you don't fall.":("지금은 넘어지지 않도록 신발을 신고 계세요.","지금은 추워지지 않도록 침대에 계세요."),
"I'll check on you often since you're confused and at high risk for falling.":("혼란스러운 상태라 낙상 위험이 높아서 자주 기록할게요.","어지러운 상태라 낙상 위험이 높아서 자주 확인할게요."),
"I'm keeping a close watch on you tonight because of your fall risk.":("낙상 위험 때문에 오늘 밤 계속 기록할게요.","낙상 위험 때문에 오늘 아침 계속 지켜볼게요."),
"Let me remind you again: please stay in bed and call before you stand.":("다시 한번 보여드릴게요, 침대에 계시고 일어나기 전에 불러주세요.","다시 한번 알려드릴게요, 침대에 계시고 식사하기 전에 불러주세요."),
"Is this hydralazine or hydroxyzine? Let's confirm.":("이거 하이드랄라진이에요, 하이드록시진이에요? 같이 읽어 봐요.","이거 하이드랄라진이에요, 하이드록시진이에요? 약사와 확인해요."),
"Can you verify the concentration with me?":("유통기한을 저와 같이 확인해 주시겠어요?","농도를 약사와 같이 확인해 주시겠어요?"),
"Right patient, right dose — read it back to me.":("정확한 환자, 정확한 시간이에요, 저한테 다시 읽어주세요.","정확한 환자, 정확한 용량이에요, 저한테 다시 적어주세요."),
"These two medicine names look alike, so let's say them out loud together.":("이 두 약 상자가 비슷해서 같이 소리 내어 말해요.","이 두 환자 이름이 비슷해서 같이 소리 내어 말해요."),
"If the concentration doesn't match the order, we stop right away.":("용량이 처방과 일치하지 않으면 바로 멈춰요.","농도가 라벨과 일치하지 않으면 바로 멈춰요."),
"Let's check it again together before we give a single dose.":("용량을 주기 전에 같이 두 번 더 확인해요.","약을 받기 전에 같이 한 번 더 확인해요."),
"Register him as unknown male, trauma alpha.":("신원 불명 여성, 트라우마 알파로 등록할게요.","신원 불명 남성, 트라우마 베타로 등록할게요."),
"Put the temporary band on and label all samples with it.":("임시 밴드를 채우고 모든 서류에 그걸로 라벨을 붙여요.","임시 밴드를 채우고 모든 약에 그걸로 라벨을 붙여요."),
"We'll update the record once we identify him.":("신원이 확인되면 가족에게 연락할게요.","신원이 확인되면 기록을 출력할게요."),
"Until we know his name, every sample and chart uses this same temporary ID.":("이름을 알기 전까지는 모든 검체와 차트에 같은 임시 색을 써요.","이름을 알기 전까지는 모든 검체와 서류에 같은 임시 번호를 써요."),
"Let's confirm the team knows he's registered as trauma alpha.":("팀이 임시 밴드를 찬 걸 알고 있는지 확인해요.","가족이 트라우마 알파로 등록된 걸 알고 있는지 확인해요."),
"Once we identify him, we'll update his real name everywhere at once.":("신원이 확인되면 모든 곳에 실명을 한 번에 출력할게요.","신원이 확인되면 가족에게 실명을 한 번에 알릴게요."),
"This tube is for bed four, not bed six — let's confirm.":("이 튜브는 3번 침상용이에요, 6번이 아니고요, 같이 확인해요.","이 튜브는 4번 침상용이에요, 5번이 아니고요, 같이 확인해요."),
"Read me the name and the order together.":("이름과 생년월일을 같이 읽어주세요.","이름과 오더를 같이 적어주세요."),
"We label at the bedside, never at the desk.":("라벨은 침상 옆에서 붙이고, 복도에서는 절대 안 해요.","서류는 침상 옆에서 붙이고, 데스크에서는 절대 안 해요."),
"With two patients in the room, it's easy to grab the wrong tube.":("한 병실에 환자가 셋이면 다른 튜브를 잘못 집기 쉬워요.","한 병실에 환자가 둘이면 다른 약을 잘못 집기 쉬워요."),
"Always check the wristband before you label the tube.":("튜브에 라벨을 붙이기 전에 항상 손을 씻어요.","튜브에 라벨을 붙인 뒤에 항상 손목밴드를 확인해요."),
"Never carry labels to the desk and label them there instead.":("라벨을 복도로 가져가서 붙이면 절대 안 돼요.","라벨을 데스크로 가져가서 읽으면 절대 안 돼요."),
"Stay still — can you tell me where it hurts?":("가만히 계세요, 어디서 넘어지셨는지 말씀해 주시겠어요?","가만히 계세요, 언제 아프기 시작했는지 말씀해 주시겠어요?"),
"Did you hit your head at all?":("목을 부딪히셨어요?","머리를 어디에 부딪히셨어요?"),
"I'm going to check you before we move you up.":("일으키기 전에 먼저 확인해 볼게요.","옮기기 전에 먼저 물어볼게요."),
"Let's check for any injury before you try to stand again.":("다시 걷기 전에 손상이 없는지 확인해요.","다시 일어서기 전에 통증이 없는지 확인해요."),
"I'll report this fall and update your care plan to prevent another one.":("이 낙상을 설명하고 재발 방지를 위해 계획을 갱신할게요.","이 낙상을 보고하고 퇴원을 위해 계획을 갱신할게요."),
"You're okay for now — let's talk about how to prevent this from happening again.":("지금은 괜찮으세요, 재발을 막을 방법을 같이 기록해요.","지금은 괜찮으세요, 재발을 막을 사람을 같이 이야기해요."),
"This is temporary, only to keep him from pulling his lines.":("이건 일시적인 거예요, 침대에서 떨어지지 못하게 하려는 것뿐이에요.","이건 일시적인 거예요, 줄이 엉키지 않게 정리하려는 것뿐이에요."),
"We check his circulation and skin every hour.":("30분마다 혈액 순환과 피부를 확인해요.","매시간 혈액 순환과 호흡을 확인해요."),
"We'll remove them as soon as it's safe.":("안전해지는 대로 바로 보고드릴게요.","안전해지는 대로 바로 옮겨드릴게요."),
"Restraints are only used when he might pull out his IV line or breathing tube.":("억제대는 정맥 주사줄이나 소변줄을 잡아당길 위험이 있을 때만 사용해요.","억제대는 정맥 주사줄이나 기관 튜브를 잡아당길 위험이 있을 때만 확인해요."),
"Let me explain why this is safe for him right now.":("지금 이게 왜 필요한지 설명해 드릴게요.","지금 이게 왜 안전한지 기록해 드릴게요."),
"As soon as he's calmer, we'll remove the restraint and check his skin again.":("진정되면 바로 억제대를 풀고 순환을 다시 확인할게요.","진정되면 바로 억제대를 풀고 피부를 기록할게요."),
"He's in isolation to protect others from infection.":("다른 사람들을 감염으로부터 보호하려고 대기 중이에요.","다른 사람들을 감염으로부터 보호하려고 청소 중이에요."),
"Please wear this gown, gloves, and mask before entering.":("들어가시기 전에 이 가운, 장갑, 마스크, 모자를 착용해 주세요.","들어가시기 전에 이 가운, 장갑, 마스크를 확인해 주세요."),
"Wash your hands well when you go in and out.":("들어가고 나올 때 손을 두 번 씻어 주세요.","들어가고 나올 때 문을 잘 닫아 주세요."),
"Isolation helps stop infection from spreading to other patients.":("격리는 감염이 다른 가족에게 퍼지는 걸 막아줘요.","격리는 소음이 다른 환자에게 퍼지는 걸 막아줘요."),
"A gown and gloves protect you from picking up any infection.":("가운과 장갑이 옷이 젖지 않도록 보호해줘요.","가운과 장갑이 감염되지 않도록 갈아 입혀줘요."),
"Always wash your hands again right after you leave the room.":("병실에 들어가기 직전에는 항상 손을 씻어 주세요.","병동을 나온 직후에는 항상 다시 손을 씻어 주세요."),
"I'm keeping the room safe for you right now.":("지금 방을 깨끗하게 만들고 있어요.","지금 침대를 안전하게 만들고 있어요."),
"Someone will stay with you at all times.":("항상 누군가가 문 앞에 있을 거예요.","항상 누군가가 곁에서 기록할 거예요."),
"You're not in trouble — we just want to help.":("곤란한 상황이 아니에요, 저희는 그냥 듣고 싶을 뿐이에요.","곤란한 상황이 아니에요, 저희는 그냥 확인하고 싶을 뿐이에요."),
"I'm going to remove anything in the room that could hurt you.":("다치게 할 수 있는 물건은 방에서 모두 확인할게요.","다치게 할 수 있는 물건은 방에서 모두 기록할게요."),
"I'll check on you often, and someone will always be close by.":("자주 설명할게요, 그리고 항상 가까이에 누군가 있을 거예요.","자주 확인할게요, 그리고 항상 문 앞에 누군가 있을 거예요."),
"We just want to keep you safe — you can always ask me for help.":("저희는 그저 편하게 해드리고 싶어요, 언제든 도움을 요청하세요.","저희는 그저 안전하게 지켜드리고 싶어요, 언제든 가족에게 요청하세요."),
"Time-out: this is John Reyes, date of birth March 3, 1962.":("타임아웃, 이분은 존 레예스, 생년월일은 1962년 3월 8일이에요.","타임아웃, 이분은 존 로페즈, 생년월일은 1962년 3월 3일이에요."),
"We're doing a right chest tube — everyone agree?":("오른쪽 흉관 삽입을 할 거예요, 모두 준비되셨어요?","오른쪽 흉관 삽입을 할 거예요, 모두 들으셨어요?"),
"Consent is signed and the site is marked.":("동의서는 서명됐고 장갑은 준비됐어요.","서류는 서명됐고 부위는 표시됐어요."),
"Before we start the procedure, let's confirm the patient's name together.":("시술을 시작하기 전에 환자분 병상을 같이 확인해요.","시술을 시작하기 전에 환자분 성함을 의사가 확인해요."),
"If anything doesn't match, we stop right there.":("뭔가 부족하면 그 자리에서 멈춰요.","뭔가 일치하지 않으면 그 자리에서 멈추고 말해요."),
"Everyone on the team must agree before we begin the procedure.":("시술을 시작하기 전에 팀 전체가 모여야 해요.","시술을 시작하기 전에 팀 전체가 소독해야 해요."),
"Her heart rate is up and pressure is dropping.":("심박수는 오르고 체온은 떨어지고 있어요.","호흡수는 오르고 혈압은 떨어지고 있어요."),
"Respiratory rate is thirty and she's confused.":("호흡수는 30이고 계속 어지러워요.","호흡수는 30이고 체온이 높아요."),
"I need eyes on her now — this is a rapid response.":("지금 바로 봐주셔야 해요, 코드 블루예요.","지금 바로 봐주셔야 해요, 신속검사예요."),
"These vital signs are getting worse fast, so I'm watching her closely.":("활력징후가 빠르게 나빠지고 있어서 계속 기록하고 있어요.","활력징후가 빠르게 나빠지고 있어서 계속 보고하고 있어요."),
"I'm calling the rapid response team right now before she gets worse.":("더 나빠지기 전에 지금 바로 책임 간호사를 부를게요.","더 나빠지기 전에 지금 바로 의사를 부를게요."),
"I'll give the team a clear report: vitals, symptoms, and what changed.":("팀에게 활력징후, 증상, 병력을 명확히 보고할게요.","가족에게 활력징후, 증상, 변화 사항을 명확히 보고할게요."),
"Two patients have similar names — let's double-check bands.":("두 약 이름이 비슷해요, 밴드를 다시 확인해요.","두 환자 이름이 비슷해요, 차트를 다시 확인해요."),
"Confirm the medical record number, not just the name.":("이름만이 아니라 생년월일을 확인해 주세요.","이름만이 아니라 의무기록번호를 기록해 주세요."),
"Let's slow down for ten seconds and get this right.":("10초만 천천히 해서 정확히 읽어요.","10초만 천천히 해서 정확히 기록해요."),
"It's crowded right now, so let's re-verify who's who before we act.":("지금 혼잡하니까 행동하기 전에 누가 어디 있는지 다시 확인해요.","지금 혼잡하니까 퇴근하기 전에 누가 누군지 다시 확인해요."),
"Always confirm the record number, never rely on the name alone.":("이름만 믿지 말고 항상 기록번호를 기록해요.","이름만 믿지 말고 항상 기록번호를 두 번 확인해요."),
"When two names look alike, double-check the wristband every single time.":("이름이 비슷할 때는 매번 차트를 다시 확인해요.","생년월일이 비슷할 때는 매번 손목밴드를 다시 확인해요."),
"Because you take a blood thinner, we need a head scan fast.":("항응고제를 복용하고 계셔서 빨리 피검사가 필요해요.","항응고제를 복용하고 계셔서 빨리 머리 스캔 동의가 필요해요."),
"Tell me if your headache gets worse or you feel sleepy.":("두통이 심해지거나 어지러우면 말씀해 주세요.","두통이 심해지거나 구역질이 나면 말씀해 주세요."),
"Do you feel any numbness or trouble seeing?":("저림이나 청력 문제가 있으세요?","어지럼이나 시야 문제가 있으세요?"),
"Because you're on a blood thinner, even a small fall can cause bleeding.":("항응고제를 복용 중이라 작은 수술도 출혈을 일으킬 수 있어요.","항응고제를 복용 중이라 작은 낙상도 어지럼을 일으킬 수 있어요."),
"We'll watch you closely and repeat the head scan if anything changes.":("계속 지켜보고 변화가 있으면 피검사를 다시 할게요.","계속 지켜보고 변화가 있으면 심전도를 다시 할게요."),
"Let me know right away if you feel any numbness or your headache changes.":("어지러움이 느껴지거나 두통이 변하면 바로 말씀해 주세요.","저림이 느껴지거나 기침이 변하면 바로 말씀해 주세요."),
"The patient got double the ordered dose.":("환자분이 처방된 용량의 세 배를 받았어요.","환자분이 처방된 용량의 두 배를 요청했어요."),
"We're monitoring her vitals and notifying the doctor.":("활력징후를 관찰하고 책임 간호사에게 알리고 있어요.","활력징후를 관찰하고 가족에게 알리고 있어요."),
"I'll complete an incident report right away.":("바로 사건 보고서를 읽을게요.","바로 사건 보고서를 출력할게요."),
"First, we make sure the patient is safe and stable.":("먼저 환자분이 안전하고 안정적인지 기록해요.","먼저 환자분이 안전한 침대에 있는지 확인해요."),
"I'm reporting exactly what happened, even though it's hard.":("힘들어도 있었던 일을 천천히 보고할게요.","피곤해도 있었던 일을 그대로 보고할게요."),
"We'll document this honestly so the team can learn from it.":("팀이 배울 수 있도록 이걸 정직하게 공유할게요.","팀이 쉴 수 있도록 이걸 정직하게 문서화할게요."),
"Ambulatory patients out this exit first.":("거동 가능한 직원부터 이 출구로 나가세요.","거동 가능한 환자부터 이 계단으로 나가세요."),
"The intubated patient needs a team to move the bed.":("삽관된 환자는 침대를 옮길 장비가 필요해요.","삽관된 환자는 침대를 닦을 팀이 필요해요."),
"Close doors behind us and account for everyone.":("뒤로 불을 끄고 모든 인원을 확인하세요.","뒤로 문을 닫고 모든 물품을 확인하세요."),
"Patients who can walk go out first, then we move the rest by bed.":("걸을 수 있는 환자가 먼저 나가고, 나머지는 직원이 따라가요.","걸을 수 있는 직원이 먼저 나가고, 나머지는 침대로 옮겨요."),
"Two of us will move the intubated patient on the bed together.":("저희 셋이서 삽관된 환자를 침대째로 같이 옮길게요.","저희 둘이서 삽관된 환자를 침대째로 같이 지켜볼게요."),
"Once everyone is out, close the doors and check the count together.":("모두 나가면 불을 끄고 같이 인원을 확인해요.","모두 나가면 문을 닫고 같이 인원을 기록해요."),
"Key risks are aspiration and a difficult airway.":("핵심 위험은 감염과 어려운 기도예요.","핵심 위험은 흡인과 어려운 자세예요."),
"She's a high fall risk and on anticoagulation.":("감염 위험이 높고 항응고 치료 중이에요.","욕창 위험이 높고 항응고 치료 중이에요."),
"Everyone clear on their role if she deteriorates?":("악화될 경우 각자 위치는 다 명확하세요?","퇴원할 경우 각자 역할은 다 명확하세요?"),
"Let's brief the team on her key risks before the shift starts.":("근무 시작 전에 팀에게 핵심 일정을 브리핑해요.","근무 시작 전에 가족에게 핵심 위험을 브리핑해요."),
"If she starts to deteriorate, everyone already knows their role and acts fast.":("악화되기 시작하면 모두 이미 자기 역할을 알고 조용히 움직여요.","악화되기 시작하면 모두 이미 자기 차례를 알고 빠르게 움직여요."),
"We share the airway plan and the fall risk together, out loud.":("기도 계획과 낙상 위험을 글로 같이 공유해요.","기도 계획과 낙상 위험을 소리 내어 따로 공유해요."),
}
W={'w-dob':(None,['date of arrival','place of birth']),'w-state':(['(이름 등을) 서명하다','(이름 등을) 기억하다'],None),
'w-identifier':(['검사 항목','확인 서류'],None),'w-walker':(None,['crutches','cane']),'w-right_away':(None,['right side','all along']),
'w-allergy':(['부작용','독성 반응'],None),'w-trip':(['대기(기다림)','출발(떠남)'],None),
'w-at_all_times':(['가끔(필요할 때만 한 번씩)','즉시(지체 없이 곧바로)'],['at times','at first']),
'w-hydralazine':(['히드록시진','히드로코르티손'],['hydroxyzine','hydrocortisone']),'w-order':(['기록(차트)','의뢰(요청)'],None),
'w-unknown':(None,['unwell','unsure']),'w-identify':(['강화하다','통지하다'],None),'w-id':(['정맥 주사(IV)','골내 주사(IO)'],None),
'w-heart_rate':(None,['heart rhythm','heart size']),'w-respiratory_rate':(None,['respiratory effort','respiratory failure']),
'w-rapid_response':(None,['rapid sequence','rapid recovery']),'w-scan':(['채혈(혈액검사)','수술(외과 수술)'],None),
'w-anticoagulation':(None,['anticonvulsant','antihypertensive'])}
B={"If she starts to deteriorate, everyone already knows their role and acts fast.":('deteriorate',['overreact','reorganize','disappear'])}
apply('core-safety-er',S,W,B)
