import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"He's being examined and is stable right now.":("환자분은 지금 엑스레이를 찍고 있고, 상태는 안정적이에요.","환자분은 아까 진찰을 받으셨고, 상태는 안정적이에요."),
"The tests take about an hour to come back.":("검사 결과가 나오는 데 세 시간 정도 걸려요.","영상 결과가 나오는 데 한 시간 정도 걸려요."),
"I'll come find you as soon as we know more.":("더 알게 되는 대로 바로 전화드릴게요.","더 알게 되는 대로 주치의가 찾아뵐게요."),
"Let me update you on how things are going.":("지금 어디서 기다리면 되는지 알려드릴게요.","지금 누가 진행하고 있는지 알려드릴게요."),
"Try to relax, we're taking good care of him.":("앉아 계셔도 돼요, 저희가 잘 돌봐드리고 있어요.","긴장 푸셔도 돼요, 저희가 어머님을 잘 돌봐드리고 있어요."),
"We allow one visitor at the bedside at a time.":("한 번에 두 분만 침상 곁에 계실 수 있어요.","한 번에 한 분만 대기실에 계실 수 있어요."),
"You can go in for a few minutes shortly.":("내일 잠깐 들어가실 수 있어요.","곧 한 시간쯤 들어가실 수 있어요."),
"This helps us keep the area safe and calm.":("이렇게 하면 이 공간을 깨끗하고 차분하게 유지할 수 있어요.","이렇게 하면 이 공간을 따뜻하고 차분하게 유지할 수 있어요."),
"Right now, only one person can be at the bedside.":("지금은 세 분만 침상 곁에 계실 수 있어요.","지금은 한 분만 복도에 계실 수 있어요."),
"It also helps her rest and stay calm.":("그래야 환자분도 먹으면서 차분하게 계실 수 있어요.","그래야 저희도 쉬면서 차분하게 일할 수 있어요."),
"Can I confirm your name and how you're related?":("주소와 환자분과의 관계를 확인해도 될까요?","성함과 환자분과의 연락처를 확인해도 될까요?"),
"Are you the patient's emergency contact?":("환자분의 주치의이신가요?","환자분의 대리인이신가요?"),
"This helps us know what we can share with you.":("이걸 알아야 어디까지 보여드릴 수 있는지 알 수 있어요.","이걸 알아야 누구에게 말씀드릴 수 있는지 알 수 있어요."),
"May I ask your relationship to the patient?":("환자분의 연세가 어떻게 되시는지 여쭤봐도 될까요?","환자분과 얼마나 함께 사셨는지 여쭤봐도 될까요?"),
"It's okay if you're not sure, I can check our records.":("확실하지 않으셔도 괜찮아요, 저희 간호사에게 물어볼게요.","확실하지 않으셔도 괜찮아요, 저희 기록을 다시 써 볼게요."),
"That's a good question — let me explain again.":("좋은 질문이에요, 먼저 설명해 드릴게요.","좋은 질문이에요, 의사 선생님께 확인해 드릴게요."),
"It's okay to ask as many times as you need.":("몇 번이든 필요한 만큼 적어 두셔도 괜찮아요.","몇 번이든 필요한 만큼 전화하셔도 괜찮아요."),
"I can see you're worried, and that's understandable.":("피곤하신 게 보여요, 그리고 그건 당연한 거예요.","걱정되시는 게 들려요, 그리고 그건 당연한 거예요."),
"I know it's a lot — ask me anything you need.":("많은 일이라는 거 알아요, 필요한 건 뭐든 적어 보세요.","급한 일이라는 거 알아요, 필요한 건 뭐든 물어보세요."),
"Every question you have matters to me.":("하시는 모든 질문이 의사에게는 중요해요.","하시는 모든 질문이 가족에게는 중요해요."),
"He's stable, and his vital signs look good.":("환자분은 안정적이고, 식사도 잘하세요.","따님은 안정적이고, 활력징후도 좋아요."),
"We're running some tests to find the cause.":("원인을 찾기 위해 몇 가지 질문을 드리고 있어요.","원인을 찾기 위해 몇 가지 기록을 보고 있어요."),
"There's no immediate danger right now.":("지금 당장 면회할 수 있는 상황은 아니에요.","지금 당장 퇴원할 상황은 아니에요."),
"Here's where your dad stands right now.":("지금 어머님 상태는 이렇습니다.","지금 아버님 일정은 이렇습니다."),
"We'll keep you posted as soon as we know more.":("더 알게 되는 대로 바로 문자 드릴게요.","더 알게 되는 대로 바로 의사에게 알려드릴게요."),
"I know not knowing is really hard.":("아프다는 게 정말 힘들다는 거 알아요.","잊는다는 게 정말 힘들다는 거 알아요."),
"I don't have the results yet, but I'll be honest when I do.":("아직 결과가 안 나왔지만, 나오면 바로 말씀드릴게요.","아직 의사가 안 왔지만, 오면 솔직하게 말씀드릴게요."),
"Is there anything I can get you while you wait?":("기다리시는 동안 여쭤볼 게 있을까요?","기다리시기 전에 가져다드릴 게 있을까요?"),
"Waiting is the hardest part — let me sit with you.":("기다리는 게 가장 힘든 부분이죠, 제가 곧 올게요.","기다리는 게 가장 힘든 부분이죠, 제가 자리 잡아 둘게요."),
"You're not alone while we wait for these results.":("수술을 기다리는 동안 혼자가 아니에요.","의사를 기다리는 동안 혼자가 아니에요."),
"Let me clarify what we actually know so far.":("지금까지 저희가 실제로 한 걸 정리해서 말씀드릴게요.","지금까지 저희가 실제로 아는 걸 적어서 말씀드릴게요."),
"I understand you heard something different earlier.":("아까 다른 이야기를 하셨다는 거 이해해요.","어제 다른 이야기를 들으셨다는 거 이해해요."),
"It might help to designate one contact person.":("연락 담당자를 두 분 정하시면 도움이 될 거예요.","통역 담당자를 한 분 정하시면 도움이 될 거예요."),
"Let's make sure everyone has the same information.":("모두가 같은 번호를 갖도록 확실히 해봐요.","모두가 같은 시간에 오도록 확실히 해봐요."),
"I'm not taking sides, I just want the facts clear for everyone.":("편을 드는 게 아니라, 모두를 위해 기록을 명확히 하고 싶은 거예요.","편을 드는 게 아니라, 아버님을 위해 사실을 명확히 하고 싶은 거예요."),
"Can you tell me what worries you about the treatment?":("치료비에 대해 무엇이 걱정되시는지 말씀해 주시겠어요?","수술에 대해 무엇이 걱정되시는지 말씀해 주시겠어요?"),
"We also need to honor what your father would want.":("저희도 어머님이 원하셨을 것을 존중해야 해요.","저희도 아버님이 원하셨을 것을 기록해야 해요."),
"Let's involve the doctor to talk this through.":("간호 팀장님도 함께 이야기 나눠봐요.","사회복지사도 함께 이야기 나눠봐요."),
"Help me understand what's behind this decision.":("이 결정 뒤에 어떤 사람이 있는지 이해하고 싶어요.","이 결정이 언제 나왔는지 이해하고 싶어요."),
"I hear how much you love him, and I want to help him too.":("아버님을 얼마나 걱정하시는지 느껴져요, 저도 도와드리고 싶어요.","아버님을 얼마나 사랑하시는지 느껴져요, 저도 함께 있고 싶어요."),
"You can hold her hand while we work.":("저희가 처치하는 동안 아이 담요를 잡아주셔도 돼요.","저희가 검사하는 동안 아이 손을 잡아주셔도 돼요."),
"Everything we're doing is to help her feel better.":("저희가 하는 모든 건 부모님이 쉬도록 돕기 위한 거예요.","저희가 하는 모든 건 아이가 웃도록 돕기 위한 거예요."),
"Tell me what usually comforts her at home.":("학교에서는 보통 뭐가 아이를 진정시키는지 알려주세요.","집에서는 보통 누가 아이를 진정시키는지 알려주세요."),
"We're taking good care of her — you can stay close.":("저희가 잘 돌보고 있어요, 잠시 쉬셔도 돼요.","저희가 잘 돌보고 있어요, 밖에서 기다리셔도 돼요."),
"You're doing great, and talking softly really helps her relax.":("잘하고 계세요, 부드럽게 노래해 주시면 아이가 진정하는 데 도움이 돼요.","잘하고 계세요, 부드럽게 말씀해 주시면 아이가 먹는 데 도움이 돼요."),
"Please tell me what practices are important to you.":("환자분께 중요한 음식이 무엇인지 말씀해 주세요.","가족분께 중요한 관습이 무엇인지 말씀해 주세요."),
"We can make space and time for prayer.":("쉴 수 있는 공간과 시간을 마련해 드릴 수 있어요.","기도할 수 있는 공간과 담요를 마련해 드릴 수 있어요."),
"I'll coordinate with the team to honor that.":("그걸 존중할 수 있도록 원무과와 조율해 볼게요.","그걸 기록할 수 있도록 팀과 조율해 볼게요."),
"We'll do our best to honor your family's wishes.":("가족분들의 뜻을 전달하도록 최선을 다할게요.","가족분들의 식사를 챙기도록 최선을 다할게요."),
"What matters most to your family during this time?":("이 시간 동안 환자분께 가장 중요한 게 무엇인가요?","이 시간 동안 가족분들께 가장 힘든 게 무엇인가요?"),
"I can see how much you care about her.":("따님을 얼마나 아끼시는지 느껴져요.","환자분을 얼마나 믿으시는지 느껴져요."),
"For her safety, I need a little space to work.":("환자분의 안전을 위해 제가 앉을 공간이 조금 필요해요.","환자분의 안전을 위해 제가 지나갈 공간이 조금 필요해요."),
"You can help most by staying near her head and talking softly.":("침대 끝 쪽 가까이 계시면서 부드럽게 말씀해 주시는 게 가장 도움이 돼요.","머리 쪽 가까이 계시면서 부드럽게 손잡아 주시는 게 가장 도움이 돼요."),
"I know you want to help — let me show you how.":("도와주고 싶으신 마음 알아요, 어디서 하면 될지 보여 드릴게요.","도와주고 싶으신 마음 알아요, 어떻게 하면 될지 적어 드릴게요."),
"You can stand right here and talk softly to her.":("바로 여기 앉아서 환자분께 부드럽게 말씀해 주셔도 돼요.","바로 여기 서서 환자분께 부드럽게 노래해 주셔도 돼요."),
"Let's step into a private room where we can talk.":("이야기 나눌 수 있는 넓은 방으로 들어가 볼까요.","식사하실 수 있는 조용한 방으로 들어가 볼까요."),
"What do you already understand about his condition?":("지금 어머님 상태에 대해 어디까지 알고 계신가요?","지금 아버님 상태에 대해 언제부터 알고 계신가요?"),
"Is there someone you'd like to have with you?":("연락드렸으면 하는 분이 있으신가요?","함께 계셨으면 하는 곳이 있으신가요?"),
"The doctor will be here soon — let's find a quiet space.":("간호사 선생님이 곧 오실 거예요, 조용한 공간을 찾아볼게요.","의사 선생님이 곧 오실 거예요, 편한 의자를 찾아볼게요."),
"Take a moment, and let me know if you need anything before we talk.":("잠시 마음을 가다듬으시고, 이야기 나눈 뒤에 필요한 게 있으면 말씀해 주세요.","잠시 마음을 가다듬으시고, 이야기 나누기 전에 물 한 잔 드릴게요."),
"I'm calling to update you on your mother's condition.":("아버님 상태를 알려드리려고 전화드렸어요.","어머님 보험을 알려드리려고 전화드렸어요."),
"She's stable, and here's what's happening now.":("안정적이시고, 지금 위치는 이래요.","안정적이시고, 지금 일정은 이래요."),
"You can call this number anytime for updates.":("이 번호로 언제든 문자하셔서 소식을 확인하실 수 있어요.","이 번호로 밤에는 전화하셔서 소식을 확인하실 수 있어요."),
"I'll walk you through everything over the phone.":("문자로 하나하나 설명해 드릴게요.","방문하셔서 하나하나 설명해 드릴게요."),
"Please write down this direct line in case you need to reach us.":("저희에게 연락하실 일이 있으면 이 직통 번호를 외워두세요.","저희에게 연락하실 일이 있으면 이 병원 주소를 적어두세요."),
"I have very difficult news to share.":("아주 급한 소식을 전해드려야 해요.","아주 힘든 질문을 드려야 해요."),
"We did everything we could, but he has passed away.":("저희가 할 수 있는 모든 걸 했지만, 어머님이 돌아가셨어요.","저희가 할 수 있는 모든 걸 했지만, 오늘 아침 돌아가셨어요."),
"Take all the time you need — I'm here with you.":("필요한 만큼 시간을 가지세요, 제가 곧 올게요.","필요한 만큼 시간을 가지세요, 제가 문 앞에 있을게요."),
"I'm so sorry — despite everything, he has died.":("정말 죄송합니다, 최선을 다했지만 따님이 돌아가셨습니다.","정말 죄송합니다, 새벽까지 최선을 다했지만 돌아가셨습니다."),
"I'm not going anywhere — I'll stay right here with you.":("저는 어디 안 가요, 계속 전화 받을게요.","저는 어디 안 가요, 계속 대기실에 있을게요."),
"The team is doing everything possible for her.":("팀이 할 수 있는 모든 걸 다 설명하고 있어요.","가족이 할 수 있는 모든 걸 다 하고 있어요."),
"I'll explain what's happening as we go.":("진행되는 상황을 계속 기록해 드릴게요.","진행되는 상황을 나중에 설명해 드릴게요."),
"Stand here with me — you can talk to her.":("제 뒤에 서 계세요, 환자분께 말을 걸어주셔도 돼요.","제 옆에 서 계세요, 환자분께 노래를 불러주셔도 돼요."),
"You can be here with her — I'll stay by your side.":("곁에 계셔도 돼요, 저는 뒤에서 지켜볼게요.","문 앞에 계셔도 돼요, 저도 옆에서 함께할게요."),
"I'll keep telling you what the team is doing for her.":("팀이 어디 있는지 계속 말씀드릴게요.","의사가 무엇을 하고 있는지 계속 말씀드릴게요."),
"I can't imagine how hard this moment is.":("이 순간이 얼마나 외로우실지 상상도 안 돼요.","이 순간이 얼마나 긴지 상상도 안 돼요."),
"It's okay to feel however you feel right now.":("지금 어떤 말씀을 하시든 괜찮아요.","지금 눈물이 나시든 괜찮아요."),
"When you're ready, I can help with next steps.":("준비되시면 이전 절차를 설명해 드릴게요.","준비되시면 다음 병실을 안내해 드릴게요."),
"There are no right words — I'm here with you.":("어떤 말도 위로가 되지 않겠지만, 제가 곧 올게요.","어떤 말도 위로가 되지 않겠지만, 의사가 곁에 있을게요."),
"I'm right here, and there's no need to rush anything.":("제가 바로 여기 있어요, 앉으셔도 돼요.","제가 바로 문 앞에 있어요, 서두르지 않으셔도 돼요."),
"Had she ever shared her wishes about this?":("이런 것에 대해 평소에 뜻을 적어 두신 적이 있나요?","이런 것에 대해 최근에 뜻을 말씀하신 적이 있나요?"),
"Our goal can be comfort rather than more machines.":("목표를 기계보다는 가족에 둘 수 있어요.","목표를 병실보다는 편안함에 둘 수 있어요."),
"There's no wrong choice — let's decide together.":("틀린 선택은 없어요, 함께 기도해요.","틀린 선택은 없어요, 제가 결정해요."),
"Let's talk about what she would have wanted.":("아버님이라면 무엇을 원하셨을지 함께 이야기해 봐요.","어머님이라면 무엇을 말하셨을지 함께 이야기해 봐요."),
"You know her best, so what mattered most to her?":("가장 잘 아시니까, 어머님이 가장 좋아하던 게 뭐였을까요?","가장 오래 아시니까, 어머님께 가장 중요했던 게 뭐였을까요?"),
"First, I'm so sorry for what you're facing.":("먼저, 이런 소식을 전하게 되어 정말 죄송합니다.","먼저, 이런 상황에서 기다리게 되어 정말 죄송합니다."),
"When you're ready, a donation specialist will come to talk with you.":("준비되시면 원목 담당자가 와서 이야기해 드릴 거예요.","준비되시면 기증 전문 담당자가 와서 서류를 드릴 거예요."),
"There's no pressure — I'm only connecting you with the donation team.":("압박은 전혀 없어요, 저는 장례 담당 팀과 연결해 드릴 뿐이에요.","압박은 전혀 없어요, 저는 사회복지 팀과 연결해 드릴 뿐이에요."),
"The donation team will also check whether your loved one is a registered donor.":("기증 담당 팀이 소중한 분이 보험에 등록하셨는지도 확인할 거예요.","기증 담당 팀이 소중한 분이 기증자로 등록하셨는지도 설명할 거예요."),
"The donation coordinator will explain everything and answer your questions.":("사회복지사가 모든 걸 설명하고 질문에 답해드릴 거예요.","기증 코디네이터가 모든 걸 설명하고 서류를 받아 갈 거예요."),
"I understand you're angry, and that's okay.":("슬프신 거 이해해요, 그래도 괜찮아요.","놀라신 거 이해해요, 그래도 괜찮아요."),
"I want to hear everything you need to say.":("하고 싶으신 질문 전부 듣고 싶어요.","하고 싶으신 말씀 전부 적고 싶어요."),
"Let's sit down so I can explain what happened.":("앉으셔서 무슨 일이 생길지 제가 설명해 드릴게요.","앉으셔서 무슨 일이 있었는지 의사가 설명해 드릴게요."),
"I hear your anger — you have every right to feel that way.":("슬픈 마음 느껴져요, 그럴 자격이 충분히 있으세요.","화나신 마음 느껴져요, 그럴 시간이 충분히 있으세요."),
"Take your time — I'm listening to all of it.":("천천히 앉으세요, 하나도 빠짐없이 듣고 있어요.","천천히 말씀하세요, 하나도 빠짐없이 적고 있어요."),
"There are no words for this kind of loss.":("이런 상실에는 어떤 시간도 부족해요.","이런 상실에는 어떤 사람도 부족해요."),
"You can hold her for as long as you need.":("필요한 만큼 오래 아이 옷을 안고 계셔도 돼요.","필요한 만큼 오래 아이를 지켜보고 계셔도 돼요."),
"We can make a keepsake if you'd like, when you're ready.":("원하시면, 준비되셨을 때 서류를 만들어 드릴 수 있어요.","원하시면, 내일 아침에 기념물을 만들어 드릴 수 있어요."),
"I am so deeply sorry — I'm right here with you.":("정말 깊이 애도를 표합니다, 제가 바로 옆방에 있을게요.","정말 깊이 애도를 표합니다, 의사 선생님이 바로 곁에 있을게요."),
"Take all the time you need to say goodbye.":("작별 인사할 시간을 십 분만 가지세요.","작별 인사할 사람을 필요한 만큼 부르세요."),
}
W={'w-relationship':(None,['relocation','reputation']),'w-walk':(['차근차근 연습하다','천천히 걸어가다'],None)}
B={"May I ask your relationship to the patient?":('relationship',['introduction','explanation','reputation']),
"Help me understand what's behind this decision.":('understand',['disregard','overlook','dismiss'])}
apply('core-family-er',S,W,B)
