import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"I'm going to call an interpreter to help us talk.":("제가 의사를 불러서 저희가 대화할 수 있게 도와드릴게요.","제가 통역사를 불러서 저희가 진찰할 수 있게 도와드릴게요."),
"It only takes a minute, and it's free for you.":("5분밖에 안 걸리고, 무료예요.","1분밖에 안 걸리고, 쉬워요."),
"You'll hear them through this phone, in your language.":("이 전화기를 통해 그분의 목소리를 들으실 거예요, 영어로요.","이 전화기를 통해 그분의 목소리를 들으실 거예요, 천천히요."),
"The interpreter is on the phone, ready to help you.":("통역사가 복도에 대기 중이고, 도와드릴 준비가 됐어요.","의사가 전화에 대기 중이고, 도와드릴 준비가 됐어요."),
"Please don't worry, I'll call the interpreter right now.":("걱정하지 마세요, 지금 바로 간호사를 부를게요.","걱정하지 마세요, 지금 바로 의사를 부를게요."),
"Pain? Point to where.":("가려움? 어디인지 가리켜 주세요.","멍? 어디인지 가리켜 주세요."),
"Any allergy to medicine? Yes or no?":("음식 알레르기 있나요? 예 아니오?","약물 부작용 있나요? 예 아니오?"),
"Show me with your fingers, zero to ten.":("손가락으로 보여주세요, 0에서 5까지요.","눈으로 보여주세요, 0에서 10까지요."),
"Where is the pain? Point with one finger.":("통증이 언제인가요? 손가락 하나로 가리켜 주세요.","통증이 어디인가요? 손가락 두 개로 가리켜 주세요."),
"Do you take medicine every day? Yes or no?":("가끔 드시는 약이 있나요? 예 아니오?","매일 드시는 영양제가 있나요? 예 아니오?"),
"The interpreter will explain the test to you.":("의사가 환자분께 검사를 설명해 드릴 거예요.","통역사가 환자분께 약을 설명해 드릴 거예요."),
"Please tell me back what you understood.":("이해하신 내용을 다시 적어 주세요.","궁금하신 내용을 다시 말씀해 주세요."),
"Do you agree to have this done? Yes or no?":("이 검사를 받는 데 동의하시나요? 예 아니오?","이 처치를 받는 데 동의하셨나요? 예 아니오?"),
"The interpreter will explain each step before we start.":("시작하기 전에 통역사가 각 서류를 설명해 드릴 거예요.","시작하기 전에 간호사가 각 단계를 설명해 드릴 거예요."),
"Please tell me if you don't understand something.":("불편한 부분이 있으면 말씀해 주세요.","이해가 안 되는 부분이 있으면 적어 주세요."),
"Thank you for wanting to help translate.":("설명을 도와주려는 마음, 감사해요.","통역을 도와주려는 마음, 존중해요."),
"For medical details, we use a trained interpreter.":("서류 세부사항은 훈련된 통역사를 이용해요.","의료 세부사항은 전화 통역사를 이용해요."),
"This keeps everything accurate and protects your mom.":("이렇게 하면 빠르게 전달되고 어머니를 보호할 수 있어요.","이렇게 하면 정확하게 전달되고 아버지를 보호할 수 있어요."),
"We always use a trained interpreter for medical talk.":("저희는 행정 대화에는 항상 훈련된 통역사를 이용해요.","저희는 의료 대화에는 보통 훈련된 통역사를 이용해요."),
"Thank you for helping, and please let the interpreter translate.":("도와주셔서 감사하지만, 기록은 통역사가 하게 해 주세요.","도와주셔서 감사하지만, 질문은 통역사가 하게 해 주세요."),
"What language would you like us to use?":("어떤 방법을 사용해 드릴까요?","어떤 자료를 사용해 드릴까요?"),
"Is it easier to read or to listen for you?":("읽는 것과 쓰는 것 중 어느 쪽이 더 편하세요?","보는 것과 듣는 것 중 어느 쪽이 더 편하세요?"),
"We can get materials in your language too.":("환자분 나라 음식도 준비해 드릴 수 있어요.","쉬운 영어로 된 자료도 준비해 드릴 수 있어요."),
"Do you prefer to speak English or your own language?":("영어와 모국어 중 어느 쪽으로 쓰시는 게 좋으세요?","영어와 모국어 중 어느 쪽으로 읽으시는 게 좋으세요?"),
"Tell me which language feels most comfortable to you.":("어떤 방법이 가장 편하게 느껴지시는지 말씀해 주세요.","어떤 언어가 가장 편하게 느껴지시는지 적어 주세요."),
"We'll prepare written materials if you'd like to read.":("듣는 것을 원하시면 문서 자료를 준비해 드릴게요.","보는 것을 원하시면 문서 자료를 준비해 드릴게요."),
"I'm speaking to you, not to the phone.":("저는 보호자께 말씀드리는 거예요, 전화기가 아니라.","저는 환자분께 말씀드리는 거예요, 의사가 아니라."),
"Please look at me, and the interpreter will follow.":("저를 봐 주세요, 의사가 따라갈 거예요.","저를 따라 해 주세요, 통역사가 따라갈 거예요."),
"Tell me in short sentences so nothing is missed.":("짧은 문장으로 적어 주세요, 놓치는 게 없도록요.","천천히 말씀해 주세요, 놓치는 게 없도록요."),
"Keep your sentences short so the interpreter can follow.":("문장을 쉽게 해 주세요, 통역사가 따라갈 수 있게요.","문장을 짧게 해 주세요, 의사가 따라갈 수 있게요."),
"Look at me while you speak, not at the phone.":("말씀하실 때 저를 봐 주세요, 보호자가 아니라.","말씀하신 뒤에 저를 봐 주세요, 전화기가 아니라."),
"I want to make sure we get the right dialect.":("정확한 억양 통역을 확보하고 싶어요.","빠른 방언 통역을 확보하고 싶어요."),
"It may take a little longer to find the interpreter.":("의사를 찾는 데 조금 더 걸릴 수 있어요.","통역사를 찾는 데 하루 더 걸릴 수 있어요."),
"You're doing fine — take your time.":("잘하고 계세요, 크게 하세요.","잘하고 계세요, 가까이 하세요."),
"Please be patient while we find the right dialect for you.":("정확한 번역을 찾는 동안 조금만 기다려 주세요.","정확한 방언을 찾는 동안 조금만 앉아 주세요."),
"You're doing fine, and I'll wait with you.":("잘하고 계세요, 제가 함께 갈게요.","잘하고 계세요, 통역사가 함께 기다릴게요."),
"The interpreter service is looking for someone who speaks your dialect.":("병원에서 환자분 방언을 하는 분을 찾고 있어요.","통역 서비스에서 환자분 방언을 하는 분의 이름을 찾고 있어요."),
"Thank you for your patience, and this helps us get it right.":("기다려 주셔서 감사해요, 그래야 빠르게 할 수 있어요.","도와 주셔서 감사해요, 그래야 정확하게 할 수 있어요."),
"You said a lot — I want to hear all of it.":("말씀을 많이 하셨는데, 전부 다 적고 싶어요.","질문을 많이 하셨는데, 전부 다 듣고 싶어요."),
"Can the interpreter repeat that in full?":("의사가 그걸 전부 다시 말해 줄 수 있나요?","통역사가 그걸 전부 적어 줄 수 있나요?"),
"Let me ask again a different way to be sure.":("확실히 하기 위해 다른 분께 다시 여쭤볼게요.","확실히 하기 위해 다른 방식으로 다시 설명해 드릴게요."),
"Interpreter, please repeat every word the patient said.":("통역사님, 제가 한 말씀을 한 마디도 빠짐없이 다시 말해 주세요.","통역사님, 환자분이 하신 말씀을 한 마디도 빠짐없이 적어 주세요."),
"That felt short, so let's go over it again to be sure.":("짧게 느껴졌으니, 확실히 하기 위해 의사에게 한번 여쭤볼게요.","이상하게 느껴졌으니, 확실히 하기 위해 다시 한번 살펴볼게요."),
"Would you prefer a female nurse for this exam?":("이 진찰은 여성 의사가 하는 걸 선호하세요?","이 진찰은 간호사 한 명이 하는 걸 선호하세요?"),
"I'll keep you covered as much as possible.":("가능한 한 계속 따뜻하게 해 드릴게요.","가능한 한 계속 닦아 드릴게요."),
"Please tell me if anything makes you uncomfortable.":("불편하게 느껴지는 게 있으면 적어 주세요.","궁금하게 느껴지는 게 있으면 말씀해 주세요."),
"I can find a female nurse if you prefer.":("원하시면 남성 간호사를 찾아드릴 수 있어요.","원하시면 여성 통역사를 찾아드릴 수 있어요."),
"We'll keep you covered during the exam.":("진찰 후에도 계속 가려 드릴게요.","처치 중에도 계속 가려 드릴게요."),
"I'll walk you through it out loud, step by step.":("소리 내어 한 단계씩 읽어 드릴게요.","천천히 한 단계씩 설명해 드릴게요."),
"Let me draw a simple picture to show you.":("간단한 글을 써서 보여드릴게요.","간단한 영상을 틀어서 보여드릴게요."),
"There's no rush — tell me if I go too fast.":("서두르지 않아도 돼요, 제가 너무 어려우면 말씀해 주세요.","서두르지 않아도 돼요, 제가 너무 빠르면 손을 들어 주세요."),
"Let's go step by step, and I'll draw it too.":("한 단계씩 해요, 그리고 표도 그려드릴게요.","천천히 해요, 그리고 그림도 그려드릴게요."),
"Take your time — there's no rush to understand this.":("천천히 하세요, 이걸 기억하는 데 서두를 필요 없어요.","천천히 하세요, 이걸 설명하는 데 서두를 필요 없어요."),
"I'm arranging a sign language interpreter now.":("지금 전화 통역사를 준비하고 있어요.","지금 수어 교재를 준비하고 있어요."),
"Face me so you can see my expressions.":("제 표정을 보실 수 있게 불을 켜 주세요.","제 손을 보실 수 있게 저를 향해 주세요."),
"We can also write things down together.":("함께 몸짓으로 소통할 수도 있어요.","함께 글로 써서 연습할 수도 있어요."),
"The interpreter will sign everything I say.":("통역사가 제가 하는 말을 전부 글로 전달해 드릴 거예요.","통역사가 제가 하는 질문을 전부 수어로 전달해 드릴 거예요."),
"Let's write it down together if that's easier.":("그게 더 빠르시면 함께 글로 써 봐요.","그게 더 편하시면 함께 그림으로 그려 봐요."),
"In here, telling me your pain helps us help you.":("여기서는 통증을 말씀해 주시는 게 저희가 가족분을 돕는 데 도움이 돼요.","여기서는 통증을 적어 주시는 게 저희가 환자분을 돕는 데 도움이 돼요."),
"You don't need to be strong for me.":("저를 위해 웃는 척하지 않으셔도 돼요.","가족을 위해 강한 척하지 않으셔도 돼요."),
"I can see you're tensing — is it worse than you're saying?":("땀 흘리시는 게 보이는데, 말씀하신 것보다 더 심한가요?","긴장하시는 게 보이는데, 말씀하신 것보다 더 오래된 건가요?"),
"It's okay to tell me your real pain.":("실제 통증을 의사에게 말씀하셔도 괜찮아요.","실제 걱정을 저에게 말씀하셔도 괜찮아요."),
"I noticed you're tensing, so I think the pain is worse.":("땀 흘리시는 걸 보니, 통증이 더 심한 것 같아요.","긴장하시는 걸 보니, 걱정이 더 큰 것 같아요."),
"Chest? Point here. Yes or no?":("배? 여기를 가리켜 주세요. 예 아니오?","머리? 여기를 가리켜 주세요. 예 아니오?"),
"Squeeze my hand if the pain is very bad.":("통증이 아주 심하면 제 팔을 꽉 쥐어 주세요.","통증이 아주 심하면 제 손을 흔들어 주세요."),
"The interpreter is coming — stay with me.":("의사가 오고 있어요, 저와 함께 계세요.","통역사가 오고 있어요, 저를 보고 계세요."),
"Is the pain in your chest? Point to it.":("통증이 배에 있나요? 그곳을 가리켜 주세요.","통증이 등에 있나요? 그곳을 가리켜 주세요."),
"Squeeze my hand twice if you understand.":("이해하시면 제 손을 한 번 꽉 쥐어 주세요.","이해하시면 제 손을 세 번 꽉 쥐어 주세요."),
"I'm using a translation app — read this.":("사전 앱을 쓰고 있어요, 이걸 읽어 주세요.","번역 앱을 쓰고 있어요, 이걸 써 주세요."),
"Nod yes, shake for no — can you breathe okay?":("예면 눈을 깜박이고, 아니오면 저으세요, 숨은 괜찮으세요?","예면 끄덕이고, 아니오면 흔드세요, 숨은 괜찮으세요?"),
"We are helping you. You are safe.":("저희가 기다리고 있어요. 안전하세요.","저희가 돕고 있어요. 가족도 안전하세요."),
"Read this on the app, then nod if you understand.":("앱에 있는 이걸 읽고, 이해하시면 손을 들어 주세요.","앱에 있는 이걸 듣고, 이해하시면 끄덕여 주세요."),
"Shake your head no if you can't breathe.":("어지러우시면 고개를 저어 주세요.","숨을 못 쉬시면 손을 들어 주세요."),
"The interpreter will help me tell you something serious.":("통역사가 심각한 이야기를 듣는 걸 도와드릴 거예요.","의사가 심각한 이야기를 전하는 걸 도와드릴 거예요."),
"I'm so sorry — his condition is very grave.":("정말 죄송합니다, 검사가 매우 오래 걸려요.","정말 죄송합니다, 회복이 매우 오래 걸려요."),
"Take your time, and ask me anything you need.":("천천히 하시고, 필요한 건 뭐든 적어 보세요.","천천히 하시고, 필요한 건 뭐든 가져가세요."),
"The interpreter will help you understand his condition.":("통역사가 일정을 이해하도록 도와드릴 거예요.","의사가 상태를 이해하도록 도와드릴 거예요."),
"I'm sorry to tell you something so serious.":("이렇게 긴 이야기를 전하게 되어 죄송해요.","이렇게 심각한 이야기를 듣게 되어 죄송해요."),
"Can you tell me back what I just explained?":("제가 방금 설명한 걸 다시 적어 주시겠어요?","제가 방금 질문한 걸 다시 말씀해 주시겠어요?"),
"We'll use the interpreter to check if he truly understands.":("통역사를 통해 정말 동의하시는지 확인할게요.","통역사를 통해 정말 이해하시는지 두 번 확인할게요."),
"If he can't consent, we'll reach his next of kin.":("동의할 수 없으시면, 책임 간호사에게 연락드릴게요.","동의할 수 없으시면, 가장 가까운 가족에게 설명드릴게요."),
"Let me explain it again, and tell me if you understand.":("다시 한번 설명해 드릴 테니, 이해되시면 끄덕여 주세요.","한번 더 읽어 드릴 테니, 이해되시면 말씀해 주세요."),
"We'll check his consent carefully with the interpreter.":("통역사와 함께 동의 서류를 꼼꼼히 확인할게요.","의사와 함께 동의 여부를 꼼꼼히 확인할게요."),
"The interpreter will help me ask some serious questions.":("통역사가 몇 가지 간단한 질문을 하는 걸 도와드릴 거예요.","의사가 몇 가지 중요한 질문을 하는 걸 도와드릴 거예요."),
"Have you thought about hurting yourself?":("다른 사람을 다치게 할 생각을 하신 적 있나요?","스스로를 다치게 할 계획을 세우신 적 있나요?"),
"You're not alone — we're here to keep you safe.":("혼자가 아니에요, 가족이 안전하게 지켜드릴게요.","혼자가 아니에요, 의사가 안전하게 지켜드릴게요."),
"The interpreter will ask if you want to hurt yourself.":("통역사가 누군가를 다치게 하고 싶으신지 여쭤볼 거예요.","통역사가 스스로를 다치게 하셨는지 여쭤볼 거예요."),
"We're here, and you're safe with us.":("저희가 여기 있고, 가족과 함께 안전하세요.","의사가 여기 있고, 저희와 함께 안전하세요."),
"I want to understand your concern, not push you.":("환자분의 걱정을 기록하고 싶은 거예요, 몰아붙이려는 게 아니라.","환자분의 걱정을 이해하고 싶은 거예요, 의심하려는 게 아니라."),
"There may be a misunderstanding I can clear up.":("제가 풀어드릴 수 있는 걱정이 있을 수 있어요.","제가 풀어드릴 수 있는 질문이 있을 수 있어요."),
"The interpreter will make sure I explain it right.":("통역사가 제가 제대로 기록하는지 확인해 드릴 거예요.","의사가 제가 제대로 설명하는지 확인해 드릴 거예요."),
"Let's clear up this misunderstanding together.":("이 오해를 함께 기록해봐요.","이 오해를 따로 풀어봐요."),
"I understand your concern, and I won't push you.":("환자분의 걱정을 기억해요, 그리고 몰아붙이지 않을게요.","환자분의 걱정을 이해해요, 그리고 서두르지 않을게요."),
"He speaks only Somali and needs a video interpreter.":("이 환자분은 소말리어만 하시고 전화 통역이 필요해요.","이 환자분은 소말리어만 하시고 화상 통역이 오래 걸려요."),
"He's declined care before due to a misunderstanding.":("걱정 때문에 전에 치료를 거부하신 적이 있어요.","오해 때문에 전에 약을 거부하신 적이 있어요."),
"Always confirm understanding through the interpreter.":("항상 통역사를 통해 동의했는지 확인해 주세요.","항상 통역사를 통해 연락처를 확인해 주세요."),
"Please confirm he needs a video interpreter, not phone.":("화상 통역이 필요하다는 걸 확인해 주세요, 대면 통역이 아니라.","화상 통역이 준비됐다는 걸 확인해 주세요, 전화 통역이 아니라."),
"He declined care once, so confirm his understanding each time.":("예전에 치료를 거부하신 적이 있으니, 매번 동의했는지 확인해 주세요.","최근에 치료를 거부하신 적이 있으니, 매번 이해했는지 확인해 주세요."),
"Can you tell me in your own words how you'll take this medicine at home?":("집에서 이 약을 언제 드실지 환자분 말로 다시 말씀해 주시겠어요?","집에서 이 약을 어떻게 드실지 환자분 말로 다시 적어 주시겠어요?"),
"I'll go through each step slowly with the interpreter.":("의사와 함께 천천히 한 단계씩 짚어드릴게요.","통역사와 함께 천천히 한 장씩 짚어드릴게요."),
"There are no wrong questions — let's make sure it's clear.":("잘못된 질문은 없어요, 확실히 기록되도록 해봐요.","잘못된 대답은 없어요, 확실히 이해되도록 해봐요."),
"Tell me each step in your own words.":("각 약을 환자분 말로 말씀해 주세요.","각 단계를 환자분 말로 적어 주세요."),
"Ask me anything — there's no wrong question here.":("뭐든 적어 보세요, 여기엔 잘못된 질문이 없어요.","뭐든 물어보세요, 여기엔 어려운 질문이 없어요."),
}
W={'w-listen':(['주의 깊게 읽다','큰 소리로 말하다'],None),'w-misunderstanding':(None,['mispronunciation','misinformation']),
'w-speak':(['(언어를) 번역하다','(언어를) 가르치다'],None),'w-tense':(['(몸이) 떨다·흔들리다','(몸이) 움츠리다·웅크리다'],None)}
B={"Please tell me back what you understood.":('understood',['disliked','misplaced','dismissed']),
"Please tell me if you don't understand something.":('understand',['purchase','approve','exchange']),
"Squeeze my hand twice if you understand.":('understand',['disagree','perspire','swallow']),
"The interpreter will help you understand his condition.":('understand',['conceal','overlook','dismiss']),
"He declined care once, so confirm his understanding each time.":('understanding',['appointment','registration','transportation'])}
apply('core-language-er',S,W,B)
