import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"On a scale of zero to ten, how would you rate your pain right now?":("0점에서 10점 척도로 어제 통증이 몇 점이었나요?","0점에서 5점 척도로 지금 통증이 몇 점인가요?"),
"Can you point to exactly where it hurts?":("정확히 언제부터 아픈지 말씀해 주시겠어요?","정확히 어디가 가려운지 가리켜 주시겠어요?"),
"Is it a sharp, dull, or burning kind of pain?":("날카로운 통증인가요, 둔한 통증인가요, 아니면 욱신거리는 통증인가요?","묵직한 통증인가요, 둔한 통증인가요, 아니면 타는 듯한 통증인가요?"),
"Does anything make the pain worse, like moving or coughing?":("움직이거나 숨 쉴 때처럼 통증이 심해지는 게 있나요?","누워 있거나 기침할 때처럼 통증이 심해지는 게 있나요?"),
"I believe you, and we'll get this pain under control.":("환자분 말씀 믿어요, 이 통증을 꼭 설명해 드릴게요.","환자분 말씀 믿어요, 이 기침을 꼭 조절해 드릴게요."),
"There's no right or wrong number, just tell me what you feel.":("정답은 없어요, 들은 그대로 말씀해 주시면 돼요.","정답은 없어요, 느끼는 그대로 직접 그려 주시면 돼요."),
"I'm going to give you something for the pain now.":("지금 열에 도움이 될 약을 드릴게요.","지금 구역질에 도움이 될 약을 드릴게요."),
"It usually starts working in about ten to fifteen minutes.":("보통 40분에서 50분 정도면 효과가 나타나요.","보통 10분에서 15분 정도면 약이 준비돼요."),
"Let me know if it makes you feel drowsy or dizzy.":("졸리거나 목이 마르면 알려 주세요.","배고프거나 어지러우면 알려 주세요."),
"This is a pain medicine called morphine.":("이건 모르핀이라는 약 설명서예요.","이건 모르핀이라는 약 상자예요."),
"It will help take the edge off the pain.":("부기를 한결 가라앉혀 줄 거예요.","열을 한결 가라앉혀 줄 거예요."),
"If you feel a little drowsy, that's normal, but tell me if it gets hard to stay awake.":("조금 어지러운 건 정상이지만, 깨어 있기 힘들어지면 알려 주세요.","조금 메스꺼운 건 정상이지만, 깨어 있기 힘들어지면 알려 주세요."),
"Let's put a cold pack on it to bring the swelling down.":("부기를 가라앉히게 냉찜질팩을 가져올게요.","부기를 가라앉히게 냉찜질팩을 옆에 둘게요."),
"Try keeping the leg raised on this pillow.":("이 담요 위에 다리를 올려 두세요.","이 의자 위에 다리를 올려 두세요."),
"I can dim the lights if that helps you relax.":("긴장이 풀리시게 소리를 작게 해드릴 수 있어요.","잠이 오시게 조명을 어둡게 해드릴 수 있어요."),
"A warm blanket might feel good on your back.":("발에 따뜻한 담요를 덮으면 편안하실 거예요.","등에 부드러운 담요를 덮으면 편안하실 거예요."),
"These methods can lower your pain without more medicine.":("이런 방법들로 약을 더 쓰지 않고도 부기를 줄일 수 있어요.","이런 방법들로 주사를 더 쓰지 않고도 통증을 줄일 수 있어요."),
"Let's try this first before we add anything else.":("다른 걸 더하기 전에 이걸 먼저 설명할게요.","다른 걸 빼기 전에 이걸 먼저 해볼게요."),
"Are you allergic to any medications that you know of?":("알고 계신 음식 알레르기가 있나요?","알고 계신 약물 부작용이 있나요?"),
"Have you ever taken morphine or codeine before?":("어제 모르핀이나 코데인을 복용하신 적 있나요?","가족분이 예전에 모르핀이나 코데인을 복용하신 적 있나요?"),
"What kind of reaction did you have last time?":("지난번엔 어떤 약을 드셨어요?","지난번엔 어디서 반응이 있으셨어요?"),
"Did you break out in a rash or have trouble breathing?":("구토가 났거나 숨쉬기 힘드셨나요?","열이 났거나 숨쉬기 힘드셨나요?"),
"Have you ever had an allergic reaction to ibuprofen or aspirin?":("이부프로펜이나 아스피린에 위장 장애를 보이신 적 있나요?","이부프로펜이나 아스피린에 알레르기 반응을 보인 가족이 있나요?"),
"I'll note this in your chart so the team knows.":("팀에서 알 수 있게 약사에게 전해 둘게요.","팀에서 알 수 있게 가족에게 말해 둘게요."),
"I'll check back with you in about twenty minutes.":("20분쯤 뒤에 동료가 다시 확인하러 올게요.","20분쯤 뒤에 다시 혈압을 확인하러 올게요."),
"If the pain gets worse before then, press this call button.":("그전에 소변이 마려우면 이 호출 버튼을 눌러 주세요.","그전에 어지러우면 이 호출 버튼을 눌러 주세요."),
"We'll rate it again to see if the medicine helped.":("약이 도움이 됐는지 다시 혈압을 재 볼게요.","약이 필요한지 다시 통증 점수를 매겨볼게요."),
"This helps us know if the medicine is working.":("이렇게 하면 부작용이 있는지 알 수 있어요.","이렇게 하면 약이 얼마나 필요한지 알 수 있어요."),
"Don't wait until it's unbearable, call us right away.":("밤이 될 때까지 기다리지 말고 바로 불러 주세요.","참을 수 없을 때까지 앉아 계시지 말고 바로 불러 주세요."),
"You're not bothering anyone by asking for help.":("음료를 요청하는 건 절대 폐가 아니에요.","도움을 요청하는 건 절대 의사에게 폐가 아니에요."),
"I hear that your pain is real, and I want to help.":("통증이 진짜라는 거 알아요, 설명해 드리고 싶어요.","두통이 진짜라는 거 알아요, 도와드리고 싶어요."),
"Let me tell you what the doctor has ordered for you.":("약사 선생님이 처방하신 걸 말씀드릴게요.","의사 선생님이 말씀하신 걸 전해드릴게요."),
"We can also try other ways to bring the pain down.":("불안을 줄일 다른 방법도 함께 시도해볼 수 있어요.","통증을 알아볼 다른 방법도 함께 시도해볼 수 있어요."),
"I can't give more than what's been ordered, but I'm not giving up on your pain.":("처방된 것보다 더 드릴 순 없지만, 통증을 잊지 않을게요.","처방된 것보다 더 드릴 순 없지만, 통증을 다시 설명드릴게요."),
"Let's talk about what's worked for you before.":("어제 효과가 있었던 방법에 대해 이야기해봐요.","예전에 효과가 있었던 방법을 가족과 이야기해봐요."),
"I'm on your side, and we'll figure this out together.":("저는 환자분 편이에요, 함께 병원을 찾아볼게요.","저는 의사 선생님 편이에요, 함께 방법을 찾아볼게요."),
"How is this pain different from your usual pain?":("이번 통증은 평소 통증과 언제 달라졌나요?","이번 통증은 지난주 통증과 어떻게 다른가요?"),
"Tell me what medicines you already take at home.":("집에서 이미 드시는 음식을 말씀해 주세요.","병원에서 이미 드신 약을 말씀해 주세요."),
"Because of your tolerance, the doctor may adjust the dose.":("내성 때문에 약사 선생님이 용량을 조절하실 수도 있어요.","내성 때문에 의사 선생님이 용량을 확인하실 수도 있어요."),
"Is this new pain sharp, and is it in a different spot?":("이번 통증은 둔한가요? 그리고 다른 부위인가요?","이번 통증은 날카로운가요? 그리고 더 넓은 부위인가요?"),
"Your body may need more medicine than it used to.":("예전보다 몸이 더 많은 시간을 필요로 할 수 있어요.","예전보다 몸이 더 많은 휴식을 필요로 할 수 있어요."),
"We'll watch you closely as we adjust the dose.":("용량을 조절하는 동안 조용히 지켜볼게요.","용량을 조절하는 동안 가족과 함께 지켜볼게요."),
"When did you last eat or drink anything?":("마지막으로 먹거나 마신 곳이 어디인가요?","처음으로 먹거나 마신 게 언제인가요?"),
"We'll keep you on monitors the whole time.":("내내 보호자를 계속 곁에 둘 거예요.","내내 조명을 계속 켜 둘 거예요."),
"You'll feel sleepy, and we'll wake you gently afterward.":("졸리실 거고, 끝나면 부드럽게 안내해 드릴게요.","어지러우실 거고, 끝나면 부드럽게 깨워 드릴게요."),
"This is called procedural sedation.":("이걸 절차적 마취라고 해요.","이걸 응급 진정이라고 해요."),
"Your oxygen and heart rate will be watched the whole time.":("산소포화도와 체온을 계속 지켜볼 거예요.","혈당과 심박수를 계속 지켜볼 거예요."),
"Someone will be with you from start to finish.":("처음부터 끝까지 가족이 함께 있을 거예요.","처음부터 끝까지 누군가 안내해 드릴 거예요."),
"We'll give him a little medicine so he won't feel the stitches.":("주사할 때 아프지 않게 약을 조금 드릴 거예요.","봉합할 때 무섭지 않게 약을 조금 드릴 거예요."),
"You can stay right by his side the whole time.":("내내 간호사 곁에 계셔도 돼요.","잠시 아이 곁에 계셔도 돼요."),
"Do you have any questions before we begin?":("끝나기 전에 궁금하신 점 있으세요?","시작하기 전에 불편하신 점 있으세요?"),
"The medicine will help him stay calm and still.":("이 약이 아이를 졸리고 가만히 있게 도와줄 거예요.","이 약이 아이를 차분하고 편안히 있게 도와줄 거예요."),
"It's normal to feel nervous, and I'll explain each step.":("화나는 건 정상이에요, 단계마다 설명해 드릴게요.","긴장되는 건 정상이에요, 단계마다 보여 드릴게요."),
"He'll wake up soon after we finish.":("시작하면 곧 아이가 깨어날 거예요.","끝나면 곧 아이가 졸릴 거예요."),
"It's okay to tell me if it really hurts.":("정말 아프면 가족한테 말씀하셔도 괜찮아요.","정말 가려우면 저한테 말씀하셔도 괜찮아요."),
"I notice you're guarding that side — can you show me?":("그쪽을 만지고 계신 게 보이는데, 보여주시겠어요?","손을 감싸고 계신 게 보이는데, 보여주시겠어요?"),
"There's no need to tough it out with me.":("저한테는 억지로 웃으실 필요 없어요.","저한테는 억지로 서 계실 필요 없어요."),
"Everyone shows pain in a different way, and that's okay.":("사람마다 통증을 표현하는 시간이 다르고, 그건 괜찮아요.","사람마다 통증을 참는 시간이 다르고, 그건 괜찮아요."),
"You don't have to be brave for me.":("저한테 미안한 척 안 하셔도 돼요.","가족한테 용감한 척 안 하셔도 돼요."),
"Let's make sure we're not missing anything.":("혹시 새로 생긴 게 없는지 확인해봐요.","혹시 놓친 약이 없는지 확인해봐요."),
"Can you tell me what worries you about the medicine?":("약에 대해 어떤 게 궁금하신지 말씀해 주시겠어요?","수술에 대해 어떤 게 걱정되시는지 말씀해 주시겠어요?"),
"I respect your choice — let's talk about other options.":("환자분의 선택을 존중해요, 다른 병원도 이야기해봐요.","가족의 선택을 존중해요, 다른 선택지도 이야기해봐요."),
"We can start with something milder if you prefer.":("의사가 원하시면 더 순한 걸로 먼저 시작할 수 있어요.","원하시면 더 순한 걸로 먼저 설명할 수 있어요."),
"Some patients worry about feeling too sleepy or losing control.":("너무 졸리거나 토할까봐 걱정하는 환자분들도 계세요.","너무 졸리거나 정신을 놓을까봐 걱정하는 가족분들도 계세요."),
"We can try a non-opioid option instead.":("먼저 비마약성 진통제를 시도해볼 수 있어요.","대신 비마약성 진통제를 의사께 물어볼 수 있어요."),
"It's your choice, and I'll support whatever you decide.":("가족분의 선택이니, 무엇을 결정하시든 지지해드릴게요.","환자분의 선택이니, 언제 결정하시든 지지해드릴게요."),
"Can you list the medicines you took today?":("어제 드신 약들을 나열해 주시겠어요?","오늘 드신 음식들을 나열해 주시겠어요?"),
"Some of these can make you very sleepy together.":("이 약들이 함께면 많이 가렵게 만들 수 있어요.","이 약들이 함께면 많이 배고프게 만들 수 있어요."),
"We'll choose something safe with what you already take.":("이미 드시는 약과 안전하게 맞는 걸 설명드릴게요.","이미 드시는 음식과 안전하게 맞는 걸 골라드릴게요."),
"Mixing sedatives and pain medicine can slow your breathing.":("진정제와 진통제를 섞으면 호흡이 느려지는지 볼게요.","진정제와 진통제를 섞기 전에 호흡을 먼저 볼게요."),
"This combination could make you too drowsy to stay safe.":("이 조합은 너무 가렵게 만들어 안전하지 않을 수 있어요.","이 조합은 너무 목마르게 만들어 안전하지 않을 수 있어요."),
"I'll pick a dose that won't add to that risk.":("그 위험을 더하지 않을 시간으로 골라드릴게요.","그 위험을 더하지 않을 병실로 골라드릴게요."),
"Let me get an interpreter so we understand each other.":("서로 잘 이해할 수 있게 보호자를 불러올게요.","서로 잘 이해할 수 있게 의사 선생님을 불러올게요."),
"Point to the face that matches your pain.":("통증과 맞는 얼굴을 말해 주세요.","통증과 맞는 얼굴을 따라해 주세요."),
"Show me with your hand where it hurts.":("발로 아픈 곳을 보여주세요.","손으로 가려운 곳을 보여주세요."),
"This face means no pain, and this one means the worst pain.":("이 얼굴은 통증 없음, 이 얼굴은 가장 오래된 통증을 뜻해요.","이 얼굴은 불안 없음, 이 얼굴은 가장 심한 불안을 뜻해요."),
"Squeeze my hand if you can't speak right now.":("지금 걷기 힘드시면 제 손을 꽉 쥐어 주세요.","지금 말씀하기 힘드시면 제 팔을 꽉 쥐어 주세요."),
"I'm watching your breathing and your expression too.":("호흡이랑 자세도 함께 지켜보고 있어요.","맥박이랑 표정도 함께 지켜보고 있어요."),
"Can you tell me your name and where you are?":("성함이랑 지금 날짜를 말씀해 주시겠어요?","나이랑 지금 계신 곳을 말씀해 주시겠어요?"),
"Take a nice deep breath for me.":("저를 위해 천천히 숨을 한번 쉬어 주세요.","저를 위해 깊게 기침을 한번 해 주세요."),
"You did great — the procedure is all done.":("정말 잘하셨어요, 검사가 다 끝났어요.","정말 힘드셨어요, 시술이 다 끝났어요."),
"Do you know what day it is?":("오늘이 몇 월인지 아세요?","어제가 무슨 요일인지 아세요?"),
"Your breathing looks much better now.":("맥박이 훨씬 좋아지셨네요.","표정이 훨씬 좋아지셨네요."),
"You're safe, and everything went well.":("안전하세요, 다 끝났어요.","조용해요, 다 잘 됐어요."),
"I need you to breathe deeply for me right now.":("지금 저를 위해 천천히 숨을 쉬어 주세요.","지금 저를 위해 깊게 기침을 해 주세요."),
"Open your eyes — squeeze my hand.":("입을 열어 보세요, 제 손을 꽉 쥐어 보세요.","눈을 떠 보세요, 제 팔을 꽉 쥐어 보세요."),
"We're giving you extra oxygen to help you breathe.":("잠자기 편하게 산소를 더 드리고 있어요.","눈뜨기 편하게 산소를 더 드리고 있어요."),
"Your oxygen level is dropping, so I'm calling for help.":("체온이 떨어지고 있어서 도움을 부르고 있어요.","산소포화도가 떨어지고 있어서 가족을 부르고 있어요."),
"I'm going to open your airway now.":("지금 조명을 켜 드릴게요.","지금 가족을 불러 드릴게요."),
"Stay with me and keep your eyes open.":("저와 함께 있어요, 손을 계속 잡고 계세요.","저와 함께 있어요, 팔을 계속 들고 계세요."),
"You stopped breathing well, so we gave you a reversal medicine.":("호흡이 잘 안 되셔서 의사가 역전제를 드렸어요.","호흡이 잘 안 되셔서 역전제를 설명드렸어요."),
"Do you know what you took today?":("어제 뭘 드셨는지 아세요?","오늘 누가 드렸는지 아세요?"),
"You may feel sick or shaky — that will pass.":("속이 안 좋거나 가려울 수 있는데, 곧 지나갈 거예요.","머리가 아프거나 떨릴 수 있는데, 곧 지나갈 거예요."),
"The reversal medicine works fast, but it wears off sooner than the opioid.":("역전제는 천천히 듣지만 마약성 진통제보다 먼저 효과가 사라져요.","역전제는 빨리 놓지만 마약성 진통제보다 먼저 효과가 사라져요."),
"Your pain may come back now that the opioid is blocked.":("마약성 진통제가 차단된 상태라 가려움이 다시 올 수 있어요.","마약성 진통제가 차단된 상태라 두통이 다시 올 수 있어요."),
"We'll stay close and watch you for a few hours.":("몇 시간 동안 가까이서 도와드릴게요.","며칠 동안 가까이서 지켜볼게요."),
"I can see this pain is unbearable, and I believe you.":("이 통증이 참기 힘드시다는 걸 알아요, 기억해요.","이 두통이 참기 힘드시다는 걸 알아요, 믿어요."),
"We're calling the doctor to try a different approach.":("다른 방법을 시도해보게 간호팀장을 부를게요.","다른 방법을 시도해보게 통역사를 부를게요."),
"Stay with me — we'll get on top of this together.":("저와 함께 있어요, 이걸 함께 지켜볼 거예요.","저와 함께 있어요, 이걸 가족과 함께 이겨낼 거예요."),
"I know you've tried everything and nothing has worked yet.":("다 드셔보셨는데 아직 효과가 없었다는 거 알아요.","다 시도해보셨는데 아직 연락이 없었다는 거 알아요."),
"We won't stop until we find something that helps.":("필요한 걸 찾을 때까지 멈추지 않을게요.","도움이 될 사람을 찾을 때까지 멈추지 않을게요."),
"You're not alone in this — I'm right here.":("혼자가 아니에요, 가족이 바로 여기 있어요.","혼자가 아니에요, 제가 바로 옆방에 있어요."),
"You're having an allergic reaction to the medicine.":("음식에 알레르기 반응이 일어나고 있어요.","벌레에 알레르기 반응이 일어나고 있어요."),
"We're giving you epinephrine to help you breathe.":("잠자기 편하게 에피네프린을 드리고 있어요.","움직이기 편하게 에피네프린을 드리고 있어요."),
"Try to stay calm — we're right here with you.":("조용히 있어 보세요, 저희가 바로 곁에 있어요.","차분히 있어 보세요, 가족이 바로 곁에 있어요."),
"Your throat feels tight because of the reaction.":("반응 때문에 목이 마른 느낌이 드는 거예요.","반응 때문에 배가 조이는 느낌이 드는 거예요."),
"The epinephrine will open your airway quickly.":("에피네프린이 기침을 빠르게 멈춰줄 거예요.","에피네프린이 기도를 천천히 열어줄 거예요."),
"We're not leaving your side until you're stable.":("의사가 올 때까지 곁을 떠나지 않을게요.","아침이 될 때까지 곁을 떠나지 않을게요."),
"Our focus now is her comfort, not more tests.":("지금 중요한 건 검사가 아니라 식사예요.","지금 중요한 건 수술이 아니라 편안함이에요."),
"This medicine will ease her pain and let her rest.":("이 약이 기침을 덜어주고 편히 쉬게 해줄 거예요.","이 약이 통증을 덜어주고 편히 앉게 해줄 거예요."),
"Let's talk about what matters most to your family.":("친구분들께 가장 중요한 게 뭔지 이야기해봐요.","가족분들께 가장 불편한 게 뭔지 이야기해봐요."),
"We're not trying to cure her anymore, our focus is on her comfort.":("이제 치료보다 식사에 집중하고 있어요.","이제 검사보다 편안함에 집중하고 있어요."),
"We want her peaceful and free of pain.":("구토 없이 평온하시길 바라요.","통증 없이 건강하시길 바라요."),
"What would she want us to do for her now?":("어제 환자분이 뭘 원하셨던 것 같으세요?","지금 환자분이 뭘 드시고 싶어하실 것 같으세요?"),
"You're in the emergency room — you're safe here.":("병실에 계세요, 여기서는 안전해요.","응급실에 계세요, 여기서는 조용해요."),
"Let's keep your hands still so you don't hurt yourself.":("넘어지지 않게 손을 가만히 두어요.","다치지 않게 발을 가만히 두어요."),
"I'm your nurse, and I'm staying right here.":("저는 담당 의사예요, 바로 여기 있을게요.","저는 담당 간호사예요, 바로 밖에 있을게요."),
"You're waking up from sedation, and some confusion is normal.":("진정에서 깨어나는 중이라 약간 배고픈 건 정상이에요.","수술에서 깨어나는 중이라 약간 혼란스러운 건 정상이에요."),
"It's Tuesday, and you're at City Hospital.":("오늘은 목요일이고, 시티 병원에 계세요.","오늘은 화요일이고, 센트럴 병원에 계세요."),
"I need you to stay in the bed for your own safety.":("편안함을 위해 침대에 계셔야 해요.","안전을 위해 병실에 계셔야 해요."),
"We're giving you something for the pain, in small amounts.":("구역질 때문에 조금씩 나눠서 약을 드리고 있어요.","통증 때문에 조금씩 나눠서 약을 가져오고 있어요."),
"Stay with me and keep looking at my eyes.":("저와 함께 있어요, 제 손을 계속 봐 주세요.","저와 함께 있어요, 모니터를 계속 봐 주세요."),
"We're watching your blood pressure very closely.":("맥박을 아주 면밀히 지켜보고 있어요.","혈압을 아주 천천히 지켜보고 있어요."),
"Too much medicine right now could drop your blood pressure further.":("지금 약을 너무 많이 쓰면 혈당이 더 떨어질 수 있어요.","지금 약을 너무 많이 쓰면 체온이 더 떨어질 수 있어요."),
"We'll give small doses and watch how your body responds.":("소량씩 드리면서 몸이 어떻게 반응하는지 설명할게요.","소량씩 드리면서 가족이 어떻게 반응하는지 지켜볼게요."),
"Keep talking to me, I'm not going anywhere.":("계속 가족한테 말씀하세요, 어디 안 가요.","계속 저한테 말씀하세요, 아무도 안 가요."),
}
S.update({
"Can you point to exactly where it hurts?":("정확히 언제 다쳤는지 말씀해 주시겠어요?","정확히 어디가 가려운지 가리켜 주시겠어요?"),
"If you feel a little drowsy, that's normal, but tell me if it gets hard to stay awake.":("조금 추운 건 정상이지만, 깨어 있기 힘들어지면 알려 주세요.","조금 메스꺼운 건 정상이지만, 깨어 있기 힘들어지면 알려 주세요."),
"Let's put a cold pack on it to bring the swelling down.":("부기를 가라앉히게 냉찜질팩을 옮길게요.","부기를 가라앉히게 냉찜질팩을 옆에 둘게요."),
"I'll check back with you in about twenty minutes.":("20분쯤 뒤에 동료가 다시 올게요.","20분쯤 뒤에 다시 혈압을 확인하러 올게요."),
"This helps us know if the medicine is working.":("이렇게 하면 졸린지 알 수 있어요.","이렇게 하면 약이 얼마나 필요한지 알 수 있어요."),
"Your body may need more medicine than it used to.":("예전보다 몸이 더 많은 잠을 필요로 할 수 있어요.","예전보다 몸이 더 많은 휴식을 필요로 할 수 있어요."),
"You'll feel sleepy, and we'll wake you gently afterward.":("졸리실 거고, 끝나면 부드럽게 모셔 드릴게요.","어지러우실 거고, 끝나면 부드럽게 깨워 드릴게요."),
"It's okay to tell me if it really hurts.":("정말 아프면 가족한테 말씀하셔도 괜찮아요.","정말 추우면 저한테 말씀하셔도 괜찮아요."),
"Let's make sure we're not missing anything.":("혹시 놓친 약 없는지 확인해봐요.","혹시 새로 생긴 게 없는지 확인해봐요."),
"You stopped breathing well, so we gave you a reversal medicine.":("호흡이 잘 안 되셔서 의사가 역전제를 드렸어요.","호흡이 잘 안 되셔서 역전제를 챙겼어요."),
"You may feel sick or shaky — that will pass.":("속이 안 좋거나 추울 수 있는데, 곧 지나갈 거예요.","머리가 아프거나 떨릴 수 있는데, 곧 지나갈 거예요."),
"You're not alone in this — I'm right here.":("혼자가 아니에요, 가족이 바로 여기 있어요.","혼자가 아니에요, 제가 바로 밖에 있어요."),
"We're not leaving your side until you're stable.":("의사가 올 때까지 곁을 떠나지 않을게요.","아침까지 곁을 떠나지 않을게요."),
"What would she want us to do for her now?":("어제 환자분이 뭘 원했을 것 같으세요?","지금 환자분이 뭘 드시고 싶어하실 것 같으세요?"),
"We're giving you something for the pain, in small amounts.":("열 때문에 조금씩 나눠서 약을 드리고 있어요.","통증 때문에 조금씩 나눠서 약을 가져오고 있어요."),
"Keep talking to me, I'm not going anywhere.":("계속 가족한테 말씀하세요, 어디 안 가요.","계속 저한테 속삭이세요, 어디 안 가요."),
"Do you know what day it is?":("오늘이 몇 월인지 아세요?","내일이 무슨 요일인지 아세요?"),
})
W={'w-allergic':(['감염이 있는','내성이 있는'],None),'w-ibuprofen':(None,['naproxen','ketorolac']),'w-oxygen':(None,['nitrogen','hydrogen']),
'w-heart_rate':(None,['heart rhythm','heart sound']),'w-guard':(['자세를 바꾸다','손으로 누르다'],None),'w-wear_off':(['효과가 커지다','효과가 나타나다'],None)}
B={"Have you ever had an allergic reaction to ibuprofen or aspirin?":('had',['noticed','seen','reported']),"Are you allergic to any medications that you know of?":('allergic',['attached','related','similar'])}
apply('er-pain-sedation',S,W,B)
