import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_five import go
S = {
"Let me check your temperature, heart rate, and breathing together.": ["체온과 심박수, 호흡을 따로 확인할게요.", "체온과 심박수, 호흡을 함께 보여 드릴게요."],
"A few of these being off can be an early warning sign.": ["몇 가지가 어긋나 있으면 최종 경고 신호일 수 있어요.", "몇 가지가 어긋나 있으면 조기 알레르기 신호일 수 있어요."],
"Do you have any pain, cough, or burning when you urinate?": ["통증이나 기침, 소변볼 때 가려움이 있나요?", "통증이나 기침, 대변볼 때 화끈거림이 있나요?"],
"Your heart rate is a little fast right now.": ["지금 심박수가 조금 불규칙해요.", "지금 호흡수가 조금 빨라요."],
"I'm also checking how fast you're breathing.": ["숨이 얼마나 깊은지도 같이 확인하고 있어요.", "걸음이 얼마나 빠른지도 같이 확인하고 있어요."],
"These vital signs together help me catch a possible infection early.": ["이 활력징후들을 따로 보면 가능한 감염을 조기에 발견할 수 있어요.", "이 활력징후들을 함께 보면 가능한 골절을 조기에 발견할 수 있어요."],
"Fever with a fast heart rate and breathing needs a closer look.": ["열에 빠른 심박수와 기침까지 더해지면 자세히 봐야 해요.", "두통에 빠른 심박수와 호흡까지 더해지면 자세히 봐야 해요."],
"We'll check your blood and look for the source of infection.": ["혈액을 확인하고 감염 시기를 찾아볼게요.", "혈액을 확인하고 감염원을 물어볼게요."],
"Where do you feel most unwell — your chest, belly, or elsewhere?": ["아침, 저녁, 아니면 다른 때 중 언제쯤이 가장 안 좋으세요?", "가슴, 배, 아니면 다른 곳 중 어디가 가장 편하세요?"],
"Your temperature is up and your heart is racing a bit.": ["체온이 올랐고 눈도 조금 빨갛게 보이고 있어요.", "체온이 올랐고 호흡도 조금 빨라졌어요."],
"We're drawing blood to find out what's causing this.": ["이 원인을 찾기 위해 혈액을 운반하고 있어요.", "이 원인을 알리기 위해 혈액을 채취하고 있어요."],
"Tell me if the pain gets worse in your chest or belly.": ["가슴이나 배 통증이 줄어들면 말씀해 주세요.", "가슴이나 배 통증이 심해지면 가족에게 말씀해 주세요."],
"We draw blood cultures before antibiotics to find the exact bug.": ["정확한 균을 찾기 위해 항생제 전에 혈액배양을 보관해요.", "정확한 균을 찾기 위해 항생제 전에 혈액배양을 보여줘요."],
"That helps us pick the best medicine for your infection.": ["그래야 감염에 잘 맞는 침대를 고를 수 있어요.", "그래야 감염에 가장 잘 맞는 시간을 고를 수 있어요."],
"It only delays the antibiotic by a few minutes.": ["검사 결과를 단 몇 분만 늦출 뿐이에요.", "식사를 단 몇 분만 늦출 뿐이에요."],
"We take the cultures first, then start the antibiotic right after.": ["먼저 배양을 채취하고 바로 이어서 항생제를 점검해요.", "먼저 배양을 채취하고 바로 이어서 항생제를 소개해요."],
"The blood culture shows exactly which germ is causing this.": ["혈액배양은 정확히 어떤 약이 원인인지 보여줘요.", "혈액배양은 정확히 언제 균이 생겼는지 보여줘요."],
"Once we know the exact bug, we can choose the right antibiotic.": ["정확한 균을 알면 맞는 병실을 고를 수 있어요.", "정확한 균을 알면 맞는 식단을 고를 수 있어요."],
"These fluids help support your blood pressure and blood flow.": ["이 수액이 혈압과 체온을 지지하는 데 도움이 돼요.", "이 약이 혈압과 혈류를 지지하는 데 도움이 돼요."],
"The cold feeling in your arm is normal and will pass.": ["다리에 느껴지는 차가운 느낌은 정상이고 곧 지나가요.", "팔에 느껴지는 차가운 느낌은 정상이고 내일 지나갈 거예요."],
"We're giving them quickly because your body needs the support.": ["몸이 열이 나서 수액을 빠르게 주고 있어요.", "팔이 지지가 필요해서 수액을 빠르게 주고 있어요."],
"This IV line lets us give fluids straight into your blood.": ["이 정맥로로 수액을 위장에 바로 줄 수 있어요.", "이 정맥로로 수액을 혈액에 천천히 줄 수 있어요."],
"Tell me right away if you feel short of breath.": ["가려우면 바로 말씀해 주세요.", "졸리면 바로 말씀해 주세요."],
"You're safe here, and we'll watch you closely.": ["여기서는 조용하고, 저희가 계속 지켜볼게요.", "여기서는 안전하고, 저희가 계속 도와드릴게요."],
"Your urine output tells us how well your organs are getting blood.": ["소변량을 보면 장기에 약이 얼마나 잘 가는지 알 수 있어요.", "소변량을 보면 장기에 혈액이 얼마나 오래 가는지 알 수 있어요."],
"Measuring it helps us know if the fluids are working.": ["소변량을 재면 수액이 언제 끝나는지 알 수 있어요.", "체온을 재면 수액이 효과가 있는지 알 수 있어요."],
"It's an important sign we watch closely in cases like yours.": ["이런 경우 저희가 계속 지켜보는 오래된 징후예요.", "이런 경우 보호자가 계속 지켜보는 중요한 징후예요."],
"This catheter lets us measure exactly how much urine you make.": ["이 카테터로 수액량을 정확히 측정할 수 있어요.", "이 정맥로로 소변량을 정확히 측정할 수 있어요."],
"We check the amount every hour to watch your kidneys.": ["폐 상태를 보려고 매시간 양을 확인해요.", "신장 상태를 보려고 매시간 색을 확인해요."],
"A good urine output is a sign the fluids are helping your body.": ["소변량이 좋으면 식사가 몸에 도움이 되고 있다는 신호예요.", "소변량이 좋으면 약이 몸에 도움이 되고 있다는 신호예요."],
"We're moving fast — cultures, antibiotics, fluids, and a lactate test.": ["빠르게 설명할게요 — 배양, 항생제, 수액, 그리고 젖산 검사예요.", "모두 함께 진행할게요 — 배양, 항생제, 수액, 그리고 젖산 검사예요."],
"This lactate level tells us how stressed your body is.": ["이 젖산 수치가 몸이 얼마나 피곤한지 알려줘요.", "이 젖산 수치가 몸이 언제 스트레스를 받았는지 알려줘요."],
"We're giving fluids now to support your blood pressure.": ["체온을 지지하려고 지금 수액을 주고 있어요.", "혈압을 지지하려고 지금 담요를 주고 있어요."],
"We have one hour to get all four of these started.": ["이 네 가지를 한 시간 안에 모두 설명해야 해요.", "이 두 가지를 한 시간 안에 모두 시작해야 해요."],
"Each step moves you closer to being stable.": ["한 단계씩 안정된 병실에 가까워지는 거예요.", "한 시간씩 안정된 상태에 가까워지는 거예요."],
"I'll explain each part as we go.": ["진행하면서 각 부분을 보여 드릴게요.", "진행하기 전에 각 부분을 설명해 드릴게요."],
"A high lactate means your tissues aren't getting enough oxygen.": ["젖산이 높다는 건 조직에 영양이 충분치 않다는 뜻이에요.", "칼슘이 높다는 건 조직에 산소가 충분치 않다는 뜻이에요."],
"After fluids, we'll recheck it to see if it's improving.": ["수액 전에 좋아지고 있는지 다시 확인할게요.", "항생제를 준 뒤 좋아지고 있는지 다시 확인할게요."],
"It's one of the main things we track to guide your treatment.": ["식사 방향을 잡기 위해 계속 추적하는 중요한 것 중 하나예요.", "퇴원 방향을 잡기 위해 계속 추적하는 중요한 것 중 하나예요."],
"The higher the number, the more stress your body is under.": ["수치가 높을수록 몸이 받는 피로도 커요.", "나이가 높을수록 몸이 받는 스트레스도 커요."],
"We'll draw it again in a couple hours to check your progress.": ["몇 분 뒤 다시 채취해서 경과를 확인할게요.", "몇 시간 뒤 다시 채취해서 경과를 알려 드릴게요."],
"A dropping lactate is a good sign you're responding to treatment.": ["젖산이 떨어지는 건 치료에 반응하고 있다는 마지막 신호예요.", "젖산이 떨어지는 건 몸이 따뜻해졌다는 좋은 신호예요."],
"In older adults, sepsis can show up as confusion or a low temperature.": ["노인은 패혈증이 혼란이나 발진으로 나타날 수 있어요.", "노인은 골절이 혼란이나 저체온으로 나타날 수 있어요."],
"The fact that he's cold and confused is why we're taking this seriously.": ["몸이 차고 혼란스러워하시는 게 가족이 이걸 심각하게 보는 이유예요.", "몸이 차고 혼란스러워하시는 게 저희가 이걸 처음 보는 이유예요."],
"Has he had any recent infection, catheter, or wound?": ["최근에 감염이나 카테터, 이사가 있었나요?", "어릴 때 감염이나 카테터, 상처가 있었나요?"],
"Older patients don't always run a fever, even with a serious infection.": ["노인은 심각한 감염에도 식욕이 늘 줄지는 않아요.", "간호사는 심각한 감염이 있어도 열이 늘 나지는 않아요."],
"Confusion like this can be an early sign of something serious.": ["이런 졸음은 심각한 상태의 조기 신호일 수 있어요.", "이런 혼란은 심각한 약물의 조기 신호일 수 있어요."],
"Any falls, new medicines, or trouble with his catheter recently?": ["최근에 낙상이나 새 음식, 카테터 문제가 있었나요?", "최근에 낙상이나 새 약, 휠체어 문제가 있었나요?"],
"The flank pain with a urine infection can lead to a serious infection.": ["요로감염과 함께 온 두통은 심각한 감염으로 이어질 수 있어요.", "폐렴과 함께 온 옆구리 통증은 심각한 감염으로 이어질 수 있어요."],
"We'll check if there's a blockage that needs to be drained.": ["막힌 곳이 있어서 수술이 필요한지 확인할게요.", "막힌 곳이 있어서 배액이 필요한지 물어볼게요."],
"We're starting fluids and antibiotics now.": ["지금 수액과 항생제를 점검할게요.", "지금 수액과 항생제를 말씀드릴게요."],
"Your back and side pain with fever points to a kidney infection.": ["등과 옆구리 통증에 열까지 있으면 폐 감염을 가리켜요.", "등과 옆구리 통증에 기침까지 있으면 신장 감염을 가리켜요."],
"If there's a blockage, we may need to drain it to control the infection.": ["막힘이 있으면 감염을 조절하기 위해 수액이 필요할 수 있어요.", "막힘이 있으면 감염을 조절하기 위해 이송이 필요할 수 있어요."],
"Antibiotics and fluids go in right away to fight the infection.": ["감염과 싸우기 위해 항생제와 수액을 바로 준비해요.", "통증과 싸우기 위해 항생제와 수액을 바로 투여해요."],
"Your pneumonia is affecting your whole body, so we're acting fast.": ["폐렴이 온몸에 영향을 주고 있어서 조용히 움직이고 있어요.", "폐렴이 온몸에 영향을 주고 있어서 모두 함께 움직이고 있어요."],
"We're giving oxygen, fluids, and antibiotics right now.": ["지금 산소, 수액, 항생제를 함께 보고 있어요.", "지금 산소, 수액, 항생제를 함께 소개하고 있어요."],
"I'm watching your breathing closely and will support it if needed.": ["맥박을 계속 지켜보고 필요하면 도와드릴게요.", "호흡을 계속 지켜보고 원하시면 도와드릴게요."],
"Your oxygen level is lower than we'd like right now.": ["지금 산소 수치가 원하는 것보다 흔들려요.", "지금 혈압이 원하는 것보다 낮아요."],
"We're treating the infection and helping your lungs at the same time.": ["감염을 치료하면서 신장도 동시에 돕고 있어요.", "감염을 점검하면서 폐도 동시에 돕고 있어요."],
"Tell me right away if breathing gets harder.": ["숨쉬기가 더 편해지면 바로 말씀해 주세요.", "걷기가 더 힘들어지면 바로 말씀해 주세요."],
"After the fluids, I'm rechecking your pressure and how you're breathing.": ["항생제를 준 뒤 혈압과 호흡을 다시 확인하고 있어요.", "수액을 준 뒤 혈압과 호흡을 다시 설명하고 있어요."],
"This tells us if your body needs more fluid or a different support.": ["이걸 보면 몸에 수액이 더 필요한지 다른 침대가 필요한지 알 수 있어요.", "이걸 보면 몸에 수액이 더 필요한지 다른 병실이 필요한지 알 수 있어요."],
"Let me know if you start to feel short of breath.": ["배가 고프기 시작하면 알려 주세요.", "추워지기 시작하면 알려 주세요."],
"Your blood pressure came up a little after that last bag of fluids.": ["마지막 수액 한 팩 뒤로 체온이 조금 올랐어요.", "첫 수액 한 팩 뒤로 혈압이 조금 올랐어요."],
"Too much fluid can make it harder to breathe, so I'm watching closely.": ["수액이 너무 많으면 먹기가 힘들어질 수 있어서 계속 지켜보고 있어요.", "약이 너무 많으면 숨쉬기가 힘들어질 수 있어서 계속 지켜보고 있어요."],
"Swelling in your legs or feeling more short of breath can mean too much fluid.": ["다리가 붓거나 열이 더 나면 수액이 과할 수 있다는 뜻이에요.", "팔이 붓거나 숨이 더 차면 수액이 과할 수 있다는 뜻이에요."],
"On immune-suppressing medicine, even mild symptoms can be serious.": ["진통제를 드시는 중이면 가벼운 증상도 심각할 수 있어요.", "면역억제제를 드시는 중이면 가벼운 약도 심각할 수 있어요."],
"We won't wait for a high fever — we'll check thoroughly now.": ["고열이 날 때까지 기다리지 않고 지금 천천히 확인할게요.", "기침이 날 때까지 기다리지 않고 지금 철저히 확인할게요."],
"We're drawing cultures and watching you closely.": ["배양을 채취하고 계속 기다릴게요.", "배양을 보관하고 계속 지켜볼게요."],
"A slightly faster heart rate might be the only clue you have.": ["조금 빨라진 걸음이 유일한 단서일 수 있어요.", "조금 빨라진 심박수가 유일한 소리일 수 있어요."],
"Because your immune system is suppressed, we act early rather than wait.": ["면역이 억제된 상태라 기다리기보다 조용히 대응해요.", "수면이 부족한 상태라 기다리기보다 일찍 대응해요."],
"Even without a fever, your body may be fighting a serious infection.": ["열이 없어도 몸은 심각한 피로와 싸우고 있을 수 있어요.", "열이 없어도 몸은 심각한 부상과 싸우고 있을 수 있어요."],
"Chills when your line is used can mean the line is infected.": ["라인을 쓸 때마다 두통이 있으면 라인 감염일 수 있어요.", "라인을 쓸 때마다 오한이 있으면 라인 막힘일 수 있어요."],
"We'll draw cultures from the line and from your arm.": ["라인과 팔 양쪽에서 배양을 보관할게요.", "라인과 팔 양쪽에서 배양을 옮길게요."],
"We may need to remove the line to clear the infection.": ["통증을 없애려면 라인을 제거해야 할 수도 있어요.", "감염을 없애려면 라인을 보여드려야 할 수도 있어요."],
"Fever and chills right after dialysis often point to the line.": ["투석 직전 열과 오한이 있으면 라인을 의심해요.", "식사 직후 열과 오한이 있으면 라인을 의심해요."],
"Redness or pain around the line site is also a warning sign.": ["라인 주변 소음이나 통증도 경고 신호예요.", "입 주변 발적이나 통증도 경고 신호예요."],
"Once the line is out, the infection usually starts to clear.": ["라인을 빼면 통증은 보통 가라앉기 시작해요.", "라인을 넣으면 감염은 보통 가라앉기 시작해요."],
"We're treating your infection and watching your baby at the same time.": ["감염을 설명하면서 아기도 동시에 지켜보고 있어요.", "감염을 치료하면서 어머니도 동시에 지켜보고 있어요."],
"We're starting fluids and antibiotics that are safe in pregnancy.": ["임신 중에도 안전한 수액과 항생제를 준비할게요.", "수유 중에도 안전한 수액과 항생제를 시작할게요."],
"We're monitoring your baby's heartbeat continuously.": ["아기의 체중을 계속 감시하고 있어요.", "어머니의 심장박동을 계속 감시하고 있어요."],
"Your fever and fast heart rate need quick treatment for both of you.": ["열과 빠른 심박수 모두 두 분을 위해 빠른 상담이 필요해요.", "열과 빠른 심박수 모두 어머니만을 위해 빠른 치료가 필요해요."],
"Tell me if you feel the baby moving less than usual.": ["본인이 평소보다 덜 움직인다고 느끼면 말씀해 주세요.", "아기가 평소보다 많이 먹는다고 느끼면 말씀해 주세요."],
"The medicines we're giving are chosen to be safe for your baby.": ["저희가 드리는 약들은 아기에게 편하도록 고른 거예요.", "저희가 드리는 음식들은 아기에게 안전하도록 고른 거예요."],
"We believe she has a serious infection.": ["심각한 감염이 있다고 들었어요.", "심각한 부상이 있다고 생각해요."],
"We're giving fluids and antibiotics urgently, and I'll explain each step.": ["수액과 항생제를 긴급하게 드리고 있고, 각 단계를 보여 드릴게요.", "수액과 항생제를 긴급하게 드리고 있고, 각 서류를 설명해 드릴게요."],
"Where does she feel pain, and when did this start?": ["어머니는 어디가 아프시고, 누가 처음 봤나요?", "어머니는 언제 아프시고, 어디서부터 시작됐나요?"],
"Through the interpreter, I'll ask her about any allergies.": ["통역을 통해 식욕이 있는지 여쭤볼게요.", "통역을 통해 보험이 있는지 여쭤볼게요."],
"I'll explain through the interpreter before we start each new step.": ["새 단계를 시작한 뒤에 통역을 통해 설명할게요.", "새 약을 시작하기 전에 통역을 통해 설명할게요."],
"We're moving quickly because her infection is very serious.": ["감염이 매우 심각해서 조용하게 움직이고 있어요.", "응급실이 매우 바빠서 빠르게 움직이고 있어요."],
"Fluid-refractory shock — we need to start norepinephrine now.": ["수액에 반응하지 않는 쇼크입니다 — 지금 노르에피네프린을 보관해야 해요.", "수액에 반응하지 않는 쇼크입니다 — 지금 노르에피네프린을 소개해야 해요."],
"Prepare for central access to run the pressor safely.": ["승압제를 안전하게 쓰려면 중심라인을 정리해 주세요.", "승압제를 안전하게 쓰려면 중심라인을 옮겨 주세요."],
"Septic shock, MAP under sixty-five after two liters — I need the physician at bedside.": ["패혈성 쇼크, 3리터 수액 뒤에도 MAP이 65 미만입니다 — 의사가 침상 곁에 필요해요.", "패혈성 쇼크, 2리터 수액 뒤에도 MAP이 65 미만입니다 — 보호자가 침상 곁에 필요해요."],
"Two liters in and pressure still low — starting the pressor.": ["2리터가 들어갔는데도 혈압이 여전히 낮습니다 — 승압제를 가져올게요.", "2리터가 들어갔는데도 체온이 여전히 낮습니다 — 승압제를 시작할게요."],
"I'll get the central line tray ready while you call the doctor.": ["선생님이 전화하시는 동안 저는 중심라인 트레이를 세어 볼게요.", "선생님이 환자를 보시는 동안 저는 중심라인 트레이를 준비할게요."],
"Pressor's running through the peripheral line until central access is in.": ["중심라인이 들어갈 때까지 말초라인으로 승압제를 준비하고 있어요.", "중심라인이 들어간 뒤에 말초라인으로 승압제를 주고 있어요."],
"The infection is now affecting several of her organs.": ["출혈이 이제 여러 장기에 영향을 주고 있어요.", "감염이 이제 여러 환자에게 영향을 주고 있어요."],
"We're supporting her kidneys, liver, and blood clotting as best we can.": ["신장과 간, 혈액응고를 저희가 할 수 있는 만큼 기다리고 있어요.", "신장과 간, 혈액응고를 저희가 아는 만큼 지지하고 있어요."],
"This is very serious, and the team is doing everything possible.": ["매우 복잡한 상황이고, 저희 팀이 할 수 있는 모든 걸 하고 있어요.", "매우 심각한 상황이고, 보호자님이 할 수 있는 모든 걸 하고 있어요."],
"Her kidney numbers and liver numbers are both getting worse.": ["신장 수치와 간 수치가 둘 다 오늘 처음 나왔어요.", "신장 수치와 폐 수치가 둘 다 나빠지고 있어요."],
"Her blood isn't clotting as well as it should right now.": ["지금 혈액순환이 정상만큼 잘 되지 않고 있어요.", "어제 혈액응고가 정상만큼 잘 되지 않았어요."],
"We'll keep explaining every change as it happens.": ["변화가 있을 때마다 계속 보여 드릴게요.", "변화가 있을 때마다 하루에 한 번 설명해 드릴게요."],
"Your lactate is still climbing, which tells me you need more support.": ["젖산이 계속 오르고 있어서 휴식이 더 필요하다는 뜻이에요.", "열이 계속 오르고 있어서 지지가 더 필요하다는 뜻이에요."],
"The mottling of your skin means your circulation is struggling.": ["피부에 얼룩덜룩한 게 생긴 건 알레르기가 있다는 뜻이에요.", "입술에 얼룩덜룩한 게 생긴 건 순환이 힘겨워하고 있다는 뜻이에요."],
"I'm escalating this now and getting the physician back in immediately.": ["지금 이걸 상급 보고하고 보호자를 곧 다시 부를게요.", "지금 이걸 상급 보고하고 간호사를 즉시 다시 부를게요."],
"Your hands and feet are going cold and blotchy.": ["손발이 차가워지고 저려지고 있어요.", "귀와 코가 차가워지고 얼룩덜룩해지고 있어요."],
"I'm calling the physician back now — this isn't improving.": ["지금 가족을 다시 부를게요 — 좋아지지 않고 있어요.", "지금 의사를 다시 만날게요 — 좋아지지 않고 있어요."],
"A lactate that keeps rising means the fluids alone aren't enough.": ["젖산이 계속 오른다는 건 식사만으로는 부족하다는 뜻이에요.", "열이 계속 오른다는 건 수액만으로는 부족하다는 뜻이에요."],
"Your breathing is tiring out, so we're going to help you with a tube.": ["몸이 지쳐가고 있어서 튜브로 도와드릴 거예요.", "호흡이 지쳐가고 있어서 튜브로 안내해 드릴 거예요."],
"We're preparing everything to keep you safe during this.": ["이 과정 동안 편안하게 모시려고 모든 걸 준비하고 있어요.", "이 과정 전에 안전하게 지키려고 모든 걸 준비하고 있어요."],
"I'll be right here — try to stay calm and breathe with the oxygen.": ["제가 바로 옆에 있을게요 — 차분히 계시고 산소와 함께 눈을 감아 보세요.", "제가 바로 옆에 있을게요 — 천천히 계시고 산소와 함께 숨 쉬어 보세요."],
"You're working very hard to breathe right now.": ["지금 일어나려고 정말 애쓰고 계세요.", "지금 말하려고 정말 애쓰고 계세요."],
"The doctor and team are getting ready to place the tube.": ["의사와 팀이 침대를 옮길 준비를 하고 있어요.", "의사와 가족이 튜브를 넣을 준비를 하고 있어요."],
"Your oxygen level keeps dropping even with the mask on.": ["마스크를 쓰고 있어도 체온이 계속 떨어지고 있어요.", "마스크를 쓰고 있어도 맥박 수치가 계속 떨어지고 있어요."],
"His pressure is collapsing and the rate is dropping — arrest is imminent.": ["혈압이 무너지고 있고 호흡도 떨어지고 있습니다 — 심정지가 임박했어요.", "혈압이 무너지고 있고 맥박도 떨어지고 있습니다 — 이송이 임박했어요."],
"Get the crash cart here and pads on now.": ["크래시카트를 여기로 가져오고 지금 침대를 올려 주세요.", "크래시카트를 여기로 가져오고 지금 문을 닫아 주세요."],
"Keep the pressor running and prepare for compressions if he loses pulse.": ["승압제는 계속 주면서 호흡이 빨라지면 압박 준비를 해 주세요.", "승압제는 계속 주면서 보호자가 오면 압박 준비를 해 주세요."],
"Pulse is thready and pressure keeps dropping fast.": ["맥박이 약하고 체온이 빠르게 계속 떨어지고 있어요.", "호흡이 약하고 혈압이 빠르게 계속 떨어지고 있어요."],
"Call the code now and bring the defibrillator to bedside.": ["지금 가족을 부르고 제세동기를 침상으로 가져와 주세요.", "지금 코드를 부르고 제세동기 배터리를 침상으로 가져와 주세요."],
"Stay on the pressor and watch the monitor closely for arrest.": ["승압제는 유지하면서 심정지 징후를 모니터로 계속 불러 주세요.", "승압제는 유지하면서 심정지 징후를 체크리스트로 계속 지켜봐 주세요."],
"Septic shock, source is a urinary infection, bundle completed within the hour.": ["패혈성 쇼크, 원인은 폐렴이고, 번들은 한 시간 안에 완료했습니다.", "패혈성 쇼크, 원인은 요로감염이고, 번들은 한 시간 안에 시작했습니다."],
"He's on norepinephrine at eight, MAP holding at sixty-six.": ["노르에피네프린 8로 투여 중이고, MAP은 56으로 유지되고 있습니다.", "노르에피네프린 8로 투여 중이고, 심박수는 66으로 유지되고 있습니다."],
"Last lactate was four, down from six after resuscitation.": ["마지막 젖산은 4로, 소생 후 8에서 내려왔습니다.", "첫 젖산은 4로, 소생 후 6에서 내려왔습니다."],
"Cultures drawn, antibiotics given, fluids started — all within the hour.": ["배양 채취, 항생제 투여, 수액 시작까지 모두 두 시간 안에 했습니다.", "배양 채취, 항생제 투여, 수액 시작까지 모두 어젯밤에 했습니다."],
"Pressure's stable on the current pressor dose, no changes in the last hour.": ["현재 승압제 용량에서 혈압은 안정적이고, 지난 하루 변화는 없습니다.", "현재 승압제 용량에서 맥박은 안정적이고, 지난 한 시간 변화는 없습니다."],
"He's alert, urine output is improving, ready for report to ICU.": ["의식은 또렷하고 소변량도 좋아지고 있어 병동 인계 준비가 됐습니다.", "의식은 또렷하고 식욕도 좋아지고 있어 ICU 인계 준비가 됐습니다."],
}
W = {
"w-temperature": {"en": ["temptation", "pressure"]},
"w-few": {"en": ["fee", "many"]},
"w-off": {"ko": ["정상 범위에 있는", "정상 수치를 유지한"]},
"w-get": {"ko": ["(그 상태를) 유지하다", "(그 상태가) 멈추다"]},
"w-stress": {"ko": ["휴식을 주다", "회복시키다"]},
"w-oxygen": {"en": ["nitrogen", "hydrogen"]},
"w-adult": {"en": ["infant", "elder"]},
"w-run": {"ko": ["(약물을) 중단하다", "(약물을) 섞다"]},
"w-mottle": {"ko": ["(피부의) 창백함", "(피부의) 발진"]},
"w-arrest": {"en": ["arrival", "attest"]},
"w-crash": {"ko": ["(crash cart의) 일반", "(crash cart의) 예비"]},
}
B = {
"Let me check your temperature, heart rate, and breathing together.": ["appetite", "insurance", "appearance"],
"It only delays the antibiotic by a few minutes.": ["breakfast", "discharge", "transport"],
}
if __name__ == "__main__":
    go("er-sepsis", S, W, B)
