import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_lib_5 import run
P = os.path.join(os.path.dirname(os.path.abspath(__file__)), "base-er-obgyn.yaml")
S = {
# 임신 초기 출혈 문진
"How many weeks along are you, and how much bleeding is there?": ["임신 몇 번째이고, 출혈은 얼마나 있으신가요?", "임신 몇 주째이고, 통증은 얼마나 있으신가요?"],
"Are you having any pain or cramping with it?": ["통증이나 가려운 느낌이 있으신가요?", "열이나 쥐어짜는 듯한 느낌이 있으신가요?"],
"We're going to check on you and the baby right away.": ["당신과 가족분을 바로 확인할게요.", "당신과 아기를 바로 안내할게요."],
"Can you tell me when the bleeding started?": ["출혈이 어디서 시작됐는지 말씀해 주시겠어요?", "통증이 언제 시작됐는지 말씀해 주시겠어요?"],
"Is it more like spotting, or heavier than your period?": ["소량의 반점성 출혈에 가까운가요, 아니면 생리보다 통증이 심한가요?", "소량의 반점성 출혈에 가까운가요, 아니면 어제보다 양이 많은가요?"],
"I know this is frightening, but we're here with you.": ["피곤하게 느껴지실 텐데, 저희가 곁에 있어요.", "무섭게 느껴지실 텐데, 저희가 기다릴게요."],
"Try to stay calm, and we're taking good care of both of you.": ["차분히 계세요, 두 분 모두 곧 검사해 드릴게요.", "차분히 계세요, 가족분도 잘 돌봐드릴게요."],
# 마지막 월경일 청취
"When was the first day of your last period, even roughly?": ["마지막 생리 마지막 날이 언제였는지, 대략이라도 알려주시겠어요?", "마지막 진료 첫날이 언제였는지, 대략이라도 알려주시겠어요?"],
"Is there any chance you could be pregnant?": ["혹시 감염되셨을 가능성이 있나요?", "혹시 다치셨을 가능성이 있나요?"],
"It's okay if you're not sure — we can test.": ["확실하지 않으셔도 괜찮아요 — 달력을 보면 돼요.", "확실하지 않으셔도 괜찮아요 — 가족에게 물어보면 돼요."],
"Do you remember it well enough to give me a rough estimate?": ["대략적인 증상이라도 기억나시는 만큼 알려주시겠어요?", "대략적인 시기라도 기억나시는 대로 확인해 주시겠어요?"],
"We ask this because it helps us figure out how far along you are.": ["임신이 얼마나 위험한지 파악하는 데 도움이 되어서 여쭤보는 거예요.", "임신이 얼마나 진행되었는지 가족에게 알리는 데 도움이 되어서 여쭤보는 거예요."],
"Even an estimate is helpful, so don't worry about being exact.": ["대략적인 것도 도움이 되니, 서두르지 않아도 괜찮아요.", "대략적인 것도 기록이 되니, 정확하지 않아도 괜찮아요."],
# 골반통 초기 사정
"Can you point to exactly where it hurts?": ["정확히 어디가 가려운지 가리켜 주시겠어요?", "정확히 어디가 아픈지 써 주시겠어요?"],
"Is the pain sharp, dull, or crampy?": ["통증이 날카로운가요, 둔한가요, 아니면 타는 듯한가요?", "통증이 날카로운가요, 시린가요, 아니면 쥐어짜는 듯한가요?"],
"Have you had any fever, discharge, or nausea?": ["열이나 기침, 메스꺼움이 있으셨나요?", "열이나 분비물, 두통이 있으셨나요?"],
"Does the pain come and go, or is it there all the time?": ["통증이 왔다갔다 하나요, 아니면 점점 심해지나요?", "열이 왔다갔다 하나요, 아니면 계속 있나요?"],
"When did the pain and fever start?": ["통증과 구토가 언제 시작됐나요?", "통증과 열이 얼마나 심한가요?"],
# 임신 확인 검사 안내
"We'll start with a urine test, then confirm with blood if needed.": ["먼저 소변 검사를 하고, 필요하면 초음파로 확인할게요.", "먼저 소변 검사를 하고, 필요하면 의사 선생님께 확인할게요."],
"The blood test tells us more precise information.": ["초음파는 더 정밀한 정보를 알려줘요.", "혈액 검사는 더 빠른 정보를 알려줘요."],
"However you're feeling about this, we're here to support you.": ["이 일에 대해 어떤 마음이 드시든, 저희가 곁에서 설명해 드릴게요.", "이 일에 대해 어떤 마음이 드시든, 의사 선생님이 곁에서 지지할게요."],
"We'll start with a urine sample, and it usually takes just a few minutes.": ["먼저 소변 검사를 하고, 보통 몇 시간이면 결과가 나와요.", "먼저 혈액 검사를 하고, 보통 몇 분이면 결과가 나와요."],
"If the test is positive, we'll talk through what happens next together.": ["검사 결과가 양성이면, 다음에 어디로 갈지 함께 이야기할게요.", "검사 결과가 양성이면, 다음에 언제 오실지 함께 이야기할게요."],
# 산전 기록 확인
"How many pregnancies and deliveries have you had?": ["임신은 몇 번, 입원은 몇 번 하셨나요?", "임신은 몇 번, 검진은 몇 번 하셨나요?"],
"Tell me about the issues in your last pregnancy.": ["지난 수술 때 있었던 문제에 대해 말씀해 주세요.", "지난 임신 때 있었던 약에 대해 말씀해 주세요."],
"Do you have your prenatal records with you?": ["산후 기록을 가지고 계신가요?", "수술 기록을 가지고 계신가요?"],
"How many times have you been pregnant, and how many babies have you delivered?": ["임신은 몇 번 하셨고, 수술은 몇 번 하셨나요?", "임신은 몇 번 하셨고, 진료는 몇 번 하셨나요?"],
"Were there any complications, like high blood pressure or diabetes?": ["고혈압이나 천식 같은 합병증이 있었나요?", "감기나 당뇨 같은 합병증이 있었나요?"],
"Any of this history helps us take better care of you and the baby now.": ["이런 병력이 지금 당신과 가족을 더 잘 돌보는 데 도움이 돼요.", "이런 병력이 지금 당신과 아기를 더 오래 돌보는 데 도움이 돼요."],
# 자궁외임신 의심
"One-sided pain with dizziness is something we take seriously.": ["한쪽으로만 아프면서 열이 나는 건 저희가 심각하게 받아들이는 증상이에요.", "양쪽으로 아프면서 어지러운 건 저희가 심각하게 받아들이는 증상이에요."],
"We're checking right away to rule out a tubal pregnancy.": ["충수염인지 바로 확인해서 배제할게요.", "자궁외임신인지 바로 확인해서 설명드릴게요."],
"Tell me immediately if the pain or dizziness gets worse.": ["통증이나 졸음이 심해지면 바로 말씀해 주세요.", "통증이나 가려움이 심해지면 바로 말씀해 주세요."],
"We need an ultrasound now to see where the pregnancy is.": ["지금 초음파로 아기 성별을 확인해야 해요.", "지금 소변으로 임신 위치를 확인해야 해요."],
"This can become an emergency fast, so we're moving quickly.": ["이건 빠르게 응급 상황이 될 수 있어서, 저희도 조용히 움직이고 있어요.", "이건 빠르게 감염이 될 수 있어서, 저희도 신속히 움직이고 있어요."],
"If your pain suddenly gets much worse, call for help right away.": ["열이 갑자기 훨씬 심해지면, 바로 도움을 요청하세요.", "구토가 갑자기 훨씬 심해지면, 바로 도움을 요청하세요."],
# 유산 진행 중 소통
"I'm so sorry — this is a painful thing to go through.": ["너무 안타까워요 — 이건 갑작스러운 일이에요.", "너무 걱정돼요 — 이건 견디기 힘든 일이에요."],
"There was nothing you did to cause this.": ["이건 날씨가 추워서 생긴 일이 아니에요.", "이건 의사 선생님이 뭘 잘못해서 생긴 일이 아니에요."],
"I'll stay with you and explain everything gently.": ["제가 곁에서 하나하나 크게 설명해 드릴게요.", "제가 곁에서 하나하나 부드럽게 기록해 드릴게요."],
"I'm worried this may be a miscarriage — the doctor will talk with you about it.": ["감염일 수 있어서 걱정돼요 — 의사 선생님이 그 부분을 자세히 말씀해 주실 거예요.", "유산일 수 있어서 걱정돼요 — 약사 선생님이 그 부분을 자세히 말씀해 주실 거예요."],
"Can you tell me how much tissue or blood you've passed?": ["조직이나 혈액을 언제 배출하셨는지 말씀해 주시겠어요?", "조직이나 소변을 얼마나 배출하셨는지 말씀해 주시겠어요?"],
"There was nothing you could have done to prevent this.": ["이걸 알 방법은 없었어요.", "이걸 되돌릴 방법은 없었어요."],
"I'm staying right here with you.": ["제가 바로 밖에 있어 드릴게요.", "제가 바로 안내해 드릴게요."],
# 임신오조 탈수
"How long have you been unable to keep fluids down?": ["물조차 넘기지 못하고 토하신 게 몇 번이나 되셨나요?", "물조차 넘기지 못하고 주무신 지 얼마나 되셨나요?"],
"We'll give you IV fluids to help you feel better.": ["열이 내리도록 정맥으로 수액을 드릴게요.", "잠이 오도록 정맥으로 수액을 드릴게요."],
"We'll check your electrolytes and keep you and baby safe.": ["체중을 확인하고 산모와 아기 모두 안전하게 지켜드릴게요.", "전해질을 확인하고 산모와 가족 모두 안전하게 지켜드릴게요."],
"Are you vomiting more than a few times every day?": ["하루에 여러 번 기침하고 계신가요?", "하루에 여러 번 설사하고 계신가요?"],
"When was the last time you were able to keep food or water down?": ["마지막으로 음식이나 약을 토하지 않고 넘길 수 있었던 게 언제였나요?", "마지막으로 음식이나 물을 토하지 않고 넘길 수 있었던 곳이 어디였나요?"],
"This IV will replace the fluids and nutrients you've lost.": ["이 수액이 잃어버린 수분과 혈액을 채워드릴 거예요.", "이 수액이 잃어버린 수분과 기운을 채워드릴 거예요."],
# 성폭력 피해자 접수
"You are safe here, and you're in control of what happens next.": ["이곳은 조용하고, 다음에 무엇을 할지는 당신이 결정해요.", "이곳은 안전하고, 다음에 무엇을 할지는 의사 선생님이 결정해요."],
"Everything is your choice — you can stop at any time.": ["모든 건 당신의 선택이에요 — 언제든 물어보실 수 있어요.", "모든 건 당신의 선택이에요 — 언제든 돌아오실 수 있어요."],
"I'm going to go at your pace and explain each step.": ["당신의 일정에 맞춰 한 단계씩 설명해 드릴게요.", "당신의 속도에 맞춰 한 단계씩 확인해 드릴게요."],
"Would you like an exam and evidence collection, or not?": ["검사와 상담을 원하시나요, 아니면 원치 않으시나요?", "검사와 약 처방을 원하시나요, 아니면 원치 않으시나요?"],
"Would you like to report this to the police, or not right now?": ["상담사에게 연락하고 싶으신가요, 아니면 지금은 원치 않으신가요?", "가족에게 연락하고 싶으신가요, 아니면 지금은 원치 않으신가요?"],
"I won't ask what happened unless you want to share it.": ["말씀하고 싶지 않으시면, 누가 그랬는지 묻지 않을게요.", "말씀하고 싶지 않으시면, 언제 있었는지 묻지 않을게요."],
"None of this is your fault.": ["이건 절대 혼자 겪을 일이 아니에요.", "이건 절대 가족의 잘못이 아니에요."],
# 임신 중 복통 감별
"Not all belly pain in pregnancy is from the baby.": ["임신 중 배 통증이 전부 음식 때문은 아니에요.", "임신 중 허리 통증이 전부 아기 때문은 아니에요."],
"Does it hurt more when I press here and let go?": ["여기를 눌렀다가 뗄 때 더 가려우신가요?", "여기를 눌렀다가 뗄 때 더 뜨거우신가요?"],
"We'll figure out the cause safely for both of you.": ["두 분 모두에게 빠르게 원인을 찾아볼게요.", "가족 모두에게 안전하게 원인을 찾아볼게요."],
"Can you show me exactly where the pain moved?": ["열이 어디로 옮겨갔는지 정확히 보여주시겠어요?", "통증이 언제 옮겨갔는지 정확히 보여주시겠어요?"],
"We'll do an ultrasound first, since it's safest for the baby.": ["아기에게 가장 안전하니 먼저 소변검사부터 할게요.", "아기에게 가장 안전하니 먼저 상담부터 할게요."],
"Appendicitis can happen during pregnancy too, so we take it seriously.": ["충수염은 임신 중에도 생길 수 있어서, 저희는 이를 기록해 둬요.", "충치는 임신 중에도 생길 수 있어서, 저희는 이를 중요하게 다뤄요."],
# 산과 병력 언어장벽
"I'm getting an interpreter so we can understand each other.": ["서로 이해할 수 있도록 간호사를 부를게요.", "서로 이해할 수 있도록 약사를 부를게요."],
"Please point or show me where it hurts.": ["아픈 곳을 말하거나 보여주세요.", "아픈 곳을 가리키거나 적어주세요."],
"Take your time — we'll make sure nothing is missed.": ["천천히 하셔도 돼요 — 빠지는 것 없이 기록할게요.", "천천히 하셔도 돼요 — 빠지는 것 없이 읽어드릴게요."],
"I won't ask your family to interpret, so nothing gets lost or confused.": ["가족에게 서류를 맡기지 않을게요, 그래야 내용이 빠지거나 헷갈리지 않아요.", "가족에게 통역을 맡기지 않을게요, 그래야 내용이 빨라지고 편해져요."],
"Can you tell me about your pregnancies through the interpreter?": ["통역을 통해 이전 수술에 대해 말씀해 주시겠어요?", "통역을 통해 이전 약에 대해 말씀해 주시겠어요?"],
"We'll go slowly, one question at a time, until we understand everything.": ["천천히, 한 번에 한 가지씩, 다 기록할 때까지 여쭤볼게요.", "천천히, 한 번에 두 가지씩, 다 이해할 때까지 여쭤볼게요."],
# 조기 진통 징후
"How far apart are the tightenings coming?": ["통증이 얼마나 자주 오나요?", "구토가 얼마나 자주 오나요?"],
"Did the fluid have any color or odor?": ["양수에 색이나 양이 있었나요?", "소변에 색이나 냄새가 있었나요?"],
"We're going to monitor you and the baby closely.": ["당신과 가족을 세심히 관찰할게요.", "당신과 아기를 세심히 안내할게요."],
"Are the tightenings coming regularly, or do they come and go?": ["출혈이 규칙적으로 오나요, 아니면 왔다갔다 하나요?", "수축이 규칙적으로 오나요, 아니면 점점 약해지나요?"],
"When did you notice the fluid, and how much was there?": ["양수를 어디서 느끼셨고, 양은 얼마나 됐나요?", "양수를 언제 느끼셨고, 색은 어땠나요?"],
"We'll put a monitor on your belly to watch the contractions and the baby's heartbeat.": ["배 위에 모니터를 대서 혈압과 아기 심박을 지켜볼게요.", "배 위에 모니터를 대서 수축과 아기 성별을 지켜볼게요."],
# 부인과 감염·분비물
"There's no need to feel embarrassed — this is very common.": ["창피해하실 필요 없어요 — 아주 오래된 증상이에요.", "창피해하실 필요 없어요 — 아주 다양한 증상이에요."],
"Can you tell me about the discharge and any other symptoms?": ["통증과 다른 증상에 대해 말씀해 주시겠어요?", "출혈과 다른 증상에 대해 말씀해 주시겠어요?"],
"Everything you share stays confidential.": ["말씀하신 내용은 모두 다시 읽어 드릴게요.", "말씀하신 내용은 모두 번역돼요."],
"Have you had any new sexual partners recently?": ["최근에 새로운 약을 드신 적이 있나요?", "최근에 새로운 비누를 쓰신 적이 있나요?"],
"Any burning, itching, or unusual smell along with the discharge?": ["분비물과 함께 화끈거림, 가려움, 이상한 색이 있나요?", "분비물과 함께 화끈거림, 부기, 이상한 냄새가 있나요?"],
"We'll do a swab test to find out exactly what's causing this.": ["정확한 원인을 찾기 위해 혈액 검사를 할게요.", "정확한 원인을 찾기 위해 초음파 검사를 할게요."],
# 피임·응급피임 상담
"There are options, and the sooner we act the better.": ["비용 지원이 있고, 빨리 조치할수록 좋아요.", "병원 예약이 있고, 빨리 조치할수록 좋아요."],
"Let me explain the choices and how each one works.": ["선택지들과 각각 얼마나 드는지 설명해 드릴게요.", "선택지들과 각각 어떻게 구하는지 설명해 드릴게요."],
"This is a judgment-free conversation about what's right for you.": ["이건 당신에게 맞는 것에 대한, 짧은 대화예요.", "이건 당신에게 맞는 것에 대한, 조용한 대화예요."],
"It happened last night — how many hours ago was that?": ["어제 아침에 있었던 일이군요 — 몇 시간 전이었나요?", "어젯밤에 있었던 일이군요 — 몇 번 있었나요?"],
"The sooner you take it, the more effective it is.": ["빨리 복용할수록 효과가 더 오래가요.", "빨리 복용할수록 가격이 더 싸요."],
"Whatever you decide, there's no right or wrong answer here.": ["무엇을 선택하시든, 비밀은 지켜져요.", "무엇을 선택하시든, 다시 바꿀 수 있어요."],
# 임신 후기 대량출혈
"We're moving fast to keep you and your baby safe.": ["당신과 가족 모두를 안전하게 지키기 위해 빠르게 움직일게요.", "당신과 아기 모두를 안전하게 지키기 위해 조용히 움직일게요."],
"Stay with me — the whole team is right here.": ["정신 놓지 마세요 — 가족 전체가 바로 여기 있어요.", "정신 놓지 마세요 — 팀 전체가 곧 올 거예요."],
"I'll tell you what's happening every step of the way.": ["매 순간 지금 무슨 약을 쓰는지 말씀드릴게요.", "매 순간 지금 누가 오는지 말씀드릴게요."],
"Your placenta may be separating early, and that's causing this bleeding.": ["탯줄이 일찍 떨어지고 있는 것 같고, 그래서 출혈이 생기고 있어요.", "태반이 일찍 떨어지고 있는 것 같고, 그래서 통증이 생기고 있어요."],
"We're feeling the tightness in your belly right now.": ["지금 배가 커지는 걸 확인하고 있어요.", "지금 배가 따뜻해지는 걸 확인하고 있어요."],
"We're getting you to the operating room quickly to protect you both.": ["두 분 모두를 편하게 하기 위해 빠르게 수술실로 모실게요.", "두 분 모두를 보호하기 위해 빠르게 담요를 준비할게요."],
# 자간전증·자간증
"Your blood pressure is high, and we're treating it now.": ["혈당이 높아서, 지금 치료하고 있어요.", "열이 높아서, 지금 치료하고 있어요."],
"Tell me right away if your headache gets worse or your vision changes.": ["기침이 심해지거나 시야가 달라지면 바로 말씀해 주세요.", "두통이 심해지거나 입맛이 달라지면 바로 말씀해 주세요."],
"We're keeping the room calm and quiet to protect you.": ["당신을 보호하기 위해 방을 차분하고 따뜻하게 유지할게요.", "당신을 보호하기 위해 방을 청결하고 조용하게 유지할게요."],
"Have you noticed any swelling in your hands or face?": ["손이나 얼굴이 가려운 걸 느끼셨나요?", "손이나 얼굴이 떨리는 걸 느끼셨나요?"],
"Are you seeing spots, or having trouble seeing clearly?": ["눈앞에 반점이 보이거나, 귀가 먹먹하신가요?", "눈앞에 반점이 보이거나, 숨이 차신가요?"],
"We're giving you medication now to help prevent a seizure.": ["경련을 예방하기 위해 지금 약을 설명드릴게요.", "경련을 예방하기 위해 지금 방을 어둡게 할게요."],
# ER 내 급속 분만
"You're doing great — I'm right here to help you deliver.": ["정말 잘하고 계세요 — 남편분이 바로 옆에서 도와드릴게요.", "정말 힘드시죠 — 제가 바로 옆에서 도와드릴게요."],
"Listen to me and breathe; we'll do this together.": ["제 말을 듣고 눈을 맞추세요; 함께 해낼 거예요.", "제 말을 듣고 숨을 쉬세요; 남편분과 해낼 거예요."],
"We're ready to care for your baby the moment they arrive.": ["아기가 태어나는 순간 바로 안아드릴 준비가 되어 있어요.", "아기가 태어나는 순간 바로 기록할 준비가 되어 있어요."],
"The head is already showing, so I need you to stop pushing for a moment.": ["양수가 이미 보이니, 잠시 힘주기를 멈춰 주세요.", "머리가 이미 보이니, 잠시 눈을 맞춰 주세요."],
"Give me one more big push when the next contraction comes.": ["다음 수축이 올 때 한 번 더 크게 숨쉬세요.", "다음 수축이 올 때까지 한 번 더 크게 쉬세요."],
"The warmer and blankets are ready for your baby as soon as they're born.": ["보온기와 침대가 아기를 위해 준비되어 있어요, 태어나자마자 바로요.", "보온기와 담요가 아기를 위해 준비되어 있어요, 퇴원하자마자 바로요."],
# 자궁외임신 파열 쇼크
"Your pressure is dropping and we're acting fast to stabilize you.": ["체온이 떨어지고 있어서, 안정시키기 위해 빠르게 조치하고 있어요.", "혈압이 떨어지고 있어서, 안정시키기 위해 차분하게 설명하고 있어요."],
"Stay with me — keep your eyes on me.": ["정신 놓지 마세요 — 저를 계속 불러 주세요.", "정신 놓지 마세요 — 숨을 계속 쉬어 주세요."],
"We're getting you to surgery quickly and safely.": ["빠르고 조용하게 수술실로 모실게요.", "빠르고 편안하게 수술실로 모실게요."],
"Your belly is rigid and very tender — that tells us something serious is happening.": ["배가 딱딱하고 아주 뜨거우신데, 이건 심각한 상황이라는 뜻이에요.", "배가 딱딱하고 아주 아프신데, 이건 갑작스러운 상황이라는 뜻이에요."],
"We're giving you fluids and blood to bring your pressure back up.": ["혈압을 다시 올리기 위해 수액과 혈액 이름표를 확인할게요.", "혈압을 다시 올리기 위해 수액과 혈액 기록을 확인할게요."],
"The surgeon is on the way to stop the bleeding inside.": ["출혈을 멈추기 위해 마취과 의사가 오고 있어요.", "출혈을 멈추기 위해 약사가 오고 있어요."],
# 산후 대량출혈
"We're massaging your uterus and giving medication to stop the bleeding.": ["자궁을 마사지하고 통증을 줄이도록 약을 드리고 있어요.", "자궁을 마사지하고 출혈을 멈추도록 약을 확인하고 있어요."],
"Stay with me — we're on top of this.": ["정신 놓지 마세요 — 남편분이 잘 대응하고 있어요.", "정신 놓지 마세요 — 저희가 잘 설명하고 있어요."],
"You're not alone; the whole team is here for you.": ["혼자가 아니에요; 가족 전체가 당신 곁에 있어요.", "혼자가 아니에요; 팀 전체가 아기 곁에 있어요."],
"How much blood have you lost since the delivery?": ["분만 이후 통증이 얼마나 있었나요?", "분만 이후 소변이 얼마나 있었나요?"],
"Your uterus feels soft, so we need to help it contract.": ["자궁이 따뜻하게 느껴져서, 수축하도록 도와드려야 해요.", "자궁이 물렁하게 느껴져서, 출혈량을 재 드려야 해요."],
"We're giving you more blood and fluids to replace what you've lost.": ["잃어버린 만큼 혈액과 수액을 더 확인할게요.", "잃어버린 만큼 혈액과 수액을 더 기록할게요."],
# 태아 사망 고지
"I'm so deeply sorry — we're not able to find the baby's heartbeat.": ["정말 깊이 안타깝습니다 — 아기의 움직임을 찾을 수가 없어요.", "정말 깊이 걱정됩니다 — 아기의 심박을 찾을 수가 없어요."],
"This isn't your fault, and you didn't do anything wrong.": ["이건 당신의 선택이 아니고, 당신은 아무것도 잘못하지 않으셨어요.", "이건 당신의 잘못이 아니고, 가족은 아무것도 잘못하지 않으셨어요."],
"We'll be here with you through whatever comes next.": ["앞으로 무슨 일이 있든 가족분들이 곁에 있을 거예요.", "앞으로 무슨 일이 있든 저희가 바로 연락드릴게요."],
"I need to tell you something difficult about your baby's heartbeat.": ["아기 위치에 대해 어려운 이야기를 드려야 할 것 같아요.", "아기 심박에 대해 긴 이야기를 드려야 할 것 같아요."],
"Your baby has died, and I am so very sorry.": ["아기가 사망했어요. 정말 놀라셨겠어요.", "아기가 사망했어요. 정말 기다리셨죠."],
"There was nothing you could have done to cause this.": ["당신이 한 어떤 일도 이 일의 결과가 아니에요.", "의사가 한 어떤 일도 이 일의 원인이 아니에요."],
"Take all the time you need before we talk about next steps.": ["다음 단계에 대해 이야기 나누기 전에, 필요하신 만큼 질문을 하세요.", "다음 단계에 대해 서명하시기 전에, 필요하신 만큼 시간을 가지세요."],
# 패혈성 유산
"Your symptoms point to an infection we need to treat urgently.": ["증상들이 출혈을 가리켜서, 서둘러 치료해야 해요.", "증상들이 감염을 가리켜서, 서둘러 설명드려야 해요."],
"We're starting antibiotics and fluids right away.": ["지금 바로 항생제와 수액 이름표를 확인할게요.", "지금 바로 항생제와 수액 기록을 시작할게요."],
"You did the right thing coming in — we'll take good care of you.": ["잘 오셨어요 — 저희가 잘 설명해 드릴게요.", "잘 오셨어요 — 가족분들도 잘 돌봐드릴게요."],
"Fever, chills, and heavy discharge after a miscarriage can mean an infection.": ["유산 후 열, 오한, 심한 분비물은 탈수를 의미할 수 있어요.", "유산 후 열, 오한, 심한 피로는 감염을 의미할 수 있어요."],
"How long have you had these symptoms since the miscarriage?": ["유산 이후 이 증상이 얼마나 심하셨나요?", "유산 이후 이 증상이 얼마나 자주 있었나요?"],
"We're also giving you fluids to support your blood pressure.": ["체온을 유지하도록 수액도 함께 드릴게요.", "혈당을 유지하도록 수액도 함께 드릴게요."],
}
W = {
 "w-pain": {"distractorsEn": ["itch", "strain"]},
 "w-spot": {"distractorsKo": ["대량의 쏟아지는 출혈", "소량의 맑은 분비물"]},
 "w-heavy": {"distractorsKo": ["양이 적은", "꾸준한, 일정한"]},
 "w-period": {"distractorsKo": ["배란(주기)", "임신(기간)"]},
 "w-calm": {"distractorsEn": ["cold", "quiet"]},
 "w-care": {"distractorsEn": ["cure", "scare"], "distractorsKo": ["완치, 완치되다", "감시, 감시하다"]},
 "w-last": {"distractorsKo": ["첫 번째의", "다음의, 다가올"]},
 "w-sharp": {"distractorsKo": ["둔한, 묵직한 느낌의", "얕은, 약한 정도의"]},
 "w-crampy": {"distractorsKo": ["찌르는 듯한(양상)", "타는 듯한(양상)"]},
 "w-confirm": {"distractorsKo": ["반박하다(검사로)", "짐작하다(검사로)"]},
 "w-ultrasound": {"distractorsEn": ["ultraviolet", "mammogram"]},
 "w-pass": {"distractorsKo": ["멈추다, 막히다", "채워 넣다, 삽입하다"]},
 "w-electrolyte": {"distractorsEn": ["electrode", "hemoglobin"]},
 "w-pace": {"distractorsKo": ["장소, 진행 장소", "차례, 진행 차례"]},
 "w-share": {"distractorsKo": ["숨기다, 감추다", "서명하다, 날인하다"]},
 "w-apart": {"distractorsKo": ["(시간·간격이) 진행되어", "(시간·간격이) 다가와"]},
 "w-tightening": {"distractorsKo": ["경련성 복통(양상)", "저린 느낌(감각 저하)"]},
 "w-odor": {"distractorsKo": ["(불쾌한) 색깔", "(많은) 분비량"]},
 "w-monitor": {"distractorsKo": ["언급하다, 말하다", "측정하다, 재다"]},
 "w-common": {"distractorsEn": ["complex", "chronic"]},
 "w-confidential": {"distractorsKo": ["자신 있는", "서로 합의한"]},
 "w-seizure": {"distractorsKo": ["실신(기절)", "근육 경직"]},
 "w-push": {"distractorsKo": ["당기다", "쉬다, 멈추다"]},
 "w-warmer": {"distractorsKo": ["인큐베이터", "신생아 담요"]},
 "w-deeply": {"distractorsKo": ["치명적으로", "급히, 서둘러"]},
}
B = {
 "I'm getting an interpreter so we can understand each other.": ["recognize", "interview", "forgive"],
 "I won't ask your family to interpret, so nothing gets lost or confused.": ["volunteer", "supervise", "participate"],
 "This is a judgment-free conversation about what's right for you.": ["complicated", "expensive", "stressful"],
 "Give me one more big push when the next contraction comes.": ["appointment", "medication", "ambulance"],
}
run(P, S, W, B)
