import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_lib_5 import run
P = os.path.join(os.path.dirname(os.path.abspath(__file__)), "base-er-geriatric.yaml")
S = {
# 노인 낙상 후 문진
"Can you tell me what happened right before you fell?": ["넘어지시기 직전에 무슨 말을 들으셨는지 말씀해 주시겠어요?", "넘어지시기 직전에 어디에 계셨는지 말씀해 주시겠어요?"],
"Do you remember feeling dizzy or faint before you fell?": ["넘어지시기 전에 어지럽거나 메스꺼운 느낌이 있으셨나요?", "넘어지신 뒤에 어지럽거나 아찔한 느낌이 있으셨나요?"],
"Did you lose consciousness at any point?": ["잠깐이라도 기억을 잃으신 적이 있나요?", "잠깐이라도 균형을 잃으신 적이 있나요?"],
"Did you trip on something, or did your legs just give out?": ["뭔가에 미끄러져 넘어지신 건가요, 아니면 다리에 힘이 풀리신 건가요?", "뭔가에 걸려 넘어지신 건가요, 아니면 다리에 쥐가 나신 건가요?"],
"Let's go over the medications you take.": ["복용하시는 약들을 함께 옮겨 둘게요.", "복용하시는 약들을 함께 받아 올게요."],
"Have you fallen before in the past year?": ["지난 1년 동안 입원하신 적이 있으신가요?", "지난 1달 동안 넘어지신 적이 있으신가요?"],
"Are you currently taking any blood thinners or sleep medication?": ["현재 혈액 희석제나 진통제를 복용하고 계신가요?", "예전에 혈액 희석제나 수면제를 복용하신 적이 있나요?"],
# 다약제 복용력 정리
"Do you have a list or the bottles with you?": ["약 목록이나 보험증을 가지고 계신가요?", "약 목록이나 퇴원 서류를 가지고 계신가요?"],
"Let's include vitamins and anything you buy over the counter.": ["붕대랑 약국에서 직접 사신 약도 포함해서 말씀해 주세요.", "비타민이랑 인터넷에서 직접 사신 약도 포함해서 말씀해 주세요."],
"Take your time — we'll go one by one.": ["천천히 하셔도 돼요 — 라벨부터 짚어볼게요.", "천천히 하셔도 돼요 — 두 개씩 짚어볼게요."],
"How long have you been taking this one?": ["이 약은 얼마나 자주 복용하고 계셨나요?", "이 약은 얼마나 오래 보관하고 계셨나요?"],
"Is this medication for your blood pressure or something else?": ["이 약은 혈당 때문인가요, 아니면 다른 이유인가요?", "이 약은 콜레스테롤 때문인가요, 아니면 다른 이유인가요?"],
"It's okay if you don't remember every dose, we can call the pharmacy.": ["복용량이 매번 기억 안 나셔도 괜찮아요 — 병원에 전화해서 확인할 수 있어요.", "복용량이 매번 기억 안 나셔도 괜찮아요 — 약국에 가서 확인할 수 있어요."],
# 청력저하 환자 소통
"I'll face you and speak slowly — let me know if this is clearer.": ["제가 마주 보고 크게 말씀드릴게요 — 이게 더 잘 들리시면 말씀해 주세요.", "제가 마주 보고 천천히 말씀드릴게요 — 이게 더 불편하시면 말씀해 주세요."],
"Would it help if I wrote this down for you?": ["그려서 보여드리면 도움이 될까요?", "적어서 읽어드리면 도움이 될까요?"],
"Just raise your hand if you miss something.": ["놓치신 부분이 있으면 그냥 고개를 끄덕여 주세요.", "놓치신 부분이 있으면 그냥 벨을 눌러 주세요."],
"Let me sit where you can see my face clearly.": ["제 이름표가 잘 보이는 자리에 앉을게요.", "제 얼굴이 잘 보이는 자리에 서 있을게요."],
"Does that sound clearer, or should I write it down?": ["이게 더 크게 들리세요, 아니면 적어드릴까요?", "이게 더 잘 들리세요, 아니면 그려드릴까요?"],
"Let's check if your hearing aids are in and working.": ["틀니가 끼워져 있고 제대로 맞는지 확인해볼게요.", "보청기가 끼워져 있고 제대로 충전됐는지 확인해볼게요."],
# 기저 인지기능 확인
"What is she normally like on a good day?": ["평소 컨디션 좋으신 날엔 무엇을 하시나요?", "평소 컨디션 좋으신 날엔 누구와 지내시나요?"],
"When did you first notice this change?": ["이 변화를 누가 처음 알아차리셨나요?", "이 변화를 언제 처음 말씀하셨나요?"],
"Your observations help us a lot — thank you.": ["보호자분의 기록이 저희에게 정말 큰 도움이 돼요 — 감사합니다.", "보호자분의 질문이 저희에게 정말 큰 도움이 돼요 — 감사합니다."],
"Is she usually oriented to time and place?": ["평소에는 이름과 장소를 잘 인지하시는 편인가요?", "평소에는 시간과 사람을 잘 인지하시는 편인가요?"],
"Does she usually know the date and where she is?": ["평소에는 나이와 지금 계신 곳을 잘 아시는 편인가요?", "평소에는 날짜와 지금 사시는 곳을 잘 아시는 편인가요?"],
"How long has she seemed different than usual?": ["평소와 다르게 보이신 게 얼마나 자주인가요?", "평소와 다르게 말씀하신 지 얼마나 되셨나요?"],
"We really appreciate you telling us these details.": ["이렇게 빨리 말씀해 주셔서 정말 감사해요.", "이렇게 자세히 기록해 주셔서 정말 감사해요."],
# 활동·일상수행 청취
"Are you able to bathe and dress on your own?": ["혼자서 씻고 운전하는 게 가능하신가요?", "혼자서 장 보고 옷 입는 게 가능하신가요?"],
"Has anything changed in what you can do lately?": ["요즘 볼 수 있는 것에 변화가 있으셨나요?", "요즘 들을 수 있는 것에 변화가 있으셨나요?"],
"There's no shame in needing a little help.": ["휴식이 필요하다고 부끄러워하실 일은 전혀 아니에요.", "도움이 필요하다고 걱정하실 일은 전혀 아니에요."],
"Can you cook and manage your own meals at home?": ["혼자서 요리하고 빨래를 하실 수 있으신가요?", "혼자서 청소하고 식사를 챙기실 수 있으신가요?"],
"Do you need help getting up from a chair or the toilet?": ["의자나 침대에서 일어나실 때 도움이 필요하신가요?", "의자나 욕조에서 일어나실 때 도움이 필요하신가요?"],
"Has getting dressed become harder lately?": ["요즘 씻는 게 더 힘들어지셨나요?", "요즘 걷는 게 더 힘들어지셨나요?"],
# 급성 섬망 감별
"You're in the hospital and you're safe with me.": ["지금 병원에 계시고, 저와 함께 앉아 계세요.", "지금 병원에 계시고, 가족과 함께 안전하세요."],
"This confusion may be new — we're finding out why.": ["이 어지러움은 새로 생긴 걸 수도 있어요 — 저희가 원인을 찾고 있어요.", "이 혼돈은 새로 생긴 걸 수도 있어요 — 저희가 기록을 찾고 있어요."],
"I'm going to stay close and help you feel calmer.": ["제가 곁에 있으면서 좀 더 따뜻해지시도록 도와드릴게요.", "제가 곁에 있으면서 좀 더 힘이 나시도록 도와드릴게요."],
"Do you know where you are right now?": ["지금 누구와 계신지 아시겠어요?", "지금 무슨 요일인지 아시겠어요?"],
"I know this feels frightening, but you're not alone.": ["피곤하게 느껴지시는 거 알아요, 하지만 혼자가 아니세요.", "복잡하게 느껴지시는 거 알아요, 하지만 혼자가 아니세요."],
"Let's keep the room quiet and calm for you.": ["방을 조용하고 따뜻하게 유지할게요.", "방을 깨끗하고 차분하게 유지할게요."],
# 비전형 감염 표현
"In older adults, infections can show up as confusion, not fever.": ["노인분들은 감염이 열 대신 발진으로 나타날 수 있어요.", "노인분들은 감염이 열 대신 피로로 나타날 수 있어요."],
"Has she had any changes in urination or breathing?": ["소변이나 시력에 변화가 있으셨나요?", "식욕이나 호흡에 변화가 있으셨나요?"],
"We'll run tests to find a hidden infection.": ["숨겨진 골절을 찾기 위해 검사를 진행할게요.", "가벼운 감염을 찾기 위해 검사를 진행할게요."],
"Older patients don't always get a fever, even with a serious infection.": ["노인 환자분들은 심각한 감염이 있어도 땀이 늘 나는 건 아니에요.", "노인 환자분들은 심각한 감염이 있어도 기침이 늘 나는 건 아니에요."],
"Has she been eating or drinking less than usual?": ["평소보다 수면이나 물 섭취가 줄어드셨나요?", "평소보다 식사나 활동이 줄어드셨나요?"],
"We'll check her urine and listen to her lungs.": ["소변 검사를 하고 심장 소리를 들어볼게요.", "혈액 검사를 하고 폐 소리를 들어볼게요."],
# 노인 흉통 비전형
"Even without sharp pain, we take this seriously.": ["타는 듯한 통증이 없어도 저희는 이걸 진지하게 받아들여요.", "압박감이 없어도 저희는 이걸 진지하게 받아들여요."],
"Do you feel more tired or short of breath than usual?": ["평소보다 더 어지러우시거나 숨이 차시나요?", "평소보다 더 피곤하시거나 기침이 나시나요?"],
"We'll check your heart to be safe.": ["안전을 위해 목을 확인해볼게요.", "안전을 위해 발목을 확인해볼게요."],
"Some people your age feel pressure or tiredness instead of pain.": ["어르신 연령대에서는 통증 대신 가려움이나 피로감을 느끼기도 해요.", "어르신 연령대에서는 통증 대신 압박감이나 오한을 느끼기도 해요."],
"Have you had any nausea, sweating, or dizziness with this?": ["메스꺼움이나 기침, 어지러움이 함께 있으셨나요?", "메스꺼움이나 식은땀, 두통이 함께 있으셨나요?"],
"We take chest symptoms seriously in older patients.": ["임산부 환자분들의 흉부 증상은 저희가 진지하게 받아들여요.", "노인 환자분들의 복부 증상은 저희가 진지하게 받아들여요."],
"We'll do an EKG and some blood tests on your heart.": ["심전도랑 소변 검사로 심장을 확인해볼게요.", "심전도랑 혈액 검사로 폐를 확인해볼게요."],
# 다약제 상호작용 부작용
"When did the dizziness start after the new medication?": ["이 구토는 새 약을 드신 뒤 언제부터 시작됐나요?", "이 어지럼증은 새 약을 드신 뒤 얼마나 심해졌나요?"],
"Some medicines can interact and cause these symptoms.": ["일부 음식들은 서로 상호작용해서 이런 증상을 일으킬 수 있어요.", "일부 약들은 오래되면 이런 증상을 일으킬 수 있어요."],
"We'll review everything you take to find the cause.": ["복용하시는 모든 약을 검토해서 기록을 찾아볼게요.", "복용하시는 모든 약을 검토해서 처방한 병원을 찾아볼게요."],
"Has anyone added or changed a medicine recently?": ["최근에 새로 추가되거나 바뀐 식단이 있나요?", "최근에 새로 추가되거나 바뀐 담당 의사가 있나요?"],
"This combination may be making you unsteady on your feet.": ["이 약 조합 때문에 걸을 때 숨이 차실 수 있어요.", "이 약 조합 때문에 걸을 때 가려우실 수 있어요."],
"We may lower or stop one of these medicines.": ["이 약들 중 하나를 다시 주문하거나 채울 수도 있어요.", "이 약들 중 하나를 나누거나 보관할 수도 있어요."],
# 요양시설 이송 정보 부족
"Do you know her baseline and what happened today?": ["평소 상태랑 어제 무슨 일이 있었는지 아시나요?", "평소 상태랑 오늘 누가 왔는지 아시나요?"],
"Can you help me reach the facility for her records?": ["소지품을 확인하기 위해 시설에 연락하는 걸 도와주실 수 있나요?", "기록을 확인하기 위해 약국에 연락하는 걸 도와주실 수 있나요?"],
"Any medication or allergy info you can share?": ["보험이나 알레르기 정보 공유해 주실 수 있나요?", "가족력이나 알레르기 정보 공유해 주실 수 있나요?"],
"The paperwork doesn't say much — what's her normal mental status?": ["서류엔 별 내용이 없네요 — 평소 영양 상태는 어떠셨나요?", "서류엔 별 내용이 없네요 — 평소 활동 상태는 어떠셨나요?"],
"Do you have a contact number for the facility nurse?": ["시설 약사 연락처가 있으신가요?", "시설 관리자 연락처가 있으신가요?"],
"Let's call the facility to confirm her medication list.": ["약 목록을 확인하러 약국에 전화해볼게요.", "알레르기 목록을 확인하러 시설에 전화해볼게요."],
# 학대·방임 의심
"I noticed some things I'd like to understand better.": ["몇 가지 들은 점이 있어서 더 이해하고 싶어요.", "몇 가지 알아차린 점이 있어서 더 설명드리고 싶어요."],
"You're safe to talk with me — I'll be honest about who else needs to know.": ["여기서는 안전하게 쉬셔도 돼요 — 누가 더 알아야 하는지는 솔직하게 말씀드릴게요.", "여기서는 안전하게 말씀하셔도 돼요 — 누가 더 알아야 하는지는 내일 말씀드릴게요."],
"My only goal is to make sure you're cared for.": ["제 목표는 어르신이 식사를 잘 하시도록 하는 것뿐이에요.", "제 목표는 어르신이 편히 주무시도록 하는 것뿐이에요."],
"I want to ask about some bruises I noticed on your arm.": ["팔에 있는 굳은살에 대해 여쭤보고 싶어요.", "다리에 있는 멍에 대해 여쭤보고 싶어요."],
"Are you getting enough food at home?": ["집에서 수면은 충분히 취하고 계신가요?", "집에서 난방은 충분히 되고 있나요?"],
"I ask everyone this — do you feel safe where you live?": ["모든 분께 여쭤보는 건데요 — 일하시는 곳에서 안전하다고 느끼세요?", "모든 분께 여쭤보는 건데요 — 사시는 곳에서 외롭다고 느끼세요?"],
# 진통제 신중 투여
"We'll start low and adjust carefully for your kidneys.": ["적은 용량으로 시작해서 간 상태에 맞춰 조절할게요.", "적은 용량으로 시작해서 심장 상태에 맞춰 조절할게요."],
"I'll help you avoid feeling too groggy or unsteady.": ["너무 가렵거나 휘청거리지 않도록 도와드릴게요.", "너무 몽롱하거나 메스껍지 않도록 도와드릴게요."],
"Tell me if you feel dizzy at any point.": ["조금이라도 졸리시면 언제든 말씀해 주세요.", "조금이라도 메스꺼우시면 언제든 말씀해 주세요."],
"Your kidneys process medication more slowly as you age.": ["나이가 드시면 폐가 약을 더 천천히 처리해요.", "나이가 드시면 근육이 약을 더 천천히 처리해요."],
"We'll watch you closely for any side effects.": ["다른 감염이 없는지 가까이서 지켜볼게요.", "다른 부작용이 없는지 가까이서 기록할게요."],
"Please don't try to get up alone until we check on you.": ["저희가 확인할 때까지 혼자 식사하려 하지 마세요.", "저희가 확인할 때까지 혼자 샤워하려 하지 마세요."],
# 보청기·안경 보조기구
"Let's see if we can get you some help hearing and seeing better.": ["걷고 보시는 데 도움이 될 만한 걸 함께 찾아볼게요.", "듣고 기억하시는 데 도움이 될 만한 걸 함께 찾아볼게요."],
"I'll speak clearly and stay in your view.": ["제가 크게 말하고 시야 안에 있을게요.", "제가 또렷하게 말하고 문 앞에 있을게요."],
"Having your glasses will help you feel less confused.": ["안경을 쓰시면 덜 불안해지실 거예요.", "안경을 쓰시면 덜 피곤해지실 거예요."],
"Do you usually wear glasses or contact lenses?": ["평소에 안경이나 보청기를 쓰시나요?", "평소에 틀니나 콘택트렌즈를 쓰시나요?"],
"Let's get your hearing aid batteries replaced if needed.": ["필요하면 보청기 케이스도 교체해드릴게요.", "필요하면 휠체어 배터리도 교체해드릴게요."],
"Wearing your glasses can make you feel much less confused here.": ["안경을 쓰시면 여기서 훨씬 덜 불안하실 거예요.", "안경을 쓰시면 밤에 훨씬 덜 혼란스러우실 거예요."],
# 사전연명의료의향 확인
"Do you know if he has a POLST or advance directive?": ["POLST나 건강보험증이 있으신지 아시나요?", "유언장이나 사전의료의향서가 있으신지 아시나요?"],
"What matters most to him about his care?": ["그분께 취미에서 가장 중요한 게 뭘까요?", "그분께 식단에서 가장 중요한 게 뭘까요?"],
"We'll honor his wishes as best we can.": ["저희가 할 수 있는 한 그분의 뜻을 설명해 드릴게요.", "저희가 할 수 있는 한 그분의 뜻을 공유해 드릴게요."],
"Has he ever talked about what kind of care he'd want?": ["평소에 원하시는 치료 방식에 대해 걱정하신 적이 있나요?", "평소에 원하시는 치료 장소에 대해 말씀하신 적이 있나요?"],
"Do you have a copy of the directive with you today?": ["오늘 보험증 사본을 가지고 오셨나요?", "오늘 약 목록 사본을 가지고 오셨나요?"],
"We want to respect his wishes and support your family.": ["그분의 뜻을 존중하고 결정을 지지해드리고 싶어요.", "그분의 뜻을 기억하고 가족분들을 지지해드리고 싶어요."],
# 노인 패혈증 급속 진행
"Her low temperature and pressure worry me — we're acting fast.": ["산소가 낮고 혈압도 걱정돼서 저희가 빠르게 움직이고 있어요.", "체온이 낮고 맥박도 걱정돼서 저희가 빠르게 움직이고 있어요."],
"In older adults sepsis can look different, and we're on it.": ["노인분들은 빈혈이 다르게 나타날 수 있는데, 저희가 확인하고 있어요.", "노인분들은 패혈증이 다르게 나타날 수 있는데, 저희가 기록하고 있어요."],
"We're starting treatment right away.": ["바로 설명을 시작할게요.", "바로 기록을 시작할게요."],
"Sepsis in older adults may not cause a high fever.": ["노인분들은 패혈증이 있어도 기침이 안 날 수 있어요.", "노인분들은 패혈증이 있어도 구토가 안 날 수 있어요."],
"We're giving fluids and antibiotics right away.": ["수액이랑 항생제 이름표를 바로 확인할게요.", "수액이랑 항생제 서류를 바로 정리할게요."],
"I'll explain each step as we move quickly.": ["빠르게 움직이는 동안 단계마다 기록해 드릴게요.", "빠르게 움직이는 동안 번호마다 설명해드릴게요."],
# 항응고제 두부외상
"Because she's on blood thinners, we take head bumps seriously.": ["혈압약을 복용 중이시라서 머리 부딪힘도 저희는 심각하게 받아들여요.", "수면제를 복용 중이시라서 머리 부딪힘도 저희는 심각하게 받아들여요."],
"We'll get a scan right away to rule out bleeding.": ["골절이 없는지 바로 영상 촬영을 할게요.", "출혈이 없는지 바로 소변 검사를 할게요."],
"Watch for any drowsiness or confusion — tell me immediately.": ["졸리거나 혼란스러운 모습이 보이면 바로 불을 켜 주세요.", "졸리거나 혼란스러운 모습이 보이면 바로 담요를 덮어 주세요."],
"Even a small bump can cause bleeding on blood thinners.": ["기침약을 드시고 계시면 작은 부딪힘도 출혈을 일으킬 수 있어요.", "비타민을 드시고 계시면 작은 부딪힘도 출혈을 일으킬 수 있어요."],
"We'll monitor her closely for the next few hours.": ["앞으로 며칠 동안 가까이서 지켜볼게요.", "앞으로 몇 시간 동안 가까이서 도와드릴게요."],
"Please tell us right away if she seems more confused.": ["더 혼란스러워 보이시면 바로 안경을 씌워 주세요.", "더 혼란스러워 보이시면 바로 의자를 가져다 주세요."],
# 급성 섬망+공격성
"You're safe here — I'm not going to hurt you.": ["여기서는 조용해요 — 제가 다치게 하지 않을게요.", "여기서는 안전해요 — 제가 곁에서 지켜볼게요."],
"Something's causing this confusion and we're finding it.": ["이 두통을 일으키는 원인이 있고, 저희가 찾고 있어요.", "이 혼돈을 일으키는 원인이 있고, 저희가 기록하고 있어요."],
"Let's lower the noise so you feel calmer.": ["조명을 줄여서 좀 더 편안해지시게 할게요.", "침대를 낮춰서 좀 더 편안해지시게 할게요."],
"We're checking your blood and body for what's causing this.": ["이걸 일으킨 원인을 찾기 위해 소변과 몸 상태를 확인하고 있어요.", "이걸 일으킨 원인을 찾기 위해 혈액과 몸 상태를 적고 있어요."],
"I won't hold you down unless it keeps you safe.": ["안전을 지키기 위해서가 아니면 깨우지 않을게요.", "안전을 지키기 위해서가 아니면 옮기지 않을게요."],
"Let's dim the lights and keep things calm around you.": ["침대를 낮추고 주변을 차분하게 유지할게요.", "조명을 낮추고 주변을 깨끗하게 유지할게요."],
# 말기 환자 목표 재설정
"Let's talk about what would give him the most comfort.": ["그분께 가장 힘이 되어 줄 수 있는 방법을 함께 이야기해볼게요.", "그분께 가장 시간을 더 줄 수 있는 방법을 함께 이야기해볼게요."],
"There's no wrong choice here — we'll support whatever you decide.": ["여기엔 빠른 선택이 없어요 — 어떤 결정을 하시든 저희가 지지할게요.", "여기엔 잘못된 선택이 없어요 — 어떤 결정을 하시든 저희가 설명드릴게요."],
"Comfort care is an active, caring option too.": ["일반 돌봄도 적극적이고 정성스러운 하나의 선택지예요.", "추가 돌봄도 적극적이고 정성스러운 하나의 선택지예요."],
"What matters most to him at this stage of his illness?": ["이 단계에서 그분께 가장 힘든 게 뭘까요?", "이 단계에서 그분의 가족께 가장 중요한 게 뭘까요?"],
"We can focus on his comfort instead of aggressive treatment.": ["실험적인 치료 대신 편안함에 집중할 수도 있어요.", "적극적인 치료 대신 휴식에 집중할 수도 있어요."],
"Whatever you decide, we'll support your family fully.": ["어떤 결정을 하시든 이웃분들을 온전히 지지해드릴게요.", "어떤 결정을 하시든 동료분들을 온전히 지지해드릴게요."],
# 다발성 만성질환 급성 악화
"Your heart and kidneys are both under strain — we're balancing them.": ["심장과 폐 모두 부담을 받고 있어서, 저희가 균형을 맞추고 있어요.", "심장과 신장 모두 부담을 받고 있어서, 저희가 상의하고 있어요."],
"We'll help your breathing first and go from there.": ["먼저 통증을 도와드리고 그다음을 살펴볼게요.", "먼저 부기를 도와드리고 그다음을 살펴볼게요."],
"Tell me which symptom is bothering you most.": ["어떤 약이 가장 힘드신지 알려 주세요.", "어떤 검사가 가장 힘드신지 알려 주세요."],
"Your legs are swollen because your heart isn't pumping well.": ["심장이 잘 뛰지 못해서 다리가 가려우신 거예요.", "심장이 잘 뛰지 못해서 다리가 뻣뻣하신 거예요."],
"We'll treat your breathing and your heart at the same time.": ["호흡이랑 통증을 동시에 치료할게요.", "호흡이랑 어지럼증을 동시에 치료할게요."],
"Let's figure out together which problem to treat first.": ["어떤 문제를 먼저 설명할지 함께 정해볼게요.", "어떤 문제를 먼저 치료할지 가족과 정해볼게요."],
# 고관절 골절 통증·수술 대기
"We'll manage your pain while you wait for surgery.": ["수술을 기다리시는 동안 일정을 관리해 드릴게요.", "수술을 기다리시는 동안 서류를 관리해 드릴게요."],
"Staying oriented and hydrated helps prevent confusion.": ["지남력을 유지하고 따뜻하게 지내면 혼돈을 예방하는 데 도움이 돼요.", "지남력을 유지하고 깨어 있으면 혼돈을 예방하는 데 도움이 돼요."],
"I'll keep checking on you so you're not alone.": ["늦지 않도록 계속 살펴보러 올게요.", "길을 잃지 않도록 계속 살펴보러 올게요."],
"Your hip fracture needs surgery, but we'll keep you comfortable until then.": ["고관절 골절이라 수술이 필요하지만, 그때까지 조용하게 지내시도록 도와드릴게요.", "고관절 골절이라 수술이 필요하지만, 그때까지 따뜻하게 지내시도록 도와드릴게요."],
"Let me check if you can drink water to stay hydrated before surgery.": ["수술 전에 체온 유지를 위해 담요를 써도 되는지 확인해 볼게요.", "수술 전에 통증 조절을 위해 약을 드셔도 되는지 확인해 볼게요."],
"Let's keep you oriented and engaged while you wait.": ["기다리시는 동안 지남력을 유지하고 계속 음악을 들으며 지내시도록 도와드릴게요.", "기다리시는 동안 청력을 유지하고 계속 이야기 나누며 지내시도록 도와드릴게요."],
# 요양원 이송 임종 임박
"We'll focus on keeping her comfortable and peaceful.": ["편안하고 깨끗하게 지내실 수 있도록 초점을 맞출게요.", "편안하고 평온하게 지내실 수 있도록 일정을 맞출게요."],
"You can hold her hand and speak to her — she may still hear you.": ["발을 잡고 말을 건네셔도 돼요 — 아직 들리실 수 있어요.", "손을 잡고 말을 건네셔도 돼요 — 아직 보이실 수 있어요."],
"Take all the time you need; we're here for all of you.": ["필요한 만큼 물을 드세요; 저희가 가족분들 곁에 있어요.", "필요한 만큼 시간을 가지세요; 저희가 환자분 곁에 있어요."],
"We'll keep the room calm and dim the lights for her.": ["방을 따뜻하게 하고 조명을 낮춰드릴게요.", "방을 차분하게 하고 음악을 낮춰드릴게요."],
"It's okay to say goodbye in whatever way feels right to you.": ["어떤 방식으로든 편하게 감사 인사를 하셔도 괜찮아요.", "어떤 방식으로든 편하게 사과 인사를 하셔도 괜찮아요."],
"We'll make sure she stays comfortable and free of pain.": ["소음 없이 편안하게 지내시도록 해드릴게요.", "외풍 없이 편안하게 지내시도록 해드릴게요."],
}
W = {
 "w-counter": {"distractorsKo": ["처방전 받아 (사는)", "남몰래 (사서 쓰는)"]},
 "w-pharmacy": {"distractorsEn": ["pharmacist", "farmer"]},
 "w-run": {"distractorsKo": ["(결과를) 해석하다", "(원인을) 배제하다"]},
 "w-pain": {"distractorsEn": ["itch", "rash"]},
 "w-allergy": {"distractorsKo": ["염증", "부작용"]},
 "w-honor": {"distractorsKo": ["(뜻을) 바꾸다", "(뜻을) 전하다"]},
 "w-treatment": {"distractorsEn": ["triage", "transplant"]},
 "w-dim": {"distractorsKo": ["(조명을) 켜다", "(조명을) 깜빡이다"]},
}
B = {
 "Did you lose consciousness at any point?": ["coordination", "concentration", "motivation"],
 "Are you currently taking any blood thinners or sleep medication?": ["heartburn pills", "cough medicine", "allergy pills"],
 "Do you have a list or the bottles with you?": ["receipts", "wallets", "photos"],
 "I know this feels frightening, but you're not alone.": ["complicated", "expensive", "crowded"],
 "Do you have a contact number for the facility nurse?": ["manager", "cook", "driver"],
 "Do you have a copy of the directive with you today?": ["consent form", "lab report", "photo ID"],
 "Her low temperature and pressure worry me — we're acting fast.": ["blood sugar", "potassium", "oxygen level"],
}
run(P, S, W, B)
