from dk_lib import run
S={
"How long were you out in the heat, and were you drinking water?":["더운 데 얼마나 오래 계셨어요, 그리고 식사는 하셨어요?","더운 데 얼마나 오래 계셨어요, 그리고 혼자 계셨어요?"],
"When did you start feeling dizzy or sick?":["언제부터 어지럽거나 두통이 있으셨어요?","언제부터 가렵거나 메스꺼우셨어요?"],
"Were you able to find any shade or rest?":["그늘을 찾거나 물을 마실 수는 있으셨어요?","차를 찾거나 쉴 수는 있으셨어요?"],
"Tell me where you were and for how long.":["누구와 얼마나 오래 계셨는지 말씀해 주세요.","어디에 몇 시에 계셨는지 말씀해 주세요."],
"Did you have any water with you out there?":["거기 계실 때 모자를 쓰고 계셨어요?","거기 계실 때 휴대폰을 갖고 계셨어요?"],
"I'm going to check your temperature and pulse now.":["지금 혈압과 맥박을 확인해 볼게요.","지금 체온과 호흡을 확인해 볼게요."],
"Sweating and feeling faint are signs of heat exhaustion.":["땀이 나고 어지러운 건 열경련의 징후예요.","땀이 나고 가려운 건 열탈진의 징후예요."],
"We're cooling you down and giving you fluids to drink.":["몸을 식혀 드리고 쉴 곳도 드릴게요.","몸을 닦아 드리고 마실 것도 드릴게요."],
"Tell me if you get confused or stop sweating — that's more serious.":["혼란스러워지거나 토하고 싶으면 말씀해 주세요 — 그건 더 심각한 거예요.","추워지거나 땀이 멈추면 말씀해 주세요 — 그건 더 심각한 거예요."],
"Let's get you some water and a cool cloth.":["물이랑 시원한 부채를 가져다드릴게요.","주스랑 시원한 수건을 가져다드릴게요."],
"How long were you out in the heat today?":["어제 더운 데 얼마나 오래 계셨어요?","오늘 더운 데 어디에 계셨어요?"],
"Your pulse is a little fast, but your temperature looks okay.":["맥박은 조금 빠른데, 체온을 한 번 더 재 볼게요.","맥박은 조금 빠른데, 수분은 더 드릴게요."],
"The shivering means your body is trying to warm itself.":["떨리는 건 몸이 스스로 수분을 지키려는 거예요.","떨리는 건 몸이 스스로 쉬려는 거예요."],
"We're getting you out of these wet clothes and into warm blankets.":["젖은 옷을 벗고 마른 수건으로 닦아 드릴게요.","젖은 옷을 벗고 따뜻한 방으로 모셔 드릴게요."],
"How long were you out in the cold and wet?":["춥고 젖은 데 어떻게 가셨어요?","춥고 어두운 데 얼마나 오래 계셨어요?"],
"Can you tell me how you're feeling right now?":["지금 어디가 아픈지 말씀해 주실 수 있어요?","지금 어떤 소리가 들리는지 말씀해 주실 수 있어요?"],
"Your words sound a little slurred — that can happen with the cold.":["손이 조금 떨리는데 — 추위 때문에 그럴 수 있어요.","피부가 조금 차가운데 — 추위 때문에 그럴 수 있어요."],
"We'll keep checking your temperature as you warm up.":["따뜻해지는 동안 맥박을 계속 확인할게요.","따뜻해지는 동안 기분을 계속 확인할게요."],
"We'll cool the skin and give you something for the pain.":["피부를 식혀 드리고 보습제도 드릴게요.","피부를 닦아 드리고 통증 약도 드릴게요."],
"Drink plenty of water, since sunburn can dry you out.":["일광화상은 몸을 건조하게 하니 로션을 충분히 바르세요.","일광화상은 몸을 건조하게 하니 그늘에 충분히 계세요."],
"Watch for blisters or a fever, and don't pop any blisters.":["물집이나 열이 나는지 지켜보시고, 옷은 헐렁하게 입으세요.","물집이나 열이 나는지 지켜보시고, 햇빛은 피해 주세요."],
"Your shoulders look pretty sunburned and tender.":["등이 꽤 심하게 타고 만지면 아프시겠어요.","어깨가 꽤 심하게 타고 가려우시겠어요."],
"Try not to scratch or rub the burned skin.":["화상 입은 피부는 햇빛에 노출하지 마세요.","화상 입은 피부는 꽉 끼는 옷을 피하세요."],
"Aloe or a cool compress can help with the pain.":["알로에나 시원한 찜질이 가려움에 도움이 돼요.","알로에나 시원한 샤워가 통증에 도움이 돼요."],
"Since you're keeping fluids down, let's start with drinking these.":["수분을 잘 받아들이고 계시니 이것부터 확인해 볼게요.","구토를 잘 참고 계시니 이것부터 마셔 볼게요."],
"If you can't drink enough, we'll give you fluids through an IV.":["충분히 못 드시면 의사에게 상황을 알릴게요.","충분히 못 드시면 빨대로 수분을 드릴게요."],
"Small frequent sips work better than gulping a lot at once.":["한 번에 벌컥벌컥 마시는 것보다 천천히 앉아서 마시는 게 나아요.","한 번에 벌컥벌컥 마시는 것보다 차게 해서 마시는 게 나아요."],
"You look pretty weak and thirsty right now.":["지금 많이 피곤하고 목말라 보이세요.","지금 많이 힘없고 배고파 보이세요."],
"Let's check how dehydrated you are with a quick exam.":["간단히 진찰해서 얼마나 열이 나는지 확인해 볼게요.","간단히 진찰해서 얼마나 아픈지 확인해 볼게요."],
"Big gulps can upset your stomach and make you throw up.":["한꺼번에 많이 마시면 속이 불편해져서 배가 아플 수 있어요.","한꺼번에 차게 마시면 속이 불편해져서 토할 수 있어요."],
"Your body temperature is dangerously high and we're cooling you fast.":["체온이 위험할 정도로 높아서 빠르게 확인하고 있어요.","체온이 위험할 정도로 높아서 빠르게 재고 있어요."],
"We're putting cool packs on you and misting you to bring it down.":["체온을 확인하려고 체온계를 대고 기록을 하고 있어요.","수분을 보충하려고 정맥 라인을 잡고 소독을 하고 있어요."],
"Can you tell me your name and where you are right now?":["지금 성함이 뭔지, 오늘이 며칠인지 말씀해 주시겠어요?","지금 성함이 뭔지, 어디가 아픈지 말씀해 주시겠어요?"],
"Can you squeeze my hand for me?":["제 이름을 따라 말해 보실 수 있어요?","제 발을 꽉 눌러 보실 수 있어요?"],
"We're going to get your temperature down quickly.":["체온을 빨리 재 드릴게요.","맥박을 빨리 확인해 드릴게요."],
"Stay with me — you're going to be okay.":["정신 놓지 마세요 — 제가 곁에 있을게요.","눈 감지 마세요 — 괜찮아지실 거예요."],
"When shivering stops, the cold has gone deeper — this is serious.":["떨림이 멎으면 추위가 더 깊이 들어간 거예요 — 의사를 부를게요.","떨림이 멎으면 추위가 더 깊이 들어간 거예요 — 담요를 더 가져올게요."],
"We're actively warming him with heated blankets and warm fluids.":["가온 담요와 따뜻한 수액을 능동적으로 준비하고 있어요.","가온 담요와 모니터로 능동적으로 지켜보고 있어요."],
"We'll move him gently to avoid stressing his heart.":["심장에 부담이 가지 않게 모니터를 먼저 붙일게요.","심장에 부담이 가지 않게 부드럽게 닦아 드릴게요."],
"He's moving more slowly and sleeping more than before — we expect that to improve as he warms up.":["움직임이 느려지고 더 많이 자는데 — 계속 깨워서 확인할게요.","움직임이 느려지고 더 많이 자는데 — 보호자께 말씀드릴게요."],
"We're checking his heart rhythm closely while we rewarm him.":["재가온하는 동안 체온을 계속 확인할게요.","재가온하는 동안 호흡을 계속 확인할게요."],
"Try not to rub or massage his arms and legs.":["팔다리에 젖은 담요는 덮지 마세요.","팔다리는 억지로 구부리거나 펴지 마세요."],
"We're rewarming your fingers in warm water, and the throbbing is expected.":["손가락을 따뜻한 물에 재가온하고 있고, 가려운 건 예상되는 거예요.","손가락을 따뜻한 물에 재가온하고 있고, 물집은 예상되는 거예요."],
"Don't rub them — that can damage the tissue more.":["눌러 보지 마세요 — 조직이 더 손상될 수 있어요.","문지르지 마세요 — 통증이 더 심해질 수 있어요."],
"We'll watch for blisters and check how the color returns.":["물집이 생기는지, 붓기가 어떻게 가라앉는지 지켜볼게요.","통증이 생기는지, 색깔이 어떻게 돌아오는지 지켜볼게요."],
"Your fingers had frostbite, so we need to warm them in warm water.":["손가락에 동상을 입어서 사진을 찍어 두어야 해요.","손가락에 동상을 입어서 상처를 살펴봐야 해요."],
"Tell me when you start to feel any tingling or pain.":["따끔거리거나 아픈 느낌이 심해지면 말씀해 주세요.","따끔거리거나 가려운 느낌이 시작되면 말씀해 주세요."],
"We're keeping your hands elevated to help the swelling.":["붓기에 도움이 되게 손을 헐렁하게 감아 두고 있어요.","붓기를 보려고 손을 사진으로 남기고 있어요."],
"Dehydration in the heat can cause confusion in older adults.":["더위 속 탈수는 노인분들에게 어지러움을 일으킬 수 있어요.","더위 속 탈수는 아이들에게 혼란을 일으킬 수 있어요."],
"We'll check her electrolytes and rehydrate her carefully.":["전해질을 확인하고 조심스럽게 소변량을 재 드릴게요.","혈당을 확인하고 조심스럽게 재수화해 드릴게요."],
"Has she been urinating less or feeling dizzy when standing?":["소변량이 줄었거나 앉아 있을 때 어지러워하셨어요?","식사량이 줄었거나 서 있을 때 어지러워하셨어요?"],
"How much has she been eating or drinking the past few days?":["지난 몇 주 동안 얼마나 드시고 마셨어요?","지난 며칠 동안 얼마나 걸으시고 쉬셨어요?"],
"Older adults can get confused quickly when they're dehydrated.":["노인분들은 탈수되면 빨리 어지러워질 수 있어요.","아이들은 탈수되면 빨리 혼란스러워질 수 있어요."],
"We'll keep a close eye on her while the fluids go in.":["수액이 들어가는 동안 기록을 남길게요.","약이 들어가는 동안 잘 지켜볼게요."],
"We're checking your core temperature with a special probe.":["특수 탐침으로 맥박을 확인하고 있어요.","특수 탐침으로 심부 체온을 기록하고 있어요."],
"We're cooling you with an ice-water immersion to bring it down fast.":["얼음물 침수 전에 빠르게 체온을 확인하고 있어요.","얼음물 침수 준비로 빠르게 욕조를 채우고 있어요."],
"How long were you running, and when did the cramps start?":["얼마나 오래 달리셨고, 언제부터 어지러웠어요?","얼마나 멀리 달리셨고, 언제부터 경련이 시작됐어요?"],
"Tell me exactly when you collapsed during the race.":["경주 중 정확히 어디서 쓰러지셨는지 말씀해 주세요.","경주 중 정확히 언제 물을 드셨는지 말씀해 주세요."],
"We're giving you fluids to help with the cramping.":["경련에 도움이 되게 다리를 펴 드릴게요.","경련 때문에 의사에게 먼저 알릴게요."],
"Your temperature is coming down well with the cooling.":["냉각으로 맥박이 잘 내려가고 있어요.","냉각 중이라 체온을 계속 확인하고 있어요."],
"You're colder than you feel, so let's get you warm and safe.":["느끼시는 것보다 체온이 낮으니 따뜻하고 조용하게 해 드릴게요.","느끼시는 것보다 맥박이 느리니 따뜻하고 안전하게 해 드릴게요."],
"I'm not judging you — I just want to take good care of you.":["혼내려는 게 아니에요 — 그저 잘 돌봐드리고 싶은 거예요.","판단하려는 게 아니에요 — 그저 잘 알아보고 싶은 거예요."],
"When did you last eat or have something to drink?":["마지막으로 언제 주무시거나 쉬셨어요?","마지막으로 어디서 드시거나 마셨어요?"],
"It's okay, we just want to make sure you're safe tonight.":["괜찮아요, 오늘 밤 따뜻하신지만 확인하고 싶은 거예요.","괜찮아요, 오늘 밤 어디 계실지만 확인하고 싶은 거예요."],
"Have you had anything to drink today, including alcohol?":["오늘 약을 포함해서 뭐든 드신 게 있으세요?","어제 술을 포함해서 뭐든 마신 게 있으세요?"],
"Let's get those cold, wet clothes off and warm you up.":["차갑고 젖은 신발을 벗기고 따뜻하게 해 드릴게요.","차갑고 젖은 옷을 벗기고 마른 옷으로 갈아 입혀 드릴게요."],
"We're watching his breathing closely since water can affect the lungs.":["물이 폐에 영향을 줄 수 있어서 산소를 계속 지켜보고 있어요.","물이 폐에 영향을 줄 수 있어서 기침을 계속 기록하고 있어요."],
"At the same time we're warming his body core.":["동시에 몸의 심부도 확인하고 있어요.","동시에 몸의 겉도 닦아 주고 있어요."],
"How long was he in the water, and did he go under?":["물에 얼마나 오래 있었고, 물을 마신 적 있어요?","물에 언제 빠졌고, 물속에 잠긴 적 있어요?"],
"He's coughing a lot, so we're keeping a close watch on his breathing.":["기침을 많이 해서 맥박을 계속 살피고 있어요.","구토를 많이 해서 호흡을 계속 살피고 있어요."],
"So you pulled him out of the ice water a few minutes ago?":["몇 분 전에 얼음물에 빠졌다는 거죠?","몇 분 전에 호수에서 끌어내셨다는 거죠?"],
"We'll listen to his lungs and check his oxygen levels.":["폐 소리를 듣고 체온을 확인할게요.","심장 소리를 듣고 산소 수치를 확인할게요."],
"Heat cramps often come from losing salt when you sweat a lot.":["열경련은 땀을 많이 흘려 칼슘을 잃으면서 자주 생겨요.","열경련은 햇볕을 많이 쬐어 염분을 잃으면서 자주 생겨요."],
"We'll give you fluids with electrolytes to replace what you lost.":["잃은 걸 보충하려고 전해질이 든 수액을 확인할게요.","잃은 걸 확인하려고 전해질 검사를 해 드릴게요."],
"Next time, take breaks and drink electrolyte drinks, not just water.":["다음엔 쉬어 가면서 물만 말고 과일도 드세요.","다음엔 쉬어 가면서 물만 말고 전해질 간식도 챙기세요."],
"Your legs are cramping because your body lost salt through sweat.":["땀으로 염분을 잃어서 팔에 쥐가 나는 거예요.","운동으로 근육을 써서 다리에 쥐가 나는 거예요."],
"Let's stretch your leg gently to help the cramp ease.":["쥐가 풀리게 다리를 부드럽게 따뜻하게 해 볼게요.","쥐가 풀리게 팔을 부드럽게 스트레칭해 볼게요."],
"Try to take a break every hour or so when you're working in the heat.":["더위 속에서 일할 땐 매시간쯤 간식을 드세요.","더위 속에서 일할 땐 모자를 꼭 쓰세요."],
"How high did he climb, and how fast?":["얼마나 높이, 얼마나 오래 올라갔나요?","얼마나 멀리, 얼마나 빨리 올라갔나요?"],
"When did the headache and shortness of breath start?":["두통과 구토가 언제 시작됐어요?","두통과 숨참이 어디서 시작됐어요?"],
"We're giving oxygen and will explain each step through the interpreter.":["산소를 확인하고 통역을 통해 각 단계를 설명해 드릴게요.","산소를 드리고 보호자를 통해 각 단계를 설명해 드릴게요."],
"Did he come down as soon as he started feeling sick?":["몸이 안 좋아지기 시작하자마자 바로 알렸나요?","배가 고파지기 시작하자마자 바로 내려왔나요?"],
"Is he still having chest pain or feeling confused?":["아직 가슴 통증이 있거나 구토하시나요?","아직 두통이 있거나 혼란스러워하시나요?"],
"We'll explain everything slowly through the interpreter.":["통역을 통해 천천히 다 확인해 드릴게요.","그림을 통해 천천히 다 설명해 드릴게요."],
"The stiffness makes me wonder if a medication is causing this, not just heat.":["이 뻣뻣함 때문에 감염 때문이 아닐지 궁금해요, 더위만은 아닌 것 같고요.","이 뻣뻣함 때문에 약물 때문이 아닐지 궁금해요, 운동만은 아닌 것 같고요."],
"What new medications did you start, and when?":["어떤 새 약을 어디서 시작하셨어요?","어떤 새 약을 얼마나 드셨어요?"],
"We'll cool you down while we figure out the exact cause.":["정확한 원인을 찾는 동안 계속 옆에 있을게요.","정확한 원인을 찾는 동안 검사를 더 할게요."],
"Are you feeling stiff anywhere besides your neck and jaw?":["목과 턱 말고 다른 데도 아프게 느껴지세요?","목과 어깨 말고 다른 데도 뻣뻣하게 느껴지세요?"],
"Tell me the name of the medication and when you started it.":["약 이름이 뭔지, 얼마나 드셨는지 말씀해 주세요.","약 이름이 뭔지, 어디서 받으셨는지 말씀해 주세요."],
"We're checking your temperature closely to see if it's the heat or the drug.":["더위 때문인지 약 때문인지 보려고 근육을 자세히 확인하고 있어요.","감염 때문인지 약 때문인지 보려고 체온을 자세히 확인하고 있어요."],
"Core temp is critically high with signs of organ injury and clotting problems.":["심부 체온이 위험할 정도로 높고, 장기 손상과 신경 문제 징후가 있습니다.","심부 체온이 위험할 정도로 높고, 근육 손상과 응고 문제 징후가 있습니다."],
"We're aggressively cooling and checking for muscle breakdown and DIC.":["적극적으로 냉각하면서 근육 분해와 소변량을 확인하고 있습니다.","적극적으로 냉각하면서 신장 손상과 DIC를 확인하고 있습니다."],
"Heat stroke with multi-organ failure — I need labs and blood products ready.":["다장기부전을 동반한 열사병입니다 — 검사와 수액을 준비해 주세요.","다장기부전을 동반한 열사병입니다 — 검사와 병상을 준비해 주세요."],
"Temp's forty-one and climbing despite cooling.":["맥박이 140이고 냉각 중인데도 계속 오르고 있습니다.","체온이 41도이고 이송 중인데도 계속 오르고 있습니다."],
"Urine is dark — I'm worried about rhabdo.":["소변이 어두운색이라 탈수가 걱정됩니다.","소변이 적어서 횡문근융해가 걱정됩니다."],
"Call the ICU, we'll need a bed for multi-organ support.":["중환자실에 연락 주세요, 다장기 지지를 위한 장비가 필요합니다.","중환자실에 연락 주세요, 다장기 지지를 위한 인력이 필요합니다."],
"He's not dead until he's warm and dead — keep resuscitating.":["따뜻해질 때까지는 죽은 게 아닙니다 — 시간을 계속 기록하세요.","따뜻해질 때까지는 죽은 게 아닙니다 — 팀에게 계속 알리세요."],
"Continue compressions while we actively rewarm the core.":["심부를 능동적으로 재가온하는 동안 시간을 계속 재세요.","심부를 능동적으로 재가온하는 동안 모니터를 계속 보세요."],
"Deep hypothermic arrest — let's activate the ECMO team now.":["심부저체온 심정지입니다 — 지금 체온을 다시 확인합시다.","심부저체온 심정지입니다 — 지금 ECMO 장비를 점검합시다."],
"His rhythm still shows no pulse, so we continue CPR.":["아직 리듬에 맥박이 안 잡혀서 CPR 교대를 준비합니다.","아직 리듬에 맥박이 안 잡혀서 모니터를 확인합니다."],
"Keep him horizontal and avoid rough handling during the resuscitation.":["수평으로 유지하고 소생술 중 모니터 선을 확인하세요.","수평으로 유지하고 소생술 중 체온을 계속 기록하세요."],
"We're prepping the room for ECMO right now.":["지금 ECMO를 위해 약을 준비하고 있어요.","지금 이송을 위해 방을 준비하고 있어요."],
"The tightness and severe pain worry me about pressure building in your foot.":["조임과 심한 통증 때문에 발에 감염이 생기는 게 걱정돼요.","조임과 심한 통증 때문에 다리에 압력이 쌓이는 게 걱정돼요."],
"We're checking the circulation and calling surgery to assess you.":["순환을 확인하고 사진을 찍어 기록할게요.","맥박을 확인하고 외과를 불러 평가받게 할게요."],
"Tell me if the numbness or pain gets worse — that's important.":["감각이 없어지거나 통증이 심해지면 말씀해 주세요 — 바로 올게요.","감각이 없어지거나 통증이 심해지면 말씀해 주세요 — 보호자도 알려 주세요."],
"Your foot looks more swollen than before, and it's very tight.":["발이 전보다 더 붉어졌고, 아주 조여 있어요.","발이 전보다 더 부었고, 아주 차가워요."],
"We need surgery to look at the pressure in your foot right away.":["지금 바로 외과에서 발의 사진을 봐야 해요.","지금 바로 외과에서 발의 맥박을 봐야 해요."],
"Can you feel me touching your toes right now?":["지금 발가락 움직이는 게 느껴지세요?","지금 발목 만지는 게 느껴지세요?"],
"Dark urine with muscle aches can mean your muscles are breaking down.":["소변이 어둡고 근육이 쑤신 건 검사가 필요하다는 뜻일 수 있어요.","소변이 어둡고 허리가 아픈 건 근육이 분해되고 있다는 뜻일 수 있어요."],
"We're giving lots of fluids to protect your kidneys.":["신장을 보호하려고 소변량을 많이 재고 있어요.","신장을 확인하려고 피를 많이 뽑고 있어요."],
"We'll watch your urine output closely and check a muscle enzyme called CK.":["소변량을 계속 지켜보고 CK라는 근육 효소를 설명할게요.","혈압을 계속 지켜보고 CK라는 근육 효소를 확인할게요."],
"Your muscles took a lot of stress from being out in the heat so long.":["더위 속에 오래 계셔서 신장에 부담이 많이 갔어요.","추위 속에 오래 계셔서 근육에 부담이 많이 갔어요."],
"We're keeping a close eye on how much you're urinating.":["소변을 얼마나 보시는지 잘 기록하고 있어요.","수분을 얼마나 드시는지 잘 지켜보고 있어요."],
"The bloodwork will tell us how much muscle damage there is.":["소변검사로 근육 손상이 얼마나 되는지 알 수 있을 거예요.","혈액검사로 신장 손상이 얼마나 되는지 알 수 있을 거예요."],
"Cold hearts are irritable — handle him as gently as possible.":["차가운 심장은 예민하니 모니터를 최대한 자주 보세요.","차가운 손은 예민하니 최대한 부드럽게 다루세요."],
"Keep rewarming while we watch this rhythm closely.":["이 리듬을 계속 지켜보면서 기록을 계속하세요.","이 리듬을 계속 지켜보면서 수액을 확인하세요."],
"Avoid unnecessary movement so we don't trigger a worse arrhythmia.":["더 심한 부정맥을 확인하게 모니터는 계속 켜 두세요.","더 심한 부정맥을 유발하지 않게 불필요한 소음은 줄이세요."],
"His rhythm changed the moment we shifted his position.":["산소를 연결한 순간 리듬이 바뀌었어요.","자세를 바꾼 순간 맥박이 바뀌었어요."],
"Let's minimize how much we touch him right now.":["지금은 최대한 적게 말하도록 할게요.","지금은 최대한 자주 확인하도록 할게요."],
"Continue rewarming, and page cardiology if the rhythm worsens.":["재가온을 계속하고, 리듬이 나빠지면 심전도를 출력하세요.","재가온을 계속하고, 리듬이 나빠지면 순환기내과에 연락할 준비를 하세요."],
"Found down in a hot warehouse, unknown duration.":["더운 차 안에서 쓰러진 채 발견됐고, 지속 시간은 불명입니다.","더운 창고에서 쓰러진 채 발견됐고, 발견 시간은 불명입니다."],
"Core temp was forty-one on scene and hasn't come down much.":["현장에서 맥박이 140이었고 아직 별로 안 내려갔습니다.","현장에서 심부 체온이 41도였고 이송 중 별로 안 내려갔습니다."],
"We started cooling and two large-bore IVs en route.":["이송 중에 모니터를 붙이고 큰 정맥주사 두 개를 확보했습니다.","이송 중에 냉각을 시작하고 피검사 두 번을 확보했습니다."],
"He's hyperthermic and his temp kept climbing during transport.":["고체온 상태였고 이송 중 맥박이 계속 올랐습니다.","고체온 상태였고 현장에서 체온이 계속 올랐습니다."],
"We're handing off a critical heat emergency, so let's move fast.":["위중한 온열질환자를 인계하니 정확하게 움직입시다.","위중한 온열질환자를 인계하니 조용히 움직입시다."],
"Vitals and access are stable, and he's ready for the resus bay.":["활력징후와 정맥로는 확인했고, 소생실로 들어갈 준비가 됐습니다.","활력징후와 정맥로는 안정적이고, 소생실에서 만나기로 했습니다."],
}
WKO={"w-faint":["메스꺼워 토할 듯한","추워서 덜덜 떨리는"],"w-sip":["벌컥 마시기","한 잔"],"w-bring":["(~ up) 올리다","(체온을) 재다"],
"w-temp":["(심장) 맥박","호흡수"],"w-lab":["영상검사","약물치료"],"w-surgery":["내과","정형외과"],"w-dangerously":["조금씩 천천히","점차적으로"]}
WEN={"w-temperature":["temperament","pressure"],"w-adult":["infant","elder"],"w-electrolyte":["electrode","electricity"],
"w-stroke":["heat rash","heat cramps"],"w-hypothermic":["hyperthermic","hypovolemic"],"w-arrest":["rhythm","attack"],"w-enzyme":["insulin","antibody"]}
B={"He's not dead until he's warm and dead — keep resuscitating.":["documenting","transferring","communicating"],
"Keep him horizontal and avoid rough handling during the resuscitation.":["documentation","transportation","communication"]}
run('er-environmental',S,WKO,WEN,B)
