import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_five import go
S = {
"How long did the shaking last?": ["떨림이 어디서 시작됐나요?", "소리가 얼마나 오래 지속됐나요?"],
"Was his whole body shaking or just one side?": ["온몸이 떨렸나요, 아니면 한 번만 떨렸나요?", "온몸이 아팠나요, 아니면 한쪽만 아팠나요?"],
"How was he right after it stopped?": ["시작 직후에는 어땠나요?", "멈춘 하루 뒤에는 어땠나요?"],
"Did he bite his tongue during it?": ["그동안 입술을 깨물었나요?", "그 전에 혀를 깨물었나요?"],
"Was he confused or sleepy afterward?": ["그 후에 혼란스러워하거나 배고파했나요?", "그 전에 혼란스러워하거나 졸려했나요?"],
"Did he recognize you when he woke up?": ["깨어났을 때 간호사를 알아봤나요?", "잠들기 전에 당신을 알아봤나요?"],
"Can you open your eyes for me?": ["입을 열어 보세요.", "눈을 비벼 보시겠어요?"],
"Do you know where you are right now?": ["지금 여기가 몇 시인지 아시겠어요?", "지금 누가 왔는지 아시겠어요?"],
"Squeeze my fingers as hard as you can.": ["제 손가락을 최대한 천천히 쥐어보세요.", "제 손가락을 최대한 오래 쥐어보세요."],
"Can you tell me today's date?": ["오늘 요일을 말씀해 주시겠어요?", "어제 날짜를 말씀해 주시겠어요?"],
"Follow my finger with your eyes.": ["눈으로 제 펜을 따라가 보세요.", "손으로 제 손가락을 따라가 보세요."],
"Does this hurt when I press here?": ["여기를 누르면 가려운가요?", "여기를 만지면 아픈가요?"],
"I'm checking your blood sugar right now.": ["지금 혈당을 설명하고 있어요.", "어제 혈당을 확인했어요."],
"When did you last eat something?": ["마지막으로 뭔가 드신 게 어디서였나요?", "마지막으로 뭔가 마신 게 언제였나요?"],
"Do you take insulin or any diabetes pills?": ["인슐린이나 당뇨약을 샀나요?", "인슐린이나 당뇨약을 언제 드시나요?"],
"Your blood sugar is very low right now.": ["지금 혈당이 매우 불규칙해요.", "지금 맥박이 매우 낮아요."],
"I'm giving you sugar through your IV.": ["정맥주사로 포도당을 고르고 있어요.", "정맥주사로 포도당 안내문을 드리고 있어요."],
"You'll feel better once your sugar goes up.": ["혈당이 오르면 좀 졸리실 거예요.", "수액이 끝나면 좀 나아지실 거예요."],
"Never hold him down or put anything in his mouth.": ["절대 그를 누르거나 침대 위에 뭘 놓지 마세요.", "절대 그를 부르거나 입안에 뭘 넣지 마세요."],
"We turn him on his side to protect his airway.": ["체온을 맞추려고 그를 옆으로 돌려 눕혀요.", "기도를 보호하려고 그를 담요로 덮어 눕혀요."],
"Just clear the area so he doesn't get hurt.": ["다치지 않게 주변만 닦아 주세요.", "다치지 않게 소리만 줄여 주세요."],
"Don't put your fingers in his mouth.": ["귀에 손가락을 넣지 마세요.", "코에 손가락을 넣지 마세요."],
"Clear away anything sharp near him.": ["그의 주변에 있는 가벼운 물건을 치우세요.", "아이의 주변에 있는 날카로운 물건을 치우세요."],
"This position keeps his airway open.": ["이 자세가 맥박을 느리게 둡니다.", "이 자세가 시야를 열어 둡니다."],
"How long have you had seizures?": ["발작을 어디서 겪으셨나요?", "두통을 얼마나 오래 겪으셨나요?"],
"What medications do you take for them?": ["그것 때문에 누가 약을 주시나요?", "그것 때문에 언제 약을 드시나요?"],
"When did you last take your medication?": ["마지막으로 약을 드신 게 어디서였나요?", "처음으로 약을 드신 게 언제였나요?"],
"Have you ever stopped taking them on your own?": ["임의로 약을 바꾼 적이 있나요?", "임의로 약을 나눈 적이 있나요?"],
"Do you know why you stopped?": ["언제 끊었는지 아세요?", "누가 끊었는지 아시나요?"],
"Are these seizures getting more frequent?": ["발작이 점점 더 길어지고 있나요?", "발작이 점점 더 약해지고 있나요?"],
"Do you feel any warning signs before a seizure?": ["발작 후에 경고 증상을 느끼시나요?", "발작 전에 경고 문자를 받으시나요?"],
"Have you been sleeping and eating normally?": ["잠도 잘 주무시고 운동도 정상적으로 하셨나요?", "잠도 잘 주무시고 출근도 정상적으로 하셨나요?"],
"Any recent illness, alcohol, or new medications?": ["최근에 아팠거나, 술을 드셨거나, 새 일을 하셨나요?", "최근에 아팠거나, 커피를 드셨거나, 새 약을 드셨나요?"],
"We'll do tests to find out why this happened.": ["왜 이런 일이 일어났는지 알아보려고 상담을 할게요.", "언제 이런 일이 일어났는지 알아보려고 검사를 할게요."],
"Did you use any new drugs recently?": ["최근에 새로운 운동을 시작하셨나요?", "가족이 최근에 새로운 약물을 사용했나요?"],
"We need a brain scan to look for a cause.": ["원인을 찾기 위해 뇌 스캔이 늦어요.", "원인을 찾기 위해 뇌 스캔이 두 번 필요해요."],
"This can happen without any obvious reason.": ["뚜렷한 소리 없이도 이런 일이 생길 수 있어요.", "뚜렷한 이유 없이도 이런 일이 어릴 때만 생겨요."],
"You're in the emergency room; you had a seizure.": ["여기는 수술실이에요. 발작을 하셨어요.", "여기는 응급실이에요. 사고를 당하셨어요."],
"Can you tell me your name and today's date?": ["이름과 생일을 말씀해 주시겠어요?", "이름과 어제 날짜를 말씀해 주시겠어요?"],
"It's okay, this confusion will clear up soon.": ["괜찮아요, 이 두통은 곧 풀릴 거예요.", "괜찮아요, 이 혼란은 곧 잊힐 거예요."],
"You're safe here; nothing bad is happening.": ["여긴 조용해요. 나쁜 일은 일어나지 않아요.", "여긴 안전해요. 새로운 일은 일어나지 않아요."],
"You had a seizure, and now you're in the hospital.": ["발작을 하셨고, 지금은 집에 계세요.", "기절을 하셨고, 지금은 병원에 계세요."],
"I'll ask you the same questions again in a few minutes.": ["몇 분 후에 다른 질문을 다시 드릴게요.", "몇 분 후에 같은 질문을 간호사에게 드릴게요."],
"How long have you been off your medication?": ["약을 받으신 지 얼마나 됐나요?", "술을 끊으신 지 얼마나 됐나요?"],
"We'll check your medication level in your blood.": ["혈중 약물 농도를 비교할게요.", "혈중 약물 농도를 곧 알려 드릴게요."],
"Stopping suddenly can trigger seizures like this.": ["갑자기 끊으면 이런 졸음이 유발될 수 있어요.", "갑자기 끊으면 이런 발진이 유발될 수 있어요."],
"Did you run out of your pills?": ["약이 다 쏟아졌나요?", "약값이 다 떨어졌나요?"],
"Please don't stop your medication on your own.": ["임의로 약을 팔지 말아 주세요.", "임의로 병원을 옮기지 말아 주세요."],
"We need to restart your seizure medication today.": ["오늘부터 항경련제를 다시 포장해야 해요.", "오늘부터 항경련제 보관법을 다시 알려야 해요."],
"When was your very last drink?": ["마지막으로 술을 드신 게 정확히 어디서였나요?", "마지막으로 물을 드신 게 정확히 언제였나요?"],
"How much do you usually drink in a day?": ["하루에 보통 어디서 드시나요?", "일주일에 보통 얼마나 드시나요?"],
"Are you having sweats, tremors, or seeing things?": ["땀이 나거나, 떨리거나, 가렵거나 하나요?", "땀이 나거나, 어지럽거나, 헛것이 보이나요?"],
"How many days has it been since you stopped drinking?": ["술을 사신 지 며칠 됐나요?", "약을 끊으신 지 며칠 됐나요?"],
"Your hands look like they're shaking a lot.": ["발이 많이 떨리고 있는 것 같아요.", "손이 많이 붓고 있는 것 같아요."],
"We're giving you medication to prevent worse withdrawal.": ["금단 증상이 심해지지 않게 물을 드릴게요.", "금단 증상이 심해지지 않게 약 이름을 알려 드릴게요."],
"Febrile seizures are frightening but usually harmless.": ["열성 두통은 무섭지만 대개 무해해요.", "열성 경련은 슬프지만 대개 무해해요."],
"She's breathing well now and starting to recover.": ["지금은 숨도 잘 쉬고 잠들기 시작했어요.", "지금은 눈도 잘 뜨고 회복되기 시작했어요."],
"Let's focus on bringing her fever down.": ["우선 열을 재는 데 집중해요.", "우선 아이를 안정시키는 데 집중해요."],
"I know this looked very scary.": ["정말 오래 걸렸을 거예요, 알아요.", "정말 슬프게 보였을 거예요, 알아요."],
"Most children outgrow febrile seizures completely.": ["대부분의 어른들은 열성 경련을 완전히 벗어나요.", "대부분의 아이들은 열성 경련을 하룻밤에 벗어나요."],
"We're giving medicine to bring the fever down safely.": ["열을 안전하게 내리도록 물을 드릴게요.", "열을 안전하게 내리도록 약을 받아 올게요."],
"How many weeks pregnant are you?": ["임신 몇 번째이신가요?", "임신한 지 며칠 되셨나요?"],
"Have you had swelling in your face or hands?": ["얼굴이나 손이 떨렸나요?", "얼굴이나 손이 가려웠나요?"],
"We're checking your blood pressure and calling OB.": ["혈압을 확인하고 소아과에 연락할게요.", "혈압을 확인하고 가족에게 연락할게요."],
"Have you had a bad headache today?": ["어제 심한 두통이 있었나요?", "오늘 심한 복통이 있었나요?"],
"Are you seeing any spots or blurry vision?": ["점이 보이거나 냄새가 이상한가요?", "점이 보이거나 귀가 먹먹한가요?"],
"We're getting the baby's heart rate on the monitor too.": ["아기 심박수도 모니터로 들을게요.", "아기 심박수도 화면으로 보여 드릴게요."],
"Did you feel lightheaded before you passed out?": ["기절하기 전에 메스꺼웠나요?", "기절한 뒤에 어지러웠나요?"],
"How quickly did you recover afterward?": ["그 후 얼마나 오래 누우셨나요?", "그 후 얼마나 빨리 병원에 오셨나요?"],
"Did anyone see stiffening or shaking?": ["몸이 뻣뻣해지거나 소리치는 걸 본 사람이 있나요?", "몸이 뻣뻣해지거나 떠는 걸 본 의사가 있나요?"],
"Did your heart feel like it was racing beforehand?": ["그 후에 심장이 빨리 뛰는 느낌이 있었나요?", "그전에 심장이 빨리 뛰는 소리가 들렸나요?"],
"Were you standing up for a long time beforehand?": ["그전에 오래 앉았나요?", "그전에 오래 걷고 계셨나요?"],
"Were you confused afterward, or did you wake up clearheaded?": ["그 후 혼란스러웠나요, 아니면 바로 잠이 들었나요?", "그 전에 혼란스러웠나요, 아니면 바로 정신이 맑았나요?"],
"How much water do you drink each day?": ["하루에 물을 언제 드시나요?", "하루에 차를 얼마나 드시나요?"],
"Any recent vomiting or diarrhea?": ["최근에 구토나 변비가 있었나요?", "어릴 때 구토나 설사가 있었나요?"],
"We're checking your electrolytes right now.": ["지금 전해질을 정리하고 있어요.", "어제 전해질을 확인했어요."],
"Do you drink much more water than usual?": ["평소보다 커피를 훨씬 많이 드시나요?", "평소보다 물을 훨씬 빨리 드시나요?"],
"Your sodium level is dangerously low right now.": ["지금 나트륨 수치가 위험할 정도로 흔들려요.", "지금 혈압이 위험할 정도로 낮아요."],
"We'll raise your sodium slowly and carefully.": ["나트륨을 천천히, 신중하게 확인할게요.", "나트륨을 천천히, 조용하게 올릴게요."],
"What did he take, and how much?": ["무엇을, 언제 드셨나요?", "누가, 얼마나 드셨나요?"],
"His pupils are pinpoint and breathing is slow.": ["동공이 바늘구멍만하고 맥박이 느려요.", "동공이 접시만하고 호흡이 느려요."],
"We're giving naloxone right now.": ["지금 날록손을 찾아볼게요.", "지금 날록손을 가져올게요."],
"Did you find any pill bottles nearby?": ["근처에서 지갑을 발견했나요?", "어제 근처에서 약병을 발견했나요?"],
"We're checking if he needs a breathing tube.": ["호흡 튜브가 어디 있는지 확인할게요.", "호흡 튜브가 필요한지 물어볼게요."],
"His breathing should improve within a few minutes.": ["몇 분 안에 호흡을 다시 들어 볼 거예요.", "몇 분 안에 가족이 도착할 거예요."],
"Seizure before — point to how many times.": ["이전 발작—몇 번인지 손가락으로 세어 주세요.", "이전 발작—몇 시인지 손가락으로 가리켜 주세요."],
"Medicine — do you take it? Yes or no?": ["약—받으셨나요? 네, 아니요?", "술—드시나요? 네, 아니요?"],
"I'm getting an interpreter for you.": ["의사를 불러 드릴게요.", "보호자를 불러 드릴게요."],
"Can you show me on your fingers?": ["손바닥으로 보여주시겠어요?", "손가락으로 그려 주시겠어요?"],
"Nod your head if you understand me.": ["이해하시면 손을 흔들어 주세요.", "필요하시면 고개를 끄덕여 주세요."],
"The interpreter will help us talk about your medicine.": ["통역사가 식사에 대해 이야기하는 걸 도와줄 거예요.", "의사가 약에 대해 이야기하는 걸 도와줄 거예요."],
"This is a prolonged seizure and it's an emergency.": ["이건 갑작스러운 발작이고 응급 상황이에요.", "이건 야간 발작이고 응급 상황이에요."],
"We're giving medication to stop it now.": ["지금 멈추기 위해 약을 고를게요.", "지금 멈추기 위해 약을 챙길게요."],
"We're protecting his airway and giving oxygen.": ["기도를 보호하고 조명을 켜고 있어요.", "기도를 보호하고 침대를 올리고 있어요."],
"This has been going on for more than five minutes.": ["15분 넘게 계속되고 있어요.", "5일 넘게 계속되고 있어요."],
"We need to give a medication to stop this seizure.": ["이 발작을 멈출 약을 알아봐야 해요.", "이 발작을 멈출 약을 챙겨야 해요."],
"We're placing a mask to help him breathe.": ["호흡을 돕기 위해 마스크를 닦고 있어요.", "호흡을 돕기 위해 담요를 덮고 있어요."],
"We're suctioning and repositioning your airway.": ["흡인하고 침대 위치를 다시 잡고 있어요.", "흡인하고 기도 위치를 천천히 보고 있어요."],
"Oxygen saturation is dropping — bag-mask now.": ["산소포화도가 떨어지고 있어요—보호자께 지금.", "산소포화도가 떨어지고 있어요—원무과에 지금."],
"Preparing for intubation to protect the airway.": ["기도 보호를 위해 삽관을 연습하고 있어요.", "체온 유지를 위해 삽관을 준비하고 있어요."],
"His oxygen level is very low right now.": ["지금 산소 수치가 매우 불안정해요.", "지금 맥박 수치가 매우 낮아요."],
"We're bagging him to help him breathe.": ["호흡을 돕기 위해 백을 점검하고 있어요.", "호흡을 돕기 위해 백을 가져오고 있어요."],
"Get the intubation tray ready right now.": ["지금 바로 삽관 트레이를 옮겨 주세요.", "지금 바로 삽관 트레이를 정리해 주세요."],
"We're giving IV dextrose to raise your sugar.": ["혈압을 올리려고 정맥으로 포도당을 드리고 있어요.", "혈당을 올리려고 정맥으로 포도당을 가져오고 있어요."],
"Tell me your name once you can hear me.": ["제 말이 들리면 손을 들어 주세요.", "제 말이 들리면 나이를 말해 주세요."],
"We'll recheck your sugar to make sure it stays up.": ["체온이 유지되는지 다시 확인할게요.", "혈당이 유지되는지 다시 물어볼게요."],
"Your blood sugar was very low when you arrived.": ["도착했을 때 혈압이 매우 낮았어요.", "도착하기 전에 혈당이 매우 낮았어요."],
"You should start waking up soon.": ["곧 배가 고프기 시작하실 거예요.", "내일 정신이 들기 시작하실 거예요."],
"We're watching for your sugar dropping again.": ["혈당이 다시 떨어지는지 말하고 있어요.", "혈압이 다시 떨어지는지 지켜보고 있어요."],
"Can you lift your left arm at all?": ["왼팔을 조금이라도 흔들어 보시겠어요?", "왼팔을 천천히 들어보시겠어요?"],
"Is the weakness getting better or staying the same?": ["저린 게 나아지고 있나요, 그대로인가요?", "어지러운 게 나아지고 있나요, 그대로인가요?"],
"We need a scan to rule out a stroke.": ["뇌졸중을 배제하려면 스캔이 오래 걸려요.", "뇌졸중을 설명하려면 스캔이 필요해요."],
"Can you squeeze my hand with your left hand?": ["왼손으로 제 팔을 쥐어보시겠어요?", "왼손으로 제 손을 두드려 보시겠어요?"],
"If this is from the seizure, the weakness usually improves within a day or two.": ["발작 때문이라면 이 약화는 대개 한 달 안에 나아져요.", "약 때문이라면 이 약화는 대개 하루 이틀 안에 나아져요."],
"Even if it's improving, we still need to rule out a stroke.": ["좋아지고 있어도 뇌졸중은 꼭 기억해야 해요.", "좋아지고 있으니 뇌졸중은 꼭 배제해야 해요."],
"GCS was 8 on arrival, now improved to 12.": ["도착 시 GCS 8점이었고, 지금은 10점으로 좋아졌습니다.", "도착 시 GCS 6점이었고, 지금은 12점으로 좋아졌습니다."],
"He received 4mg lorazepam and IV dextrose.": ["로라제팜 4mg과 정맥 포도당을 준비했습니다.", "로라제팜 4mg과 정맥 포도당을 보관했습니다."],
"Last glucose was 90; airway is currently stable.": ["마지막 혈당은 90이었고, 맥박은 현재 안정적입니다.", "첫 혈당은 90이었고, 기도는 현재 안정적입니다."],
"Seizure lasted about six minutes before he arrived.": ["도착 후 발작이 약 6분간 지속됐습니다.", "도착 전 발작이 약 6시간 지속됐습니다."],
"No further seizure activity since arrival.": ["도착 이후 추가 구토는 없습니다.", "도착 이후 추가 낙상은 없습니다."],
"Please recheck his glucose in one hour.": ["30분 후에 혈당을 다시 확인해 주세요.", "한 시간 후에 혈당을 다시 말해 주세요."],
"We found several empty bottles — checking what they were.": ["빈 약병 여러 개를 발견해서 누구 것인지 확인 중이에요.", "빈 물병 여러 개를 발견해서 무엇이었는지 확인 중이에요."],
"Monitoring your breathing and heart rhythm closely.": ["호흡과 심장 리듬을 면밀히 그리고 있어요.", "호흡과 체온을 면밀히 관찰하고 있어요."],
"We're screening for toxins and supporting you.": ["독소를 선별검사하면서 가족을 안내하고 있어요.", "독소를 정리하면서 지지 치료를 하고 있어요."],
"We don't know exactly what he took.": ["정확히 언제 드셨는지는 몰라요.", "정확히 누가 드렸는지는 몰라요."],
"His heart rhythm looks abnormal on the monitor.": ["모니터상 호흡 리듬이 비정상적으로 보여요.", "체크리스트상 심장 리듬이 비정상적으로 보여요."],
"We'll keep supporting him until we know more.": ["아침이 될 때까지 계속 지지 치료를 할게요.", "더 알아낼 때까지 계속 가족을 안내할게요."],
}
W = {
"w-oxygen": {"en": ["nitrogen", "hydrogen"]},
"w-reposition": {"ko": ["자리를 교체하다", "소유를 되찾다"]},
"w-bag": {"ko": ["심하게 구역질을 하다", "가볍게 두드려 주다"]},
"w-dextrose": {"en": ["dextran", "dexterous"]},
}
B = {
"Were you confused afterward, or did you wake up clearheaded?": ["overheated", "breathless", "unconscious"],
"This is a prolonged seizure and it's an emergency.": ["nighttime", "familiar", "scheduled"],
}
if __name__ == "__main__":
    go("er-seizure-loc", S, W, B)
