from dk_lib import run
S={
"When did the shortness of breath start?":["호흡곤란이 어디서 시작됐나요?","기침이 언제 시작됐나요?"],
"Is it worse when you lie down or when you move?":["앉으면 더 힘든가요, 아니면 움직이면 더 힘든가요?","누우면 더 힘든가요, 아니면 걸으면 더 힘든가요?"],
"Do you have any cough, fever, or chest pain with it?":["기침이나 열, 복통도 같이 있나요?","기침이나 구토, 가슴 통증도 같이 있나요?"],
"Are you having trouble breathing right now?":["지금 삼키기 힘드신가요?","지금 걷기 힘드신가요?"],
"Does sitting up help you breathe?":["앉으면 가슴이 좀 편해지나요?","서면 숨쉬기가 좀 편해지나요?"],
"This clip measures the oxygen level in your blood.":["이 밴드가 혈중 산소 수치를 재는 거예요.","이 집게가 혈중 산소 수치를 기록하는 거예요."],
"I'm counting how many breaths you take per minute.":["1분 동안 몇 번 뛰는지 세고 있어요.","1분 동안 몇 번 기침하는지 세고 있어요."],
"This won't hurt at all.":["이건 전혀 오래 걸리지 않아요.","이건 전혀 차갑지 않아요."],
"If it's low, we'll give you a little oxygen.":["수치가 낮으면 의사에게 알려 드릴게요.","수치가 낮으면 다시 한 번 재 볼게요."],
"Your oxygen level looks okay right now.":["지금 맥박은 괜찮아 보이네요.","지금 체온은 괜찮아 보이네요."],
"The prongs go just inside your nose, gently.":["고정줄이 귀 뒤로 살짝 걸려요.","튜브가 코 아래로 살짝 지나가요."],
"I'm starting the oxygen at a low flow for now.":["지금은 낮은 유량으로 산소를 확인할게요.","지금은 낮은 유량으로 산소를 설명해 드릴게요."],
"Can you breathe through your nose okay?":["입으로 숨 쉬는 건 괜찮으세요?","코로 냄새 맡는 건 괜찮으세요?"],
"Let me know if it feels too dry or tickly.":["너무 건조하거나 따가우면 알려 주세요.","너무 답답하거나 간질거리면 알려 주세요."],
"I'll adjust it if it's too tight.":["너무 뜨거우면 조절해 드릴게요.","너무 간지러우면 조절해 드릴게요."],
"You're safe — let's slow your breathing down together.":["안전해요 — 같이 천천히 눈을 감아봐요.","안전해요 — 같이 천천히 어깨를 내려봐요."],
"Breathe in for four, and out slowly for four with me.":["다섯을 세며 들이쉬고, 다섯을 세며 천천히 내쉬어요, 저랑 같이.","넷을 세며 들이쉬고, 넷을 세며 천천히 내쉬어요, 눈 감고."],
"Let's breathe in together, nice and slow.":["저랑 같이 천천히, 편안하게 앉아봐요.","저랑 같이 천천히, 편안하게 세어봐요."],
"The tingling will ease as your breathing settles.":["어지러움은 숨이 안정되면서 나아질 거예요.","저림은 몸이 따뜻해지면서 나아질 거예요."],
"You're doing great — just keep breathing with me.":["잘하고 계세요 — 계속 저를 보고 숨 쉬어요.","거의 다 됐어요 — 계속 저랑 같이 숨 쉬어요."],
"How high has your fever been?":["열이 얼마나 오래됐나요?","기침이 얼마나 심했나요?"],
"Is the cough bringing anything up?":["기침할 때 어디가 아픈가요?","재채기할 때 뭔가 나오나요?"],
"Have you had a fever at home?":["어제도 열이 있었나요?","집에서도 오한이 있었나요?"],
"Does your throat hurt or feel swollen?":["목이 아프거나 가려운 느낌이 있나요?","코가 막히거나 부은 느낌이 있나요?"],
"Does the cough make it hard to breathe?":["기침 때문에 잠자기가 힘든가요?","열 때문에 숨쉬기가 힘든가요?"],
"Let's sit you upright to help you breathe.":["숨쉬기 편하게 창문을 열어 드릴게요.","숨쉬기 편하게 단추를 풀어 드릴게요."],
"The pink, frothy cough worries me about fluid in your lungs.":["분홍빛 거품 섞인 기침이 걱정돼요, 폐렴인 것 같아서요.","분홍빛 거품 섞인 기침이 걱정돼요, 폐에 염증이 생긴 것 같아서요."],
"I'm listening to your lungs and getting oxygen on you.":["폐 소리를 듣고 혈압도 재 드리고 있어요.","심장 소리를 듣고 산소도 넣어드리고 있어요."],
"Try not to lie flat right now.":["지금은 마스크를 벗지 않도록 해요.","지금은 말을 많이 하지 않도록 해요."],
"Have you coughed up anything pink or frothy before?":["어제도 분홍빛이나 거품 있는 기침을 하셨나요?","전에도 노란빛이나 거품 있는 기침을 하신 적 있나요?"],
"What color is the phlegm you're coughing up?":["기침에서 나온 가래는 양이 얼마나 돼요?","기침에서 나온 가래는 무슨 냄새예요?"],
"Does it hurt to take a deep breath?":["숨을 깊이 쉬면 어지러운가요?","기침을 깊이 하면 아픈가요?"],
"Have you had a fever with this cough?":["이 기침과 함께 오한도 있었나요?","이 기침과 함께 땀도 났나요?"],
"Your oxygen is a bit low, so we'll give you some.":["산소가 약간 낮아서 다시 재 볼게요.","산소가 약간 낮아서 알려 드릴게요."],
"We'll get your oxygen back up.":["산소 수치를 다시 알려드릴게요.","맥박 수치를 다시 확인해드릴게요."],
"Did the shortness of breath start suddenly?":["호흡곤란이 아침에 시작됐나요?","가슴통증이 갑자기 시작됐나요?"],
"Is one of your legs more swollen or painful?":["한쪽 팔이 더 붓거나 아픈가요?","한쪽 다리가 더 차갑거나 아픈가요?"],
"Have you traveled far or been immobile recently?":["최근에 멀리 다녀오셨거나 수술을 받으셨나요?","최근에 이사하셨거나 오래 움직이지 못하셨나요?"],
"Does your chest hurt when you breathe in?":["숨을 내쉴 때 가슴이 아픈가요?","숨을 들이쉴 때 어깨가 아픈가요?"],
"Point to where your leg feels swollen.":["다리가 아픈 곳을 가리켜 주세요.","팔이 부은 곳을 가리켜 주세요."],
"This mask pushes air in to help you breathe easier.":["이 마스크가 공기를 데워서 숨쉬기를 도와줘요.","이 마스크가 공기를 밀어넣어서 잠자기를 도와줘요."],
"I'll hold it gently first so you can get used to it.":["먼저 마스크를 보여드릴 테니 익숙해지시면 돼요.","먼저 살살 대드릴 테니 불편하면 말씀하세요."],
"Try to breathe with the machine — it works with you.":["기계와 같이 숨 쉬어보세요 — 기계가 알려줘요.","저와 같이 숨 쉬어보세요 — 기계가 맞춰줘요."],
"It will feel tight around your face at first.":["처음엔 얼굴 주변이 시원한 느낌이 들 거예요.","처음엔 코 주변이 꽉 조이는 느낌이 들 거예요."],
"This helps your lungs rest.":["이게 몸을 좀 쉬게 해줄 거예요.","이게 폐를 좀 열어 줄 거예요."],
"Your oxygen is lower than we'd like, even though you feel okay.":["느낌은 괜찮으셔도 맥박 수치는 원하는 만큼 안 나와요.","아프지는 않으셔도 산소 수치는 원하는 만큼 안 나와요."],
"Let me recheck it and watch you take a few breaths.":["다시 확인하면서 기침 몇 번 하시는 걸 볼게요.","다시 확인하면서 맥박 몇 번 뛰는 걸 볼게요."],
"You don't feel short of breath, but your numbers are low.":["아픈 느낌은 없으셔도 수치는 낮아요.","숨찬 느낌은 없으셔도 맥박은 빨라요."],
"We'll give oxygen and keep a close eye on you.":["산소를 확인하고 계속 가까이서 지켜볼게요.","의사에게 알리고 계속 가까이서 지켜볼게요."],
"This clip will show your oxygen level again.":["이 집게로 맥박 수치를 다시 보여드릴게요.","이 밴드로 산소 수치를 다시 보여드릴게요."],
"I'm listening to both sides of your chest to compare.":["양쪽 가슴 모양을 비교하려고 보고 있어요.","양쪽 등 소리를 비교하려고 듣고 있어요."],
"Did the tightness come on suddenly or gradually?":["조이는 느낌이 아침에 왔나요, 아니면 점차 왔나요?","찌르는 느낌이 갑자기 왔나요, 아니면 점차 왔나요?"],
"Point to exactly where it feels tight.":["아픈 곳을 정확히 가리켜 주세요.","조이는 곳을 천천히 가리켜 주세요."],
"Can you take a deep breath for me?":["기침을 한 번 해봐 주시겠어요?","숨을 깊게 한 번 참아봐 주시겠어요?"],
"Does it hurt more on one side?":["한쪽이 더 붓나요?","한쪽이 더 저린가요?"],
"Chest pain? Yes or no?":["가슴 두근거림? 예, 아니오?","복부 통증? 예, 아니오?"],
"Choking feeling? Point to your throat, yes or no?":["질식할 것 같은 느낌? 가슴을 가리켜 보세요, 예, 아니오?","어지러운 느낌? 목을 가리켜 보세요, 예, 아니오?"],
"Allergy to medicine? An interpreter is on the way.":["약물 알레르기? 의사가 오고 있어요.","음식 알레르기? 통역사가 오고 있어요."],
"Can you nod yes or shake your head no?":["예면 눈을 깜빡이고, 아니면 좌우로 흔들어 주세요.","예면 고개를 끄덕이고, 아니면 손가락을 흔들어 주세요."],
"We'll keep you safe until the interpreter arrives.":["보호자가 올 때까지 안전하게 지켜드릴게요.","통역사가 올 때까지 편안하게 지켜드릴게요."],
"Has your cough gotten weaker over the past few days?":["지난 몇 주 사이 기침이 더 약해졌나요?","지난 며칠 사이 목소리가 더 약해졌나요?"],
"Are you having trouble swallowing or clearing your throat?":["말하기 힘들거나 목에 낀 가래를 뱉어 내기 힘든가요?","삼키기 힘들거나 입에 고인 침을 뱉어 내기 힘든가요?"],
"Does food or water ever go down the wrong way?":["음식이나 약을 먹다가 사레가 들리는 일이 있나요?","음식이나 물을 먹다가 체하는 일이 있나요?"],
"We need to watch your breathing muscles closely.":["호흡수를 가까이서 지켜봐야 해요.","삼킴 근육을 가까이서 지켜봐야 해요."],
"Let's check your strength again today.":["오늘 열도 다시 확인해볼게요.","오늘 목소리도 다시 확인해볼게요."],
"For you, too much oxygen can actually be harmful.":["환자분께는 소금이 너무 많아도 오히려 해로울 수 있어요.","환자분께는 약이 너무 많아도 오히려 해로울 수 있어요."],
"We aim for a target range, not the highest number.":["가장 높은 수치가 아니라 목표 범위를 기록하는 거예요.","가장 높은 수치가 아니라 목표 범위를 알려 드리는 거예요."],
"I'll adjust it carefully to keep you in the safe zone.":["안전한 범위 안에 있도록 조심스럽게 확인할게요.","안전한 범위 안에 있도록 조심스럽게 기록할게요."],
"Turning it all the way up isn't safe for you.":["마스크를 끝까지 조이는 건 환자분께 안전하지 않아요.","수액을 끝까지 올리는 건 환자분께 안전하지 않아요."],
"I'll check your levels and adjust as needed.":["수치를 확인하고 필요하면 알려 드릴게요.","수치를 확인하고 필요하면 기록할게요."],
"Your oxygen and lung exam look reassuring.":["산소 수치도 폐 진찰 소견도 다시 볼게요.","산소 수치도 폐 진찰 소견도 설명해 드릴게요."],
"Your heart and lungs sound normal to me.":["심장과 폐 소리를 다시 들어볼게요.","심장과 폐 사진을 먼저 찍어볼게요."],
"Does this happen when you feel stressed or anxious?":["스트레스받거나 운동할 때 이런 증상이 나타나나요?","스트레스받거나 불안할 때 이런 통증이 나타나나요?"],
"Let's slow your breathing and see if it eases.":["숨을 천천히 쉬면서 어지러운지 봐요.","손을 따뜻하게 하면서 나아지는지 봐요."],
"It's okay to feel anxious — you're safe here.":["무서워도 괜찮아요 — 여긴 안전해요.","불안해도 괜찮아요 — 저도 여기 있어요."],
"That high-pitched sound worries me about your airway.":["그 높은 숨소리 때문에 폐가 걱정돼요.","그 갈라진 목소리 때문에 기도가 걱정돼요."],
"Are you able to swallow right now?":["지금 말씀하실 수 있으세요?","지금 팔을 올릴 수 있으세요?"],
"I'm calling for airway help right now — stay calm.":["기도 도움을 지금 부를게요 — 천천히 숨 쉬세요.","의사 도움을 지금 부를게요 — 침착하게 계세요."],
"We're keeping you upright and getting oxygen ready.":["곧게 앉혀드리고 모니터도 준비하고 있어요.","곧게 앉혀드리고 수액도 준비하고 있어요."],
"Try to stay still and let us help you.":["편하게 계시고 저희가 돕게 해주세요.","가만히 계시고 보호자가 돕게 해주세요."],
"Suction is on, blade and tube are ready.":["흡인 준비됐고, 후두경 날과 모니터도 준비됐습니다.","산소 준비됐고, 후두경 날과 튜브도 준비됐습니다."],
"Induction and paralytic drawn up and labeled.":["유도제와 근이완제 뽑아서 카트에 두었습니다.","유도제와 근이완제 뽑아서 시간 적었습니다."],
"Airway cart is at the bedside.":["산소 탱크는 침상 옆에 있습니다.","흡인기는 침상 옆에 있습니다."],
"Sats are 98, we're good to go — go ahead.":["산소포화도 98, 알람도 켰습니다 — 시작하세요.","산소포화도 98, 진행해도 좋습니다 — 기록합니다."],
"I'll call it out step by step.":["단계별로 기록하겠습니다.","단계별로 보고하겠습니다."],
"He's not responding to oxygen — sats keep falling.":["산소에 반응이 없습니다 — 맥박이 계속 떨어지고 있습니다.","수액에 반응이 없습니다 — 수치가 계속 떨어지고 있습니다."],
"His oxygen level dropped fast just now.":["혈압 수치가 방금 급격히 떨어졌습니다.","산소 수치가 아까 급격히 떨어졌습니다."],
"We need to move toward intubation now.":["지금 삽관 도구를 점검해야 합니다.","지금 삽관 팀을 확인해야 합니다."],
"I'm calling the team and preparing the airway.":["팀을 부르고 약을 준비하고 있습니다.","가족을 부르고 기도를 준비하고 있습니다."],
"Let's get anesthesia on the line.":["중환자실에 바로 연락하겠습니다.","약국에 바로 연락하겠습니다."],
"Give IM epinephrine now per protocol — her airway is closing.":["프로토콜대로 지금 모니터를 연결해 주세요 — 기도가 막히고 있습니다.","프로토콜대로 지금 두 번째 라인을 잡아 주세요 — 기도가 막히고 있습니다."],
"Her lips are swelling fast.":["손이 빠르게 부어오르고 있습니다.","입술이 빠르게 붉어지고 있습니다."],
"Call for the difficult airway cart and ENT.":["어려운 기도 카트와 방사선과 불러주세요.","어려운 기도 카트와 약제과 불러주세요."],
"Have a surgical airway kit open at the bedside.":["외과적 기도 세트를 카트에 올려 두세요.","흡인 장비 세트를 침상에 열어 두세요."],
"Get epinephrine ready to give again if needed.":["필요하면 다시 줄 수 있게 시간 기록해 두세요.","필요하면 다시 쓸 수 있게 흡인기를 준비해 두세요."],
"Run through DOPE — displacement, obstruction, pneumothorax, equipment.":["DOPE로 기록하겠습니다 — 위치 이탈, 폐쇄, 기흉, 장비.","DOPE로 설명하겠습니다 — 위치 이탈, 폐쇄, 기흉, 장비."],
"Displacement first — is the tube still in place?":["위치부터요 — 튜브에 김이 서려 있나요?","위치부터요 — 카프가 제자리에 그대로 있나요?"],
"Check the tube position and suction for a plug.":["튜브 위치를 확인하고 막힌 곳이 있는지 소리 들어보세요.","튜브 고정을 확인하고 막힌 곳이 있는지 흡인해보세요."],
"Listen for equal breath sounds and check the ventilator.":["양쪽 호흡음이 같은지 듣고 모니터도 확인해주세요.","양쪽 가슴 움직임이 같은지 보고 인공호흡기도 확인해주세요."],
"Sats are climbing again.":["산소포화도를 다시 확인하고 있습니다.","산소포화도를 다시 기록하고 있습니다."],
"Suction continuously to keep the airway clear.":["기도를 확보하려고 계속 산소를 주세요.","기도를 확보하려고 계속 알려주세요."],
"He's bleeding a lot — suction again.":["출혈이 많습니다 — 다시 확인하세요.","기침이 많습니다 — 다시 흡인하세요."],
"Position him with the bleeding side down.":["출혈 양을 컵 눈금으로 재어 주세요.","출혈 시각을 시계 보고 적어 주세요."],
"Protect the good lung on top.":["건강한 폐 소리를 계속 들으며 보호해주세요.","건강한 폐 쪽 가슴 움직임을 보며 확인해주세요."],
"Prepare to intubate and call for help now.":["삽관 준비하고 지금 흡인기를 확인하세요.","삽관 준비하고 지금 혈액형을 확인하세요."],
"I'm suctioning your trach to clear any blockage.":["막힌 곳을 찾으려고 기관절개관을 흡인하고 있어요.","막힌 곳을 없애려고 기관절개관을 살펴보고 있어요."],
"Let me check if air is moving through it.":["공기가 새는지 제가 확인해 볼게요.","소리가 나는지 제가 확인해 볼게요."],
"If it's out of place, we'll change the tube right away.":["제자리에서 빠졌으면 바로 의사에게 알릴게요.","제자리에서 빠졌으면 바로 산소를 연결할게요."],
"Try to stay calm — we're giving you oxygen now.":["침착하게 계세요 — 지금 도움을 부르고 있어요.","침착하게 계세요 — 지금 모니터를 보고 있어요."],
"We'll have a new tube ready in a moment.":["새 마스크를 잠시 후 준비해 드릴게요.","새 튜브를 잠시 후 확인해 드릴게요."],
}
WKO={"w-breath":["(가로) 폭","출생"],"w-prong":["(병) 마개","(검사) 탐침"],"w-listen":["(눈이) 반짝이다","(수치를) 줄이다"],
"w-clear":["(문을) 닫다","(뚜껑을) 덮다"],"w-sound":["두드리다","(줄을) 묶다"],"w-stay":["길을 벗어나다","(~처럼) 흔들리다"],
"w-blade":["스타일렛","(소변) 방광"],"w-drawn":["(음식을) 토해 내다","(우물이) 바짝 마르다"],"w-sats":["(조사) 통계 수치","(검사) 세트 구성"],
"w-line":["(도로) 차선","(과일) 라임"],"w-run":["문지르다","(일을) 망치다"],"w-plug":["(전염) 역병","민달팽이"]}
WEN={"w-ease":["erase","cease"],"w-flat":["prone","slanted"]}
B={"Call for the difficult airway cart and ENT.":["lab","OB","PT"],
"Suction continuously to keep the airway clear.":["occasionally","reluctantly","temporarily"]}
run('er-dyspnea',S,WKO,WEN,B)
