import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"When did the pain first start today?":("어제 통증이 언제 처음 시작됐나요?","오늘 통증이 어디서 처음 시작됐나요?"),
"Can you show me where it hurts the most?":("가장 아픈 때가 언제인지 말씀해 주시겠어요?","가장 아픈 곳이 어디인지 적어 주시겠어요?"),
"Does the pain move or spread anywhere else?":("통증이 다른 곳으로 옮겨가거나 심해지나요?","통증이 다른 곳으로 옮겨가거나 가라앉나요?"),
"I need to know exactly when the pain began.":("통증이 정확히 어디서 시작됐는지 알아야 해요.","통증이 정확히 언제 끝났는지 알아야 해요."),
"Tell me if the pain spreads to your back or chest.":("통증이 등이나 가슴으로 퍼지면 적어 주세요.","통증이 등이나 팔로 퍼지면 말씀해 주세요."),
"On a scale of zero to ten, how bad is the pain right now?":("0에서 10까지 중에서, 지금 통증이 얼마나 오래됐나요?","0에서 5까지 중에서, 지금 통증이 얼마나 심한가요?"),
"When was the last time you ate or drank anything?":("마지막으로 뭔가 먹거나 마신 게 무엇이었나요?","마지막으로 약을 먹거나 마신 게 언제였나요?"),
"I'm going to check your blood pressure and temperature.":("혈압과 맥박을 확인할게요.","혈당과 체온을 확인할게요."),
"Is the pain any worse than it was an hour ago?":("하루 전보다 통증이 더 심해졌나요?","한 시간 전보다 통증이 더 넓어졌나요?"),
"Have you had anything to eat or drink today?":("어제 뭐라도 먹거나 마신 게 있나요?","오늘 뭐라도 먹거나 토한 게 있나요?"),
"Can you point to exactly where it hurts the most?":("가장 아픈 곳을 정확히 그려 주시겠어요?","가장 아픈 때를 정확히 말씀해 주시겠어요?"),
"Does it hurt more when I press or when I let go?":("누를 때와 걸을 때 중 언제 더 아픈가요?","앉을 때와 뗄 때 중 언제 더 아픈가요?"),
"When did you last eat or drink anything?":("마지막으로 누구와 뭔가 먹거나 마셨나요?","마지막으로 언제 약을 먹거나 마셨나요?"),
"Tell me if you feel sick or have a fever.":("어지럽거나 열이 나면 말씀해 주세요.","메스껍거나 기침이 나면 말씀해 주세요."),
"We may need to call the surgeon, so nothing to eat or drink for now.":("마취과 선생님을 부를 수도 있으니, 지금부터 먹지도 마시지도 마세요.","외과 선생님을 부를 수도 있으니, 지금부터 걷지도 일어나지도 마세요."),
"Is the pain more of a burning or a sharp feeling?":("통증이 화끈거리는 느낌인가요, 아니면 묵직한 느낌인가요?","통증이 욱신거리는 느낌인가요, 아니면 날카로운 느낌인가요?"),
"Does it get better or worse after you eat?":("먹고 나면 나아지나요, 아니면 번지나요?","누우면 나아지나요, 아니면 심해지나요?"),
"Have you had any chest pain, sweating, or shortness of breath?":("가슴 통증이나 식은땀, 어지러움이 있었나요?","가슴 통증이나 식은땀, 두근거림이 있었나요?"),
"Do you feel dizzy or short of breath right now?":("지금 어지럽거나 열이 있나요?","아까 어지럽거나 숨이 찼나요?"),
"Tell me what you ate before the pain started.":("통증이 시작된 뒤에 뭘 드셨는지 말씀해 주세요.","통증이 시작되기 전에 뭘 하셨는지 말씀해 주세요."),
"When was your last bowel movement?":("마지막 식사가 언제였나요?","마지막 배뇨가 언제였나요?"),
"Have you been drinking and eating normally lately?":("최근에 평소처럼 마시고 주무셨나요?","최근에 평소보다 마시고 드셨나요?"),
"Are you passing any gas at all?":("소변은 조금이라도 나오나요?","가스는 조금이라도 차 있나요?"),
"What have you been eating and drinking this week?":("이번 달에 뭘 드시고 마셨나요?","이번 주에 뭘 드시고 약을 드셨나요?"),
"Does your belly feel swollen or tight?":("배가 붓거나 쓰린 느낌이 있나요?","다리가 붓거나 팽팽한 느낌이 있나요?"),
"Did the pain start after a fatty or heavy meal?":("기름지거나 과한 운동 후에 통증이 시작됐나요?","기름지거나 과한 식사 전에 통증이 시작됐나요?"),
"Does it hurt when I press here as you breathe in?":("숨을 내쉴 때 여기를 누르면 아픈가요?","숨을 들이쉴 때 여기를 누르면 어지러운가요?"),
"Does the pain spread to your back or right shoulder?":("통증이 등이나 왼쪽 어깨로 퍼지나요?","통증이 등이나 오른쪽 팔로 퍼지나요?"),
"Have you had a fever or felt short of breath with this pain?":("이 통증과 함께 열이 나거나 토한 적이 있나요?","이 통증과 함께 오한이 나거나 숨이 찬 적이 있나요?"),
"We'll need an ultrasound, so please don't eat anything for now.":("CT 촬영이 필요하니, 지금은 아무것도 드시지 마세요.","초음파 검사가 필요하니, 지금은 아무 데도 가지 마세요."),
"Does the pain go through to your back?":("통증이 어깨까지 관통하듯 뻗치나요?","통증이 옆구리까지 관통하듯 뻗치나요?"),
"How much alcohol have you been drinking recently?":("최근에 술을 얼마나 오래 드셨나요?","최근에 술을 어디서 드셨나요?"),
"We'll need to keep you from eating or drinking for now.":("지금은 걷거나 일어나지 못하게 해야 해요.","지금은 씻거나 옷 갈아입지 못하게 해야 해요."),
"When did this pain start, and had you been drinking before that?":("이 통증은 어디서 시작됐고, 그 전에 술을 드셨나요?","이 통증은 언제 시작됐고, 그 전에 약을 드셨나요?"),
"We're starting IV fluids and medicine to control your pain.":("통증을 조절하기 위해 수액과 산소를 시작할게요.","통증을 조절하기 위해 수액과 약을 설명할게요."),
"Is the pain low on your left side?":("통증이 오른쪽 아래쪽에 있나요?","통증이 왼쪽 위쪽에 있나요?"),
"Have you had any fever, chills, or change in your stools?":("열이나 오한, 소변에 변화가 있었나요?","열이나 두통, 대변에 변화가 있었나요?"),
"You may need to drink a contrast liquid before the CT scan.":("X선 촬영 전에 조영제 액체를 드셔야 할 수도 있어요.","CT 촬영 전에 설명서를 읽어야 할 수도 있어요."),
"Does it hurt more when you move or cough?":("움직이거나 숨 쉴 때 더 아픈가요?","웃거나 기침할 때 더 아픈가요?"),
"The scan will show if the infection has spread.":("촬영을 하면 출혈이 있는지 알 수 있어요.","촬영을 하면 결석이 있는지 알 수 있어요."),
"Have you had any abdominal surgeries in the past?":("과거에 흉부 수술을 받으신 적이 있나요?","과거에 복부 검사를 받으신 적이 있나요?"),
"Are you able to pass gas or have a bowel movement?":("가스를 배출하거나 소변을 볼 수 있나요?","가스를 배출하거나 구토를 할 수 있나요?"),
"We may need to place a tube through your nose to relieve the pressure.":("압력을 확인하기 위해 코로 관을 넣어야 할 수도 있어요.","압력을 완화하기 위해 코로 관을 빼야 할 수도 있어요."),
"Tell me how many times you've vomited today.":("오늘 몇 번이나 드셨는지 말씀해 주세요.","어제 몇 번이나 토하셨는지 말씀해 주세요."),
"Your belly looks swollen and firm right now.":("지금 다리가 붓고 단단해 보여요.","지금 배가 붓고 뜨거워 보여요."),
"Does it hurt when I tap on your back here?":("여기 배를 두드리면 아픈가요?","여기 등을 누르면 아픈가요?"),
"Do you have any burning or pain when you urinate?":("대변볼 때 화끈거리거나 아픈가요?","소변볼 때 가렵거나 아픈가요?"),
"We'll need a urine sample to check for infection.":("감염을 확인하기 위해 혈액 검체가 필요해요.","감염을 확인하기 위해 대변 검체가 필요해요."),
"Have you had a fever or chills with this pain?":("이 통증과 함께 구토나 오한이 있었나요?","이 증상 전에 열이나 오한이 있었나요?"),
"We're sending the urine for a culture as well.":("배양검사를 위해 혈액도 함께 보낼게요.","배양검사를 위해 소변도 함께 가져올게요."),
"When was your last menstrual period?":("마지막 검진이 언제였나요?","마지막 출산이 언제였나요?"),
"Is there any chance you could be pregnant?":("출혈 가능성이 있나요?","임신 계획이 있나요?"),
"We'll do a pregnancy test as part of checking your belly pain.":("두통 검사의 일환으로 임신 검사도 할게요.","복통 검사를 끝낸 뒤 임신 검사도 할게요."),
"Is it possible you missed a period this month?":("지난달에 생리를 거르셨을 가능성이 있나요?","이번 주에 생리를 거르셨을 가능성이 있나요?"),
"The test result will help guide your treatment safely.":("검사 결과가 안전한 퇴원 시간을 정하는 데 도움이 될 거예요.","검사 결과가 안전한 치료 방향을 정하는 데 오래 걸릴 거예요."),
"Have you noticed any vaginal bleeding or spotting?":("코피나 소량출혈이 있었나요?","질 분비물이나 소량출혈이 있었나요?"),
"Do you feel lightheaded or like you might faint?":("어질어질하거나 구토할 것 같은 느낌이 있나요?","어질어질하거나 실신한 적이 있나요?"),
"We need to check right away whether you could be pregnant.":("감염 가능성을 지금 바로 확인해야 해요.","임신 가능성을 지금 바로 설명해야 해요."),
"How long have you felt dizzy or weak?":("얼마나 자주 어지럽거나 힘이 없으셨나요?","얼마나 오래 어지럽거나 열이 있으셨나요?"),
"This needs urgent blood work and an ultrasound right now.":("지금 바로 긴급 혈액검사와 CT 촬영이 필요해요.","지금 바로 긴급 소변검사와 초음파가 필요해요."),
"I'll get an interpreter so we can understand you better.":("의사를 불러서 더 잘 이해할 수 있게 할게요.","통역사를 불러서 더 잘 설명할 수 있게 할게요."),
"Can you point to where it hurts the most?":("가장 아픈 곳을 그려 주시겠어요?","가장 아픈 곳을 써 주시겠어요?"),
"Please nod yes or shake your head no.":("맞으면 눈을 깜박이고 아니면 저어 주세요.","맞으면 고개를 끄덕이고 아니면 손을 흔들어 주세요."),
"Show me with your hand exactly where it hurts.":("손으로 정확히 어디가 가려운지 보여주세요.","손으로 정확히 어디가 아픈지 써 주세요."),
"Tell the interpreter if anything feels new or different.":("새롭거나 다르게 느껴지는 게 있으면 간호사에게 말씀해 주세요.","새롭거나 다르게 느껴지는 게 있으면 통역사에게 적어 주세요."),
"I want to understand your pain so we can help you safely.":("통증을 이해해서 빠르게 도와드리고 싶어요.","통증을 기록해서 안전하게 도와드리고 싶어요."),
"What medications have you taken for this already?":("이걸 위해 이미 어떤 병원을 가셨나요?","이걸 위해 언제 약을 드셨나요?"),
"We'll assess you fully before deciding on treatment.":("퇴원을 정하기 전에 충분히 사정할게요.","치료를 정하기 전에 충분히 설명할게요."),
"Tell me honestly what has helped your pain before.":("전에 무엇이 통증을 심하게 했는지 솔직하게 말씀해 주세요.","전에 무엇이 통증에 도움이 됐는지 자세히 말씀해 주세요."),
"We're not judging you, we just want to keep you safe.":("판단하려는 게 아니라, 그저 편하게 해드리고 싶은 거예요.","판단하려는 게 아니라, 그저 안전하게 알려드리고 싶은 거예요."),
"Sometimes serious problems can feel mild, so I want to check carefully.":("때로는 심각한 문제도 가볍게 느껴질 수 있어서, 천천히 설명하고 싶어요.","때로는 심각한 문제도 가볍게 느껴질 수 있어서, 신중히 기록하고 싶어요."),
"Have you had any nausea, weakness, or dizziness?":("메스꺼움이나 가려움, 어지러움이 있었나요?","메스꺼움이나 힘없음, 두통이 있었나요?"),
"Let me recheck your vital signs to be safe.":("안전을 위해 활력징후를 두 번 다시 확인할게요.","편의를 위해 활력징후를 다시 확인할게요."),
"Even a little pain can be a serious problem for you.":("작은 통증이라도 오래된 문제일 수 있어요.","작은 변화라도 심각한 문제일 수 있어요."),
"A small change in your vital signs matters a lot here.":("체중의 작은 변화도 여기서는 중요해요.","활력징후의 작은 변화도 지금은 중요해요."),
"Does the pain feel tearing or ripping?":("통증이 쑤시거나 뜯기는 느낌인가요?","통증이 찢어지거나 쥐어짜는 느낌인가요?"),
"We're moving fast because this could be very serious.":("매우 심각할 수 있어서 저희가 조용히 움직이고 있어요.","매우 바쁠 수 있어서 저희가 빠르게 움직이고 있어요."),
"We're calling the surgeon and preparing blood right now.":("마취과 선생님을 부르고 지금 혈액을 준비하고 있어요.","외과 선생님을 부르고 지금 수액을 준비하고 있어요."),
"Have you ever noticed a pulsing lump in your belly?":("배에서 박동하는 통증을 느낀 적이 있나요?","목에서 박동하는 덩어리를 느낀 적이 있나요?"),
"Your blood pressure is low, so we're acting quickly.":("체온이 낮아서 저희가 빠르게 대응하고 있어요.","혈압이 낮아서 저희가 의사에게 보고하고 있어요."),
"Your pain is much worse than what we feel on exam — that concerns us.":("진찰에서 느끼는 것보다 통증이 훨씬 오래됐어요, 그래서 걱정이 돼요.","검사에서 느끼는 것보다 통증이 훨씬 심해요, 그래서 걱정이 돼요."),
"We're drawing a lactate level right away.":("지금 바로 혈당 수치를 채혈할게요.","지금 바로 젖산 수치를 설명할게요."),
"You'll need an urgent CT scan of your belly.":("배 부위의 긴급 초음파 촬영이 필요해요.","배 부위의 긴급 CT 촬영 동의가 필요해요."),
"The exam feels soft, but your pain is severe.":("진찰상으로는 부드럽지만, 통증은 오래됐어요.","진찰상으로는 부드럽지만, 구토는 심해요."),
"We're moving quickly to find the cause of this pain.":("이 통증의 원인을 빠르게 설명하고 있어요.","이 구토의 원인을 빠르게 찾고 있어요."),
"Your belly is very rigid, which is a serious sign.":("배가 아주 뜨거워요, 이건 심각한 징후예요.","배가 아주 딱딱해요, 이건 오래된 징후예요."),
"We're going to keep you still and comfortable to reduce the pain.":("구역질을 줄이기 위해 편한 자세로 가만히 계시게 할게요.","통증을 줄이기 위해 편한 베개로 가만히 계시게 할게요."),
"We're calling the surgeon right now to come see you.":("지금 바로 마취과 선생님이 와서 봐 주시도록 연락하고 있어요.","지금 바로 외과 선생님이 와서 가족을 봐 주시도록 연락하고 있어요."),
"The team needs to operate as soon as possible.":("팀이 최대한 빨리 설명해야 해요.","팀이 최대한 빨리 이송해야 해요."),
"Have you noticed your skin or eyes turning yellow?":("피부나 눈이 빨갛게 변한 걸 알아차리셨나요?","피부나 손톱이 노랗게 변한 걸 알아차리셨나요?"),
"You have a fever and right-sided pain that we take seriously.":("열과 왼쪽 통증이 있어서 저희가 심각하게 받아들이고 있어요.","열과 오한이 있어서 저희가 심각하게 받아들이고 있어요."),
"You may need a procedure called ERCP to drain the bile duct.":("담관을 확인하기 위해 ERCP라는 시술이 필요할 수도 있어요.","담관을 배액하기 위해 MRI라는 검사가 필요할 수도 있어요."),
"Does your pain sit mostly on your right side, under the ribs?":("통증이 주로 왼쪽, 갈비뼈 아래쪽에 있나요?","통증이 주로 오른쪽, 갈비뼈 위쪽에 있나요?"),
"We'll start antibiotics right away to treat the infection.":("감염을 치료하기 위해 지금 바로 수액을 시작할게요.","감염을 치료하기 위해 지금 바로 항생제를 설명할게요."),
"Your blood pressure has dropped, so we're acting quickly.":("체온이 떨어져서 저희가 빠르게 대응하고 있어요.","혈압이 떨어져서 저희가 가족에게 알리고 있어요."),
"Stay with me — I'm calling for the team right now.":("정신 놓지 마세요, 지금 바로 간호사를 부를게요.","숨 참지 마세요, 지금 바로 팀을 부를게요."),
"We're starting fluids and oxygen immediately.":("즉시 수액과 산소를 설명할게요.","즉시 수액과 심전도를 시작할게요."),
"Tell me right away if you feel any worse.":("조금이라도 더 안 좋아지면 바로 적어 주세요.","조금이라도 더 안 좋아지면 바로 의사에게 말씀해 주세요."),
"The team is starting fluids to bring your pressure back up.":("팀이 혈압을 다시 끌어올리기 위해 수액을 확인하고 있어요.","팀이 체온을 다시 끌어올리기 위해 수액을 시작하고 있어요."),
"We're doing a quick ultrasound of your belly called a FAST exam.":("배에 빠른 초음파, 즉 FAST 검사를 설명할게요.","배에 빠른 엑스레이, 즉 FAST 검사를 할게요."),
"Tell me where you hurt the most from the crash.":("사고로 언제부터 가장 아픈지 말씀해 주세요.","사고로 어디가 가장 아픈지 적어 주세요."),
"We're getting blood ready in case you need a transfusion.":("수술이 필요할 경우를 대비해 혈액을 준비하고 있어요.","수혈이 필요할 경우를 대비해 수액을 준비하고 있어요."),
"Your blood pressure and pulse tell us how serious this is.":("혈압과 체온을 보면 얼마나 심각한지 알 수 있어요.","혈압과 맥박을 보면 얼마나 오래됐는지 알 수 있어요."),
"The trauma team is here to help you right now.":("외과팀이 지금 바로 도와드리러 왔어요.","외상팀이 지금 바로 설명드리러 왔어요."),
}
W={'w-temperature':(None,['temperament','temperate']),'w-ultrasound':(None,['ultraviolet','radiograph']),'w-comfortable':(None,['considerable','comparable'])}
B={"What medications have you taken for this already?":('medications',['photographs','vacations','appointments']),
"We're going to keep you still and comfortable to reduce the pain.":('comfortable',['embarrassed','responsible','knowledgeable'])}
apply('er-abdominal',S,W,B)
