from dk_lib import run
S={
"When did the fever start, and how high has it gotten?":["통증이 언제 시작됐고, 얼마나 심해졌나요?","열이 언제 시작됐고, 얼마나 자주 올랐나요?"],
"Do you have a cough, sore throat, burning urine, or any pain?":["기침, 콧물, 소변 화끈거림, 또는 다른 통증이 있나요?","기침, 목 아픔, 설사, 또는 다른 통증이 있나요?"],
"Has anything made it better or worse?":["뭔가 나아지게 하거나 나빠지게 한 음식이 있었나요?","뭔가 나아지게 하거나 나빠지게 한 장소가 있었나요?"],
"Did you check your temperature at home before you came in?":["오시기 전에 집에서 혈압을 재보셨어요?","오시기 전에 직장에서 체온을 재보셨어요?"],
"Did you take any medicine to bring the fever down?":["열을 내리려고 얼음을 쓰셨나요?","통증을 줄이려고 약을 드셨나요?"],
"Let me check your temperature, pulse, and breathing first.":["체온, 맥박, 혈압을 먼저 확인할게요.","체온, 맥박, 호흡을 먼저 설명할게요."],
"I'll ask about a few common sources of infection.":["감염의 흔한 증상 몇 가지를 여쭤볼게요.","감염의 흔한 원인 몇 가지를 설명드릴게요."],
"Any pain when you pee, cough, or a wound anywhere?":["소변볼 때, 삼킬 때, 또는 어디든 상처에 통증이 있나요?","소변볼 때, 기침할 때, 또는 어디든 상처에 열감이 있나요?"],
"Your pulse is a little fast, but your breathing sounds fine.":["맥박이 조금 빠르지만, 체온은 다시 재 볼게요.","맥박이 조금 빠르지만, 혈압은 다시 재 볼게요."],
"We'll look for signs of infection in your urine, skin, or lungs.":["소변, 피부, 또는 목에서 감염의 징후를 찾아볼게요.","소변, 피부, 또는 폐에서 감염의 원인을 찾아볼게요."],
"Because of the cough and fever, I'll have you wear a mask.":["기침과 열이 있으니 손을 씻으시도록 할게요.","기침과 구토가 있으니 마스크를 써 주시도록 할게요."],
"We may place you in a separate room to protect others.":["다른 분들을 보호하려고 별도의 대기실로 옮길 수도 있어요.","다른 분들을 보호하려고 별도의 마스크를 드릴 수도 있어요."],
"Have you been around anyone sick or traveled recently?":["최근에 아픈 사람 곁에 있었거나 입원하셨나요?","최근에 아픈 동물 곁에 있었거나 여행하셨나요?"],
"How long have you had this cough, and is it getting worse?":["이 기침이 얼마나 오래됐고, 밤에 더 심한가요?","이 두통이 얼마나 오래됐고, 점점 심해지고 있나요?"],
"I know the mask feels uncomfortable, but it helps keep everyone safe.":["마스크가 불편하신 거 알지만, 곧 병실로 안내해 드릴게요.","마스크가 불편하신 거 알지만, 의사 선생님이 곧 오실 거예요."],
"This will help lower your fever and make you more comfortable.":["이 약이 통증을 줄이고 더 편안하게 해드릴 거예요.","이 약이 열을 낮추고 땀이 나게 해드릴 거예요."],
"We'll recheck your temperature in about an hour.":["한 시간쯤 후에 혈압을 다시 재볼게요.","한 시간쯤 후에 맥박을 다시 재볼게요."],
"Keep drinking fluids — that helps too.":["충분히 쉬세요 — 그것도 도움이 돼요.","옷을 가볍게 입으세요 — 그것도 도움이 돼요."],
"This medicine will bring your fever down within an hour or so.":["이 약은 한 시간쯤 안에 통증을 줄여줄 거예요.","이 약은 한 시간쯤 안에 땀을 줄여줄 거예요."],
"If your fever goes back up before then, please let us know.":["그 전에 통증이 다시 오면 저희에게 알려주세요.","그 후에 열이 다시 오르면 저희에게 알려주세요."],
"Where did you travel, and when did you get back?":["어디로 여행하셨고, 누구와 가셨어요?","어디서 일하셨고, 언제 돌아오셨어요?"],
"Did you get any bug bites or eat anything unusual?":["벌레에 물리거나 특이한 걸 보신 적 있나요?","동물에 물리거나 특이한 걸 드신 적 있나요?"],
"Was anyone you traveled with also sick?":["함께 사시는 분 중에 아픈 사람이 있었나요?","함께 여행하신 분 중에 다친 사람이 있었나요?"],
"Which countries or cities did you visit on this trip?":["이번 여행에서 어느 호텔이나 도시를 방문하셨어요?","이번 여행에서 어느 나라나 섬을 방문하셨어요?"],
"We'll check for infections that travelers sometimes bring back from abroad.":["여행자가 해외에서 가끔 가져오는 감염을 설명해드릴게요.","여행자가 국내에서 가끔 걸리는 감염을 확인해볼게요."],
"Your cough and shortness of breath make us think of pneumonia.":["기침과 숨가쁨을 보면 천식이 떠올라요.","기침과 가슴 통증을 보면 폐렴이 떠올라요."],
"We'll get a chest X-ray and check your oxygen level.":["흉부 엑스레이를 찍고 체온을 확인할게요.","복부 엑스레이를 찍고 산소 수치를 확인할게요."],
"If it's pneumonia, we'll start antibiotics promptly.":["폐렴이라면 바로 의사에게 알릴게요.","폐렴이라면 바로 가래 검사를 할게요."],
"How many days have you had this deep cough and fever?":["이렇게 깊은 기침과 열이 몇 주나 됐나요?","이렇게 깊은 기침과 통증이 며칠이나 됐나요?"],
"We're also checking your blood to see how serious this infection is.":["이 감염이 얼마나 심각한지 보려고 소변도 확인하고 있어요.","이 감염이 얼마나 오래된지 보려고 혈액도 확인하고 있어요."],
"In older adults, a urine infection can show up as confusion.":["노인분들은 요로감염이 낙상으로 나타날 수 있어요.","아이들은 요로감염이 혼돈으로 나타날 수 있어요."],
"We'll check her urine and blood to look for infection.":["감염을 찾아보려고 소변과 가래를 확인할게요.","탈수를 찾아보려고 소변과 혈액을 확인할게요."],
"Has she had any change in urination or new incontinence?":["배변에 변화가 있거나 새로 요실금이 생겼나요?","배뇨에 변화가 있거나 새로 통증이 생겼나요?"],
"Has she seemed more confused than usual, or is this new for her?":["평소보다 더 졸려 보이셨나요, 아니면 처음 있는 일인가요?","평소보다 더 혼란스러워 보이셨나요, 아니면 자주 있는 일인가요?"],
"Confusion in her age group is often the first sign of a urine infection.":["이 연령대에서는 어지러움이 흔히 요로감염의 첫 징후예요.","이 연령대에서는 혼돈이 흔히 탈수의 첫 징후예요."],
"I'm marking the edge of the redness to see if it spreads.":["발적이 퍼지는지 보려고 사진을 찍고 있어요.","붓기가 퍼지는지 보려고 경계를 표시하고 있어요."],
"The fever means the infection may be spreading, so we'll treat it.":["열이 있는 걸 보면 감염이 퍼지고 있을 수 있어서 검사할게요.","통증이 있는 걸 보면 감염이 퍼지고 있을 수 있어서 치료할게요."],
"Tell me if the pain suddenly gets much worse than it looks.":["통증이 겉보기보다 갑자기 훨씬 심해지면 바로 올게요.","통증이 겉보기보다 갑자기 훨씬 심해지면 약을 더 드릴게요."],
"I'll draw a line around the redness so we can watch if it grows.":["커지는지 지켜보려고 발적 주변을 사진으로 남길게요.","줄어드는지 지켜보려고 발적 주변에 선을 그을게요."],
"We'll start antibiotics now to keep the infection from spreading further.":["감염이 더 퍼지지 않게 지금 다리를 올려 둘게요.","감염이 더 퍼지지 않게 지금 상처를 덮어 둘게요."],
"We'll swab you to check for the flu.":["독감 검사를 위해 소변검사를 할게요.","독감 검사를 위해 면봉을 보여 드릴게요."],
"If it's positive and it's early, an antiviral may help.":["양성이고 초기라면 휴식이 도움이 될 수 있어요.","양성이고 초기라면 따뜻한 물이 도움이 될 수 있어요."],
"Please keep the mask on to protect others while you're here.":["여기 계시는 동안 다른 분들을 보호하도록 손소독을 자주 해 주세요.","여기 계시는 동안 다른 분들을 보호하도록 휴지를 계속 써 주세요."],
"Everyone at your work having the flu makes this very likely.":["가족들이 다 독감이라면 독감일 가능성이 아주 커요.","직장 동료들이 다 독감이라면 감염일 가능성이 아주 커요."],
"The antiviral works best if we start it within the first two days.":["항바이러스제는 처음 이틀 안에 시작하면 처방 확인이 필요해요.","항바이러스제는 처음 이틀 안에 시작하면 약사가 설명해 드려요."],
"With chemo, a fever is an emergency, so we act fast.":["항암치료 중이면 발열은 응급상황이라 저희가 빠르게 확인해요.","방사선치료 중이면 발열은 응급상황이라 저희가 빠르게 움직여요."],
"We're drawing cultures and starting antibiotics quickly.":["배양검사를 채취하고 활력징후를 신속히 확인하고 있어요.","배양검사를 채취하고 정맥 라인을 신속히 잡고 있어요."],
"We'll keep you protected from other infections while you're here.":["여기 계시는 동안 편안하게 쉬시게 해 드릴게요.","여기 계시는 동안 담당 간호사를 알려 드릴게요."],
"Even a mild fever like this can turn serious very quickly for you.":["이런 가벼운 열도 아주 빠르게 올라갈 수 있어요.","이런 가벼운 기침도 아주 빠르게 심각해질 수 있어요."],
"Your nurse was right to send you in immediately.":["간호사분이 바로 전화하라고 한 게 맞았어요.","의사분이 바로 오시라고 한 게 맞았어요."],
"We'll bring the fever down and keep him comfortable.":["열을 재고 편안하게 해드릴게요.","열을 내리고 안아서 달래 드릴게요."],
"Most fever seizures are brief and don't cause lasting harm.":["대부분의 열성경련은 짧고 어린 나이에 생겨요.","대부분의 열성경련은 짧고 열이 오를 때 생겨요."],
"Keep offering fluids, and let me know if he becomes hard to wake.":["옷을 가볍게 입혀 주시고, 깨우기 힘들어지면 알려주세요.","수분을 계속 권해 주시고, 열이 오르면 알려주세요."],
"Seizures like this look scary, but they usually stop on their own within a few minutes.":["이런 경련은 무서워 보이지만 보통 열이 오를 때 생겨요.","이런 울음은 무서워 보이지만 보통 몇 분 안에 저절로 멈춰요."],
"Give him small sips of fluid every few minutes to keep him hydrated.":["탈수되지 않게 몇 분마다 조금씩 체온을 재세요.","탈수되지 않게 몇 시간마다 조금씩 수분을 드리세요."],
"The new medication makes me wonder if the rash is a drug reaction.":["새로 드신 약 때문에 이 발진이 감염은 아닌지 궁금해요.","새로 바른 약 때문에 이 발진이 약물 반응은 아닌지 궁금해요."],
"We'll look at how it's spreading and whether it blisters.":["어떻게 퍼지는지, 가려운지 살펴볼게요.","어디서 퍼지는지, 물집이 잡히는지 살펴볼게요."],
"Do you have any mouth sores or eye irritation?":["입안에 궤양이나 목에 자극이 있나요?","코안에 궤양이나 눈에 자극이 있나요?"],
"Did the rash start before or after you began the new medication?":["발진이 새 음식을 드시기 전에 났나요, 후에 났나요?","열이 새 약을 드시기 전에 났나요, 후에 났나요?"],
"Let's watch closely for blisters or peeling skin over the next few hours.":["앞으로 며칠 동안 물집이나 피부 벗겨짐을 자세히 지켜볼게요.","앞으로 몇 시간 동안 물집이나 가려움을 자세히 지켜볼게요."],
"The stiff neck with fever and headache makes me worried about meningitis.":["뻣뻣한 목에 발열, 두통까지 있으니 감염이 걱정돼요.","뻣뻣한 어깨에 발열, 두통까지 있으니 수막염이 걱정돼요."],
"We'll need a spinal tap to check the fluid around your brain.":["뇌 주변 체액을 확인하려고 뇌 CT가 필요해요.","뇌 주변 압력을 확인하려고 척수천자가 필요해요."],
"Does bright light bother your eyes right now?":["지금 큰 소리가 귀에 거슬리세요?","지금 센 냄새가 코에 거슬리세요?"],
"Can you bring your chin down toward your chest for me?":["턱을 어깨 쪽으로 돌려 보시겠어요?","무릎을 가슴 쪽으로 올려 보시겠어요?"],
"This test tells us if there's an infection around your brain and spine.":["이 검사로 뇌와 척추 주변에 출혈이 있는지 알 수 있어요.","이 검사로 뇌와 신장 주변에 감염이 있는지 알 수 있어요."],
"A long cough with night sweats and weight loss can suggest TB.":["오랜 기침에 밤에 나는 땀, 가슴 통증까지 있으면 결핵을 의심할 수 있어요.","오랜 기침에 밤에 나는 땀, 체중 감소까지 있으면 폐암을 의심할 수 있어요."],
"We'll place you in a special isolation room right away.":["바로 특별 음압격리실 준비를 확인할게요.","바로 특별 음압격리실 안내문을 드릴게요."],
"We'll test your sputum to check for tuberculosis.":["결핵 확인을 위해 피 검사를 할게요.","폐렴 확인을 위해 가래 검사를 할게요."],
"How many weeks have you had this cough and the night sweats?":["이 기침과 밤에 나는 땀이 몇 달이나 됐나요?","이 기침과 체중 감소가 몇 주나 됐나요?"],
"The isolation room keeps the air from spreading TB to others.":["격리실은 결핵 검사 결과를 기다리는 동안에도 계속 사용해요.","격리실은 공기 중으로 감기가 다른 사람에게 퍼지지 않게 막아줘요."],
"Fever after travel to a malaria area needs urgent testing.":["말라리아 지역 여행 후 열이 나면 신속한 기록이 필요해요.","뎅기열 지역 여행 후 열이 나면 신속한 검사가 필요해요."],
"Did you take any malaria prevention pills, and finish them?":["말라리아 예방접종을 받으셨고, 끝까지 다 받으셨나요?","말라리아 예방약을 드셨고, 시간 맞춰 드셨나요?"],
"We'll run a rapid blood test to check for it now.":["지금 신속 소변검사를 해서 확인해볼게요.","지금 신속 혈액검사 결과를 확인해볼게요."],
"When exactly did you get back from that trip?":["그 여행에서 정확히 언제 출발하셨어요?","그 여행에서 정확히 어디 가셨어요?"],
"Malaria can look like the flu at first, so we test to be sure.":["말라리아는 처음엔 감기처럼 보일 수 있어서 확실히 검사해봐요.","말라리아는 처음엔 독감처럼 보일 수 있어서 의사에게 알려요."],
"Neutropenic and now hypotensive — this is septic until proven otherwise.":["호중구감소성인 데다 지금 빈맥까지 — 반증되기 전까진 패혈증이에요.","호중구감소성인 데다 지금 저산소까지 — 반증되기 전까진 패혈증이에요."],
"Cultures are drawn; give broad-spectrum antibiotics within the hour.":["배양검사는 채취됐고, 한 시간 안에 활력징후를 알려 주세요.","배양검사는 채취됐고, 검체 라벨을 바로 확인해 주세요."],
"Febrile neutropenia with sepsis — I need fluids running and a physician now.":["발열성 호중구감소증에 패혈증까지 — 수액을 달고 모니터가 지금 필요해요.","발열성 호중구감소증에 패혈증까지 — 라인을 잡고 의사가 지금 필요해요."],
"Give the first antibiotic dose now — don't wait for the workup.":["첫 활력징후를 지금 확인해 주세요 — 검사 결과를 기다리지 마세요.","첫 소변 검체를 지금 보내 주세요 — 결과를 기다리지 마세요."],
"Pressure's dropping — I need you in here now.":["맥박이 올라가고 있어요 — 지금 와 주셔야 해요.","혈압이 떨어지고 있어요 — 지금 연락해 주셔야 해요."],
"Those purple spots with drowsiness are a dangerous sign — we're acting now.":["저 자주색 반점에 구토까지 있으면 위험한 징후예요 — 지금 바로 움직일게요.","저 자주색 반점에 졸림까지 있으면 위험한 징후예요 — 지금 바로 알려 드릴게요."],
"We're giving antibiotics immediately and starting fluids.":["배양검사를 즉시 확인하고 수액도 시작할게요.","산소를 즉시 드리고 모니터도 시작할게요."],
"We're isolating him and will need to protect close contacts too.":["그를 안정시키고 가까이 접촉한 사람들도 보호해야 해요.","그를 격리하고 가까이 있던 장비도 소독해야 해요."],
"How quickly did the spots spread after they first appeared?":["반점이 처음 나타난 곳이 어디였나요?","반점이 처음 나타난 후 얼마나 가려웠나요?"],
"Anyone who's been close to him will need preventive antibiotics too.":["그와 가까이 지낸 사람은 누구든 명단 작성이 필요해요.","그와 가까이 지낸 사람은 누구든 연락이 필요해요."],
"Pain this severe with a fever makes me worried about a deep infection.":["이렇게 심한 통증에 발열까지 있으면 골절이 걱정돼요.","이렇게 심한 통증에 부종까지 있으면 깊은 감염이 걱정돼요."],
"We're calling surgery urgently to evaluate you.":["긴급히 혈액검사를 해서 평가받게 할게요.","긴급히 외과에 보낼 기록을 정리할게요."],
"We're starting strong antibiotics and fluids right now.":["강한 항생제와 수액 알레르기를 지금 바로 확인할게요.","강한 진통제와 수액을 지금 바로 시작할게요."],
"This pain is much worse than the redness alone would explain.":["이 통증은 열만 봐서는 설명이 안 될 만큼 훨씬 심해요.","이 통증은 발적만 봐서는 설명이 안 될 만큼 계속돼요."],
"The surgery team needs to see this leg right away, before it spreads further.":["외과 팀이 지금 바로 이 다리 사진을 봐야 해요, 더 퍼지기 전에요.","마취과 팀이 지금 바로 이 다리를 봐야 해요, 더 퍼지기 전에요."],
"The rash, fever, and low pressure point to toxic shock.":["발진, 발열, 낮은 혈압이 알레르기를 가리켜요.","발진, 발열, 빠른 맥박이 독성쇼크를 가리켜요."],
"We're pouring in fluids and starting antibiotics now.":["지금 수액을 쏟아붓고 산소도 시작할게요.","지금 모니터를 붙이고 항생제도 시작할게요."],
"Have you had any recent wound, surgery, or been using tampons?":["최근에 상처, 수술, 또는 약 복용이 있었나요?","최근에 상처, 여행, 또는 탐폰 사용이 있었나요?"],
"Dizziness with a rash like this can mean your organs are under stress.":["이런 발진에 구토까지 있으면 장기가 스트레스를 받고 있다는 뜻일 수 있어요.","이런 발진에 어지러움까지 있으면 피부가 스트레스를 받고 있다는 뜻일 수 있어요."],
"We need fluids running fast to bring your pressure back up.":["혈압을 다시 확인하려고 팔 커프를 바꿀게요.","혈압을 다시 올리려고 수액 라인을 하나 더 잡을게요."],
"Your pressure is dropping fast, so we're moving quickly now.":["맥박이 빠르게 올라가고 있어서 저희도 빠르게 움직이고 있어요.","혈압이 빠르게 떨어지고 있어서 저희도 팀을 부르고 있어요."],
"We're giving fluids wide open and antibiotics right away.":["수액을 활짝 열어 놓고 산소도 바로 드릴게요.","수액을 활짝 열어 놓고 배양검사도 바로 채취할게요."],
"Stay with me — I'm getting the team in here.":["저를 봐 주세요 — 팀을 여기로 부를게요.","저와 함께 있어 주세요 — 약을 여기로 가져올게요."],
"An hour ago you looked stable — now everything is changing fast.":["한 시간 전엔 안정적으로 보이셨는데 — 지금은 열이 빠르게 오르고 있어요.","하루 전엔 안정적으로 보이셨는데 — 지금은 모든 게 빠르게 변하고 있어요."],
"We're activating the sepsis bundle and calling the physician right now.":["패혈증 번들을 가동하고 지금 바로 기록도 시작할게요.","패혈증 번들을 설명하고 지금 바로 의사도 부를게요."],
"Suspected meningococcemia — he's on droplet precautions.":["수막구균혈증 의심 — 비말 격리실에 있습니다.","수막염 의심 — 비말 격리 중입니다."],
"Cultures were drawn and first antibiotic dose given at nineteen-hundred.":["배양검사는 채취했고, 첫 항생제 라벨은 19시에 확인했습니다.","소변검사는 채취했고, 첫 항생제는 19시에 투여했습니다."],
"Last pressure eighty-five systolic on fluids — please continue isolation.":["마지막 혈압은 수액 중 수축기 85입니다 — 모니터는 계속 유지해 주세요.","마지막 산소포화도는 수액 중 94입니다 — 격리는 계속 유지해 주세요."],
"He's septic and on precautions — keep him isolated during transport.":["패혈증 상태고 격리 중입니다 — 이송하는 동안 모니터를 유지해 주세요.","패혈증 상태고 격리 중입니다 — 이송하는 동안 연락을 유지해 주세요."],
"Two large-bore IVs are in, and he's had one liter of fluids so far.":["굵은 정맥주사 두 개를 확보했고, 지금까지 항생제 1회를 투여했습니다.","굵은 정맥주사 두 개를 확보했고, 지금까지 소변 500cc가 나왔습니다."],
}
WKO={"w-get":["(상태를) 유지하다","(진행을) 멈추다"],"w-show":["(증상을) 숨기다","(증상이) 사라지다"],"w-draw":["(수액을) 주입하다","(고름을) 배액하다"],
"w-begin":["(약을) 끊다","(약을) 다 먹다"],"w-tb":["뇌손상","에이즈"],"w-tuberculosis":["경화증","결절"],"w-run":["(수액을) 멈추다","(수액을) 빼내다"],
"w-wide":["(수액을) 꽉 잠가 둔","천천히 떨어지게"],"w-ago":["(지금부터) ~ 후","한 번 더 다시"]}
WEN={"w-pain":["panic","itch"],"w-temperature":["temperament","pressure"],"w-uncomfortable":["unconscious","unavailable"],"w-xray":["CT scan","MRI"],
"w-adult":["children","infants"],"w-urination":["urinalysis","hydration"],"w-chemo":["steroid","dialysis"],"w-brief":["lengthy","belief"],"w-test":["treat","text"],
"w-tuberculosis":["tuberculin","tuberosity"],"w-neutropenic":["neurogenic","lymphopenic"],"w-hypotensive":["hypertensive","hypothermic"],
"w-prove":["until prompted otherwise","until further notice"],"w-neutropenia":["lymphopenia","neuropathy"],"w-meningococcemia":["meningococcus","meningococcal"]}
B={"Let me check your temperature, pulse, and breathing first.":["medication","orientation","appearance"],
"This will help lower your fever and make you more comfortable.":["suspicious","impatient","nauseated"],
"Has she had any change in urination or new incontinence?":["constipation","dehydration","hemorrhoids"],
"We'll bring the fever down and keep him comfortable.":["suspicious","impatient","nauseated"],
"Give him small sips of fluid every few minutes to keep him hydrated.":["restless","isolated","distracted"]}
run('er-fever-infection',S,WKO,WEN,B)
