import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"Can you tell me your full name and date of birth?":("성함 전체와 주소를 말씀해 주시겠어요?","성함 전체와 전화번호를 말씀해 주시겠어요?"),
"I'm going to draw a small tube of blood.":("작은 튜브 하나 분량의 혈액을 설명할게요.","작은 튜브 하나 분량의 혈액을 보관할게요."),
"You'll feel a quick pinch, then it's over.":("따끔한 느낌이 잠깐 있고 나면 시작돼요.","따뜻한 느낌이 잠깐 있고 나면 끝나요."),
"Let me double-check your wristband before I start.":("시작하기 전에 손목밴드를 한 번 더 닦을게요.","시작하기 전에 명찰을 한 번 더 확인할게요."),
"I'll compare this with your chart just to be safe.":("안전을 위해 이걸 시계와 대조해 볼게요.","청결을 위해 이걸 차트와 대조해 볼게요."),
"It'll only take a few seconds.":("몇 분밖에 안 걸려요.","몇 초 뒤에 시작해요."),
"This little tube lets us give you fluids and medicine.":("이 작은 바늘로 수액과 약을 드릴 수 있어요.","이 작은 관으로 수액과 약을 설명해 드릴 수 있어요."),
"You'll feel a sharp pinch for just a second.":("오래 날카로운 따끔함이 느껴질 거예요.","잠깐 차가운 느낌이 느껴질 거예요."),
"Try to hold your arm nice and still for me.":("다리를 가만히 잘 고정해 주세요.","팔을 가만히 잘 올려 주세요."),
"I know needles can feel scary, but I'll be quick.":("바늘이 아프게 느껴질 수 있지만 빨리 끝낼게요.","바늘이 무섭게 느껴질 수 있지만 같이 끝낼게요."),
"It's just a small needle to start your IV line.":("정맥주사 관을 보여줄 작은 바늘일 뿐이에요.","정맥주사 관을 넣을 작은 밴드일 뿐이에요."),
"You're doing great — almost done.":("조용히 계세요, 거의 다 됐어요.","잘하고 계세요, 곧 시작이에요."),
"First wipe from front to back with this cloth.":("마지막에 이 수건으로 앞에서 뒤로 닦아 주세요.","먼저 이 수건을 앞에서 뒤로 접어 주세요."),
"Start urinating, then catch the middle part in the cup.":("소변을 보시다가 처음 부분을 컵에 받아 주세요.","소변을 보시다가 중간 부분을 병에 받아 주세요."),
"Leave the sample here and I'll take care of it.":("검체는 여기 두시면 직원이 처리할게요.","검체는 저기 두시면 제가 처리할게요."),
"This helps us test for infection accurately.":("이렇게 하면 혈당 여부를 정확히 검사할 수 있어요.","이렇게 하면 감염 여부를 빠르게 검사할 수 있어요."),
"I'll step out and give you some privacy.":("제가 나가서 문을 닫아드릴게요.","제가 나가서 가족을 불러드릴게요."),
"Just place the cup on the shelf when you're done.":("다 하시면 컵을 선반 아래에 두세요.","다 하시면 컵을 책상 위에 올려 두세요."),
"I'm placing these stickers to check your heart.":("심장을 확인하려고 이 스티커를 뗄게요.","심장을 확인하려고 이 스티커들을 보여드릴게요."),
"It doesn't hurt at all — it just listens.":("전혀 아프지 않아요, 그냥 재기만 하는 거예요.","전혀 가렵지 않아요, 그냥 듣기만 하는 거예요."),
"Please stay still for about ten seconds.":("10분 정도만 가만히 계셔 주세요.","10초 정도만 편하게 계셔 주세요."),
"This test is called an EKG.":("이 검사를 뇌파라고 해요.","이 장비를 심전도라고 해요."),
"Try not to talk while it's recording.":("저장되는 동안은 말씀을 삼가 주세요.","인쇄되는 동안은 말씀을 삼가 주세요."),
"We'll have your results in just a minute.":("결과는 내일 나올 거예요.","결과는 금방 설명할 거예요."),
"These tests help us find what's causing your pain.":("이 검사들로 기침의 원인을 찾을 수 있어요.","이 검사들로 통증의 원인을 설명할 수 있어요."),
"It's a routine step to keep you safe.":("환자분을 안전하게 지키기 위한 특별한 절차예요.","가족분을 안전하게 지키기 위한 일상적인 절차예요."),
"I'll let you know as soon as we have results.":("결과가 나오는 대로 바로 의사에게 알려 드릴게요.","결과가 나오는 대로 내일 알려 드릴게요."),
"I understand waiting for answers is stressful.":("답을 기다리는 게 지루하다는 거 이해해요.","검사를 기다리는 게 스트레스라는 거 이해해요."),
"The doctor will explain everything once we're done.":("다 끝나면 간호사 선생님이 전부 설명해 주실 거예요.","다 끝나면 의사 선생님이 전부 확인해 주실 거예요."),
"You're not alone — we're working on this together.":("혼자가 아니에요, 저희가 함께 기다리고 있어요.","혼자가 아니에요, 가족이 함께 해결하고 있어요."),
"I'm sorry this is taking a few tries.":("몇 분 더 시도하게 돼서 죄송해요.","몇 번 더 시도하게 돼서 감사해요."),
"Your veins are hard to see, so I'll use a warm pack.":("정맥이 잘 안 보여서 베개를 써볼게요.","손이 잘 안 보여서 온찜질팩을 써볼게요."),
"If needed, I'll ask a colleague who's great at this.":("필요하면 이 일에 능숙한 의사에게 부탁할게요.","필요하면 이 일에 능숙한 동료에게 설명할게요."),
"I know this is frustrating, and I appreciate your patience.":("화나실 텐데, 참아주셔서 감사해요.","답답하실 텐데, 도와주셔서 감사해요."),
"Let's take a short break and try again.":("잠깐 쉬었다가 다시 설명해볼게요.","오래 쉬었다가 다시 시도해볼게요."),
"I'll try once more, and then we'll get help.":("한 번만 더 해 보고, 그다음엔 설명을 드릴게요.","한 번만 더 해 보고, 그다음엔 쉴게요."),
"You can hold him on your lap to keep him calm.":("침대에 눕혀 계시면 아이가 진정하는 데 도움이 돼요.","무릎에 안고 계시면 아이가 웃는 데 도움이 돼요."),
"We'll count to three together and it's done.":("함께 열을 세면 바로 끝나요.","함께 셋을 세면 바로 시작해요."),
"A sticker and a big high-five are waiting after.":("끝나면 풍선이랑 하이파이브가 기다리고 있어요.","시작하면 스티커랑 하이파이브가 기다리고 있어요."),
"It should be over before he even notices.":("아마 아이가 눈 뜨기도 전에 끝날 거예요.","아마 아이가 알아차리기도 전에 시작할 거예요."),
"You're doing an amazing job keeping him calm.":("아이를 안아주느라 정말 잘하고 계세요.","아이를 진정시키느라 정말 지치셨어요."),
"He's being so brave right now.":("지금 정말 조용하게 하고 있네요.","어제 정말 용감하게 했네요."),
"Have you ever reacted to contrast dye before?":("예전에 조영제를 맞아 보신 적 있나요?","예전에 조영제에 반응을 보인 가족이 있나요?"),
"Do you have any kidney problems or take metformin?":("신장에 문제가 있으시거나 메트포르민을 사셨나요?","신장에 문제가 있으시거나 가족이 메트포르민을 복용하시나요?"),
"The dye may feel warm — that's normal.":("조영제가 차갑게 느껴질 수 있는데 정상이에요.","조영제가 따뜻하게 느껴질 수 있는데 드물어요."),
"Please tell me about any allergies you have.":("가지고 계신 알레르기가 있으면 보여 주세요.","가지고 계신 알레르기가 있으면 눌러 주세요."),
"This helps us keep your kidneys safe during the scan.":("이렇게 하면 검사 후에 신장을 안전하게 지킬 수 있어요.","이렇게 하면 검사 전에 신장을 안전하게 지킬 수 있어요."),
"That warm feeling passes quickly and it's expected.":("그 차가운 느낌은 금방 지나가고, 예상된 거예요.","그 따뜻한 느낌은 금방 지나가고, 드문 거예요."),
"I need to clean the site really well first.":("나중에 부위를 아주 깨끗이 소독해야 해요.","먼저 부위를 아주 깨끗이 말려야 해요."),
"Please try not to touch the area once it's prepped.":("붕대를 감으면 그 부위를 만지지 말아 주세요.","소독이 끝나면 그 부위를 가리지 말아 주세요."),
"This keeps the sample clean so results are accurate.":("이렇게 하면 검체가 깨끗하게 유지돼서 결과가 빨라져요.","이렇게 하면 검체가 뜨겁게 유지돼서 결과가 정확해져요."),
"Contamination can give us a false result.":("오염되면 늦은 결과가 나올 수 있어요.","오염되면 잘못된 처방이 나올 수 있어요."),
"Just hold still for a moment while I finish.":("제가 끝낼 때까지 잠깐만 편하게 계세요.","의사가 끝낼 때까지 잠깐만 가만히 계세요."),
"We're almost done — thanks for your patience.":("거의 다 됐어요, 도와주셔서 감사해요.","거의 다 됐어요, 와주셔서 감사해요."),
"Have you had this antibiotic before?":("이 항생제를 어제 맞아 보신 적 있나요?","이 병원에서 전에 맞아 보신 적 있나요?"),
"Tell me right away if you feel itchy or short of breath.":("가렵거나 숨이 차면 바로 눌러 주세요.","추우시거나 숨이 차면 바로 말씀해 주세요."),
"I'll be watching you closely during the first dose.":("첫 투여 동안 천천히 지켜볼게요.","첫 투여 전에 세심히 지켜볼게요."),
"Have you ever had an allergic reaction to any medicine?":("음식에 알레르기 반응을 보이신 적 있나요?","약물에 알레르기 반응을 보인 가족이 있나요?"),
"Press your call button if anything feels wrong.":("뭔가 이상하면 호출 버튼을 보세요.","뭔가 빠지면 호출 버튼을 눌러 주세요."),
"I'll check on you again in a few minutes.":("몇 분 후에 다시 설명하러 올게요.","몇 분 후에 의사가 다시 확인하러 올게요."),
"Two of us will double-check your name and blood type.":("두 사람이 이름과 침대 번호를 이중 확인할 거예요.","두 사람이 이름과 혈액형을 이중 설명할 거예요."),
"Tell me if you feel chills, itching, or back pain.":("오한, 가려움, 등 통증이 느껴지면 눌러 주세요.","열, 가려움, 등 통증이 느껴지면 말씀해 주세요."),
"The first fifteen minutes we'll watch you very closely.":("처음 15분 동안은 아주 천천히 지켜볼게요.","처음 15분 동안은 가족과 함께 지켜볼게요."),
"This confirms the blood matches you exactly.":("이렇게 하면 혈액이 정확히 얼마인지 확인돼요.","이렇게 하면 혈액이 정확히 빨리 들어가는지 확인돼요."),
"A second nurse will verify everything with me.":("다른 의사가 저와 함께 모든 걸 검증할 거예요.","다른 간호사가 저와 함께 모든 걸 설명할 거예요."),
"If anything feels off, press your call button right away.":("뭔가 아프면 바로 호출 버튼을 눌러 주세요.","뭔가 이상하면 바로 의사에게 손을 들어 주세요."),
"This tube goes through your nose into your stomach.":("이 약은 코를 통해 위까지 들어가요.","이 관은 코를 통해 위까지 나와요."),
"When I say go, swallow the water to help it down.":("제가 신호하면 물을 삼켜서 넘어가는 걸 지켜봐 주세요.","제가 신호하면 껌을 씹어서 넘어가는 걸 도와주세요."),
"It feels strange, but it won't stop you from breathing.":("느낌이 이상하겠지만 걷는 데는 지장이 없어요.","느낌이 간지럽겠지만 숨쉬는 데는 지장이 없어요."),
"Take small sips and swallow when I count.":("제가 세면 물을 조금씩 마시고 뱉어 주세요.","제가 세면 주스를 조금씩 마시고 삼켜 주세요."),
"I know this feels uncomfortable, and that's normal.":("복잡하게 느껴지는 거 알아요, 정상이에요.","불편하게 느껴지는 거 알아요, 드문 일이에요."),
"We're almost through — a few more swallows.":("이제 시작이에요, 몇 번만 더 삼켜 주세요.","거의 다 끝나가요, 몇 번만 더 마셔 주세요."),
"This soft tube drains the urine that's stuck.":("이 부드러운 관이 막혀 있는 가스를 배출해 줘요.","이 부드러운 관이 막혀 있는 소변을 검사해 줘요."),
"I'll clean everything carefully to prevent infection.":("통증을 예방하기 위해 모든 걸 조심스럽게 소독할게요.","감염을 예방하기 위해 모든 걸 조심스럽게 설명할게요."),
"It's uncomfortable for a moment, then the pressure eases.":("잠깐 따끔하다가 곧 압박감이 가라앉아요.","잠깐 불편하다가 곧 가려움이 가라앉아요."),
"I'll keep you covered as much as possible.":("가능한 한 최대한 빨리 해드릴게요.","가능한 한 최대한 닦아드릴게요."),
"Do I have your okay to go ahead?":("나가도 될까요?","설명해도 될까요?"),
"This will help your bladder empty completely.":("이렇게 하면 방광을 완전히 씻는 데 도움이 돼요.","이렇게 하면 방광을 천천히 비우는 데 도움이 돼요."),
"I'm labeling each tube with your name right at your bedside.":("침상 곁에서 바로 각 튜브에 이름으로 라벨을 읽고 있어요.","침상 곁에서 바로 각 튜브의 이름으로 라벨을 맞추고 있어요."),
"Can you confirm your date of birth once more?":("주소를 한 번 더 확인해 주시겠어요?","전화번호를 한 번 더 확인해 주시겠어요?"),
"This makes sure your results never get mixed up.":("이렇게 하면 결과가 절대 늦지 않아요.","이렇게 하면 라벨이 절대 섞이지 않아요."),
"Each tube gets its own barcode right now.":("각 가방마다 지금 바로 고유 바코드를 붙여요.","각 튜브마다 지금 바로 고유 스티커를 붙여요."),
"We label at the bedside so nothing gets switched later.":("나중에 늦지 않도록 침상 곁에서 라벨을 붙여요.","나중에 바뀌지 않도록 침상 곁에서 라벨을 읽어요."),
"I'll double-check every label before sending them to the lab.":("검사실로 보내기 전에 모든 라벨을 다시 설명할게요.","검사실로 보내기 전에 모든 서류를 다시 확인할게요."),
"Please keep your head turned to this side.":("손을 이쪽 방향으로 돌린 채 유지해 주세요.","머리를 이쪽 방향으로 돌린 채 올려 주세요."),
"You'll feel some numbing medicine, then pressure.":("소독약이 느껴지고 나서 압박감이 있을 거예요.","마취약이 느껴지기 전에 압박감이 있을 거예요."),
"The drapes keep everything sterile — try not to touch them.":("방포가 온기 상태를 유지해 주니 만지지 말아 주세요.","방포가 무균 상태를 유지해 주니 말씀하지 말아 주세요."),
"I'm watching your monitor the whole time.":("내내 모니터를 닦고 있어요.","내내 시계를 지켜보고 있어요."),
"You're doing great — just a little longer.":("잘하고 계세요, 조금만 더 쉬면 돼요.","조용하시네요, 조금만 더 하면 돼요."),
"I know this is scary, but we're staying right here with you.":("무서우실 텐데, 가족이 바로 여기 계속 있을게요.","화나실 텐데, 저희가 바로 여기 계속 있을게요."),
"I'm stopping the blood right away.":("지금 바로 라벨을 확인할게요.","지금 바로 혈압을 재 볼게요."),
"Tell me exactly what you're feeling now.":("어제 느끼셨던 걸 정확히 말씀해 주세요.","지금 느끼시는 걸 정확히 그려 주세요."),
"We're switching to fluids and calling the doctor.":("수액으로 바꾸고 의사 선생님께 말할게요.","수액으로 바꾸고 의사 선생님을 기다릴게요."),
"Your safety comes first, always.":("환자분의 편안이 언제나 최우선이에요.","병원의 안전이 언제나 최우선이에요."),
"I'm right here, and we'll get through this together.":("가족이 바로 여기 있고, 함께 이겨낼 거예요.","제가 바로 여기 있고, 함께 기다릴 거예요."),
"The doctor will be here in just a minute.":("간호사 선생님이 곧 오실 거예요.","의사 선생님이 곧 가실 거예요."),
"You're having a reaction to the contrast.":("음식에 반응이 나타나고 있어요.","벌레에 반응이 나타나고 있어요."),
"We're giving epinephrine to open your airway.":("눈을 뜨기 위해 에피네프린을 드리고 있어요.","기도를 닦기 위해 에피네프린을 드리고 있어요."),
"Focus on my voice and try to breathe slowly.":("제 얼굴에 집중하시고 천천히 숨을 쉬어 보세요.","제 목소리에 집중하시고 깊게 숨을 쉬어 보세요."),
"Your throat feels tight, but the medicine is working fast.":("목이 마른 느낌이 있지만 약이 빠르게 효과를 보이고 있어요.","배가 조이는 느낌이 있지만 약이 빠르게 효과를 보이고 있어요."),
"I'm not leaving your side.":("곁에 의사를 부를게요.","곁에 가족을 부를게요."),
"We're watching your oxygen and blood pressure closely.":("산소포화도와 체온을 면밀히 지켜보고 있어요.","산소포화도와 혈압을 천천히 지켜보고 있어요."),
"We're placing a line in your leg bone to give medicine fast.":("약을 빨리 드리려고 다리뼈에 관을 챙길게요.","약을 빨리 드리려고 다리뼈 관을 설명할게요."),
"You'll feel strong pressure — it means it's working.":("강한 통증이 느껴지는데, 잘 되고 있다는 뜻이에요.","약한 압박감이 느껴지는데, 잘 되고 있다는 뜻이에요."),
"Stay with me, we're getting fluids into you now.":("정신 놓지 마세요, 지금 수액을 설명하고 있어요.","눈 감지 마세요, 지금 수액을 넣고 있어요."),
"We couldn't find a vein, so we're using another way in.":("정맥을 찾지 못해서 다른 경로를 보고 있어요.","정맥을 찾지 못해서 다른 간호사를 부르고 있어요."),
"This should work fast, and we're right here with you.":("이건 오래 효과가 날 거예요, 저희가 바로 곁에 있어요.","이건 빨리 효과가 날 거예요, 가족이 바로 곁에 있어요."),
"Hang on, help is on the way.":("조금만 쉬어요, 도움이 오고 있어요.","조금만 버텨요, 가족이 오고 있어요."),
"Can you verify the drug, dose, and concentration with me?":("약물, 용량, 시간을 저와 함께 검증해 주시겠어요?","약물, 용량, 농도를 저와 따로 검증해 주시겠어요?"),
"Right patient, right route — let's read it aloud.":("정확한 환자, 정확한 경로, 소리내어 써봐요.","정확한 의사, 정확한 경로, 소리내어 읽어봐요."),
"Please calculate the units on your own, then we'll compare.":("먼저 혼자 유닛을 계산해 주세요, 그다음 서명해요.","먼저 같이 유닛을 계산해 주세요, 그다음 맞춰 봐요."),
"Wait — that number doesn't match the order.":("잠깐만요, 그 숫자가 시간과 안 맞아요.","잠깐만요, 그 색깔이 처방과 안 맞아요."),
"Let's stop and double-check before we give this.":("이걸 드리기 전에 멈추고 다시 설명해봐요.","이걸 드리기 전에 앉아서 다시 확인해봐요."),
"Thanks for catching that — safety first.":("그걸 잡아줘서 고마워요, 시간이 우선이니까요.","그걸 잡아줘서 미안해요, 안전이 우선이니까요."),
"You'll feel numbing medicine, then pushing pressure.":("소독약이 느껴지고 나서 누르는 압박감이 있을 거예요.","마취약이 느껴지기 전에 누르는 압박감이 있을 거예요."),
"Squeeze my hand — I'm giving you pain medicine now.":("제 손을 꽉 쥐세요, 지금 진통제를 설명할게요.","제 팔을 꽉 쥐세요, 지금 진통제를 드릴게요."),
"This tube helps your lung expand and you'll breathe easier.":("이 관이 폐가 펴지게 도와서 걷기가 더 편해질 거예요.","이 관이 폐가 펴지는지 보여서 숨쉬기가 더 편해질 거예요."),
"Stay with me, you're doing so well.":("눈 감지 마세요, 정말 잘하고 계세요.","정신 놓지 마세요, 정말 조용히 계세요."),
"The worst part is almost over.":("가장 힘든 부분은 이제 시작이에요.","가장 쉬운 부분은 거의 끝났어요."),
"I'm right here the whole time.":("내내 바로 밖에 있을게요.","내내 의사가 여기 있을게요."),
"I'm hanging the first unit of packed cells now.":("지금 두 번째 적혈구 팩을 걸고 있어요.","지금 첫 번째 적혈구 팩을 확인하고 있어요."),
"Do you want a one-to-one-to-one ratio with plasma and platelets?":("혈장·혈소판과 1대1대1 비율로 볼까요?","혈장·혈소판과 1대1대1 비율로 바꿀까요?"),
"Blood bank has two more coolers on the way.":("혈액은행에서 보냉함 세 개가 더 오고 있어요.","약국에서 보냉함 두 개가 더 오고 있어요."),
"I'll report vitals every five minutes.":("5분마다 활력징후를 설명할게요.","5분마다 소변량을 보고할게요."),
"Let's confirm the ratio with the attending now.":("지금 담당의와 비율을 설명해봐요.","지금 담당의와 이름을 확인해봐요."),
"Tell me the moment the next cooler arrives.":("다음 보냉함이 도착하는 순간 눌러 주세요.","다음 보냉함이 출발하는 순간 알려 주세요."),
}
W2={'w-birth':(None,['date of arrival','place of birth']),'w-check':(['바꾸다·교체하다','치우다·정리하다'],None),'w-done':(['(할 일을) 막 시작한','(할 일을) 잠시 멈춘'],None),
'w-stay':(['떠나다·옮겨가다','움직이다·돌아다니다'],None),'w-cause':(['결과; 이어지다','증상; 나타내다'],None),'w-stressful':(['지루하고 단조로운','위험부담이 큰'],None),'w-site':(['(시술) 방향','(시술) 시야'],None)}
W={'w-area':(['(그) 전체 범위','(그) 가장자리·끝'],None),'w-prep':(['(시술 후 피부를) 붕대로 감다','(시술 후 피부를) 말려 두다'],None),
'w-allergic':(['내성이 있는','감염이 있는'],None),'w-confirm':(['(맞는지) 거절하다·취소하다','(맞는지) 수정하다·바꾸다'],None),
'w-bladder':(None,['bowel','blister']),'w-over':(['(힘든 것이) 막 시작된','(힘든 것이) 남아 있는'],None)}
B={"Let me double-check your wristband before I start.":('double-check',['disinfect','reposition','investigate']),
"I know this feels uncomfortable, and that's normal.":('uncomfortable',['unbelievable','complicated','impossible'])}
W.update(W2)
apply('er-procedures',S,W,B)
