import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_five import go
S = {
"Let me take your blood pressure and check your pulse.": ["혈압을 재고 침대를 확인할게요.", "혈압을 설명하고 맥박을 확인할게요."],
"Your hands feel cool — I'm checking your circulation.": ["발이 서늘하네요 — 순환을 확인하고 있어요.", "손이 서늘하네요 — 호흡을 확인하고 있어요."],
"How long have you been feeling weak like this?": ["어디서부터 이렇게 힘이 없으셨어요?", "얼마나 오랫동안 이렇게 배가 고프셨어요?"],
"Your blood pressure is a little low right now.": ["지금 맥박이 조금 낮아요.", "지금 체온이 조금 낮아요."],
"I'm also checking how alert you are.": ["말투가 또렷한지도 함께 확인하고 있어요.", "시력이 또렷한지도 함께 확인하고 있어요."],
"Do you feel dizzy only when you stand up?": ["누울 때만 어지러우세요?", "일어설 때만 메스꺼우세요?"],
"How much have you had to drink today?": ["어제 물은 얼마나 드셨어요?", "오늘 술은 얼마나 드셨어요?"],
"I'll check your blood pressure lying down and standing.": ["앉은 상태와 선 상태에서 혈압을 확인할게요.", "누운 상태와 선 상태에서 체온을 확인할게요."],
"Have you had any falls because you feel dizzy?": ["졸려서 넘어진 적이 있으세요?", "어지러워서 병원에 간 적이 있으세요?"],
"Standing up slowly can help prevent a fall.": ["천천히 일어나면 감기를 예방하는 데 도움이 돼요.", "천천히 일어나면 낙상을 예방하는 데 시간이 걸려요."],
"I'm placing a larger IV so we can give fluids quickly.": ["빠르게 수액을 줄 수 있도록 더 긴 정맥로를 넣을게요.", "편하게 수액을 줄 수 있도록 더 굵은 정맥로를 넣을게요."],
"This fluid will help bring your blood pressure up.": ["이 수액이 맥박을 올리는 데 도움이 될 거예요.", "이 약이 혈압을 올리는 데 도움이 될 거예요."],
"You'll feel a quick pinch, then a cool sensation in your arm.": ["따끔한 느낌이 잠깐 있고, 그 다음 다리가 서늘하게 느껴질 거예요.", "가벼운 느낌이 잠깐 있고, 그 다음 팔이 서늘하게 느껴질 거예요."],
"This IV lets us give fluids or medicine quickly if needed.": ["이 정맥로로 필요하면 수액이나 음식을 빠르게 줄 수 있어요.", "이 팔찌로 필요하면 수액이나 약을 빠르게 줄 수 있어요."],
"I'll clean your arm first, then place the IV.": ["먼저 팔을 소독하고 나서 정맥로를 설명할게요.", "먼저 팔을 소독하고 정맥로를 소개할게요."],
"Losing that much fluid can lower your blood pressure.": ["그렇게 많은 수분을 잃으면 시력이 내려갈 수 있어요.", "그렇게 많은 수면을 잃으면 혈압이 내려갈 수 있어요."],
"We'll give fluids through your vein to catch you up.": ["정맥으로 수액을 드려서 부족한 시간을 채워드릴게요.", "정맥으로 수액을 드려서 부족한 부분을 알려드릴게요."],
"Once you feel better, we'll try small sips slowly.": ["좀 나아지시면 천천히 조금씩 밥을 먹어볼게요.", "좀 나아지시면 천천히 조금씩 걸어볼게요."],
"Throwing up for two days can make you lose a lot of fluid.": ["일주일 동안 계속 토하면 수분을 많이 잃을 수 있어요.", "이틀 동안 계속 토하면 입맛을 많이 잃을 수 있어요."],
"Call us before you stand up, because you may feel dizzy.": ["일어나시기 전에 저희를 불러 주세요, 졸리실 수 있어요.", "앉으시기 전에 저희를 불러 주세요, 어지러우실 수 있어요."],
"Do you remember feeling anything before you fainted?": ["쓰러진 후에 뭔가 느낀 게 기억나세요?", "쓰러지기 전에 누가 있었는지 기억나세요?"],
"Did anyone see what happened?": ["누가 그 상황을 신고했나요?", "누가 그 상황을 도왔나요?"],
"Did you hit your head or hurt yourself when you fell?": ["넘어지실 때 머리를 부딪히거나 옷이 찢어지셨나요?", "넘어지기 전 머리를 부딪히거나 다치셨나요?"],
"Try to remember if you felt dizzy before this happened.": ["쓰러진 뒤에 어지러웠는지 기억해 보세요.", "쓰러지기 전에 졸렸는지 기억해 보세요."],
"Let's check your head and arms for any injury from the fall.": ["머리와 팔에 낙상으로 인한 손상이 있는지 설명해 볼게요.", "머리와 팔에 낙상으로 인한 손상이 있는지 물어볼게요."],
"Have you noticed any black or bloody stools?": ["검거나 노란 대변을 본 적이 있으세요?", "검거나 피가 섞인 대변을 가족이 본 적이 있으세요?"],
"Are you taking any blood thinners?": ["항응고제를 구입하고 계신가요?", "항응고제를 어디서 복용하고 계신가요?"],
"We're getting fluids and blood ready for you.": ["수액과 침대를 준비하고 있어요.", "수액과 수혈을 소개하고 있어요."],
"Any recent surgery, injury, or vaginal bleeding?": ["최근 수술이나 부상, 또는 질 감염이 있었나요?", "어릴 때 수술이나 부상, 또는 질 출혈이 있었나요?"],
"We'll draw labs and get blood ready in case you need it.": ["혹시 필요할 경우를 대비해 채혈하고 수혈용 혈액을 보관할게요.", "혹시 필요할 경우를 대비해 채혈하고 수혈용 혈액을 옮길게요."],
"You feel warm and your heart is racing — I'm concerned about infection.": ["몸이 따뜻하고 심장이 빠르게 뛰네요 — 출혈이 걱정돼요.", "손이 따뜻하고 심장이 빠르게 뛰네요 — 감염이 걱정돼요."],
"Where do you think the infection might be coming from?": ["감염이 언제부터 시작됐다고 생각하세요?", "감염이 누구에게서 시작됐다고 생각하세요?"],
"We're drawing cultures and lactate and starting fluids fast.": ["배양검사와 젖산을 채취하고 수액을 빠르게 준비할게요.", "배양검사와 젖산을 옮기고 수액을 빠르게 시작할게요."],
"We need blood cultures before we start antibiotics.": ["식사를 시작하기 전에 혈액배양이 필요해요.", "퇴원하기 전에 혈액배양이 필요해요."],
"Feeling this confused can be an early sign of infection.": ["이렇게 정신이 혼미한 건 피로의 초기 징후일 수 있어요.", "이렇게 정신이 혼미한 건 감염의 마지막 징후일 수 있어요."],
"Does the chest heaviness spread to your arm or jaw?": ["가슴의 압박감이 팔이나 턱에서 시작되나요?", "가슴의 압박감이 팔이나 머리로 퍼지나요?"],
"Is it harder to breathe when you lie flat?": ["평평하게 앉으면 숨쉬기가 더 힘드세요?", "평평하게 누우면 먹기가 더 힘드세요?"],
"We're getting an ECG and listening to your lungs now.": ["지금 심전도를 설명하고 폐 소리를 들어볼게요.", "지금 심전도를 찍고 폐 소리를 녹음할게요."],
"Chest pressure that spreads to your jaw needs urgent attention.": ["가슴 압박감이 턱까지 퍼지면 긴급한 서류가 필요해요.", "가슴 압박감이 턱까지 퍼지면 긴급한 이송이 필요해요."],
"Tell me right away if the pressure in your chest gets worse.": ["가슴 압박감이 더 줄면 바로 말씀해 주세요.", "가슴 압박감이 더 심해지면 바로 가족에게 말씀해 주세요."],
"I'm giving you epinephrine in your thigh right now.": ["지금 쓴 에피네프린 펜을 상자에 넣을게요.", "지금 에피네프린을 놓기 전에 장갑을 낄게요."],
"What did you eat or take before this started?": ["이렇게 되기 전에 어디를 가셨거나 방문하셨나요?", "이렇게 된 뒤에 무엇을 드셨거나 복용하셨나요?"],
"Does your throat or tongue feel tight?": ["목이나 혀가 차가운 느낌이 있으세요?", "목이나 손이 조이는 느낌이 있으세요?"],
"I'll watch your airway closely while the epinephrine works.": ["에피네프린이 효과를 보이기 전에 기도를 계속 지켜볼게요.", "에피네프린이 효과를 보이는 동안 피부를 계속 지켜볼게요."],
"Hives and a tight throat can mean a serious allergic reaction.": ["두드러기와 목이 조이는 느낌은 심한 소화 반응일 수 있어요.", "두드러기와 코가 막히는 느낌은 심한 알레르기 반응일 수 있어요."],
"After the fluid, your pressure came up a little.": ["수액을 드린 후에 맥박이 조금 올라왔어요.", "수액을 드리기 전에 혈압이 조금 올라왔어요."],
"We're watching your urine output for signs that you're improving.": ["소변량을 보면서 식사가 나아지고 있는지 지켜보고 있어요.", "체중을 보면서 몸이 나아지고 있는지 지켜보고 있어요."],
"If you don't improve, we'll add another treatment.": ["호전이 없으면 다른 침대를 추가할게요.", "호전이 없으면 다른 병원으로 옮길게요."],
"We'll recheck your blood pressure after the bolus.": ["볼루스 전에 혈압을 다시 확인할게요.", "볼루스 후에 호흡을 다시 확인할게요."],
"If your urine output stays low, we may add more fluid.": ["소변량이 계속 적으면 물병을 더 추가할 수도 있어요.", "소변량이 계속 적으면 검사를 더 추가할 수도 있어요."],
"This medicine helps raise and hold your blood pressure.": ["이 약은 체온을 올리고 유지하는 데 도움을 줘요.", "이 약은 혈압을 올리고 확인하는 데 도움을 줘요."],
"We use the neck line so it works quickly and safely.": ["빠르고 편하게 작용하도록 목의 라인을 사용해요.", "빠르고 안전하게 작용하도록 목의 라인을 교체해요."],
"We'll watch you very closely while it's running.": ["이 약이 들어가는 동안 아주 조용히 지켜볼게요.", "이 약이 들어가기 전에 아주 꼼꼼히 지켜볼게요."],
"It's okay to feel nervous about a new medicine.": ["새로운 병실에 긴장되시는 건 자연스러운 일이에요.", "새로운 약에 설레시는 건 자연스러운 일이에요."],
"We placed this line in your neck so it works fast.": ["빨리 효과가 나도록 이 라인을 목에서 뺐어요.", "빨리 효과가 나도록 이 라인을 목에 넣을 거예요."],
"Which blood thinner do you take, and when was your last dose?": ["어떤 항응고제를 드시고, 마지막 복용은 어디서였나요?", "누가 항응고제를 주시고, 마지막 복용은 언제였나요?"],
"Any recent falls, bruising, or dark stools?": ["최근에 넘어지거나 멍이 들거나 노란 대변을 본 적이 있으세요?", "어릴 때 넘어지거나 멍이 들거나 검은 대변을 본 적이 있으세요?"],
"We're checking your blood count and clotting right away.": ["지금 바로 혈구 수와 응고 기능을 보여드릴게요.", "지금 바로 혈구 수와 응고 기능을 점검할게요."],
"Bleeding inside can quietly drop your blood pressure.": ["안에서 출혈이 있으면 몸무게가 조용히 떨어질 수 있어요.", "밖에서 출혈이 있으면 혈압이 조용히 떨어질 수 있어요."],
"Can I ask if you missed a dose or took extra medicine?": ["약을 잃어버리셨거나 추가로 더 사셨는지 여쭤봐도 될까요?", "약을 거르셨거나 추가로 더 드셨는지 말씀드릴까요?"],
"Bleeding? Point to where. Yes or no?": ["통증이에요? 어디인지 짚어주세요. 예, 아니오?", "출혈이에요? 언제인지 짚어주세요. 예, 아니오?"],
"Pain here? Yes or no?": ["여기가 가려워요? 예, 아니오?", "어제 아팠어요? 예, 아니오?"],
"Any allergy to medicine? Interpreter is coming.": ["약 알레르기 있어요? 의사가 오고 있어요.", "약 알레르기 있어요? 가족이 오고 있어요."],
"Squeeze my hand once for yes, twice for no.": ["'예'이면 손을 두 번, '아니요'이면 세 번 꽉 쥐어 주세요.", "'예'이면 발을 한 번, '아니요'이면 두 번 꽉 쥐어 주세요."],
"We'll get the interpreter here as soon as possible.": ["최대한 빨리 의사를 모셔올게요.", "최대한 빨리 보호자를 모셔올게요."],
"Can we go through all the medicines you took today?": ["어제 드신 약을 전부 함께 살펴볼까요?", "오늘 드신 음식을 전부 함께 살펴볼까요?"],
"Did you take an extra dose of any blood pressure pill?": ["혈압약을 평소보다 일찍 드신 적이 있으세요?", "비타민을 평소보다 더 드신 적이 있으세요?"],
"Water pills and heart pills together can drop your pressure.": ["이뇨제와 비타민을 함께 드시면 혈압이 떨어질 수 있어요.", "이뇨제와 심장약을 함께 드시면 체중이 떨어질 수 있어요."],
"Let's check all your pill bottles together.": ["가지고 계신 약병을 다 같이 닦아 볼게요.", "가지고 계신 가방을 다 같이 확인해 볼게요."],
"Too many pills at once can make you feel very dizzy.": ["한 번에 음식을 너무 많이 드시면 어지러워질 수 있어요.", "한 번에 약을 너무 많이 드시면 배가 고파질 수 있어요."],
"Let's start from the beginning — when did you last feel well?": ["처음부터 다시 시작해 볼게요 — 마지막으로 괜찮으셨던 게 어디였어요?", "처음부터 다시 시작해 볼게요 — 처음으로 괜찮으셨던 게 언제였어요?"],
"Any fever, bleeding, chest pain, or new medications?": ["발열이나 출혈, 가슴 통증, 또는 새로 시작한 운동이 있으세요?", "발열이나 기침, 가슴 통증, 또는 새로 시작한 약이 있으세요?"],
"We're running labs and an ECG to find the cause.": ["원인을 찾기 위해 검사와 심전도를 안내할게요.", "원인을 알리기 위해 검사와 심전도를 진행할게요."],
"Any recent falls, faints, or new pills you started?": ["최근에 넘어지거나 실신한 적, 또는 새로 시작한 일이 있으세요?", "어릴 때 넘어지거나 실신한 적, 또는 새로 시작한 약이 있으세요?"],
"We'll check your labs first, then decide on imaging.": ["먼저 검사 결과를 확인하고, 퇴원 여부를 정할게요.", "먼저 검사 결과를 확인하고, 영상검사 비용을 정할게요."],
"Fluids aren't holding — start norepinephrine now.": ["수액으로는 안 버텨요 — 노르에피네프린 지금 준비해야 해요.", "수액으로는 안 버텨요 — 노르에피네프린 지금 점검해야 해요."],
"Get broad-spectrum antibiotics in within the hour.": ["한 시간 안에 항생제 서류를 준비하세요.", "한 시간 안에 광범위 항생제 냉장고를 점검하세요."],
"Recheck the lactate and keep the MAP above 65.": ["혈당을 재확인하고 평균동맥압을 65 이상으로 유지하세요.", "젖산을 재확인하고 심박수를 100 이하로 유지하세요."],
"Call the pharmacy and get antibiotics moving now.": ["원무과에 연락해서 지금 바로 항생제를 준비해 주세요.", "약국에 연락해서 지금 바로 휠체어를 준비해 주세요."],
"Keep checking her blood pressure every few minutes.": ["몇 분마다 혈압계를 계속 확인해 주세요.", "몇 분마다 침대를 계속 확인해 주세요."],
"The swollen leg and crash suggest a massive PE.": ["다리가 붓고 갑자기 악화된 걸 보면 대량 출혈이 의심돼요.", "팔이 붓고 갑자기 악화된 걸 보면 대량 폐색전이 의심돼요."],
"Get a bedside echo to look at the right heart.": ["우심장을 볼 수 있게 침상 의자 준비해요.", "우심장을 볼 수 있게 침상 조명 준비해요."],
"Prepare thrombolytics and notify the team.": ["혈전용해제를 준비하고 보호자에 알리세요.", "혈전용해제를 보관하고 팀에 알리세요."],
"Watch his oxygen and blood pressure closely right now.": ["지금 산소포화도와 혈압을 조용히 지켜보세요.", "지금 산소포화도와 혈압을 면밀히 읽어 주세요."],
"Get two large-bore IVs in before the thrombolytics start.": ["혈전용해제를 시작하기 전에 굵은 정맥로를 세 개 잡아 주세요.", "혈전용해제를 시작하기 전에 가는 정맥로를 두 개 잡아 주세요."],
"Low pressure, big neck veins, muffled tones — think tamponade.": ["혈압이 낮고 손 정맥이 부풀고 심음이 둔탁해요 — 심장압전을 생각하세요.", "혈압이 낮고 목 정맥이 부풀고 호흡음이 둔탁해요 — 심장압전을 생각하세요."],
"Get the ultrasound and call for a pericardiocentesis kit.": ["초음파를 가져오고 심낭천자 동의서를 요청하세요.", "초음파 젤을 가져오고 천자 키트를 요청하세요."],
"Give a fluid bolus while we prepare the drain.": ["배액을 정리하는 동안 수액 볼루스를 주세요.", "배액을 준비하기 전에 수액 볼루스를 주세요."],
"Her neck veins look big and her heart tones are muffled.": ["손 정맥이 부풀어 보이고 심음도 둔탁하게 들려요.", "목 정맥이 부풀어 보이고 폐음도 둔탁하게 들려요."],
"Get the kit ready — we may need to drain this now.": ["심낭천자가 필요할 수 있으니 침대를 준비해 주세요.", "심낭천자가 필요할 수 있으니 키트를 세어 주세요."],
"Activate the massive transfusion protocol now.": ["지금 대량수혈 서류를 정리하세요.", "지금 대량수혈 프로토콜 번호를 안내하세요."],
"Two large-bore IVs and get O-negative blood up here.": ["굵은 정맥로 세 개를 잡고 O형 음성 혈액을 가져오세요.", "굵은 정맥로 두 개를 잡고 O형 음성 혈액 서류를 가져오세요."],
"Call GI for emergent endoscopy.": ["응급 내시경을 위해 호흡기내과에 연락하세요.", "응급 내시경을 위해 소화기내과에 방문하세요."],
"He's vomiting blood and looks very pale and weak.": ["혈액을 토하고 있고 창백하고 졸려 보여요.", "혈액을 토하고 있고 창백하고 슬퍼 보여요."],
"Keep two large IV lines running for the transfusion.": ["수혈을 위해 굵은 정맥로 세 개를 계속 유지하세요.", "검사를 위해 굵은 정맥로 두 개를 계속 유지하세요."],
"Low pressure with a slow heart rate points to neurogenic shock.": ["혈압은 낮은데 호흡도 느린 걸 보면 신경성 쇼크가 의심돼요.", "혈압은 낮은데 맥박도 느린 걸 보면 출혈성 쇼크가 의심돼요."],
"Keep full spinal precautions — don't move his neck.": ["척추 고정을 완전히 유지하세요 — 문을 닫지 마세요.", "척추 고정을 완전히 유지하세요 — 침대를 올리지 마세요."],
"Give fluids and consider a pressor and atropine.": ["수액을 주고, 승압제와 아트로핀도 세어 두세요.", "수액을 주고, 승압제와 아트로핀 병도 옮겨 두세요."],
"He can't keep himself warm, so watch his temperature.": ["스스로 체온을 유지하지 못하니 담요를 지켜보세요.", "스스로 일어나지 못하니 체온을 계속 지켜보세요."],
"We'll give a pressor if fluids don't fix his pressure.": ["수액으로도 혈압이 안 오르면 승압제를 소개할게요.", "수액으로도 체온이 안 오르면 승압제를 줄게요."],
"Situation: septic shock on norepinephrine, still hypotensive.": ["상황: 노르에피네프린을 쓰고 있는 패혈증성 쇼크, 여전히 열이 높아요.", "상황: 노르에피네프린을 쓰고 있는 패혈증성 쇼크, 여전히 의식이 없어요."],
"Her urine output dropped and lactate is climbing.": ["소변량이 줄었고 체온 수치가 올라가고 있어요.", "식사량이 줄었고 젖산 수치가 올라가고 있어요."],
"I recommend ICU admission and close monitoring now.": ["지금 중환자실 입원과 가족 면회를 권합니다.", "지금 중환자실 입원과 면회 조절을 권합니다."],
"Her pressure keeps dropping despite two pressors running.": ["승압제 세 가지를 쓰는데도 혈압이 계속 떨어지고 있어요.", "승압제 두 가지를 쓰는데도 체온이 계속 떨어지고 있어요."],
"I think she needs close monitoring in the ICU now.": ["병동에서 집중 감시를 받아야 할 것 같아요.", "중환자실에서 집중 면회를 받아야 할 것 같아요."],
"When did you last take your steroid, and why did you stop?": ["스테로이드를 마지막으로 어디서 드셨고, 왜 끊으셨나요?", "스테로이드를 마지막으로 언제 드셨고, 누가 중단하셨나요?"],
"Missing your steroids can cause a dangerous crisis.": ["비타민을 거르면 위험한 위기가 올 수 있어요.", "스테로이드를 나누면 위험한 위기가 올 수 있어요."],
"We're giving hydrocortisone and fluids right away.": ["지금 바로 하이드로코르티손과 수액을 보관할게요.", "지금 바로 하이드로코르티손과 수액을 옮길게요."],
"You can't just stop steroids suddenly without a plan.": ["스테로이드는 계획 없이 갑자기 나누면 안 돼요.", "비타민은 계획 없이 갑자기 끊으면 안 돼요."],
"Hydrocortisone replaces the hormone your body is missing right now.": ["하이드로코르티손은 지금 몸에 모자란 수분을 채워 줘요.", "하이드로코르티손은 지금 몸에 모자란 호르몬을 줄여 줘요."],
}
W = {
"w-stand": {"ko": ["눕다·누워 있다", "앉다·착석하다"]},
"w-fall": {"ko": ["실신(기절함)", "발작(경련함)"]},
"w-place": {"ko": ["빼다·제거하다", "소독하다"]},
"w-give": {"ko": ["빼다·제거하다", "받다·투여받다"]},
"w-throw": {"ko": ["기침하다(일상어)", "삼키다(일상어)"]},
"w-thinner": {"ko": ["이뇨제(소변촉진제)", "진통제(통증완화제)"]},
"w-get": {"ko": ["치우다·없애다", "버리다·폐기하다"]},
"w-bleed": {"ko": ["봉합하다", "붓다(붓기)"]},
"w-hold": {"ko": ["(혈압을) 떨어뜨리다·낮추다", "(혈압을) 올리다·높이다"]},
"w-run": {"ko": ["(검사를) 중단하다·(펌프가) 멈추다", "(검사를) 섞다·(펌프가) 막히다"]},
"w-dark": {"ko": ["밝은·환한", "투명한"]},
"w-count": {"ko": ["배양(균배양)", "농도(진하기)"]},
"w-go": {"ko": ["(하나씩) 건너뛰다", "(하나씩) 처방하다"]},
"w-keep": {"ko": ["멈추다·중단하다", "바꾸다·교체하다"]},
"w-call": {"ko": ["보내다·발송하다", "기다리다·대기하다"]},
"w-crash": {"ko": ["회복(빠른 호전)", "안정(차분한 상태)"]},
"w-right": {"ko": ["왼쪽·틀린", "위쪽·높은"]},
"w-tone": {"ko": ["잡음(소음)", "박동수(맥박)"]},
"w-pericardiocentesis": {"en": ["pericardiectomy", "thoracocentesis"]},
"w-kit": {"ko": ["약병(약통)", "주사기(주사도구)"]},
"w-bolus": {"ko": ["지속 주입(천천히)", "경구 투여(입으로)"]},
"w-activate": {"ko": ["(프로토콜을) 해제하다", "(프로토콜을) 보류하다"]},
"w-bore": {"ko": ["길이(전체길이)", "눈금(표시선)"]},
"w-vomit": {"ko": ["기침하다(의학어)", "트림하다(의학어)"]},
"w-point": {"ko": ["감추다·숨기다", "배제하다·제외하다"]},
"w-hypotensive": {"en": ["hypertensive", "hypoglycemic"]},
}
B = {
"He can't keep himself warm, so watch his temperature.": ["schedule", "insurance", "appearance"],
"Situation: septic shock on norepinephrine, still hypotensive.": ["mild", "silent", "chronic"],
"Missing your steroids can cause a dangerous crisis.": ["seasonal", "friendly", "colorful"],
"We're giving hydrocortisone and fluids right away.": ["acetaminophen", "amoxicillin", "ondansetron"],
}
if __name__ == "__main__":
    go("er-shock", S, W, B)
