import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_five import go
S = {
"Can you smile and show me your teeth for me?": ["미소 지으면서 손을 보여주실 수 있나요?", "인사하면서 이를 보여주실 수 있나요?"],
"Hold both arms straight out and close your eyes.": ["양팔을 옆으로 쭉 뻗고 눈을 감아 보세요.", "양팔을 앞으로 쭉 뻗고 입을 다물어 보세요."],
"What time did these symptoms first start?": ["이 증상이 어디서 처음 시작됐나요?", "이 증상이 누구에게 처음 시작됐나요?"],
"Does one side of your face feel numb?": ["얼굴 한쪽이 뜨겁게 느껴지세요?", "얼굴 한쪽이 가렵게 느껴지세요?"],
"Try to repeat this simple sentence for me.": ["이 간단한 문장을 따라 읽어 보세요.", "이 간단한 노래를 따라 말해 보세요."],
"Your speech sounds a little slurred right now.": ["지금 말씀이 조금 빠르게 들려요.", "지금 말씀이 조금 작게 들려요."],
"Tell me exactly when you first noticed this.": ["이걸 처음 알아차린 장소를 정확히 말씀해 주세요.", "이걸 마지막으로 알아차린 시각을 정확히 말씀해 주세요."],
"When did you last see him completely normal?": ["그를 마지막으로 완전히 정상으로 보신 게 어디였나요?", "그를 처음으로 완전히 정상으로 보신 게 언제였나요?"],
"Who was with him right before this started?": ["이게 시작된 직후에 누가 그와 함께 있었나요?", "이게 시작되기 직전에 그가 어디에 있었나요?"],
"Was he acting like himself at dinner last night?": ["오늘 아침 식사 때는 평소와 똑같아 보였나요?", "어젯밤 외출했을 때는 평소와 똑같아 보였나요?"],
"Can you tell me exactly what time it was?": ["그게 정확히 어디였는지 말씀해 주실 수 있나요?", "그게 정확히 몇 명이었는지 말씀해 주실 수 있나요?"],
"Did anyone else see him after that?": ["그 전에 다른 사람이 그를 본 적이 있나요?", "그 후에 다른 사람이 그를 도운 적이 있나요?"],
"I need your phone number in case we have questions.": ["질문이 생길 경우를 대비해 주소가 필요합니다.", "질문이 생길 경우를 대비해 보험증이 필요합니다."],
"Are you the most recent person who saw him?": ["그를 가장 처음에 본 사람이 보호자님이신가요?", "그를 가장 최근에 본 사람이 이웃분이신가요?"],
"I'm going to check your blood sugar with a quick finger stick.": ["손끝을 살짝 닦아서 혈당을 빠르게 확인할게요.", "손끝을 살짝 찔러서 혈당을 안내할게요."],
"Have you eaten anything today?": ["어제 뭐라도 드셨나요?", "오늘 누구라도 만나셨나요?"],
"Are you on any diabetes medication or insulin?": ["당뇨약이나 인슐린을 샀나요?", "당뇨약이나 인슐린을 처음 쓰고 계신가요?"],
"I'm going to take your blood pressure and pulse now.": ["지금 혈압과 키를 잴게요.", "지금 혈압과 맥박을 알려 드릴게요."],
"Let me also check your oxygen level quickly.": ["산소포화도도 빠르게 볼게요.", "산소포화도도 빠르게 알려드릴게요."],
"Your blood sugar reading is a little low right now.": ["지금 혈당 수치가 조금 불규칙해요.", "지금 혈압 수치가 조금 낮아요."],
"We'll give you sugar through your IV to bring it up.": ["혈당을 알리기 위해 정맥으로 당을 드릴게요.", "혈압을 올리기 위해 정맥으로 당을 드릴게요."],
"The CT scan checks for bleeding versus a clot in your brain.": ["CT 촬영으로 뇌에 출혈이 있는지 감염이 있는지 확인해요.", "CT 촬영으로 폐에 출혈이 있는지 혈전이 있는지 확인해요."],
"It's quick and painless, and we need it right away.": ["빠르고 소리도 없으며, 지금 바로 필요해요.", "빠르고 통증도 없으며, 지금 바로 안내해요."],
"Please hold your head still while the machine scans.": ["기계가 촬영하는 동안 머리를 숙여 주세요.", "기계가 촬영하기 전에 머리를 가만히 있어 주세요."],
"We need to rule out bleeding before we give any medication.": ["식사를 하기 전에 출혈부터 배제해야 해요.", "약을 투여하기 전에 감염부터 배제해야 해요."],
"You'll need to remove any metal jewelry first.": ["먼저 금속 장신구를 닦으셔야 해요.", "먼저 신발을 빼셔야 해요."],
"This scan will only take a few minutes.": ["이 서류는 몇 분밖에 안 걸려요.", "이 약은 몇 분밖에 안 걸려요."],
"Try to stay as still as possible during the scan.": ["촬영하는 동안 최대한 편하게 있어 주세요.", "촬영하기 전에 최대한 가만히 있어 주세요."],
"Before you drink, I need to check your swallowing first.": ["물을 드시기 전에 먼저 걸음 기능을 확인해야 해요.", "물을 드시기 전에 먼저 삼킴 기능을 설명해야 해요."],
"Please don't eat or drink anything until we test it.": ["검사가 끝날 때까지 아무데도 가거나 앉지 마세요.", "검사가 끝날 때까지 아무것도 만지거나 흔들지 마세요."],
"Take a small sip and tell me if you cough.": ["입을 조금만 벌리고 기침이 나면 말씀해 주세요.", "숨을 조금만 쉬고 기침이 나면 말씀해 주세요."],
"I know your mouth feels dry, but we test first.": ["눈이 마르신 거 알아요, 그래도 검사부터 할게요.", "입이 아프신 거 알아요, 그래도 검사부터 할게요."],
"If you cough or choke, we'll stop right away.": ["졸리거나 하품하면 바로 멈출게요.", "기침을 하거나 웃으시면 바로 멈출게요."],
"Swallowing safely protects your lungs from aspiration.": ["안전하게 삼키는 것이 흡인으로부터 심장을 보호해요.", "안전하게 걷는 것이 흡인으로부터 폐를 보호해요."],
"You can't eat or drink until the results come back.": ["결과가 나올 때까지 걷거나 앉을 수 없어요.", "결과가 나올 때까지 퇴원하거나 이동할 수 없어요."],
"I'm going to ask you a few questions and tasks.": ["몇 가지 질문과 서류를 드릴게요.", "몇 가지 안내와 과제를 드릴게요."],
"Follow my finger with your eyes only.": ["눈으로만 제 펜을 따라와 보세요.", "고개로만 제 손가락을 따라와 보세요."],
"Tell me the name of this object I'm holding up.": ["제가 들고 있는 이 물건의 색깔을 말씀해 보세요.", "제가 들고 있는 이 물건을 받아 보세요."],
"Squeeze my hands as hard as you can.": ["최대한 천천히 제 손을 쥐어 보세요.", "최대한 오래 제 손을 쥐어 보세요."],
"Now close your eyes and hold both arms up.": ["이제 입을 다물고 양팔을 들어 보세요.", "이제 눈을 감고 양손을 들어 보세요."],
"Try your best on each task, even if it's hard.": ["졸려도 각 과제에 최선을 다해 보세요.", "어려워도 매 시간 최선을 다해 보세요."],
"This score helps us track any changes over time.": ["이 점수는 시간에 따른 비용을 추적하는 데 도움이 돼요.", "이 점수는 시간에 따른 변화를 줄이는 데 도움이 돼요."],
"When did you last feel completely normal?": ["마지막으로 완전히 정상으로 느끼신 게 몇 번이었나요?", "처음으로 완전히 정상으로 느끼신 게 언제였나요?"],
"Can you squeeze my hand with both hands for me?": ["양발로 제 손을 쥐어 보실 수 있나요?", "양손으로 제 어깨를 쥐어 보실 수 있나요?"],
"I need you to try to repeat this sentence.": ["이 문장을 외워 보셨으면 해요.", "이 숫자를 따라 말해 보셨으면 해요."],
"Your right side looks weaker than your left.": ["오른쪽이 왼쪽보다 커 보여요.", "오른쪽이 왼쪽보다 어두워 보여요."],
"You're still inside the window for clot-busting medication.": ["아직 혈전용해제를 쓸 수 있는 병실 안에 있어요.", "곧 혈전용해제를 쓸 수 있는 시간창 안에 있어요."],
"Have you had any surgery or bleeding in the past two weeks?": ["지난 2주 안에 수술이나 여행이 있었나요?", "지난 2일 안에 수술이나 출혈이 있었나요?"],
"I'm going to explain the risks of this medication now.": ["지금 이 약의 가격을 설명해 드릴게요.", "지금 이 검사의 위험성을 설명해 드릴게요."],
"Are you seeing one of me or two right now?": ["지금 제가 하나로 들리세요, 둘로 들리세요?", "지금 제가 하나로 보이세요, 셋으로 보이세요?"],
"Can you touch your nose then my finger?": ["귀를 만졌다가 제 손가락을 만져 보실 수 있나요?", "코를 만졌다가 제 어깨를 만져 보실 수 있나요?"],
"Does the dizziness get worse when you move your head?": ["머리를 숙이면 어지럼증이 심해지나요?", "머리를 움직이면 두통이 심해지나요?"],
"Does the double vision go away if you cover one eye?": ["한쪽 귀를 가리면 겹쳐 보이는 게 사라지나요?", "한쪽 눈을 가리면 겹쳐 들리는 게 사라지나요?"],
"Does it feel like the room is spinning around you?": ["방이 빙빙 흔들리는 것처럼 느껴지세요?", "문이 빙빙 도는 것처럼 느껴지세요?"],
"Any trouble with your balance or walking straight?": ["균형을 잡거나 똑바로 앉는 데 문제가 있나요?", "식사를 하거나 똑바로 걷는 데 문제가 있나요?"],
"These symptoms can still mean a stroke, even without weakness.": ["위약감이 없어도 이 증상들은 오래 갈 수 있어요.", "위약감이 없어도 이 증상들은 갑자기 생길 수 있어요."],
"What time did you go to sleep last night?": ["어젯밤 몇 시에 일어나셨나요?", "어젯밤 어디서 주무셨나요?"],
"Did you wake up at all during the night feeling normal?": ["밤중에 깨어났을 때 배가 고프셨나요?", "아침에 깨어났을 때 정상이라고 느끼셨나요?"],
"When exactly did you notice the weakness this morning?": ["어제 아침 정확히 언제 위약감을 알아차리셨나요?", "오늘 아침 정확히 어떻게 위약감을 알아차리셨나요?"],
"We'll use imaging to estimate how long this has been going on.": ["영상검사로 이게 얼마나 커졌는지 추정할게요.", "영상검사로 이게 왜 생겼는지 추정할게요."],
"Do you remember getting up to use the bathroom overnight?": ["밤새 물 마시려고 일어나신 거 기억나세요?", "아침에 화장실 가려고 일어나신 거 기억나세요?"],
"Since we can't confirm the exact start time, the scan will guide us.": ["정확한 시작 시각을 확인할 수 없으니, 설명서가 판단에 도움이 될 거예요.", "정확한 시작 장소를 확인할 수 없으니, 촬영 결과가 판단에 도움이 될 거예요."],
"Was anyone else awake with you during the night?": ["아침에 다른 사람도 함께 깨어 있었나요?", "밤중에 다른 사람도 함께 나가 있었나요?"],
"Have you had any surgery or major bleeding recently?": ["최근에 수술이나 큰 여행이 있었나요?", "어릴 때 수술이나 큰 출혈이 있었나요?"],
"Are you taking any blood thinners?": ["항응고제를 나누고 계신가요?", "항응고제를 언제 복용하고 계신가요?"],
"Have you ever had bleeding in your brain before?": ["전에 두통이 있었던 적이 있나요?", "최근에 뇌출혈이 있었던 적이 있나요?"],
"Any history of stroke or head injury in the past three months?": ["지난 3일 안에 뇌졸중이나 머리 손상 병력이 있나요?", "지난 3개월 안에 뇌졸중이나 허리 손상 병력이 있나요?"],
"Is your blood pressure under good control at home?": ["집에서 체중이 잘 조절되고 있나요?", "병원에서 혈압이 잘 조절되고 있나요?"],
"These questions help us make sure the medication is safe for you.": ["이 질문들은 이 약이 저렴한지 확인하는 데 도움이 돼요.", "이 질문들은 이 검사가 안전한지 확인하는 데 도움이 돼요."],
"Do you know if you have any bleeding disorders?": ["수면 장애가 있는지 알고 계신가요?", "출혈 장애가 있는지 가족이 알고 계신가요?"],
"Blink twice for yes and once for no.": ["예이면 한 번, 아니오면 세 번 눈을 깜빡여 주세요.", "예이면 두 번, 아니오면 한 번 손을 흔들어 주세요."],
"Point to where it hurts if you can.": ["가능하면 먼 곳을 가리켜 주세요.", "가능하면 가고 싶은 곳을 가리켜 주세요."],
"Squeeze my hand if you understand me.": ["제 말을 이해하시면 제 발을 쥐어 주세요.", "제 말을 이해하시면 제 손을 흔들어 주세요."],
"I'll ask yes or no questions, one at a time.": ["한 번에 두 개씩 예/아니오 질문을 드릴게요.", "한 번에 하나씩 예/아니오 설명을 드릴게요."],
"Blink once if that's not right.": ["맞지 않으면 두 번 깜빡여 주세요.", "아프면 한 번 깜빡여 주세요."],
"Take your time, there's no rush at all.": ["천천히 하세요, 전혀 걱정할 필요 없어요.", "천천히 하세요, 전혀 말할 필요 없어요."],
"Squeeze harder if the answer is yes.": ["답이 예이면 더 오래 쥐어 주세요.", "답이 아니오이면 더 세게 쥐어 주세요."],
"How long have you had atrial fibrillation?": ["심방세동을 어떻게 앓으셨나요?", "고혈압을 얼마나 오래 앓으셨나요?"],
"Are you on a blood thinner for your heart?": ["심장 때문에 항응고제를 구입하고 계신가요?", "허리 때문에 항응고제를 복용하고 계신가요?"],
"Have you missed any doses recently?": ["최근에 병원을 옮긴 적이 있나요?", "어릴 때 복용을 거른 적이 있나요?"],
"An irregular heartbeat can let clots form inside your heart.": ["불규칙한 심장박동은 심장 안에 소음을 만들 수 있어요.", "불규칙한 심장박동은 폐 안에 혈전을 만들 수 있어요."],
"Those clots can travel to the brain and cause a stroke.": ["그 혈전이 폐로 이동해 뇌졸중을 일으킬 수 있어요.", "그 혈전이 뇌로 이동해 감염을 일으킬 수 있어요."],
"Staying on your blood thinner helps prevent this.": ["항응고제를 계속 복용하면 이를 예방하는 데 돈이 들어요.", "항응고제를 계속 복용하면 이를 비교하는 데 도움이 돼요."],
"Let's check when you took your last dose.": ["마지막으로 복용한 장소를 확인해 볼게요.", "처음으로 복용한 시각을 확인해 볼게요."],
"What blood thinner do you take and what dose?": ["어떤 항응고제를 어떻게 복용하시나요?", "어떤 비타민을 얼마나 복용하시나요?"],
"When was your last dose exactly?": ["정확히 마지막 복용이 몇 번째였나요?", "정확히 처음 복용이 언제였나요?"],
"Do you know your most recent INR value?": ["가장 처음 INR 수치를 알고 계신가요?", "가장 최근 INR 수치를 가족이 알고 계신가요?"],
"Warfarin needs regular blood tests to check the level.": ["와파린은 수치를 확인하기 위해 정기적인 소변검사가 필요해요.", "와파린은 맛을 확인하기 위해 정기적인 혈액검사가 필요해요."],
"A high INR means a higher bleeding risk right now.": ["높은 INR은 지금 감염 위험이 더 크다는 뜻이에요.", "높은 체온은 지금 출혈 위험이 더 크다는 뜻이에요."],
"We may need to reverse the medication if bleeding is severe.": ["출혈이 심하면 약효를 설명해야 할 수도 있어요.", "통증이 심하면 약효를 되돌려야 할 수도 있어요."],
"Please bring your pill bottle next time if you can.": ["가능하면 다음에 가방을 가져와 주세요.", "가능하면 다음에 약병을 두고 와 주세요."],
"What time? Point to the clock.": ["몇 번이죠? 시계를 가리켜 보세요.", "몇 시죠? 달력을 가리켜 보세요."],
"This arm — when did it stop moving?": ["이 팔—어떻게 움직이지 않았나요?", "이 팔—언제부터 아프지 않았나요?"],
"I'm getting an interpreter right now.": ["지금 바로 의사를 데려올게요.", "지금 바로 보호자를 데려올게요."],
"Show me with your fingers, one to five.": ["손가락으로 1부터 10까지 보여 주세요.", "손가락으로 1부터 5까지 세어 주세요."],
"Nod if you understand what I'm saying.": ["제 말을 이해하시면 눈을 감아 주세요.", "제 말이 틀리면 고개를 끄덕여 주세요."],
"The interpreter will be here in just a few minutes.": ["통역사가 몇 시간 안에 도착할 거예요.", "보호자가 몇 분 안에 도착할 거예요."],
"Point to your arm and show me strong or weak.": ["팔을 가리키고 큰지 작은지 보여 주세요.", "팔을 가리키고 뜨거운지 차가운지 보여 주세요."],
"Your blood pressure needs to come down before treatment.": ["치료 전에 체온을 낮춰야 해요.", "식사 전에 혈압을 낮춰야 해요."],
"We'll give medication to lower it safely.": ["안전하게 낮추도록 물을 드릴게요.", "안전하게 낮추도록 약을 고를게요."],
"Tell me if your headache gets worse.": ["두통이 줄면 말씀해 주세요.", "소음이 심해지면 말씀해 주세요."],
"We're targeting a lower number before we can treat the clot.": ["혈전을 치료한 뒤에 더 낮은 수치를 목표로 하고 있어요.", "감염을 치료하기 전에 더 낮은 수치를 목표로 하고 있어요."],
"I'll check your pressure again in fifteen minutes.": ["5분 후에 혈압을 다시 확인할게요.", "15분 후에 혈압을 다시 알려 드릴게요."],
"Let me know right away if your vision changes.": ["청력에 변화가 있으면 바로 알려 주세요.", "기분에 변화가 있으면 바로 알려 주세요."],
"A sudden headache with high pressure needs quick attention.": ["갑작스러운 두통과 높은 혈압은 빠른 서류가 필요해요.", "갑작스러운 소음과 높은 혈압은 빠른 조치가 필요해요."],
"Even though it passed, this was a serious warning sign.": ["지나갔더라도 이건 심각한 소식이었어요.", "지나갔더라도 이건 오래된 경고 신호였어요."],
"We need tests to prevent a full stroke.": ["본격적인 뇌졸중을 알리려면 검사가 필요해요.", "본격적인 감염을 예방하려면 검사가 필요해요."],
"Please stay so we can find the cause.": ["원인을 정리할 수 있도록 남아 계셔 주세요.", "비용을 줄일 수 있도록 남아 계셔 주세요."],
"This was likely a mini-stroke, and it can happen again.": ["이건 미니 뇌졸중일 가능성이 높고, 그전에도 있었어요.", "이건 미니 뇌졸중일 가능성이 높고, 누구에게나 일어날 수 있어요."],
"Going home now means we can't find out why this happened.": ["지금 집에 가시면 언제 이런 일이 생겼는지 알아낼 수 없어요.", "지금 쉬시면 왜 이런 일이 생겼는지 알아낼 수 없어요."],
"Without treatment, your risk of a real stroke goes up.": ["치료하지 않으면 실제 비용 부담이 올라가요.", "치료하지 않으면 실제 대기 시간이 올라가요."],
"These tests can find the cause and help prevent another one.": ["이 검사들은 원인을 찾고 재발을 기억하는 데 도움이 돼요.", "이 검사들은 비용을 찾고 재발을 예방하는 데 도움이 돼요."],
"I need you to stay with me — can you open your eyes?": ["정신 잃지 마세요—입을 열 수 있나요?", "정신 잃지 마세요—눈을 비빌 수 있나요?"],
"We're protecting your airway if you keep vomiting.": ["계속 구토하시면 침대를 보호할 거예요.", "계속 기침하시면 기도를 보호할 거예요."],
"Your blood pressure is dangerously high; we're treating it now.": ["혈압이 위험할 정도로 불안정해요. 지금 치료하고 있어요.", "혈압이 위험할 정도로 높아요. 지금 설명하고 있어요."],
"Can you squeeze my hand and open your eyes for me?": ["제 손을 쥐고 혀를 내밀어 보실 수 있나요?", "제 손을 놓고 눈을 떠 보실 수 있나요?"],
"We're turning you on your side to protect your airway.": ["체온을 맞추기 위해 옆으로 돌려 드릴게요.", "기도를 보호하기 위해 담요로 덮어 드릴게요."],
"We're giving medication right now to bring your pressure down.": ["지금 혈압을 낮추기 위해 약을 고르고 있어요.", "지금 혈압을 낮추기 위해 물을 드리고 있어요."],
"Stay with me and keep your eyes open if you can.": ["정신 잃지 마시고 가능하면 입을 벌리고 계세요.", "정신 잃지 마시고 가능하면 손을 들고 계세요."],
"There's a large clot we can physically remove.": ["물리적으로 제거할 수 있는 큰 혈전이 두 개 있어요.", "물리적으로 계산할 수 있는 큰 혈전이 있어요."],
"He needs to transfer to the cath lab immediately.": ["즉시 병동으로 이송해야 해요.", "즉시 시술실로 안내해야 해요."],
"I need your consent so we don't lose time.": ["시간을 잃지 않도록 신분증이 필요해요.", "비용을 잃지 않도록 동의가 필요해요."],
"This procedure can pull the clot out and restore blood flow.": ["이 시술로 혈전을 빼내고 통증을 회복시킬 수 있어요.", "이 약으로 혈전을 빼내고 혈류를 회복시킬 수 있어요."],
"The team is ready and waiting for him right now.": ["팀이 곧 준비되어 그를 기다리고 있어요.", "팀이 지금 식사 중이라 그를 기다리고 있어요."],
"Every minute without treatment means more brain tissue at risk.": ["치료 없이 지나가는 매분마다 더 많은 심장 조직이 위험해져요.", "치료 없이 지나가는 매분마다 더 많은 대기자가 위험해져요."],
"Please sign here so we can move quickly.": ["빨리 진행할 수 있도록 여기 이름을 말해 주세요.", "빨리 진행할 수 있도록 저기 서명해 주세요."],
"I'm stopping the medication right now.": ["지금 바로 약 상자를 닫을게요.", "지금 바로 약 목록을 정리할게요."],
"Tell me if the weakness is getting worse.": ["위약감이 가벼워지면 말씀해 주세요.", "졸림이 심해지면 말씀해 주세요."],
"We need an urgent repeat scan of your head.": ["머리 긴급 재촬영 서류가 필요해요.", "머리에 대한 긴급 재촬영 동의가 필요해요."],
"Any new headache or confusion since the medication started?": ["투약 후로 새로운 가려움이나 혼돈이 있었나요?", "약을 투여하기 전에 새로운 두통이나 혼돈이 있었나요?"],
"I'm worried this could mean bleeding in the brain.": ["이게 뇌감염을 의미할까 봐 걱정돼요.", "이게 장출혈을 의미할까 봐 걱정돼요."],
"We'll get the scan done as fast as possible.": ["최대한 조용히 촬영을 끝낼게요.", "최대한 빨리 서류를 끝낼게요."],
"Your right arm looks weaker than it did an hour ago.": ["오른팔이 한 시간 전보다 붉어 보여요.", "오른팔이 한 시간 전보다 무거워 보여요."],
"Stay with me — can you hear my voice?": ["정신 잃지 마세요—제 얼굴이 보이세요?", "정신 잃지 마세요—제 이름이 들리세요?"],
"We're securing your airway to protect your breathing.": ["호흡을 보호하기 위해 침대를 확보할게요.", "체온을 보호하기 위해 기도를 확보할게요."],
"I'm getting the team for intubation now.": ["지금 삽관 전에 가족을 부를게요.", "지금 삽관을 위해 팀을 소개할게요."],
"His eyes are closing and he's not responding to me now.": ["입이 떨리고 있고 지금 제게 반응하지 않아요.", "눈이 감기고 있고 지금 제게 인사하지 않아요."],
"We're calling anesthesia to help secure the airway.": ["기도 확보를 돕기 위해 소아과를 부를게요.", "기도 확보를 돕기 위해 마취과에 방문할게요."],
"Keep watching his breathing while we get everything ready.": ["정리하는 동안 계속 호흡을 지켜봐 주세요.", "준비하기 전에 계속 호흡을 지켜봐 주세요."],
"The team is getting ready for intubation now.": ["지금 팀이 식사 준비를 하고 있어요.", "지금 팀이 삽관 연습을 하고 있어요."],
"Last known well was 08:15, symptom onset unclear.": ["마지막 정상 확인은 08:45였고, 증상 발현 시각은 불명확합니다.", "마지막 정상 확인은 08:15였고, 증상 발현 장소는 불명확합니다."],
"Initial NIHSS was 12, now up to 15.": ["초기 NIHSS는 12였고, 지금은 13까지 올라갔습니다.", "초기 NIHSS는 8이었고, 지금은 15까지 올라갔습니다."],
"tPA was started at 09:40, watch for deterioration.": ["tPA는 09:10에 시작했고, 악화 여부를 지켜봐 주세요.", "tPA는 09:40에 종료했고, 악화 여부를 지켜봐 주세요."],
"He's a sixty-year-old man with left-sided weakness.": ["좌측 위약감이 있는 70세 남성 환자입니다.", "좌측 위약감이 있는 60세 여성 환자입니다."],
"Blood pressure has been stable, no antihypertensives given.": ["체온은 안정적이었고, 항고혈압제는 투여하지 않았습니다.", "혈압은 안정적이었고, 항고혈압제는 구입하지 않았습니다."],
"Repeat CT is scheduled in one hour to check for bleeding.": ["출혈 확인을 위해 30분 후 재촬영이 예정돼 있습니다.", "감염 확인을 위해 한 시간 후 재촬영이 예정돼 있습니다."],
"Please call me if his exam changes at all.": ["신경학적 검사 결과가 나오면 바로 연락 주세요.", "신경학적 점수에 변화가 있으면 바로 연락 주세요."],
"Did you have any neck injury or sudden strain?": ["발에 부상이나 갑자기 무리하게 힘을 준 일이 있었나요?", "목에 부상이나 갑자기 무리하게 웃은 일이 있었나요?"],
"When did the neck pain start compared to the numbness?": ["두통은 무감각보다 먼저 시작됐나요, 나중에 시작됐나요?", "목 통증은 무감각보다 먼저 끝났나요, 나중에 끝났나요?"],
"Have you had any recent chiropractic or heavy lifting?": ["최근에 해외여행을 가거나 무거운 걸 든 적이 있나요?", "어릴 때 카이로프랙틱을 받거나 무거운 걸 든 적이 있나요?"],
"You're young for a stroke, so we look for other causes.": ["뇌졸중을 겪기엔 건강하셔서 다른 원인을 찾아보고 있어요.", "뇌졸중을 겪기엔 젊으셔서 다른 병원을 찾아보고 있어요."],
"A tear in the neck artery can cause a stroke like this.": ["목 동맥의 찢어짐이 이런 감기를 일으킬 수 있어요.", "목 근육의 찢어짐이 이런 뇌졸중을 일으킬 수 있어요."],
"Any recent chiropractic adjustment or heavy gym session?": ["최근에 카이로프랙틱 시술이나 심한 야근을 하셨나요?", "최근에 치과 시술이나 심한 운동을 하셨나요?"],
"We'll image the neck vessels to check for a tear.": ["찢어짐이 있는지 확인하기 위해 목 혈관을 그려 볼게요.", "찢어짐이 있는지 확인하기 위해 목 혈관을 소개할게요."],
"We're watching closely for swelling in the brain.": ["뇌부종이 없는지 자세히 기억하고 있어요.", "손부종이 없는지 자세히 지켜보고 있어요."],
"One pupil is now larger — that's an important change.": ["한쪽 눈꺼풀이 지금 더 무거워졌어요—중요한 변화예요.", "한쪽 동공이 어제 더 커졌어요—중요한 변화예요."],
"I'm alerting the team right away.": ["지금 바로 의사에 알릴게요.", "지금 팀에 보여 줄게요."],
"This can happen with large strokes as the brain swells.": ["큰 뇌졸중에서는 뇌가 식으면서 이런 일이 생길 수 있어요.", "큰 뇌졸중에서는 심장이 부으면서 이런 일이 생길 수 있어요."],
"Check his pupils every fifteen minutes for now.": ["지금부터 15분마다 침대를 확인해 주세요.", "지금부터 15분마다 조명을 확인해 주세요."],
"A bigger pupil on one side can mean rising pressure.": ["한쪽 동공이 더 커지는 건 혈압이 오른다는 뜻일 수 있어요.", "한쪽 눈이 더 붉어지는 건 뇌압이 오른다는 뜻일 수 있어요."],
"We may need to alert the surgeon about this change.": ["이 변화에 대해 마취과의에게 알려야 할 수도 있어요.", "이 변화에 대해 가족에게 알려야 할 수도 있어요."],
}
W = {
"w-numb": {"en": ["limp", "sore"]},
"w-thinner": {"en": ["blood pressure", "blood sugar"]},
"w-fibrillation": {"en": ["frustration", "palpitation"]},
"w-interpreter": {"en": ["interviewer", "investigator"]},
"w-stay-with-me": {"en": ["play with me", "stand by me"]},
"w-strain": {"ko": ["골절(뼈가 부러짐)", "탈구(관절이 빠짐)"]},
"w-tear": {"en": ["tier", "spasm"]},
"w-surgeon": {"en": ["sergeant", "surveyor"]},
}
B = {
"An irregular heartbeat can let clots form inside your heart.": ["An enormous", "A beautiful", "A peaceful"],
"I'm getting an interpreter right now.": ["a wheelchair", "a stretcher", "an ambulance"],
}
if __name__ == "__main__":
    go("er-stroke", S, W, B)
