import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"When did the fever start and how high has it been?":("열이 어디서 시작됐고 얼마나 높이 올랐나요?","열이 언제 시작됐고 얼마나 오래 이어졌나요?"),
"Is she still drinking and making wet diapers?":("아직 잘 자고 기저귀도 젖고 있나요?","아직 잘 마시고 기저귀도 갈고 있나요?"),
"You're doing the right thing by bringing her in.":("이렇게 안고 오신 게 잘하신 거예요.","이렇게 데려오신 게 놀라운 거예요."),
"Has she seemed more tired than usual?":("평소보다 더 보채 보이던가요?","어제보다 더 처져 보이던가요?"),
"Can I feel your forehead, sweetie?":("손 좀 만져봐도 될까, 아가?","이마 좀 닦아봐도 될까, 아가?"),
"I'm going to take her temperature now.":("지금 키를 재 볼게요.","지금 체중을 재 볼게요."),
"We calculate the dose based on his exact weight.":("정확한 체중을 기준으로 용량을 설명해요.","정확한 체중을 기준으로 용량을 준비해요."),
"This amount is safe and carefully measured for him.":("이 양은 안전하고 이 아이에 맞춰 신중하게 포장된 거예요.","이 양은 안전하고 이 아이에 맞춰 천천히 측정된 거예요."),
"I'll double-check every number before he gets it.":("투여하기 전에 숫자를 다시 한번 알려드릴게요.","투여하기 전에 약병을 다시 한번 닦을게요."),
"Every dose here is based on his weight, not just his age.":("모든 용량은 나이가 아니라 체중을 기준으로 약사가 정해요.","모든 용량은 나이가 아니라 체중을 기준으로 가족이 정해요."),
"I know it's scary to watch, but this keeps him safe.":("지켜보시기 힘드실 텐데, 이게 아이를 안전하게 지켜줘요.","지켜보시기 무서우실 텐데, 이게 아이를 편안하게 지켜줘요."),
"Do you have her vaccine card or an app record with you?":("접종 카드나 앱에 있는 사진 가지고 오셨나요?","접종 카드나 앱에 있는 기록 보내 주셨나요?"),
"Let's go through which ones she's had so far.":("오늘 맞은 것들을 같이 확인해 볼게요.","지금까지 먹은 것들을 같이 확인해 볼게요."),
"It's okay if some are missing — we can catch up.":("빠진 게 있어도 괜찮아요 — 지금부터 물어보면 돼요.","틀린 게 있어도 괜찮아요 — 지금부터 채우면 돼요."),
"I'll pull up her records so we don't guess.":("짐작하지 않도록 기록을 출력할게요.","미루지 않도록 기록을 불러올게요."),
"There's no blame here, we just want her protected.":("탓하려는 게 아니라, 그저 아이를 지켜보고 싶은 거예요.","탓하려는 게 아니라, 그저 아이를 안심시키고 싶은 거예요."),
"I'll note today's visit and we can schedule the rest.":("오늘 방문을 알려 두고 나머지는 일정을 잡을게요.","어제 방문을 기록해 두고 나머지는 일정을 잡을게요."),
"For his age, a faster heart rate is completely normal.":("이 나이에는 심박수를 표에서 완전히 찾아볼게요.","이 나이의 심박수가 빠른지 완전히 살펴볼게요."),
"These numbers are right where we'd expect them to be.":("이 수치들을 예상했던 표와 맞춰 볼게요.","이 수치들을 예상했던 범위로 읽어 드릴게요."),
"Let me show you what's normal for a child his age.":("이 나이 아이한테 필요한 게 뭔지 보여드릴게요.","이 나이 아이한테 정상인 게 뭔지 물어볼게요."),
"Children's hearts naturally beat faster than adult hearts.":("아이들의 심장은 원래 어른보다 더 빨리 자라요.","아이들의 심장은 원래 어른보다 더 크게 뛰어요."),
"I'll double-check his numbers against the chart for his age.":("나이에 맞는 표와 수치를 다시 한번 읽어 볼게요.","나이에 맞는 표와 수치를 다시 한번 출력해 볼게요."),
"Can I count your heartbeats with my stethoscope?":("청진기로 내 심장 소리 세어 봐도 될까?","청진기로 곰인형 소리 세어 봐도 될까?"),
"Hi buddy, do you want to help me check your teddy first?":("안녕 친구야, 먼저 네 토끼인형부터 같이 확인해 볼래?","안녕 친구야, 먼저 네 곰인형부터 같이 그려 볼래?"),
"I'm going to be really gentle, I promise.":("정말 조용히 할게, 약속해.","정말 살살 할게, 비밀이야."),
"You're so brave — can you show me your superhero muscles?":("정말 똑똑하네 — 슈퍼히어로 근육 좀 보여줄래?","정말 용감하네 — 슈퍼히어로 망토 좀 보여줄래?"),
"It helps if you stay close and stay calm for him.":("가까이서 차분하게 있어 주시면 선생님한테 도움이 돼요.","가까이서 조용하게 있어 주시면 아이한테 도움이 돼요."),
"Let's pretend your teddy needs a checkup too.":("네 토끼인형도 검진이 필요한 척 해보자.","네 곰인형도 졸린 척 해보자."),
"You can pick the sticker you want after, okay?":("끝나고 원하는 풍선 고를 수 있어, 알겠지?","시작하기 전에 원하는 스티커 고를 수 있어."),
"What you saw was terrifying, but he's stable now.":("보신 건 정말 슬프셨겠지만, 지금은 안정됐어요.","보신 건 정말 무서우셨겠지만, 지금은 검사 중이에요."),
"Febrile seizures are common and usually not harmful.":("열성 경련은 흔하고 대개 밤에 일어나요.","열성 경련은 흔하고 대개 여름에만 일어나요."),
"Let me explain what to watch for and what to do next time.":("다음에 뭘 가져오고 어떻게 해야 할지 설명해 드릴게요.","다음에 뭘 살피고 어디로 가야 할지 설명해 드릴게요."),
"It's scary to witness, but you did everything right.":("목격하시기엔 힘들었겠지만, 다 잘 하셨어요.","목격하시기엔 무서웠겠지만, 아이도 잘 했어요."),
"Most children outgrow febrile seizures by school age.":("대부분의 아이들은 사춘기가 되면 열성 경련이 없어져요.","대부분의 아이들은 유치원 때 열성 경련이 없어져요."),
"If a seizure lasts more than five minutes, call 911 right away.":("열이 5분 넘게 지속되면 바로 911에 전화하세요.","기침이 5분 넘게 지속되면 바로 911에 전화하세요."),
"I can see she's working hard to breathe — we'll help her.":("걷기가 힘들어 보이네요 — 저희가 도와드릴게요.","숨쉬기가 힘들어 보이네요 — 저희가 같이 볼게요."),
"How much is she feeding compared to normal?":("평소에 비해 얼마나 자고 있나요?","어제에 비해 얼마나 먹고 있나요?"),
"I'll show you the signs to watch at home.":("병원에서 살펴야 할 징후를 보여드릴게요.","집에서 살펴야 할 약을 보여드릴게요."),
"Her chest is pulling in a little with every breath.":("숨을 쉴 때마다 가슴이 많이 함몰되고 있어요.","기침할 때마다 가슴이 살짝 함몰되고 있어요."),
"We'll clear her nose and give her oxygen to help her breathe.":("코를 뚫어주고 산소를 줘서 먹는 걸 도와드릴게요.","코를 뚫어주고 산소를 줘서 자는 걸 도와드릴게요."),
"I'll teach you what harder breathing looks like before you go home.":("퇴원 전에 호흡이 힘들어지는 모습이 어떤지 물어볼게요.","퇴원 전에 열이 나는 모습이 어떤지 알려드릴게요."),
"When was her last wet diaper?":("처음으로 기저귀가 젖은 게 언제였나요?","마지막으로 기저귀를 간 게 언제였나요?"),
"Let's try small sips of fluid frequently.":("음식을 조금씩 자주 먹게 해볼게요.","수분을 조금씩 자주 재 볼게요."),
"I'll show you the signs of dehydration to watch for.":("살펴야 할 열 징후를 보여드릴게요.","살펴야 할 탈수 징후를 물어볼게요."),
"Has she vomited today, or is it just loose stools?":("어제 토하기도 했나요, 아니면 무른 변만 있었나요?","오늘 토하기도 했나요, 아니면 기침만 있었나요?"),
"Try small amounts every few minutes instead of a lot at once.":("한 번에 많이보다 조금씩 자주 먹게 해보세요.","한 번에 많이보다 조금씩 자주 안아 보세요."),
"I'll show you how to check for dry lips and sunken eyes at home.":("집에서 입술 마름과 눈 꺼짐을 확인하는 법을 물어볼게요.","집에서 입술 마름과 손 차가움을 확인하는 법을 알려드릴게요."),
"Can you point to the face that shows how much it hurts?":("얼마나 졸린지 보여주는 얼굴을 짚어볼래?","얼마나 아픈지 보여주는 얼굴을 그려볼래?"),
"I'm going to be very gentle and get you medicine soon.":("아주 조용히 할 거고 곧 약도 줄게.","아주 살살 할 거고 곧 엄마도 올게."),
"You're being so brave — squeeze mom's hand if it hurts.":("정말 용감하네 — 아프면 아빠 손을 꽉 잡아.","정말 용감하네 — 무서우면 엄마 손을 꽉 잡아."),
"This is just a quick pinch, then it's all done.":("이건 따끔하고 곧 시작해.","이건 시원하고 금방 끝나."),
"Do you want the cold spray or the bandage first?":("차가운 스프레이랑 스티커 중에 뭘 먼저 할래?","차가운 스프레이랑 밴드 중에 뭘 나중에 할래?"),
"We'll splint the arm and give pain medicine before the X-ray.":("엑스레이 전에 팔을 보고 진통제를 드릴게요.","엑스레이 전에 팔에 부목을 대고 진통제를 설명할게요."),
"Can you tell me exactly what he swallowed and when?":("정확히 뭘 삼켰고 어디였는지 말씀해 주시겠어요?","정확히 뭘 삼켰고 누가 봤는지 말씀해 주시겠어요?"),
"Is he able to breathe and talk normally right now?":("지금 숨쉬고 걷는 게 정상적으로 되나요?","지금 울고 말하는 게 정상적으로 되나요?"),
"You did the right thing bringing him in immediately.":("바로 안고 오신 게 잘하신 거예요.","바로 전화하신 게 잘하신 거예요."),
"Can you describe the coin or toy he had in his hand?":("바닥에 있던 동전이나 장난감을 설명해 주시겠어요?","손에 들고 있던 동전이나 사탕을 설명해 주시겠어요?"),
"Is he drooling or having any trouble swallowing his own saliva?":("침을 흘리거나 자기 침을 뱉는 데 어려움이 있나요?","코를 흘리거나 자기 침을 삼키는 데 어려움이 있나요?"),
"We'll get an X-ray to see exactly where it is.":("정확히 몇 개인지 엑스레이로 확인할게요.","정확히 언제 들어갔는지 엑스레이로 확인할게요."),
"Help me understand exactly how the injury happened.":("다치신 경위를 정확히 이해할 수 있게 그려 주세요.","다치신 시각을 정확히 이해할 수 있게 말씀해 주세요."),
"I'm asking these questions for every child, not just yours.":("이 질문들은 모든 보호자에게 똑같이 드리는 거예요.","이 서류들은 모든 아이에게 똑같이 드리는 거예요."),
"My main focus is making sure he's okay.":("제 가장 큰 관심은 아이가 어디 있는지예요.","제 가장 큰 관심은 부모님이 괜찮은지예요."),
"Can you walk me through what happened just before the fall?":("넘어지기 직후에 무슨 일이 있었는지 차근차근 말씀해 주시겠어요?","넘어지기 직전에 어디 있었는지 차근차근 말씀해 주시겠어요?"),
"This is part of our routine exam for every child who comes in.":("이건 오는 모든 어른에게 하는 일상적인 진찰의 일부예요.","이건 오는 모든 아이에게 하는 일상적인 접수의 일부예요."),
"My job right now is to keep him safe.":("지금 제 역할은 아이를 안전하게 안내하는 거예요.","지금 제 역할은 부모님을 안전하게 지키는 거예요."),
"Tell me what usually helps him stay calm.":("평소에 뭐가 아이를 즐겁게 하는 데 도움이 되는지 알려주세요.","어제 뭐가 아이를 진정시키는 데 도움이 되었는지 알려주세요."),
"I'll dim the lights and keep my voice soft.":("소리를 작게 하고 목소리도 부드럽게 할게요.","불빛을 어둡게 하고 음악도 부드럽게 할게요."),
"We'll go at his pace and follow your lead.":("아이 속도에 맞춰 선생님이 이끄시는 대로 따라갈게요.","아이 취향에 맞춰 부모님이 이끄시는 대로 따라갈게요."),
"Would his favorite toy or some headphones help right now?":("지금 아이가 좋아하는 장난감이나 담요가 도움이 될까요?","어제 아이가 좋아하는 장난감이나 헤드폰이 도움이 되었나요?"),
"We can move slowly and skip anything that feels too loud.":("천천히 진행하고 너무 밝게 느껴지는 건 건너뛸게요.","천천히 진행하고 너무 시끄럽게 느껴지는 건 먼저 알려드릴게요."),
"Please let me know if anything I'm doing is too much for him.":("제가 하는 것 중에 아이에게 너무 어렵다 싶으면 알려주세요.","동료가 하는 것 중에 아이에게 너무 과하다 싶으면 알려주세요."),
"Some of what we talk about can stay private.":("우리가 나누는 얘기 중 일부는 먼저 설명해 줄 수 있어.","우리가 나누는 시간 중 일부는 혼자 있을 수 있어."),
"The only thing I'd share is if your safety was at risk.":("내가 물어볼 유일한 경우는 네 안전이 위험할 때뿐이야.","내가 적을 유일한 경우는 네 안전이 위험할 때뿐이야."),
"You can be honest with me — no judgment here.":("나한테는 솔직해도 돼 — 여기서는 아무도 서두르지 않아.","나한테는 솔직해도 돼 — 여기서는 아무도 보지 않아."),
"Would you like your parents to step out for this part?":("이 부분은 친구가 잠시 나가 계셨으면 좋겠어?","이 부분은 부모님이 잠시 앉아 계셨으면 좋겠어?"),
"Are you sexually active, or using any drugs or alcohol?":("성관계를 하거나 약물이나 담배를 쓰고 있니?","운동을 하거나 약물이나 술을 쓰고 있니?"),
"If you ever feel unsafe at home, please tell me.":("학교에서 불안하다고 느껴지면 언제든 나한테 말해줘.","집에서 불안하다고 느껴지면 언제든 친구한테 말해줘."),
"When did she last feed well, and how long has she been sleepy?":("마지막으로 잘 잔 게 언제고, 얼마나 오래 처져 있었나요?","마지막으로 잘 먹은 게 언제고, 얼마나 오래 울고 있었나요?"),
"The yellow color is something we'll check right away.":("붉은빛은 지금 바로 확인해 볼게요.","노란빛은 지금 바로 설명해 드릴게요."),
"You were right to bring her in — newborns need quick attention.":("데려오신 게 맞아요 — 신생아는 특별한 대응이 필요해요.","데려오신 게 맞아요 — 신생아는 정확한 대응이 필요해요."),
"Has she had fewer wet diapers than usual today?":("오늘 평소보다 더러운 기저귀가 적었나요?","어제 평소보다 젖은 기저귀가 적었나요?"),
"We'll test her blood to see how high her jaundice level is.":("혈액 검사로 황달 수치가 얼마나 높은지 설명할게요.","혈액 검사로 황달 수치가 언제 높아졌는지 확인할게요."),
"Newborns can get sick quickly, so we move fast to check her.":("신생아는 빠르게 자랄 수 있어서 저희도 신속히 확인해요.","신생아는 빠르게 나빠질 수 있어서 저희도 신속히 설명해요."),
"We're giving him epinephrine right now — it works fast.":("지금 바로 에피네프린을 투여하고 있어요 — 한 번만 놓아요.","지금 바로 에피네프린을 투여하고 있어요 — 바로 설명할게요."),
"Stay with me; we're on top of his airway.":("저한테 집중해 주세요 — 기도는 의사가 확실히 챙기고 있어요.","저한테 집중해 주세요 — 기도는 저희가 확실히 기억하고 있어요."),
"You got him here in time — that matters.":("제때 안고 오셨어요 — 그게 중요해요.","제때 데려오셨어요 — 그게 고마워요."),
"His throat is swelling, so we need to act immediately.":("목이 붓고 있어서 바로 설명해야 해요.","손이 붓고 있어서 바로 조치해야 해요."),
"Try to stay calm — panicking makes it harder to help him.":("차분하게 있어 주세요 — 당황하시면 아이를 보기 더 어려워져요.","조용하게 있어 주세요 — 당황하시면 아이를 돕기 더 어려워져요."),
"We know peanuts caused this, so we'll keep him away from them.":("땅콩 때문인 걸 알고 있어서, 앞으로 설명해 드릴게요.","땅콩 때문인 걸 알고 있어서, 앞으로 가족에게 알릴게요."),
"Her signs worry me — we're moving quickly to help her.":("아이 상태가 걱정돼서 — 저희가 조용히 움직이고 있어요.","아이 부모님이 걱정돼서 — 저희가 빠르게 움직이고 있어요."),
"Tell me when this change started.":("이 변화가 어디서 시작됐는지 말씀해 주세요.","이 변화가 언제 끝났는지 말씀해 주세요."),
"We're calling the team so nothing is missed.":("놓치는 게 없도록 가족을 부르고 있어요.","놓치는 게 없도록 팀을 소개하고 있어요."),
"Is she harder to wake up than she was an hour ago?":("하루 전보다 깨우기가 더 힘든가요?","한 시간 전보다 먹이기가 더 힘든가요?"),
"Her skin feels cool and looks a little blotchy.":("피부가 서늘하고 노랗게 보여요.","손이 서늘하고 얼룩덜룩해 보여요."),
"We're moving fast because early treatment saves lives.":("빠른 검사가 생명을 구하기 때문에 저희도 서두르고 있어요.","빠른 치료가 생명을 구하기 때문에 저희도 설명하고 있어요."),
"Our whole team is working on her right now.":("저희 팀 전체가 지금 아이를 지켜보고 있어요.","저희 팀 일부가 지금 아이를 돌보고 있어요."),
"You can stay right here where she can hear your voice.":("아이가 얼굴을 볼 수 있게 바로 여기 계셔도 돼요.","아이가 목소리를 들을 수 있게 바로 밖에 계셔도 돼요."),
"I'll keep telling you what's happening every step.":("매 시간마다 무슨 일이 있는지 계속 말씀드릴게요.","매 단계마다 누가 오는지 계속 말씀드릴게요."),
"We're giving chest compressions and medicine to help her heart.":("심장을 돕기 위해 흉부 압박과 약물을 모두 준비했어요.","심장을 돕기 위해 흉부 압박과 약물을 설명하고 있어요."),
"It's okay to hold her hand while we work.":("저희가 처치하는 동안 아이 발을 잡고 계셔도 돼요.","저희가 처치하는 동안 아이 이름을 불러 주셔도 돼요."),
"Every second counts, and our whole team is focused on her.":("1분이 소중해서, 저희 팀 전체가 아이에게 집중하고 있어요.","1초가 소중해서, 저희 팀 전체가 부모님께 집중하고 있어요."),
"I'm so sorry — we did everything we could, and she didn't survive.":("정말 감사합니다 — 저희가 할 수 있는 모든 걸 다 했지만, 아이는 살아나지 못했어요.","정말 유감입니다 — 저희가 할 수 있는 모든 걸 다 했지만, 아이는 눈을 뜨지 못했어요."),
"Take all the time you need to be with her.":("아이 곁에 있고 싶으신 만큼 충분히 쉬어 가세요.","가족분들과 있고 싶으신 만큼 충분히 시간을 가지세요."),
"You are not alone; we're here with you.":("혼자가 아니에요; 저희가 밖에 있어요.","혼자가 아니에요; 가족이 곁에 있어요."),
"This is not your fault.":("이건 정말 갑작스러운 일이에요.","이건 부모님께 정말 힘든 일이에요."),
"Would you like a chaplain or someone else here with you?":("사회복지사나 다른 누군가가 곁에 있었으면 하시나요?","원목이나 다른 누군가에게 연락했으면 하시나요?"),
"You can hold her for as long as you'd like.":("원하시는 만큼 오래 아이를 씻겨 드릴 수 있어요.","원하시는 만큼 오래 아이 옷을 입혀 드릴 수 있어요."),
"By law, I have to report certain injuries — it's not an accusation.":("법에 따라 특정 질병은 신고해야 해요 — 비난하려는 게 아니에요.","법에 따라 특정 손상은 설명해야 해요 — 비난하려는 게 아니에요."),
"My focus is your child's safety, and I want to work with you.":("제 초점은 아이의 회복이고, 부모님과 함께 풀어 가고 싶어요.","제 초점은 아이의 안전이고, 의사와 함께 풀어 가고 싶어요."),
"A specialist will help us figure this out together.":("전문가가 부모님과 함께 이 상황을 파악하는 걸 도와줄 거예요.","전문가가 저희와 함께 이 상황을 설명하는 걸 도와줄 거예요."),
"I understand this feels upsetting, but I have to follow the process.":("화나게 느껴지실 걸 알지만, 절차를 따라야 해요.","속상하게 느껴지실 걸 알지만, 간호사를 따라야 해요."),
"The specialist will ask both of you the same questions.":("전문가가 두 분께 간단한 질문을 드릴 거예요.","전문가가 두 분께 똑같은 서류를 드릴 거예요."),
"Nothing you say here changes how much we care about your child.":("여기서 뭐라고 하시든 저희가 부모님을 아끼는 마음은 변하지 않아요.","여기서 뭐라고 하시든 저희가 아이를 지켜보는 마음은 변하지 않아요."),
"Her body is low on insulin, and we're correcting it carefully.":("아이 몸에 칼슘이 부족해서, 저희가 신중하게 바로잡고 있어요.","아이 몸에 인슐린이 부족해서, 저희가 신중하게 살피고 있어요."),
"This is a lot to take in — I'll walk you through each step.":("받아들이기 힘드시겠지만 — 단계마다 차근차근 보여 드릴게요.","받아들이기 힘드시겠지만 — 시간마다 차근차근 설명해 드릴게요."),
"She's in the right place and we're helping her now.":("제대로 된 곳에 오셨고 지금 의사가 돕고 있어요.","제때 오셨고 지금 저희가 돕고 있어요."),
"We're giving fluids and insulin through an IV to bring her sugar down safely.":("정맥주사로 수액과 인슐린을 줘서 혈당을 안전하게 재고 있어요.","정맥주사로 수액과 인슐린을 줘서 혈당을 안전하게 알려 드릴게요."),
"Diabetes means her body needs help managing sugar every day.":("당뇨병은 매일 혈압 관리에 몸이 도움을 필요로 한다는 뜻이에요.","당뇨병은 매주 혈당 관리에 몸이 도움을 필요로 한다는 뜻이에요."),
"We'll check her levels often until she's stable and steady.":("안정되고 일정해질 때까지 수치를 자주 설명할게요.","안정되고 일정해질 때까지 식사를 자주 확인할게요."),
"We're giving stronger treatments right now to open his airways.":("지금 더 강한 치료로 열을 내려주고 있어요.","지금 더 빠른 치료로 기도를 열어주고 있어요."),
"Stay close and keep your voice calm for him.":("가까이서 조용한 목소리로 있어 주세요.","가까이서 차분한 모습으로 있어 주세요."),
"We're watching him every second.":("매 시간 아이를 지켜보고 있어요.","매 순간 부모님을 지켜보고 있어요."),
"His oxygen level is dropping, so we're adding more support now.":("체온이 떨어지고 있어서 지금 호흡 보조를 더 올리고 있어요.","산소 수치가 떨어지고 있어서 지금 호흡 보조를 더 설명하고 있어요."),
"If breathing gets any harder, we'll help him with a breathing machine.":("맥박이 더 빨라지면 호흡 보조 기계로 도와드릴게요.","호흡이 더 힘들어지면 호흡 보조 기계를 설명해 드릴게요."),
"You're doing great staying calm — it really helps him.":("차분히 계셔주셔서 정말 잘하고 계세요 — 저희한테 큰 도움이 돼요.","조용히 계셔주셔서 정말 잘하고 계세요 — 아이한테 큰 도움이 돼요."),
}
S.update({
"When did the fever start and how high has it been?":("열이 어제 시작됐고 얼마나 높이 올랐나요?","열이 언제 시작됐고 얼마나 오래 이어졌나요?"),
"Every dose here is based on his weight, not just his age.":("모든 용량은 나이가 아니라 체중을 기준으로 약사가 정해요.","모든 용량은 나이가 아니라 체중을 보고 가족이 정해요."),
"These numbers are right where we'd expect them to be.":("이 수치들을 예상했던 표와 맞춰 볼게요.","이 수치들을 예상했던 범위로 읽어요."),
"Can I count your heartbeats with my stethoscope?":("청진기로 숨 소리 세어 봐도 될까?","청진기로 곰인형 소리 세어 봐도 될까?"),
"I'm going to be really gentle, I promise.":("정말 빨리 할게, 약속해.","정말 살살 할게, 비밀이야."),
"I'm going to be very gentle and get you medicine soon.":("아주 빨리 할 거고 곧 약도 줄게.","아주 살살 할 거고 곧 엄마도 올게."),
"Do you want the cold spray or the bandage first?":("차가운 스프레이랑 스티커 중에 뭘 먼저 할래?","차가운 스프레이랑 밴드 중에 뭘 고를래?"),
"My main focus is making sure he's okay.":("제 가장 큰 관심은 아이가 어디 있는지예요.","제 가장 큰 관심은 엄마가 괜찮은지예요."),
"My job right now is to keep him safe.":("지금 제 역할은 아이를 안전하게 안내하는 거예요.","지금 제 역할은 엄마를 안전하게 지키는 거예요."),
"If you ever feel unsafe at home, please tell me.":("밖에서 불안하다고 느껴지면 언제든 나한테 말해줘.","집에서 불안하다고 느껴지면 언제든 친구한테 말해줘."),
"You were right to bring her in — newborns need quick attention.":("데려오신 게 맞아요 — 신생아는 큰 대응이 필요해요.","데려오신 게 맞아요 — 신생아는 정확한 대응이 필요해요."),
"We're calling the team so nothing is missed.":("놓치는 게 없도록 가족을 부르고 있어요.","놓치는 게 없도록 팀을 바꾸고 있어요."),
"We're giving chest compressions and medicine to help her heart.":("심장을 돕기 위해 흉부 압박과 약물을 줄 거예요.","심장을 돕기 위해 흉부 압박과 약물을 설명하고 있어요."),
"This is not your fault.":("이건 정말 갑작스러운 일이에요.","부모님께 힘든 일이에요."),
"You can hold her for as long as you'd like.":("원하시는 만큼 아이를 씻겨 드릴 수 있어요.","원하시는 만큼 오래 아이 옷을 입혀 드릴 수 있어요."),
"Nothing you say here changes how much we care about your child.":("여기서 뭐라고 하시든 저희가 부모님을 아끼는 마음은 변하지 않아요.","여기서 뭐라고 하시든 저희가 아이를 보는 마음은 변하지 않아요."),
"Let's pretend your teddy needs a checkup too.":("네 토끼인형도 검진이 필요한 척 해보자.","네 곰인형도 검진이 끝난 척 해보자."),
})
W2={'w-temperature':(None,['temperament','temperate']),'w-measure':(None,['match','mature']),'w-doublecheck':(None,['double-click','double-dose']),
'w-catchup':(['따라하다','미루다'],None),'w-adult':(None,['adopt','addict']),'w-xray':(None,['CT scan','MRI'])}
W={'w-walk':(['뒤따라가다','나중에 알리다'],['work you through','walk you down']),
'w-epinephrine':(None,['ephedrine','dopamine']),
'w-work':(['(처치를) 미루다','(처치를) 쉬다'],None),
'w-alltime':(['정해진 시간에 맞춰','서둘러서 빠르게'],['all the time you knew','all the room you need'])}
B={"I'm going to take her temperature now.":('temperature',['photograph','sweatshirt','appointment']),
"Help me understand exactly how the injury happened.":('understand',['imagine','remember','pretend']),
"I understand this feels upsetting, but I have to follow the process.":('upsetting',['ordinary','exciting','pleasant']),
"We're giving stronger treatments right now to open his airways.":('treatments',['bandages','blankets','vitamins'])}
W.update(W2)
apply('er-peds',S,W,B)
