import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_lib_5 import run
P = os.path.join(os.path.dirname(os.path.abspath(__file__)), "base-er-gi-bleed.yaml")
S = {
# 상부 vs 하부 출혈 문진
"Did you vomit any blood or something that looked like coffee grounds?": ["피를 토했거나 찻잎 같은 것을 토하셨나요?", "피를 삼켰거나 커피 찌꺼기 같은 것을 토하셨나요?"],
"Have your stools been black and tarry, or bright red?": ["변이 검고 묽었나요, 아니면 선홍색이었나요?", "변이 검고 끈적했나요, 아니면 초록색이었나요?"],
"When did you first notice this?": ["누가 처음 알아차리셨어요?", "어디서 처음 알아차리셨어요?"],
"How much blood do you think you brought up?": ["게워내신 피가 얼마나 진하다고 생각하세요?", "삼키신 피가 얼마나 많다고 생각하세요?"],
"I need to know if the bleeding is coming from above or below.": ["출혈이 위쪽에서 오는지 뒤쪽에서 오는지 알아야 해요.", "출혈이 앞쪽에서 오는지 아래쪽에서 오는지 알아야 해요."],
"Can you describe the exact color of what you vomited?": ["토하신 것의 정확한 양을 설명해 주시겠어요?", "토하신 것의 정확한 냄새를 설명해 주시겠어요?"],
# 활력·기립성 저혈압
"Do you feel dizzy or lightheaded when you stand up?": ["일어설 때 어지럽거나 속이 메스꺼우세요?", "누울 때 어지럽거나 머리가 띵하세요?"],
"Have you fainted or nearly passed out?": ["실신했거나 거의 넘어질 뻔했나요?", "넘어졌거나 거의 의식을 잃을 뻔했나요?"],
"I'm going to check your blood pressure lying down and standing up.": ["누운 상태와 선 상태에서 체온을 확인할게요.", "누운 상태와 앉은 상태에서 혈압을 확인할게요."],
"Did you almost fall when you felt dizzy?": ["어지러웠을 때 거의 토하실 뻔했나요?", "어지러웠을 때 거의 숨이 막히실 뻔했나요?"],
"How much blood do you think you have lost so far?": ["지금까지 피를 얼마나 받았다고 생각하세요?", "지금까지 약을 얼마나 먹었다고 생각하세요?"],
"We need to watch your blood pressure closely for a while.": ["당분간 체온을 자세히 지켜봐야 해요.", "당분간 식사량을 자세히 지켜봐야 해요."],
# NSAID·항응고제 복용력
"Which blood thinner do you take, and when was your last dose?": ["어떤 항응고제를 복용하시고, 마지막 검사는 언제였나요?", "어떤 항응고제를 복용하시고, 마지막 식사는 언제였나요?"],
"How often do you take pain relievers like ibuprofen?": ["이부프로펜 같은 진통제를 얼마나 오래 드셨어요?", "오메프라졸 같은 위장약을 얼마나 자주 드세요?"],
"Do you take any aspirin regularly?": ["타이레놀을 규칙적으로 드세요?", "아스피린을 식후에 드세요?"],
"Are you taking these medicines every day or only sometimes?": ["이 약들을 매일 드세요, 아니면 아침에만 드세요?", "이 약들을 매일 드세요, 아니면 가끔 바꾸세요?"],
"These medicines can raise your risk of bleeding.": ["이 약들이 감염 위험을 높일 수 있어요.", "이 약들이 알레르기 위험을 높일 수 있어요."],
"We may need to stop one of these medicines for now.": ["지금은 이 약들 중 하나를 다시 처방받아야 할 수도 있어요.", "지금은 이 약들 중 하나를 가져오셔야 할 수도 있어요."],
# 흑색변 주소 노인
"How many days have your stools looked black?": ["며칠째 변이 노란색으로 보이시나요?", "며칠째 소변이 검은색으로 보이시나요?"],
"Have you felt more tired or short of breath than usual?": ["평소보다 더 목마르거나 숨이 차셨나요?", "평소보다 더 피곤하거나 가려우셨나요?"],
"Have you had any belly pain along with this?": ["이와 함께 무릎이 아프기도 하셨나요?", "이와 함께 허리가 아프기도 하셨나요?"],
"Has the color or amount changed at all?": ["모양이나 양이 조금이라도 변했나요?", "색이나 냄새가 조금이라도 변했나요?"],
"Do you feel weak or more tired than before?": ["전보다 저리거나 더 피곤하세요?", "전보다 힘이 없거나 더 목마르세요?"],
"We'll check your blood count to look for anemia.": ["당뇨가 있는지 혈액 수치를 확인할게요.", "빈혈이 있는지 소변 수치를 확인할게요."],
# 대량 정맥로 확보 설명
"We need two large IVs in case you need fluids or blood quickly.": ["수액이나 약이 급히 필요할 경우를 대비해 큰 정맥로 두 개가 필요해요.", "수액이나 혈액이 급히 필요할 경우를 대비해 큰 수액 걸이 두 개가 필요해요."],
"You may feel a pinch, but it will be over fast.": ["저릴 수 있지만 금방 끝날 거예요.", "차가울 수 있지만 금방 끝날 거예요."],
"This helps us treat you as safely and quickly as possible.": ["이렇게 하면 가능한 한 안전하고 빠르게 검사할 수 있어요.", "이렇게 하면 가능한 한 안전하고 빠르게 이동할 수 있어요."],
"One IV goes in each arm so we can work fast.": ["빨리 처치할 수 있도록 각 팔에 이름표를 하나씩 붙일게요.", "빨리 처치할 수 있도록 각 팔에 혈압 측정기를 하나씩 감을게요."],
"The needle pinch lasts only a second.": ["압박대 조임은 잠깐이면 지나가요.", "소독약 차가움은 잠깐이면 지나가요."],
"I'll stay right here with you the whole time.": ["제가 처음부터 끝까지 바로 여기서 설명할게요.", "제가 처음부터 끝까지 바로 밖에 있을게요."],
# 정맥류 출혈(간경변)
"Do you have a history of liver disease or cirrhosis?": ["신장질환이나 신부전 병력이 있으세요?", "폐질환이나 폐렴 병력이 있으세요?"],
"How much blood did you vomit, and when?": ["피를 얼마나 토하셨고, 어디서였나요?", "피를 얼마나 삼키셨고, 언제였나요?"],
"We'll start a medicine to reduce the bleeding and prepare for an endoscopy.": ["출혈을 줄이는 약을 시작하고 엑스레이를 준비할게요.", "출혈을 줄이는 약을 시작하고 소변 검사를 준비할게요."],
"Have you been drinking alcohol heavily in the past?": ["과거에 커피를 심하게 드셨나요?", "과거에 담배를 심하게 피우셨나요?"],
"This medicine will help lower the pressure in your veins.": ["이 약이 정맥의 통증을 낮추는 데 도움이 될 거예요.", "이 약이 위의 산도를 낮추는 데 도움이 될 거예요."],
"The doctor will look inside your stomach with a small camera.": ["의사 선생님이 작은 카메라로 귀 안쪽을 들여다볼 거예요.", "의사 선생님이 작은 카메라로 폐 안쪽을 들여다볼 거예요."],
# 소화성 궤양 토혈
"The coffee-ground appearance suggests bleeding in your stomach.": ["커피 찌꺼기 같은 모습은 위에서 염증이 있음을 시사해요.", "녹색 담즙 같은 모습은 위에서 출혈이 있음을 시사해요."],
"Have you had heartburn or ulcer problems before?": ["전에 변비나 궤양 문제가 있으셨나요?", "전에 속쓰림이나 천식 문제가 있으셨나요?"],
"We'll start an IV acid-reducing medicine and plan for an endoscopy.": ["위산을 줄이는 정맥주사 약을 시작하고 수술을 계획할게요.", "위산을 줄이는 정맥주사 약을 시작하고 CT를 계획할게요."],
"Do you often get heartburn after eating spicy food?": ["짠 음식을 드신 후에 자주 속이 쓰리세요?", "차가운 음식을 드신 후에 자주 속이 쓰리세요?"],
"Have you ever been treated for a stomach ulcer before?": ["전에 구내염으로 치료받으신 적 있으세요?", "전에 피부 궤양으로 치료받으신 적 있으세요?"],
"The medicine will lower the acid in your stomach.": ["이 약이 열을 낮춰줄 거예요.", "이 약이 혈압을 낮춰줄 거예요."],
# 하부 GI 대량 혈변
"How many times have you passed blood, and how much each time?": ["지금까지 몇 번, 매번 얼마나 변을 보셨나요?", "지금까지 몇 번, 매번 얼마나 소변을 보셨나요?"],
"Is the blood bright red or mixed in with the stool?": ["피가 묽은가요, 아니면 변에 섞여 있나요?", "피가 선홍색인가요, 아니면 구토에 섞여 있나요?"],
"You'll likely need a colonoscopy to find the source.": ["원인을 찾기 위해 조직검사가 필요할 것 같아요.", "원인을 찾기 위해 위내시경이 필요할 것 같아요."],
"Does the blood come out with the stool or by itself?": ["피가 소변과 함께 나오나요, 아니면 따로 나오나요?", "피가 변과 함께 나오나요, 아니면 구토와 함께 나오나요?"],
"We'll need to check your blood count and watch your vital signs.": ["혈액 수치를 확인하고 소변량을 지켜볼게요.", "혈당 수치를 확인하고 활력징후를 지켜볼게요."],
"The colonoscopy will help the doctor find where the bleeding is coming from.": ["위내시경으로 출혈이 어디서 오는지 의사 선생님이 찾을 수 있을 거예요.", "대장내시경으로 출혈이 언제 시작됐는지 의사 선생님이 알 수 있을 거예요."],
# 와파린 과다 출혈
"When did you last have your INR checked?": ["마지막으로 혈당을 언제 확인하셨나요?", "마지막으로 콜레스테롤을 언제 확인하셨나요?"],
"How much warfarin do you take each day?": ["일주일에 와파린을 얼마나 드세요?", "하루에 와파린을 언제 드세요?"],
"We'll give medicine to reverse the blood thinner and stop the bleeding.": ["항응고제를 역전시키고 통증을 멈추는 약을 드릴게요.", "항응고제를 역전시키고 구토를 멈추는 약을 드릴게요."],
"Has your doctor changed your warfarin dose recently?": ["최근에 의사 선생님이 와파린 상표를 바꾸셨나요?", "최근에 의사 선생님이 와파린 일정을 바꾸셨나요?"],
"We'll give you vitamin K to help reverse the effect.": ["식욕을 돋우도록 비타민K를 드릴게요.", "통증을 줄이도록 비타민K를 드릴게요."],
"Your blood will need to be checked again after treatment.": ["치료 후에 소변을 다시 확인해야 해요.", "치료 후에 상처를 다시 확인해야 해요."],
# 수혈 동의·부작용 설명
"A transfusion replaces the blood you've lost to keep you safe.": ["수혈은 잃으신 수분을 대체해서 안전하게 지켜줘요.", "수혈은 잃으신 피를 대체해서 편안하게 지켜줘요."],
"Tell me right away if you feel chills, itching, or trouble breathing.": ["오한, 목마름, 숨쉬기 곤란을 느끼면 바로 말씀해 주세요.", "허기, 가려움, 숨쉬기 곤란을 느끼면 바로 말씀해 주세요."],
"We'll watch you closely during the transfusion.": ["수혈하는 동안 자세히 설명해 드릴게요.", "수혈하기 전에 자세히 지켜볼게요."],
"A transfusion is generally very safe, but reactions can happen.": ["수혈은 대체로 매우 빠르지만 반응이 생길 수 있어요.", "수혈은 대체로 매우 간단하지만 반응이 생길 수 있어요."],
"If you feel any different, please tell us immediately.": ["조금이라도 다르게 느껴지면 바로 저희에게 보여 주세요.", "조금이라도 다르게 보이면 바로 저희에게 말씀해 주세요."],
"We'll check your temperature and pulse often during the transfusion.": ["수혈하는 동안 체중과 맥박을 자주 확인할게요.", "수혈하는 동안 체온과 소변을 자주 확인할게요."],
# Mallory-Weiss(반복 구토 후)
"Did the vomiting come before you noticed the blood?": ["기침이 피를 알아차리기 전에 있었나요?", "통증이 피를 알아차리기 전에 있었나요?"],
"How many times had you vomited beforehand?": ["그 전에 몇 번 기침하셨나요?", "그 전에 몇 시간 구토하셨나요?"],
"Have you been drinking alcohol recently?": ["최근에 커피를 드셨나요?", "최근에 주스를 드셨나요?"],
"Which happened first, the vomiting or the blood?": ["구토와 통증 중에 무엇이 먼저였나요?", "기침과 피 중에 무엇이 먼저였나요?"],
"Was there any blood the first few times you vomited?": ["처음 몇 번 토하셨을 때 담즙이 있었나요?", "처음 몇 번 토하셨을 때 음식이 있었나요?"],
"How much alcohol do you usually drink in a week?": ["하루에 술을 보통 얼마나 드세요?", "일주일에 커피를 보통 얼마나 드세요?"],
# 출혈+빈혈 실신
"Do you feel dizzy or weak when you sit up?": ["일어나 앉을 때 졸리거나 힘이 없으세요?", "일어나 앉을 때 어지럽거나 배가 고프세요?"],
"Please call us before getting out of bed.": ["침대에서 나오시기 전에 저희가 불을 켜 드려요.", "침대에서 나오시기 전에 저희가 신발을 놔 드려요."],
"We're keeping the bed low and the rails up to prevent a fall.": ["욕창을 막기 위해 침대를 낮추고 난간을 올려둘게요.", "감염을 막기 위해 침대를 낮추고 난간을 올려둘게요."],
"How long were you unconscious when you fainted?": ["실신하셨을 때 얼마나 오래 누워 계셨나요?", "실신하셨을 때 얼마나 오래 혼자 계셨나요?"],
"We don't want you to fall and get hurt again.": ["다시 넘어져서 놀라지 않으셨으면 해요.", "다시 넘어져서 창피하지 않으셨으면 해요."],
"Someone will help you get up every time.": ["매번 누군가 일어나실 때 베개를 고쳐 드릴게요.", "매번 누군가 일어나실 때 물을 따라 드릴게요."],
# 여호와의증인 수혈 거부
"I respect your decision and want to understand your wishes fully.": ["결정을 존중하고 바람을 완전히 기록하고 싶어요.", "결정을 존중하고 바람을 빨리 이해하고 싶어요."],
"There are other treatments we can use to support you.": ["환자분을 돕기 위해 쓸 수 있는 다른 병원들이 있어요.", "환자분을 돕기 위해 쓸 수 있는 다른 일정들이 있어요."],
"Let's document your preferences clearly with the team.": ["팀과 함께 환자분의 선호를 명확하게 번역해 둘게요.", "팀과 함께 환자분의 일정을 명확하게 기록해 둘게요."],
"Can you tell me more about your beliefs regarding blood transfusions?": ["수혈에 관한 환자분의 증상을 더 말씀해 주시겠어요?", "수혈에 관한 환자분의 알레르기를 더 말씀해 주시겠어요?"],
"We will do everything possible without using blood products.": ["혈액 제품을 쓰지 않고 가능한 모든 것을 설명드릴게요.", "혈액 제품을 쓰지 않고 가능한 모든 것을 물어볼게요."],
"The team will respect your wishes throughout your care.": ["치료 내내 팀이 환자분의 바람을 기록할 거예요.", "치료 내내 팀이 환자분의 가족을 존중할 거예요."],
# 재출혈 이력 통합
"Tell me about the endoscopy you had before.": ["전에 받으신 조직검사에 대해 말씀해 주세요.", "전에 받으신 수술에 대해 말씀해 주세요."],
"Do you know what was found or treated last time?": ["지난번에 무엇이 발견됐거나 검사됐는지 아세요?", "지난번에 누가 발견했거나 치료했는지 아세요?"],
"Has this type of bleeding happened more than once?": ["이런 종류의 통증이 한 번 넘게 있었나요?", "이런 종류의 구토가 한 번 넘게 있었나요?"],
"How many years ago was your last procedure?": ["마지막 시술이 몇 달 전이었나요?", "마지막 검진이 몇 년 전이었나요?"],
"Did the doctors say anything about the cause back then?": ["그때 의사 선생님들이 비용에 대해 뭐라고 하셨나요?", "그때 의사 선생님들이 계획에 대해 뭐라고 하셨나요?"],
"This history helps us understand your risk of bleeding again.": ["이 병력이 감염 위험을 이해하는 데 도움이 돼요.", "이 병력이 재출혈 비용을 이해하는 데 도움이 돼요."],
# 항혈소판제 심장환자 출혈
"Which heart medicines are you taking, like aspirin or clopidogrel?": ["아스피린이나 클로피도그렐 같은 어떤 위장약을 드세요?", "아스피린이나 클로피도그렐 같은 어떤 수면제를 드세요?"],
"Have you had a stent or heart procedure recently?": ["최근에 스텐트나 위 시술을 받으셨나요?", "최근에 스텐트나 심장 시술을 예약하셨나요?"],
"The team will weigh your bleeding against your clot risk carefully.": ["팀이 출혈과 응고 위험을 신중하게 설명드릴 거예요.", "팀이 출혈과 감염 위험을 신중하게 저울질할 거예요."],
"How long have you been taking this medicine for your heart?": ["이 심장약을 얼마나 자주 드셨나요?", "이 심장약을 얼마나 많이 드셨나요?"],
"Stopping this medicine too soon could increase your clot risk.": ["이 약을 너무 일찍 끊으면 감염 위험이 늘어날 수 있어요.", "이 약을 너무 일찍 끊으면 통증이 늘어날 수 있어요."],
"The heart doctor and the stomach doctor will decide together.": ["심장 의사와 소화기 의사가 함께 설명할 거예요.", "심장 의사와 마취과 의사가 함께 결정할 거예요."],
# 출혈성 쇼크 인지
"Your heart rate is high and your pressure is dropping — we're acting now.": ["심박수는 높고 체온은 떨어지고 있어요 — 지금 바로 조치할게요.", "심박수는 높고 혈압은 떨어지고 있어요 — 지금 바로 설명드릴게요."],
"We're giving fluids and blood right away.": ["수액과 혈액을 바로 확인할게요.", "수액과 혈액을 바로 기록할게요."],
"Stay with me while the team gets everything ready.": ["팀이 모든 걸 준비하는 동안 가족과 함께 있어 주세요.", "약국이 모든 걸 준비하는 동안 저와 함께 있어 주세요."],
"Your heart is beating very fast right now.": ["심장이 지금 아주 불규칙하게 뛰고 있어요.", "심장이 지금 아주 약하게 뛰고 있어요."],
"We need to act quickly to keep you safe.": ["안전하게 지켜드리려면 조용히 조치해야 해요.", "안전하게 지켜드리려면 정확하게 조치해야 해요."],
"More blood is on the way for you.": ["수액이 더 오고 있어요.", "약이 더 오고 있어요."],
# 정맥류 대량 토혈 기도위험
"We're turning you on your side to protect your airway.": ["피부를 보호하기 위해 옆으로 돌려드릴게요.", "허리를 보호하기 위해 옆으로 돌려드릴게요."],
"Suction is ready to keep your airway clear.": ["기도를 깨끗하게 유지하도록 산소 준비가 됐어요.", "기도를 깨끗하게 유지하도록 가습기 준비가 됐어요."],
"We may need a special tube to control the bleeding.": ["출혈을 조절하기 위해 특수한 약이 필요할 수도 있어요.", "출혈을 조절하기 위해 특수한 팀이 필요할 수도 있어요."],
"You're bringing up a lot of blood very quickly.": ["아주 빠르게 많은 물을 게워내고 계세요.", "아주 빠르게 많은 침을 게워내고 계세요."],
"We're going to suction your mouth to help you breathe.": ["침 삼키는 걸 돕기 위해 입안을 흡인할게요.", "말하는 걸 돕기 위해 입안을 흡인할게요."],
"This tube will press on the bleeding vessel to stop it.": ["이 튜브가 출혈 혈관을 씻어서 멈추게 할 거예요.", "이 튜브가 출혈 혈관을 빼내서 멈추게 할 거예요."],
# 응고병증 동반 출혈
"Do you have a known bleeding or clotting disorder?": ["알려진 출혈이나 수면 장애가 있으세요?", "알려진 출혈이나 호흡 장애가 있으세요?"],
"We're ordering platelets and plasma to help you clot.": ["통증을 줄이기 위해 혈소판과 혈장을 요청할게요.", "수면을 돕기 위해 혈소판과 혈장을 요청할게요."],
"I'm giving the team an SBAR update on your labs now.": ["지금 엑스레이 결과에 대해 팀에 SBAR로 업데이트할게요.", "지금 식사량에 대해 팀에 SBAR로 업데이트할게요."],
"Are you still bleeding from the same spot?": ["여전히 같은 부위에서 통증이 있나요?", "여전히 같은 부위에서 멍이 보이나요?"],
"Your blood isn't clotting the way it should right now.": ["지금 혈액이 제대로 순환되지 않고 있어요.", "지금 소변이 제대로 나오지 않고 있어요."],
"The doctor needs to know your labs as soon as possible.": ["의사 선생님이 최대한 빨리 엑스레이 결과를 알아야 해요.", "의사 선생님이 최대한 빨리 가족 연락처를 알아야 해요."],
# 내시경 중 급속악화
"Your vitals are dropping, so we're pausing the procedure.": ["활력징후가 떨어지고 있어서 보호자를 잠시 부를게요.", "활력징후가 떨어지고 있어서 조명을 잠시 켤게요."],
"We're giving you fluids and calling for extra help.": ["수액을 확인하고 추가 도움을 요청할게요.", "수액을 드리고 추가 담요를 요청할게요."],
"Stay with me — we're right here with you.": ["저와 함께 숨 쉬어 주세요 — 바로 여기 있어요.", "저를 보고 있어 주세요 — 바로 여기 있어요."],
"Your oxygen level is falling quickly right now.": ["혈당 수치가 지금 빠르게 떨어지고 있어요.", "체온 수치가 지금 빠르게 떨어지고 있어요."],
"We're stopping the procedure to keep you safe.": ["안전하게 지켜드리려고 시술을 설명할게요.", "안전하게 지켜드리려고 조명을 켤게요."],
"More help is coming into the room right now.": ["지금 더 많은 약이 병실로 오고 있어요.", "지금 더 많은 가족이 병실로 오고 있어요."],
# 하부출혈 지속 색전술 이송
"The bleeding hasn't stopped, so we're sending you to a specialist.": ["출혈이 멈추지 않아서 검사실에 보내드릴게요.", "출혈이 멈추지 않아서 전문의에게 설명드릴게요."],
"They'll block the bleeding vessel through a small catheter.": ["작은 바늘을 통해 출혈 혈관을 막을 거예요.", "작은 카메라를 통해 출혈 혈관을 막을 거예요."],
"I'll hand off all your information to the next team.": ["다음 팀에게 모든 정보를 요청할게요.", "같은 팀에게 모든 정보를 인계할게요."],
"This procedure will find and stop the bleeding vessel.": ["이 시술로 출혈 혈관을 찾아 기록할 거예요.", "이 시술로 출혈 혈관을 찾아 보호할 거예요."],
"You'll be moved to a different room for this procedure.": ["이 시술을 위해 큰 방으로 옮겨질 거예요.", "이 시술을 위해 조용한 방으로 옮겨질 거예요."],
"The next team will know your full history and current condition.": ["다음 팀이 전체 병력과 가족 연락처를 알게 될 거예요.", "다음 팀이 전체 병력과 현재 위치를 알게 될 거예요."],
# 재출혈 급변 야간 SBAR
"How does the bleeding compare to earlier tonight?": ["통증이 오늘 밤 아까와 비교해서 어떤가요?", "메스꺼움이 오늘 밤 아까와 비교해서 어떤가요?"],
"Your vital signs have changed, so I'm calling the doctor.": ["활력징후가 변해서 약사 선생님을 부를게요.", "활력징후가 변해서 목사님을 부를게요."],
"I'll report your situation, background, and vitals clearly.": ["상황, 배경, 활력징후를 조용히 보고할게요.", "상황, 배경, 활력징후를 간단하게 보고할게요."],
"Is the blood darker or lighter than before?": ["변이 전보다 더 어두운가요, 아니면 더 밝은가요?", "소변이 전보다 더 어두운가요, 아니면 더 밝은가요?"],
"I'm watching your vitals closely tonight.": ["오늘 밤 소변량을 자세히 지켜보고 있어요.", "오늘 밤 식사량을 자세히 지켜보고 있어요."],
"The doctor needs to hear about this change right away.": ["약사 선생님이 이 변화에 대해 바로 들어야 해요.", "목사님이 이 변화에 대해 바로 들어야 해요."],
}
W = {
 "w-coffee-grounds": {"distractorsEn": ["coffee beans", "cocoa powder"]},
 "w-tarry": {"distractorsKo": ["묽은 갈색의", "딱딱한"]},
 "w-thinner": {"distractorsEn": ["blood sugar pill", "stool softener"]},
 "w-ibuprofen": {"distractorsEn": ["tramadol", "naproxen"]},
 "w-aspirin": {"distractorsEn": ["ibuprofen", "codeine"]},
 "w-itself": {"distractorsEn": ["yourself", "himself"]},
 "w-source": {"distractorsKo": ["(출혈의) 결과", "(출혈의) 경과"]},
 "w-temperature": {"distractorsEn": ["temperament", "temperance"]},
 "w-beforehand": {"distractorsEn": ["afterward", "overhand"]},
 "w-product": {"distractorsKo": ["(혈액) 검체", "프로토콜"]},
 "w-ago": {"distractorsKo": ["(지금부터) 뒤", "(지금부터) 동안"]},
 "w-rate": {"distractorsKo": ["(분당) 리듬", "(정상) 범위"]},
 "w-oxygen": {"distractorsEn": ["nitrogen", "hydrogen"]},
 "w-background": {"distractorsEn": ["baseline", "backbone"]},
}
B = {
 "How long were you unconscious when you fainted?": ["embarrassed", "unprepared", "uncertain"],
 "This history helps us understand your risk of bleeding again.": ["overlook", "eliminate", "postpone"],
 "You'll be moved to a different room for this procedure.": ["spacious", "freezing", "crowded"],
}
run(P, S, W, B)
