from dk_lib import run
S={
"When did you last take your insulin?":["마지막으로 혈당을 언제 재셨어요?","마지막으로 인슐린을 어디에 맞으셨어요?"],
"When did you last eat?":["마지막으로 언제 주무셨어요?","마지막으로 어디서 드셨어요?"],
"Can you tell me what type of insulin you take?":["어떤 종류의 약을 쓰시는지 말씀해 주시겠어요?","어떤 회사의 인슐린을 쓰시는지 말씀해 주시겠어요?"],
"I'm going to check your blood sugar now.":["지금 혈압을 확인할게요.","지금 체온을 확인할게요."],
"I'll prick your finger for a quick blood sample.":["손끝을 소독해서 혈액을 조금 채취할게요.","손끝을 찔러 혈액을 조금 닦아 낼게요."],
"Are you feeling any symptoms right now?":["지금 어떤 약을 드시고 계신가요?","어제 어떤 증상이 있으셨나요?"],
"Do you feel shaky, sweaty, or dizzy?":["떨리거나 땀이 나거나 졸리신가요?","떨리거나 춥거나 어지러우신가요?"],
"How much insulin did you take today?":["오늘 인슐린을 어디에 맞으셨어요?","어제 인슐린을 얼마나 맞으셨어요?"],
"Let's have you take some juice or glucose tablets now.":["지금 주스나 포도당 알약이 있는지 찾아볼게요.","지금 주스나 포도당 알약을 드신 시각을 적어 둘게요."],
"We'll recheck your sugar in fifteen minutes.":["십오 분 뒤에 혈압을 다시 잴게요.","십오 분 뒤에 체온을 다시 잴게요."],
"You might feel better once your sugar comes back up.":["혈당이 다시 오르면 식사를 드시게 할게요.","혈당이 다시 오르면 잠이 오실 거예요."],
"We'll keep watching you until you feel normal again.":["정상으로 돌아올 때까지 계속 물어볼게요.","보호자가 올 때까지 계속 지켜볼게요."],
"How often have you been urinating?":["물을 얼마나 자주 마셨어요?","대변을 얼마나 자주 보셨어요?"],
"Have you been unusually thirsty or tired?":["평소보다 허기지거나 피곤하셨어요?","평소보다 갈증이 나거나 어지러우셨어요?"],
"Have you been able to keep up with drinking fluids?":["식사는 충분히 해오셨어요?","소변 배출은 충분히 해오셨어요?"],
"How many days have you been feeling this way?":["몇 주째 이러셨어요?","몇 시간째 이러셨어요?"],
"Do you have a history of diabetes in your family?":["가족 중에 심장병 병력이 있으신가요?","본인에게 당뇨병 병력이 있으신가요?"],
"We'll check your blood sugar and look for ketones too.":["혈압도 확인하고 케톤도 함께 볼게요.","혈당도 확인하고 칼륨도 함께 볼게요."],
"Can you show me how you usually give your insulin?":["평소 인슐린을 어디에 놓으시는지 보여주시겠어요?","평소 인슐린을 어떻게 보관하시는지 보여주시겠어요?"],
"Which spots do you use, and do you rotate them?":["어느 부위를 쓰시고, 직접 놓으시나요?","어느 주사기를 쓰시고, 돌아가며 놓으시나요?"],
"Have you missed any doses recently?":["최근에 주사를 바꾸신 적 있으세요?","최근에 식사를 빠뜨리신 적 있으세요?"],
"Where on your body do you usually inject?":["보통 하루 몇 번 주사하세요?","보통 누가 주사해 주세요?"],
"Let me walk you through the steps one more time.":["단계를 한 번 더 적어 드릴게요.","설명서를 한 번 더 가져다 드릴게요."],
"Rotating your sites helps prevent skin problems.":["부위를 돌아가며 놓으면 통증 문제를 예방할 수 있어요.","부위를 돌아가며 놓으면 피부 문제를 확인할 수 있어요."],
"How long has the sore been there?":["상처가 아픈 지 얼마나 되셨어요?","멍이 생긴 지 얼마나 되셨어요?"],
"How long have you had diabetes?":["고혈압을 앓으신 지 얼마나 되셨어요?","당뇨약을 드신 지 얼마나 되셨어요?"],
"Is there any redness, warmth, or drainage around it?":["주변에 발적이나 열감, 가려움이 있나요?","주변에 멍이나 열감, 삼출물이 있나요?"],
"High blood sugar can slow healing, so we'll check that too.":["혈압이 높으면 회복이 늦어질 수 있어서 그것도 확인할게요.","혈당이 높으면 회복이 늦어질 수 있어서 기록도 남길게요."],
"We'll clean and dress the wound carefully.":["상처를 조심스럽게 사진 찍고 기록할게요.","상처를 조심스럽게 살피고 크기를 잴게요."],
"Keeping your sugar controlled helps wounds heal faster.":["혈압을 잘 조절하면 상처가 더 빨리 낫습니다.","혈당을 잘 조절하면 상처가 더 깨끗해집니다."],
"Have you missed any insulin doses recently?":["최근에 인슐린 주사를 바꾸신 적 있으세요?","최근에 인슐린 펜 뚜껑을 빠뜨리신 적 있으세요?"],
"Are you breathing faster or deeper than usual?":["평소보다 심장이 빠르거나 세게 뛰시나요?","평소보다 수면이 길거나 깊으신가요?"],
"Does your breath smell fruity or sweet?":["숨에서 쇠 냄새나 단 냄새가 나나요?","소변에서 과일 냄새나 단 냄새가 나나요?"],
"We're checking your sugar, ketones, and blood gas now.":["지금 혈당과 케톤, 소변검사를 확인하고 있어요.","지금 혈압과 케톤, 혈액가스를 확인하고 있어요."],
"We'll start IV fluids and insulin to treat this.":["정맥 수액과 인슐린을 놓을 팔을 확인할게요.","정맥 수액과 인슐린 치료에 대해 설명해 드릴게요."],
"We're getting everything ready for your treatment now.":["지금 검사를 위해 모든 것을 준비하고 있어요.","지금 이송을 위해 모든 것을 준비하고 있어요."],
"When did you notice he became confused?":["언제부터 졸려 하시는 걸 알아차리셨어요?","언제부터 떨려 하시는 걸 알아차리셨어요?"],
"Is he responding when you speak to him?":["몸을 만지면 반응하시나요?","빛을 비추면 반응하시나요?"],
"We're giving sugar directly into his vein right now.":["지금 정맥으로 바로 혈액을 뽑고 있어요.","지금 정맥 라인이 잘 들어갔는지 보고 있어요."],
"His sugar should come back up in a few minutes.":["몇 분 안에 검사 결과가 다시 나올 거예요.","몇 분 안에 혈압이 다시 오를 거예요."],
"Did he take his insulin without eating?":["식사 후에 인슐린을 맞으셨나요?","운동 없이 인슐린을 맞으셨나요?"],
"Does he have any other medical conditions?":["다른 알레르기가 있으신가요?","다른 증상이 있으신가요?"],
"This is a lot to take in, and it's okay to feel overwhelmed.":["받아들이기 힘드실 텐데, 화가 나는 기분이 드셔도 괜찮아요.","당황스러우실 텐데, 압도되는 기분이 드셔도 괜찮아요."],
"It's normal to feel scared right after a new diagnosis.":["새로 진단받으면 화가 나는 게 당연해요.","처음 입원하면 겁이 나는 게 당연해요."],
"I'm here to answer any questions you have.":["궁금하신 점 있으면 뭐든 찾아 드릴게요.","불편하신 점 있으면 뭐든 답해 드릴게요."],
"Your body needs insulin, which we'll teach you to use.":["몸에는 인슐린이 필요하고, 보관법을 알려드릴게요.","몸에는 인슐린이 필요하고, 연락처를 알려드릴게요."],
"We'll also explain what ketones are and why they matter.":["케톤이 무엇이고 어디서 나오는지도 설명해 드릴게요.","혈당이 무엇이고 왜 중요한지도 설명해 드릴게요."],
"We'll start with the basics and go step by step.":["기초부터 한 장씩 보여 드릴게요.","기초를 마치고 한 단계씩 시작할게요."],
"How long has she been drowsy and confused?":["언제부터 어지럽고 혼란스러워하셨어요?","언제부터 졸리고 불안해하셨어요?"],
"Her sugar is extremely high with severe dehydration.":["혈당이 매우 높고 맥박도 빠르세요.","혈압이 매우 낮고 탈수도 심하세요."],
"When did you last see her drink normally?":["마지막으로 정상적으로 식사를 하신 게 언제예요?","마지막으로 정상적으로 소변을 보신 게 언제예요?"],
"Has she been eating or drinking less than usual?":["평소보다 덜 걸으시거나 덜 마셨나요?","평소보다 덜 드시거나 덜 주무셨나요?"],
"We'll give fluids carefully and monitor her closely.":["소변량을 조심스럽게 재면서 계속 지켜볼게요.","보호자께 조심스럽게 알리면서 계속 지켜볼게요."],
"We'll keep a close eye on her heart and kidneys.":["심장과 간도 자세히 살펴볼게요.","폐와 신장도 자세히 살펴볼게요."],
"When did you last change the pump site and reservoir?":["펌프 부위와 배터리를 마지막으로 언제 교체하셨어요?","펌프 부위와 저장통을 마지막으로 어디서 교체하셨어요?"],
"Let's check whether the tubing is kinked or the site is red.":["튜브가 빠졌는지, 부위가 빨간지 확인해 볼게요.","튜브가 꺾였는지, 부위가 젖었는지 확인해 볼게요."],
"When did your sugar start rising?":["혈당이 어제부터 오르기 시작했어요?","열이 언제부터 오르기 시작했어요?"],
"What's your current basal rate set at?":["지금 식사 주입량은 얼마로 맞춰져 있어요?","지금 알람은 몇 시로 맞춰져 있어요?"],
"We may need to give insulin by injection while we sort this out.":["해결될 때까지 제조사에 전화해야 할 수도 있어요.","해결될 때까지 부위를 새로 골라야 할 수도 있어요."],
"We'll switch you to injections until the pump is fixed.":["펌프가 고쳐질 때까지 혈당을 자주 재 드릴게요.","펌프가 고쳐질 때까지 병실로 옮겨드릴게요."],
"When did you start the steroid medication?":["스테로이드 약을 누구에게 처방받으셨어요?","스테로이드 약을 얼마나 드셨어요?"],
"What are you taking the steroid for?":["스테로이드는 누가 처방해서 드시는 거예요?","스테로이드는 얼마 동안 드시는 거예요?"],
"Steroids can temporarily raise your blood sugar.":["스테로이드는 일시적으로 혈압을 올릴 수 있어요.","스테로이드는 일시적으로 체중을 올릴 수 있어요."],
"This rise in sugar is usually temporary.":["이번 혈압 상승은 보통 일시적이에요.","이번 체온 상승은 보통 일시적이에요."],
"We'll monitor your sugar and adjust your treatment.":["혈당을 관찰하면서 식단을 조정할게요.","체온을 관찰하면서 치료를 조정할게요."],
"We may need extra insulin while you're on the steroid.":["스테로이드를 드시는 동안 물이 더 필요할 수 있어요.","스테로이드를 드시는 동안 검사가 더 필요할 수 있어요."],
"What infection symptoms have you had, and for how long?":["어떤 알레르기 증상이 있었고, 얼마나 오래됐어요?","어떤 감염 증상이 있었고, 어디가 제일 아팠어요?"],
"How long have you had the flu?":["감기를 앓으신 지 얼마나 되셨어요?","폐렴을 앓으신 지 얼마나 되셨어요?"],
"Illness can make your sugars harder to control.":["아프면 혈압 조절이 더 어려워질 수 있어요.","아프면 식사 조절이 더 어려워질 수 있어요."],
"Have you been able to eat, drink, and take your insulin?":["먹고 마시고 약도 드실 수 있으셨어요?","먹고 마시고 잠도 주무실 수 있으셨어요?"],
"Keep checking your sugar more often while you're sick.":["아픈 동안에는 체온을 더 자주 확인하세요.","아픈 동안에는 약상자를 더 자주 확인하세요."],
"Never skip your insulin, even if you can't eat much.":["잘 못 드시더라도 물은 절대 거르지 마세요.","잘 못 드시더라도 체온은 매일 꼭 재세요."],
"Which diabetes medicines do you take, and at what times?":["어떤 당뇨약을 드시고, 얼마나 드세요?","어떤 혈압약을 드시고, 언제 드세요?"],
"How many times has this happened this month?":["이번 주에 몇 번이나 이런 일이 있었어요?","이번 달에 몇 번이나 응급실에 오셨어요?"],
"Have these low sugars caused you to fall or nearly fall?":["이런 저혈당 때문에 정신을 잃거나 잃을 뻔하셨어요?","이런 어지럼 때문에 넘어지거나 넘어질 뻔하셨어요?"],
"Did you feel dizzy or faint before you fell?":["넘어지시기 전에 어지럽거나 가슴이 두근거리셨어요?","넘어지신 뒤에 어지럽거나 실신할 것 같으셨어요?"],
"We may need to review and adjust your medications.":["약을 재검토하고 설명해 드려야 할 수도 있어요.","식단을 재검토하고 조정해야 할 수도 있어요."],
"We'll set up a plan to keep you safer at home.":["병원에서 더 안전하게 지내실 계획을 세울게요.","다음 주에 더 안전하게 지내실 계획을 세울게요."],
"How many weeks pregnant are you?":["당뇨 몇 년 되셨어요?","입원한 지 몇 주 되셨어요?"],
"Have you had gestational diabetes before?":["이전에 임신성 고혈압이 있으셨어요?","이전에 쌍둥이를 임신하신 적 있으세요?"],
"In pregnancy we aim for tighter sugar targets to protect the baby.":["임신 중에는 아기를 보호하기 위해 혈압 목표를 더 엄격히 잡아요.","임신 중에는 아기를 보호하기 위해 식사 목표를 더 엄격히 잡아요."],
"Keeping your sugar in range protects you both.":["혈압을 범위 안에 유지하면 두 분 모두에게 좋아요.","혈당을 범위 안에 유지하면 출산에 도움이 돼요."],
"We'll also monitor the baby while we manage your sugar.":["혈압을 관리하면서 아기도 함께 살펴볼게요.","혈당을 관리하면서 보호자도 함께 살펴볼게요."],
"We'll check on the baby's heartbeat as well.":["아기 움직임도 확인할게요.","엄마 심장박동도 확인할게요."],
"I'll bring an interpreter so we can explain clearly.":["설명을 정확히 드릴 수 있게 보호자를 모셔올게요.","설명을 정확히 드릴 수 있게 그림책을 가져올게요."],
"Let me show you step by step how to use the insulin.":["인슐린 보관법을 한 단계씩 보여드릴게요.","인슐린 사용법을 한 번만 보여드릴게요."],
"Do you have any questions about the insulin?":["식사에 대해 궁금하신 점 있으세요?","인슐린에 대해 불편하신 점 있으세요?"],
"Can you show me how you'd do it, so I know you understand?":["기억하시는지 알 수 있게 어떻게 하실지 보여주시겠어요?","이해하셨는지 알 수 있게 어디에 놓을지 보여주시겠어요?"],
"Please show me how you would draw up the dose.":["인슐린을 어떻게 보관하시는지 보여주세요.","주사기를 어떻게 버리시는지 보여주세요."],
"That's exactly right, you understand this well.":["맞아요, 정확히 기억하고 계세요.","맞아요, 정확히 준비하고 계세요."],
"Tell me about any muscle weakness or cramping.":["근육이 약해지거나 쑤시는지 말씀해 주세요.","관절이 약해지거나 쥐가 나는지 말씀해 주세요."],
"Do your legs or your arms feel weak?":["다리나 팔에 저린 느낌이 있으세요?","다리나 팔에 열이 나는 느낌이 있으세요?"],
"Your potassium is low, so we'll correct it before more insulin.":["칼륨이 낮아서 인슐린을 더 넣기 전에 먼저 의사에게 알릴게요.","칼륨이 낮아서 인슐린을 더 넣기 전에 먼저 심전도를 할게요."],
"We're watching your heart rhythm closely on the monitor.":["모니터로 호흡 수를 계속 지켜보고 있어요.","모니터로 산소 수치를 계속 지켜보고 있어요."],
"We'll hold extra insulin until your potassium improves.":["칼륨이 좋아질 때까지 심전도를 계속 볼게요.","칼륨이 좋아질 때까지 보호자께 상황을 알릴게요."],
"Any changes on the monitor will tell us right away.":["모니터에 변화가 생기면 저희가 기록해 둘게요.","모니터에 변화가 생기면 보호자께 알려 드릴게요."],
"When did the headache and drowsiness start?":["두통과 구토가 언제부터 시작됐어요?","복통과 졸림이 언제부터 시작됐어요?"],
"Is he more sleepy than he was an hour ago?":["한 시간 전보다 더 보채시나요?","하루 전보다 더 졸려 하시나요?"],
"We're checking his neurological status closely right now.":["지금 호흡 상태를 자세히 확인하고 있어요.","지금 신경학적 상태를 자세히 기록하고 있어요."],
"We're watching his pupils and alertness very closely.":["동공과 호흡 상태를 아주 자세히 지켜보고 있어요.","혈압과 의식 상태를 아주 자세히 지켜보고 있어요."],
"We're acting immediately because this can be serious.":["심각할 수 있어서 지금 담당의에게 알리고 있어요.","심각할 수 있어서 지금 바로 기록하고 있어요."],
"The team is responding right away to keep him safe.":["팀이 아이를 안전하게 옮기려고 바로 대응하고 있어요.","팀이 부모를 안심시키려고 바로 대응하고 있어요."],
"How responsive has she been over the last hour?":["지난 하루 동안 반응이 어땠어요?","지난 한 시간 동안 열이 어땠어요?"],
"Is she opening her eyes or responding to your voice?":["눈을 뜨거나 손길에 반응하시나요?","눈을 깜빡이거나 목소리에 반응하시나요?"],
"Her pressure is low, so we're giving fluids quickly.":["혈압이 낮아서 수액 라인을 하나 더 확보하고 있어요.","혈압이 낮아서 의사에게 바로 알리고 있어요."],
"The fluids should bring her blood pressure back up.":["수액이 소변량을 다시 늘려 줄 거예요.","수액이 들어가면 혈압을 다시 재 볼게요."],
"We're monitoring her heart and sugar continuously.":["호흡과 혈당을 계속 관찰하고 있어요.","심장과 체온을 계속 관찰하고 있어요."],
"We'll keep monitoring her closely in the trauma bay.":["중환자실에서 계속 자세히 지켜볼게요.","외상 구역에서 계속 기록하며 지켜볼게요."],
"How long ago did you give him the sugar?":["인슐린을 드린 지 얼마나 됐어요?","주스를 드린 지 얼마나 됐어요?"],
"His sugar is up, but he's still not fully awake, so we're investigating.":["혈압은 올랐는데 아직 완전히 깨지 않아서 원인을 찾고 있어요.","혈당은 올랐는데 아직 완전히 깨지 않아서 담당의를 찾고 있어요."],
"Is he opening his eyes or moving at all?":["눈을 뜨거나 조금이라도 말씀하시나요?","입을 열거나 조금이라도 움직이시나요?"],
"We're giving more glucose and checking for other causes.":["혈당을 다시 재고 다른 원인도 확인하고 있어요.","의사에게 보고하고 다른 원인도 확인하고 있어요."],
"We may give another dose of sugar if he doesn't wake up soon.":["곧 깨지 않으면 의사에게 한 번 더 알릴 수 있어요.","곧 깨지 않으면 혈당을 한 번 더 잴 수 있어요."],
"We're also looking for other reasons he's still drowsy.":["아직 열이 나는 다른 이유도 찾고 있어요.","아직 어지러워하시는 다른 이유도 찾고 있어요."],
"Your foot infection and fever together are very serious.":["발 감염과 기침이 함께 있어서 매우 심각해요.","발 통증과 열이 함께 있어서 매우 심각해요."],
"How long has your foot looked like this?":["발이 이렇게 부은 지 얼마나 되셨어요?","다리가 이렇게 된 지 얼마나 되셨어요?"],
"Are the swelling and blackness spreading up your leg?":["부종과 붉은 변색이 다리 위로 번지고 있나요?","부종과 검은 변색이 팔 위로 번지고 있나요?"],
"Your blood sugar, infection, and fever are all connected here.":["혈압과 감염, 열이 모두 연관되어 있어요.","혈당과 감염, 통증이 모두 연관되어 있어요."],
"We're starting antibiotics and fluids right away.":["배양검사와 채혈을 바로 시작할게요.","항생제 알레르기를 바로 확인할게요."],
"I'm calling the surgical team with an SBAR report.":["SBAR 보고를 외과팀에 문자로 보낼게요.","SBAR 보고로 약제팀에 연락할게요."],
"I'll give a full report so the surgical team can act fast.":["외과팀이 빨리 대응할 수 있게 전체 기록을 보내 드릴게요.","중환자팀이 빨리 대응할 수 있게 전체 보고를 드릴게요."],
"How does your breathing compare to a few hours ago?":["몇 시간 전과 비교해서 통증이 어떠세요?","몇 시간 전과 비교해서 의식이 어떠세요?"],
"Have you felt more short of breath tonight?":["오늘 밤 열이 더 나셨어요?","오늘 밤 속이 더 메스꺼우셨어요?"],
"Your labs still show a lot of acid, so I'm updating the doctor.":["검사에서 칼륨이 아직 많이 나와서 의사에게 알리고 있어요.","검사에서 산이 아직 많이 나와서 기록을 확인하고 있어요."],
"I'll report your pH and anion gap trend clearly.":["pH와 음이온차 추이를 명확히 기록할게요.","혈당과 음이온차 추이를 명확히 보고할게요."],
"I'm giving the on-call doctor a clear update now.":["당직 간호사에게 명확히 업데이트하고 있어요.","병동 의사에게 명확히 업데이트하고 있어요."],
"I'll hand this off clearly so nothing gets missed.":["놓치는 것 없이 명확하게 기록할게요.","놓치는 것 없이 명확하게 확인할게요."],
}
WKO={"w-take":["(약을) 처방하다","(약을) 끊다"],"w-spot":["(주사) 흉터","(주사) 멍"],
"w-walk":["조용히 걸어가다","급하게 서두르다"],"w-sore":["아물고 남은 흉터","발에 박힌 굳은살"]}
WEN={"w-walk":["work you through","walk you around"],"w-gas":["gap","count"],"w-treatment":["treaty","trauma"],
"w-condition":["complication","contraction"],"w-neurological":["neurosurgical","nephrological"],"w-alertness":["allergies","attention"]}
B={"Can you show me how you'd do it, so I know you understand?":["disagree","complain","hesitate"],
"We're acting immediately because this can be serious.":["casually","eventually","reluctantly"]}
run('er-diabetic',S,WKO,WEN,B)
