import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"Can you tell me your name and what happened?":("이름이 뭐고 언제 일이 있었는지 말씀해 주시겠어요?","나이가 몇이고 무슨 일이 있었는지 말씀해 주시겠어요?"),
"Take a deep breath for me — does it hurt to breathe?":("숨을 깊게 쉬어 보세요—누르면 아프세요?","숨을 천천히 쉬어 보세요—숨쉴 때 아프세요?"),
"I'm checking you head to toe now.":("지금 머리부터 발끝까지 설명할게요.","지금 머리부터 발끝까지 닦아볼게요."),
"I'm checking your airway, breathing, and circulation first.":("기도, 호흡, 순환부터 먼저 설명할게요.","기도, 호흡, 순환부터 다시 확인할게요."),
"I need to find what's most serious first.":("가장 아픈 것부터 먼저 찾아야 해요.","가장 심각한 것부터 먼저 말씀드려야 해요."),
"Please don't move your neck — hold still for me.":("손을 움직이지 마세요—가만히 계셔 주세요.","목을 움직이지 마세요—조용히 계셔 주세요."),
"We're keeping your head in line to protect your spine.":("피부를 보호하려고 머리를 일직선으로 유지하고 있어요.","척추를 보호하려고 다리를 일직선으로 유지하고 있어요."),
"The collar stays on until we clear your neck.":("목에 이상이 없다고 확인될 때까지 담요는 그대로 둡니다.","목에 이상이 없다고 확인될 때까지 목 보호대는 의사가 둡니다."),
"This is just a precaution to protect your spine from further injury.":("척추가 더 붓지 않게 보호하려는 예방조치일 뿐이에요.","척추가 더 다치지 않게 보호하려는 규정일 뿐이에요."),
"I know it's uncomfortable, but it's keeping you safe.":("답답하신 건 알지만, 이게 환자분을 안전하게 지켜 줘요.","불편하신 건 알지만, 이게 환자분을 따뜻하게 지켜 줘요."),
"I'm taking your pulse and blood pressure now.":("지금 체온과 혈압을 재고 있어요.","지금 맥박과 키를 재고 있어요."),
"Do you feel dizzy or lightheaded right now?":("지금 졸리거나 머리가 핑 도는 느낌이 있으세요?","지금 어지럽거나 손이 저린 느낌이 있으세요?"),
"Your heart rate is high — we're watching you closely.":("심박수가 높아서—세심히 설명하고 있어요.","혈압이 높아서—세심히 지켜보고 있어요."),
"Your blood pressure is a little low right now.":("지금 체온이 조금 낮아요.","지금 맥박이 조금 낮아요."),
"We'll keep checking these numbers every few minutes.":("이 수치들을 몇 분마다 계속 읽을게요.","이 수치들을 몇 분마다 계속 보여드릴게요."),
"Point to exactly where it hurts the most.":("가장 아픈 곳을 정확히 말씀해 주세요.","가장 가려운 곳을 정확히 가리켜 주세요."),
"Does it hurt when I press here?":("여기를 누를 때 가려우세요?","저기를 누를 때 아프세요?"),
"Any pain in your back or belly?":("등이나 팔에 통증이 있나요?","목이나 배에 통증이 있나요?"),
"Can you tell me if you're wide awake or feeling drowsy?":("완전히 깨어 있는지, 아니면 어지러운 느낌인지 말씀해 주시겠어요?","완전히 배고픈지, 아니면 졸린 느낌인지 말씀해 주시겠어요?"),
"I'm marking every spot that hurts on this chart.":("아픈 부위를 전부 이 차트에서 지우고 있어요.","가려운 부위를 전부 이 차트에 표시하고 있어요."),
"How fast was the car going?":("차가 어디로 가고 있었나요?","차가 얼마나 빠르게 멈췄나요?"),
"Were you wearing a seatbelt?":("헬멧을 쓰고 계셨나요?","안경을 쓰고 계셨나요?"),
"Were you thrown from the vehicle at all?":("차량 안에 갇혀 계셨나요?","차량 밖으로 걸어나가셨나요?"),
"Do you remember how the crash happened?":("충돌이 언제 일어났는지 기억하세요?","충돌이 어떻게 일어났는지 보셨어요?"),
"Which part of the car were you sitting in?":("차 안에서 어느 자리에 서 계셨나요?","버스 안에서 어느 자리에 앉아 계셨나요?"),
"We're assessing both of you right now.":("지금 두 분 모두 설명하고 있어요.","지금 한 분만 사정하고 있어요."),
"Tell me who has trouble breathing or is bleeding heavily.":("누가 걷기 힘든지, 아니면 심하게 출혈되는지 말씀해 주세요.","누가 숨쉬기 힘든지, 아니면 심하게 졸린지 말씀해 주세요."),
"The team is dividing up to care for each of you.":("팀이 나뉘어서 두 분 각자를 설명하고 있어요.","팀이 나뉘어서 두 분 가족을 돌보고 있어요."),
"Your friend is being cared for by another nurse right now.":("친구분은 지금 다른 의사가 돌보고 있어요.","형제분은 지금 다른 간호사가 돌보고 있어요."),
"I'll update you as soon as I know more about your friend.":("친구분에 대해 더 알게 되는 대로 바로 전화해 드릴게요.","가족분에 대해 더 알게 되는 대로 바로 알려 드릴게요."),
"Does your belly feel tender or full anywhere?":("등이 어디 압통이 있거나 팽만한 느낌이 있나요?","배가 어디 압통이 있거나 따가운 느낌이 있나요?"),
"You look pale — we're watching for internal bleeding.":("창백해 보이셔서—내부출혈이 있는지 설명하고 있어요.","붉어 보이셔서—내부출혈이 있는지 지켜보고 있어요."),
"We're getting scans to look inside.":("안쪽을 보려고 사진을 찍고 있어요.","바깥쪽을 보려고 스캔을 찍고 있어요."),
"I know a small injury may not seem like much to worry about.":("작은 부상이라 크게 서두를 일 같지 않으실 수 있다는 거 알아요.","작은 상처라 크게 걱정할 일 같지 않으실 수 있다는 거 알아요."),
"Even a small injury can hide a bigger problem inside.":("작은 부상도 바깥쪽에 더 큰 문제를 숨기고 있을 수 있어요.","작은 부상도 안쪽에 더 큰 문제를 숨기고 있는지 볼게요."),
"We're placing a binder to stabilize your pelvis.":("골반을 안정시키려고 바인더를 보고 있어요.","골반을 안정시키려고 바인더를 설명하고 있어요."),
"Please don't move your hips or legs.":("엉덩이나 팔을 움직이지 마세요.","엉덩이나 다리를 만지지 마세요."),
"We're preparing blood in case you need it.":("혹시 필요할 경우를 대비해 혈액을 설명하고 있어요.","혹시 필요할 경우를 대비해 혈액을 정리하고 있어요."),
"Your pelvis is unstable, so we're keeping you very still.":("골반이 불안정해서 최대한 편하게 하고 있어요.","무릎이 불안정해서 최대한 움직이지 않게 하고 있어요."),
"We're watching your blood pressure closely because of the bleeding.":("통증 때문에 혈압을 세심히 지켜보고 있어요.","출혈 때문에 체온을 세심히 지켜보고 있어요."),
"Which blood thinner do you take?":("어떤 혈압약을 드세요?","언제 혈액희석제를 드세요?"),
"When was your last dose?":("마지막 진료가 언제였나요?","처음 복용이 언제였나요?"),
"Even a minor injury can bleed more with these.":("이 약을 드시면 경미한 부상도 통증이 더 심할 수 있어요.","이 음식을 드시면 경미한 부상도 출혈이 더 많을 수 있어요."),
"We need to watch you closely because of the blood thinner.":("혈압약 때문에 세심히 지켜봐야 해요.","혈액희석제 때문에 천천히 지켜봐야 해요."),
"Please tell me every medication you're taking, even the ones in small doses.":("어제 하루 드신 약은 전부 말씀해 주세요.","적은 용량이라도 드시는 음식은 전부 말씀해 주세요."),
"We're leaving the object in place and stabilizing it.":("물체는 그대로 두고 설명하고 있어요.","물체는 그대로 두고 사진을 찍고 있어요."),
"Try to stay very still for me.":("최대한 편하게 계셔 주세요.","최대한 조용히 계셔 주세요."),
"How many times were you struck?":("몇 번이나 넘어지셨나요?","어디를 맞으셨나요?"),
"Please don't touch or pull on the object.":("붕대를 만지거나 당기지 마세요.","머리를 만지거나 당기지 마세요."),
"We're figuring out exactly where the object went.":("물체가 정확히 언제 지나갔는지 파악하고 있어요.","물체가 정확히 어디로 지나갔는지 설명하고 있어요."),
"Did you hit your head when you fell?":("넘어지기 전에 머리를 부딪히셨나요?","넘어지실 때 의식을 잃으셨나요?"),
"What medications are you taking?":("무슨 음식 드시고 계세요?","어디서 약을 드시고 계세요?"),
"Even a small fall can cause serious injury at your age.":("연세가 있으시면 작은 낙상도 심각한 부상인지 확인해요.","연세가 있으시면 작은 낙상도 조심스레 부축해 드릴게요."),
"I know it doesn't feel that serious, but we still need to check carefully.":("그렇게 아프게 느껴지지 않아도 신중히 확인해야 해요.","그렇게 심각하게 느껴지지 않아도 신중히 설명해야 해요."),
"We're checking your medications along with your injuries.":("부상과 함께 복용 중인 약도 설명하고 있어요.","부상과 함께 복용 중인 음식도 확인하고 있어요."),
"Point to where the pain is worst.":("통증이 가장 심한 곳을 말해 주세요.","가려움이 가장 심한 곳을 가리켜 주세요."),
"Any allergy to medicine? Yes or no?":("음식 알레르기 있나요? 예 아니면 아니오?","약물 부작용 있나요? 예 아니면 아니오?"),
"I'm getting an interpreter for you now.":("지금 의사를 연결해 드릴게요.","지금 통역사에게 설명해 드릴게요."),
"I'll use my hands to show you what I mean.":("제 뜻을 문자로 보내 드릴게요.","제 이름을 손짓으로 보여 드릴게요."),
"Point to your body if it's easier than words.":("말보다 쉬우면 몸으로 따라해 주세요.","그림보다 쉬우면 몸으로 가리켜 주세요."),
"How many weeks pregnant are you right now?":("몇 주째 아프세요?","지금 임신 몇 번째세요?"),
"We're tilting you to your left side to help blood flow.":("배를 보호하려고 왼쪽으로 기울여 드릴게요.","혈류를 도우려고 왼쪽으로 앉혀 드릴게요."),
"Any belly pain, bleeding, or contractions?":("등 통증이나 출혈, 아니면 수축이 있나요?","배 통증이나 출혈, 아니면 기침이 있나요?"),
"We're checking both you and your baby.":("산모분과 가족 둘 다 확인하고 있어요.","산모분과 아기 둘 다 설명하고 있어요."),
"Lying flat can press on a big vein, so the tilt helps you both.":("똑바로 앉으면 큰 정맥을 눌러서, 기울이면 두 분 다 도움이 돼요.","똑바로 누우면 큰 정맥을 눌러서, 기울이면 아기만 도움이 돼요."),
"He's losing a lot of blood, so we're replacing it fast.":("출혈이 많아서 빠르게 설명해 드리고 있어요.","통증이 많아서 빠르게 보충해 드리고 있어요."),
"We're giving blood and clotting factors together.":("혈액과 응고인자를 함께 보고 있어요.","혈액과 응고인자를 함께 준비하고 있어요."),
"The team is doing everything they can right now.":("팀이 지금 할 수 있는 모든 걸 보고 있어요.","팀이 지금 할 수 있는 모든 걸 정리하고 있어요."),
"I know this is frightening, but his heart rate is already improving.":("무서우신 거 알아요, 하지만 심박수는 계속 지켜보고 있어요.","무서우신 거 알아요, 하지만 맥박을 벌써 재고 있어요."),
"I'll come find you as soon as we know more.":("더 알게 되는 대로 바로 전화드릴게요.","더 알게 되면 내일 찾아뵐게요."),
"We're covering you with warm blankets now.":("지금 따뜻한 수건으로 덮어 드릴게요.","지금 따뜻한 담요를 갖다 드릴게요."),
"Keeping you warm helps your blood clot properly.":("따뜻하게 유지하면 소변 배출이 제대로 돼요.","따뜻하게 유지하면 혈액 응고가 제대로 되는지 볼게요."),
"Tell me if you keep feeling cold.":("계속 더우시면 말씀해 주세요.","계속 추우시면 눌러 주세요."),
"Getting cold can make it harder for your blood to clot.":("몸이 차가워지면 소변이 나오기가 더 어려워질 수 있어요.","몸이 뜨거워지면 혈액이 응고되기가 더 어려워질 수 있어요."),
"We're keeping every blanket warm before it touches your skin.":("담요는 전부 침대에 닿기 전에 따뜻하게 데워 둡니다.","수건은 전부 피부에 닿기 전에 따뜻하게 데워 둡니다."),
"Your breath sounds are absent on one side.":("한쪽에서 맥박이 들리지 않아요.","한쪽에서 호흡음이 약하게 들려요."),
"We need to release the pressure in your chest now.":("지금 가슴 안의 압력을 재야 해요.","지금 가슴 안의 압력을 알려야 해요."),
"Stay with me — we're helping you breathe.":("정신 차리세요—걷는 걸 도와드릴게요.","정신 차리세요—숨쉬는 걸 지켜볼게요."),
"Your chest is getting tighter and your heart rate is climbing fast.":("배가 점점 팽팽해지고 심박수가 빠르게 오르고 있어요.","가슴이 점점 팽팽해지고 체온이 빠르게 오르고 있어요."),
"We're moving fast because the pressure on this side is building quickly.":("이쪽 압력이 빠르게 차오르고 있어서 설명하고 있어요.","저쪽 압력이 빠르게 차오르고 있어서 서두르고 있어요."),
"We're giving blood as fast as we can.":("최대한 빠르게 혈액을 보고 있어요.","최대한 정확하게 혈액을 드리고 있어요."),
"Applying pressure to control the bleeding.":("통증을 조절하려고 압박하고 있어요.","출혈을 조절하려고 압박을 설명하고 있어요."),
"Stay with me — open your eyes if you can.":("정신 차리세요—할 수 있으면 손 들어 보세요.","정신 차리세요—할 수 있으면 입을 열어 보세요."),
"Your pulse is getting weak, so we're moving very fast.":("맥박이 약해지고 있어서 아주 조용히 움직이고 있어요.","혈압이 약해지고 있어서 아주 빠르게 움직이고 있어요."),
"You're barely responding, but we're right here with you.":("거의 반응이 없으시지만, 가족이 바로 곁에 있어요.","거의 반응이 없으시지만, 저희가 바로 밖에 있어요."),
"Continue compressions — checking for tension pneumothorax.":("압박 계속하고—긴장성 기흉 보고 중.","압박 계속하고—긴장성 기흉 설명 중."),
"Bilateral chest decompression now.":("양측 흉강 감압 설명.","양측 흉강 감압 보고."),
"Assessing for cardiac tamponade with ultrasound.":("초음파로 심장압전 사정 끝.","초음파로 심장압전 사정 요청."),
"Pulse check now — hold compressions.":("지금 맥박 확인—모니터 잠깐 봐.","지금 맥박 확인—시간 잠깐 봐."),
"Switching compressors — continue at the same rate.":("시계 담당 교대—같은 속도로 계속.","압박자 교대—같은 구호로 계속."),
"MVC at highway speed, unrestrained driver.":("고속도로 속도 자동차 사고, 안전벨트 미착용 동승자.","저속 주차장 자동차 사고, 안전벨트 미착용 운전자."),
"Pelvic and femur fractures, binder in place.":("골반과 대퇴골 골절, 바인더 준비된 상태.","골반과 대퇴골 골절, 바인더 설명된 상태."),
"Two units of blood given, BP now stabilizing.":("혈액 두 팩 투여, 현재 맥박 안정되는 중.","혈액 두 팩 준비, 현재 혈압 안정되는 중."),
"Airway is secure, breathing on his own.":("기도 확보됨, 인공 호흡 중.","기도 정리됨, 자가 호흡 중."),
"Watching for internal bleeding — next scan in an hour.":("내부출혈 경과 설명 중—다음 스캔은 한 시간 후.","내부출혈 경과 관찰 중—다음 혈액검사는 한 시간 후."),
"He has internal bleeding that needs surgery now.":("내부출혈이 있어서 지금 설명이 필요해요.","외부출혈이 있어서 지금 수술이 필요해요."),
"We're taking him straight to the operating room.":("바로 영상실로 데려갈 거예요.","바로 병실로 데려갈 거예요."),
"The surgeon needs your consent to proceed immediately.":("즉시 진행하려면 마취과 의사가 보호자분의 동의를 받아야 해요.","즉시 진행하려면 외과 의사가 보호자분의 연락을 받아야 해요."),
"I know this is happening very fast, but every minute matters right now.":("이 모든 게 아주 빠르게 일어나고 있는 거 알지만, 지금은 설명이 중요해요.","이 모든 게 아주 빠르게 일어나고 있는 거 알지만, 지금은 가족이 중요해요."),
"I'll come back and update you as soon as he's out of surgery.":("검사가 끝나는 대로 바로 와서 알려 드릴게요.","수술이 끝나는 대로 바로 전화로 알려 드릴게요."),
"Is it getting harder to breathe or swallow?":("숨쉬거나 걷기가 점점 더 힘드세요?","말하거나 삼키기가 점점 더 힘드세요?"),
"Your airway may swell, so we're securing it early.":("얼굴이 부을 수 있어서 미리 확보하고 있어요.","기도가 부을 수 있어서 미리 설명하고 있어요."),
"We're preparing to place a breathing tube now.":("지금 기관삽관 튜브를 설명할 준비를 하고 있어요.","지금 기관삽관 튜브를 챙길 준비를 하고 있어요."),
"Tell me right away if your throat feels like it's swelling shut.":("목구멍이 가려워서 막히는 느낌이면 바로 말씀해 주세요.","목구멍이 부어서 막히는 느낌이면 바로 눌러 주세요."),
"We're checking your face and airway together right now.":("지금 얼굴과 기도를 함께 설명하고 있어요.","지금 얼굴과 기도를 따로 확인하고 있어요."),
}
W2={'w-keep':(['내려놓다·치우다','가져가다·옮기다'],None),'w-stay':(['(그대로) 서다','(바로) 떠나다'],None),'w-clear':(['이상 부위를 고정하다','이상 부위를 소독하다'],None),
'w-rate':(['(분당) 리듬','(분당) 크기'],None),'w-pain':(None,['itch','paint']),'w-stabilize':(['소독시키다·씻기다','표준화하다·맞추다'],None)}
W={'w-strike':(['(손으로) 쓰다듬다','(흉기를) 내려놓다'],None),'w-contraction':(['(자궁) 출혈','양수 파열'],None),'w-absent':(None,['present','distant']),
'w-release':(['(압력을) 재다','(압력을) 채우다'],None),'w-apply':(['(압박을) 재다','(압박을) 알리다'],None),'w-unit':(['(혈액) 용량','(혈액) 리터'],None)}
B={"I know it's uncomfortable, but it's keeping you safe.":('uncomfortable',['impossible','expensive','unbelievable']),
"I'm getting an interpreter for you now.":('interpreter',['ambulance','invitation','inhaler']),
"Applying pressure to control the bleeding.":('pressure',['ointment','lotion','sunscreen']),
"Assessing for cardiac tamponade with ultrasound.":('ultrasound',['radiograph','fluoroscopy','mammography'])}
W.update(W2)
apply('er-polytrauma',S,W,B)
