import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_five import go
S = {
"Have you had any thoughts of ending your life?": ["삶을 바꾸려는 생각이 든 적이 있나요?", "일을 끝내려는 생각이 든 적이 있나요?"],
"Do you have a plan for how you would do it?": ["어떻게 할지 구체적인 약속이 있나요?", "언제 할지 구체적인 계획이 있나요?"],
"I want you to know you're safe here and I'm listening.": ["여기서는 안전하고, 제가 보고 있다는 걸 알아주셨으면 해요.", "여기서는 조용하고, 제가 듣고 있다는 걸 알아주셨으면 해요."],
"I'm going to ask you some direct questions now.": ["지금부터 직접적인 설명을 몇 가지 드릴게요.", "내일부터 직접적인 질문을 몇 가지 드릴게요."],
"Do you have access to anything you could use to hurt yourself?": ["자해에 쓸 만한 것이 어디 있는지 아시나요?", "자해에 쓸 만한 것을 누가 두었나요?"],
"There's no judgment here, only concern for you.": ["여기엔 소음은 없고, 당신에 대한 염려만 있어요.", "여기엔 판단은 없고, 당신에 대한 질문만 있어요."],
"For your safety, I need to hold onto a few items for now.": ["안전을 위해 내일은 몇 가지 물건을 제가 맡아 둘게요.", "편의를 위해 지금은 몇 가지 물건을 제가 맡아 둘게요."],
"You'll get everything back when you're discharged.": ["입원할 때 전부 돌려받으실 거예요.", "퇴원할 때 일부만 돌려받으실 거예요."],
"This is something we do for everyone in this room.": ["이건 이 병원에 있는 모두에게 하는 절차예요.", "이건 이 방에 처음 온 분께 하는 절차예요."],
"I need to hold your belt and shoelaces until you leave this room.": ["이 방을 나가실 때까지 가방과 신발끈을 맡아 둘게요.", "이 방을 나가실 때까지 벨트와 지갑을 맡아 둘게요."],
"I know this feels intrusive, but it keeps you safe.": ["침해적으로 느껴질 수 있지만, 이건 당신을 편안하게 지켜줘요.", "지루하게 느껴질 수 있지만, 이건 당신을 안전하게 지켜줘요."],
"This isn't punishment — it's part of keeping this room safe for everyone.": ["이건 처벌이 아니라, 이 방을 모두에게 깨끗하게 지키기 위한 절차예요.", "이건 처벌이 아니라, 이 병원을 모두에게 안전하게 지키기 위한 절차예요."],
"It took a lot of courage to come here today.": ["어제 여기 오기까지 정말 큰 용기가 필요했을 거예요.", "오늘 여기 오기까지 정말 큰 준비가 필요했을 거예요."],
"Can you tell me what's been the hardest part lately?": ["요즘 가장 좋은 부분이 무엇이었는지 말씀해 주시겠어요?", "어릴 때 가장 힘든 부분이 무엇이었는지 말씀해 주시겠어요?"],
"You're in the right place, and we'll take it one step at a time.": ["여기 잘 오셨어요, 하루씩 함께 해나갈게요.", "여기 잘 오셨어요, 한 사람씩 함께 해나갈게요."],
"Tell me what's been going on lately.": ["어제 어떤 일이 있었는지 말씀해 주세요.", "요즘 누가 오셨는지 말씀해 주세요."],
"You made the right call by coming in.": ["여기 온 건 쉬운 판단이었어요.", "여기 온 건 의사의 판단이었어요."],
"We're going to take this step by step together.": ["이 과정을 한 번에 함께 해나갈 거예요.", "이 과정을 한 주씩 함께 해나갈 거예요."],
"You're safe — this feeling will pass, I'm right here with you.": ["안전해요 — 이 소리는 지나갈 거고, 제가 바로 곁에 있어요.", "안전해요 — 이 느낌은 지나갈 거고, 제가 바로 문 앞에 있어요."],
"Let's breathe together, in for four, out for four.": ["함께 숨을 쉬어요, 둘을 세며 들이쉬고, 둘을 세며 내쉬고요.", "함께 숨을 쉬어요, 넷을 세며 들이쉬고, 열을 세며 내쉬고요."],
"Your heart is working hard, but we're checking everything to be sure.": ["심장이 천천히 뛰고 있지만, 확실히 하기 위해 전부 확인하고 있어요.", "심장이 열심히 뛰고 있지만, 확실히 하기 위해 일부만 확인하고 있어요."],
"I need to check your heart rate and oxygen right now.": ["지금 의사가 심박수와 산소포화도를 확인해야 해요.", "지금 심박수와 산소포화도를 설명해야 해요."],
"It feels like something terrible is happening, but your body is safe.": ["끔찍한 일이 일어나는 것처럼 느껴지겠지만, 방은 안전해요.", "놀라운 일이 일어나는 것처럼 느껴지겠지만, 몸은 안전해요."],
"I'm staying right here until this feeling passes.": ["이 느낌이 지나갈 때까지 바로 저기 있을게요.", "날이 밝을 때까지 바로 여기 있을게요."],
"Over the last two weeks, how has your sleep been?": ["지난 2주 동안 식사는 어떠셨어요?", "지난 2일 동안 잠은 어떠셨어요?"],
"Have you lost interest in things you used to enjoy?": ["예전에 즐기던 사람들에 흥미를 잃으셨나요?", "요즘 즐기는 것들에 흥미를 잃으셨나요?"],
"Thank you for being honest with me — that helps a lot.": ["천천히 말씀해 주셔서 감사해요 — 큰 도움이 돼요.", "솔직하게 말씀해 주셔서 감사해요 — 조금 도움이 돼요."],
"Have you noticed any changes in your appetite?": ["수면이 달라진 걸 느끼셨나요?", "체중이 달라진 걸 느끼셨나요?"],
"It takes courage to talk about feeling this way.": ["이런 기분을 이야기하는 데는 시간이 필요해요.", "이런 기분을 잊어 버리는 데는 용기가 필요해요."],
"I hear you, and we'll work through this together.": ["듣고 있어요, 이걸 천천히 헤쳐 나갈 거예요.", "보고 있어요, 이걸 함께 헤쳐 나갈 거예요."],
"I'm glad you're here — you don't have to explain anything right now.": ["여기 있어 다행이에요 — 지금 당장 웃지 않으셔도 돼요.", "여기 있어 다행이에요 — 지금 당장 가족에게 설명하지 않으셔도 돼요."],
"You're not being judged. I just want to understand how you're feeling.": ["비난받는 게 아니에요. 지금 어디가 아픈지 이해하고 싶을 뿐이에요.", "비난받는 게 아니에요. 어떤 일이 있었는지 이해하고 싶을 뿐이에요."],
"We'll get through the next steps together, at your pace.": ["다음 단계들을 병원의 속도에 맞춰 함께 헤쳐 나갈 거예요.", "이전 단계들을 당신의 속도에 맞춰 함께 헤쳐 나갈 거예요."],
"Take all the time you need before we talk.": ["이야기하기 전에 필요한 만큼 물을 드세요.", "이야기한 뒤에 필요한 만큼 시간을 가지세요."],
"No one here is judging you for what happened.": ["무슨 일이 있었든 여기서는 아무도 당신을 방해하지 않아요.", "무슨 일이 있었든 밖에서는 아무도 당신을 비난하지 않아요."],
"We're going to take good care of you from here.": ["이제부터 잘 데려다드릴게요.", "내일부터 잘 돌봐드릴게요."],
"Some things stay between us, but safety I do have to share.": ["몇몇은 우리 사이에만 두지만, 식사 문제는 공유해야 해요.", "몇몇은 우리 사이에만 두지만, 학교 문제는 공유해야 해요."],
"I hear that you want your own space to talk — that's fair.": ["혼자만의 시간에 이야기하고 싶은 마음, 이해해요 — 그게 맞아요.", "선생님과 함께 이야기하고 싶은 마음, 이해해요 — 그게 맞아요."],
"You're not in trouble here; we just want to help you feel better.": ["여기서 혼나는 게 아니에요; 그저 잠을 잘 자도록 돕고 싶을 뿐이에요.", "여기서 혼나는 게 아니에요; 그저 친구를 사귀도록 돕고 싶을 뿐이에요."],
"Before anything else, I need to ask about your safety.": ["무엇보다 먼저, 식사에 대해 여쭤봐야 해요.", "무엇보다 먼저, 가족에 대해 여쭤봐야 해요."],
"Your mom wants to help too, and we'll find a way that works for you.": ["아버지도 돕고 싶어 하시고, 당신에게 맞는 방법을 함께 찾을 거예요.", "어머니도 돕고 싶어 하시고, 당신에게 맞는 학교를 함께 찾을 거예요."],
"It's okay to want some things kept between just us.": ["어떤 건 가족끼리만 두고 싶어도 괜찮아요.", "어떤 건 친구끼리만 두고 싶어도 괜찮아요."],
"This is a temporary hold to keep you safe while we assess.": ["이건 사정하는 동안 안전을 지키기 위한 일시적인 이송이에요.", "이건 이송하는 동안 안전을 지키기 위한 일시적인 억류예요."],
"You still have rights, and I'll explain each step to you.": ["여전히 권리가 있고, 각 비용을 설명해 드릴게요.", "여전히 시간이 있고, 각 단계를 설명해 드릴게요."],
"I know this feels unfair — let me walk you through why.": ["부당하게 느껴진다는 거 알아요 — 어디로 가는지 안내해 드릴게요.", "불안하게 느껴진다는 거 알아요 — 왜 그런지 안내해 드릴게요."],
"The doctor will assess you first, and then we'll talk about next steps.": ["먼저 의사 선생님이 평가하고, 그다음 다음 병실을 이야기해요.", "먼저 원무과 직원이 평가하고, 그다음 다음 단계를 이야기해요."],
"I know this feels unfair, and I want to explain why it's happening.": ["부당하게 느껴진다는 것 알아요, 언제 끝나는지 설명하고 싶어요.", "외롭게 느껴진다는 것 알아요, 왜 이렇게 되는지 설명하고 싶어요."],
"You still have a say in how we do this together.": ["이 과정을 언제 할지 여전히 당신의 의견이 반영돼요.", "이 과정을 어떻게 할지 여전히 의사의 의견이 반영돼요."],
"I can see you're scared — you're safe in this room with me.": ["지친 게 보여요 — 이 방에서는 저와 함께 안전해요.", "겁먹은 게 보여요 — 이 병동에서는 저와 함께 안전해요."],
"I don't hear what you hear, but I believe it feels real to you.": ["당신이 보는 걸 저는 못 보지만, 당신에겐 진짜처럼 느껴진다는 걸 믿어요.", "당신이 듣는 걸 저는 못 듣지만, 당신에겐 오래된 일처럼 느껴진다는 걸 믿어요."],
"Let's keep the door open so you can see everyone around you.": ["주변 사람들이 다 들리도록 문을 열어 둘게요.", "주변 사람들이 다 보이도록 창을 열어 둘게요."],
"I believe that this feels very real to you right now.": ["어제 이게 당신에게 아주 진짜처럼 느껴졌다는 걸 믿어요.", "지금 이게 저에게 아주 진짜처럼 느껴진다는 걸 믿어요."],
"You're safe with me, and no one here wants to hurt you.": ["저와 함께 안전해요, 여기서는 아무도 당신을 놀리려 하지 않아요.", "저와 함께 안전해요, 여기서는 아무도 당신을 깨우려 하지 않아요."],
"Tell me what you're seeing or hearing right now.": ["지금 무엇이 보이거나 느껴지는지 말씀해 주세요.", "어제 무엇이 보이거나 들렸는지 말씀해 주세요."],
"I hear you say you're fine — I just want to double-check a few things.": ["괜찮다고 하시는 말씀은 들었어요 — 몇 가지만 다시 설명하고 싶어요.", "피곤하다고 하시는 말씀은 들었어요 — 몇 가지만 다시 확인하고 싶어요."],
"Sometimes people say they're okay when they're really struggling.": ["사람들은 정말 아파도 괜찮다고 말할 때가 있어요.", "사람들은 정말 힘들어도 쉬겠다고 말할 때가 있어요."],
"There's no wrong answer here; I only want to keep you safe.": ["틀린 답은 없어요; 그저 당신을 편안하게 모시고 싶을 뿐이에요.", "틀린 질문은 없어요; 그저 당신을 안전하게 지키고 싶을 뿐이에요."],
"Can I ask you a few more questions about how you've been feeling?": ["요즘 잠이 어떠셨는지 몇 가지 더 여쭤봐도 될까요?", "어제 기분이 어떠셨는지 몇 가지 더 여쭤봐도 될까요?"],
"It's okay to say more than fine if that's true for you.": ["괜찮다는 말로 다 담기지 않는다면, 그렇게 우셔도 돼요.", "괜찮다는 말로 다 담기지 않는다면, 가족에게 말씀하셔도 돼요."],
"Sometimes it's hard to admit how much you're really struggling.": ["얼마나 아픈지 인정하기 어려울 때가 있어요.", "얼마나 오래 힘들었는지 인정하기 어려울 때가 있어요."],
"Your chest pain is real to me, and we're going to check it properly.": ["당신의 흉통은 저에게 진짜예요, 제대로 기억할 거예요.", "당신의 걱정은 저에게 진짜예요, 제대로 확인할 거예요."],
"Having anxiety doesn't mean this can't also be something physical.": ["불안이 있다고 해서 오래된 문제일 수 없는 건 아니에요.", "불안이 있다고 해서 갑작스러운 문제일 수 없는 건 아니에요."],
"Tell me exactly where it hurts and what it feels like.": ["정확히 언제 아프고 어떤 느낌인지 말씀해 주세요.", "정확히 어디가 아프고 얼마나 오래인지 말씀해 주세요."],
"I'm not going to assume this is only anxiety.": ["이걸 그저 피로 때문이라고 단정하지 않을 거예요.", "이걸 그저 흡연 때문이라고 단정하지 않을 거예요."],
"We're going to run tests to check your heart properly.": ["심장을 제대로 확인하기 위해 검사를 서두를 거예요.", "심장을 제대로 확인하기 위해 검사를 설명할 거예요."],
"Even with anxiety, real pain deserves a real answer.": ["불안이 있더라도, 진짜 통증에는 진짜 휴식이 필요해요.", "불안이 있더라도, 진짜 통증에는 진짜 약이 필요해요."],
"I'm so sorry for your loss — take all the time you need.": ["상실에 진심으로 애도를 표해요 — 필요한 만큼 물을 드세요.", "상실에 진심으로 애도를 표해요 — 필요한 만큼 간호사를 부르세요."],
"There's no right way to feel right now.": ["지금 어떤 기분이든 옳고 그른 시간은 없어요.", "내일 어떤 기분이든 옳고 그른 방식은 없어요."],
"I'm here to sit with you and help however I can.": ["문밖에서 제가 할 수 있는 어떤 식으로든 돕고 싶어요.", "곁에 앉아 제가 할 수 있는 어떤 식으로든 기다리고 싶어요."],
"This grief is a normal response to a terrible loss.": ["이 슬픔은 끔찍한 소식에 대한 정상적인 반응이에요.", "이 슬픔은 끔찍한 상실에 대한 갑작스러운 반응이에요."],
"Some people cry, some go quiet, and both are okay.": ["우는 사람도, 웃는 사람도 있어요, 둘 다 괜찮아요.", "화내는 사람도, 조용해지는 사람도 있어요, 둘 다 괜찮아요."],
"I won't rush you through this.": ["이 과정을 미루게 하지 않을게요.", "이 과정을 혼자 겪게 하지 않을게요."],
"This person is here just to make sure you're safe, not to judge you.": ["이 분은 당신이 편한지 확인하러 있는 거지, 판단하러 있는 게 아니에요.", "이 분은 당신이 안전한지 확인하러 있는 거지, 치료하러 있는 게 아니에요."],
"You can talk to them or not — whatever feels comfortable.": ["이야기해도 되고 쉬어도 돼요 — 편한 대로 하시면 돼요.", "이야기해도 되고 그림을 그려도 돼요 — 편한 대로 하시면 돼요."],
"It's a temporary support while we work on the next steps.": ["다음 단계를 진행하는 동안의 일시적인 휴식이에요.", "다음 검사를 진행하는 동안의 일시적인 지원이에요."],
"Someone will stay close by to keep you safe tonight.": ["내일 밤 안전하게 지켜드리려고 누군가 가까이 있을 거예요.", "오늘 밤 편안하게 해드리려고 누군가 가까이 있을 거예요."],
"They'll stay with you to keep you safe, not as a punishment.": ["안전을 지키려고 곁에 있는 것이지, 시험이 아니에요.", "안전을 지키려고 문 앞에 있는 것이지, 벌로 그러는 게 아니에요."],
"You don't have to talk to them if you're not comfortable.": ["편하지 않으면 그 분과 굳이 식사하지 않아도 돼요.", "피곤하면 그 분과 굳이 이야기하지 않아도 돼요."],
"Let's list a few people you can call when things feel dark.": ["힘든 순간이 올 때 연락할 장소들을 몇 곳 적어봐요.", "즐거운 순간이 올 때 연락할 사람들을 몇 명 적어봐요."],
"What has helped you get through hard moments before?": ["예전에 힘든 순간을 버티는 데 누가 도움이 되었나요?", "최근에 힘든 순간을 버티는 데 무엇이 도움이 되었나요?"],
"We'll make a plan together that you can actually use.": ["실제로 쓸 수 있는 목록을 함께 만들 거예요.", "실제로 쓸 수 있는 계획을 친구와 함께 만들 거예요."],
"Who are the people you'd call first when things get hard?": ["힘들어질 때 가장 먼저 연락할 곳은 어디인가요?", "힘들어질 때 가장 나중에 연락할 사람은 누구인가요?"],
"Let's also plan how to remove anything you could use to hurt yourself.": ["자해에 쓸 만한 것을 없애는 시간도 함께 계획해봐요.", "자해에 쓸 만한 것을 없애는 사람도 함께 계획해봐요."],
"This plan is yours, so it needs to actually work for you.": ["이 계획은 병원의 것이니, 실제로 병원에 맞아야 해요.", "이 계획은 당신의 것이니, 실제로 짧아야 해요."],
"I'm going to keep my distance — I'm not here to hurt you.": ["오래 거리를 두고 있을게요 — 당신을 해치려는 게 아니에요.", "거리를 두고 있을게요 — 당신을 보러 온 게 아니에요."],
"You're in control of this conversation; tell me what you need.": ["이 대화의 주도권은 당신에게 있어요; 마시고 싶은 걸 말씀해 주세요.", "이 대화의 주도권은 의사에게 있어요; 필요한 걸 말씀해 주세요."],
"Let's lower the noise and lights so you feel more at ease.": ["더 편안하게 느끼도록 소음과 온도를 낮출게요.", "더 안전하게 느끼도록 소음과 조명을 낮출게요."],
"I'm going to stay calm and give you space right now.": ["차분하게 있으면서 지금 당신에게 담요를 드릴게요.", "차분하게 있으면서 지금 당신에게 물을 드릴게요."],
"Tell me what would help you feel safer right now.": ["나중에 더 안전하게 느끼려면 무엇이 도움이 될지 말씀해 주세요.", "지금 더 안전하게 느끼려면 누가 도움이 될지 말씀해 주세요."],
"We're going to work together to keep everyone safe.": ["모두의 식사를 챙기기 위해 함께 협력할 거예요.", "모두의 안전을 지키기 위해 천천히 협력할 거예요."],
"This is only until you're safe, and we'll reassess constantly.": ["이건 안전해질 때까지만이고, 계속 닦아 드릴 거예요.", "이건 안전해질 때까지만이고, 계속 불을 켜 둘 거예요."],
"I'll tell you exactly what medication we're giving and why.": ["정확히 약을 언제 드리는지 말씀드릴게요.", "정확히 어떤 음식을 왜 드리는지 말씀드릴게요."],
"As soon as it's safe, these restraints come off.": ["안전해지는 대로 이 억제대는 바로 점검해드려요.", "안전해지는 대로 이 억제대는 곧 옮겨드려요."],
"I know this feels frightening, but it's only until you're safe.": ["외롭게 느껴질 수 있지만, 안전해질 때까지만이에요.", "무섭게 느껴질 수 있지만, 근무 교대 때까지만이에요."],
"We check on you constantly to see if the restraints can come off.": ["침대를 올릴 수 있는지 계속 확인하고 있어요.", "보호자를 만날 수 있는지 계속 확인하고 있어요."],
"I'll explain exactly why you need this medication right now.": ["지금 이 약이 언제 필요한지 설명해 드릴게요.", "나중에 이 약이 왜 필요한지 정확히 설명해 드릴게요."],
"I hear you want to leave — let me make sure you understand the risks.": ["떠나고 싶어 하시는 거 들었어요 — 비용을 이해하고 계신지 확인할게요.", "쉬고 싶어 하시는 거 들었어요 — 위험을 이해하고 계신지 확인할게요."],
"Right now my job is to keep you safe, even when it's hard.": ["지금 제 역할은 힘들어도 당신을 편안하게 모시는 거예요.", "지금 경비의 역할은 힘들어도 당신을 안전하게 지키는 거예요."],
"Can you tell me what you think will happen if you go home?": ["병원에 있으면 어떤 일이 일어날 거라고 생각하시나요?", "집에 가면 누가 기다릴 거라고 생각하시나요?"],
"I need to understand if you can think clearly about this decision.": ["이 결정을 오늘 내릴 수 있는지 확인해야 해요.", "이 비용을 명확하게 생각할 수 있는지 확인해야 해요."],
"I know you want to go home, but it's my job to keep you safe right now.": ["일터에 가고 싶으신 거 알지만, 지금은 안전을 지키는 게 제 역할이에요.", "집에 가고 싶으신 거 알지만, 지금은 안전을 지키는 게 원무과 역할이에요."],
"Even if this feels unfair, I have to take the risks seriously.": ["부당하게 느껴지더라도, 그 규칙은 진지하게 받아들여야 해요.", "불안하게 느껴지더라도, 그 위험은 진지하게 받아들여야 해요."],
"I know this wait has been exhausting for both of you.": ["이 기다림이 두 분 모두에게 놀라운 일이었다는 거 알아요.", "이 기다림이 세 분 모두에게 지치는 일이었다는 거 알아요."],
"Beds are limited, and I'm checking for openings every shift.": ["병상이 제한적이라, 매일 아침 빈자리를 확인하고 있어요.", "의자가 제한적이라, 매 근무마다 빈자리를 확인하고 있어요."],
"Let me tell you exactly what we're doing while you wait.": ["기다리시는 동안 저희가 어디에 연락하고 있는지 정확히 말씀드릴게요.", "기다리시는 동안 저희가 무엇을 하고 있는지 정확히 보여드릴게요."],
"I understand how frustrating this long wait must feel.": ["이 긴 대화가 얼마나 답답하게 느껴질지 이해해요.", "이 짧은 기다림이 얼마나 답답하게 느껴질지 이해해요."],
"As soon as a bed opens, you'll be the first to know.": ["병상이 나는 대로 가장 먼저 모셔드릴게요.", "간호사가 오는 대로 가장 먼저 알려드릴게요."],
"We're doing everything we can to get a bed as soon as possible.": ["보호자를 최대한 빨리 모시려고 할 수 있는 모든 걸 하고 있어요.", "병상을 최대한 빨리 구하려고 할 수 있는 일부를 하고 있어요."],
"It sounds like you're carrying a lot of anger — can we talk about it?": ["많은 슬픔을 안고 계신 것 같아요 — 그것에 대해 이야기해볼까요?", "많은 분노를 안고 계신 것 같아요 — 그것에 대해 친구와 이야기해볼까요?"],
"Do you have a specific plan or person in mind?": ["구체적인 계획이나 생각해 둔 장소가 있나요?", "구체적인 약속이나 생각해 둔 사람이 있나요?"],
"I have to take threats seriously to keep everyone safe, including you.": ["당신을 포함해 모두의 안전을 지키려면 규칙을 진지하게 받아들여야 해요.", "가족을 포함해 모두의 안전을 지키려면 위협을 진지하게 받아들여야 해요."],
"Can you tell me exactly what you're planning to do to him?": ["그 사람에게 정확히 언제 하려는 계획인지 말씀해 주시겠어요?", "그 사람에게 정확히 무엇을 받으려는 계획인지 말씀해 주시겠어요?"],
"Because of this threat, I have to tell a few other people on the team.": ["이 위협 때문에, 팀의 다른 사람들에게도 물어봐야 해요.", "이 병 때문에, 팀의 다른 사람들에게도 알려야 해요."],
"Your anger makes sense, but I still need to ask who it's aimed at.": ["화가 나는 건 이해되지만, 그게 언제부터인지 여쭤봐야 해요.", "슬픈 건 이해되지만, 그게 누구를 향한 건지 여쭤봐야 해요."],
"I'm going to explain everything I do, even if you can't respond.": ["대답하지 못하시더라도, 제가 아는 모든 걸 설명해 드릴게요.", "대답하지 못하시더라도, 제가 하는 모든 걸 보여 드릴게요."],
"I'm here with you and you're safe.": ["당신 곁에 있고, 당신은 조용해요.", "문 곁에 있고, 당신은 안전해요."],
"I'll check a few things gently to understand what's happening.": ["무슨 일이 일어나고 있는지 정리하려고 몇 가지를 부드럽게 확인해 볼게요.", "무슨 일이 일어나고 있는지 이해하려고 몇 가지를 부드럽게 물어볼게요."],
"I'm going to look at your eyes and check how your body responds.": ["손을 살펴보고 몸이 어떻게 반응하는지 확인할게요.", "눈을 살펴보고 몸이 어떻게 반응하는지 들어 볼게요."],
"I know you may not be able to answer, but I'm still listening.": ["대답을 못하실 수도 있지만, 저는 계속 보고 있어요.", "대답을 못하실 수도 있지만, 저는 계속 말하고 있어요."],
"We're checking your body carefully to rule out other causes.": ["다른 원인을 배제하기 위해 몸을 조심스럽게 옮기고 있어요.", "다른 원인을 알아보기 위해 몸을 빠르게 확인하고 있어요."],
"Something's changed — talk to me about what's going on right now.": ["뭔가 달라졌네요 — 무슨 일인지 동료에게 말해 주세요.", "뭔가 달라졌네요 — 어제 무슨 일이 있었는지 저에게 말해 주세요."],
"You're not alone in this hallway; I'm staying right here.": ["이 방에서 혼자가 아니에요; 제가 바로 여기 있을게요.", "이 복도에서 혼자가 아니에요; 제가 바로 앞에서 걸을게요."],
"Let's get you somewhere safer while we sort this out.": ["이걸 해결하는 동안 더 조용한 곳으로 모실게요.", "이걸 해결하는 동안 더 따뜻한 곳으로 모실게요."],
"Tell me exactly what changed in the last few minutes.": ["지난 몇 시간 동안 정확히 무엇이 달라졌는지 말씀해 주세요.", "지난 몇 분 동안 정확히 누가 다녀갔는지 말씀해 주세요."],
"I'm not leaving you alone until we get you somewhere safer.": ["더 조용한 곳으로 모실 때까지 혼자 두지 않을게요.", "보호자가 올 때까지 혼자 두지 않을게요."],
"Let's move quickly and figure out what's going on right now.": ["빠르게 움직여서 지금 누가 필요한지 파악해봐요.", "조용히 움직여서 지금 무슨 일인지 파악해봐요."],
}
W = {
"w-access": {"ko": ["허가(서류)", "보관(방법)"]},
"w-back": {"ko": ["(미리) 먼저", "나중에"]},
"w-something": {"ko": ["아무것도", "누군가"]},
"w-keep": {"ko": ["가두다, 감금하다", "풀어 주다, 놓아주다"]},
"w-courage": {"en": ["coverage", "courtesy"]},
"w-tell": {"ko": ["물어보다, 질문하다", "들어 주다, 경청하다"]},
"w-call": {"ko": ["찾아가다, 방문하다", "부탁하다, 맡기다"]},
"w-work": {"ko": ["멈추다, 고장 나다; (방법이) 막히다", "쉬다, 놀다; (방법이) 어긋나다"]},
"w-rate": {"ko": ["(심박) 리듬, 박자", "(심박) 범위, 구간"]},
"w-get": {"ko": ["포기하다, (상태가) 끝나다", "멈추다, (상태를) 끝내다"]},
"w-fine": {"ko": ["피곤한, 기운 없는", "우울한, 의욕 없는"]},
"w-exactly": {"en": ["extremely", "eventually"]},
"w-sit": {"ko": ["(곁에) 눕다", "(곁에) 서다"]},
"w-grief": {"en": ["brief", "greed"]},
"w-response": {"en": ["resource", "recompense"]},
"w-off": {"ko": ["묶여, 걸려", "조여, 잠겨"]},
"w-sound": {"ko": ["~처럼 보이다", "~처럼 믿다"]},
"w-mind": {"ko": ["계획(의도)", "기억(회상)"]},
"w-eye": {"en": ["ear", "ice"]},
}
B = {"I know this feels frightening, but it's only until you're safe.": ["complicated", "disappointing", "interesting"]}
if __name__ == "__main__":
    go("er-psych", S, W, B)
