from dk_lib import run
S={
"When did the burning with urination start?":["배뇨 시 통증이 언제 시작됐나요?","배뇨 시 화끈거림이 어디서 시작됐나요?"],
"How often are you needing to urinate?":["얼마나 자주 대변을 봐야 하나요?","얼마나 자주 물을 마셔야 하나요?"],
"Have you noticed any blood or strong odor in your urine?":["소변에서 피나 거품을 알아차리셨나요?","대변에서 피나 강한 냄새를 알아차리셨나요?"],
"Does it burn the whole time you're urinating, or just at the start?":["소변보는 내내 화끈거리나요, 아니면 끝에만 그런가요?","소변보는 내내 가려운가요, 아니면 처음에만 그런가요?"],
"Have you had any fever or pain in your lower belly?":["열이나 허리 통증이 있었나요?","오한이나 아랫배 통증이 있었나요?"],
"I need to check a urine sample before we go further.":["더 진행하기 전에 혈액 검체를 확인해야 해요.","더 진행하기 전에 소변 검체를 표시해야 해요."],
"First, clean the area with the wipe we give you.":["먼저, 저희가 드리는 비누로 손을 씻으세요.","먼저, 저희가 드리는 가운으로 갈아입으세요."],
"Start urinating, then catch the middle part of the stream in the cup.":["소변을 보기 시작한 뒤, 중간 부분을 컵에 받는 걸 도와 드릴게요.","소변을 보기 시작한 뒤, 마지막 부분을 컵에 받으세요."],
"Try not to touch the inside of the cup.":["컵 뚜껑은 바닥에 놓지 않도록 하세요.","컵 안쪽은 들여다보지 않도록 하세요."],
"Let me explain the steps before you begin.":["시작하기 전에 컵을 보여 드릴게요.","시작하기 전에 이름을 확인해 드릴게요."],
"Do you have any questions about the collection?":["검사에 대해 궁금한 점이 있으신가요?","채취에 대해 불편한 점이 있으신가요?"],
"Once you're done, seal the cup and bring it to the front desk.":["끝나면 컵을 밀봉해서 간호사에게 주세요.","끝나면 컵을 밀봉해서 의자에 두세요."],
"When was the last time you were able to urinate?":["마지막으로 물을 마실 수 있었던 때가 언제였나요?","마지막으로 대변을 볼 수 있었던 때가 언제였나요?"],
"Does your lower belly feel full or tender?":["윗배가 가득 차거나 압통이 있나요?","아랫배가 가득 차거나 쓰라린가요?"],
"We may need to place a small catheter to drain your bladder.":["방광을 확인하기 위해 작은 스캐너를 대야 할 수도 있어요.","방광을 확인하기 위해 소변 검체가 필요할 수도 있어요."],
"How long has it been since you last urinated?":["마지막으로 식사를 한 지 얼마나 됐나요?","마지막으로 대변을 본 지 얼마나 됐나요?"],
"I'm going to press gently on your belly to check.":["확인을 위해 등을 부드럽게 눌러볼게요.","확인을 위해 배를 부드럽게 두드려볼게요."],
"The catheter will relieve the pressure right away.":["카테터가 즉시 소변량을 확인해줄 거예요.","스캐너가 즉시 압박감을 확인해줄 거예요."],
"Is there any pain when you urinate?":["소변볼 때 냄새가 있나요?","대변볼 때 통증이 있나요?"],
"When did you first notice the red color?":["빨간 색깔을 어디서 처음 알아차리셨나요?","갈색 색깔을 언제 처음 알아차리셨나요?"],
"Is the blood at the start, the end, or throughout?":["피가 처음에 나오나요, 중간에 나오나요, 아니면 계속 나오나요?","피가 처음에 나오나요, 끝에 나오나요, 아니면 가끔 나오나요?"],
"Have you passed any clots along with the blood?":["피와 함께 돌을 배출한 적이 있나요?","피와 함께 고름을 배출한 적이 있나요?"],
"Does the color change from one trip to the bathroom to the next?":["화장실에 갈 때마다 냄새가 바뀌나요?","식사할 때마다 색깔이 바뀌나요?"],
"We'll send your urine to the lab for more testing.":["추가 검사를 위해 혈액을 검사실로 보낼게요.","추가 검사를 위해 소변을 외래로 보낼게요."],
"You may feel some pressure, but it shouldn't be sharply painful.":["압박감은 느낄 수 있지만 차갑게 느껴질 거예요.","압박감은 느낄 수 있지만 곧 소변이 나오기 시작할 거예요."],
"We keep everything sterile to prevent infection.":["감염을 예방하기 위해 모든 것을 따로 포장해 두어요.","감염을 예방하기 위해 모든 것을 깨끗이 닦아 두어요."],
"Tell me if you feel any discomfort and I'll go slowly.":["불편감이 있으면 손을 들어 주세요, 천천히 할게요.","불편감이 있으면 말씀해 주세요, 설명해 드릴게요."],
"This will only take a couple of minutes.":["이건 몇 가지만 확인하면 돼요.","이건 소변이 나오면 끝나요."],
"Try to relax and breathe normally for me.":["긴장을 풀고 평소대로 다리를 벌려 보세요.","긴장을 풀고 평소대로 눈을 감아 보세요."],
"You're doing great, almost done.":["아주 잘하고 계세요, 곧 시작할게요.","아주 잘하고 계세요, 거의 준비됐어요."],
"Does the pain come in waves or stay constant?":["통증이 파도처럼 오나요, 아니면 밤에만 있나요?","통증이 갑자기 오나요, 아니면 계속되나요?"],
"Does it travel from your side down toward your groin?":["옆구리에서 어깨 쪽으로 올라가며 방사되나요?","옆구리에서 서혜부 쪽으로 내려가며 저리나요?"],
"We'll give you pain medicine and arrange a CT scan.":["진통제를 드리고 소변검사를 준비할게요.","진통제를 드리고 초음파 촬영을 준비할게요."],
"On a scale of one to ten, how bad is the pain right now?":["1부터 10까지 중에, 어제 통증이 얼마나 심했나요?","1부터 10까지 중에, 지금 불안이 얼마나 심한가요?"],
"It might come and go, or stay constant the whole time.":["왔다 갔다 할 수도 있고, 점점 심해질 수도 있어요.","왔다 갔다 할 수도 있고, 갑자기 멈출 수도 있어요."],
"We'll get you comfortable while we wait for the scan.":["스캔을 기다리는 동안 설명해 드릴게요.","스캔을 기다리는 동안 담요를 드릴게요."],
"Does it hurt when I tap over your back here?":["여기 배를 누를 때 아픈가요?","여기 등을 문지를 때 아픈가요?"],
"Have you had fever, chills, or nausea?":["열, 기침, 또는 메스꺼움이 있었나요?","열, 오한, 또는 어지러움이 있었나요?"],
"We'll get a urine culture before starting antibiotics.":["항생제 투여 전에 알레르기를 확인할게요.","항생제 투여 전에 활력징후를 확인할게요."],
"This pain in your back and side is common with a kidney infection.":["배와 옆구리의 이런 통증은 신장 감염에서 흔해요.","등과 옆구리의 이런 통증은 신장 결석에서 흔해요."],
"We'll start antibiotics as soon as the culture is collected.":["배양검사 채취가 끝나는 대로 결과를 확인할게요.","배양검사 채취가 끝나는 대로 활력징후를 확인할게요."],
"Let's get your temperature and check your blood pressure.":["몸무게를 재고 혈압을 확인할게요.","체온을 재고 맥박을 확인할게요."],
"Have you had a weak stream or trouble starting for a while?":["소변 줄기가 약하거나 끊기는 게 한동안 있었나요?","소변 줄기가 약하거나 시작하기 어려운 게 어제부터 있었나요?"],
"We'll do a quick bladder scan to see how full it is.":["얼마나 찼는지 보기 위해 소변검사를 빠르게 할게요.","얼마나 늘었는지 보기 위해 방광스캔을 빠르게 할게요."],
"This will tell us how much urine is inside your bladder.":["이걸로 방광 안에 피가 얼마나 있는지 알 수 있어요.","이걸로 신장 안에 소변이 얼마나 있는지 알 수 있어요."],
"How long have you been having trouble starting your stream?":["소변 줄기가 약해진 게 얼마나 오래됐나요?","소변 줄기를 멈추기 어려운 게 얼마나 오래됐나요?"],
"Do you feel like your bladder is completely empty after you go?":["소변을 보는 중에 방광이 아프다고 느끼시나요?","소변을 본 후에 허리가 완전히 풀렸다고 느끼시나요?"],
"We'll pass a catheter now to relieve the pressure and drain your bladder.":["지금 스캐너를 대서 압박감을 확인하고 방광을 살펴볼게요.","지금 카테터를 준비해서 압박감을 설명하고 방광을 확인할게요."],
"Exactly when did the pain start?":["정확히 어디서 통증이 시작됐나요?","정확히 언제 붓기가 시작됐나요?"],
"Is the pain only on one side, or on both sides?":["통증이 한쪽에만 있나요, 아니면 배에도 있나요?","붓기가 한쪽에만 있나요, 아니면 양쪽 다 있나요?"],
"Did you notice any swelling or redness?":["붓거나 멍이 있는 걸 알아차리셨나요?","붓거나 가려운 걸 알아차리셨나요?"],
"This can be an emergency, so we're moving quickly.":["응급 상황일 수 있어서, 저희가 바로 확인하고 있어요.","복잡한 상황일 수 있어서, 저희가 빠르게 움직이고 있어요."],
"We're arranging an urgent ultrasound and calling the specialist.":["긴급 초음파를 준비하고 보호자에게 연락하고 있어요.","긴급 초음파를 준비하고 마취과에 연락하고 있어요."],
"Acting fast can protect the testicle from damage.":["빠르게 대처하면 통증을 줄일 수 있어요.","빠르게 대처하면 고환 손상을 확인할 수 있어요."],
"How long has the catheter been in place?":["카테터가 자리 잡은 곳이 어디인가요?","카테터가 자리 잡은 뒤 열이 있었나요?"],
"Has your urine become cloudy or foul-smelling?":["소변이 붉거나 악취가 나기 시작했나요?","소변이 뿌옇거나 거품이 나기 시작했나요?"],
"We may need to change the catheter and check for infection.":["카테터를 확인하고 감염을 설명해야 할 수도 있어요.","카테터를 교체하고 상처를 확인해야 할 수도 있어요."],
"Has anyone changed the catheter recently?":["최근에 카테터를 만진 적이 있나요?","최근에 소변 주머니를 교체한 적이 있나요?"],
"We'll send a sample from the catheter port for culture.":["카테터 포트에서 검체를 받아 소변검사를 보낼게요.","카테터 포트를 닦아서 검체를 받아 보낼게요."],
"A new catheter should feel more comfortable once it's in place.":["새 카테터가 자리 잡으면 소변이 더 잘 나올 거예요.","새 카테터가 자리 잡으면 확인 후 알려 드릴게요."],
"Which blood thinner are you taking, and when was your last dose?":["어떤 혈압약을 드시고 계시고, 마지막 복용은 언제였나요?","어떤 혈액희석제를 드시고 계시고, 처음 복용은 언제였나요?"],
"Is there any pain along with the blood in your urine?":["소변에 피와 함께 열도 있나요?","대변에 피와 함께 통증도 있나요?"],
"Have you had any recent injury or catheter?":["최근에 부상을 입거나 수술을 받은 적이 있나요?","최근에 넘어지거나 카테터를 넣은 적이 있나요?"],
"How many pills do you take, and at what time each day?":["약을 몇 알씩, 식사 전에 드시나요?","주사를 몇 번씩, 하루 중 몇 시에 맞으시나요?"],
"We'll check your blood levels to see how thin your blood is right now.":["지금 혈액이 얼마나 묽은지 보기 위해 약을 확인할게요.","지금 소변이 얼마나 붉은지 보기 위해 수치를 확인할게요."],
"We may need to hold your next dose until we know more.":["더 알게 될 때까지 다음 복용 시간을 적어 둘게요.","더 알게 될 때까지 다음 복용 시간을 확인해야 할 수도 있어요."],
"When was your last dialysis session?":["마지막 투석 회차가 어디서였나요?","마지막 진료 회차가 언제였나요?"],
"Which arm has your access, so we avoid it for blood pressure?":["손목 밴드가 있는 팔은 어느 쪽이라 혈압 측정 시 피해야 하나요?","혈관통로가 있는 팔은 어느 쪽이라 체온 측정 시 피해야 하나요?"],
"Have you had trouble breathing or swelling in your legs?":["호흡이 어렵거나 가슴이 아픈 게 있었나요?","소변이 적거나 다리가 붓는 게 있었나요?"],
"How many days has it been since your last treatment?":["마지막 치료 이후 몇 번 토했나요?","마지막 식사 이후 며칠이 지났나요?"],
"We'll avoid using that arm for IVs or blood draws.":["그 팔에 주의 표시 팔찌를 붙여 둘게요.","그 팔은 혈압 측정에도 쓰지 않도록 할게요."],
"Your heart and lungs need extra fluid removed safely.":["심장과 폐를 위해 여분의 체액을 안전하게 측정해야 해요.","심장과 신장을 위해 여분의 체액을 안전하게 제거해야 해요."],
"How many times have you vomited today?":["오늘 몇 번이나 설사하셨나요?","어제 몇 번이나 토하셨나요?"],
"We'll give you fluids and medicine to settle your stomach.":["속을 확인하기 위해 수액과 검사를 할게요.","통증을 줄이기 위해 수액과 약을 드릴게요."],
"We'll ask you to strain your urine to catch the stone.":["결석을 잡아내기 위해 소변량을 적어 달라고 요청할게요.","결석을 잡아내기 위해 물을 마셔 달라고 요청할게요."],
"Are you able to keep any water down?":["물을 드시고 토하지 않고 걸으실 수 있나요?","음식을 드시고 토하지 않고 넘기실 수 있나요?"],
"How many hours has it been since you last kept fluids down?":["마지막으로 수분을 유지한 지 며칠이나 됐나요?","마지막으로 구토한 지 몇 시간이나 됐나요?"],
"Once we catch the stone, we'll send it to the lab for testing.":["결석을 잡으면 병동으로 보내 보관할게요.","결석을 잡으면 보호자에게 보여 드릴게요."],
"How many weeks pregnant are you?":["임신 몇 번째이신가요?","입원 몇 일째이신가요?"],
"We'll choose antibiotics that are safe during pregnancy.":["임신 중에도 편안한 자세를 고를게요.","임신 중에도 안전한 검사를 고를게요."],
"We'll also check on the baby's wellbeing.":["산모가 편한지도 함께 확인할게요.","아기 심박수도 함께 확인할게요."],
"Have you had any bleeding or contractions?":["출혈이나 구토가 있었나요?","열이나 수축이 있었나요?"],
"We'll monitor your fever and the baby's heart rate closely.":["열과 산모 혈압을 면밀히 관찰할게요.","열과 아기 움직임을 면밀히 관찰할게요."],
"Staying hydrated can help you feel better.":["휴식을 충분히 취하면 몸이 나아지는 데 도움이 돼요.","수분을 충분히 섭취하면 소변이 맑아지는 데 도움이 돼요."],
"Drinking plenty of water is one of the best ways to prevent stones.":["운동을 꾸준히 하는 것이 결석을 예방하는 좋은 방법 중 하나예요.","물을 충분히 마시는 것이 감염을 예방하는 최고의 방법 중 하나예요."],
"We can review foods that may raise your risk.":["위험을 높일 수 있는 약들을 함께 검토해볼 수 있어요.","위험을 높일 수 있는 습관들을 함께 검토해볼 수 있어요."],
"Following up with a urologist can help find the cause.":["내과 전문의와 추적 관찰하면 원인을 찾는 데 도움이 돼요.","비뇨기과 전문의와 추적 관찰하면 검사 일정을 잡는 데 도움이 돼요."],
"Try to drink enough water every day, especially in hot weather.":["특히 더운 날씨에는 매일 모자를 꼭 쓰도록 하세요.","특히 운동할 때는 매일 물을 충분히 마시도록 하세요."],
"Cutting back on salt can also lower your risk.":["커피 섭취를 줄이는 것도 위험을 낮출 수 있어요.","소금 섭취를 줄이는 것도 통증을 낮출 수 있어요."],
"We'll give you a strainer to catch any future stones.":["앞으로 나올 소변을 재기 위해 눈금 통을 드릴게요.","앞으로 나올 결석을 잡기 위해 설명서를 드릴게요."],
"Your fever and low blood pressure make this an emergency.":["열과 빠른 맥박 때문에 이건 응급 상황이에요.","통증과 낮은 혈압 때문에 이건 응급 상황이에요."],
"We're starting fluids and antibiotics right away.":["지금 바로 수액 라인과 배양검사를 준비할게요.","지금 바로 산소와 모니터를 시작할게요."],
"You may need an urgent procedure to relieve the blockage.":["폐쇄를 확인하기 위해 긴급 촬영이 필요할 수도 있어요.","폐쇄를 풀기 위해 긴급 연락이 필요할 수도 있어요."],
"Your body is fighting a serious infection right now.":["지금 몸이 심각한 탈수와 싸우고 있어요.","지금 몸이 심각한 통증과 싸우고 있어요."],
"We're moving fast because sepsis can turn dangerous quickly.":["패혈증은 빠르게 위험해질 수 있어서 저희도 팀을 부르고 있어요.","탈수는 빠르게 위험해질 수 있어서 저희도 빠르게 움직이고 있어요."],
"A specialist will relieve the blockage as soon as possible.":["전문의가 최대한 빨리 상태를 확인해 줄 거예요.","전문의가 최대한 빨리 연락을 줄 거예요."],
"We're getting an ECG right away to check your heart.":["지금 바로 혈액을 뽑아서 칼륨을 확인할게요.","지금 바로 모니터를 붙여서 심장을 확인할게요."],
"Your potassium may be dangerously high, so we're acting fast.":["칼륨 수치가 위험할 정도로 높을 수 있어서 빠르게 확인하고 있어요.","혈당 수치가 위험할 정도로 높을 수 있어서 빠르게 대처하고 있어요."],
"You may need emergency dialysis.":["응급 검사가 필요할 수도 있어요.","입원 치료가 필요할 수도 있어요."],
"Have you been able to urinate at all today?":["오늘 물을 조금이라도 마실 수 있었나요?","오늘 대변을 조금이라도 볼 수 있었나요?"],
"High potassium can affect your heart rhythm.":["칼륨 수치가 높으면 근육에 영향을 줄 수 있어요.","나트륨 수치가 높으면 심장 리듬에 영향을 줄 수 있어요."],
"We're watching your heart monitor closely for any changes.":["변화가 있는지 소변량을 면밀히 지켜보고 있어요.","변화가 있는지 혈압 모니터를 면밀히 지켜보고 있어요."],
"We're giving you oxygen and sitting you upright to help you breathe.":["모니터를 붙이고 몸을 세워서 숨쉬기 편하도록 도와드릴게요.","산소를 드리고 옷을 풀어서 숨쉬기 편하도록 도와드릴게요."],
"The fluid overload may need urgent dialysis to remove.":["체액 과부하는 긴급 검사로 확인해야 할 수도 있어요.","체액 과부하는 긴급 영상으로 확인해야 할 수도 있어요."],
"Try to take slow breaths — we're right here.":["천천히 눈을 감아 보세요, 저희가 여기 있어요.","천천히 숨을 쉬어 보세요, 곧 의사가 와요."],
"Sitting up straight can make it easier to breathe.":["똑바로 앉으면 말하기가 더 쉬워질 수 있어요.","똑바로 앉으면 삼키기가 더 쉬워질 수 있어요."],
"We're keeping you upright and giving extra oxygen to ease the strain on your heart.":["몸을 세운 채 여분의 모니터를 붙여서 심장의 상태를 확인할게요.","몸을 세운 채 여분의 베개를 드려서 허리의 부담을 덜어드릴게요."],
"The swelling in your legs should improve once the fluid comes off.":["체액이 빠지면 다리 통증도 나아질 거예요.","체액이 빠지면 호흡도 편해질 거예요."],
"How many hours has this been going on?":["이게 며칠이나 지속되고 있나요?","이게 몇 번이나 반복되고 있나요?"],
"This is time-sensitive, so we're contacting the specialist now.":["이건 통증이 심해서 지금 전문의에게 연락하고 있어요.","이건 시간이 중요해서 지금 보호자에게 연락하고 있어요."],
"We'll give you pain medicine while we prepare treatment.":["치료를 준비하는 동안 얼음찜질을 드릴게요.","치료를 준비하는 동안 담요를 드릴게요."],
"Is there any injury or new medicine that might explain this?":["부상이나 새로 드신 음식이 이걸 설명할 수 있을까요?","부상이나 새로 받은 주사가 이걸 설명할 수 있을까요?"],
"The longer this goes on, the higher the risk to the tissue.":["이게 오래 지속될수록 통증이 더 심해져요.","이게 오래 지속될수록 감염에 대한 위험이 높아져요."],
"We're calling the on-call urologist right away.":["지금 바로 당직 마취과 전문의에게 연락하고 있어요.","지금 바로 당직 비뇨기과 간호사에게 연락하고 있어요."],
"Have you been able to pass any urine since the accident?":["사고 이후 물을 조금이라도 마실 수 있었나요?","사고 이후 걸음을 조금이라도 걸을 수 있었나요?"],
"We're going to do a special X-ray of your bladder with contrast.":["조영제를 사용해서 신장의 특수 엑스레이를 찍을게요.","조영제를 사용해서 방광의 특수 CT를 찍을게요."],
"We're keeping the trauma team involved for your pelvis.":["골반 때문에 정형외과도 계속 함께 볼 거예요.","골반 때문에 외상팀도 곧 함께 설명할 거예요."],
"Does your pelvis hurt when I press here?":["여기를 누르면 허리가 아픈가요?","여기를 누르면 다리가 아픈가요?"],
"We're watching for blood at the tip before we place any tube.":["관을 넣기 전에 골반 사진이 있는지 살펴보고 있어요.","관을 넣기 전에 알레르기가 있는지 살펴보고 있어요."],
"The surgeon may need to repair the bladder in the operating room.":["외과의가 수술실에서 골반을 복구해야 할 수도 있어요.","외과의가 수술 전에 방광을 확인해야 할 수도 있어요."],
"How much have you urinated over the last few hours?":["지난 몇 시간 동안 물을 얼마나 드셨나요?","지난 몇 시간 동안 대변을 얼마나 보셨나요?"],
"Your labs have changed, so I'm updating the doctor.":["검사 수치가 바뀌어서 간호사에게 알리고 있어요.","검사 수치가 바뀌어서 기록을 확인하고 있어요."],
"I'll report your urine output and potassium trend clearly.":["소변 배출량과 혈압 추이를 명확하게 보고할게요.","소변 배출량과 칼륨 추이를 명확하게 기록할게요."],
"Your potassium has been climbing for the past few hours.":["지난 몇 시간 동안 맥박이 계속 오르고 있어요.","지난 며칠 동안 칼륨이 계속 오르고 있어요."],
"I'm going to call the on-call doctor now with these numbers.":["지금 이 수치들을 가지고 당직 간호사에게 연락할 거예요.","지금 이 수치들을 가지고 당직 의사에게 설명할 거예요."],
"I'll give a clear report of your urine output and vital signs.":["소변 배출량과 검사 결과를 명확하게 보고할게요.","수액 투여량과 활력징후를 명확하게 보고할게요."],
}
WKO={"w-drain":["(물로) 씻어 내다","(관으로) 채우다"],"w-pass":["(음식을) 삼키다","(구멍을) 틀어막다"],"w-change":["기록하다","(통을) 비우다"],
"w-trip":["잠깐 쉬어가기","순서 기다리기"],"w-take":["(약을) 처방하다","(약을) 끊다"],"w-wave":["한결같음","바늘로 찌르기"],"w-hydrated":["탈수된","음식을 굶은"]}
WEN={"w-temperature":["temperament","temperance"],"w-empty":["full","swollen"],"w-hydrated":["dehydrated","heated"]}
B={"We'll send your urine to the lab for more testing.":["ICU","ER","OR"],
"Let's get your temperature and check your blood pressure.":["medication","insurance","occupation"],
"We're arranging an urgent ultrasound and calling the specialist.":["mammogram","endoscopy","colonoscopy"],
"This is time-sensitive, so we're contacting the specialist now.":["uncomplicated","self-limiting","insignificant"]}
run('er-genitourinary',S,WKO,WEN,B)
