import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from dk_lib_5 import run
P = os.path.join(os.path.dirname(os.path.abspath(__file__)), "base-er-head-trauma.yaml")
S = {
# 두부외상 초기 사정
"How did you hit your head?": ["어디서 머리를 부딪히셨어요?", "언제 머리를 부딪히셨어요?"],
"Did you lose consciousness at all?": ["잠깐이라도 시력을 잃으셨나요?", "잠깐이라도 청력을 잃으셨나요?"],
"Do you remember everything right before it happened?": ["그 일이 있기 직전까지 다 설명하실 수 있으세요?", "그 일이 있기 하루 전까지 다 기억나세요?"],
"Can you tell me exactly how you fell?": ["정확히 어디서 넘어지셨는지 말씀해 주시겠어요?", "정확히 언제 넘어지셨는지 말씀해 주시겠어요?"],
"Were you awake the whole time after you fell?": ["넘어진 뒤로 계속 혼자 계셨나요?", "넘어진 뒤로 계속 서 계셨나요?"],
"Do you feel like you're missing any part of what happened?": ["그 일 중에서 기억이 반복되는 부분이 있는 것 같으세요?", "그 일 중에서 기억나는 말이 있는 것 같으세요?"],
# GCS 측정·재평가
"Can you open your eyes and look at me?": ["눈을 비비고 저를 봐 주시겠어요?", "입을 벌리고 저를 봐 주시겠어요?"],
"Tell me where you are and what day it is.": ["여기가 어디고 오늘이 몇 월인지 말씀해 주세요.", "여기가 어디고 올해가 몇 년인지 말씀해 주세요."],
"I'm going to recheck this in a few minutes.": ["몇 분 뒤에 이걸 다시 설명할게요.", "몇 분 뒤에 이걸 다시 기록할게요."],
"Squeeze my hand as tight as you can.": ["제 팔을 최대한 세게 잡아 보세요.", "제 손을 최대한 오래 잡아 보세요."],
"Your score has stayed the same since your last check.": ["지난번 확인 이후로 혈압은 그대로예요.", "지난번 확인 이후로 맥박은 그대로예요."],
"I'll ask you these same questions again soon.": ["곧 쉬운 질문을 다시 드릴게요.", "곧 같은 설명을 다시 드릴게요."],
"I ask the same questions again because it shows me if you're changing.": ["같은 질문을 반복하는 건 숨쉬는지 알 수 있어서예요.", "같은 질문을 반복하는 건 주무시는지 알 수 있어서예요."],
# 동공 반응 확인
"I'm shining a light in your eyes — look straight ahead.": ["귀에 빛을 비출게요—정면을 봐 주세요.", "코에 빛을 비출게요—정면을 봐 주세요."],
"This checks how your pupils respond.": ["이건 눈꺼풀이 어떻게 반응하는지 보는 거예요.", "이건 동공이 어떻게 생겼는지 보는 거예요."],
"It'll only take a second, hold still.": ["잠깐이면 되니까 위를 보세요.", "잠깐이면 되니까 밖을 보세요."],
"Both pupils should be the same size.": ["양쪽 동공은 모양이 같아야 해요.", "양쪽 동공은 색이 같아야 해요."],
"One pupil looks larger than the other.": ["한쪽 눈썹이 다른 쪽보다 더 커 보여요.", "한쪽 눈꺼풀이 다른 쪽보다 더 커 보여요."],
"Any change in your pupils could mean something serious.": ["청력에 변화가 있으면 심각한 걸 의미할 수 있어요.", "식욕에 변화가 있으면 심각한 걸 의미할 수 있어요."],
# 두피 열상·혈종 관찰
"I'm going to gently feel your scalp.": ["턱을 살살 만져 볼게요.", "어깨를 살살 만져 볼게요."],
"We'll apply pressure to stop the bleeding.": ["통증을 줄이려고 압박할게요.", "붓기를 줄이려고 압박할게요."],
"Tell me if any spot is especially painful.": ["특별히 부은 부위가 있으면 말씀해 주세요.", "특별히 가려운 부위가 있으면 말씀해 주세요."],
"I can feel a bump and some swelling here.": ["여기서 혹이랑 멍이 만져지네요.", "여기서 혹이랑 열감이 만져지네요."],
"We're holding pressure until the bleeding slows down.": ["통증이 줄어들 때까지 압박을 유지할게요.", "부기가 줄어들 때까지 압박을 유지할게요."],
"The pressure should stay firm and steady.": ["붕대는 계속 깨끗하고 일정하게 유지해야 해요.", "얼음은 계속 차갑고 일정하게 유지해야 해요."],
# 오심·구토 모니터
"How many times have you vomited?": ["몇 번이나 기침하셨어요?", "몇 번이나 기절하셨어요?"],
"Is the nausea getting worse?": ["통증이 점점 심해지고 있나요?", "어지럼증이 점점 심해지고 있나요?"],
"We're watching for signs of pressure in your head.": ["배 속 압력 상승 징후가 있는지 지켜보고 있어요.", "가슴 속 압력 상승 징후가 있는지 지켜보고 있어요."],
"Has the vomiting happened more than once?": ["두통이 한 번 넘게 있었나요?", "어지럼증이 한 번 넘게 있었나요?"],
"I'm keeping track of how you feel each hour.": ["매시간 식사량을 기록하고 있어요.", "매시간 약을 드셨는지 기록하고 있어요."],
"Let me know right away if it gets worse.": ["더 배고프면 바로 알려주세요.", "더 심해지면 바로 지켜봐 주세요."],
# 경증 뇌진탕 귀가교육
"Come back if you have worsening headache or vomiting.": ["두통이나 구토가 심해지면 가족에게 말해 두세요.", "두통이나 구토가 심해지면 메모해 두세요."],
"Watch for confusion, drowsiness, or weakness.": ["혼돈, 졸림, 무력감이 있는지 사진으로 남겨 주세요.", "혼돈, 졸림, 무력감이 있는지 목록으로 만들어 주세요."],
"Have someone stay with you tonight.": ["오늘 밤은 누군가와 함께 식사하세요.", "오늘 밤은 누군가에게 전화하세요."],
"If the headache gets much worse, come back right away.": ["두통이 훨씬 심해지면 바로 시간을 적어 두세요.", "두통이 훨씬 심해지면 바로 점수를 매겨 두세요."],
"Wake him every few hours to check that he responds normally.": ["몇 분마다 깨워서 정상적으로 반응하는지 확인해 주세요.", "몇 시간마다 깨워서 정상적으로 드시는지 확인해 주세요."],
"Any seizure or trouble waking up means you need to return.": ["발작이 있거나 잘 깨어나지 못하면 기록지를 챙겨 둬야 해요.", "발작이 있거나 잘 깨어나지 못하면 영상을 찍어 둬야 해요."],
# 항응고제 복용 경미 두부외상
"Which blood thinner are you taking?": ["어떤 항생제를 복용하고 계세요?", "어떤 수면제를 복용하고 계세요?"],
"Even a minor bump can bleed slowly in the brain.": ["가벼운 충격이라도 위 안에서는 서서히 출혈이 있을 수 있어요.", "가벼운 충격이라도 무릎 안에서는 서서히 출혈이 있을 수 있어요."],
"We recommend a CT scan to be safe.": ["안전하게 PET 스캔을 권해 드려요.", "안전하게 심장 스캔을 권해 드려요."],
"Blood thinners make even small injuries riskier.": ["수면제를 드시면 작은 부상도 더 위험해져요.", "항응고제를 드시면 작은 부상도 더 느리게 나아져요."],
"The scan checks for bleeding we can't see or feel yet.": ["스캔은 아직 안 보이거나 느껴지지 않는 감염까지 확인해요.", "스캔은 아직 안 보이거나 느껴지지 않는 통증까지 확인해요."],
"Even without symptoms now, bleeding can show up hours later.": ["지금 증상이 없어도 몇 시간 뒤에 멍이 나타날 수 있어요.", "지금 열이 없어도 몇 시간 뒤에 출혈이 나타날 수 있어요."],
# 고령 낙상 경막하 의심
"When exactly did he fall?": ["정확히 어디서 넘어지셨어요?", "정확히 왜 넘어지셨어요?"],
"Has his confusion been getting worse over days?": ["며칠에 걸쳐 두통이 더 심해지고 있나요?", "며칠에 걸쳐 졸음이 더 심해지고 있나요?"],
"A slow brain bleed can show up like this.": ["서서히 진행되는 감염이 이렇게 나타날 수 있어요.", "서서히 진행되는 빈혈이 이렇게 나타날 수 있어요."],
"Is he acting differently than he usually does?": ["평소와 다르게 말씀하시나요?", "평소와 다르게 걸으시나요?"],
"Family often notices these changes before we do.": ["이런 변화는 저희보다 이웃이 먼저 알아채는 경우가 많아요.", "이런 변화는 저희보다 환자분이 먼저 알아채는 경우가 많아요."],
"We'll get a CT scan to check for bleeding in his brain.": ["배 안 출혈을 확인하려고 CT 스캔을 할게요.", "가슴 안 출혈을 확인하려고 CT 스캔을 할게요."],
# 소아 두부외상 부모 소통
"Can you walk me through exactly how he fell?": ["정확히 언제 넘어졌는지 차근차근 설명해 주시겠어요?", "정확히 어디서 넘어졌는지 차근차근 설명해 주시겠어요?"],
"Watch for vomiting, unusual sleepiness, or fussiness.": ["구토, 평소와 다른 졸림, 이앓이가 있는지 지켜봐 주세요.", "구토, 평소와 다른 졸림, 침 흘림이 있는지 지켜봐 주세요."],
"We'll examine him carefully to be sure.": ["확실히 하기 위해 꼼꼼하게 촬영할게요.", "확실히 하기 위해 꼼꼼하게 체중을 잴게요."],
"It helps to know if the story matches what we see.": ["말씀하신 상황과 저희가 듣는 소견이 맞는지 아는 게 도움이 돼요.", "말씀하신 상황과 저희가 생각하는 소견이 맞는지 아는 게 도움이 돼요."],
"Please tell me if he seems more sleepy than usual.": ["평소보다 더 보채 보이면 말씀해 주세요.", "평소보다 더 배고파 보이면 말씀해 주세요."],
"Call us right away if he throws up or won't wake easily.": ["토하거나 잘 깨지 않으면 바로 수건을 챙겨 주세요.", "토하거나 잘 깨지 않으면 바로 아이 이름을 불러 주세요."],
# 음주 동반 두부외상
"How much did you drink tonight?": ["오늘 밤 얼마나 주무셨어요?", "오늘 밤 얼마나 피우셨어요?"],
"I can't tell if it's alcohol or your injury — so we watch you.": ["약 때문인지 부상 때문인지 구분이 안 돼서—그래서 계속 지켜봐요.", "발작 때문인지 부상 때문인지 구분이 안 돼서—그래서 계속 지켜봐요."],
"Please stay so we can recheck you.": ["입원할 수 있게 계셔 주세요.", "전원할 수 있게 계셔 주세요."],
"Have you hit your head at all tonight?": ["오늘 밤 팔을 부딪힌 적이 있나요?", "오늘 밤 무릎을 부딪힌 적이 있나요?"],
"Alcohol can hide the signs we need to watch for.": ["커피는 저희가 지켜봐야 할 징후를 가릴 수 있어요.", "소음은 저희가 지켜봐야 할 징후를 가릴 수 있어요."],
"We'll keep checking on you until you're clearly sober and steady.": ["확실히 술이 깨고 안정될 때까지 계속 설명할게요.", "확실히 열이 내리고 안정될 때까지 계속 확인할게요."],
# 두개저 골절 징후
"I see bruising around your eyes — when did that appear?": ["눈 주위에 붉은 기가 보이는데—언제부터 생겼어요?", "눈 주위에 긁힌 자국이 보이는데—언제부터 생겼어요?"],
"Is there any clear fluid from your nose or ears?": ["코나 귀에서 누런 액체가 나오나요?", "코나 눈에서 맑은 액체가 나오나요?"],
"Please don't blow your nose.": ["코를 비비지 말아 주세요.", "코를 파지 말아 주세요."],
"Bruising around both eyes can mean a fracture at the base of your skull.": ["양쪽 눈 주위의 멍은 척추 골절을 의미할 수 있어요.", "양쪽 눈 주위의 멍은 두개저 감염을 의미할 수 있어요."],
"That clear fluid could be spinal fluid leaking.": ["그 끈적한 액체는 뇌척수액이 새는 것일 수 있어요.", "그 초록 액체는 뇌척수액이 새는 것일 수 있어요."],
"Let me check behind your ears for any bruising too.": ["귀 안쪽에도 멍이 있는지 확인해 볼게요.", "귀 위쪽에도 멍이 있는지 확인해 볼게요."],
# 뇌진탕후증후군
"How long have the headaches been going on?": ["코피가 얼마나 오래 지속되고 있나요?", "목 통증이 얼마나 오래 지속되고 있나요?"],
"Any trouble concentrating or sleeping?": ["삼키거나 잠드는 데 어려움이 있으세요?", "걷거나 잠드는 데 어려움이 있으세요?"],
"These symptoms can linger after a concussion.": ["이런 증상은 감염 후에 계속 남을 수 있어요.", "이런 증상은 수술 후에 계속 남을 수 있어요."],
"Do you still feel dizzy or off balance?": ["아직도 졸리거나 균형이 안 잡히세요?", "아직도 어지럽거나 메스꺼우세요?"],
"Most people improve slowly over several weeks.": ["대부분은 몇 달에 걸쳐 서서히 나아져요.", "대부분은 몇 주에 걸쳐 서서히 적응해요."],
"Rest and light activity both help your brain recover.": ["휴식과 가벼운 활동 둘 다 심장 회복에 도움이 돼요.", "휴식과 가벼운 활동 둘 다 허리 회복에 도움이 돼요."],
# 반복 구토·기면 진행
"How many times has he vomited now?": ["지금까지 몇 번 먹었나요?", "지금까지 몇 번 잤나요?"],
"Is he getting harder to wake up?": ["점점 말하기가 더 힘들어지고 있나요?", "점점 앉기가 더 힘들어지고 있나요?"],
"This could mean rising pressure — we're rechecking him now.": ["열이 오르고 있다는 뜻일 수 있어서—지금 다시 확인하고 있어요.", "압력이 오르고 있다는 뜻일 수 있어서—지금 다시 기록하고 있어요."],
"He's vomited three times in the last hour.": ["지난 한 시간 동안 세 번 기침했어요.", "지난 한 시간 동안 세 번 졸았어요."],
"I'm calling the doctor right now to report this change.": ["지금 바로 약사에게 전화해서 이 변화를 보고할게요.", "지금 바로 기사님에게 전화해서 이 변화를 보고할게요."],
"He's much harder to wake than he was an hour ago.": ["한 시간 전보다 훨씬 먹이기 힘들어졌어요.", "한 시간 전보다 훨씬 옮기기 힘들어졌어요."],
# 언어장벽 두부외상
"Did you black out? Yes or no?": ["토하셨어요? 예, 아니오?", "넘어지셨어요? 예, 아니오?"],
"Blood thinner medicine — do you take it?": ["수면제 약—드시고 계세요?", "항생제 약—드시고 계세요?"],
"I'm getting an interpreter for you.": ["휠체어를 가져다 드릴게요.", "담요를 가져다 드릴게요."],
"Point to where it hurts the most.": ["가장 가려운 곳을 가리켜 주세요.", "가장 뜨거운 곳을 가리켜 주세요."],
"Nod yes or shake your head no.": ["맞으면 손을 흔들고 아니면 저어 주세요.", "맞으면 고개를 끄덕이고 아니면 손을 흔들어 주세요."],
"The interpreter will help us understand each other.": ["목사님이 서로 이해하도록 도와줄 거예요.", "약사님이 서로 이해하도록 도와줄 거예요."],
# 경막외혈종 명료기 후 악화
"Your headache is suddenly much worse — we're acting now.": ["어지러움이 갑자기 훨씬 심해졌어요—지금 바로 대응하고 있어요.", "통증이 갑자기 훨씬 심해졌어요—지금 바로 대응하고 있어요."],
"Stay with me and keep talking to me.": ["정신 차리시고 계속 저와 눈 맞춰요.", "정신 차리시고 계속 저와 숨 쉬어요."],
"We're calling neurosurgery immediately.": ["지금 바로 영상의학과에 연락하고 있어요.", "지금 바로 정형외과에 연락하고 있어요."],
"You felt fine minutes ago — now tell me what changed.": ["몇 시간 전만 해도 괜찮으셨는데—지금 뭐가 달라졌는지 말씀해 주세요.", "몇 분 전만 해도 괜찮으셨는데—지금 누가 왔는지 말씀해 주세요."],
"This sudden change looks like bleeding building up fast.": ["이 갑작스러운 변화는 감염이 빠르게 번지는 것처럼 보여요.", "이 갑작스러운 변화는 부기가 빠르게 쌓이는 것처럼 보여요."],
"We need surgery fast to relieve the pressure on your brain.": ["뇌압을 재려면 빨리 수술이 필요해요.", "뇌압을 낮추려면 빨리 사진이 필요해요."],
# 뇌탈출 임박(동공 산대)
"One pupil is blown — this is an emergency.": ["한쪽 팔이 처졌어요—응급 상황이에요.", "양쪽 동공이 산대됐어요—응급 상황이에요."],
"We're hyperventilating and giving medication to reduce pressure.": ["과호흡시키면서 통증을 낮추는 약을 주고 있어요.", "산소를 주면서 압력을 낮추는 약을 주고 있어요."],
"Neurosurgery is coming for emergency decompression.": ["응급 감압을 위해 마취과가 오고 있어요.", "응급 감압을 위해 보호자가 오고 있어요."],
"His posturing means the pressure in his brain is rising fast.": ["이 자세이상은 열이 빠르게 오르고 있다는 뜻이에요.", "이 자세이상은 혈압이 빠르게 오르고 있다는 뜻이에요."],
"Check the other pupil now — compare both sides.": ["지금 다른 쪽 동공도 확인해서—양쪽을 기록해요.", "지금 다른 쪽 팔도 확인해서—양쪽을 비교해요."],
"Get neurosurgery on the phone right now.": ["지금 바로 영상의학과에 전화 연결해 주세요.", "지금 바로 약제과에 전화 연결해 주세요."],
# 두부외상 삽관·환기
"GCS is 6 — we need to secure the airway.": ["GCS가 6점이라—가족에게 연락해야 합니다.", "GCS가 6점이라—기록지를 확인해야 합니다."],
"Maintain oxygenation and avoid rises in pressure.": ["산소화를 유지하고 압력 상승은 기록합니다.", "산소화를 유지하고 체온 상승은 피합니다."],
"Target normal CO2 to protect the brain.": ["심장을 보호하려고 정상 CO2를 목표로 합니다.", "간을 보호하려고 정상 CO2를 목표로 합니다."],
"Prepping for intubation now.": ["지금 수술 준비 중입니다.", "지금 이송 준비 중입니다."],
"Airway takes priority — GCS is too low to protect it.": ["기도가 우선입니다—혈압이 너무 낮아서 스스로 보호가 안 됩니다.", "기도가 우선입니다—체온이 너무 낮아서 스스로 보호가 안 됩니다."],
"Keep sedation steady to avoid spikes in pressure.": ["체온이 튀지 않도록 진정 수준을 일정하게 유지합니다.", "혈당이 튀지 않도록 진정 수준을 일정하게 유지합니다."],
# 관통성 두부손상
"We're stabilizing the object and leaving it in place.": ["물체를 사진으로 남기고 그대로 둘게요.", "물체를 보고하고 그대로 둘게요."],
"Please keep your head as still as possible.": ["손을 최대한 가만히 유지해 주세요.", "다리를 최대한 가만히 유지해 주세요."],
"Neurosurgery is on the way for you.": ["영상의학과 선생님이 오고 계세요.", "보안팀 직원이 오고 계세요."],
"We will not remove it here — that could cause more bleeding.": ["여기서는 제거하지 않을 거예요—통증이 더 심해질 수 있거든요.", "여기서는 제거하지 않을 거예요—감염이 더 심해질 수 있거든요."],
"The trauma team is already talking with neurosurgery.": ["외상팀이 이미 영상의학과와 이야기하고 있어요.", "외상팀이 이미 소아과와 이야기하고 있어요."],
"Try not to touch or move near the object.": ["모니터 근처는 만지거나 움직이지 않도록 해 주세요.", "조명 근처는 만지거나 움직이지 않도록 해 주세요."],
# 두부외상 SBAR 인계
"GCS dropped from 14 to 10 over 30 minutes.": ["GCS가 이송 중 14에서 10으로 떨어졌습니다.", "GCS가 수술 중 14에서 10으로 떨어졌습니다."],
"Right pupil is now sluggish and dilated.": ["우측 동공이 지금 반응이 느리고 수축되어 있습니다.", "우측 동공이 지금 모양이 둥글고 산대되어 있습니다."],
"He's on apixaban; reversal is being considered.": ["아픽사반을 복용 중이고, 수술 일정을 고려 중입니다.", "아픽사반을 복용 중이고, 퇴원 일정을 고려 중입니다."],
"Left pupil remains brisk and reactive.": ["좌측 팔은 여전히 반응이 빠르고 정상입니다.", "좌측 동공은 여전히 색이 같고 정상입니다."],
"He takes apixaban daily for atrial fibrillation.": ["당뇨로 아픽사반을 매일 복용하고 있습니다.", "천식으로 아픽사반을 매일 복용하고 있습니다."],
"Neurosurgery is aware and reviewing the scan now.": ["신경외과에 알렸고 지금 차트를 검토 중입니다.", "신경외과에 알렸고 지금 메모를 검토 중입니다."],
# 외상성 발작 동반
"We're giving medication to stop the seizure now.": ["지금 발작을 멈추는 약을 설명하고 있어요.", "지금 발작을 멈추는 약을 기록하고 있어요."],
"Protecting the airway and giving oxygen.": ["기도를 보호하고 산소를 확인하고 있어요.", "기도를 보호하고 산소를 기록하고 있어요."],
"Watching closely for rising brain pressure.": ["눈 압력 상승이 있는지 유심히 지켜보고 있어요.", "가슴 압력 상승이 있는지 유심히 지켜보고 있어요."],
"The seizure has lasted almost two minutes now.": ["떨림이 거의 2분째 계속되고 있어요.", "오한이 거의 2분째 계속되고 있어요."],
"His GCS is dropping while he's still seizing.": ["발작이 계속되는 동안 맥박이 떨어지고 있어요.", "발작이 멈춘 뒤에도 GCS가 떨어지고 있어요."],
"We're managing the seizure and the airway at the same time.": ["발작과 출혈을 동시에 관리하고 있어요.", "발작과 통증을 동시에 관리하고 있어요."],
}
W = {
 "w-consciousness": {"distractorsEn": ["conscience", "conscientious"]},
 "w-miss": {"distractorsKo": ["(기억이) 섞이다", "(기억이) 되살아나다"]},
 "w-open": {"distractorsKo": ["(눈을) 감다", "깜빡이다"]},
 "w-stay": {"distractorsKo": ["떠나다·사라지다", "바뀌다·달라지다"]},
 "w-change": {"distractorsKo": ["유지(하다)", "회복(하다)"]},
 "w-slow": {"distractorsKo": ["멈추다·끝나다", "심해지다·늘어나다"]},
 "w-drowsy": {"distractorsKo": ["혼돈(헷갈리는 상태)", "불면(잠 못 드는 밤)"]},
 "w-bloodthinner": {"distractorsKo": ["혈압강하제", "진통소염제"]},
 "w-sleepiness": {"distractorsKo": ["(평소와 다른) 짜증", "(평소와 다른) 식욕"]},
 "w-concentrate": {"distractorsEn": ["consecrate", "contemplate"]},
 "w-harder": {"distractorsKo": ["(~하기) 쉬운", "(~하기) 조용한"]},
 "w-place": {"distractorsKo": ["바깥으로 (나가게)", "다른 곳에 (옮겨)"]},
 "w-sluggish": {"distractorsKo": ["(반응이) 고정된", "(반응이) 민첩한"]},
 "w-reversal": {"distractorsKo": ["(항응고) 중단", "(항응고) 증량"]},
 "w-nod": {"distractorsKo": ["(고개를) 젓다", "(손을) 흔들다"]},
}
B = {
 "Did you lose consciousness at all?": ["coordination", "concentration", "motivation"],
 "Is he acting differently than he usually does?": ["more politely", "more carefully", "more cheerfully"],
 "I'm calling the doctor right now to report this change.": ["manager", "chaplain", "driver"],
 "He takes apixaban daily for atrial fibrillation.": ["chronic kidney disease", "rheumatoid arthritis", "seasonal allergies"],
 "We're giving medication to stop the seizure now.": ["antibiotics", "vitamins", "painkillers"],
}
run(P, S, W, B)
