import sys; sys.path.insert(0,'/Users/ywyeom/private/forin/server/content/tools/wip/er-dk')
from dkcommon import apply
S={
"What exactly did you take, and do you have the bottle with you?":("정확히 언제 드셨고, 그 약병을 가지고 계신가요?","정확히 무엇을 드셨고, 그 영수증을 가지고 계신가요?"),
"About how many did you take, and how long ago?":("대략 몇 개를 샀고, 얼마나 전이었어요?","대략 몇 개를 드셨고, 어디서 드셨어요?"),
"Did you take anything else along with it?":("그것과 함께 다른 것도 사셨나요?","그것과 함께 물도 드셨나요?"),
"It's okay if you're not sure, just tell me what you remember.":("확실하지 않으셔도 괜찮아요, 기억나는 대로만 그려 주세요.","확실하지 않으셔도 괜찮아요, 보이는 대로만 말씀해 주세요."),
"You're not in any trouble, and I just want to keep you safe.":("곤란해지는 거 아니에요, 그냥 편하게 해드리고 싶은 거예요.","곤란해지는 거 아니에요, 그냥 안전하게 지켜보고 싶은 거예요."),
"Did you bring the pill bottle, or is it still at home?":("약병을 가져오셨나요, 아니면 아직 차에 있나요?","물병을 가져오셨나요, 아니면 아직 집에 있나요?"),
"This charcoal binds the medicine so your body absorbs less of it.":("이 활성탄이 음식과 결합해서 몸이 덜 흡수하게 해줘요.","이 활성탄이 약물과 결합해서 간이 덜 흡수하게 해줘요."),
"It's important to drink it now while it can still help.":("아직 따뜻할 때 지금 마시는 게 중요해요.","아직 도움이 될 수 있을 때 지금 먹는 게 중요해요."),
"Tell me right away if you feel like you might throw up.":("어지러울 것 같으면 바로 말씀해 주세요.","토할 것 같으면 바로 눌러 주세요."),
"I know this tastes bad, but it will help soak up the poison.":("냄새가 안 좋다는 거 알아요, 하지만 독을 빨아들이는 데 도움이 될 거예요.","맛이 안 좋다는 거 알아요, 하지만 열을 빨아들이는 데 도움이 될 거예요."),
"Drinking it through a straw can make it easier.":("컵으로 마시면 좀 더 쉬워질 수 있어요.","빨대로 마시면 좀 더 빨라질 수 있어요."),
"We'll watch you closely in case you can't keep it down.":("드신 걸 토하실 경우를 대비해 가족이 지켜볼게요.","드신 걸 흘리실 경우를 대비해 가까이서 지켜볼게요."),
"I need to ask — were you trying to hurt yourself?":("여쭤봐야 하는데요 — 스스로를 달래려고 약을 드셨나요?","여쭤봐야 하는데요 — 다른 분을 다치게 하려고 하셨나요?"),
"You're safe here, and I won't judge you for anything you tell me.":("여긴 조용해요, 무슨 말씀을 하셔도 판단하지 않을게요.","여긴 안전해요, 무슨 말씀을 하셔도 서두르지 않을게요."),
"Have you had thoughts like this before today?":("오늘 전에도 이런 약을 드신 적 있으세요?","오늘 아침에도 이런 생각을 하신 적 있으세요?"),
"It's okay to feel this way, and I'm glad you're here now.":("이런 기분이 드셔도 괜찮아요, 오늘 여기 와주셔서 다행이에요.","이런 기분이 드셔도 괜찮아요, 지금 가족이 와주셔서 다행이에요."),
"Right now, my only job is to keep you safe.":("지금 제 유일한 일은 당신을 안전하게 안내하는 거예요.","지금 제 유일한 일은 가족을 안전하게 지키는 거예요."),
"Is there anyone at home who might also be in danger?":("집에 위험할 수 있는 약이 남아 있나요?","직장에 위험할 수 있는 다른 분이 계신가요?"),
"Which products did you mix, and did you breathe in the fumes?":("어떤 제품들을 사셨고, 그 가스를 들이마셨나요?","어떤 용기들을 섞으셨고, 그 가스를 들이마셨나요?"),
"Did any of it get in your eyes or on your skin?":("코나 피부에 묻은 건 없나요?","눈이나 신발에 묻은 건 없나요?"),
"I'm calling Poison Control so we treat this exactly right.":("정확히 맞게 처치하도록 가족에게 전화할게요.","정확히 맞게 처치하도록 병원에 전화할게요."),
"How long ago did the mixing happen?":("섞으신 게 어디였나요?","마신 지 얼마나 됐나요?"),
"We'll flush your eyes and rinse your skin right away.":("바로 눈을 씻어내고 머리를 헹궈드릴게요.","바로 눈을 씻어내고 손을 헹궈드릴게요."),
"Are you having any trouble breathing right now?":("지금 삼키기 힘든 점이 있나요?","지금 걷기 힘든 점이 있나요?"),
"How many pills were in the bottle before, and how many are left now?":("이전에 서랍에 알약이 몇 개 있었고, 지금 몇 개 남았나요?","이전에 병에 알약이 몇 개 있었고, 지금 몇 개 줬나요?"),
"About what time did you find her?":("대략 몇 시에 출발하셨어요?","대략 어디서 발견하셨어요?"),
"You did the right thing bringing her in quickly.":("빨리 연락하신 건 정말 잘하신 거예요.","빨리 데려오신 건 정말 놀라운 일이에요."),
"Was she alone with the bottle before you found her?":("발견하시기 전에 아이 혼자 그 방에 있었나요?","발견하시기 전에 아이 형이 그 병과 있었나요?"),
"This happens to a lot of parents, and it's not your fault.":("많은 병원에서 일어나는 일이고, 보호자분 잘못이 아니에요.","많은 부모님들께 일어나는 일이고, 보호자분 설명이 필요해요."),
"We'll take good care of her now.":("이제 아이를 잘 안아드릴게요.","이제 부모님을 잘 돌봐드릴게요."),
"Feeling okay now is normal, but the danger can show up later.":("지금 졸린 건 정상이지만, 위험은 나중에 나타날 수 있어요.","지금 괜찮은 건 정상이지만, 위험은 밤에 나타날 수 있어요."),
"We'll check your acetaminophen level based on the exact time you took it.":("드신 정확한 양 기준으로 아세트아미노펜 수치를 확인할게요.","드신 정확한 시각 기준으로 아세트아미노펜 수치를 설명할게요."),
"This antidote called NAC protects your liver, and starting it early matters.":("NAC라는 이 해독제가 간을 보호해주고, 일찍 설명드리는 게 중요해요.","NAC라는 이 해독제가 간을 보호해주고, 시작은 의사가 정해요."),
"Even without symptoms, your liver can still be at risk.":("증상이 없어도 가족은 여전히 위험할 수 있어요.","증상이 없어도 간은 여전히 쉬어야 해요."),
"We'll start NAC now so your liver has the best chance.":("간이 가장 좋은 기회를 갖도록 지금 NAC를 설명할게요.","간이 가장 좋은 기회를 갖도록 지금 NAC를 가져올게요."),
"I'll explain each step so you know what's happening.":("어떤 상황인지 아시도록 단계마다 보여 드릴게요.","어떤 상황인지 아시도록 시간마다 설명해 드릴게요."),
"I'm giving him naloxone now to reverse the opioid.":("지금 카페인을 되돌리기 위해 날록손을 투여할게요.","지금 알코올을 되돌리기 위해 날록손을 투여할게요."),
"He may wake up but slip back, so we'll watch him closely.":("깨어났다가 다시 처질 수 있어서, 가족이 지켜볼게요.","깨어났다가 다시 먹을 수 있어서, 가까이서 지켜볼게요."),
"What did he take, and do you know how much?":("무엇을 샀고, 얼마나 드셨는지 아세요?","무엇을 드셨고, 어디서 드셨는지 아세요?"),
"Is he breathing on his own, or do you need to help him?":("스스로 숨을 쉬고 있나요, 아니면 눕혀드려야 하나요?","스스로 숨을 쉬고 있나요, 아니면 지켜봐야 하나요?"),
"His breathing should look better within a few minutes.":("몇 분 안에 맥박이 더 나아질 거예요.","몇 시간 안에 호흡이 더 나아질 거예요."),
"We're staying right here in case he needs naloxone again.":("다시 날록손이 필요할 경우를 대비해 가족과 여기 있을게요.","다시 날록손이 필요할 경우를 대비해 밤새 여기 있을게요."),
"I'm going to check how deeply she's sedated and protect her airway.":("얼마나 오래 진정됐는지 확인하고 기도를 보호할게요.","얼마나 깊이 숨 쉬는지 확인하고 기도를 보호할게요."),
"We're cautious with the reversal drug because it can trigger seizures.":("수액이 발작을 유발할 수 있어서 신중하게 쓰고 있어요.","역전제가 졸음을 유발할 수 있어서 신중하게 쓰고 있어요."),
"Has she taken any other pills or alcohol with this?":("다른 약이나 물도 함께 드셨나요?","다른 약이나 술을 어디서 드셨나요?"),
"Right now her airway is our top priority.":("지금은 가족 면담이 가장 우선이에요.","지금은 기도가 가장 어려워요."),
"We'll give the reversal drug slowly and watch closely for seizures.":("역전제를 천천히 투여하고 호흡을 가까이서 지켜볼게요.","역전제를 천천히 투여하고 발작을 가까이서 설명할게요."),
"Tell me if you notice any twitching or jerking.":("졸리거나 하품이 자꾸 나오면 말씀해 주세요.","씰룩거리거나 움찔거리는 게 보이면 눌러 주세요."),
"The ringing in your ears is a clue that the aspirin level is high.":("손 떨림은 아스피린 수치가 높다는 단서예요.","귀 울림은 소음 수치가 높다는 단서예요."),
"We'll give you fluids with bicarbonate to help clear it faster.":("더 빨리 씻어내도록 중탄산염이 든 수액을 설명해 드릴게요.","더 빨리 식히도록 중탄산염이 든 수액을 드릴게요."),
"How many aspirin did you take, and over how long?":("아스피린을 몇 알 드셨고, 얼마나 전에 드셨어요?","아스피린을 몇 알 드셨고, 어디서 드셨어요?"),
"Fast breathing can be a sign your body is trying to protect itself.":("빠른 호흡은 몸이 스스로를 식히려는 신호일 수 있어요.","빠른 맥박은 몸이 스스로를 보호하려는 신호일 수 있어요."),
"The bicarbonate helps your body clear the aspirin faster.":("중탄산염이 몸이 아스피린을 더 빨리 씻어내는지 볼게요.","중탄산염이 몸이 아스피린을 더 빨리 씻어내는 걸 설명해요."),
"We'll keep checking your breathing and blood levels closely.":("호흡과 혈액 수치를 계속 가까이서 설명할게요.","호흡과 소변 수치를 계속 가까이서 확인할게요."),
"We're watching your heart rhythm very closely right now.":("지금 혈당을 아주 가까이서 지켜보고 있어요.","지금 심장 리듬을 아주 가까이서 설명하고 있어요."),
"This bicarbonate helps protect your heart from the medication.":("이 중탄산염이 약물로부터 간을 보호하는 데 도와줘요.","이 중탄산염이 음식으로부터 심장을 보호하는 데 도와줘요."),
"Exactly which pills did you take, and when?":("정확히 어떤 약을 사셨고, 언제였나요?","정확히 어떤 약을 드셨고, 어디서였나요?"),
"Your heart's electrical signal can change quickly with this overdose.":("이 과다복용으로 심장의 소리가 빠르게 바뀔 수 있어요.","이 과다복용으로 위장의 전기 신호가 빠르게 바뀔 수 있어요."),
"We're ready to act fast if your heart rhythm changes.":("혈압이 바뀌면 바로 빠르게 대응할 준비가 돼 있어요.","심장 리듬이 바뀌면 바로 가족께 연락할 준비가 돼 있어요."),
"Stay still for me while we watch the monitor.":("의사가 모니터를 보는 동안 가만히 계세요.","제가 모니터를 보는 동안 누워 계세요."),
"We'll check your INR to see how thin your blood is right now.":("지금 혈액이 얼마나 묽은지 INR로 설명할게요.","지금 소변이 얼마나 묽은지 INR로 확인할게요."),
"There's a reversal medicine we can give if the bleeding gets worse.":("통증이 더 심해지면 드릴 수 있는 역전제가 있어요.","출혈이 더 심해지면 드릴 수 있는 설명서가 있어요."),
"Are you seeing any blood in your urine or stool, or bruising anywhere?":("소변이나 대변에 피가 보이거나, 어디 아픈 곳이 있나요?","소변이나 대변에 피가 보이거나, 어디 가려운 곳이 있나요?"),
"How many extra pills did you take by mistake?":("어제 얼마나 더 많은 약을 드셨나요?","실수로 얼마나 더 많은 물을 드셨나요?"),
"We're watching closely for any new bruising or bleeding.":("새로운 멍이나 출혈이 없는지 가족과 함께 지켜보고 있어요.","새로운 멍이나 출혈이 없는지 가까이서 설명하고 있어요."),
"If bleeding gets worse, we're ready to give the reversal medicine right away.":("출혈이 심해지면 바로 역전제를 설명할 준비가 돼 있어요.","통증이 심해지면 바로 역전제를 드릴 준비가 돼 있어요."),
"I hear how much pain you're in, and I'm staying right here with you.":("얼마나 힘드신지 느껴져요, 지금 가족과 여기 있을게요.","얼마나 힘드신지 느껴져요, 지금 밤새 여기 있을게요."),
"Can you tell me each thing you took so we can keep you safe?":("안전하게 해드릴 수 있도록 사신 것 하나하나 말씀해 주시겠어요?","편하게 해드릴 수 있도록 드신 것 하나하나 말씀해 주시겠어요?"),
"A counselor will come see you, and someone will stay with you the whole time.":("의사가 오셔서 뵐 거고, 누군가 계속 함께 있어드릴 거예요.","상담사가 오셔서 뵐 거고, 가족이 계속 함께 있어드릴 거예요."),
"I know this feels like too much right now.":("지금 너무 외롭게 느껴지신다는 거 알아요.","어제 너무 벅차게 느껴지셨다는 거 알아요."),
"You're not alone, and we're going to help you through this.":("혼자가 아니고, 이 밤을 함께 헤쳐나가도록 도와드릴게요.","혼자가 아니고, 이 일을 함께 헤쳐나가도록 가족에게 연락할게요."),
"Someone will be with you every step of the way.":("매 순간 의사가 함께 있어드릴 거예요.","매 순간 가족이 함께 있어드릴 거예요."),
"Alcohol and those pills together can slow your breathing, so we'll watch you closely.":("술과 그 약이 함께 있으면 심박이 느려질 수 있어서, 가까이서 지켜볼게요.","술과 그 약이 함께 있으면 호흡이 느려질 수 있어서, 가족이 지켜볼게요."),
"How much did you drink, and how many pills did you take?":("얼마나 사셨고, 약은 몇 개 드셨어요?","얼마나 드셨고, 약은 어디서 드셨어요?"),
"Stay with me — I'll keep checking on you every few minutes.":("정신 놓지 마세요 — 몇 분마다 계속 설명할게요.","눈 감지 마세요 — 몇 분마다 계속 확인할게요."),
"Mixing alcohol with sedatives can make you stop breathing without warning.":("술과 비타민을 함께 쓰면 경고 없이 숨이 멈출 수 있어요.","커피와 진정제를 함께 쓰면 경고 없이 숨이 멈출 수 있어요."),
"I'll check your oxygen and alertness every few minutes.":("혈당과 각성 상태를 몇 분마다 확인할게요.","산소와 식사량을 몇 분마다 확인할게요."),
"Try to stay awake and talk with me for now.":("지금은 깨어 있으면서 가족과 이야기해 보세요.","지금은 일어나 앉아서 저와 이야기해 보세요."),
"A regular oxygen reading can look normal even with carbon monoxide, so we use a special test.":("산소 수치는 일산화탄소 중독에서도 정상으로 보일 수 있어서, 특별한 팀을 불러요.","체온 수치는 일산화탄소 중독에서도 정상으로 보일 수 있어서, 특별한 검사를 써요."),
"I'm putting you on high-flow oxygen to clear it from your blood.":("혈액에서 씻어내도록 고유량 산소를 설명해 드릴게요.","폐에서 씻어내도록 고유량 산소를 드릴게요."),
"Was anyone else in the house feeling sick too?":("집에 다른 분도 계셨나요?","차에 다른 분도 아프셨나요?"),
"Headaches in the whole family can be a big clue for carbon monoxide.":("가족 전체의 기침은 일산화탄소 중독의 큰 단서가 될 수 있어요.","가족 전체의 두통은 일산화탄소 중독의 큰 원인이 될 수 있어요."),
"Your oxygen number can look fine even when carbon monoxide is high.":("일산화탄소가 높아도 체온 수치는 괜찮아 보일 수 있어요.","일산화탄소가 높아도 산소 수치는 괜찮아 보이는지 볼게요."),
"We'll keep you on oxygen until your levels are safe.":("수치가 안전해질 때까지 산소를 계속 챙길게요.","수치가 안전해질 때까지 산소를 계속 설명할게요."),
"I'm not here to get you in trouble — I just want to keep you safe.":("곤란하게 하려는 게 아니라, 그냥 편하게 해드리고 싶은 거예요.","화나게 하려는 게 아니라, 그냥 안전하게 해드리고 싶은 거예요."),
"Some of your signs tell me your body reacted to something. Can we talk about it?":("몇 가지 징후를 보면 몸이 뭔가에 반응한 것 같아요. 그것에 대해 설명해 볼까요?","몇 가지 징후를 보면 몸이 뭔가에 놀란 것 같아요. 그것에 대해 이야기해 볼까요?"),
"Whatever you tell me stays between us and your care team.":("무슨 말씀을 하셔도 저와 가족 사이에만 남아요.","무슨 말씀을 하셔도 저와 간호팀 사이에만 남아요."),
"I can see some things that don't add up, and that's okay.":("앞뒤가 안 맞는 부분이 좀 들리는데, 그래도 괜찮아요.","앞뒤가 안 맞는 부분이 좀 보이는데, 그래도 설명해 주세요."),
"You won't get in trouble here, no matter what you tell me.":("무슨 말씀을 하셔도 밖에서 곤란해지지 않아요.","무슨 말씀을 하셔도 여기서 서두르지 않아요."),
"Your care team just wants to understand what happened to you.":("가족은 그저 무슨 일이 있었는지 이해하고 싶은 거예요.","의료팀은 그저 언제 일이 있었는지 이해하고 싶은 거예요."),
"Pupils are pinpoint and respirations are eight — this looks like a toxidrome.":("동공이 점같이 작고 호흡수는 8회예요 — 중독센터에 전화할게요.","동공이 점같이 작고 호흡수는 8회예요 — 보호자께 연락할게요."),
"I need airway support and naloxone at the bedside now.":("기도 지지와 날록손을 입구 곁에 지금 준비해 주세요.","기도 지지와 날록손을 침상 곁에 지금 설명해 주세요."),
"Unknown ingestion, GCS 6, protecting the airway — can you take report?":("미상 섭취, GCS 6, 기도 보호 중입니다 — 의사 불러 주실 수 있나요?","미상 섭취, GCS 6, 수액 거는 중입니다 — 인계 받으실 수 있나요?"),
"Airway first, then we treat the cause.":("기도가 먼저고, 그다음 원인을 설명해요.","기도가 먼저고, 그다음 원인을 정리해요."),
"Vitals are stable for now, but I'm watching closely.":("혈액검사는 지금은 안정적이지만 가까이서 지켜보고 있어요.","활력징후는 지금은 안정적이지만 가까이서 설명하고 있어요."),
"Can you take report while I stay with the airway?":("제가 기도를 맡고 있는 동안 약 챙겨 주실 수 있나요?","제가 모니터를 맡고 있는 동안 인계 받으실 수 있나요?"),
"These signs — drooling, sweating, tearing — point to organophosphate poisoning.":("이 징후들 — 기침, 땀, 눈물 — 은 유기인계 중독을 가리켜요.","이 징후들 — 침 흘림, 열, 눈물 — 은 유기인계 중독을 가리켜요."),
"We're giving atropine to dry up his secretions and protect his breathing.":("분비물을 말리고 호흡을 보호하도록 아트로핀을 설명할게요.","분비물을 말리고 체온을 보호하도록 아트로핀을 드릴게요."),
"We need to remove his clothes and wash his skin to stop more from absorbing.":("더 흡수되지 않도록 옷을 벗기고 침대를 씻어야 해요.","더 흡수되지 않도록 신발을 벗기고 피부를 씻어야 해요."),
"How long was he exposed to the pesticide?":("살충제에 어디서 노출됐나요?","살균제에 얼마나 오래 노출됐나요?"),
"Atropine will help dry up the extra fluid in his lungs.":("아트로핀이 눈의 여분 체액을 말리는 데 도와줄 거예요.","아트로핀이 폐의 여분 체액을 설명하는 데 도와줄 거예요."),
"We'll keep giving atropine until his secretions dry up.":("분비물이 마를 때까지 아트로핀을 계속 설명할게요.","분비물이 마를 때까지 아트로핀을 계속 챙길게요."),
"The twitching and high fever suggest your medications are interacting.":("씰룩거림과 기침은 약물이 서로 상호작용하고 있다는 걸 시사해요.","씰룩거림과 고열은 음식이 서로 상호작용하고 있다는 걸 시사해요."),
"We're stopping the trigger and cooling you down right away.":("유발 원인을 멈추고 바로 몸을 닦아드릴게요.","유발 원인을 찾고 바로 몸을 식혀드릴게요."),
"Which new medication or supplement did you start this week?":("이번 달에 새로 시작한 약이나 보충제가 있나요?","이번 주에 새로 시작한 운동이나 보충제가 있나요?"),
"Your muscles are stiff and your body temperature is very high.":("근육이 뻣뻣하고 맥박이 아주 높아요.","관절이 뻣뻣하고 체온이 아주 높아요."),
"We're cooling you and giving medication to calm your body down.":("열을 식히고, 몸을 진정시키도록 물을 드릴게요.","열을 식히고, 몸을 진정시키도록 약을 설명할게요."),
"We'll stop every medication that could be the trigger.":("유발 원인이 될 수 있는 약물은 전부 설명할게요.","유발 원인이 될 수 있는 약물은 전부 모아둘게요."),
"Trouble seeing after drinking that can mean methanol poisoning.":("그걸 마신 뒤 귀가 울리는 건 메탄올 중독을 의미할 수 있어요.","그걸 마신 뒤 시야가 흐려지는 건 탈수를 의미할 수 있어요."),
"There's an antidote we're giving now, and you may need urgent dialysis.":("지금 드리고 있는 해독제가 있고, 긴급 투석을 설명해 드릴게요.","지금 설명하고 있는 해독제가 있고, 긴급 투석이 필요할 수도 있어요."),
"How much did you drink, and about how long ago?":("얼마나 사셨고, 대략 얼마나 전이었어요?","얼마나 드셨고, 대략 어디서 드셨어요?"),
"We'll check your eyes and how well you can see right now.":("지금 눈과 시력이 어떤지 설명할게요.","어제 눈과 시력이 어땠는지 확인할게요."),
"The antidote works quickly, but dialysis may still be urgent.":("해독제가 빠르게 작용하지만, 투석을 여전히 설명해 드릴게요.","해독제가 빠르게 작용하지만, 투석이 여전히 오래 걸릴 수 있어요."),
"We're moving fast because your vision and your blood's acid level are both at risk.":("시력과 혈액의 당 수치가 둘 다 위험해서 빠르게 움직이고 있어요.","청력과 혈액의 산성도가 둘 다 위험해서 빠르게 움직이고 있어요."),
"Your rhythm is unstable, so we're preparing everything to support you.":("리듬이 불안정해서, 설명할 수 있도록 모든 걸 준비하고 있어요.","혈압이 불안정해서, 지원할 수 있도록 모든 걸 준비하고 있어요."),
"Stay with me and tell me right away if it gets worse.":("눈 감지 마시고, 더 나빠지면 바로 말씀해 주세요.","정신 놓지 마시고, 더 나빠지면 바로 눌러 주세요."),
"Overdose with widening QRS and bradycardia — I need the crash cart and a physician now.":("과다복용에 QRS 확대와 서맥이 있습니다 — 지금 크래시카트와 팀장이 필요해요.","과다복용에 QRS 확대와 서맥이 있습니다 — 지금 크래시카트와 보안요원이 필요해요."),
"I'm watching for any new widening or slowing in his rhythm.":("리듬에 새로운 확대나 빨라짐이 있는지 지켜보고 있어요.","리듬에 새로운 확대나 느려짐이 있는지 설명하고 있어요."),
"Tell me right away if you feel your heart racing or skipping.":("심장이 빨리 뛰거나 건너뛰는 느낌이 들면 바로 눌러 주세요.","심장이 빨리 뛰거나 건너뛰는 느낌이 들면 바로 가족께 말씀해 주세요."),
"The team is ready with everything we might need.":("팀은 필요할 수 있는 모든 걸 설명하고 있어요.","가족은 필요할 수 있는 모든 걸 준비하고 있어요."),
"Ingestion was tricyclics about ninety minutes ago per the family.":("구급대원에 따르면 약 90분 전에 삼환계 약물을 섭취했습니다.","가족에 따르면 약 90분 전에 삼환계 약물을 발견했습니다."),
"He was talking at pickup but became hypotensive and drowsy en route.":("인수 시점엔 말도 했는데, 이송 중 빈맥에 졸린 상태가 됐습니다.","인수 시점엔 걷기도 했는데, 이송 중 저혈압에 졸린 상태가 됐습니다."),
"Last pressure was eighty over forty, and I gave a bicarb bolus.":("마지막 혈압은 80에 40이었고, 중탄산제 볼루스를 준비했습니다.","마지막 혈압은 80에 40이었고, 중탄산제 볼루스를 요청했습니다."),
"GCS dropped from fifteen to nine during transport.":("이송 전 GCS가 15에서 9로 떨어졌습니다.","이송 중 GCS가 15에서 9로 재측정됐습니다."),
"I'm protecting his airway and watching his pressure closely.":("기도를 보호하고 혈당을 가까이서 지켜보고 있습니다.","기도를 보호하고 동공을 가까이서 지켜보고 있습니다."),
"Can you take over airway and pressure while I give report?":("제가 인계하는 동안 기도와 혈당을 맡아주실 수 있나요?","제가 인계하는 동안 기도와 서류를 맡아주실 수 있나요?"),
}
W={'w-aspirin':(None,['ibuprofen','aspartame']),'w-carbon':(None,['carbon dioxide','nitrogen oxide']),'w-organophosphate':(None,['organochlorine','organosulfate']),
'w-temperature':(None,['temperament','temperate']),'w-hypotensive':(None,['hypertensive','hypothermic'])}
B={"The bicarbonate helps your body clear the aspirin faster.":('bicarbonate',['potassium','adrenaline','antibiotic']),
"We'll keep checking your breathing and blood levels closely.":('breathing',['appetite','mattress','schedule'])}
apply('er-poisoning',S,W,B)
