from dkfix_er5lib import run
run('ortho-trauma',{
"Come back if your fingers turn pale":("손가락이 차가워지거나 저리거나 많이 아프면 다시 오세요.","손가락이 창백해지거나 붓거나 많이 아프면 다시 오세요."),
"We're keeping the finger cool and moist":("손가락을 이송하기 위해 시원하고 촉촉하게 보관하고 있어요.","손가락을 보호하기 위해 시원하고 촉촉하게 보관해 주세요."),
"Keep the ankle raised above your heart":("잘 때는 발목을 심장보다 높게 들어올려 두세요.","쉴 때는 발목을 심장 높이까지 들어올려 두세요."),
"We'll check your toes for color and warmth":(None,"30분마다 발가락 색과 온기를 확인할게요."),
"Wrap it with a bandage":(None,"붕대로 감싸시되 너무 오래 두지는 마세요."),
"You'll get antibiotics to prevent infection":(None,"감염을 예방하기 위해 파상풍 주사도 맞으실 거예요."),
"Once it's safe, we'll slowly release":("안전해지면 천천히 지혈대를 풀면서 혈압을 지켜볼게요.","안전해지면 천천히 지혈대를 풀면서 통증을 지켜볼게요."),
"Your arm looks a little deformed":("반대쪽과 비교하면 팔이 조금 부어 보여요.",None),
"On a scale of zero to ten":("0에서 10까지 중에 붓기가 얼마나 심하세요?",None),
"We'll cover the wound with a sterile dressing":("바로 멸균 식염수로 상처를 적실게요.","바로 멸균 장갑을 끼고 상처를 볼게요."),
"Your foot feels cold":("발이 차갑고 색깔도 얼룩덜룩해 보여요.",None),
"After we reset it":("다시 맞춘 뒤에 사진으로 위치를 다시 확인할게요.","다시 맞춘 뒤에 팔걸이를 하고 다시 확인할게요."),
"Once you're sleepy":(None,"졸리게 되면 다시 맞추는 것을 보지 못하실 거예요."),
"We're calling the hand surgeon":("이송을 준비하려고 지금 구급차에 전화하고 있어요.","이송을 준비하려고 지금 손 외과의에게 사진을 보내고 있어요."),
# own pass
"Keep this leg raised and try not to put weight":("병원에서도 이 다리를 들어올리고 체중을 싣지 않도록 하세요.","회사에서도 이 다리를 들어올리고 체중을 싣지 않도록 하세요."),
"Use ice for twenty minutes":(None,"한 번에 20분씩 하루에 몇 번 얼음찜질을 해 드릴게요."),
"We can see the bone":(None,"뼈가 보여서 상처를 잘 덮어야 해요."),
"Never push anything inside the cast":("닦으려고 깁스 안에 아무것도 넣지 마세요.","긁으려고 부목 안에 아무것도 넣지 마세요."),
"Keep the cast covered and dry":("운동할 때는 깁스를 덮어서 마르게 유지하세요.",None),
"We're placing a binder":(None,"골반을 고정하고 출혈을 늦추기 위해 바인더를 준비할게요."),
"We're giving you fluids and blood to keep":("혈압을 유지하기 위해 수액과 혈소판을 드리고 있어요.","혈압을 유지하기 위해 수액과 혈액을 가져오고 있어요."),
"We're watching your oxygen closely":(None,"이런 골절 후에는 산소 수치를 자세히 알려드려요."),
"Your pressure is low, so we're starting a transfusion":("혈압이 낮아서 산소를 시작하고 있어요.","혈압이 낮아서 수혈을 준비하고 있어요."),
"We're giving you blood quickly":("피를 많이 잃고 계셔서 빠르게 의사를 부르고 있어요.",None),
"We're going to realign it":(None,"혈류를 되살리기 위해 뼈를 재정렬할 준비를 할 거예요."),
"We'll numb the area":(None,"부위를 마취하고 빨리 의사를 부를게요."),
"We need surgery soon":(None,"압박을 풀기 위해 곧 마취가 필요해요."),
"We'll control your bleeding":("이송을 준비하는 동안 출혈을 조절해 보세요.",None),
})
