from dkfix_er5lib import run
run('head-trauma',{
"Come back if you have worsening headache":("두통이나 구토가 심해지면 구급차를 부르세요.","두통이나 어지럼이 심해지면 다시 오세요."),
"Watch for confusion, drowsiness":("혼돈, 구토, 무력감이 있는지 지켜봐 주세요.","어지럼, 졸림, 무력감이 있는지 지켜봐 주세요."),
"If the headache gets much worse":("두통이 훨씬 심해지면 바로 가까운 병원에 가세요.","구토가 훨씬 심해지면 바로 다시 오세요."),
"Any seizure or trouble waking up":("발작이 있거나 잘 깨어나지 못하면 119를 불러야 해요.","발작이 있거나 말이 어눌해지면 다시 와야 해요."),
"Wake him every few hours":(None,"몇 시간마다 깨워서 정상적으로 숨쉬는지 확인해 주세요."),
"Let me know right away if it gets worse":(None,"더 어지러우면 바로 알려주세요."),
"Call us right away if he throws up":("토하거나 열이 나면 바로 저희를 불러 주세요.","토하거나 많이 보채면 바로 저희를 불러 주세요."),
"Right pupil is now sluggish":("우측 동공이 지금 반응이 느리고 모양이 찌그러져 있습니다.",None),
"I ask the same questions again because":("같은 질문을 반복하는 건 잘 들리는지 알 수 있어서예요.",None),
"I'm calling the doctor right now":(None,"지금 바로 책임간호사에게 전화해서 이 변화를 보고할게요."),
"Nod yes or shake your head no":("맞으면 손을 들고 아니면 고개를 저어 주세요.",None),
"Stay with me and keep talking to me":(None,"정신 차리시고 계속 제 손을 잡아요."),
"Neurosurgery is coming for emergency":(None,"응급 감압을 위해 외상팀이 오고 있어요."),
"GCS is 6":(None,"GCS가 6점이라—신경외과를 불러야 합니다."),
"He's on apixaban; reversal":(None,"아픽사반을 복용 중이고, 중환자실 입원을 고려 중입니다."),
"He takes apixaban daily":("심부정맥혈전으로 아픽사반을 매일 복용하고 있습니다.","폐색전증으로 아픽사반을 매일 복용하고 있습니다."),
# own pass
"I'm going to recheck this in a few minutes":("몇 분 뒤에 의사가 다시 확인할 거예요.","몇 분 뒤에 이걸 다시 물어볼게요."),
"Have someone stay with you tonight":(None,"오늘 밤은 누군가와 함께 병원에 계세요."),
"We recommend a CT scan to be safe":("급하게 CT 스캔을 권해 드려요.","안전하게 CT 스캔을 설명해 드려요."),
"We'll get a CT scan to check for bleeding in his brain":("뇌 안 출혈을 확인하려고 MRI 스캔을 할게요.","뇌 안 출혈을 확인하려고 CT 동의를 받을게요."),
"We'll examine him carefully":("확실히 하기 위해 의사가 꼼꼼하게 진찰할게요.","확실히 하기 위해 꼼꼼하게 설명해 드릴게요."),
"We'll keep checking on you until you're clearly sober":(None,"확실히 술이 깨고 안정될 때까지 계속 확인해 주세요."),
"This could mean rising pressure":(None,"압력이 오르고 있다는 뜻일 수 있어서—지금 의사가 다시 확인하고 있어요."),
"Check the other pupil now":("지금 다른 쪽 동공도 확인해서—전후를 비교해요.","지금 다른 쪽 동공도 확인해서—결과를 보고해요."),
"Maintain oxygenation and avoid rises":("산소화를 유지하고 소음 증가는 피합니다.",None),
"We're stabilizing the object":("물체를 고정하고 그대로 두세요.","물체를 가리고 그대로 둘게요."),
"We're giving medication to stop the seizure":("지금 발작을 멈추는 약을 준비하고 있어요.","지금 발작을 멈추는 약을 가지러 가고 있어요."),
"Protecting the airway and giving oxygen":("기도를 보호하고 수액을 주고 있어요.","기도를 확인하고 산소를 주고 있어요."),
"Please keep your head as still":("머리를 최대한 낮게 유지해 주세요.","머리를 최대한 편하게 유지해 주세요."),
})
