/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a cleared scenario (awards XP, advances streak) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description scenario clear */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.attemptReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_domain_progress.Progress"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/dev": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dev login (no provider). Registered only in dev or where DEV_AUTH_SECRET is set. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_adapters_http.loginResp"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout (revoke refresh tokens) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate refresh token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description refresh token */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.refreshReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_domain_auth.TokenPair"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/social": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Social login (Apple/Google/Kakao) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description provider + ID token */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["internal_adapters_http.socialLoginReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_adapters_http.loginResp"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Today's situation board — a daily-rotated set of scenario cards */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/economy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Economy config (single source of truth mirrored to the client) + pronunciation feature flag */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_adapters_http.economyConfigResp"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/content/manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Content manifest (version) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/{sessionId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade the finished conversation, award scaled XP, return the result */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/{sessionId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Throw a conversation away so it is not offered for resuming */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_adapters_http.discardResp"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/{sessionId}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a message; NPC replies in persona (LLM) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description user message */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.messageReq"];
                };
            };
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/{sessionId}/speech.wav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Speak the latest NPC line of a conversation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "audio/wav": Record<string, never>;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversation/{sessionId}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a message; NPC reply streamed as Server-Sent Events (LLM) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description user message */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.messageReq"];
                };
            };
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** AI-correct an English utterance (creates a review card) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description utterance to correct */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.correctReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_domain_conversation.Correction"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List departments (optionally ?profession=nurse) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events (optionally ?profession=nurse) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interiors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a department interior (tile map: regions/rooms/objects/hotspots) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invite/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview the person behind an invite code */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user + profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_adapters_http.meResp"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/access/{interiorId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the learner may enter in one interior */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["internal_adapters_http.gate"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity calendar — per-day sessions with the shift band they fell in */
        get: {
            parameters: {
                query?: {
                    /** @description YYYY-MM (defaults to the current month in tz) */
                    month?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["github_com_bingoring_forin_server_internal_domain_progress.CalendarDay"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/cheers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cheer inbox (marks them read) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/colleague-prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read or update colleague sharing preferences */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/colleague-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending colleague requests addressed to me */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/colleague-requests/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a colleague request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/colleague-requests/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decline a colleague request */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/colleagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My colleagues */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        /** Redeem an invite code (creates a request, or links when mutual) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/colleagues/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One colleague's profile (404 unless linked) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        /** Remove a colleague */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/colleagues/{id}/cheers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a cheer to a colleague */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/curriculum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Building/floor/curriculum path with per-user progress */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["github_com_bingoring_forin_server_internal_curriculum.BuildingGroup"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/daily-board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personalized daily pool — weighted, persisted, resets 00:00 local (?tz=) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/daily-board/topup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rewarded-ad top-up of today's daily pool (+N, up to a daily cap) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home tab (one round trip) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_adapters_http.homeResp"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/invite-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** My invite code (mints one when absent; ?rotate=1 issues a fresh one) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Discovered hidden missions */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/missions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a hidden-mission discovery (permanent, idempotent) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string[];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Save onboarding profile (marks the user onboarded) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description onboarding selections */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.updateProfileReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_domain_user.Profile"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user's growth */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_domain_progress.Progress"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review cards due today */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/review/{id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade a review card (SM-2 spaced repetition) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description grade: again|hard|good|easy */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.gradeReq"];
                };
            };
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/route": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Main-route curriculum path (events + unlock states) for the user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/situations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Situation cards — one department (?dept=ER) or a title search (?q=) */
        get: {
            parameters: {
                query?: {
                    /** @description Department code; ignored when q is present */
                    dept?: string;
                    /** @description Title search across every department */
                    q?: string;
                    /** @description Page offset (dept listing only) */
                    offset?: number;
                    /** @description Page size, 1-50 (default 20) */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: components["schemas"]["github_com_bingoring_forin_server_internal_domain_content.DeptSituation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Growth-report aggregates (scenarios, cards, conversation time, attendance) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_domain_progress.GrowthStats"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Equip a career title */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description title id (” to un-equip) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.titleReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_domain_user.Profile"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/me/ui-lang": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set the app's display language */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description locale code, or \ */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.uiLangReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_domain_user.Profile"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/pronunciation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assess pronunciation of recorded audio vs a reference phrase (Azure), and persist the attempt */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description base64 WAV (16kHz mono PCM) + reference text + optional origin/scenarioId/reviewCardId */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.pronounceReq"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_adapters_http.pronounceResp"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a quiz (playable content) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{id}/audio-meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Waveform + duration for a listen quiz's dictation audio */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{id}/audio.wav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synthesized dictation audio for a listen quiz (WAV) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a scenario (dialogue/quiz/effect steps) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scenarios/{id}/conversation/last": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Previous conversation for a scenario, if any */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["internal_adapters_http.resumableResp"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speech/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent attempt history for a sentence, oldest first (business-rules R3: screen renders the last 3) */
        get: {
            parameters: {
                query: {
                    /** @description sentence text — the server derives sentenceKey from text+locale (business-rules §2); clients cannot compute or send it directly */
                    text: string;
                    /** @description max attempts to return, default 3 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_ports.SpeechAttemptRow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speech/reference": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Canonical syllable/phoneme reference for a sentence (TTS-derived, cached globally per business-rules R9) */
        get: {
            parameters: {
                query: {
                    /** @description sentence text to derive the reference for */
                    text: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["github_com_bingoring_forin_server_internal_ports.SentenceReferenceRow"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/speech/reference/audio.wav": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Synthesized reference audio for a sentence (WAV) — the same TTS render GET /speech/reference derives its IPA from */
        get: {
            parameters: {
                query: {
                    /** @description sentence text — same text passed to GET /speech/reference */
                    text: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: never;
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transcribe recorded audio to text (dictation, Azure STT) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description base64 WAV (16kHz mono PCM) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["internal_adapters_http.sttReq"];
                };
            };
            responses: never;
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "github_com_bingoring_forin_server_internal_curriculum.BuildingGroup": {
            building?: string;
            floors?: components["schemas"]["github_com_bingoring_forin_server_internal_curriculum.FloorGroup"][];
        };
        "github_com_bingoring_forin_server_internal_curriculum.CurriculumState": {
            building?: string;
            done?: number;
            floor?: string;
            key?: string;
            name?: string;
            /** @description name of the current (now) step */
            next?: string;
            resume?: boolean;
            /** @description done | doing | todo */
            state?: string;
            steps?: components["schemas"]["github_com_bingoring_forin_server_internal_curriculum.StepState"][];
            total?: number;
            where?: string;
        };
        "github_com_bingoring_forin_server_internal_curriculum.FloorGroup": {
            curricula?: components["schemas"]["github_com_bingoring_forin_server_internal_curriculum.CurriculumState"][];
            floor?: string;
            where?: string;
        };
        "github_com_bingoring_forin_server_internal_curriculum.StepState": {
            kind?: string;
            name?: string;
            /** @description bonus practice; doesn't gate */
            optional?: boolean;
            scenarioId?: string;
            /** @description done | now | lock | optional */
            state?: string;
        };
        "github_com_bingoring_forin_server_internal_domain_auth.TokenPair": {
            accessToken?: string;
            /** @description access token seconds-to-live */
            expiresIn?: number;
            refreshToken?: string;
        };
        /** @enum {string} */
        "github_com_bingoring_forin_server_internal_domain_colleague.Relation": "peer" | "mentor" | "mentee";
        "github_com_bingoring_forin_server_internal_domain_content.DeptSituation": {
            lv?: string;
            min?: number;
            name?: string;
            room?: string;
            scenarioId?: string;
            tag?: string;
            /**
             * @description TagCode is the STATE ("cleared" | "urgent" | "new"); Tag is its label in the
             *     request's language. They were one Korean field, which forced the client to
             *     compare against "완료" — so the string could never be translated without
             *     breaking the comparison that decided which situations count as done.
             */
            tagCode?: string;
            /** @description high difficulty */
            urgent?: boolean;
        };
        "github_com_bingoring_forin_server_internal_domain_conversation.Correction": {
            cardId?: string;
            corrected?: string;
            note?: string;
            original?: string;
        };
        "github_com_bingoring_forin_server_internal_domain_home.MentorNote": {
            id?: string;
            npc?: {
                dept?: string;
                name?: string;
                role?: string;
            };
            text?: string;
        };
        "github_com_bingoring_forin_server_internal_domain_home.Phrase": {
            en?: string;
            id?: string;
            ko?: string;
            note?: string;
        };
        "github_com_bingoring_forin_server_internal_domain_home.Shift": {
            deptLabel?: string;
            /** @description DAY | EVENING */
            shift?: string;
        };
        /**
         * @description Band is the day's dominant band — where most of the work happened. A day split
         *     across two bands reports the busier one rather than both: the calendar cell has
         *     room for one mark, and the entries below it carry the detail.
         * @enum {string}
         */
        "github_com_bingoring_forin_server_internal_domain_progress.Band": "day" | "evening" | "night";
        "github_com_bingoring_forin_server_internal_domain_progress.CalendarDay": {
            band?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_progress.Band"];
            cleared?: number;
            /** @description YYYY-MM-DD in the caller's timezone */
            date?: string;
            entries?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_progress.CalendarEntry"][];
            sessions?: number;
        };
        "github_com_bingoring_forin_server_internal_domain_progress.CalendarEntry": {
            cleared?: boolean;
            /** @description local hour it started, 0-23 */
            hour?: number;
            scenarioId?: string;
            title?: string;
        };
        "github_com_bingoring_forin_server_internal_domain_progress.GrowthStats": {
            /** @description yyyy-mm-dd (tz), the StreakWindowDays ending today */
            activeDates?: string[];
            conversationSecondsToday?: number;
            conversationSecondsWeek?: number;
            newCardsToday?: number;
            newCardsWeek?: number;
            scenariosToday?: number;
            /** @description lifetime clears → praise stickers (1 each) */
            scenariosTotal?: number;
            scenariosWeek?: number;
        };
        "github_com_bingoring_forin_server_internal_domain_progress.Progress": {
            level?: number;
            rank?: string;
            /**
             * @description Reputation is ordered for display and carries its own labels, so the client
             *     renders whatever the profession defines without knowing any of the names.
             */
            reputation?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_progress.Standing"][];
            streakCurrent?: number;
            streakLongest?: number;
            xp?: number;
        };
        "github_com_bingoring_forin_server_internal_domain_progress.Standing": {
            key?: string;
            label?: string;
            value?: number;
        };
        "github_com_bingoring_forin_server_internal_domain_user.Profile": {
            /** @description e.g. "us" */
            destination?: string;
            /** @description equipped career title id (may be empty) */
            equippedTitle?: string;
            /** @description MVP: "nurse" */
            job?: string;
            /** @description user's language, e.g. "ko" */
            nativeLang?: string;
            /** @description completed the onboarding wizard */
            onboarded?: boolean;
            /** @description language being learned, e.g. "en", "de" */
            targetLang?: string;
            /** @description level in TargetLang, e.g. "B1" */
            targetLevel?: string;
            /**
             * @description UILang is the language the SCREENS are drawn in, which is not NativeLang:
             *     NativeLang tells the AI which language to explain corrections in, so a user
             *     who wants an English interface must not thereby get English explanations.
             *     "" means follow NativeLang.
             */
            uiLang?: string;
            userId?: string;
        };
        "github_com_bingoring_forin_server_internal_domain_user.User": {
            createdAt?: string;
            /** @description UUID */
            id?: string;
            status?: string;
        };
        "github_com_bingoring_forin_server_internal_ports.PhonemeResult": {
            accuracy?: number;
            duration?: number;
            offset?: number;
            phoneme?: string;
        };
        "github_com_bingoring_forin_server_internal_ports.SentenceReferenceRow": {
            durationMs?: number;
            ipa?: string;
            locale?: string;
            referenceText?: string;
            sentenceKey?: string;
            words?: components["schemas"]["github_com_bingoring_forin_server_internal_ports.WordScore"][];
        };
        "github_com_bingoring_forin_server_internal_ports.SpeechAttemptRow": {
            accuracy?: number;
            attemptNo?: number;
            completeness?: number;
            createdAt?: string;
            durationMs?: number;
            fluency?: number;
            id?: string;
            overall?: number;
            prosody?: number;
            /** @description false = NULL in storage, i.e. prosody was never scored — see SpeechAttemptInput */
            prosodyAvailable?: boolean;
            recognized?: string;
            words?: components["schemas"]["github_com_bingoring_forin_server_internal_ports.WordScore"][];
        };
        "github_com_bingoring_forin_server_internal_ports.SyllableResult": {
            accuracy?: number;
            duration?: number;
            grapheme?: string;
            offset?: number;
            syllable?: string;
        };
        "github_com_bingoring_forin_server_internal_ports.WordScore": {
            accuracy?: number;
            errorType?: string;
            phonemes?: components["schemas"]["github_com_bingoring_forin_server_internal_ports.PhonemeResult"][];
            syllables?: components["schemas"]["github_com_bingoring_forin_server_internal_ports.SyllableResult"][];
            word?: string;
        };
        "internal_adapters_http.attemptReq": {
            scenarioId?: string;
            score?: number;
        };
        "internal_adapters_http.correctReq": {
            context?: string;
            text?: string;
        };
        "internal_adapters_http.discardResp": {
            discarded?: boolean;
        };
        "internal_adapters_http.economyConfigResp": {
            /** @description weight multiplier for already-cleared */
            dailyClearedWeight?: number;
            /** @description max scenarios per dept in a day's set */
            dailyDeptCap?: number;
            /** @description weight multiplier for off-level difficulty */
            dailyOffBandWeight?: number;
            /** @description Daily situation pool. */
            dailyPoolSize?: number;
            /** @description Spaced repetition (SM-2). */
            easeDefault?: number;
            easeFloor?: number;
            /** @description days, reps 0 → 1 */
            firstInterval?: number;
            /** @description mastery pips ceiling */
            masteryCap?: number;
            pronunciationEnabled?: boolean;
            rankHead?: number;
            /** @description Rank thresholds (level → career title). */
            rankJunior?: number;
            rankSenior?: number;
            /**
             * @description ReadyDestinations are the countries whose authored learning phrases exist, so
             *     the onboarding can offer the rest as intentions rather than as choices. It
             *     rides on this response for the same reason pronunciationEnabled does: the app
             *     fetches it on every launch, before login, and it is a deploy-wide fact.
             */
            readyDestinations?: string[];
            /** @description ≥ → neutral/cordial */
            repBandCordial?: number;
            /** @description ≥ → NPC noticeably warm */
            repBandWarm?: number;
            /** @description ≥ → slightly wary; below → guarded */
            repBandWary?: number;
            /** @description reputation gained by a perfect clear */
            repGainMax?: number;
            /** @description reputation lost by a zero-score attempt */
            repLossMax?: number;
            /** @description Reputation (0..100). */
            reputationDefault?: number;
            /** @description default XP for clearing a scenario */
            scenarioBaseXP?: number;
            /** @description XP floor for a genuine attempt (score>0) */
            scenarioMinXP?: number;
            /**
             * @description Scenario grading (AI-judged completion). A scenario is "cleared" (완료) only
             *     when the graded score ≥ ScenarioPassScore; below that it's an engaged attempt
             *     (재도전) that still earns score-scaled XP + streak but no clear/스티커.
             */
            scenarioPassScore?: number;
            /** @description days, reps 1 → 2 */
            secondInterval?: number;
            /** @description equipped "warm" title nudge */
            titleWarmthBonus?: number;
            /** @description Rewarded-ad top-up. */
            topUpAdd?: number;
            /** @description rewarded top-ups allowed per local day */
            topUpCap?: number;
            /** @description XP for one level (level = 1 + xp/XPPerLevel) */
            xpPerLevel?: number;
        };
        "internal_adapters_http.gate": {
            id?: string;
            locked?: boolean;
            reason?: string;
        };
        "internal_adapters_http.gradeReq": {
            grade?: string;
        };
        "internal_adapters_http.homeColleague": {
            activeToday?: boolean;
            activity?: string;
            id?: string;
            name?: string;
            relation?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_colleague.Relation"];
        };
        "internal_adapters_http.homeResp": {
            colleagueTotal?: number;
            colleagues?: components["schemas"]["internal_adapters_http.homeColleague"][];
            date?: string;
            done?: boolean;
            /**
             * @description FirstRun is true until the learner clears anything. The home screen leads with
             *     the task instead of the streak in that state: a row of ten empty day-boxes is
             *     the first thing a new user would otherwise see, and it teaches nothing.
             */
            firstRun?: boolean;
            level?: number;
            mentorNote?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_home.MentorNote"];
            pendingRequests?: number;
            phrase?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_home.Phrase"];
            review?: components["schemas"]["internal_adapters_http.homeReview"];
            shift?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_home.Shift"];
            situationsWaiting?: number;
            streak?: number;
            targetLevel?: string;
            todayOne?: components["schemas"]["internal_adapters_http.homeTodayOne"];
            unreadCheers?: number;
            /**
             * @description A rolling window ending today (progress.StreakWindowDays long), not a
             *     calendar week. Kept as `week` on the wire so already-shipped clients keep
             *     parsing it; the length is what changed, and the client reads .length.
             */
            week?: number[];
            xp?: number;
        };
        "internal_adapters_http.homeReview": {
            front?: string;
            id?: string;
        };
        "internal_adapters_http.homeTodayOne": {
            chapter?: string;
            kind?: string;
            scenarioId?: string;
            title?: string;
        };
        "internal_adapters_http.loginResp": {
            tokens?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_auth.TokenPair"];
            user?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_user.User"];
        };
        "internal_adapters_http.meResp": {
            profile?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_user.Profile"];
            user?: components["schemas"]["github_com_bingoring_forin_server_internal_domain_user.User"];
        };
        "internal_adapters_http.messageReq": {
            text?: string;
        };
        "internal_adapters_http.phonemeTipDTO": {
            ipa?: string;
            message?: string;
        };
        "internal_adapters_http.pronounceReq": {
            audioBase64?: string;
            /**
             * @description Origin/ScenarioID/ReviewCardID are all optional and new in Task 5 —
             *     existing clients that omit them get origin="freeform", no scenario,
             *     no linked card (business-rules §2, domain-entities §4).
             */
            origin?: string;
            referenceText?: string;
            reviewCardId?: string;
            scenarioId?: string;
        };
        "internal_adapters_http.pronounceResp": {
            accuracy?: number;
            attemptId?: string;
            attemptNo?: number;
            completeness?: number;
            /**
             * @description DurationMS is the recorded audio's length in milliseconds. Azure's
             *     pronunciation-assessment response does not carry this — it is NOT
             *     populated by the azurespeech adapter. The caller computes it from the
             *     WAV it captured (see business-rules R6 / domain-entities SpeechAttempt).
             */
            durationMs?: number;
            fluency?: number;
            overall?: number;
            /**
             * @description PhonemeTips is new in Task 11 — see phonemeTipsFor's doc for the shape
             *     and dedup rationale. omitempty: a scored attempt with no words at all
             *     (or no phoneme with a mapped tip) sends no field rather than `{}`.
             */
            phonemeTips?: {
                [key: string]: components["schemas"]["internal_adapters_http.phonemeTipDTO"];
            };
            /**
             * @description Prosody (억양) only arrives when EnableProsodyAssessment is on AND the
             *     locale supports it. ProsodyOK distinguishes "scored 0" from "not scored" —
             *     rendering an absent score as 0 would tell the learner a falsehood.
             */
            prosody?: number;
            prosodyAvailable?: boolean;
            recognized?: string;
            words?: components["schemas"]["github_com_bingoring_forin_server_internal_ports.WordScore"][];
        };
        "internal_adapters_http.refreshReq": {
            refreshToken?: string;
        };
        "internal_adapters_http.resumableResp": {
            sessionId?: string;
            turns?: components["schemas"]["internal_adapters_http.resumableTurn"][];
        };
        "internal_adapters_http.resumableTurn": {
            content?: string;
            role?: string;
        };
        "internal_adapters_http.socialLoginReq": {
            idToken?: string;
            provider?: string;
        };
        "internal_adapters_http.sttReq": {
            audioBase64?: string;
        };
        "internal_adapters_http.titleReq": {
            titleId?: string;
        };
        "internal_adapters_http.uiLangReq": {
            uiLang?: string;
        };
        "internal_adapters_http.updateProfileReq": {
            destination?: string;
            job?: string;
            nativeLang?: string;
            targetLang?: string;
            targetLevel?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
